### PR TITLE
Paprika: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by emmamarichal**
4eab003: [gftools-packager] Paprika: Version 1.010; ttfautohint (v1.8.3) added

* Paprika Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/etunni/paprika at commit https://github.com/etunni/paprika/commit/ea1b86bd02ae31a0c2b59b87e9dce21e70dd7e38.

### CODE REVIEW

**Comment by emmamarichal** [comment]
Closes #4137

**Comment by emmamarichal** [comment]
Here is the new version, I added the kerning of the API version and the sources that Eduardo sent me.
I just did a PR to him.
[QA Paprika.zip](https://github.com/google/fonts/files/8532519/QA.Paprika.zip)

**Comment by RosaWagner** [comment]
@emmamarichal can you re-do the PR when he merged your PR?

**Comment by emmamarichal** [comment]
Updated

## Paprika: Version 1.010; ttfautohint (v1.8.3) added

---
 a4eb39d: [gftools-packager] Paprika: Version 1.010; ttfautohint (v1.8.3) added

* Paprika Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/etunni/paprika at commit https://github.com/etunni/paprika/commit/4297101a8717fd9ee5795b693f37f3c80bdd3d68.

**Pull request merged**
