### PR TITLE
Noto Sans Oriya: Version 2.001 added

### PR DESCRIPTION
**Pull request by simoncozens**
34323f6: [gftools-packager] Noto Sans Oriya: Version 2.001 added

* Noto Sans Oriya Version 2.001 taken from the upstream repo https://github.com/notofonts/oriya.git at commit https://github.com/notofonts/oriya/commit/.

### CODE REVIEW

**Review by m4rc1e — CHANGES_REQUESTED** [review]
I get different results for the following string:

◌ସ‘୍ହଣ୫ଚ

Screenshot 2022-07-06 at 14 55 34

**Comment by simoncozens** [comment]
Thank you. This is exactly the kind of build weirdness I was worried about. This actually works in the statics:
shape
but not in the variable font:
shape

Looks to be due to hateful rvrn substitutions.

**Comment by simoncozens** [comment]
This will require me to implement the Glyphs "Feature for Feature Variations" custom parameter, what joy.

**Comment by simoncozens** [comment]
I'm going to re-release this with the new toolchain.

**Pull request closed without merging**
