### PR TITLE
Big Shoulders Inline Display: Version 2.000 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
de72971: [gftools-packager] Big Shoulders Inline Display: Version 2.000 added

* Big Shoulders Inline Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 8e57b9c: [gftools-packager] ofl/bigshouldersinlinedisplay remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This PR upgrades [Big Shoulders Inline Display](https://fonts.google.com/specimen/Big+Shoulders+Inline+Display?query=Big) into a `wght` Variable Font.
OFL.txt and Description files were added in #3432

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Inline Display: Version 2.000 added

---
 a558fe6: [gftools-packager] Big Shoulders Inline Display: Version 2.000 added

* Big Shoulders Inline Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 06405bd: [gftools-packager] ofl/bigshouldersinlinedisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Inline Display: Version 2.002 added

---
 3a7f2d6: [gftools-packager] Big Shoulders Inline Display: Version 2.002 added

* Big Shoulders Inline Display Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/c32776c15acba7f76797d45cfeb27d1c2a1738a0.

 85c5ebf: [gftools-packager] ofl/bigshouldersinlinedisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The font includes now the `ExtraLight` Instance.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Inline Display: Version 2.002 added

---
 b2f50c4: [gftools-packager] Big Shoulders Inline Display: Version 2.002 added

* Big Shoulders Inline Display Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/2f924dd1205484c5e0054b1f3955f434224ba72e.

 bddb142: [gftools-packager] ofl/bigshouldersinlinedisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The PR was updated to solve STAT table (with no opsz axis) as mentioned in [#3434](https://github.com/google/fonts/pull/3432#issuecomment-880703015)

**Comment by m4rc1e** [comment]
This looks great!

**Pull request merged**
