### PR TITLE
Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
121fd76: [gftools-packager] Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Micro 5 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-micro at commit https://github.com/scfried/soft-type-micro/commit/b642aae8b850ae551a93623e3c116866de402879.

 d74c9c4: Description and metadatas

 77c8183: metadatas

### CODE REVIEW

**Comment by emmamarichal** [comment]
- 🔥 FAIL: Check font follows the Google Fonts vertical metric schema
- 🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. 
-> Need to be aligned to the charted version (we can't overlap the grid)

- ⚠ WARN: METADATA.pb: Designers are listed correctly on the Google Fonts catalog? 
-> Working on it

- ⚠ WARN: Does GPOS table have kerning information? This check skips monospaced fonts as defined by post.isFixedPitch value 
-> No kerning, to be aligned to the charted version (we can't overlap the grid)

**Comment by vv-monsalve** [comment]
Hi @emmamarichal 

> Need to be aligned to the charted version (we can't overlap the grid)

Please provide more information on this, the vertical metrics look really tight indeed. If this is about "pixel units" Could the font use 2x the current values?
Screen Shot 2023-12-11 at 17 12 33


Perhaps now would be a good time to include the new OFL location #7062

**Comment by emmamarichal** [comment]
@vv-monsalve I thought it would be nice if we had the same v-metrics as https://github.com/google/fonts/pull/7082 (Micro Charted). And in Micro Charted, I can't do the usual calculation UPM*1,2, since we don't want overlaps with the grid.

And for OFL, I'll can indeed update it, thanks! :)

**Comment by vv-monsalve** [comment]
> (Micro Charted). And in Micro Charted, I can't do the usual calculation UPM*1,2, since we don't want overlaps with the grid.

Ah, the Charted sibling family. I've added a comment in that font regarding the vertical metrics.
These projects could benefit from finding different grid-pixel units to accommodate better the diacritics, increasing the potential of use and upgrade (e.g. to more language support in the future)

**Comment by emmamarichal** [comment]
Updated

## Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

---
 fd6db39: [gftools-packager] Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Micro 5 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-micro at commit https://github.com/scfried/soft-type-micro/commit/032a7f1329bd7c2bb30aa727a8c48e84c780f41d.

 ed4acdf: description and metadatas

**Comment by emmamarichal** [comment]
@vv-monsalve, updated! 😀

**Comment by emmamarichal** [comment]
Updated

## Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

---
 fb3ccaf: [gftools-packager] Micro 5: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Micro 5 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-micro at commit https://github.com/scfried/soft-type-micro/commit/e8450033cd07542081f72abd540b93574434bc71.

 02505d0: description and metadatas updated

**Comment by emmamarichal** [comment]
Does DESCRIPTION file contain broken links? ([com.google.fonts/check/description/broken_links](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/broken_links))

-> I linked the charted version, not released yet

**Comment by vv-monsalve** [comment]
I updated the Description file to include the clarification sentence we discussed about the number in the font name.

**Pull request merged**
