### PR TITLE
inconsolata: v2.001 Regular and v2.001 Bold

### PR DESCRIPTION
**Pull request by emabrey**
Add version 2.001 of the Inconsolata-Regular and the Inconsolata-Bold fonts. The fonts have had minor metadata fixes and the font hinting has been improved via usage of ttfautohint 1.6 (an upgrade from the previous version 1.3).

I've already signed the CLA, but if I need to do anything else please let me know.

### CODE REVIEW

**Comment by davelab6** [comment]
@emabrey awesome! Thanks for contributing! :) @alexeiva is this the latest version? @m4rc1e please review :)

**Comment by m4rc1e** [comment]
Hey @emabrey @davelab6,

Thank you for your pr. I'm incredibly grateful to see it, we usually end up dealing with the +1 crew :-).

I'll chat to @alexeiva about the state of our source repo. Ideally, we'd like this to be applied at source and not hot fixed on the current binary.

I will have an answer very soon.

Marc

**Comment by m4rc1e** [comment]
Hey @emabrey,

Could you do this at the source [repo](https://github.com/cyrealtype/Inconsolata). Ideally, you'd have the ttfautohint command in a shell script entitled build.sh.

**Comment by emabrey** [comment]
Can someone give me a little guidance on what program opens these `.glyphs` and `.vfb` files? They are the only source files provided within the linked repo and I can't figure out how to use them. Fontforge doesn't recognize them and some googling hasn't been helpful. Should I just replace the contents of the source repos `fonts` directory directly?

**Comment by davelab6** [comment]
> Can someone give me a little guidance on what program opens these .glyphs and .vfb files? 

`.glyphs` is www.glyphsapp.com and `.vfb` is www.fontlab.com

However, https://github.com/googlei18n/fontmake/ and its underlying libraries can also parse `.glyphs` files, and fontmake can compile them. 

It might be good to move Inconsolata to being built by fontmaker instead of Glyphs itself. 

All editors support the `.ufo` format (including FontForge, Metapolator, RoboFont, and especially - Trufont! Which I have switched my focus to in the last year or so, although the recent development has been done single handedly by @adrientetar in private...) 

However, almost all professional font designers use the GlyphsApp these days, so most Google Fonts project sources are migrating to that editor's source format as the preferred form of modification. 

I expect that TruFont will eventually support this format too. 

> They are the only source files provided within the linked repo and I can't figure out how to use them. Fontforge doesn't recognize them and some googling hasn't been helpful. Should I just replace the contents of the source repos fonts directory directly?

Sadly to make upstream edits you'll need OS X and Glyphs

**Comment by davelab6** [comment]
@m4rc1e since this has gone on for a month can you just QA these files to ensure no regressions and assign to me to push? and we can deal with upstream purity later

**Comment by m4rc1e** [comment]
We had issue #611 which Alexei has fixed. However, we also had this issue with glyphsapp which has now been fixed, https://forum.glyphsapp.com/t/instance-customparameters-scale-to-upm-outputs-2-000-instead-of-2-048/5887. 

Alexei has implemented his fixes so I need to upload his version. I will also apply @emabrey improvements.

**Comment by alexeiva** [comment]
@m4rc1e There will be more inbetween weights of Inco once they pass your shape orders test: https://github.com/cyrealtype/Inconsolata/issues/6

**Comment by davelab6** [comment]
Closing as v3 was published already

**Pull request closed without merging**
