### PR TITLE
Add designer: JAMO

### PR DESCRIPTION
**Pull request by emmamarichal**
Manual entry on the designers spreadsheet (I don't know by whom), no image, no website.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
It seems he is one of the designers for Orbit font.
@aaronbell, could you confirm this?

**Comment by aaronbell** [comment]
`JAMO` is the name of the organization that is releasing the fonts. They provided oversight and review / critique of the designer's work. At current they're not listed as the designer in the repro, but for the sake of keeping all of the JAMO fonts together, it is probably worth adding.

**Comment by vv-monsalve** [comment]
This is what is shown for [JAMO](https://fonts.google.com/?query=JAMO). Do you mean all of them?

**Comment by aaronbell** [comment]
Yes. All of them.

**Pull request merged**
