### PR TITLE
Noto Sans Egyptian Hieroglyphs: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/egyptian-hieroglyphs at commit https://github.com/notofonts/egyptian-hieroglyphs/commit/08dec90190624040743ebb4e28d5552ae3d60862.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
```
Noto Sans Egyptian Hieroglyphs v2.002

This release adds support for various codepoints added in Unicode 14.
Thanks to @mercury13 (drawing) and @dwerning (consultancy).
```

**Comment by vv-monsalve** [comment]
@simoncozens Diffenator is reporting modified but not new glyphs.
Is this ok?

NotoSansEgyptianHieroglyphs

**Comment by simoncozens** [comment]
Could be a diffenator2 problem here - the new font has U+13446 for example and the existing font does not.

**Comment by simoncozens** [comment]
Here's what I see with `gftools-qa -gfb --diffenator -pr https://github.com/google/fonts/pull/7556`

Screenshot 2024-04-18 at 08 29 44

**Comment by simoncozens** [comment]
Actually that's what I see in the GitHub action run [here](https://github.com/google/fonts/actions/runs/8687223774) too.

**Comment by vv-monsalve** [comment]
> Actually that's what I see in the GitHub action run [here](https://github.com/google/fonts/actions/runs/8687223774) too.

Right. Short list, but there. Given the bigger group of reported cases were modified ones, I was unsure how to proceed. I'll merge this here

**Pull request merged**
