### PR TITLE
Nabla: Version 1.002 added

### PR DESCRIPTION
**Pull request by m4rc1e**
3345df7: [gftools-packager] Nabla: Version 1.002 added

* Nabla Version 1.002 taken from the upstream repo https://github.com/justvanrossum/nabla at commit https://github.com/justvanrossum/nabla/commit/.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Will run maximum_color on this one.

**Comment by chrissimpkins** [comment]
> If Nabla contains a colored .notdef glyph it might be affected by this maximum_color bug [googlefonts/nanoemoji#427](https://github.com/googlefonts/nanoemoji/issues/427)
> 
> I am working on a fix, see the linked PR

@justvanrossum

**Comment by chrissimpkins** [comment]
@m4rc1e I think that this needs to be rebased on the changes at or following 2ec9ec2b67be549b767eb5e1b8177869a731998c.  CI is failing on the old axisregistry path format

**Comment by justvanrossum** [comment]
When I run fontbakery I only get one FAIL: `com.google.fonts/check/STAT`, and I don't know what it means. I asked a question about it, but didn't get a response: https://github.com/googlefonts/fontbakery/discussions/3885 It may be a false positive.

How do you invoke fontbakery to get the additional FAILs? I just do `fontbakery check-googlefonts fonts/*.ttf`

I also don't understand the `com.google.fonts/check/whitespace_glyphs)` FAIL, because the font does contain U+00A0, as `uni00A0`.

**Comment by justvanrossum** [comment]
> If Nabla contains a colored .notdef glyph it might be affected by this maximum_color bug https://github.com/googlefonts/nanoemoji/issues/427

It does, as ov v1.002.

**Comment by m4rc1e** [comment]
> How do you invoke fontbakery to get the additional FAILs? I just do fontbakery check-googlefonts fonts/*.ttf

We have additional checks which are only executed when you run fontbakery on a family in this repo. Most of these checks are to ensure that the font will be correctly onboarded so it checks the metadata files, license etc.

**Comment by anthrotype** [comment]
I just released https://github.com/googlefonts/nanoemoji/releases/tag/v0.14.2 with a fix for the colored .notdef being reshuffled. Please use that going forward, thanks

**Comment by anthrotype** [comment]
actually, hold on the horses, I found another bug whil maximum_color'ing Nabla 1.002, will let you know in a bit, sorry.

**Comment by anthrotype** [comment]
I fixed the bug in https://github.com/googlefonts/nanoemoji/releases/tag/v0.14.3, and tested with Nabla locally, it now keeps the .notdef glyph in first position as expected. Please revert https://github.com/google/fonts/pull/5160/commits/15e9ce11b77998a0ef65c46ec3a8dc86af24180e then re-run the latest maximum_color tool from nanoemoji==0.14.3 - thanks!

**Comment by m4rc1e** [comment]
@rsheeter still needs maximum_color. Will run it tomorrow.

**Comment by rsheeter** [comment]
Is that the only thing needed?

**Pull request merged**
