### PR TITLE
Jacquard 24: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
d4c5e58: [gftools-packager] Jacquard 24: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Jacquard 24 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-jacquard at commit https://github.com/scfried/soft-type-jacquard/commit/9c5c14889fd148d385536658cc2d320be294f32d.

 2ee6615: Description and metadatas

### CODE REVIEW

**Comment by emmamarichal** [comment]
@m4rc1e 
🔥 FAIL: Font contains '.notdef' as its first glyph?

I think we ignored it for the other style, let me know we do you think about it!

**Review by m4rc1e — CHANGES_REQUESTED** [review]
@emmamarichal MS suggests not having an empty .notdef, https://learn.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph


Jacquard 12 does have a filled notdef:


Screenshot 2024-02-22 at 16 52 28

Due to the 12 family having one, I think we should add it.

**Comment by vv-monsalve** [comment]
Agree. This glyph must be the first one and have an outline in all the fonts, which is why it is a Fail :)

@emmamarichal have you added it to the font yet?

**Comment by emmamarichal** [comment]
Updated

## Jacquard 24: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

---
 9a81090: [gftools-packager] Jacquard 24: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Jacquard 24 Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-jacquard at commit https://github.com/scfried/soft-type-jacquard/commit/0ef57f102270194f4e41ce609ad5888f14983b8e.

 4960272: update

**Comment by emmamarichal** [comment]
@m4rc1e updated!

**Review by m4rc1e — APPROVED** [review]

**Pull request merged**
