### PR TITLE
arakatana : bio added

### PR DESCRIPTION
**Pull request by mintoming**
catalog/designers/arakatana

### CODE REVIEW

**Comment by mintoming** [comment]
Hi @m4rc1e , could you help me on this? Don't understand why it's a fail 🥲

**Comment by davelab6** [comment]
`arakatana/info.pb` had a typo in the filename of the PNG file, I corrected it.

**Comment by davelab6** [comment]
Ah, @mintoming, actually, I see the twitter handle is "ARTAKANA" (art-a-kana) so I guess the directory name, image filename, and filename listed in the info file, all need to change. Please triple check this one :)

**Review by davelab6 — CHANGES_REQUESTED** [review]
Ah, @mintoming, actually, I see the twitter handle is "ARTAKANA" (art-a-kana) so I guess the directory name, image filename, and filename listed in the info file, all need to change. Please triple check this one :)

**Comment by mintoming** [comment]
Sorry @davelab6 I didn't see this!
Ha, I checked his email and sent us the info with the typo...😂
I'll go ahead and update👍

**Comment by RosaWagner** [comment]
fixed in #3614

**Pull request closed without merging**
