### PR TITLE
Update cabin and cabincondensed to Version 2.000

### PR DESCRIPTION
**Pull request by graphicore**

### CODE REVIEW

**Comment by graphicore** [comment]
@m4rc1e: Is this still the latest version or will you make a new PR?

**Comment by davelab6** [comment]
Assigning to @m4rc1e to comment/resolve

**Comment by m4rc1e** [comment]
@impallari, I see you've made some improvements to your source repo, https://github.com/impallari/Cabin.

Are you happy for us to release from the source?

**Comment by impallari** [comment]
Yep

**Comment by m4rc1e** [comment]
Fantastic!

I will do this today.

Cheers,
Marc

**Pull request closed without merging**
