### PR TITLE
Aref Ruqaa Ink: Version 1.005 added

### PR DESCRIPTION
**Pull request by yanone**
db4ad6d: [gftools-packager] Aref Ruqaa Ink: Version 1.005 added

* Aref Ruqaa Ink Version 1.005 taken from the upstream repo https://github.com/aliftype/aref-ruqaa at commit https://github.com/aliftype/aref-ruqaa/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
posting that to confirm to @m4rc1e that the QA tool is now effectively displaying colors :)

Capture d’écran 2022-05-11 à 16 55 18

**Comment by m4rc1e** [comment]
Any reason why we've blocked this family?

**Comment by vv-monsalve** [comment]
> The Reserved Font Name issue is out of his control because it references a name that the Latin is based on. It's not an issue with the actual font name.
> And finally, I have no idea what the METADATA.pb fail is related to.

Probably some of the reported fails: RFN or Metadata?

**Comment by davelab6** [comment]
The OFL issues are ok.

**Comment by vv-monsalve** [comment]
Color font. So it's not supposed to reach production yet

**Pull request merged**
