### PR TITLE
Gf2016 fix

### PR DESCRIPTION
**Pull request by alexeiva**
- Added Glyphs List Filter Troubleshooting Guide
- Added List of Vietnamese unique glyphs

Changes to encodings:
**Plus:**
 * removed germanbls.alt to recommended 
 * removed CR, and NULL 

**Pro set:**
 * added emptyspace

### CODE REVIEW

**Comment by alexeiva** [comment]
@kalapi I have merged #313, thank you.
I need to fix #306 (Vietnamese), and after that you can merge my branch to master.

I plan some more updates on my branch later:
— add drawn/composite table for Cyrillic
— add CustomFilter.plist with all Google List Filters.

**Comment by alexeiva** [comment]
@googlebot I confirm that these commits were authored by me. The email registered with Google is the same as the one configured in my Git config.

**Comment by kalapi** [comment]
@alexeiva I wonder why it's still complaining about a merge conflict. I checked out the remote branch once more and there seems to be no conflict! Maybe i'm doing something wrong.

**Comment by davelab6** [comment]
To fix this, I checked out master, then branched, then cherry picked the commits by ID, and the first one (6c99c09) had conflicts, which I fixed in branch davelab6-GF2016-fix, so I'm closing this PR for #315

**Comment by alexeiva** [comment]
thanks, @davelab6!

**Pull request closed without merging**
