### PR TITLE
Mplus fix2

### PR DESCRIPTION
**Pull request by vv-monsalve**
This PR is intended to fix MPLUS1p issue as defined in the last comment in [#4962](https://github.com/google/fonts/issues/4952#issuecomment-1191780820).

It includes:

- Font binaries Uppercase filenames, e.g. `MPLUS1p-Regular.ttf`
- File names fixed in METADATA following the above, e.g.:
```
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 400
  filename: "MPLUS1p-Regular.ttf"
  post_script_name: "MPLUS1p-Regular"
  full_name: "M PLUS 1p"
  copyright: "Copyright 2016 The M+ Project Authors."
}
```
- Name table on each font was adjusted accordingly
Screen Shot 2022-07-21 at 18 36 16

### CODE REVIEW

**Review by chrissimpkins — APPROVED** [review]
LGTM.  Thank you very much Viv!

**Comment by chrissimpkins** [comment]
The CI failed on a Browserstack credentials error.  I triggered a re-run of the failed job. Let's see if it completes successfully.

**Review by chrissimpkins — CHANGES_REQUESTED** [review]
Hmm.  Seems to be a browserstack issue.  We'll need to investigate

**Comment by RosaWagner** [comment]
Version number should be bumped up to avoid confusion

**Comment by vv-monsalve** [comment]
> Version number should be bumped up to avoid confusion

Bumped to 1.062

**Comment by vv-monsalve** [comment]
Last commit created a mess instead of solving it. Closing this hear and will create a new one.

**Pull request closed without merging**
