### PR TITLE
Noto Sans Balinese: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
d4d18da: [gftools-packager] Noto Sans Balinese: Version 2.003 added

* Noto Sans Balinese Version 2.003 taken from the upstream repo https://github.com/notofonts/balinese.git at commit https://github.com/notofonts/balinese/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: Does the font have any invalid language tags? ([com.google.fonts/check/layout_valid_language_tags](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/layout.html#com.google.fonts/check/layout_valid_language_tags))
> 🔥 FAIL The following invalid language tags were found in the font: KAW [code: bad-language-tags]

Is this ok?

**Comment by vv-monsalve** [comment]
There is something strange with the text preview. I've re-run the tests and the issue persists.

Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
KAW is a valid tag for Kawi (Old Javanese). I need to update the tag registry Python module that FB is checking.

**Comment by vv-monsalve** [comment]
> There is something strange with the text preview. I've re-run the tests and the issue persists.

Running the diff test locally there is the same empty result. When using only the current font the text displayed doesn't include Balinese.
@m4rc1e what could be the situation?
Desktop_Windows_10_chrome_71 0_

**Comment by vv-monsalve** [comment]
Glyph diff is working though. @simoncozens could you confirm ᬸ is ok?

Chrome-cut

**Comment by simoncozens** [comment]
No, not OK - but only for the dotted circle glyph, I think. Will fix it. Closing this PR for re-release.

**Pull request closed without merging**
