### PR TITLE
hotfix-yatraone: v1.002 added

### PR DESCRIPTION
**Pull request by m4rc1e**
@davelab6 the license txt files come directly from the zips on fonts.google.com :-). This isn't me hand editing them.

### CODE REVIEW

**Comment by davelab6** [comment]
> @davelab6 the license txt files come directly from the zips on fonts.google.com :-). This isn't me hand editing them.

That may be true, but all in this repo (eg https://github.com/google/fonts/blob/master/ofl/abeezee/OFL.txt)  have the linebreak

**Comment by chezsick** [comment]
thanks! my prefered font

**Comment by davelab6** [comment]
@m4rc1e there might be a bug in your script as https://fonts.google.com/specimen/Yatra+One is definitely has Devanagari enabled but this PR missed it :)

**Comment by m4rc1e** [comment]
Hey @davelab6 the codepoints for the missing repos were calculated by add_font.py. Here's the output after running it:

```
name: "Yatra One"
designer: "Unknown"
license: "OFL"
category: "SANS_SERIF"
date_added: "2017-05-25"
fonts {
  name: "Yatra One"
  style: "normal"
  weight: 400
  filename: "YatraOne-Regular.ttf"
  post_script_name: "YatraOne-Regular"
  full_name: "Yatra One Regular"
  copyright: "Copyright 2014 The Yatra Project Authors."
}
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
```

I am able to steal the codepoints from the api if you prefer?

**Comment by davelab6** [comment]
> I am able to use the subset info from the api instead if you prefer?

That will be safer, but I wonder why `add_font.py` doesn't detect the Devanagari in this font...

**Pull request merged**
