### PR TITLE
MonteCarlo: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
7bbcc23: [gftools-packager] MonteCarlo: Version 1.010; ttfautohint (v1.8.3) added

* MonteCarlo Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/monte-carlo at commit https://github.com/googlefonts/monte-carlo/commit/1087ae0a2c3abc7c12cc53e1f930a2336e9241fd.

 0f7d9f0: [gftools-packager] ofl/montecarlo remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: METADATA.pb: Check if fontname is not camel cased.
> 🔥 FAIL: Check name table: FONTFAMILYNAME entries.
> 🔥 FAIL: Check name table: FULLFONTNAME entries.

This is related to this [issue](https://github.com/googlefonts/fontbakery/issues/3270) and a [PR](https://github.com/googlefonts/fontbakery/pull/3286) was done to FB to solve it

> 🔥 FAIL: Ensure Stylistic Sets have description.

Related to this [issue](https://github.com/googlefonts/fontbakery/issues/3155#issuecomment-839683110)

**Comment by m4rc1e** [comment]
Any particular reason for the largish vertical metrics?

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by vv-monsalve** [comment]
Updated

## MonteCarlo: Version 1.010; ttfautohint (v1.8.3) added

---
 1b703b2: [gftools-packager] MonteCarlo: Version 1.010; ttfautohint (v1.8.3) added

* MonteCarlo Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/monte-carlo at commit https://github.com/googlefonts/monte-carlo/commit/62962590ae6b6dea67788c485d38217abe196e1b.

 a8b3ea8: [gftools-packager] ofl/montecarlo remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> Any particular reason for the largish vertical metrics?

No. I updated the PR.

**Pull request merged**
