### PR TITLE
Added digitalnumbers font including the mentioned fixes:

### PR DESCRIPTION
**Pull request by s-a**
- Support Basic Latin Alphabet
 - SIL Open Font License v1.1 with no Reserved Font Name
 - Complete Corresponding Source + Build instructions/scripts

### CODE REVIEW

**Comment by davelab6** [comment]
Woohoo! You did it :) This looks good but there's a few more things to fix. You can leave this pull request open, commit a fixed font file, and git rebase to squash the commits into 1, or if that's too much git gymnastics, close and make a new PR later when we're ready :)

**Comment by s-a** [comment]
@davelab6 Hope this is ready now :) 
If this works ... Are there any brand images available like these here https://developers.google.com/drive/web/branding? I ' like to link from my repo to pose there that this is cool ^^

**Comment by s-a** [comment]
Forgot ```git rebase``` squash and did this now. Hope this works.

**Comment by s-a** [comment]
Hello @davelab6 do I miss something here? Or is it ready to merge?

**Pull request closed without merging**
