### PR TITLE
Zen Kaku Gothic Antique: Version 1.002 added; Zen Kaku Gothic New: Version 1.002 added

### PR DESCRIPTION
**Pull request by aaronbell**
314bbc9: [gftools-packager] Zen Kaku Gothic Antique: Version 1.002 added

* Zen Kaku Gothic Antique Version 1.002 taken from the upstream repo https://github.com/googlefonts/zen-kakugothic.git at commit https://github.com/googlefonts/zen-kakugothic/commit/81443c39f8364063b747f2f1af778969d60acee8.

 c5ea0e7: [gftools-packager] ofl/zenkakugothicantique remove METADATA "source".  google/fonts#2587

 f9aaf3d: [gftools-packager] Zen Kaku Gothic New: Version 1.002 added

* Zen Kaku Gothic New Version 1.002 taken from the upstream repo https://github.com/googlefonts/zen-kakugothic.git at commit https://github.com/googlefonts/zen-kakugothic/commit/81443c39f8364063b747f2f1af778969d60acee8.

 89922d7: [gftools-packager] ofl/zenkakugothicnew remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by aaronbell** [comment]
Alright, I think I got all of this ready to go. It seems there's some language options that have been added that the packager didn't add and I'm not totally sure about them, so thought I'd call it out.

**Comment by aaronbell** [comment]
The issue here is due to how GlyphsLib processes Glyphs files. If no glyphs are assigned a vertical height value (even if the vertical height value needs to be the default of 1000), GlyphsLib will not automatically assign a vertical value in the vmtx table. In this case, the "shared" glyphs file had an added 1000 height assigned, but the kana files did not. As a result, the kana had a set height of 0 rather than 1000. 

This has been corrected.

**Comment by m4rc1e** [comment]
Language info seems to have been ripped out of the METDATA.pb files. I'll need to make some changes to gftools so this doesn't happen. Let's block this for now.

**Comment by aaronbell** [comment]
I’d rather not block a fix to broken functionality due to a metadata issue. Would it be OK if I manually updated the languages in this case rather than wait for a tooling fix?

**Comment by m4rc1e** [comment]
Sounds fine to me on this occasion but please don't PR any family updates until the tooling is fixed. Hopefully, I'll have it done this week.

**Comment by aaronbell** [comment]
Updated the metadata. Thanks!

**Comment by aaronbell** [comment]
@m4rc1e has this been pushed live as of yet? Per the label it looks like it is still in sandbox.

**Comment by RosaWagner** [comment]
Apparently you guys forgot to add the PR to Traffic Jam project, don’t expect much happening if it’s not in positioned to be tracked :)

**Comment by aaronbell** [comment]
Thanks @RosaWagner. That explains it :)

**Pull request merged**
