### PR TITLE
Noto Serif Hebrew: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
2268a64: [gftools-packager] Noto Serif Hebrew: Version 2.003 added

* Noto Serif Hebrew Version 2.003 taken from the upstream repo https://github.com/notofonts/hebrew.git at commit https://github.com/notofonts/hebrew/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens could you confirm the marks position are as intended?
marks_modified

marks_new

Desktop_Windows_10_chrome_71 0-CUT

**Comment by simoncozens** [comment]
These are a mess. :-/

**Comment by simoncozens** [comment]
No, I am confusing my before/after. These positions are much nicer! The only mark which looks strange is SHIN DOT but that should only be used with SHIN anyway.

**Comment by RosaWagner** [comment]
No latin, waiting for confirmation to see if it's okay.
Missing codepoint for specimen page. 

Capture d’écran 2022-07-21 à 11 24 21

**Comment by simoncozens** [comment]
Looks like there is a Latin:

```
$ shape ofl/notoserifhebrew/NotoSerifHebrew\[wdth,wght\].ttf  'ABC'
[A=0+705|B=1+654|C=2+614]
```
shape

And that specimen page doesn't look like Serif Hebrew to me?

**Comment by RosaWagner** [comment]
Arg I commented in the wrong PR, it was for Noto SANS Hebrew

**Comment by RosaWagner** [comment]
Ah I actually reviewed the wrong font since Noto Sans Hebrew is not even merged yet. Okay ignore my comment.

**Pull request merged**
