### PR TITLE
Noto Serif Kannada: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
068a24a: [gftools-packager] Noto Serif Kannada: Version 2.003 added

* Noto Serif Kannada Version 2.003 taken from the upstream repo https://github.com/notofonts/kannada.git at commit https://github.com/notofonts/kannada/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Hi @simoncozens, ಁ is looking off in Safari Sierra and Chrome windows.
Desktop_Windows_10_chrome_71 0-cut

**Comment by simoncozens** [comment]
This is notofonts/kannada#12. I am happy with the placement.

**Comment by RosaWagner** [comment]
This is the third Noto font I check in sandbox that has no article/description. The about section is now empty in sandbox. Lisu, Kannada and Devanagari so far. The previous merged CJK fonts seem intact. @simoncozens is it part of the plan ?

**Comment by simoncozens** [comment]
I don't understand. I don't want to remove the descriptions; the description file is still there and fontbakery is not complaining about it.

**Pull request merged**
