### PR TITLE
REM: Version 1.004;gftools[0.9.28] added

### PR DESCRIPTION
**Pull request by vv-monsalve**
43286b9: [gftools-packager] REM: Version 1.004;gftools[0.9.28] added

* REM Version 1.004;gftools[0.9.28] taken from the upstream repo https://github.com/octaviopardo/REM at commit https://github.com/octaviopardo/REM/commit/bd1ba614dc0495c265ab015907ca24784718e9bb.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: Check family name for GF Guide compliance. ([com.google.fonts/check/name/family_name_compliance](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/family_name_compliance))
🔥 FAIL "REM" contains an abbreviation. [code: abbreviation]

Already added to the [exception list](https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/data/googlefonts/abbreviations_familyname_exceptions.txt)

**Comment by vv-monsalve** [comment]
Updated

## REM: Version 1.005;gftools[0.9.28] added

---
 02cff60: [gftools-packager] REM: Version 1.005;gftools[0.9.28] added

* REM Version 1.005;gftools[0.9.28] taken from the upstream repo https://github.com/octaviopardo/REM at commit https://github.com/octaviopardo/REM/commit/75b5f1c2d565291703a2498eb73fea9719ba343d.

**Comment by vv-monsalve** [comment]
@RosaWagner updated with Medium

**Comment by RosaWagner** [comment]
@vv-monsalve just found an issue with Ldot
Capture d’écran 2023-05-03 à 17 55 23
Capture d’écran 2023-05-03 à 17 55 15

**Comment by vv-monsalve** [comment]
Oh Lord. I'll check them and update the PR.

> Practical this proofer!

Practical indeed. Is it diff2 proof option?

**Comment by vv-monsalve** [comment]
Updated

## REM: Version 1.005;gftools[0.9.28] added

---
 31823ee: [gftools-packager] REM: Version 1.005;gftools[0.9.28] added

* REM Version 1.005;gftools[0.9.28] taken from the upstream repo https://github.com/octaviopardo/REM at commit https://github.com/octaviopardo/REM/commit/b26d584ebdb3d8084355205d22c87e4e99658d56.

**Pull request merged**
