### PR TITLE
Jacquard 24 Charted: Version 1.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
cdcc1fa: [gftools-packager] Jacquard 24 Charted: Version 1.000 added

* Jacquard 24 Charted Version 1.000 taken from the upstream repo https://github.com/scfried/soft-type-jacquard at commit https://github.com/scfried/soft-type-jacquard/commit/9c5c14889fd148d385536658cc2d320be294f32d.

 ae7faac: description and metadata updated

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: Font enables smart dropout control in "prep" table instructions? ([com.google.fonts/check/smart_dropout](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/Font%20File%20Checks.html#com.google.fonts/check/smart_dropout))

I'm wondering why the builder didn't add this fixing step.

**Comment by vv-monsalve** [comment]
Following the [`.notdef` revision in Jacquard 24](https://github.com/google/fonts/pull/7305#pullrequestreview-1896369295) the outlines included in this font are not spec compliant and will create confusion between an actual missing glyph and the `space` character.

You would like to include here the same outlines that get defined in Jacquard24 

Screen Shot 2024-03-06 at 18 18 46

**Comment by emmamarichal** [comment]
@m4rc1e updated!

**Comment by emmamarichal** [comment]
Blocked in sandbox: there is a notdef outlines in the space: 

Screenshot 2024-03-29 at 13 51 04

**Pull request merged**
