### PR TITLE
Gulzar: Version 1.001;[0cc0313]; ttfautohint (v1.8.4) added

### PR DESCRIPTION
**Pull request by simoncozens**
8576c46: [gftools-packager] Gulzar: Version 1.001;[0cc0313]; ttfautohint (v1.8.4) added

* Gulzar Version 1.001;[0cc0313]; ttfautohint (v1.8.4) taken from the upstream repo https://github.com/simoncozens/Gulzar at commit https://github.com/simoncozens/Gulzar/commit/229b53b8941dfac262f24f2ef3b06b9832e12763.

### CODE REVIEW

**Comment by simoncozens** [comment]
This upgrade improves spacing and kerning, and will cause reflow. However, it is a big improvement on the previous spacing.

**Comment by chrissimpkins** [comment]
@simoncozens status?

**Comment by chrissimpkins** [comment]
Requires review of Latin kerning

**Comment by RosaWagner** [comment]
Designer wants to do more changes and this PR has conflict so closing this.

**Pull request closed without merging**
