### PR TITLE
Afacad Flux: Version 1.100; Development; Release 1; Build 8 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/Dicotype/Afacad at commit https://github.com/Dicotype/Afacad/commit/7582e0c3d903ab23b02d4735bb2b9c759bc1f2bc.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [x] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [x] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [x] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
It's not really a new font, but another version of https://fonts.google.com/specimen/Afacad (there is a backslant in that version)

**Comment by vv-monsalve** [comment]
@emmamarichal, the weight axis shows a strange behavior that the Afacad font doesn't have. It seems like a spacing change.

#### Afacad Flux
https://github.com/google/fonts/assets/48698976/5a462658-a7f8-4373-baa3-9b48e6aa2344

#### Afacad
https://github.com/google/fonts/assets/48698976/39725287-f990-43ef-b8ae-f14b373e1102

**Comment by vv-monsalve** [comment]
> 🔥 FAIL STAT table has Axis Value tables?

Please include the STAT table info for the -14 position. 

> 🔥 FAIL METADATA.pb: Check URL on copyright string is the same as in repository_url field.

It seems to be a typo in the repo URL "Afacade" is having an extra 'e'

> 🔥 FAIL Copyright field for this font on METADATA.pb matches all copyright notice entries on the name table ?

There is a mismatch in the strings and the typo is also present here

**Comment by emmamarichal** [comment]
Thanks @vv-monsalve! Will check that today

**Comment by emmamarichal** [comment]
I corrected the urls issues, I will update that PR, but I wanted your confirmation about the Stat table.


Here is the corrected STAT:
```
sources:
  - AfacadFlux.glyphs
familyName: Afacad Flux
axisOrder:
  - slnt
  - wght
stat:
  AfacadFlux[slnt,wght].ttf:
  - name: Slant
    tag: slnt
    values:
    - name: Backslant
      value: 14
    - name: Default
      value: 0
      flags: 2
    - name: Italic
      value: -14
  - name: Weight
    tag: wght
    values:
    - name: Thin
      value: 100
    - name: ExtraLight
      value: 200
    - name: Light
      value: 300
    - name: Regular
      value: 400
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: Black
      value: 900
    - name: ExtraBlack
      value: 1000
outputDir: "../fonts/Afacad_Flux"
buildTTF: true
buildOTF: false
# autohintTTF: false
```
**BUT**

Now I have these fails:

Screenshot 2024-05-10 at 09 55 41


The first stat I wrote, I took example on several fonts with a slnt axis, and the slant values are not precised. That why I wrote first this: 

  ```
AfacadFlux[slnt,wght].ttf:
  - name: Slant
    tag: slnt
    values:
    - name: Default
      value: 0
      flags: 2
```

Let me know what you think! I'll then send a PR to the designer with the corrections. :)

**Comment by vv-monsalve** [comment]
When using the `slnt` axis to provide italic instances in the `fvar`, we'll need to ignore the first reported Fail, and the STAT table needs to match the Italic in the fvar. See [FB#4215](https://github.com/fonttools/fontbakery/pull/4215).

For all the axes registered without fallback instances (that is, `slnt` and all the newer custom ones), FB will complain about the STAT because it is using the axis registry to validate them. However, we have allowed STAT-named instances in these cases.

Otoh, there are some interpolation issues reported that you may want to check. e.g.

Screen Shot 2024-05-10 at 12 28 07

**Comment by emmamarichal** [comment]
thank you @vv-monsalve, I'll correct that asap! Will let you know

**Comment by emmamarichal** [comment]
@vv-monsalve I close this one, there were a bug with the packager, I'll open a new one

**Pull request closed without merging**
