### PR TITLE
Noto Sans Khojki: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
27491a7: [gftools-packager] Noto Sans Khojki: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Khojki Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/khojki.git at commit https://github.com/notofonts/khojki/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
Is this okay ?

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by simoncozens** [comment]
New release coming.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Khojki: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

---
 6cf4b0f: [gftools-packager] Noto Sans Khojki: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Khojki Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/khojki.git at commit https://github.com/notofonts/khojki/commit/.

**Comment by RosaWagner** [comment]
@simoncozens 

glyphs_missing

**Comment by simoncozens** [comment]
There is a bug here but I will fix it in another release. I don't think this should stop the onboarding - that mark combination would be formed a different way.

**Pull request merged**
