### PR TITLE
Titillium Web: v3.000 added

### PR DESCRIPTION
**Pull request by eliheuer**
Taken from the upstream repo: https://github.com/eliheuer/titillium-web-vf
At commit: https://github.com/eliheuer/titillium-web-vf/commit/79ca7466dc7e611184905b6a6f6617d3d67f6e69

### CODE REVIEW

**Comment by eliheuer** [comment]
This PR has been updated to use the new VF naming spec as was discussed here: https://github.com/google/fonts/issues/1817

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.9

<details>
<summary><b>[3] TitilliumWeb[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWeightClass.</summary>

* [com.google.fonts/check/usweightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/usweightclass)
* 🔥 **FAIL** OS/2 usWeightClass expected value for 'ExtraLight' is 275 but this font has 400.
 GlyphsApp users should set a Custom Parameter for 'Axis Location' in each master to ensure that the information is accurately built into variable fonts.

</details>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
* ⚠ **WARN** ttfautohint used in font = 1.8.2; installed = 1.8.3; Need to re-run with the newer version!

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 1 | 2 | 74 | 6 | 76 |
| 0% | 1% | 1% | 47% | 4% | 48% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**


## Diff images: [titillium_qa.zip](http://35.188.158.120/media/dfbf9e83-768d-41c3-bb65-1e10f77058e5/titillium_qa.zip)

**Comment by eliheuer** [comment]
I updated the copy in `DESCRIPTION.en_us.html`, adding info on the Arabic and VF updates. I tried not to change the original copy too much, but it needed some work, so I made some minor edits.

**Comment by eliheuer** [comment]
With Public Sans it was easier to just have the Italic included with the Roman in the PR, and there are some FontBakery error above looking for the Italic from the metadata. So I think I'll just close the[Italic PR](https://github.com/google/fonts/pull/1988) and include both files in this PR.

**Comment by RosaWagner** [comment]
We have a more recent PR which in conflict with this one. Moreover it is planned to work on this font to make an improved update… So I close this and add an issue instead.

**Pull request closed without merging**
