### PR TITLE
alegreya: v2.001 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
Improvement includes new styles and extended language coverage

Taken from upstream repo, https://github.com/huertatipografica/Alegreya. Myself and @juandelperal have done extensive mastering on this family.

@davelab6 GFRegression now can now proof against github urls which contain fonts. Copy n paste this font [dir](https://github.com/m4rc1e/fonts/tree/alegreya/ofl/alegreya) into the [app](http://45.55.138.144) and select the second option.

### CODE REVIEW

**Comment by m4rc1e** [comment]
I'll add the SC family in a separate pr.

**Comment by davelab6** [comment]
This needs updating to 2.002 (https://github.com/huertatipografica/Alegreya/releases)

**Comment by juandelperal** [comment]
Hi @m4rc1e @davelab6 !
There is a new release:
https://github.com/huertatipografica/Alegreya/releases

I hope now is fixed. please let me know if there is something else to fix. 
Thanks!!

**Comment by m4rc1e** [comment]
Thanks @juandelperal, I'll take a look later

**Comment by juandelperal** [comment]
Great, I suppose that I also have to add fi.sc and fl.sc also in Alegreya Sans. I will do it now

**Comment by juandelperal** [comment]
Added v2.003 in the sans:
https://github.com/huertatipografica/Alegreya-Sans/releases

**Pull request closed without merging**
