### PR TITLE
ci: Check server files for typos

### PR DESCRIPTION
**Pull request by m4rc1e**
Check if typos exist in the to_sandbox.txt and to_production.txt files.

This PR relies on https://github.com/googlefonts/gftools/pull/284. Once this is merged and tagged, I'll need to update the pip installation in this gh action.

### CODE REVIEW

**Comment by m4rc1e** [comment]
It appears to be working well. It's currently outputting:

```
ValueError: to_production.txt: Following paths are not valid dirs:
axisregistry/wonkiness.textproto
axisregistry/softness.textproto
axisregistry/optical_size.textproto

to_sandbox.txt: Following paths are not valid dirs:
axisregistry/wonkiness.textproto
axisregistry/softness.textproto
axisregistry/optical_size.textproto
axisregistry/grade.textproto
axisregistry/width.textproto
axisregistry/flair.textproto
axisregistry/volume.textproto
```

In the above example, we can see it's failing because the server files contain paths to files, not dirs. @davelab6 do we know if we can declare files or should it just be dirs? If it's just dirs, then it has done its job properly and we should update to the to_sandbox and to_production files.

**Comment by RosaWagner** [comment]
Thanks Mark!!

**Comment by m4rc1e** [comment]
Nyshadh confirmed that we can include .textproto files in the server files. I've updated `gftools push-status` to reflect this.

**Comment by davelab6** [comment]
This was related to https://github.com/google/fonts/issues/2589

**Pull request merged**
