### PR TITLE
Noto Sans Myanmar: Version 2.107 added

### PR DESCRIPTION
**Pull request by simoncozens**
42bb2cd: [gftools-packager] Noto Sans Myanmar: Version 2.106 added

* Noto Sans Myanmar Version 2.106 taken from the upstream repo https://github.com/notofonts/myanmar.git at commit https://github.com/notofonts/myanmar/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
```
🔥 FAIL: Glyph names are all valid? ([com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames))
🔥 FAIL The following glyph names do not comply with naming conventions: greatNnya-mon
A glyph name must be entirely comprised of characters from the following set: A-Z a-z 0-9 .(period) (underscore). A glyph name must not start with a digit or period. There are a few exceptions such as the special glyph ".notdef". The glyph names "twocents", "a1", and "" are all valid, while "2cents" and ".twocents" are not. [code: found-invalid-names]
```


I guess this glyphs name was not converted to prod name. Is it bad? I have no idea if it is that bad.

**Comment by simoncozens** [comment]
Actually none of them were using production names...

**Comment by simoncozens** [comment]
Updated

## Noto Sans Myanmar: Version 2.107 added

---
 ca6146e: [gftools-packager] Noto Sans Myanmar: Version 2.107 added

* Noto Sans Myanmar Version 2.107 taken from the upstream repo https://github.com/notofonts/myanmar.git at commit https://github.com/notofonts/myanmar/commit/.

**Comment by simoncozens** [comment]
Article, article, article... Gimme a sec, I'll add it again.

**Comment by vv-monsalve** [comment]
There seem to be many suspect issues, could you confirm they are as expected?
glyphs_missing

**Comment by vv-monsalve** [comment]
Marks behave differently among weights

**Thin**
marks_new

**Regular**
marks_new

**ExtraBold**
marks_new

**Comment by vv-monsalve** [comment]
There is a significant reflow in Sierra Safari 11 `qa` images. It also happens for the Thin weight in more recent versions, although less severe, including Monterrey 15.5 (tested with BrowserStack)

**Sierra Safari 11**
Desktop_OS_X_High_Sierra_safari_11 1_


**Catalina Safari 13.1**
Catalina-13-1


**Monterrey Safari 15.5**
Monterrey-15-5-Thin

**Comment by simoncozens** [comment]
These are all correct. There were previously significant bugs with the Mon language support which have now been fixed.

**Comment by vv-monsalve** [comment]
> Marks behave differently among weights

@simoncozens, even the [different behavior of mark](https://github.com/google/fonts/pull/4938#issuecomment-1198543079)s among weights is ok?

**Comment by simoncozens** [comment]
It's fine. Most of these sequences can't exist; diffenator is just adding random glyphs together.

**Comment by vv-monsalve** [comment]
> diffenator is just adding random glyphs together

Okay. I kind of suspected it, but better safe…
Merging this one here then

**Pull request merged**
