### PR TITLE
Play: v2.100 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Okay, we may need to keep this one open.

The Greek has been updated by @irenevl 

play-greek

We appear to have some missing glyphs, which I reported in the upstream a while back, https://github.com/alexeiva/play/issues/3.
play-missing

The big question, will people mind the missing pro Cyrillic for the time being?

cc @alexeiva

### CODE REVIEW

**Comment by alexeiva** [comment]
Hi @m4rc1e, I will add the missing Cyrillic before merging. This is a standard procedure now.

**Comment by m4rc1e** [comment]
@alexeiva thank you very much!

**Comment by alexeiva** [comment]
Legacy Cyrillic glyphs issue has been fixed. Please accept this 2.101 update https://github.com/m4rc1e/play/pull/1 before pushing

**Comment by m4rc1e** [comment]
Smoking hot sir, I will inspect this tomorrow

**Comment by davelab6** [comment]
@m4rc1e status of this? :0

**Comment by m4rc1e** [comment]
I'll add it tomorrow.

**Pull request closed without merging**
