### PR TITLE
Update Noto Sans

### PR DESCRIPTION
**Pull request by simoncozens**
This updates the existing Noto Sans fonts to the latest versions from https://github.com/googlefonts/noto-source.

Important notes!

* This is my first google/fonts PR. I don't really know what I'm doing!
* The existing Noto Sans on GF was built by hand with a merged Noto Sans Devanagari. So this build also includes a merged Devanagari. For reproducibility:  I built Noto Sans using notobuilder (https://github.com/googlefonts/noto-source/pull/499) and then I used the merge script below to add Devanagari (binaries from https://github.com/googlefonts/noto-fonts/tree/main/hinted/ttf/NotoSansDevanagari) and fix up some fontbakery issues.
* Existing Noto Sans on GF just has RIBBI styles. While I was merging everything anyway, I merged all the weight styles we have because why not, so this expands the weight range.
* Existing Noto Sans Regular on GF has PostScript name "NotoSans" *not* "NotoSans-Regular". **I have not conformed to this**. `NotoSans-Regular.ttf` in this PR is just the way it came out of notobuilder, and it has PS Name "NotoSans-Regular", which fontbakery is much happier about. So this is a change to what is in the catalogue. I don't know if this is a problem. 
 
Fontbakery fails:

* Mostly about copyright strings. The copyright string for Noto Sans is "Copyright 2015-2021 Google LLC. All Rights Reserved." which makes Fontbakery sad . But I think the Noto style copyright should be kept; it seems more correct than the usual "The ... Project Authors". We may need to make a FB exception for this?
* "Designers are listed correctly on the Google Fonts catalog". I don't know how this is supposed to work for Noto. All the other Noto fonts seem to have "Designer: Google" so maybe they fail too.
* "Check samples can be rendered." This is because the italic fonts have no Devanagari; we have no Noto Sans Devanagari Italic, and this is consistent with the existing GF Noto Sans. The upright styles can renderer all the sample glyphs.

## Merge script (for posterity)

```python
from fontTools.ttLib import TTFont
from fontTools.merge import Merger
from tempfile import NamedTemporaryFile
from gftools.fix import fix_family
import glob
import re

NAME_13 = "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://scripts.sil.org/OFL"

def fix_up_glyph_names(font):
	# Requires compiling a bunch of the tables, easiest to save/reload
	with NamedTemporaryFile() as ntf:
		font.save(ntf.name)
		font = TTFont(ntf.name)

	# Fixup glyph names.
	mapping = {x: x.replace("#","_") for x in font.getGlyphOrder()}
	mapping[".notdef#1"] = "_notdef_1"
	neworder = [mapping[x] for x in font.getGlyphOrder()]
	font.setGlyphOrder(neworder)
	font["glyf"].glyphOrder = neworder
	font["glyf"].glyphs = {mapping.get(k,k):v for k,v in font["glyf"].glyphs.items()}
	font["hmtx"].metrics = {mapping.get(k,k):v for k,v in font["hmtx"].metrics.items()}
	return font

def fixup_various(font):
	# Vertical metrics
	font["OS/2"].sTypoAscender = font["hhea"].ascender = 1069
	font["OS/2"].sTypoDescender = font["hhea"].descender = -293
	# Missing glyphs for GF Latin Core
	for cmap in font["cmap"].tables:
		cmap.cmap[0x2215] = cmap.cmap[0x2f]  # Division sign <- solidus
		if 0x2212 not in cmap.cmap:
			cmap.cmap[0x2212] = cmap.cmap[0x2d]  # Minus sign <- hyphen-minus
	# name ID 13
	font["name"].setName(NAME_13, 13, 3, 1, 0x409)

LGC = glob.glob("../source/output/Noto Sans/unhinted/ttf/*.ttf")
DEVA = glob.glob("unhinted/ttf/NotoSansDevanagari/*.ttf")

styles = {}

for filename in LGC:
	style = re.search("-(.*?).ttf", filename)[1]
	styles[style] = { "lgc": filename }

for filename in DEVA:
	style = re.search("-(.*?).ttf", filename)[1]
	if style in styles:
		styles[style]["deva"] = filename

outfonts = {}

for style, files in styles.items():
	# Skip the condensed
	if "Condensed" in style or "Display" in style:
		continue
	print("Merging %s" % style)
	if "deva" in files:
		outfont = Merger().merge([files["lgc"], files["deva"]])
		outfonts[style] = fix_up_glyph_names(outfont)
	else:
		ttfont = outfonts[style] = TTFont(files["lgc"])
		# Just keep 3-1-0 cmap
		ttfont["cmap"].tables = [ x for x in ttfont["cmap"].tables if x.platformID == 3]


print("Fixing")
fix_family(list(outfonts.values()),include_source_fixes=True)

for style, outfont in outfonts.items():
	output = "merged/NotoSans-%s.ttf" % style
	fixup_various(outfont)
	print("Saving %s" % style)
	outfont.save(output)
```

### CODE REVIEW

**Comment by rsheeter** [comment]
> Merge script (for posterity)

We should commit this somewhere, noto-source I would guess. @marekjez86

**Comment by simoncozens** [comment]
But then we might be tempted to accidentally use it again instead of fixing the root problem. ;-)

**Comment by RosaWagner** [comment]
- PS Name is okay for Regular, it was incorrect before
- Copyright is okay, it is a Noto exception (should be added to fontbakery)
- I am not surprised Google is not part of their own catalog of designers. Although I find it a bit odd no other designers are credited, maybe we could correct that @davelab6 
- A bit worried by the missing parts of sample text in METADATA.pb, someone from the eng-team should review (like @nathan-williams?)

@simoncozens we would need the upstream URL of where these binaries are store with a commit number, as described in this this draft document: https://rosaliewagner.notion.site/Make-a-PR-to-Google-Fonts-577ca20030524f668ff98d88347edbdb
Then if you can push the branch onto a new google/fonts branch and re-do the PR from that branch, it would allow the CI to function.

**Comment by simoncozens** [comment]
Cool, thank you. I will put the merge script and the binaries into a new branch on noto-fonts and redo this PR.

**Comment by RosaWagner** [comment]
these fonts can't be in the main branch of noto-fonts?

**Comment by simoncozens** [comment]
Unfortunately not. The LGC+Deva version is a Google Fonts-specific hack; we don't want the Devanagari glyphs in official Noto Sans.

Also, I don't seem to have permission to push a new branch onto google/fonts.

**Pull request closed without merging**
