### PR TITLE
Noto Serif: Version 2.015 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic at commit https://github.com/notofonts/latin-greek-cyrillic/commit/22328ea1ab03320d5519445fb74fd5659eebcb81.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
Noto Serif v2.014

This release:

* Removes the semibold masters
* Fixes style linking of the bold instances (#476)
* Improves kerning for Slovak, Czech and Kamba (thanks to Yusuke Shirakihara)
* Fixes an issue with the right sidebearing of quadrupleprime (#415)
* Improves the anchoring of U+1AC7 COMBINING INVERTED DOUBLE ARCH ABOVE (#467)
* Corrects the width of U+2212 MINUS SIGN (#396)
```

**Comment by emmamarichal** [comment]
@simoncozens 
This update has the same description as Noto Sans:

> This release:
> 
> * Removes the semibold masters
> * Fixes style linking of the bold instances (#476)
> * Improves kerning for Slovak, Czech and Kamba (thanks to Yusuke Shirakihara)
> * Fixes an issue with the right sidebearing of quadrupleprime (#415)
> * Improves the anchoring of U+1AC7 COMBINING INVERTED DOUBLE ARCH ABOVE (#467)
> * Corrects the width of U+2212 MINUS SIGN (#396)

 but I realised that it has less changes (Noto Sans had a lot of modifications in devanagari, if you have the corresponding PR, I'll add it in the [Noto Sans PR ](https://github.com/google/fonts/pull/8184)so we can track the changes better).

Otherwise, there are some interpolation issues remaining, and some of them should be corrected (`lslash` for instance).
[NotoSerif-Italic[wdth,wght].pdf](https://github.com/user-attachments/files/17058919/NotoSerif-Italic.wdth.wght.pdf)
[NotoSerif[wdth,wght].pdf](https://github.com/user-attachments/files/17058921/NotoSerif.wdth.wght.pdf)

**Comment by simoncozens** [comment]
Noto Serif doesn't include a Devanagari subset. (Noto Sans LGC *shouldn't* include a Devanagari subset, but workspace needed it in the distant past and now Google Fonts has to contain one for ever more. :-) ) That's why it's a smaller set of changes. lslash looks OK to me (better than the "proposed fix"), but germandbls should be fixed.

**Comment by vv-monsalve** [comment]
> but germandbls should be fixed

It seems to be working ok.

https://github.com/user-attachments/assets/a68765c5-14f1-45f6-912a-5e246d11971c

Would you like to modify it still? Other than that this LGTM

**Review by vv-monsalve — APPROVED** [review]

**Comment by simoncozens** [comment]
wdth=62 wght=290 looks like this:

Screenshot 2024-09-27 at 16 29 07

**Comment by vv-monsalve** [comment]
> wdth=62 wght=290 looks like this:

Ok, In that case, you would probably like to review the 2 aswell as the other kinks reported in the PDFs. And we'll wait for the update.

**Comment by vv-monsalve** [comment]
> And we'll wait for the update.

@simoncozens Let us know if you have a _unkinked_ font for the update :)

**Pull request merged**
