### PR TITLE
encodesans: v3.001 added.

### PR DESCRIPTION
**Pull request by thundernixon**
This makes almost no changes to the fonts from https://github.com/google/fonts/pull/2438, except:
- Static filenames have been improved (the main reason to upgrade).
- The glyph `dotlessi.sc` has been added to the smallcap glyphs

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thanks. LGTM.

**Comment by thlinard** [comment]
Hi @thundernixon 

I don't want to delay publication, as this version is much better than the previous one, but why Encode Sans "**SC**" in nameID 1, 3 and 4 (static files)?

**Comment by m4rc1e** [comment]
Good spot @thlinard.

```
    <namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Encode Sans SC Cnd Black
    </namerecord>
    <namerecord nameID="3" platformID="1" platEncID="0" langID="0x0" unicode="True">
      3.001;GOOG;EncodeSansSC-CndBlack
    </namerecord>
    <namerecord nameID="4" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Encode Sans SC Cnd Black
    </namerecord>
```

@thundernixon would you mind updating the static files?

**Comment by thundernixon** [comment]
😬 Thanks for spotting that, @thlinard.

I’ve done a bit of digging, and found that the problem is caused by unwisely combining logic to fix SC names with logic to abbreviate names more generally (done to meet character length limitations) in [a single Python script](https://github.com/thundernixon/Encode-Sans/blob/011cec896d1131512265193c34cbb8bf283c170c/sources/scripts/helpers/fix-SC-names.py).

I have some urgent tasks right now, but I will separate these parts of the flow to the static files this weekend.

**Pull request merged**
