### PR TITLE
Anta: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by m4rc1e**
95c82f2: [gftools-packager] Anta: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Anta Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/Typedesigners/Anta-Regular at commit https://github.com/Typedesigners/Anta-Regular/commit/e0a16ca419e252d498976a66fd4717a949789ee3.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
OFL URL license is now https://openfontlicense.org/; being a new font, you would like to update it before publishing.

**Comment by Typedesigners** [comment]
@vv-monsalve Hello, I filled out the form for my designer profile in March 2023.
I hope the GF team has received it.
https://googlefonts.github.io/gf-guide/profile.html

**Comment by Typedesigners** [comment]
@vv-monsalve  I have just filled out the "Designer Profile" form again.
https://googlefonts.github.io/gf-guide/profile.html

**Comment by vv-monsalve** [comment]
Hello Sergej, The above issues are pending review and resolution. We'll report here when they have been addressed.

**Comment by m4rc1e** [comment]
Updated

## Anta: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

---
 d4c32fb: [gftools-packager] Anta: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Anta Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/Typedesigners/Anta-Regular at commit https://github.com/Typedesigners/Anta-Regular/commit/7ef14d1901946d317cb3bc136a895ff6c74c246c.

**Pull request merged**
