### PR TITLE
Noto Naskh Arabic: Version 2.013 added

### PR DESCRIPTION
**Pull request by simoncozens**
092f713: [gftools-packager] Noto Naskh Arabic: Version 2.013 added

* Noto Naskh Arabic Version 2.013 taken from the upstream repo https://github.com//notofonts/arabic.git at commit https://github.com//notofonts/commit/.

### CODE REVIEW

**Review by m4rc1e — CHANGES_REQUESTED** [review]
- Figures have changed. Is this intentional? seems like a dflt locale change.
- Ng dots (ڭ) are too loose

before:

Screenshot 2022-07-07 at 12 48 39

after:

Screenshot 2022-07-07 at 12 50 33

**Comment by vv-monsalve** [comment]
Confirming: would design also apply for this one?
Desktop_Windows_10_chrome_71 0_

Other than that, @m4rc1e could we merge it?

**Comment by vv-monsalve** [comment]
> * The placement of dots in ڭ appears to be by design, since that's composed as a single glyph.
> * Farsi numerals are now the default for 06F4/06F6/06F7, and if you want Urdu you have to ask for them.
> 
> So both of these seem to be design choices.


Other than the above comment confirmation, @m4rc1e could we go ahead and merge it?

**Comment by simoncozens** [comment]
> Confirming: would design also apply for this one?

That codepoint (U+06F4) represent the "Eastern Arabic-Indic" four, which could refer to either the Urdu or the Persian forms of the digit. The designer of this version made Persian the default rather than Urdu (although Urdu is still available via locl), which matches the Unicode code charts. I think this is fine.

**Review by m4rc1e — APPROVED** [review]

**Comment by vv-monsalve** [comment]
LGTM

**Comment by simoncozens** [comment]
2.014 incoming.

**Pull request merged**
