### PR TITLE
Mansalva: Version 2.112; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
6760569: [gftools-packager] Mansalva: Version 2.112; ttfautohint (v1.8.4.7-5d5b) added

* Mansalva Version 2.112; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/carolinashort/mansalva at commit https://github.com/carolinashort/mansalva/commit/2237a60711d5abb1371f693b352cd54ae705e0e8.

 661ea44: Description updated

### CODE REVIEW

**Comment by emmamarichal** [comment]
🔥 FAIL: Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts. ([com.google.fonts/check/vertical_metrics_regressions](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics_regressions))

I saw that fail, but I don't understand why it appears. I downloaded the version on GF, and I looked at the one in the ofl too, they are exactly the same as this new version 🤔

**Google's version**
Capture d’écran 2022-10-06 à 10 58 34
**New version**
Capture d’écran 2022-10-06 à 10 58 55


I had not seen the problem on windows, I will see how to fix it

**OS:** 
Desktop_OS_X_High_Sierra_safari_11 1_

**Win:**
Desktop_Windows_10_chrome_71 0_

**Comment by RosaWagner** [comment]
Can be a use_typo_metric flag problem

**Comment by emmamarichal** [comment]
Indeed, I checked, the previous version did not have any. I guess it's better to remove it on the new version than to have such a difference. I will make a new PR to Carolina

**Comment by vv-monsalve** [comment]
> Better to keep the flag and update the v-metrics to avoid regression, check the GF Guide chapter for help on methodology

It *should* keep the flag and etc. Having the fsSelection bit 7 enabled is mandatory for any update.

**Comment by emmamarichal** [comment]
Ok thanks! :) 
So I put the good values to get exactly the same result as before, but with the "use typo metrics" activated. 
But for that, I have different values for hhea and typo, which obviously creates a fail since it has to be the same ones.
I still have trouble knowing what to prioritize, keeping the same visual result and not respecting the specs for the v-metrics, or the opposite? thank you!

Desktop_OS_X_High_Sierra_safari_11 1_
Desktop_Windows_10_chrome_71 0_
Desktop_Windows_10_edge_18 0_

**Comment by RosaWagner** [comment]
We want the same v metrics across platforms, windows is prioritized, so you can modify the hhea so they align with the typo metrics, it will only break Mac users: it means a warning needs to be added in description to explain it.

**Comment by emmamarichal** [comment]
Ok I'll do that, thanks!

**Comment by emmamarichal** [comment]
Updated

## Mansalva: Version 2.112; ttfautohint (v1.8.4.7-5d5b) added

---
 d7042c7: [gftools-packager] Mansalva: Version 2.112; ttfautohint (v1.8.4.7-5d5b) added

* Mansalva Version 2.112; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/carolinashort/mansalva at commit https://github.com/carolinashort/mansalva/commit/192d65ff2d1560ff6399abde05904d910965d483.

 ac97ff0: Description updated

**Comment by emmamarichal** [comment]
> ⚠ WARN: METADATA.pb: Designers are listed correctly on the Google Fonts catalog?

-> I'm going to send a email to the author for her designer profile

**Pull request merged**
