### PR TITLE
Rokkitt: Version 3.103 added

### PR DESCRIPTION
**Pull request by emmamarichal**
6648882: [gftools-packager] Rokkitt: Version 3.103 added

* Rokkitt Version 3.103 taken from the upstream repo https://github.com/Fonthausen/RokkittFont at commit https://github.com/Fonthausen/RokkittFont/commit/511c51b911442d3b7ee434b525997f2b334db8f1.

 6003197: Rokkitt: description updated

### CODE REVIEW

**Comment by emmamarichal** [comment]
@fonthausen just found a bug, I'm fixing it.
https://github.com/Fonthausen/RokkittFont/pull/1#issuecomment-1396744102

**Comment by m4rc1e** [comment]
Spacing is also better in this pr but needs approving.

**Comment by emmamarichal** [comment]
@m4rc1e I think it's the spacing of the 'd' that is quite wide, because kerning has been added on the dcaron. Maybe even a bit too much on the middle master. I'll check with the designer or suggest a solution

Capture d’écran 2023-01-27 à 09 38 06
Capture d’écran 2023-01-27 à 09 38 11
Capture d’écran 2023-01-27 à 09 38 18

**Comment by m4rc1e** [comment]
Acutally, it looks ok. Let's leave it. What about the spacing for the backtick?


Screenshot 2023-01-27 at 09 02 09

**Comment by emmamarichal** [comment]
Ah, before the spacing of the legacy accents looked a bit random, in the new version, they put them all at 500, all masters combined (for the grave, it was at 337, so a bit tighter) 
I can change this, anyway there is still a PR pending regarding alternates layers so I can take the opportunity to send this change (at least for the grave)

**Comment by m4rc1e** [comment]
I'm only pointing out differences. If you feel they're an improvement, then I'll accept them. I don't actually have the time to look into these details myself so I'm relying on your designer eyes ;-)

**Comment by emmamarichal** [comment]
Updated

## Rokkitt: Version 3.103 added

---
 1994971: [gftools-packager] Rokkitt: Version 3.103 added

* Rokkitt Version 3.103 taken from the upstream repo https://github.com/Fonthausen/RokkittFont at commit https://github.com/Fonthausen/RokkittFont/commit/762d1439aaa7cf4a590f604451dfc2e1c6970b9f.

 fa5c4c0: Description updated

**Comment by emmamarichal** [comment]
@m4rc1e you can merge it! :)

**Pull request merged**
