### PR TITLE
Lists of April 17th 

### PR DESCRIPTION
**Pull request by vv-monsalve**

### CODE REVIEW

**Review by chrissimpkins — APPROVED** [review]
OK for merge once @vv-monsalve confirms that the tagging CSV data are current with the families that we are moving into the pipeline here.

**Comment by vv-monsalve** [comment]
Confirmed

**Comment by vv-monsalve** [comment]
However, I could add some projects to the lists after today's Pipeline meeting.
I'll ping you after I update the lists.

**Comment by vv-monsalve** [comment]
@chrissimpkins The lists were updated, including the #7576.

**Review by chrissimpkins — APPROVED** [review]

**Comment by chrissimpkins** [comment]
Thanks Viv!  Looks good!

**Pull request merged**
