### PR TITLE
Noto Sans Ethiopic: Version 2.101 added

### PR DESCRIPTION
**Pull request by simoncozens**
269180e: [gftools-packager] Noto Sans Ethiopic: Version 2.101 added

* Noto Sans Ethiopic Version 2.101 taken from the upstream repo https://github.com/notofonts/ethiopic.git at commit https://github.com/notofonts/ethiopic/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> Don't know why we missed out the new OFL.txt here. Will a new one manually

Hi @simoncozens, please remember to include the OFL

On the other hand, It says this is a Font Upgrade but I don't find a `Noto Sans Ethiopic` in the online catalog and there are no diffenator results in the QA package. 

Could you or @m4rc1e confirm this?

**Comment by m4rc1e** [comment]
Apologies, the family is new. I just changed the label.

**Comment by vv-monsalve** [comment]
LGTM

**Comment by chrissimpkins** [comment]
Still requires prod push

**Pull request merged**
