### PR TITLE
Fix polish locl from PLN to PLK

### PR DESCRIPTION
**Pull request by FAlthausen**
Hi guys.
I found a mistake.
(Georg found it for me.)
Friedrich

### CODE REVIEW

**Comment by alexeiva** [comment]
@FAlthausen Thank you for spotting this. I would be happy to merge in your request after you have signed CLA.

thanks @shriftgestalt 

@davelab6 this PR entirely fixes the issue.

**Comment by davelab6** [comment]
@alexeiva okay perfect, thanks for clarifying!! :)

**Comment by FAlthausen** [comment]
I signed it!

**Comment by davelab6** [comment]
Thanks everyone!

**Pull request merged**
