### PR TITLE
STIX Two Math: Version 2.12 b168 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
01e63a6: [gftools-packager] STIX Two Math: Version 2.12 b168 added

* STIX Two Math Version 2.12 b168 taken from the upstream repo https://github.com/stipub/stixfonts at commit https://github.com/stipub/stixfonts/commit/85ca3fb1be4f68ee6d36e83ccae63fc15a5b40cb.

 36321a0: [gftools-packager] ofl/stixtwomath remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Notes:

This PR includes the Math font of the STIX Two project. A sibling VF Text family were included in PR #3256.

> 🔥 FAIL: Check font follows the Google Fonts CJK vertical metric schema

Related to the FB new check cjk_not_enough_glyphs [#3214](https://github.com/googlefonts/fontbakery/pull/3214)

> 🔥 FAIL: METADATA.pb: Designer is listed with the correct name on the Google Fonts catalog of designers?

Ross Mills info was added in #3258

**Comment by RosaWagner** [comment]
Last time a push got broken because the OFL.txt was not having the standard text, i'll bring it up to the next pipeline meeting to be sure we can merge.

**Comment by RosaWagner** [comment]
We just found out the fsSelection bit 7 is disabled here too.

**Comment by tiroj** [comment]
> We just found out the fsSelection bit 7 is disabled here too.

Fixed: https://github.com/stipub/stixfonts/commit/8365f8a99dc24d7e34542f8d008678a0cd92adff

**Comment by vv-monsalve** [comment]
Updated

## STIX Two Math: Version 2.12 b168a added

---
 0abf982: [gftools-packager] STIX Two Math: Version 2.12 b168a added

* STIX Two Math Version 2.12 b168a taken from the upstream repo https://github.com/stipub/stixfonts at commit https://github.com/stipub/stixfonts/commit/1017d1b276c623a3f5faad8f0966d62f7a8e1dde.

 e3c63d7: [gftools-packager] ofl/stixtwomath remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
PR updated

**Comment by RosaWagner** [comment]
LGTM 👍  Just the licence thing that needs Dave's attention.

**Comment by vv-monsalve** [comment]
Updated

## STIX Two Math: Version 2.12 b168a added

---
 700e2e3: [gftools-packager] STIX Two Math: Version 2.12 b168a added

* STIX Two Math Version 2.12 b168a taken from the upstream repo https://github.com/stipub/stixfonts at commit https://github.com/stipub/stixfonts/commit/2e94666780a3a67cb32fbfac968cc2120bbb3b90.

 edb5640: [gftools-packager] ofl/stixtwomath remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
PR updated after [OFL fixes](https://github.com/stipub/stixfonts/pull/197)

**Comment by thlinard** [comment]
Hi @tiroj @RosaWagner  

In Italic, an Elidable flag is missing for the Regular weight in the `STAT` table.

**Comment by RosaWagner** [comment]
Thanks Thomas! Another check we need for Fontbakery ;)

**Comment by thlinard** [comment]
> Thanks Thomas! Another check we need for Fontbakery ;)

Indeed! I think one way would be to compare what an `fvar`-based UI and a `STAT`-based UI would look like (this would give a more general check than just the elision flags).

With the current PR version, we have for an `fvar`-based UI:

- STIX Two Text Regular
- **STIX Two Text Italic**
- STIX Two Text Medium
- STIX Two Text Medium Italic
- STIX Two Text SemiBold
- STIX Two Text SemiBold Italic
- STIX Two Text Bold
- STIX Two Text Bold Italic

For an `STAT`-based UI:

- STIX Two Text Regular
- **STIX Two Text Regular Italic**
- STIX Two Text Medium
- STIX Two Text Medium Italic
- STIX Two Text SemiBold
- STIX Two Text SemiBold Italic
- STIX Two Text Bold
- STIX Two Text Bold Italic

So the check would consist in verifying the absence of discrepancy between the two.

**Comment by tiroj** [comment]
Not sure I 100% understand what needs to change in the STIX Two Text fonts.

@khaledhosny is this clear to you? Can we tweak the build script to handle this?

**Comment by thlinard** [comment]
> Not sure I 100% understand what needs to change in the STIX Two Text fonts.

This is a TTX excerpt of the `STAT` table (Italic font):

```
      <AxisValue index="0" Format="1">
        <AxisIndex value="0"/>
        <Flags value="0"/>
        <ValueNameID value="261"/>  <!-- Regular -->
        <Value value="400.0"/>
      </AxisValue>
```
  `<Flags value="0"/>` should become `<Flags value="2"/>`, like this:

```
      <AxisValue index="0" Format="1">
        <AxisIndex value="0"/>
        <Flags value="2"/>
        <ValueNameID value="261"/>  <!-- Regular -->
        <Value value="400.0"/>
      </AxisValue>
```

I think this should be done at least for the Italic font (this would make the names in `STAT` and `fvar` match), but you might want it for the Roman as well.

**Comment by tiroj** [comment]
Fixed in the STIX Two build script for v2.13 b170
https://github.com/stipub/stixfonts

**Pull request merged**
