### PR TITLE
Noto Sans Chakma: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
c2106ec: [gftools-packager] Noto Sans Chakma: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Chakma Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/chakma.git at commit https://github.com/notofonts/chakma/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens many marks are reported as missing and some of them look shifted (touching the base letter) on sample text. Could you confirm this is ok?
marks_missing
Desktop_Windows_10_chrome_71 0_

**Comment by vv-monsalve** [comment]
> Could you confirm this is ok?

@simoncozens

**Comment by vv-monsalve** [comment]
> and some of them look shifted (touching the base letter) on sample text. Could you confirm this is ok?

@simoncozens

**Comment by simoncozens** [comment]
The circular marks should be touching the base characters. This is what I see locally:

Screenshot 2022-09-29 at 11 54 09

The new position of marks on the dotted circle is good.

**Comment by vv-monsalve** [comment]
> The new position of marks on the dotted circle is good.

Great. Thanks for the confirmation. Merging this here then.

**Pull request merged**
