### PR TITLE
Noto Sans: Version 2.014 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic at commit https://github.com/notofonts/latin-greek-cyrillic/commit/22328ea1ab03320d5519445fb74fd5659eebcb81.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
Noto Sans v2.014

This release:

* Removes the semibold masters
* Fixes style linking of the bold instances (#476)
* Improves kerning for Slovak, Czech and Kamba (thanks to Yusuke Shirakihara)
* Fixes an issue with the right sidebearing of quadrupleprime (#415)
* Improves the anchoring of U+1AC7 COMBINING INVERTED DOUBLE ARCH ABOVE (#467)
* Corrects the width of U+2212 MINUS SIGN (#396)
```

**Comment by emmamarichal** [comment]
@simoncozens Some small interpolation are still there, but not big ones, I don't mind if we merge it with them. But feel free to correct them if you have some other corrections to do. 
[NotoSans-Italic[wdth,wght].pdf](https://github.com/user-attachments/files/17056565/NotoSans-Italic.wdth.wght.pdf)

Just want to check if this is intentional:
Screenshot 2024-09-19 at 11 10 13

+check the url in the description (see my review).

Otherwise lgtm! 👏

**Comment by emmamarichal** [comment]
thanks @simoncozens! Will you add other commit or can I merge this?

**Comment by simoncozens** [comment]
That Devanagari does not look right, let me investigate a little further.

**Comment by simoncozens** [comment]
@emmamarichal I think this is actually a fix.

Old:

shape

New:

shape

Please go ahead.

**Pull request merged**
