### PR TITLE
Agu Display: Version 1.103 added



### PR DESCRIPTION
**Pull request by n8willis**

### CODE REVIEW

**Comment by n8willis** [comment]
Looking at the built binaries, the VF version appears to have "Uzo" as the subfamily name.

Screenshot-20241114153746-553x311


Screenshot 2024-11-14 at 15-33-52 Wakamai Fondue

I thought that had been sorted out previously. I may have thinking about the static instances.

TTX `name` dump:
```
  <name>
    <namerecord nameID="256" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Morph
    </namerecord>
    <namerecord nameID="257" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Uzo
    </namerecord>
    <namerecord nameID="258" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Ala
    </namerecord>
    <namerecord nameID="259" platformID="1" platEncID="0" langID="0x0" unicode="True">
      Osisi
    </namerecord>
    <namerecord nameID="0" platformID="3" platEncID="1" langID="0x409">
      Copyright 2024 The Agu Display Project Authors (https://github.com/theseunbadejo/nsibidi-libre/blob/main/AUTHORS.txt)
    </namerecord>
    <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
      Agu Display Uzo
    </namerecord>
    <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
      Regular
    </namerecord>
    <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
      1.099;53VN;AguDisplay-Uzo
    </namerecord>
    <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
      Agu Display Uzo
    </namerecord>
    <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
      Version 1.099
    </namerecord>
    <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
      AguDisplay-Uzo
    </namerecord>
    <namerecord nameID="9" platformID="3" platEncID="1" langID="0x409">
      Oluwaseun Badejo
    </namerecord>
    <namerecord nameID="12" platformID="3" platEncID="1" langID="0x409">
      https://seun.design
    </namerecord>
    <namerecord nameID="13" platformID="3" platEncID="1" langID="0x409">
      This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: https://openfontlicense.org
    </namerecord>
    <namerecord nameID="14" platformID="3" platEncID="1" langID="0x409">
      https://openfontlicense.org
    </namerecord>
    <namerecord nameID="16" platformID="3" platEncID="1" langID="0x409">
      Agu Display
    </namerecord>
    <namerecord nameID="17" platformID="3" platEncID="1" langID="0x409">
      Uzo
    </namerecord>
    <namerecord nameID="25" platformID="3" platEncID="1" langID="0x409">
      AguDisplay
    </namerecord>
    <namerecord nameID="256" platformID="3" platEncID="1" langID="0x409">
      Morph
    </namerecord>
    <namerecord nameID="257" platformID="3" platEncID="1" langID="0x409">
      Uzo
    </namerecord>
    <namerecord nameID="258" platformID="3" platEncID="1" langID="0x409">
      Ala
    </namerecord>
    <namerecord nameID="259" platformID="3" platEncID="1" langID="0x409">
      Osisi
    </namerecord>
  </name>
```

**Comment by n8willis** [comment]
@m4rc1e Is that just an artifact of Uzo being at MORF=0?

**Comment by n8willis** [comment]
@vv-monsalve Were you intending to tag me on this?

> I've restored the first PR comment information including the checklist, it is key to our process, please do not delete it.

Just for the record, I did not delete it.

**Comment by vv-monsalve** [comment]
> @vv-monsalve Were you intending to tag me on this?
> 
> > I've restored the first PR comment information including the checklist, it is key to our process, please do not delete it.
> 
> Just for the record, I did not delete it.

Bad tagging indeed! Thank you for the clarification

**Comment by n8willis** [comment]
> > @vv-monsalve Were you intending to tag me on this?
> > > I've restored the first PR comment information including the checklist, it is key to our process, please do not delete it.
> > 
> > 
> > Just for the record, I did not delete it.
> 
> Bad tagging indeed! Thank you for the clarification. Fixed it now.

As far as I can tell from the timestamps, the comment was "edited" at the same moment the first update push landed & the page refreshed. So maybe the update-as-someone-checks-checkboxes collides in transit with the page refresh. I don't know. It makes one wonder though.

**Comment by vv-monsalve** [comment]
> As far as I can tell from the timestamps, the comment was "edited" at the same moment the first update push landed & the page refreshed. So maybe the update-as-someone-checks-checkboxes collides in transit with the page refresh. I don't know. It makes one wonder though.

Uhm! You're probably right. IIRC, Emma reported it before on another PR.

@m4rc1e seems the packager is still doing this.

**Comment by n8willis** [comment]
Some of these combinations it's reporting a problem with seem to come from [this list](https://github.com/googlefonts/glyphsets/issues/147#issuecomment-1810294388) of combos that don't have a Unicode codepoint. Like, right near the top, "Shaper didn't attach gravecomb to m". It's very trivial to see that m has the correct anchor on it. I don't see what the recommended fix is in that glyphsets issue. Is there something established here?

**Comment by vv-monsalve** [comment]
> It's very trivial to see that m has the correct anchor on it. I don't see what the recommended fix is in that glyphsets issue. Is there something established here?

Not only the components (base glyph, marks, anchors) but also the rules to make them work are needed. Inspecting the files at the repo, the source is a `.glyphs` file, but there are no features set up and no features separated file.

Screenshot 2024-11-15 at 10 21 38

When trying to add them, some issues with some marks are reported.
Screenshot 2024-11-15 at 11 07 28

**Comment by simoncozens** [comment]
Add

```
languagesystem DFLT dflt;
languagesystem latn dflt;
```

to the feature prefixes. That way ufo2ft will make the appropriate mark-to-base rules for the script.

This will help, but other problems really do need new anchors (e.g. verticallineabovecomb, Eopen/eopen, schwa/Schwa, etc.  have no anchors).

**Comment by n8willis** [comment]
> Not only the components (base glyph, marks, anchors) but also the rules to make them work are needed. Inspecting the files at the repo, the source is a `.glyphs` file, but there are no features set up and no features separated file.

(Just for future reference, I do understand how shaping functions. I've even written about it at times.)

Sorry that you weren't able to join the call where we brought this up. The font doesn't have any non-standard features; it has been using the auto-generated `mark` and `mkmk` features — which worked up until now. The thing that we've been needing to figure out is why that is working for many/most combinations but  isn't working for certain other combinations. Like whether there's something unexpected happening in the Glyphs file or if the build tools are losing something along the way.

That all having been said, the question I could really use some clarification on is what's supposed to be done about this list:

> from https://github.com/googlefonts/glyphsets/issues/147#issuecomment-1810294388 of combos that don't have a Unicode codepoint.

of things. As I recall, Eben said that it was a `ccmp` issue. But what the best practices are for handling it, I do not find. There's not a solution on that issue thread, certainly not anything in the GF guide, and I have not had luck searching for it in old chat histories.

**Comment by simoncozens** [comment]
I've explained what you need to do to fix that list. Because you understand shaping, you will know why this helps.

**Comment by n8willis** [comment]
> Add
> 
> ```
> languagesystem DFLT dflt;
> languagesystem latn dflt;
> ```
> 
> to the feature prefixes. That way ufo2ft will make the appropriate mark-to-base rules for the script.

So, a TTX dump of GPOS indicates that those get added already (which does seem like it would be the expected behavior).

> 
> This will help, but other problems really do need new anchors (e.g. verticallineabovecomb, Eopen/eopen, schwa/Schwa, etc. have no anchors).

Well, some of that might happen at the same time, but as I understand where the conversation ended up, then upstream isn't going to be asked to add things beyond the original contracted feature set. It's certainly great that the glyphsets have received a serious cleanup and refactoring of the tools, but the goalposts of the contract shouldn't be moving at this stage.

**Comment by simoncozens** [comment]
> So, a TTX dump of GPOS indicates that those get added already

Language systems get added to the font binary, yes. But that's not what I said. I said, add them to the feature prefixes. Please believe that there's a reason I suggested doing that.

I cloned the Agu Display repo as at the commit above and built the font. I saw that mark attachment was not working for the combinations above. Why not, I wondered? So I looked into it. I did some debugging. I used the `--debug-feature-file` argument to fontmake. There's a "pos base m" rule in `mark2base_3`. That looks fine. So why is it not firing? I noticed that the feature file doesn't define any `languagesystem`s.

Then I did some *more* debugging - I loaded the font into FontGoggles, and changed the script from Automatic to `DFLT`. It worked! Aha! This tells me that the rules are correct in the font, but are not being attached to the correct language system - no mark rules for `latn`, only for `DFLT`.

So I tried adding the language systems into the feature prefixes, checked the generated feature file and the font in FontGoggles, and all was well. 

Debugging: I can highly recommend it.

**Comment by n8willis** [comment]
Well, perhaps fortuitous that this landed while I was in the middle of writing a reply, not before:

> I've explained what you need to do to fix that list. Because you understand shaping, you will know why this helps.

You make pointed comments like this — and like this one:

> Debugging: I can highly recommend it.

directed my way, and in mid-thread context I'm not clear if this's intended to be humorous or what, but it really just sounds like you want to have an argument, and I'm not interested in that.

I wrote my [comment](https://github.com/google/fonts/pull/8487#issuecomment-2485563371) in reply to Viviana's comment, which was about general feature code, because it started out with high-level, overview stuff. Viviana and I have never actually met, and we really do not know each other at all apart from these comments. So I was very literally explaining in my reply to her that I was already familiar with the basics and that it wasn't necessary to start there. And then followed up by relaying what we had figured out so far in additional detail. Your own comment I replied to below that, in its own message.

For the record on that one, upstream did already include that prefix insertion several days ago, and it didn't solve it.

So I don't get what these remarks are supposed to communicate. But I'm not interested in the argument at all, so if that's the intent please consider me out. OTOH, if it's meant to be humor, then it is not coming across. If neither, I suppose it's still not coming across.

**Comment by n8willis** [comment]
> * Please add the `primary_script` field into the Metadata file

@vv-monsalve The checklist in the PR template says that this field is for "projects that have a primary non-Latin based language support target". Is that not the case (or not the case anymore)?

**Comment by chrissimpkins** [comment]
I've pulled together time for us to discuss this project tomorrow.  Please pause discussion in this thread until we have a chance to speak together.  I will post the next message in this thread with the plan of record to land this in main once we have an opportunity to speak with each other.

**Comment by n8willis** [comment]
Updated

**Comment by chrissimpkins** [comment]
Nate will publish the list of unsupported African languages as defined by a local shaperglot CLI reporting run here.  Then we will decide on next steps for the v1.0 release.

**Comment by vv-monsalve** [comment]
> @vv-monsalve The checklist in the PR template says that this field is for "projects that have a primary non-Latin based language support target". Is that not the case (or not the case anymore)?

Hi @n8willis. No, it's not needed. After reviewing previous PRs, I got briefly confused last week, but in this font, it is not required. Please ignore that comment. I'll delete the bullet for added clarity.

**Comment by chrissimpkins** [comment]
@n8willis please let us know what is missing for the following langauages when you've completed your assessment:

- Bambara
- Igbo
- Ganda
- Dyula

Thanks!

**Comment by chrissimpkins** [comment]
shaperglot lang checks across those four languages using the latest PyPI release of the shaperglot tool.

It looks like we only need to resolve the upper case Eng default +/- `locl` supported GSUB shaping. Do you know if we currently have the African form in the default position? Or is it the Sami form?  If the African lang form, then there is probably nothing to do at all and we are ready to ship v1.0?

### Bambara

```
$ shaperglot check AguDisplay\[MORF\].ttf Bambara

 * FAIL: The locl feature did not affect Eng

To add full support to nearly-supported languages:
 * Add feature: a locale rule to substitute Eng with a variant glyph
```

### Igbo

```
$ shaperglot check AguDisplay\[MORF\].ttf Igbo

 * FAIL: The locl feature did not affect Eng

To add full support to nearly-supported languages:
 * Add feature: a locale rule to substitute Eng with a variant glyph
```

Ditto my above question for Bambara

### Ganda

```
shaperglot check AguDisplay\[MORF\].ttf Ganda
Font nearly supports language 'lg_Latn'
 * FAIL: The locl feature did not affect Eng

To add full support to nearly-supported languages:
 * Add feature: a locale rule to substitute Eng with a variant glyph
```


### Dyula

```
 * FAIL: The locl feature did not affect Eng

To add full support to nearly-supported languages:
 * Add feature: a locale rule to substitute Eng with a variant glyph
```

**Comment by n8willis** [comment]
Sorry; I didn't see this until just now.

> It looks like we only need to resolve the upper case Eng default +/- `locl` supported GSUB shaping. 

That's correct, as far as I can determine. I have started a PR on the upstream repo that should have taken care of the other issue, with soft-dotted i/j in `ccmp`. I expect that will get merged in when the upstream designer has Eng solved to satisfaction.

I don't currently have an ETA on that, but there is already a base glyph that _mostly- share construction with the other Eng skeleton. So it's likely just a matter of ensuring that the other Eng form works visually with the 3 variation masters and the rotating/substituting decorations in the alternate layers.

> Do you know if we currently have the African form in the default encoding position? Or is it the Sami form? 

The existing Eng form was Sami; the new one to be added is the African form. That will become the default; the plan is to make use of Glyphs's auto-feature-generation func. Assuming that works as expected, moving the old Eng to Eng.loclNSM and adding the new African Eng as the default is (I believe) all that's required. But even if the auto-feature doesn't work as advertised, this way there's just one `locl` rule required, which is trivial to do by hand if needed.

Plus, folks have said that the full set of African languages that would need `locl` lookups, in the reverse strategy, isn't perfect anyway, since not all of the languages have official codes (yet?).

Although on this:
> $ shaperglot check AguDisplay\[MORF\].ttf Bambara
> 
>  * FAIL: The locl feature did not affect Eng
> 
> To add full support to nearly-supported languages:
>  * Add feature: a locale rule to substitute Eng with a variant glyph

as I understand it, the check assumes Sami is the default and just looks for "does the glyph change if the language is set == Bambara". So the check will not succeed for fonts where the African form is the default, and that just needs to be noted and acknowledged when examining the report.

**Comment by chrissimpkins** [comment]
> The existing Eng form was Sami; the new one to be added is the African form. 

Noted.  It sounds like we need to wait on this so that we pick up the missing languages that I noted above in our v1.0 release.  Do we have an estimate on how long it will take to develop this glyph?

**Comment by chrissimpkins** [comment]
> So the check will not succeed for fonts where the African form is the default, and that just needs to be noted and acknowledged when examining the report.

This is my understanding as well.  I think that we can satisfy the v1.0 release requirements if we add the African UC Eng as the default design in the encoded position.  That is all that we need.  If we can support the non-African localization by next week, that is fine. If we can't, let's ship without it and add that in a new release following v1.

**Comment by chrissimpkins** [comment]
@n8willis please convert out of Draft PR status when https://github.com/google/fonts/pull/8487#issuecomment-2494810801 is complete and ping Marc so that he knows that your PR is ready for review. Thanks!

**Comment by n8willis** [comment]
Updated

**Comment by n8willis** [comment]
The Eng has been updated, with the African construction as the default and the Sami construction activated in `locl`. The only bakery fail I encounter with {Bambara, Igbo, Ganda, Dyula} is the one that says `locl` doesn't "affect" Eng in those languages, which is expected because those langs need the default form.

@m4rc1e the designer still has some updated Article content he wants to deliver (it's a bit boilerplate now). Same with the Bio form. Should I hold off on un-drafting the state of this until that's pushed?

**Comment by n8willis** [comment]
> Eng thing looks good, I wonder how we can fix the FB check.

I could be mistaken, but it seems like checking for `locl` to affect NSM is the only other case to expect for Eng. So perhaps the check could be _either_ locl-affects-NSM _or_ locl-affects-{African-language-set}. If it does at least one of the two, that should be an indicator it's OK, right?

> Article and Bio data should not delay this push to meet the EoY goal, we can update those in January.

Great; thanks. On the move now!

**Pull request merged**
