### PR TITLE
Anton SC: Version 2.116; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/googlefonts/AntonFont at commit https://github.com/googlefonts/AntonFont/commit/beb92fcad87808357123bb66881b4032dc96efe7.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
There were only two fails but the shape_languages fail was so long that it could not be posted.

**Comment by vv-monsalve** [comment]
The SC fonts are automatically created from the non-SC fonts, so they do not cover update fixes. They should probably be done "upstream" later on.

**Comment by vv-monsalve** [comment]
@simoncozens the Fontbakery report was not deployed in this font. Did you deactivated it in any way?

**Comment by vv-monsalve** [comment]
> There were only two fails but the shape_languages fail was so long that it could not be posted.

@simoncozens could this be the reason behind the CI failing? One of them says `ninja: build stopped: interrupted by user.` but that was not the case :)

**Comment by vv-monsalve** [comment]
@simoncozens I added the SC reference to the Description file. After that, LGTM. 
However, since the CI run is not working now, I'll wait until we hear from Marc.

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
The PR must be rebased so that the CI can work with the latest changes. However, I got the QA files from yesterday, and they were okay, so I'm merging this now.

**Pull request merged**
