### PR TITLE
Parkinsans: Version 1.000 added



### PR DESCRIPTION
**Pull request by emmamarichal**

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal 

- `Ŀ` `ŀ` are showing a weird interpolation. Alternatively, if the font has `periodcentered.loclCAT` I think you can mark this glyph as non-export. We have deprecate it from our glyphsets, considered a legacy encoding.

https://github.com/user-attachments/assets/d55390e0-cb25-4362-b734-c818132c890c

<hr>

- `hbar` legibility is affected, especially at dark weights in small sizes.

Screenshot 2024-11-07 at 09 48 09
Screenshot 2024-11-07 at 09 32 32

<hr>

- Acute in `Ǽ` looks shifted off 
Screenshot 2024-11-07 at 09 27 11

**Comment by emmamarichal** [comment]
@vv-monsalve ok great, thank you, I'll try to implement the changes this afternoon!

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
@vv-monsalve updated!

**Review by vv-monsalve — APPROVED** [review]

**Pull request merged**
