### PR TITLE
HindGuntur, InknutAntiqua, Khula, Padauk Hinting

### LINKED ISSUE #1204: HindGuntur-Bold.ttf, InknutAntiqua, Khula and Padauk Hinting issues (reported by HintingDebugger)
Issues reported on HindGuntur-Bold (on current master at https://github.com/google/fonts/commit/8382674661d70b35dcfec78c7d4b705685ed6a4f) by running https://github.com/felipesanches/HintingDebugger/commit/955e0cd7194cf00f4b5d9a3fa78c2ef10c0eda95

```
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x0ABA (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
/home/felipe/gfonts/ofl/hindguntur/HindGuntur-Bold.ttf (12 pt): "CVT Out of range." at IP=0x005F (RCvt)
```

### PR DESCRIPTION
**Pull request by laerm0**
Reran fonts through ttfautohint, using original parameters if they were noted in the name table. Versions incremented.

Fixes #1204. 

Did this as a draft because I have only hotfixed the hinting. Other thing will need to be fixed to bring them up to current spec. @m4rc1e let me know if you'd like those done as well, otherwise, please merge.

### CODE REVIEW

**Comment by m4rc1e** [comment]
drop the commit for ledger since that is in pr #2353

**Comment by laerm0** [comment]
There ya go @m4rc1e

**Comment by RosaWagner** [comment]
I ran some diff and it looks okay

[Khula.zip](https://github.com/google/fonts/files/5141706/Khula.zip)

[Padauk.zip](https://github.com/google/fonts/files/5141707/Padauk.zip)

[Inknutantiqua.zip](https://github.com/google/fonts/files/5141709/Inknutantiqua.zip)

[HindGuntur.zip](https://github.com/google/fonts/files/5141710/HindGuntur.zip)

**Comment by davelab6** [comment]
Thanks everyone!

**Pull request merged**
