### PR TITLE
Karla: Version 2.002 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
e485dbb: [gftools-packager] Karla: Version 2.002 added

* Karla Version 2.002 taken from the upstream repo https://github.com/googlefonts/karla.git at commit https://github.com/googlefonts/karla/commit/944bd03a1e88bdc543a739293656d88dac52f547.

 964b1f9: [gftools-packager] ofl/karla remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This PR includes the changes performed by Mirko to update it:

- [x] Create Karla as a Variable Font
- [x] Include new ExtraLight, Light, Medium and ExtraBold instances

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.7.31

<details>
<summary><b>[1] Karla-Italic[wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>
<details>
<summary><b>[1] Karla[wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 2 | 70 | 18 | 258 | 0 |
| 0% | 0% | 1% | 20% | 5% | 74% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [karla_qa.zip](http://35.238.63.0/media/263c235a-f789-4422-9be0-5cc7713765ee/karla_qa.zip)

**Comment by RosaWagner** [comment]
There is unusual with the STAT when I check it in Samsa: roman (which is marked as default) appears in the compose name. And italic is also accessible in the upright variable.

**Comment by vv-monsalve** [comment]
Updated

## Karla: Version 2.002 added

---
 ca45c17: [gftools-packager] Karla: Version 2.002 added

* Karla Version 2.002 taken from the upstream repo https://github.com/googlefonts/karla.git at commit https://github.com/googlefonts/karla/commit/beaccb2d86b457655610b69732f3449fa5d5885b.

 cc80223: [gftools-packager] ofl/karla remove METADATA "source".  google/fonts#2587

**Comment by m4rc1e** [comment]
https://github.com/googlefonts/karla/blob/master/sources/karla_stat_table.py#L42 name should be Roman.

**Comment by vv-monsalve** [comment]
Updated

## Karla: Version 2.002 added

---
 e66ad67: [gftools-packager] Karla: Version 2.002 added

* Karla Version 2.002 taken from the upstream repo https://github.com/googlefonts/karla.git at commit https://github.com/googlefonts/karla/commit/1bd63a928e0f1122373b2a3dfe6c82cdb20569b3.

 aaba405: [gftools-packager] ofl/karla remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> https://github.com/googlefonts/karla/blob/master/sources/karla_stat_table.py#L42 name should be Roman.

Right, I went back to the spec and yes it should be Roman. So that part on the first attempt was right. 

I inspected Cabin according to this and it should be changed there then, and probably others since it was like this in the script that Chris shared me once.

> And italic is also accessible in the upright variable.

This part is what wasn't ok. I replicated it when using gen_stat.py. I went back to karla_stat_table.py and worked well.

**Comment by m4rc1e** [comment]
Can you remove the gen_stat.py from the upstream? It's now redundant.

**Comment by vv-monsalve** [comment]
> Can you remove the gen_stat.py from the upstream? It's now redundant.

Done

**Comment by RosaWagner** [comment]
### [Karla_qa.zip](https://github.com/google/fonts/files/5487453/Karla_qa.zip)

There is a regression with the Italics of ExtraLight and Light:

Desktop_Windows_10_firefox_62 0_

**Comment by vv-monsalve** [comment]
> This PR includes the changes performed by Mirko to update it:
> 
> * [x]  Create Karla as a Variable Font
> * [x]  Include new ExtraLight, Light, Medium and ExtraBold instances
> 
> Also a new Upstream for the project created at https://github.com/googlefonts/karla

@RosaWagner Thanks, [Karla](https://fonts.google.com/specimen/Karla?query=Karl) used to be a RIBBI font. The ExtraLight, Light, Medium and ExtraBold weights are new.

**Comment by RosaWagner** [comment]
Yes yes, but for some raisons I have this diff for the italics and not for the upright. It must be a bug, can you check with this command and tell me if you have the same ?

`gftools qa -pr https://github.com/google/fonts/pull/2770 --browser-previews -o ~/Desktop/Castoro_qa`

**Comment by vv-monsalve** [comment]
> Yes yes, but for some raisons I have this diff for the italics and not for the upright. It must be a bug, can you check with this command and tell me if you have the same ?
> 
> `gftools qa -pr https://github.com/google/fonts/pull/2770 --browser-previews -o ~/Desktop/Castoro_qa`

I've done that and I'm not receiving the regressions
Desktop_Windows_10_chrome_69 0_
Desktop_Windows_10_firefox_62 0_
Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by RosaWagner** [comment]
Great, perfect. Then all looks good !

**Pull request merged**
