### PR TITLE
charm: v1.001 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo, https://github.com/cadsondemak/Charm

@davelab6 let me gen an FB report and diffs before we merge this.

### CODE REVIEW

**Comment by m4rc1e** [comment]
@davelab6 Here's the scale update.
charm_height

**Comment by davelab6** [comment]
@m4rc1e @suppakit- what are these glyphs? :)

['L_O_G_O_period_l_i_n_e_t_h_a_i_A', 'L_O_G_O_period_l_i_n_e_t_h_a_i_B', 'L_O_G_O_period_l_i_n_e_t_h_a_i_C', 'L_O_G_O_period_l_i_n_e_t_h_a_i_D', 'L_O_G_O_period_l_i_n_e_t_h_a_i_E', 'L_O_G_O_period_l_i_n_e_t_h_a_i_F', 'L_O_G_O_period_l_i_n_e_t_h_a_i_G', 'L_O_G_O_period_l_i_n_e_t_h_a_i_H', 'L_O_G_O_period_l_i_n_e_t_h_a_i_I', 'L_O_G_O_period_l_i_n_e_t_h_a_i_J', 'L_O_G_O_period_l_i_n_e_t_h_a_i_K']

**Comment by m4rc1e** [comment]
Probably used for some crazy ligatures.

**Comment by m4rc1e** [comment]
They fail because they are longer than 32 chars

**Comment by davelab6** [comment]
Okay, here's what they look like: 

screen shot 2018-10-16 at 11 58 25 am

dlig feature:
```
sub L O G O period l i n e t h a i A by L_O_G_O_period_l_i_n_e_t_h_a_i_A;
sub L O G O period l i n e t h a i B by L_O_G_O_period_l_i_n_e_t_h_a_i_B;
sub L O G O period l i n e t h a i C by L_O_G_O_period_l_i_n_e_t_h_a_i_C;
sub L O G O period l i n e t h a i D by L_O_G_O_period_l_i_n_e_t_h_a_i_D;
sub L O G O period l i n e t h a i E by L_O_G_O_period_l_i_n_e_t_h_a_i_E;
sub L O G O period l i n e t h a i F by L_O_G_O_period_l_i_n_e_t_h_a_i_F;
sub L O G O period l i n e t h a i G by L_O_G_O_period_l_i_n_e_t_h_a_i_G;
sub L O G O period l i n e t h a i H by L_O_G_O_period_l_i_n_e_t_h_a_i_H;
sub L O G O period l i n e t h a i I by L_O_G_O_period_l_i_n_e_t_h_a_i_I;
sub L O G O period l i n e t h a i J by L_O_G_O_period_l_i_n_e_t_h_a_i_J;
sub L O G O period l i n e t h a i K by L_O_G_O_period_l_i_n_e_t_h_a_i_K;
sub L O G O period e n d l i n e A by L_O_G_O_period_e_n_d_l_i_n_e_A;
sub L O G O period e n d l i n e B by L_O_G_O_period_e_n_d_l_i_n_e_B;
sub L O G O period e n d l i n e C by L_O_G_O_period_e_n_d_l_i_n_e_C;
sub L O G O period e n d l i n e D by L_O_G_O_period_e_n_d_l_i_n_e_D;
sub L O G O period c o r n e r A by L_O_G_O_period_c_o_r_n_e_r_A;
sub L O G O period c o r n e r B by L_O_G_O_period_c_o_r_n_e_r_B;
sub L O G O period c o r n e r C by L_O_G_O_period_c_o_r_n_e_r_C;
sub L O G O period c o r n e r D by L_O_G_O_period_c_o_r_n_e_r_D;
sub L O G O period k r a j a n g by L_O_G_O_period_k_r_a_j_a_n_g;
sub L O G O period S b o a t by L_O_G_O_period_S_b_o_a_t;
sub T h by T_h;
sub T k by T_k;
sub T l by T_l;
sub boBaimai-thai saraAa-thai by boBaimai_saraAa-thai;
```

So, is this a problem or not? Should we fix the font, or fix the check?

**Comment by m4rc1e** [comment]
They're 34 chars long so they go over the 32 char limit.

I didn't change them because the authors may have some docs that are using them.

**Comment by davelab6** [comment]
> I didn't change them because the authors may have some docs that are using them.

But no docs refer to glyph names. 

Assuming you built then with fontmake, goes glyphsapp compiler truncate them/rename them to pass the check?

**Comment by m4rc1e** [comment]
I built the fonts with Glyphsapp so it doesn't truncate the names.

Shall I rename these glyphs?

**Comment by davelab6** [comment]
Yes. And I guess file a bug against fontmake and post on the glyphsapp
forum about it.

**Pull request merged**
