### PR TITLE
Ojuju: Version 1.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
d101d99: [gftools-packager] Ojuju: Version 1.000 added

* Ojuju Version 1.000 taken from the upstream repo https://github.com/jobosonchisa/ojuju at commit https://github.com/jobosonchisa/ojuju/commit/923e574a4f8003b2683319003b5e50f9e55fcdc5.

### CODE REVIEW

**Comment by emmamarichal** [comment]
@bghryct, here you can find a review for Ojuju. Please let me know when the changes are done in the upstream repo. I'll then update and merge that PR :)


### **PR to update / for @emmamarichal**
🔥 FAIL: METADATA.pb: Designers are listed correctly on the Google Fonts catalog? 
- [ ] I'll change your name in metadata.pb, once the upstream changes will be done. Mirko Velimirovic -> Mirko Velimirović
- [ ] I'll add Chisaokwu Joboson to the designer catalog https://github.com/google/fonts/issues/7262

⚠ WARN: Check OFL body text is correct. 
- [ ] I guess it's an URL issue, but I'll check once the upstream changes will be done and the PR updated.

### **Changes needed on sources / for @bghryct**
⚠ WARN: Are there caret positions declared for every ligature? 
-> add caret anchors for ligatures.

⚠ WARN: Does the font contain a soft hyphen? 
-> Soft hyphen can be removed

⚠ WARN: Check math signs have the same width. 
-> Better, but it's ok if they don't have the same width.

**Design issues:**

The L accent is positioned differently:

https://github.com/google/fonts/assets/64773544/b103d65d-2c4b-4299-a2ff-e496284d5b78

**Comment by bghryct** [comment]
Thanks @emmamarichal I'll get on this with the designer.

**Comment by bghryct** [comment]
@emmamarichal  I'm updating the repo with the corrected work.

**Comment by emmamarichal** [comment]
Updated

## Ojuju: Version 1.000 added

---
 672543f: [gftools-packager] Ojuju: Version 1.000 added

* Ojuju Version 1.000 taken from the upstream repo https://github.com/jobosonchisa/ojuju at commit https://github.com/jobosonchisa/ojuju/commit/7f366504f204a579b27c99cb6c6272183100cde0.

 133854d: ojuju: metadata updated

**Pull request merged**
