### PR TITLE
majormonodisplay: remove Mike LaGattuta from METADATA.pb

### PR DESCRIPTION
**Pull request by laerm0**

### CODE REVIEW

**Comment by felipesanches** [comment]
@laerm0, it looks like there's a ton of unrelated older commits in here :-(

**Comment by felipesanches** [comment]
maybe this can be solved by git rebase upstream/master + git push force feature-branch

**Comment by felipesanches** [comment]
@micah, I am opening a new PR for this cherry-picking your commit that removes Mike LaGattuta form that METADATA.pb file

**Comment by laerm0** [comment]
Yeah, sorry, I hadn't pulled from upstream in a while. (Should make a cron job for that.)

**Pull request closed without merging**
