### PR TITLE
fira code: v1.207 added.

### PR DESCRIPTION
**Pull request by thundernixon**
Fira Code is a highly popular monospace font, famous for including "code ligatures."

A variable font has been built from it, and a few pieces of metadata have been cleaned up to pass FontBakery checks.

This PR isn't immediately ready to merge – remaining to-do items are:

- [x] Finish vector outline check + fixes (Light master was extrapolated, and has a few issues) – [quick pass correcting outline issues summarized here](https://github.com/thundernixon/FiraCode/blob/qa/googlefonts-qa/notes/outline-checks.md)
- [ ] Wait for https://github.com/mozilla/Fira/pull/219 to merge, so we have permission to use name "Fira"

---

Upstream Repo: https://github.com/tonsky/FiraCode
Working QA branch: https://github.com/thundernixon/FiraCode/tree/qa
PR Closes: https://github.com/google/fonts/issues/1460

### CODE REVIEW

**Comment by thundernixon** [comment]
@tonsky You're welcome to take a look at this, if you like! I know you care about this project a lot, so I want to make sure you have some say before we merge it. Is the variable font working as you expect? Is the html description looking good to you? Are you finding any issues I may have missed? 

If you're busy with other work; no worries – I think things are solid here, but I just wanted to welcome input from you, if you have any.

**Comment by tonsky** [comment]
@thundernixon thanks for pinging me! Looks great!

BTW not sure if this is intentional or not, but shouldn’t [this file](https://github.com/google/fonts/blob/9555b351342cd003c28c60ed88b365ceaac8b45f/ofl/firacode/FiraCode-Light.ttf) be called FiraCode.ttf (no -Light suffix)?

**Comment by thundernixon** [comment]
@tonsky cheers! Thanks for taking a look.

> shouldn’t this file be called FiraCode.ttf (no -Light suffix)?

Good question! Variable font filenames will soon be converted to a [format described in GF issue 1817](https://github.com/google/fonts/issues/1817#issuecomment-466556000). For Fira Code, I think that will look like `FiraCode[wght].ttf`. However, I haven't imposed that in this PR, because we (probably @m4rc1e) will just make a new [gftools](https://github.com/googlefonts/gftools) script to convert filenames for many VFs at once.

In general, VFs contain some default naming metadata based on their default instance, so that they'll make sense as a fallback in legacy software that doesn't understand the new OpenType tables used for variable fonts. As a random example, if you load the Fira Code VF in a 2011 MS Word, it will (as far as I know) show up as `Fira Code Light` and show the associated glyph shapes.

**Comment by tonsky** [comment]
Shouldn’t Regular be the default then?

**Comment by thundernixon** [comment]
Another good question! 

To make this work as a variable font, it was necessary to set up the font file so that it wouldn't rely on extrapolation for the extremes. In your version of the source, there are Regular and Bold masters which output Light through Bold instances. Those can be built as static fonts, but VarLib doesn't currently support such a setup.

So, the two choices were to 
1. Make a light master and let the be the default (alternatively, the bold could be the default)
2. Make a light master *plus* keep the Regular master so it could be the default. This would create a significantly larger VF output, with little advantage. So long as the font is being viewed on modern software, almost no users will even realize that the light master is a default state, because the browser and CSS will provide their own styles.

**Comment by tonsky** [comment]
I just dived into your PR and noticed there’s no Regular master anymore. That explains it, thanks!

**Comment by thundernixon** [comment]
The latest update adds fresh statics to the build – previously, these were accidentally left out.

**Comment by davelab6** [comment]
@thundernixon mozilla/Fira#219 is merged!

**Comment by m4rc1e** [comment]
The VF contains 5 instances. One of them is the following style, which is in between Regular and Medium:
```
    <!-- Retina -->
    <NamedInstance flags="0x0" subfamilyNameID="259">
      <coord axis="wght" value="450.0"/>
    </NamedInstance>
```

@garretrieger Will having such an instance cause issues? if not, we can merge this. I've attached the full [fvar dump](https://github.com/google/fonts/files/3367252/FiraCode-fvar.txt)

**Comment by rsheeter** [comment]
We don't rely on named instances, shouldn't matter

**Comment by twhite96** [comment]
Is this live because I search for it and don't see it.

**Comment by thundernixon** [comment]
@twhite96 There are internal engineering processes that happen to further optimize fonts (especially variable fonts) to make things work with the API / generate CSS, statics, etc. This PR merging into the public repo means were a lot closer than before! It also means that the font has gotten some useful improvements, and should be solid if you'd like to use them for self-hosting before they make it onto the public directory & API.

**Comment by twhite96** [comment]
>@twhite96 There are internal engineering processes that happen to further optimize fonts (especially variable fonts) to make things work with the API / generate CSS, statics, etc. But, this PR merging into the public GF repo means we're a lot closer than before! It also means that the font has gotten some useful improvements, and should be solid if you'd like to use it for self-hosting before it makes it onto the public directory & API.

@thundernixon okay! No worries.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
