### PR TITLE
Noto Sans Tai Viet: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
2cfd63f: [gftools-packager] Noto Sans Tai Viet: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Tai Viet Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/tai-viet.git at commit https://github.com/notofonts/tai-viet/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
No we do not!

**Comment by simoncozens** [comment]
Updated

## Noto Sans Tai Viet: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

---
 feb67bd: [gftools-packager] Noto Sans Tai Viet: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Tai Viet Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/tai-viet.git at commit https://github.com/notofonts/tai-viet/commit/.

**Comment by RosaWagner** [comment]
Now it doesn't move in Safari, but it moves in chrome and windows

Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
I can't reproduce this; Chrome looks fine locally. I wonder if this is an old version of Chrome which did not put this script through the USE. (Don't know about Windows.)

**Comment by RosaWagner** [comment]
It also looks normal on Edge Windows 11, so i would ignore the gif

**Pull request merged**
