### PR TITLE
Noto Sans Limbu: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
2f96660: [gftools-packager] Noto Sans Limbu: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Limbu Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/limbu.git at commit https://github.com/notofonts/limbu/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Sample text has a dotted circle #5028

**Comment by simoncozens** [comment]
Not a font bug, I’ll look at the text when I get back.

**Comment by chrissimpkins** [comment]
Still requires prod push

**Comment by RosaWagner** [comment]
Tofu in sample text

Capture d’écran 2022-09-28 à 15 03 38

**Comment by simoncozens** [comment]
Dotted circles too, which is unfortunate. (Our sample text is not ideal.) The tofu character is U+0964 DEVANAGARI DANDA. I'll add this character (and DOUBLE DANDA) to the glyphset.

**Pull request merged**
