### PR TITLE
opensans v3.001 added

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR enables the overlap flag bits for glyphs which have overlapping contours. It was created by using [Niko's script](https://github.com/google/fonts/issues/4405#issuecomment-1080664412) and then bumping the version number.

@bungeman Dave Crossland asked me to fix this for every VF in our collection. I've just read through https://github.com/MicrosoftDocs/typography-issues/issues/922 and apart from the woff2 issue, are there any other components that also need updating? I'm assuming that enabling these bits will allow stroked glyphs with overlaps to render correctly? which platforms/rasterizers will be fixed by enabling these bits? happy to make tests if you don't have the answers.

If we're happy that this solves the issue, I'll update all the other VFs in our collection and add this functionality to the build chain.

Part fixes https://github.com/google/fonts/issues/4405

### CODE REVIEW

**Comment by bungeman** [comment]
So the WOFF2 fix was needed just to transmit these bits at all and was a longstanding issue which needed to be fixed anyway. The issue with overlap when stroking and the proposal to use this bit as a signal that the outlines should be automatically simplified (overlap removed) when this bit is set gave a push to implement the WOFF2 change. Note that there are reasons other than simplifying the outline for stroking that this bit should be set (it may change the fill rule from even-odd to non-zero, or select perfect coverage instead of coverage counting rasterization) so it's still a good idea to set it in any event.

Currently (afaik) the only implementation using this bit as a signal to remove overlap in outlines is Skia's FreeType port. This means Android system and Skia on Linux with new enough FreeType. This includes Chrome on Linux, Chrome on Android, and the Android WebView. This went in to Chrome M102, so you'll currently need a Dev or Canary to see the overlap removal change in Chrome or the WebView.

The OpenType issue has been opened to get a general feel for how implementations would like to handle the stroking issue. Currently DirectWrite and CoreText do not surface this bit in their public APIs, which is why Skia has not attempted to implement this yet on Windows or Mac (in theory Skia can go looking for this bit, but it would be best to get this information directly). It may be that these implementations wish to not surface the bit and simplify the outline automatically themselves. It may be that no one wants to use or expose this bit for some reason. It may be that there is some extremely fast way to detect that there is overlap and the bit isn't really needed (though this may or may not be overriding the font author's intent).

**Comment by davelab6** [comment]
Note to GF eng team, this builds on the OFL license change, which wasn't yet pushed in the API.

**Comment by m4rc1e** [comment]
Going to close this since this family is too popular for testing purposes. I've made a pr for Maven Pro instead #4539

**Comment by davelab6** [comment]
@m4rc1e did the Maven release go thru?

**Pull request closed without merging**
