### PR TITLE
Noto Sans Adlam Unjoined: Version 3.001 added

### PR DESCRIPTION
**Pull request by simoncozens**
9df8940: [gftools-packager] Noto Sans Adlam Unjoined: Version 3.001 added

* Noto Sans Adlam Unjoined Version 3.001 taken from the upstream repo https://github.com/notofonts/adlam.git at commit https://github.com/notofonts/adlam/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Something looks suspect with the marls in Chrome

**OS X High Sierra Safari_11**
Desktop_OS_X_High_Sierra_safari_11 1_
**Windows 10 Chrome_71**
Desktop_Windows_10_chrome_71 0_
**Windows 10 Edge_18**
Desktop_Windows_10_edge_18 0_

**Comment by simoncozens** [comment]
See comment on #4934. I think it's fine

**Comment by vv-monsalve** [comment]
In today's meeting, we've decided to move ahead with Adlam projects since the support for this script is really recent, so it's not expected to be supported by legacy environments (browsers - shape engines)

**Comment by vv-monsalve** [comment]
@simoncozens Noto Sans Adlam Unjoined is missing the article

**Comment by vv-monsalve** [comment]
Article reinstated in #5176

**Pull request merged**
