### PR TITLE
Signika: Version 2.001 added

### PR DESCRIPTION
**Pull request by aaronbell**
39dc43b: [gftools-packager] Signika: Version 2.001 added

* Signika Version 2.001 taken from the upstream repo https://github.com/aaronbell/signika at commit https://github.com/aaronbell/signika/commit/9d4b72fabf94c84b54c7f3eb0300bb451d2d0fcf.

 33b0589: [gftools-packager] ofl/signika remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by aaronbell** [comment]
(I pushed from my local repro as this version has the NEGA axis removed, however there's an open PR to the Ancymonic's repro: https://github.com/Ancymonic/Signika/pull/6 and I'll also push a PR to the googlefonts repro)

**Comment by RosaWagner** [comment]
Some top anchors seem to be missing:
marks_missing

**Comment by aaronbell** [comment]
Updated

## Signika: Version 2.001 added

---
 82b4b00: [gftools-packager] Signika: Version 2.001 added

* Signika Version 2.001 taken from the upstream repo https://github.com/aaronbell/signika at commit https://github.com/aaronbell/signika/commit/cae278e3e6f615905abd9fea0f50285a7744a65d.

 f8939c2: [gftools-packager] ofl/signika remove METADATA "source".  google/fonts#2587

**Comment by aaronbell** [comment]
Pushed an update that resolves the anchor propagation.

**Pull request merged**
