### PR TITLE
[Font Bakery Dashboard] create family: Calistoga

### PR DESCRIPTION
**Pull request by vv-monsalve**
[full report](https://fontbakery.graphicore.de/dispatcher/process/7bae7c51-7a53-43fb-8162-be899fb25425)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@vv-monsalve** confirms the family package.

Report…

### Files
 * `Calistoga-Regular.ttf` *128660 Bytes*
 * `DESCRIPTION.en_us.html` *791 Bytes*
 * `METADATA.pb` *469 Bytes*
 * `OFL.txt` *4384 Bytes*

[zip file download](https://fontbakery.graphicore.de/download/persistence/71c34c471ac05aa653a1bdcbcd9e7451296339dc1dfc1ecc7a7da037a1afc96f:0/Calistoga.zip)

### Metadata
**commit** 1bb6e0f18e15d4ff40fe1333aa6b2b6fa595b0a5  
**commitDate** 2019-10-30T21:12:45.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"Calistoga"`  
&emsp;**nameConfirmed** `""`  
&emsp;**upstream** `"https://github.com/SorkinType/Calistoga"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/Calistoga-"`  
&emsp;**genre** `"Display"`  
&emsp;**designer** `"Yvonne Schuttler, Eben Sorkin"`  
**familyPath** fonts  
**repository** https://github.com/SorkinType/Calistoga  
**branch** master  
**googleMasterDir** (unknown)  
**isUpdate** `false`  
**licenseDir** ofl

---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@vv-monsalve** Font Bakery looks good.

Report…

## [Font Bakery Result](https://fontbakery.graphicore.de/report/4eaee585-fd39-4e11-a350-889d7014e7b1)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 5 | 30 | 8 | 118 |
| 0 % | 0 % | 3.11 % | 18.63 % | 4.97 % | 73.29 % |

*created* Wed Oct 30 2019 21:15:23 GMT+0000 (Coordinated Universal Time)<br />
*started* Wed Oct 30 2019 21:15:23 GMT+0000 (Coordinated Universal Time)<br />
*finished* Wed Oct 30 2019 21:15:26 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@vv-monsalve** Diffenator is skipped.

Is a new font on GF

### Task BrowsersDiffsAndPreviews OK

**@vv-monsalve** Browsers diffs and previews are looking good.

Report…

### Preparation Logs
 * `Diffbrowsers version 0.1.6`
 * `Added file "after/Calistoga-Regular.ttf".`
 * `Added file "after/DESCRIPTION.en_us.html".`
 * `Added file "after/METADATA.pb".`
 * `Added file "after/OFL.txt".`

### Results
 * browse report: [**Regular**](https://fontbakery.graphicore.de/browse/persistence/a0537e1690b53c30978d38f3936cc7a6103f33d499a20f950bcd5adf74910c78:0/) or download: [zip file](https://fontbakery.graphicore.de/download/persistence/a0537e1690b53c30978d38f3936cc7a6103f33d499a20f950bcd5adf74910c78:0/Browser%20Diffs_Calistoga_Regular.zip)

Download the [full report zip file](https://fontbakery.graphicore.de/download/persistence/collect/a0537e1690b53c30978d38f3936cc7a6103f33d499a20f950bcd5adf74910c78%3A0%2CRegular/Browser%20Diffs_Calistoga.zip).

*started* Wed Oct 30 2019 21:15:59 GMT+0000 (Coordinated Universal Time)<br />
*finished* Wed Oct 30 2019 21:18:30 GMT+0000 (Coordinated Universal Time)

### CODE REVIEW

**Comment by m4rc1e** [comment]
Vert metrics are too different for each platform.

It may be helpful to read this, https://github.com/googlefonts/fontbakery/issues/2164#issuecomment-436595886

**Comment by vv-monsalve** [comment]
Updated:

---
[full report](https://fontbakery.graphicore.de/dispatcher/process/5f67804e-efdf-4bb5-907b-bc017a542ae1)

# Step # 0 Review the Request and Generate the Files Package

**finished: OK**

All tasks completed successfully.

### Task ApproveProcess OK

**@vv-monsalve** confirms the family package.

Report…

## Files Package for *Calistoga*
### Files
 * `Calistoga-Regular.ttf` *128660 Bytes*
 * `DESCRIPTION.en_us.html` *791 Bytes*
 * `METADATA.pb` *469 Bytes*
 * `OFL.txt` *4390 Bytes*


[zip file download](https://fontbakery.graphicore.de/download/persistence/7477da645d5a55e0fcfc9607d0cb6700e937d227d7b528bca7d88a50e652dc7e:0/Calistoga.zip)


### Metadata
**commit** 396f7f53993c2372763019428e2593a0de8f069a  
**commitDate** 2019-11-04T21:30:17.000Z  
**sourceDetails** 

&emsp;**status** `"OK"`  
&emsp;**name** `"Calistoga"`  
&emsp;**nameConfirmed** `""`  
&emsp;**upstream** `"https://github.com/SorkinType/Calistoga"`  
&emsp;**branch** `""`  
&emsp;**fontfilesPrefix** `"fonts/Calistoga-"`  
&emsp;**genre** `"Display"`  
&emsp;**designer** `"Yvonne Schuttler, Eben Sorkin"`  
**familyPath** fonts  
**repository** https://github.com/SorkinType/Calistoga  
**branch** master  
**googleMasterDir** (unknown)  
**isUpdate** `false`  
**licenseDir** ofl


---

# Step # 1 Quality Assurance

**finished: OK**

All tasks completed successfully.

### Task Fontbakery OK

**@vv-monsalve** Font Bakery looks good.

Report…

## [Font Bakery Result](https://fontbakery.graphicore.de/report/95092182-af77-4f4a-b60d-3fbc08bc1f91)

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | 🛈 INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 5 | 30 | 8 | 118 |
| 0 % | 0 % | 3.11 % | 18.63 % | 4.97 % | 73.29 % |

*created* Mon Nov 04 2019 21:32:11 GMT+0000 (Coordinated Universal Time)<br />
*started* Mon Nov 04 2019 21:32:12 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Nov 04 2019 21:32:15 GMT+0000 (Coordinated Universal Time)

### Task Diffenator OK

**@vv-monsalve** Diffenator is skipped.

Is a new font on GF

### Task BrowsersDiffsAndPreviews OK

**@vv-monsalve** Browsers diffs and previews are looking good.

Vertical Metris adjusted

Report…

## Browser diffs and previews Result
### Preparation Logs
 * `Diffbrowsers version 0.1.6`
 * `Added file "after/Calistoga-Regular.ttf".`
 * `Added file "after/DESCRIPTION.en_us.html".`
 * `Added file "after/METADATA.pb".`
 * `Added file "after/OFL.txt".`

### Results
 * browse report: [**Regular**](https://fontbakery.graphicore.de/browse/persistence/36ad8aa824bbb2840c3fee2a89a9ccc42742d277434fe67522b2a4f2f5810c00:0/) or download: [zip file](https://fontbakery.graphicore.de/download/persistence/36ad8aa824bbb2840c3fee2a89a9ccc42742d277434fe67522b2a4f2f5810c00:0/Browser%20Diffs_Calistoga_Regular.zip)

Download the [full report zip file](https://fontbakery.graphicore.de/download/persistence/collect/36ad8aa824bbb2840c3fee2a89a9ccc42742d277434fe67522b2a4f2f5810c00%3A0%2CRegular/Browser%20Diffs_Calistoga.zip).

*started* Mon Nov 04 2019 21:32:44 GMT+0000 (Coordinated Universal Time)<br />
*finished* Mon Nov 04 2019 21:35:19 GMT+0000 (Coordinated Universal Time)

**Comment by vv-monsalve** [comment]
PR re-ran with adjusted Vertical Metrics

**Comment by m4rc1e** [comment]
LGTM

**Pull request merged**
