### PR TITLE
HOTFIX Mulish v.2.001 added. Changed name Muli to Mulish.

### PR DESCRIPTION
**Pull request by RosaWagner**
Removed Muli folder.

### CODE REVIEW

**Comment by davelab6** [comment]
@RosaWagner thanks! Please could you hotfix the copyright notice in the TTFs to be

    Copyright 2011 The Mulish Project Authors (github.com/googlefonts/mulish)

**Comment by RosaWagner** [comment]
Is there a script with gftools for that ? It doesn't appear in the commands.

**Comment by m4rc1e** [comment]
**Muli[wght]**
```
****names modified: 5****

id                  string_a            string_b            
(0, 3, 1, 1033)     Copyright 2016 T... Copyright 2011 T... 
(1, 3, 1, 1033)     Muli                Mulish              
(3, 3, 1, 1033)     2.100;NONE;Muli-... 2.100;NONE;Mulis... 
(4, 3, 1, 1033)     Muli Regular        Mulish Regular      
(6, 3, 1, 1033)     Muli-Regular        Mulish-Regular      

****attribs modified: 1****

table               attrib              value_a             value_b             
head                modified            2019/01/17 16:30... 2020/06/16 19:59...
```


**Muli-Italic[wght]**
```
****names modified: 5****

id                  string_a            string_b            
(0, 3, 1, 1033)     Copyright 2016 T... Copyright 2011 T... 
(1, 3, 1, 1033)     Muli                Mulish              
(3, 3, 1, 1033)     2.100;NONE;Muli-... 2.100;NONE;Mulis... 
(4, 3, 1, 1033)     Muli Italic         Mulish Italic       
(6, 3, 1, 1033)     Muli-Italic         Mulish-Italic       

****attribs modified: 1****

table               attrib              value_a             value_b             
head                modified            2019/01/17 16:30... 2020/06/16 19:59...
```

LGTM

**Comment by davelab6** [comment]
> Is there a script with gftools for that ?

No.. you are welcome to make one for gftools :)

**Comment by m4rc1e** [comment]
> Is there a script with gftools for that ?

>> No.. you are welcome to make one for gftools :)

Script fixed in https://github.com/googlefonts/gftools/pull/215

**Comment by davelab6** [comment]
Ah, Rosalie's suggestion here is different to the bug you fixed in googlefonts/gftools#215

She is suggesting a similar tool, only for updating the copyright notices.

**Comment by RosaWagner** [comment]
Now I am confused. Isn’t it what update-nameids -c is doing?

**Comment by m4rc1e** [comment]
@RosaWagner yep, you're correct.

Imo we should have better docs for gftools.

**Comment by nrakochy** [comment]
Hi there, 

I am currently using `Muli` in a project and trying to understand the impact of this PR. Does this mean that the name `Muli` has been deprecated and will be dropped?

**Comment by felipesanches** [comment]
If I understood it correctly, old users would still have their requests served with the original name, but new visitors to the gfonts website will get the new font name. So the transition should work transparently.

**Comment by nrakochy** [comment]
I see, thanks. So the change will not break existing functionality but should be updated to use the new name

**Comment by rtd62** [comment]
Is there any differences to the typeface itself? Or is it just the name that has changed? I kind of see a different between the old and new on two different pages that I have, but I can't really tell.

**Comment by fitojb** [comment]
The name was changed for legal reasons AFAICT

**Pull request merged**
