### PR TITLE
STIX Two Text: Version 2.13 b170 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
fed1e56: [gftools-packager] STIX Two Text: Version 2.13 b170 added

* STIX Two Text Version 2.13 b170 taken from the upstream repo https://github.com/stipub/stixfonts at commit https://github.com/stipub/stixfonts/commit/df59aad65b2957b9b5f99b7008db29e0bc6a7065.

 4957260: [gftools-packager] ofl/stixtwotext remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This PR is done to unblock #3255 
Designers was added in #3258

**Comment by RosaWagner** [comment]
STAT table is still incomplete.

- Regular should be elided in Upright style also (<Flags value="2"/> instead of 0, like in Italic)
- Regular and bold should be linked (<LinkedValue value="700.0"/> in Regular for Upright and Italic)

**Comment by tiroj** [comment]
@khaledhosny Can you review this STAT table issue and tweak the build process further?

**Comment by vv-monsalve** [comment]
Updated

## STIX Two Text: Version 2.13 b171 added

---
 845be0b: [gftools-packager] STIX Two Text: Version 2.13 b171 added

* STIX Two Text Version 2.13 b171 taken from the upstream repo https://github.com/stipub/stixfonts_dev at commit https://github.com/stipub/stixfonts_dev/commit/aea8fd51a2458678242f7e570710d0d5d098e684.

 cc953fa: [gftools-packager] ofl/stixtwotext remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
This is an update done from the private `stixfonts_dev` repository to ensure it passes all the test before pushing the latest files into the public repo.

The following comprobations were done to the latest files in the repo:

- [x] Inspecting the STAT table manually, it seems [everything was covered](https://github.com/googlefonts/fontbakery/issues/3090#issuecomment-729753965).
- [x] Inspecting the interpolation for italics in InDesign, is working.
- [x] Use of typo Metrics is enabled.
- [x] OFL and Authors files seem to be ok with the latest fixes included.

**Comment by RosaWagner** [comment]
LGTM, I wait for you to make it not-draft

**Comment by vv-monsalve** [comment]
Updated

## STIX Two Text: Version 2.13 b171 added

---
 51f7da1: [gftools-packager] STIX Two Text: Version 2.13 b171 added

* STIX Two Text Version 2.13 b171 taken from the upstream repo https://github.com/stipub/stixfonts at commit https://github.com/stipub/stixfonts/commit/744a22a4dd626cd14d75728aef34fc8ad7c85db0.

 c58cabe: [gftools-packager] ofl/stixtwotext remove METADATA "source".  google/fonts#2587

**Pull request merged**
