### PR TITLE
Noto Sans Old Hungarian: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
8275d74: [gftools-packager] Noto Sans Old Hungarian: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Old Hungarian Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/old-hungarian.git at commit https://github.com/notofonts/old-hungarian/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
🔥 FAIL: Check samples can be rendered. ([com.google.fonts/check/metadata/can_render_samples](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/can_render_samples))
🔥 FAIL Font can't render "ohu_Hung" sample text:
"𐲪𐲢𐲙𐲔⁝𐲥𐲬𐲖𐲦𐲤𐲦𐲬𐲖⁝𐲌𐲛𐲍𐲮𐲀𐲙⁝𐲐𐲢𐲙𐲔⁝𐲯𐲢𐲞𐲦 ⁝𐲥𐲀𐲯𐲎⁝𐲥𐲦𐲙𐲇𐲞𐲂𐲉⁝𐲘𐲀𐲨𐲤⁝𐲒𐲀𐲙𐲛𐲤⁝𐲤𐲨𐲦𐲙⁝𐲓𐲛𐲮𐲀𐲆⁝𐲆𐲐𐲙𐲀𐲖𐲦𐲔⁝𐲘𐲀𐲨𐲀𐲤𐲘𐲤𐲦𐲢⁝𐲍𐲢𐲍𐲗𐲘𐲤𐲦𐲢𐲆𐲐𐲙𐲀𐲖𐲦𐲀𐲔"

[code: sample-text]


@simoncozens this sign ⁝ is missing
Screenshot 2023-06-27 at 11 13 17

**Comment by simoncozens** [comment]
Updated

## Noto Sans Old Hungarian: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

---
 36c3941: [gftools-packager] Noto Sans Old Hungarian: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Old Hungarian Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/old-hungarian.git at commit https://github.com/notofonts/old-hungarian/commit/.

**Comment by RosaWagner** [comment]
@simoncozens it is still showing tofu in sandbox, tricolon seems to be missing

Screenshot 2023-07-18 at 15 06 04

**Comment by RosaWagner** [comment]
Note to self: to repush to sandbox once nam file is merged and in prod

**Comment by RosaWagner** [comment]
@eliheuer the nam file has been merged so we can unblock this PR and repush to sandbox to trigger the new subset

**Pull request merged**
