### PR TITLE
delete: apache/irishgrowler

### PR DESCRIPTION
**Pull request by davelab6**
Fixes https://github.com/google/fonts/issues/1128

### CODE REVIEW

**Comment by sapics** [comment]
I would like to keep these files for consistency in my project.
It would be enough to mention in DESCRIPTION.en_us.html like Duplicated fonts, isn't it?

**Comment by thlinard** [comment]
Irish Growler doesn't exist anymore in the API.

**Comment by sapics** [comment]
@thlinard 

If this git follows the API, it makes sense.
Previous my comment was just my two cent, I will just revert this commit in my project after this is merged :)

**Comment by rsheeter** [comment]
This git should be viewed as upstream of the API, not following. Either way deleting this makes sense.

**Pull request merged**
