### PR TITLE
hotfix-baloothambi: v1.101 added

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by davelab6** [comment]
@m4rc1e this needs to be closed or reworked using the latest release on https://github.com/EkType/Baloo

**Comment by m4rc1e** [comment]
Closing this.

Updated version here #1042

**Comment by davelab6** [comment]
This is Baloo Thambi, not Baloo (which #1042 covers)

**Comment by m4rc1e** [comment]
Apologies, I did update the previous comment. it now points to #1052 , Baloo Thambi

**Comment by davelab6** [comment]
aha great! :)

**Pull request closed without merging**
