### PR TITLE
alegreyasans: v2.000 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
New version includes Greek and Cyrillic. Thanks @juandelperal

### CODE REVIEW

**Comment by thlinard** [comment]
"UC roman numerals added, fonts not updated yet" for the last commit?

**Comment by m4rc1e** [comment]
@thlinard released from latest upstream pr, https://github.com/huertatipografica/Alegreya-Sans/commit/74aeab859ae718db0df4275a63952f3447df360d

**Comment by thlinard** [comment]
Ah, OK. Thanks Marc.

**Comment by m4rc1e** [comment]
@thlinard thank you for checking these prs! its great to have some peer review.

**Comment by juandelperal** [comment]
Thank you very much guys for all your help here

**Comment by thlinard** [comment]
Thank you Juan for your superb work!

**Comment by juandelperal** [comment]
Marc, I found a compatibility bug in the italics.
Now fixed in https://github.com/huertatipografica/Alegreya-Sans
Do I have to submit the PR or you?
Thanks!

**Comment by m4rc1e** [comment]
@juandelperal Thanks, I'll re pr this tomorrow

@davelab6 keep this open

**Comment by davelab6** [comment]
@m4rc1e I think this is still pending - no worries if so, just checking that I didn't miss it somewhere else :)

**Comment by m4rc1e** [comment]
Its in the pipeline

**Comment by m4rc1e** [comment]
Alright, I've added your Italic fix. Thanks again @juandelperal

**Comment by juandelperal** [comment]
Hi @m4rc1e 
cleaned sc also in the sans.
https://github.com/huertatipografica/Alegreya-Sans/releases/tag/v2.002

Thanks!
j.

**Pull request merged**
