### PR TITLE
Big Shoulders Stencil Display: Version 2.000 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
153c0bc: [gftools-packager] Big Shoulders Stencil Display: Version 2.000 added

* Big Shoulders Stencil Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 7a1bd23: [gftools-packager] ofl/bigshouldersstencildisplay remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This PR upgrades [Big Shoulders Stencil Display](https://fonts.google.com/specimen/Big+Shoulders+Stencil+Display?query=Big) into a Variable Font.
OFL.txt and Description files were added in #3432

**Comment by thlinard** [comment]
Hi @vv-monsalve 

The API will deliver an Extra-Light static file for which the VF doesn't have a corresponding instance.

@RosaWagner has already done a PR to fix a similar problem (https://github.com/googlefonts/rubik/pull/38 to fix #3214, see also #3411): you might as well correct it before release.

**Comment by thlinard** [comment]
Same remark for PR  #3438 #3437 #3435 #3434 #3433 #3432

**Comment by RosaWagner** [comment]
@thlinard I don't know if the missing ExtraLight is intended or not, but sometimes designers don't want to include them. Although it would be nice to have perfect consistency between the STAT and what the API does, and even if we should try to do so as much as possible, it is not always possible and we try to find the best compromise with the designers upstream. If I fixed it before, it was because it could be done for that situation.

**Comment by thlinard** [comment]
> @thlinard I don't know if the missing ExtraLight is intended or not, but sometimes designers don't want to include them. Although it would be nice to have perfect consistency between the STAT and what the API does, and even if we should try to do so as much as possible, it is not always possible and we try to find the best compromise with the designers upstream. If I fixed it before, it was because it could be done for that situation.

Hi @RosaWagner 

Whether the designer approves it or not, there will be an ExtraLight weight, because

> When a variable font is onboarded to Google Fonts, we will provide instantiated static fonts for legacy applications. Thus, bear in mind Google’s API will automatically create all the 100x weights along the used range of the axis when producing static fonts, whether or not they are included in the designer's original design space.
https://github.com/googlefonts/gf-docs/tree/main/Spec#stat-table

The purpose of this PR is to provide "variable fonts containing a wght axis, that 1:1 matches the prior static releases" (#3433): this is a good goal, but in fact this PR, by wanting to achieve this goal, is going to make it fail (because of what the API is doing with VFs, which will give new statics, including an extra weight, ExtraLight). You would better meet the spirit of this goal by providing VFs whose instances 1:1 match the statics provided after release.

I believed for a while that the VF format would appear as more modern and offering more possibilities, but I realized that this is not always the case when my users started complaining about VFs and asking me for statics, to have more weights: please, don't release VFs that have fewer instances than the number of static weights! This will only make the VF appear as a crippled format.

**Comment by vv-monsalve** [comment]
Hello @thlinard. We appreciate your interest in the fonts we serve. Just as all the questions and requests submitted by users, we take notes on the comments received. We evaluate them and eventually will include them in our workflow as we advance with the improvements of our process and tools. However, the priority evaluation and the way and the time in which, if necessary, we address them depends on a series of internal factors to coordinate. Therefore it is not immediate and will depend on the Google Font Team.

Finally, bear in mind that this is a Libre Fonts platform, where we receive many contributions from many sources and motivations. We are not and will not always be in the position of demanding particularities or changes to designers who already completed a huge amount of work.

**Comment by thlinard** [comment]
Hi @vv-monsalve 
I'm well aware of this (maybe you've noticed that I'm not quite a new one here: two months ago, @davelab6 wrote to me to praise my assessments, which I am grateful to him, because I try to help).

I presume we agree that when this PR is pushed to production, users will download an ExtraLight static font, whether its creator objects or not. And I think that will be a problem. The fix I'm suggesting is easy: one line in the Python font script + recompiling, to avoid a lot of trouble down the road.

**Comment by davelab6** [comment]
> when this PR is pushed to production, users will download an ExtraLight static font, whether its creator objects or not. And I think that will be a problem. The fix I'm suggesting is easy: one line in the Python font script + recompiling, to avoid a lot of trouble down the road.

I agree, but I also want to see progress on getting this update out, and despite that it looks like a quick script change and recompile, there's a lot of additional stakeholders and distribution points to keep appraised and in sync for this particular project which make that prohibitive. 

So what I'd like to see is 

* @vv-monsalve merges and pushes this PR to production now
* @vv-monsalve files a bug upstream to address this STAT issue
* @vv-monsalve makes sure that the next time we PR this family, this improvement is made
* @vv-monsalve updates the [Spec](https://github.com/googlefonts/gf-docs/tree/main/Spec) with PRs to include new guidance about avoiding "thinly spread" ranges such that the intermediates are not different enough, and avoid 'gaps' in the ranges; if the designer is thinking of gaps, that probably means they should reduce the range

**Comment by davelab6** [comment]
WHOOPS lol

**Comment by thlinard** [comment]
Thank you Dave!

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Stencil Display: Version 2.000 added

---
 55877c0: [gftools-packager] Big Shoulders Stencil Display: Version 2.000 added

* Big Shoulders Stencil Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 8c09744: [gftools-packager] ofl/bigshouldersstencildisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> * @vv-monsalve merges and pushes this PR to production now

@davelab6 I've spotted a new issue about the weight value in the metadata. It was included as 400 despite the default is the Thin.

``` name: "Big Shoulders Text"
  style: "normal"
  weight: 400
  filename: "BigShouldersText[wght].ttf"
  post_script_name: "BigShouldersText-Thin"
  full_name: "Big Shoulders Text Thin"
```

I'll have to inspect this in detail as the current build schema for this project is from one year ago when we were following an entirely different workflow. I will take this as an opportunity to give `gftools builder` approach a trial for this project. So, despite what we agreed on the call, I'm turning this PR into a draft for now.

On the other hand, I already reported the [requisition of the ExtraLight weight](https://github.com/xotypeco/big_shoulders/issues/36) to the Designer. Perhaps we could include it while switching to Builder.

**Comment by davelab6** [comment]
> Perhaps we could include [the new 200 style] while switching to Builder.

I believe we've agreed to do that with him :)

Generally, I think switching to the builder is a good idea, especially for projects like this where we expect more updates from the designer in the future, and as the builder itself improves, that will propagate to the project and help keep it conformant with our requirements.

**Comment by vv-monsalve** [comment]
> I believe we've agreed to do that with him :)

We have now, this comment was done the same day I wrote him about that :)

Generally, I think switching to the builder is a good idea, especially for projects like this where we expect more updates from the designer in the future, and as the builder itself improves, that will propagate to the project and help keep it conformant with our requirements.

Agree, this was my reasoning to turn this as an opportunity to switch to the builder approach.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Stencil Display: Version 2.001 added

---
 f8ce3f7: [gftools-packager] Big Shoulders Stencil Display: Version 2.001 added

* Big Shoulders Stencil Display Version 2.001 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/c32776c15acba7f76797d45cfeb27d1c2a1738a0.

 e3f4866: [gftools-packager] ofl/bigshouldersstencildisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The font includes now the `ExtraLight` Instance.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Stencil Display: Version 2.001 added

---
 3185d42: [gftools-packager] Big Shoulders Stencil Display: Version 2.001 added

* Big Shoulders Stencil Display Version 2.001 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/2f924dd1205484c5e0054b1f3955f434224ba72e.

 6c5f261: [gftools-packager] ofl/bigshouldersstencildisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The PR was updated to solve STAT table (with no opsz axis) as mentioned in [#3434](https://github.com/google/fonts/pull/3432#issuecomment-880703015)

**Pull request merged**
