### PR TITLE
Spectral: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/productiontype/Spectral at commit https://github.com/productiontype/Spectral/commit/e1179c4fc05c1ba7efd40038e203312b4c90c376.
## PR Checklist:

- [ ] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [ ] `tags` are added for NEW FONTS
- [ ] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by m4rc1e** [comment]
Continues #8340

**Comment by vv-monsalve** [comment]
@emmamarichal, please confirm the following changes:

- `U+1FEE Greek Dialytika and Oxia` placement
- `U+2116 Numero Sign` typically this sign is related to typographic shapes and not currency symbols
- Ligatures are no longer working
- Hinting: I can confirm Marc's comment on the rendering height jump in Windows. It happens at 16pt (changing the size in the Elements panel). 


spectral-suspicious-changes

spectral-hinting-regular-16pt

**Comment by vv-monsalve** [comment]
@m4rc1e, @emmamarichal. Once merged, the changes here could continue to be tracked by the original #8340, so I removed this one from the Traffic Board.

**Comment by emmamarichal** [comment]
- U+1FEE Greek Dialytika and Oxia placement
I already checked, the anchors didn't changed from the previous version. I don't know why it changed, but since the font doesn't support greek, I ignored it.

All of this is intentional and are design changes:
- U+2116 Numero Sign typically this sign is related to typographic shapes and not currency symbols
- Ligatures are no longer working

> Hinting: I can confirm Marc's comment on the rendering height jump in Windows. It happens at 16pt (changing the size in the Elements panel).

@m4rc1e was making some tests, I think it's a question of ttfa version. @m4rc1e Is is solvable?

**Comment by m4rc1e** [comment]
Unfortunately this isn't solvable since ttfa calculates cvts based on the design of the font. Since the design has changed, we get different cvts, hence the height change.

**Pull request merged**
