### PR TITLE
Playball: Version 1.001 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
9185f94: [gftools-packager] Playball: Version 1.001 added

* Playball Version 1.001 taken from the upstream repo https://github.com/googlefonts/play-ball at commit https://github.com/googlefonts/play-ball/commit/ff97e9fd2f9222eeea988765d6cf1d5b9c39e677.

 ab34af2: [gftools-packager] ofl/playball remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Font Update. Part of Batch 1 of TypeSetIt projects

> 🔥 FAIL: Are there caret positions declared for every ligature?
> 🔥 FAIL: Is there kerning info for non-ligated sequences?

Related to: https://github.com/googlefonts/fontbakery/issues/3131#issuecomment-821237145

**Comment by m4rc1e** [comment]
LGTM. Thanks!

**Comment by RosaWagner** [comment]
This one still has TypeSETIt as designer, it's ok?

**Comment by vv-monsalve** [comment]
> This one still has TypeSETIt as designer, it's ok?

It is listed ok in the [metadata file](https://github.com/google/fonts/blob/ab34af278592c54a1daf014030b5e883f2ed5f16/ofl/playball/METADATA.pb) though.

What we are realising now reviewing it with Rosalie is that the font version didn't increase and wasn't report as a Fail by FB  under `0.7.34` as reported in [FB#3172](https://github.com/googlefonts/fontbakery/issues/3172) issue

**Pull request merged**
