### PR TITLE
Yuji Syuku: Version 3.001; Yuji Mai: Version 3.001; Yuji Boku: Version 3.001;

### PR DESCRIPTION
**Pull request by aaronbell**
a52a06a: [gftools-packager] Yuji Syuku: Version 3.001; ttfautohint (v1.8.3) added

* Yuji Syuku Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.

 d8aeee5: [gftools-packager] Yuji Mai: Version 3.001; ttfautohint (v1.8.3) added

* Yuji Mai Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.

 0a08e71: [gftools-packager] Yuji Boku: Version 3.001; ttfautohint (v1.8.3) added

* Yuji Boku Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.

 e1cd34f: [gftools-packager] Yuji Hentaigana Akebono: Version 3.001; ttfautohint (v1.8.3) added

* Yuji Hentaigana Akebono Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.

 b32e312: [gftools-packager] Yuji Hentaigana Akari: Version 3.001; ttfautohint (v1.8.3) added

* Yuji Hentaigana Akari Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.

### CODE REVIEW

**Comment by davelab6** [comment]
@aaronbell it looks like these were ttfautohinted, but I expect this may add filesize to the fonts and does little to improve Windows rendering for the display latins, and nothing for the CJK. What do you think about removing the hints and using the "non hinting" approach?

**Comment by davelab6** [comment]
For sets of fonts like this, I'd like to add an unordered list element to the DESC file, which has links to all the others in the set, except the current one. One example:

https://fonts.google.com/specimen/Baloo+2#about

**Comment by aaronbell** [comment]
Added the ul to the description. I'm not 100% sure I got the URLS correct, but I took a crack at it :)

**Comment by m4rc1e** [comment]
Do we care that the author's name is in family name? from what I can remember, we don't want foundry names in the family name?

**Comment by aaronbell** [comment]
In this case, “Kinuta” is the foundry name. The different fonts are based on different styles by the calligrapher “Yuji”.

Essentially the same as like “Snell Roundhand”.

**Comment by RosaWagner** [comment]
yujihentaiganaakari and yujihentaiganaakariebono have smaller glyphsets, maybe they should be in a separate PR in case they get blocked in sandbox?

**Comment by RosaWagner** [comment]
@aaronbell can you put the fonts with a reduced glyphset in another PR? So we can block it in sandbox…

**Comment by aaronbell** [comment]
@RosaWagner I've removed the Hentaigana fonts from the set and will submit them separately. :)

**Comment by aaronbell** [comment]
Updated

## Yuji Syuku: Version 3.002 added; Yuji Boku: Version 3.002 added; Yuji Mai: Version 3.002 added

---
 582f696: [gftools-packager] Yuji Boku: Version 3.002 added

* Yuji Boku Version 3.002 taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/efec977b14b57c19eb85d468edcfbbad13139e67.

 a1d7e86: [gftools-packager] ofl/yujiboku remove METADATA "source".  google/fonts#2587

 4d2e709: [gftools-packager] Yuji Mai: Version 3.002 added

* Yuji Mai Version 3.002 taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/efec977b14b57c19eb85d468edcfbbad13139e67.

 f7d4cb5: [gftools-packager] ofl/yujimai remove METADATA "source".  google/fonts#2587

 ad2095e: [gftools-packager] Yuji Syuku: Version 3.002 added

* Yuji Syuku Version 3.002 taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/efec977b14b57c19eb85d468edcfbbad13139e67.

 6f9dd43: [gftools-packager] ofl/yujisyuku remove METADATA "source".  google/fonts#2587

**Comment by aaronbell** [comment]
Updated these with versions set to decompose transformed components.

**Comment by RosaWagner** [comment]
Description are missing the links to the other fonts of the family.
Since the 2 kana-only families won't be pushed to prod at the same time, better not to include their links.

**Comment by aaronbell** [comment]
Updated the metadata / description files. :)

**Pull request merged**
