### PR TITLE
Kapakana: Version 1.000 added

### PR DESCRIPTION
**Pull request by aaronbell**
359199a: [gftools-packager] Kapakana: Version 1.000 added

* Kapakana Version 1.000 taken from the upstream repo https://github.com/nagamaki008/kapakana.git at commit https://github.com/nagamaki008/kapakana/commit/a67631c34287778228898d27a6a085bb4cbd8f83.

 00778bd: [gftools-packager] ofl/kapakana remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by m4rc1e** [comment]
There's no Kana in this font. If this is intentional, please update the description.

**Comment by aaronbell** [comment]
@m4rc1e What do you mean? It has a set of Kana here:

Screenshot_12_23_20__8_39_AM

Unconventional, perhaps, but still kana :).

**Comment by m4rc1e** [comment]
Any reason why we're not following our CJK metric schema for this family?

**Comment by aaronbell** [comment]
https://github.com/nagamaki008/kapakana/issues/10

**Comment by m4rc1e** [comment]
Thanks!

**Comment by m4rc1e** [comment]
I may be dense here but how legible is the Kana? and would it be something people will even use?

Right now I'm hesitant to push this family because I don't know if the quality is good enough.

**Comment by emmamarichal** [comment]
@m4rc1e @chrissimpkins @davelab6 I remove this PR from the project board, don't hesitate to change that if you think we should onboard it.

The sandbox still showing tofu, but this is not a sample text issue. The glyphset misses the IDEOGRAPHIC COMMA.
Also, I'm agree with @m4rc1e 

> Right now I'm hesitant to push this family because I don't know if the quality is good enough.

I'm not an expert in katakana, but here is an exemple of what the font looks like (and what it's supposed to like to, for the uni30F4):
Screenshot 2024-02-01 at 15 29 28

**Comment by aaronbell** [comment]
I think it would be better to ask a native speaker their opinion on the font’s legibility rather than making a decision one way or another on our own. 

And if there are characters missing that you feel are necessary, feel free to open an issue on the project github repro to let the designer respond.

This is certainly an unusual design and different from the norm of Japanese fonts, but I don’t think that automatically excludes it from potential inclusion.

**Comment by emmamarichal** [comment]
@aaronbell Yes, sorry, I went a bit fast, I didn't see your explanation above. Let me check with the upstream repo

**Comment by emmamarichal** [comment]
issue opened here: https://github.com/nagamaki008/kapakana/issues/13

**Comment by vv-monsalve** [comment]
The designer is consulting with an engineer to solve the problem.

**Comment by emmamarichal** [comment]
@chrissimpkins this is a project where Aaron can help!

**Pull request merged**
