### PR TITLE
hotfix-abeezee: v1.002 added

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by davelab6** [comment]
@m4rc1e lines 7 and 16 of METADATA are unwanted changes, and I suspect the file has the same unwanted 'name' table change. Please check and update :)

**Comment by m4rc1e** [comment]
@davelab6 The font names are good.

screen shot 2017-05-08 at 15 44 59

The problem is in add_font.py. It relies on a family name parser which splits the [camelcase](https://github.com/google/fonts/blob/master/tools/util/google_fonts.py#L349-L364).

I'll fix it by hand for the time being. The family name should be taken from the nametable imo.

**Comment by davelab6** [comment]
OK cool - FB has an exceptions list for the unusual (un camel casable) families we have.

**Comment by m4rc1e** [comment]
@davelab6, I'll do this for other camelcase names which should be ignored, e.g VT323.

**Pull request merged**
