### PR TITLE
Montagu Slab: Version 1.000 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
8f2e615: [gftools-packager] Montagu Slab: Version 1.000 added

* Montagu Slab Version 1.000 taken from the upstream repo https://github.com/floriankarsten/montagu-slab at commit https://github.com/floriankarsten/montagu-slab/commit/317bc2344f39f20620fae2424afc645aff7ab0ef.

 e3212a7: [gftools-packager] ofl/montaguslab remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Montagu Slab is a new commissioned Font

**Comment by m4rc1e** [comment]
Thanks. LGTM.

**Comment by RosaWagner** [comment]
While pushing to sandbox, Rod noted: 
```
10/4 held Montagu Slab due to:
opsz must declare an api default or support the axis registry default
fsSelection bold should be 0, is 1
```
Indeed postscript name is bold

**Comment by vv-monsalve** [comment]
> opsz must declare an api default or support the axis registry default

The intended default position for Montagu is `wght: 700` `opsz: 144`
`144 pt` is a value registered in the Axis Registry

<br>

> fsSelection bold should be 0, is 1
Screen Shot 2021-10-07 at 13 07 22

fsSelection bits are `5 Bold` + `7 use of typo metrics`


<br>

> Indeed postscript name is bold

The default position is Bold, so PostScript name Bold is therefore intended

I don't see any situation outside of what was expected or possible.
@rsheeter could you please elaborate on the comments of why was Montagu held?

**Comment by davelab6** [comment]
@rsheeter I think "fsSelection bold should be 0, is 1" is pre vf and is now false negative. 

I think @vv-monsalve can update the metadata file to declare the default, I'll meet with you next week to discuss and update the docs so this is more clear

**Comment by rsheeter** [comment]
For context I believe the fsSelection check predates the existence of VF so it's not entirely surprising it doesn't handle them correctly

**Comment by davelab6** [comment]
@nathan-williams has updated the internal check

**Pull request merged**
