### PR TITLE
Update axis registry: YEAR, ELSH, ELGR

### PR DESCRIPTION
**Pull request by vv-monsalve**
git subtree pull of:

- https://github.com/googlefonts/axisregistry/pull/53
- https://github.com/googlefonts/axisregistry/pull/56
- https://github.com/googlefonts/axisregistry/pull/78

@chrissimpkins, @davelab6, @RosaWagner

### CODE REVIEW

**Comment by RosaWagner** [comment]
Element Grid appears two times in sandbox

Capture d’écran 2022-10-05 à 13 14 02

cc @chrissimpkins

**Comment by chrissimpkins** [comment]
Will you please link the page where you are seeing this?

**Comment by vv-monsalve** [comment]
> Will you please link the page where you are seeing this?

Hi Chris, it is in Sandbox dev under /variablefonts#axis-definitions

**Comment by chrissimpkins** [comment]
Thank you very much!  I reported it to the Fonts front end eng team and opened https://github.com/google/fonts/issues/5398 to track it.  I don't see a general purpose "bug" label for the issue.  Mind updating with any labels that are appropriate for you to prioritize it?

**Comment by vv-monsalve** [comment]
There is one `I Font Bug` but it doesn't apply here. I've added `Tools / Workflow` and `Needs upstream resolution` for the time being. 
- Since it is an API fix, who should be assigned?
- We only have a `---API Tofu` Is it worth to include a new label like `-- API fix needed`?

**Comment by chrissimpkins** [comment]
Assigned myself.  OK to add new labels if that helps you.  Not necessary for my own tracking.  Thanks!

**Pull request merged**
