### PR TITLE
Zen Maru Gothic: Version 1.002 added

### PR DESCRIPTION
**Pull request by aaronbell**
ab796be: [gftools-packager] Zen Maru Gothic: Version 1.002 added

* Zen Maru Gothic Version 1.002 taken from the upstream repo https://github.com/googlefonts/zen-marugothic.git at commit https://github.com/googlefonts/zen-marugothic/commit/decae11c15a25910ded2a06a9d27ee01c4addc76.

### CODE REVIEW

**Comment by aaronbell** [comment]
Updated

## Zen Maru Gothic: Version 1.001 added

---
 633bf7f: [gftools-packager] Zen Maru Gothic: Version 1.001 added

* Zen Maru Gothic Version 1.001 taken from the upstream repo https://github.com/googlefonts/zen-marugothic.git at commit https://github.com/googlefonts/zen-marugothic/commit/decae11c15a25910ded2a06a9d27ee01c4addc76.

**Comment by aaronbell** [comment]
This is a minor modification to the Regular weight only of Zen Maru Gothic. 

In particular, unicode 6C42 is missing a stroke in the upper right:
スクリーンショット 2023-02-15 14 00 44

Is now: 
Screen Shot 2023-02-22 at 9 32 25 PM

**Comment by m4rc1e** [comment]
@aaronbell Is this issue in the other weight or only the Regular?

**Comment by aaronbell** [comment]
@m4rc1e  only the regular.

**Comment by RosaWagner** [comment]
@aaronbell please next time bump up the version number of the entire family, this is too confusing.

**Pull request merged**
