### PR TITLE
Noto Sans Zanabazar Square: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
0cd6aa6: [gftools-packager] Noto Sans Zanabazar Square: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Zanabazar Square Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/zanabazar-square.git at commit https://github.com/notofonts/zanabazar-square/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens 

Safari
Desktop_OS_X_High_Sierra_safari_11 1_

Windows
Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
Oh, that's really bad.

**Comment by simoncozens** [comment]
Please wait until 2.005.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Zanabazar Square: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

---
 d32aa06: [gftools-packager] Noto Sans Zanabazar Square: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Zanabazar Square Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/zanabazar-square.git at commit https://github.com/notofonts/zanabazar-square/commit/.

**Comment by RosaWagner** [comment]
@simoncozens The diff is still strange

marks_missing
mkmks_missing

**Comment by simoncozens** [comment]
I'm not sure I trust diffenator here. The text is rendering fine on Safari and Chrome. It's just that now we are not using mkmk for mark-to-mark attachment; as this is a USE font we use blwm instead.

**Comment by RosaWagner** [comment]
@simoncozens 

Previous version in sandbox:
Capture d’écran 2022-10-28 à 17 50 08


New version in dev-sandbox:
Capture d’écran 2022-10-28 à 17 50 13

**Comment by simoncozens** [comment]
Sample text looks broken. Virama+mark doesn’t make sense.

**Pull request merged**
