### PR TITLE
Alumni Sans Collegiate One SC: Version 1.100 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/googlefonts/alumni-sans-collegiate at commit https://github.com/googlefonts/alumni-sans-collegiate/commit/9dc96be1ead732fb1677c88632665e0bbf2e4ee2.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
The SC fonts are automatically created from the non-SC fonts, so they do not cover update fixes. They should probably be done "upstream" later on.

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@simoncozens I added the SC reference to the Description file. After that, LGTM. 
However, the CI run is not working now. I'll wait until we hear from Marc on that.

**Comment by vv-monsalve** [comment]
The PR must be rebased for the CI to work with the latest changes. However, I got the QA files from yesterday, and they were okay, so I'm merging this now.

**Comment by vv-monsalve** [comment]
@simoncozens Looks like the font is missing the space


Screen Shot 2024-05-31 at 13 52 45

**Comment by simoncozens** [comment]
Huh, the problem with this font is that it has a "space.sc"! It's a bug with the parent font too:

Screenshot 2024-06-01 at 18 13 14

**Comment by vv-monsalve** [comment]
Arf! It isn't needed. Could you remove it?

**Comment by emmamarichal** [comment]
@simoncozens @vv-monsalve Is that font needs a new PR? should I stop tracking this one?

**Comment by vv-monsalve** [comment]
@emmamarichal I can update the font without the unnecessary `space.sc`. However, all the SC fonts should not go beyond the Sandbox server. We can add a 'blocked' status for now.

**Comment by emmamarichal** [comment]
@vv-monsalve Ok great, thank you!

**Pull request merged**
