### PR TITLE
Update URL of Sortsmill source repository in descriptions

### PR DESCRIPTION
**Pull request by fitojb**
This is a trivial change to the descriptions of the fonts Fanwood Text, Linden Hill and Prociono.

### CODE REVIEW

**Comment by fitojb** [comment]
I’ve signed the CLA.

**Comment by fitojb** [comment]
Ping?

**Comment by davelab6** [comment]
@fitojb sorry I missed this, I will tend to it soon :)

**Comment by davelab6** [comment]
Thanks again @fitojb :)

**Pull request merged**
