### PR TITLE
Noto Sans Arabic: Version 2.010 added

### PR DESCRIPTION
**Pull request by simoncozens**
c81407f: [gftools-packager] Noto Sans Arabic: Version 2.010 added

* Noto Sans Arabic Version 2.010 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

### CODE REVIEW

**Comment by m4rc1e** [comment]
There are quite a lot of design changes so I'm hesitant to merge this one.

Desktop_Windows_10_chrome_71 0_

overall it looks better but I think this mark position is too loose.


Screenshot 2022-07-06 at 14 35 39
**Before**

Screenshot 2022-07-06 at 14 35 21
**After**

**Comment by simoncozens** [comment]
OK. @nizarsq, were you involved in recent changes to Noto Sans Arabic? (Your name is on the credits...) If so, could you confirm you are happy with:

* the positioning of small tah on ddal/rreh? It does look quite high.
* the new kerning of alif/lam and alif/beh-shapes.
* the shortened tail of the bari ye
* the placement of dots on the ng

If this is all by design, no problem, and we can go ahead. But we want to make sure these design changes are OK - especially the kerning, because I don't know if that's by design or if we have messed something up in the process.

**Comment by simoncozens** [comment]
Oh, apparently this was @arabictype. Nadine, could you please confirm the questions above? Thanks.

**Comment by arabictype** [comment]
@simoncozens I haven't touched this project in years so no clue what the background is...

**Comment by simoncozens** [comment]
Ah, OK. Sorry to bother you!

**Comment by Gue3bara** [comment]
I ran a quick test for the marks and noticed the following issues: 

- uni0615 positioning is too high and inconsistent with other marks across the font 
Screen Shot 2022-07-30 at 1 23 28 PM

- uni0653 is too high at most points and overlaps with lam alef hamza above 

Screen Shot 2022-07-30 at 1 16 46 PM
Screen Shot 2022-07-30 at 1 16 38 PM

**Comment by arabictype** [comment]
This is definitely not how the marks were designed and not sure what updates have been made since then but they definitely need fixing!

**Comment by nizarsq** [comment]
Hello everyone,
@simoncozens sorry for the delay in response. I can see the issue with uni0615(sitting a little too high). Not sure if there are any recent changes to the font/uni0615. I’m trying to find my notes (back to May 2021) but I don’t see any related work on uni0615. I looked at the last version I have and the uni0615 sits at a reasonable height, I believe the last version I have is 2.007 and it seems to be ok. @marekjez86 to check if there was any work done to uni0615 in our notes that I can't find.

This issue should be easy/quick fix.


Screen Shot 2022-07-30 at 7 19 23 AM

**Comment by nizarsq** [comment]
Seems to be regression. I believe I fixed this  issue fixed in 2.004, https://github.com/notofonts/arabic/issues/73 Not sure what happened.
Screen Shot 2022-07-30 at 7 57 18 AM

**Pull request closed without merging**
