### PR TITLE
Noto Kufi Arabic: Version 2.108 added

### PR DESCRIPTION
**Pull request by simoncozens**
a002dcf: [gftools-packager] Noto Kufi Arabic: Version 2.108 added

* Noto Kufi Arabic Version 2.108 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Vertical metrics have changed? other than that, LGTM.

diffbrowsers_text-Windows-10-10 0 20348-SP0_firefox_118 0 1

Are the default Arabic figures now tabular?

**Comment by simoncozens** [comment]
Metric regression is bad. Yes, we're going with tabular digits to match Noto Sans and Serif.

**Comment by simoncozens** [comment]
Okay. It looks like the vertical metrics change actually happened a long time ago.

GF prod has 2.102.
2.105 (March 2021) has 1282/-615.
2.106 (June 2021) has hhea/win/typo ascents 1374/-738.

This 2.106 version is in the GF repo but presumably not pushed into prod because of the regression.

I guess if we want to make progress on onboarding we have to put the metrics back to what they were? I don't really want to have different metrics for the GF build as for the "Noto" build but that's another option I can do if needed.

Opinions, @khaledhosny?

**Comment by RosaWagner** [comment]
@simoncozens can we go back with previous vertical metrics?

**Comment by simoncozens** [comment]
Fine with me. It's not in Android so we won't mess them up. I'll set the metrics and re-release.

**Comment by RosaWagner** [comment]
@simoncozens did you have the chance to re-release with the old v metrics?

**Comment by emmamarichal** [comment]
@simoncozens Sorry for all my comments, I'm trying to move on with all the Noto PRs!
Did you have the time to check this one? Thanks!

**Comment by simoncozens** [comment]
Updated

## Noto Kufi Arabic: Version 2.109 added

---
 1ad6a0d: [gftools-packager] Noto Kufi Arabic: Version 2.109 added

* Noto Kufi Arabic Version 2.109 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

**Pull request merged**
