### PR TITLE
Noto Sans Syloti Nagri: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
1447760: [gftools-packager] Noto Sans Syloti Nagri: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Syloti Nagri Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/syloti-nagri.git at commit https://github.com/notofonts/syloti-nagri/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
`Noto Sans Syloti Nagri v2.004 This release fixes a number of issues with attachment of accents to the dotted circle glyph. (#7)`

**Review by RosaWagner — APPROVED** [review]

**Comment by RosaWagner** [comment]
@simoncozens this family still shows tofu in dev-sandbox. The missing glyphs seems to be `avagraha-beng (09BD)`
Screenshot 2023-09-07 at 12 16 47

**Comment by simoncozens** [comment]
Sample text for Syloti Nagri is still Sanskrit. I need to ask @SKing-2003 to find a new one...

**Comment by emmamarichal** [comment]
@simoncozens Did you ask for a new sample text? 
I also read this issue: https://github.com/googlefonts/lang/pull/105, do we need to do something there too in order to unblock this PR?

**Comment by simoncozens** [comment]
We currently have a good sample text for Syloti Nagri (syl_Sylo) and a bad one (sa_Sylo). We need to remove the bad one. I'll do that now.

**Comment by m4rc1e** [comment]
Tofus are still visible on dev server. Keeping this blocked.

Screenshot 2024-04-26 at 15 19 33

**Comment by vv-monsalve** [comment]
@simoncozens Is the change introduced in pull request #7248 the only one needed, or is something else missing? The font still shows tofu on the development server even though that pull request has been merged.

**Comment by simoncozens** [comment]
Putting the changed language in the push lists should do it, although eng may also need to repush the font afterwards, I'm not sure.

**Comment by chrissimpkins** [comment]
@nyshadhr9 possible to weigh in on the process that we need to follow here?

**Comment by nyshadhr9** [comment]
I deleted sa_Sylo from dev and the specimen page now seems to be displaying the correct sample text.

**Comment by vv-monsalve** [comment]
Thanks @nyshadhr9. I can confirm it looks okay now in dev-server

Is something else needed for the other servers as we advance?

**Pull request merged**
