### PR TITLE
lemonada: v4.005 added.

### PR DESCRIPTION
**Pull request by eliheuer**
Taken from the upstream repo https://github.com/eliheuer/Lemonada/tree/gf-mastering
at commit https://github.com/eliheuer/Lemonada/commit/184ab5bf683491607cdd50b3c7b4de520b5bc274

### CODE REVIEW

**Comment by m4rc1e** [comment]
ping @eliheuer

**Comment by m4rc1e** [comment]
glyphs_modified

Gaf bar still shifted.

Vert metrics on Win are incorrect.

Desktop_Windows_10_chrome_69 0_

We'll pair on your fonts next week. Sorry I've been quite busy this week.

**Comment by m4rc1e** [comment]
@eliheuer I found the issue with your vert metrics. The OS/2.sTypoDescender isn't a negative number. Change it from 653 to -653.

**Comment by eliheuer** [comment]
@marc I fixed the OS/2.sTypoDescender and also the one remaining fail: Checking OS/2 usWeightClass.

So this is ready for a merge review again, thanks!

From: `git@github.com:eliheuer/Lemonada.git`
At commit:  `0a5c299a8de73e8a0cc7fff5be2649cc8d010ae5`
Built with the following, run from the Git repo root directory:
`sources/scripts/build.sh && sources/scripts/pull-request.sh`

**Comment by m4rc1e** [comment]
Metadata file needs updating to:

```
name: "Lemonada"
designer: "Multiple Designers"
license: "OFL"
category: "DISPLAY"
date_added: "2016-06-20"
fonts {
  name: "Lemonada"
  style: "normal"
  weight: 400
  filename: "Lemonada[wght].ttf"
  post_script_name: "Lemonada-Regular"
  full_name: "Lemonada Regular"
  copyright: "Copyright 2011 The Lemonada Project Authors (https://github.com/Gue3bara/Lemonada)"
}
subsets: "arabic"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
axes {
  tag: "wght"
  min_value: 300.0
  default_value: 400.0
  max_value: 700.0
}

```

Also mention in the description that the family is now a vf.

Sorry these checks will be triggered once I fix how gftools qa fetches the fonts.

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.14

<details>
<summary><b>[3] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Ensure METADATA.pb lists all font binaries </summary>

* [com.google.fonts/check/metadata/undeclared_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/undeclared_fonts)
* 🔥 **FAIL** The file "Lemonada-Light.ttf" declared on METADATA.pb is not available in this directory. [code: file-missing]
* 🔥 **FAIL** The file "Lemonada[wght].ttf" is not declared on METADATA.pb [code: file-not-declared]

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb: According Google Fonts standards, families should have a Regular style.</summary>

* [com.google.fonts/check/metadata/has_regular](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/has_regular)
* 🔥 **FAIL** This family lacks a Regular (style: normal and weight: 400) as required by Google Fonts standards. [code: lacks-regular]

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb: Font filenames match font.filename entries?</summary>

* [com.google.fonts/check/metadata/filenames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/filenames)
* 🔥 **FAIL** Filename "Lemonada-Light.ttf" is listed on METADATA.pb but an actual font file with that name was not found. [code: file-not-found]
* 🔥 **FAIL** Filename "Lemonada[wght].ttf" is not declared on METADATA.pb as a font.filename entry. [code: file-not-declared]

</details>
<br>
</details>
<details>
<summary><b>[6] Lemonada[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please mention in the DESCRIPTION.en-us.html that the family is a variable font. This check expects the words 'variable font' to be present in the text e.g 'This font is now available as a variable font.' [code: should-mention-varfonts]

</details>
<details>
<summary>🔥 <b>FAIL:</b> DESCRIPTION.en_us.html must have less than 1000 bytes.</summary>

* [com.google.fonts/check/description/max_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/max_length)
* 🔥 **FAIL** DESCRIPTION.en_us.html must have size smaller than 1000 bytes. [code: too-long]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
* ⚠ **WARN** ttfautohint used in font = 1.8.2; installed = 1.8.3; Need to re-run with the newer version! [code: old-ttfa]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
	* ('uni0337', 21.1, 30.5)
	* ('uni0337', 18.0, 30.5) and ('uni0337', 25.3, 30.5)

This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message. [code: points-out-of-bounds]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 5 | 4 | 53 | 7 | 92 | 0 |
| 0% | 3% | 2% | 33% | 4% | 57% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [lemonada_qa2.zip](http://35.188.158.120/media/186ccebb-fe29-43ea-9bff-7543915437e4/lemonada_qa2.zip)

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.14

<details>
<summary><b>[4] Lemonada[wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
* ⚠ **WARN** ttfautohint used in font = 1.8.2; installed = 1.8.3; Need to re-run with the newer version! [code: old-ttfa]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
	* ('uni0337', 21.1, 30.5)
	* ('uni0337', 18.0, 30.5) and ('uni0337', 25.3, 30.5)

This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message. [code: points-out-of-bounds]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 4 | 35 | 7 | 115 | 0 |
| 0% | 0% | 2% | 22% | 4% | 71% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [lemonada_qa4.zip](http://35.188.158.120/media/c27710e7-7ad7-4972-be42-09b247f3c019/lemonada_qa4.zip)

**Comment by m4rc1e** [comment]
Your percent sign is off.

Screenshot 2019-10-30 at 11 01 55

**Comment by eliheuer** [comment]
I had to make some edits to the description to add the fact that it is now a variable font and keep it under the character limit.

@Gue3bara here is the updated description, let me know if you have any feedback or edits you want.

<hr>

Lemonada is a modern Arabic and Latin typeface family designed by Mohamed Gaber and Eduardo Tunni. It started with the Latin design [Lemon](https://fonts.google.com/specimen/Lemon), which Eduardo Tunni expanded to four weights. The Arabic was designed by Mohamed Gaber.

The Arabic design is contemporary, starting with Naskh and introducing influences of Diwani. It has wide and open counters that improve readability at smaller text sizes, while its more subtle details make it a great display face at larger sizes.

Lemonada is currently available as a variable font with a weight axis, four static fonts (Light, Regular, SemiBold, Bold), and a wide character set that supports the Arabic, Farsi, and Urdu languages.

The Lemonada project is led by Mohamed Gaber, a type designer based in Cairo, Egypt. To contribute, see [github.com/Gue3bara/Lemonada](https://github.com/Gue3bara/Lemonada)

**Comment by m4rc1e** [comment]
LGTM Thanks!

**Comment by RosaWagner** [comment]
The content of this PR never went to sandbox nor production.
cc @m4rc1e

**Pull request merged**
