### PR TITLE
girassol: v1.004 added

### PR DESCRIPTION
**Pull request by yanone**
This is a second PR from my own branch, as previously it was submitted by Liam.
The font is now unhinted and the description file properly HTML-formatted.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Whats the point of commit fb1d170?

**Comment by m4rc1e** [comment]
Have you sent a PR to Liam's repo? we want your changes in the source upstream.

**Comment by yanone** [comment]
> Whats the point of commit fb1d170?

I was trying to update my own fork. Went in the wrong direction, I guess? Please delete this if it's nonsensical.

> Have you sent a PR to Liam's repo? we want your changes in the source upstream.

I have now: https://github.com/liamspradlin/Girassol-Display/pull/8
I get mixed signals on whether it is actually necessary to submit PR to the upstream repo before submitting a PR to GF, so I wanted to do it afterwards this time.

**Comment by m4rc1e** [comment]
> I was trying to update my own fork. Went in the wrong direction, I guess? Please delete this if it's nonsensical.

I've pushed an update which removes this commit.

Learning how to rebase, squash and drop are incredibly valuable skills. If you still struggle with them, it really helps to dedicate some time to figure it out away from complex projects.

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.15

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** ftxvalidator is not available.

</details>
<br>
</details>
<details>
<summary><b>[9] Girassol-Regular.ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Does DESCRIPTION file contain broken links?</summary>

* [com.google.fonts/check/description/broken_links](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/broken_links)
<pre>--- Rationale ---

The snippet of HTML in the DESCRIPTION.en_us.html file is added to the font
family webpage on the Google Fonts website. For that reason, all hyperlinks in
it must be properly working. 


</pre>

* 💔 **ERROR** Failed with XMLSyntaxError: Opening and ending tag mismatch: html line 1 and p, line 3, column 5 (<string>, line 3)

</details>
<details>
<summary>💔 <b>ERROR:</b> Does DESCRIPTION file contain a upstream Git repo URL?</summary>

* [com.google.fonts/check/description/git_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/git_url)
<pre>--- Rationale ---

The contents of the DESCRIPTION.en-us.html file are displayed on the Google
Fonts website in the about section of each font family specimen page.

Since all of the Google Fonts collection is composed of libre-licensed fonts,
this check enforces a policy that there must be a hypertext link in that page
directing users to the repository where the font project files are made
available.

Such hosting is typically done on sites like Github, Gitlab, GNU Savannah or
any other git-based version control service.


</pre>

* 💔 **ERROR** Failed with XMLSyntaxError: Opening and ending tag mismatch: html line 1 and p, line 3, column 5 (<string>, line 3)

</details>
<details>
<summary>🔥 <b>FAIL:</b> DESCRIPTION.en_us.html must have less than 1000 bytes.</summary>

* [com.google.fonts/check/description/max_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/max_length)

* 🔥 **FAIL** DESCRIPTION.en_us.html must have size smaller than 1000 bytes. [code: too-long]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)

* ⚠ **WARN** OS/2 VendorID value 'LIAM' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---

Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.

But value of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.

Another acceptable value is 2000. Since TT outlines are all integers (no
floats), then instances in a VF suffer rounding compromises, and therefore a
1000 UPM is to small because it forces too many such compromises.

Therefore 2000 is a good &#x27;new VF standard&#x27;, because 2000 is a simple 2x
conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what
10 units can do for 1000 UPM will know what 20 units does too.

Additionally, values above 2048 would result in filesize increases with not
much added benefit.


</pre>

* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.


</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: rupee	Contours detected: 1	Expected: 3
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: etilde	Contours detected: 2	Expected: 3
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: rupee	Contours detected: 1	Expected: 3
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: aogonek	Contours detected: 3	Expected: 2 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.


</pre>

* ⚠ **WARN** GDEF table is missing, but it is mandatory to declare it on fonts that provide ligature glyphs because the caret (text cursor) positioning for each ligature must be provided in this table. [code: GDEF-missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- R + R
	- T + T
	- r + r
	- t + t

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 2 | 1 | 7 | 28 | 7 | 116 | 0 |
| 1% | 1% | 4% | 17% | 4% | 72% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [Girassol_qa.zip](http://35.238.63.0/media/cc6e01de-b9b8-4f47-9c35-d1fdaa67db30/Girassol_qa.zip)

**Comment by m4rc1e** [comment]
LGTM thanks @yanone

**Pull request merged**
