### PR TITLE
Fix URLs for description files with associated upstream yaml files only

### PR DESCRIPTION
**Pull request by eliheuer**
Fixes issues from PR 6749: https://github.com/google/fonts/pull/6749

Specifically this comment here: https://github.com/google/fonts/pull/6749#issuecomment-1737670711

Only fonts with associated upstream.yaml files have been updated, all other fonts from PR #6749 will be updated separately

### CODE REVIEW

**Comment by eliheuer** [comment]
Here is a breakdown of what I found while looking at what fonts have upstream.yaml files, yes+target means it had a HTML target attribute, and the attribute was removed in my PR:
```
font                    has yaml
--------------------------------
ofl/adlamdisplay             yes
ofl/asapvfbeta               no
ofl/balsamiqsans             yes+target
ofl/bebasneue                no
ofl/besley                   yes
ofl/dongle                   yes
ofl/dosis                    yes
ofl/firacode                 no
ofl/geologica                yes
ofl/goldman                  no
ofl/gowundodum               yes
ofl/hahmlet                  yes
ofl/kaiseidecol              yes
ofl/kaiseiharunoumi          yes
ofl/kaiseiopti               yes
ofl/kaiseitokumin            yes
ofl/kumbhsans                yes+target
ofl/mochiypopone             yes
ofl/mochiypoppone            yes
ofl/mplus1                   yes
ofl/mplus1code               yes
ofl/mplus2                   yes
ofl/mpluscodelatin           yes
ofl/orbitron                 no
ofl/overpass                 yes
ofl/overpassmono             yes
ofl/padauk                   yes
ofl/palettemosaic            yes
ofl/paytoneone               yes
ofl/podkovavfbeta            no
ofl/redrose                  yes+target
ofl/rowdies                  no
ofl/shipporiantique          yes
ofl/shipporiantiqueb1        yes
ofl/shipporimincho           yes
ofl/shipporiminchob1         yes
ofl/varta                    no
ofl/xanhmono                 no
ofl/zenmarugothic            yes

```

**Comment by felipesanches** [comment]
It is not clear to me what's the problem with target attributes. Please see https://github.com/google/fonts/issues/3682#issuecomment-1737805306

There are hundreds of HTML files with the target attribute on the google/fonts repo, and I can see many of these anchors with `target="_blank"` are live on the families' About pages. So, if this will change, there should be a better explanation for why this is being done. And then the change should be made consistently on the entire collection, which will mean hundreds of HTML page updates. These target attributes are also present in the designers catalog `bio.html` files.

**Comment by RosaWagner** [comment]
@felipesanches I personally don't think that the target is such a problem, but we had a discussion last year that it was unnecessary because the website was already set up to open links in a new tab or because it can be a personal browser set up. So I see it as an aesthetic change and since we are doing right now here we may as well get that at the same time. But good to ask Rod why it was a blocker at that moment and not in other moments.

**Comment by RosaWagner** [comment]
@eliheuer you can make an issue listing all the families to keep track if it helps, eg https://github.com/google/fonts/issues/3103

**Review by RosaWagner — APPROVED** [review]

**Pull request merged**
