### PR TITLE
Noto Sans Armenian: Version 2.007 added

### PR DESCRIPTION
**Pull request by simoncozens**
cc96c0e: [gftools-packager] Noto Sans Armenian: Version 2.007 added

* Noto Sans Armenian Version 2.007 taken from the upstream repo https://github.com/notofonts/armenian.git at commit https://github.com/notofonts/armenian/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
There is a horizontal reflow on Sierra Safari 11

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by vv-monsalve** [comment]
In Mojave Safari 12.1 there is less reflow
Noto-Sans-Armenian-Mojave-Safari-12

It gets stronger on Catalina Safari 13.1 for the Medium weight (below image) , and stops on BigSur

(Tests done using BrwoserStack Live preview)
Noto-Sans-Armenian-Catalina-Safari-13

**Review by m4rc1e — COMMENTED** [review]
The reflow looks huge because the actual word which is overflowing is enormous. I'm ok for us to merge this. On the latest Safari and Chrome, it looks decent.

**Comment by vv-monsalve** [comment]
Merging this one here then.

**Comment by vv-monsalve** [comment]
@simoncozens Noto Sans Armenian is showing a tofu in Sandbox
Screen Shot 2022-09-01 at 8 45 22

**Comment by simoncozens** [comment]
This is the mijaket glyph (ONE DOT LEADER, U+2024). It is present in the font but probably not in the Armenian subset definition.

**Comment by vv-monsalve** [comment]
Subset fix googlefonts/glyphsets [#69](https://github.com/googlefonts/glyphsets/pull/69)

**Comment by vv-monsalve** [comment]
Looking good now in Sandbox

**Pull request merged**
