### PR TITLE
2017 Greek Glyph Sets

### PR DESCRIPTION
**Pull request by alexeiva**
The Greek Glyphs sets are now ready to be merged.
I have added .nam files 
cc @thlinard @irenevl

### CODE REVIEW

**Comment by graphicore** [comment]
I see a lot of unicodes with lower case hex codepoints, like:

```
+# GF Greek Coptic   
+# Generated by Alexei Vanyashin 10 Feb 2017   
+0x3e2  Ϣ COPTIC CAPITAL LETTER SHEI
+0x3e3  ϣ COPTIC SMALL LETTER SHEI
+0x3e4  Ϥ COPTIC CAPITAL LETTER FEI
```

The "Spec" [README.md](https://github.com/google/fonts/blob/master/tools/encodings/README.md) says:

> The subsetting requires that each line must start with 0x and then have 4 **uppercase** hex digits; what follows is an arbitrary description to the end of the line. Comments are lines starting with #.

The word **uppercase** is written in bold.

It would be cool to change this before the merge, or we must discuss the "spec".

**Comment by alexeiva** [comment]
Will update this. Thank you

**Comment by alexeiva** [comment]
@graphicore In fact some hex points are 5 digit, we should update this in the readme spec.

```
0x10140  𐅀 GREEK ACROPHONIC ATTIC ONE QUARTER
0x10141  𐅁 GREEK ACROPHONIC ATTIC ONE HALF
0x10142  𐅂 GREEK ACROPHONIC ATTIC ONE DRACHMA
0x03D8  Ϙ GREEK LETTER ARCHAIC KOPPA
0x03D9  ϙ GREEK SMALL LETTER ARCHAIC KOPPA

```

**Comment by graphicore** [comment]
Thanks a lot for this hint! I was wondering already but I had no example for this (I think). I'll change this and all the code that assumes 4 digits.

**Comment by alexeiva** [comment]
lowercase 2-3 digit hex values came from the `namelist.py` script... 

```
python namelist.py /Users/alexeiva/Desktop/newFont-Regular.ttf > ~/Desktop/GreekPro-test.nam
/Library/Python/2.7/site-packages/fontTools/__init__.py:11: RuntimeWarning: versioneer: no suitable tags
  __import__('warnings').warn("versioneer: %s" % v['error'], RuntimeWarning)
```

Test font for creating nam files included 53 Latin + 82 Greek Pro glyphs

Generated .nam file had 715 glyphs => 271 unique glyphs + duplicates

Test font
[newFont-Regular.ttf.zip](https://github.com/google/fonts/files/767242/newFont-Regular.ttf.zip)

Generated nam file, unique glyphs only
[GreekPro-test-unique.nam.zip](https://github.com/google/fonts/files/767244/GreekPro-test-unique.nam.zip)

**Comment by graphicore** [comment]
Allright, in my PR #642 

> lowercase 2-3 digit hex values came from the namelist.py script...

fixed in cffa3fc

> @graphicore In fact some hex points are 5 digit, we should update this in the readme spec.

fixed in bb19451

> I'll change this and all the code that assumes 4 digits.

fixed in 52d851d (hope that's "all")

**Comment by graphicore** [comment]
Here's the output of the fixed `namelist.py` https://gist.github.com/graphicore/d06816558bc21172ff40cc4a465842ca

**Comment by davelab6** [comment]
Great work guys! Please assign to me when ready to merge

**Comment by alexeiva** [comment]
interesting, the syntax issues is fixed, but still Latin A is duplicated 5 times. 
namelist.py doesn't provide preview characters, so I use spreadsheets to create proper nam files anyway. 

For other Greek glyph ranges it worked just fine, with identical number of glyphs in the ttf and nam files. 

If you include a single glyph in the TTF, say Latin A, it will spit out its whole parent Latin Core set..

**Comment by alexeiva** [comment]
Moving our discussion from https://github.com/alexeiva/play/issues/3

> I think it doesn't, small caps feature creates variants, it's a soft conversion, it doesn't interfere with the Unicode value of the glyph. The unicode value is preserved and when the user switches off the feature, the glyph will go back to what it was. SBL is like that, Adobe's fonts etc

@irenevl I was thinking about a similar solution as the capital eszett workaround: https://glyphsapp.com/tutorials/localize-your-font-german-capital-sharp-s

cc @thlinard

**Comment by thlinard** [comment]
I thought of ezsett, but the problem is a little different (with sigma.sc, the glyph exists anyway). So I checked some fonts, if they have (or not) sigmafinal.sc (or uni03C2.sc, u03C2.sc, uni03C2.smcp, &c.)

SBL Greek: without sigmafinal.sc
Brill: with sigmafinal.sc
Fira Sans v4.2: with sigmafinal.sc

Adobe Arno Pro v1.011: with sigmafinal.sc
Adobe Garamond Premier Pro v1.014: with sigmafinal.sc
Adobe Hypatia Sans Pro v1.008: with sigmafinal.sc
Adobe Text v1.015: with sigmafinal.sc

Georgia v5.58: without sigmafinal.sc
Calibri v6.18: without sigmafinal.sc
Times New Roman v6.96: without sigmafinal.sc

Not every type engine seems to have the same requirements…

**Comment by alexeiva** [comment]
I have examined the implementation in SBL Greek as a webfont on Impallari's Font Testing Page:

Lowercase
screen shot 2017-02-11 at 8 10 04 pm

Small Caps
screen shot 2017-02-11 at 8 09 54 pm

Faux Small Caps
screen shot 2017-02-11 at 8 11 03 pm

Opentype features need to be written explicitly. Glyphs has no automation for this. 

```
sub sigma by Sigma.small;
sub uni03C2 by Sigma.small;
```

where `uni03C3=sigmaginal`

**Comment by graphicore** [comment]
> interesting, the syntax issues is fixed, but still Latin A is duplicated 5 times.

I can fix this.

> namelist.py doesn't provide preview characters, so I use spreadsheets to create proper nam files anyway.

I can fix this, too :-) By " preview characters" you mean

```
0x0046 F LATIN CAPITAL LETTER F
```

instead of

```
0x0046 LATIN CAPITAL LETTER F
```

right?

**Comment by alexeiva** [comment]
exactly

**Comment by graphicore** [comment]
I just pushed an updated namelist.py. Sample output: https://gist.github.com/graphicore/d06816558bc21172ff40cc4a465842ca

**Comment by alexeiva** [comment]
looks much better! But I think the accented Latin is stray here. It wasn't present in the TTF?
Would like to test this further to make proper .nam files for our existing Latin and Cyrillic sets. 

```
0x00C0 À LATIN CAPITAL LETTER A WITH GRAVE
0x00C1 Á LATIN CAPITAL LETTER A WITH ACUTE
0x00C2 Â LATIN CAPITAL LETTER A WITH CIRCUMFLEX
```

**Comment by alexeiva** [comment]
@davelab6 this is ready to merge now

**Comment by davelab6** [comment]
Thank you boss

**Comment by graphicore** [comment]
> looks much better! But I think the accented Latin is stray here. It wasn't present in the TTF?

Ok, I can look into this. Maybe the fonttools CMAP is used slightly wrong.

**Comment by graphicore** [comment]
@alexeiva  I just pushed the next iteration of `namelist.py`.

3cf4880f `[tools] only use uniode cmaps and sort by charcode.`

Your remark above is fixed AND it's sorted.

It is the best version ever. It's huge! Believe me!

---

```
0x0041 A LATIN CAPITAL LETTER A
0x0042 B LATIN CAPITAL LETTER B
0x0043 C LATIN CAPITAL LETTER C
0x0044 D LATIN CAPITAL LETTER D
0x0045 E LATIN CAPITAL LETTER E
0x0046 F LATIN CAPITAL LETTER F
0x0047 G LATIN CAPITAL LETTER G
0x0048 H LATIN CAPITAL LETTER H
0x0049 I LATIN CAPITAL LETTER I
0x004A J LATIN CAPITAL LETTER J
0x004B K LATIN CAPITAL LETTER K
0x004C L LATIN CAPITAL LETTER L
0x004D M LATIN CAPITAL LETTER M
0x004E N LATIN CAPITAL LETTER N
0x004F O LATIN CAPITAL LETTER O
0x0050 P LATIN CAPITAL LETTER P
0x0051 Q LATIN CAPITAL LETTER Q
0x0052 R LATIN CAPITAL LETTER R
0x0053 S LATIN CAPITAL LETTER S
0x0054 T LATIN CAPITAL LETTER T
0x0055 U LATIN CAPITAL LETTER U
0x0056 V LATIN CAPITAL LETTER V
0x0057 W LATIN CAPITAL LETTER W
0x0058 X LATIN CAPITAL LETTER X
0x0059 Y LATIN CAPITAL LETTER Y
0x005A Z LATIN CAPITAL LETTER Z
0x0061 a LATIN SMALL LETTER A
0x0062 b LATIN SMALL LETTER B
0x0063 c LATIN SMALL LETTER C
0x0064 d LATIN SMALL LETTER D
0x0065 e LATIN SMALL LETTER E
0x0066 f LATIN SMALL LETTER F
0x0067 g LATIN SMALL LETTER G
0x0068 h LATIN SMALL LETTER H
0x0069 i LATIN SMALL LETTER I
0x006A j LATIN SMALL LETTER J
0x006B k LATIN SMALL LETTER K
0x006C l LATIN SMALL LETTER L
0x006D m LATIN SMALL LETTER M
0x006E n LATIN SMALL LETTER N
0x006F o LATIN SMALL LETTER O
0x0070 p LATIN SMALL LETTER P
0x0071 q LATIN SMALL LETTER Q
0x0072 r LATIN SMALL LETTER R
0x0073 s LATIN SMALL LETTER S
0x0074 t LATIN SMALL LETTER T
0x0075 u LATIN SMALL LETTER U
0x0076 v LATIN SMALL LETTER V
0x0077 w LATIN SMALL LETTER W
0x0078 x LATIN SMALL LETTER X
0x0079 y LATIN SMALL LETTER Y
0x007A z LATIN SMALL LETTER Z
0x02D9 ˙ DOT ABOVE
0x0305 ̅ COMBINING OVERLINE
0x0323 ̣ COMBINING DOT BELOW
0x0359 ͙ COMBINING ASTERISK BELOW
0x035C ͜ COMBINING DOUBLE BREVE BELOW
0x03DA Ϛ GREEK LETTER STIGMA
0x03DB ϛ GREEK SMALL LETTER STIGMA
0x03DC Ϝ GREEK LETTER DIGAMMA
0x03DD ϝ GREEK SMALL LETTER DIGAMMA
0x03DE Ϟ GREEK LETTER KOPPA
0x03DF ϟ GREEK SMALL LETTER KOPPA
0x03E0 Ϡ GREEK LETTER SAMPI
0x03E1 ϡ GREEK SMALL LETTER SAMPI
0x2016 ‖ DOUBLE VERTICAL LINE
0x203B ※ REFERENCE MARK
0x203F ‿ UNDERTIE
0x2042 ⁂ ASTERISM
0x2056 ⁖ THREE DOT PUNCTUATION
0x2058 ⁘ FOUR DOT PUNCTUATION
0x2059 ⁙ FIVE DOT PUNCTUATION
0x205A ⁚ TWO DOT PUNCTUATION
0x205B ⁛ FOUR DOT MARK
0x205C ⁜ DOTTED CROSS
0x205D ⁝ TRICOLON
0x205E ⁞ VERTICAL FOUR DOTS
0x207A ⁺ SUPERSCRIPT PLUS SIGN
0x207B ⁻ SUPERSCRIPT MINUS
0x207C ⁼ SUPERSCRIPT EQUALS SIGN
0x208A ₊ SUBSCRIPT PLUS SIGN
0x208B ₋ SUBSCRIPT MINUS
0x208C ₌ SUBSCRIPT EQUALS SIGN
0x2135 ℵ ALEF SYMBOL
0x2136 ℶ BET SYMBOL
0x2297 ⊗ CIRCLED TIMES
0x22EE ⋮ VERTICAL ELLIPSIS
0x23D1 ⏑ METRICAL BREVE
0x23D2 ⏒ METRICAL LONG OVER SHORT
0x23D3 ⏓ METRICAL SHORT OVER LONG
0x23D4 ⏔ METRICAL LONG OVER TWO SHORTS
0x23D5 ⏕ METRICAL TWO SHORTS OVER LONG
0x23D6 ⏖ METRICAL TWO SHORTS JOINED
0x23D7 ⏗ METRICAL TRISEME
0x23D8 ⏘ METRICAL TETRASEME
0x23D9 ⏙ METRICAL PENTASEME
0x2AFD ⫽ DOUBLE SOLIDUS OPERATOR
0x2E00 ⸀ RIGHT ANGLE SUBSTITUTION MARKER
0x2E01 ⸁ RIGHT ANGLE DOTTED SUBSTITUTION MARKER
0x2E02 ⸂ LEFT SUBSTITUTION BRACKET
0x2E03 ⸃ RIGHT SUBSTITUTION BRACKET
0x2E04 ⸄ LEFT DOTTED SUBSTITUTION BRACKET
0x2E05 ⸅ RIGHT DOTTED SUBSTITUTION BRACKET
0x2E06 ⸆ RAISED INTERPOLATION MARKER
0x2E07 ⸇ RAISED DOTTED INTERPOLATION MARKER
0x2E08 ⸈ DOTTED TRANSPOSITION MARKER
0x2E09 ⸉ LEFT TRANSPOSITION BRACKET
0x2E0A ⸊ RIGHT TRANSPOSITION BRACKET
0x2E0B ⸋ RAISED SQUARE
0x2E0C ⸌ LEFT RAISED OMISSION BRACKET
0x2E0D ⸍ RIGHT RAISED OMISSION BRACKET
0x2E0E ⸎ EDITORIAL CORONIS
0x2E0F ⸏ PARAGRAPHOS
0x2E10 ⸐ FORKED PARAGRAPHOS
0x2E11 ⸑ REVERSED FORKED PARAGRAPHOS
0x2E12 ⸒ HYPODIASTOLE
0x2E13 ⸓ DOTTED OBELOS
0x2E14 ⸔ DOWNWARDS ANCORA
0x2E15 ⸕ UPWARDS ANCORA
0x2E16 ⸖ DOTTED RIGHT-POINTING ANGLE
0x2E17 ⸗ DOUBLE OBLIQUE HYPHEN
0x3008 〈 LEFT ANGLE BRACKET
0x3009 〉 RIGHT ANGLE BRACKET
0x300A 《 LEFT DOUBLE ANGLE BRACKET
0x300B 》 RIGHT DOUBLE ANGLE BRACKET
0x300C 「 LEFT CORNER BRACKET
0x300D 」 RIGHT CORNER BRACKET
0x301A 〚 LEFT WHITE SQUARE BRACKET
0x301B 〛 RIGHT WHITE SQUARE BRACKET
0x1D459 𝑙 MATHEMATICAL ITALIC SMALL L
0x1D510 𝔐 MATHEMATICAL FRAKTUR CAPITAL M
0x1D513 𝔓 MATHEMATICAL FRAKTUR CAPITAL P
0x1D516 𝔖 MATHEMATICAL FRAKTUR CAPITAL S
0x1D52D 𝔭 MATHEMATICAL FRAKTUR SMALL P
```

**Comment by alexeiva** [comment]
@graphicore just tested your update. Das ist wunderbar!

**Comment by davelab6** [comment]
Thank you!

**Comment by thlinard** [comment]
Thank you Dave!

**Pull request merged**
