### PR TITLE
abel: four was overkerned to period and comma

### LINKED ISSUE #1984: Abel: The digit "4" goes outside it's boundaries when after a dot (".") on Linux/Android
This happens in both Chrome and Firefox and has been the same for the past years (tried reporting an issue on Google Fonts a year or two ago without any response).

This is what it looks like (other digits for comparison):
Screenshot from 2019-05-15 11-33-33

Here you can see that it looks like the 4 is in violation, or maybe the dot isn't working properly (I have selected only the 4):
Screenshot from 2019-05-15 11-37-19

Worth noting is that this does not happen when other characters are in front of the 4, only with the dot.

### PR DESCRIPTION
**Pull request by laerm0**
Fixes #1984 

Period and comma were overkerned to a four following. Changed `.4` and `,4` from -397 to -107.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Before making a fix, please check if the family has an [upstream repo,](https://docs.google.com/spreadsheets/d/1ampzD9veEdrwUMkOAJkMNkftqtv1jEygiPR0wZ6eNl8/edit?userstoinvite=post%40yanone.de&ts=5dbc3d4e&actionButton=1#gid=0)

I don't mind hotfixes if there isn't an upstream. Abel's upstream is https://github.com/m4rc1e/Abel

**Comment by laerm0** [comment]
Aha, yes, sorry. Been a while since I went on a binge of clearing out little issues. I'll hit up the upstream.

**Comment by davelab6** [comment]
@m4rc1e since the last update to Abel was a hotfix (https://github.com/google/fonts/pull/741) that apparently didn't address this issue, or introduced it, back in 2017, I feel like a hotfix is appropriate for this one. 

@rosawagner please check this for regressions and then I'd like to merge and push

**Comment by RosaWagner** [comment]
No visual regression, although FB shows few fails.

## Fontbakery report

Fontbakery version: 0.7.27

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Do we have the latest version of FontBakery installed?</summary>

* [com.google.fonts/check/fontbakery_version](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/fontbakery_version)

* 🔥 **FAIL** Unable to detect what's the latest version of FontBakery available. Maybe we're offline? Please check Internet access and try again.

</details>
<br>
</details>
<details>
<summary><b>[9] Abel-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check `Google Fonts Latin Core` glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
<pre>--- Rationale ---

Google Fonts expects that fonts in its collection support at least the minimal
set of characters defined in the `GF-latin-core` glyph-set.


</pre>

* 🔥 **FAIL** Missing required codepoints: 0x00AD (SOFT HYPHEN), 0x2074 (SUPERSCRIPT FOUR) and 0x2215 (DIVISION SLASH) [code: missing-codepoints]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)

* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2011, Matthew Desmond (http://www.madtype.com | mattdesmond@gmail.com), with Reserved Font Name Abel." [code: bad-notice-format]
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2011, Matthew Desmond (http://www.madtype.com | mattdesmond@gmail.com), with Reserved Font Name Abel." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Name table strings must not contain the string 'Reserved Font Name'.</summary>

* [com.google.fonts/check/name/rfn](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn)
<pre>--- Rationale ---

Some designers adopt the &quot;Reserved Font Name&quot; clause of the OFL license. This
means that the original author reserves the rights to the family name and other
people can only distribute modified versions using a different family name.

Google Fonts published updates to the fonts in the collection in order to fix
issues and/or implement further improvements to the fonts. It is important to
keep the family name so that users of the webfonts can benefit from the
updates. Since it would forbid such usage scenario, all families in the GFonts
collection are required to not adopt the RFN clause.

This check ensures &quot;Reserved Font Name&quot; is not mentioned in the name table.


</pre>

* 🔥 **FAIL** Name table entry ("Copyright (c) 2011, Matthew Desmond (http://www.madtype.com | mattdesmond@gmail.com), with Reserved Font Name Abel.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]
* 🔥 **FAIL** Name table entry ("Copyright (c) 2011, Matthew Desmond (http://www.madtype.com | mattdesmond@gmail.com), with Reserved Font Name Abel.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>🔥 <b>FAIL:</b> A font repository should not include ZIP files</summary>

* [com.google.fonts/check/repo/zip_files](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/zip_files)
<pre>--- Rationale ---

Sometimes people check in ZIPs into their font project repositories. While we
accept the practice of checking in binaries, we believe that a ZIP is a step
too far ;)

Note: a source purist position is that only source files and build scripts
should be checked in. 


</pre>

* 🔥 **FAIL** Please do not host ZIP files on the project repository. These files were detected:
	* ./mavenproFont-master.zip
	* ./FontTableViewer1.0.3-13.zip
	* ./Montserrat-master.zip
	* ./Fraunces-master.zip
	* ./2020-04-20_TB-Dedale_Beta.zip
	* ./Inconsolata-master.zip
	* ./Epilogue-master.zip
	* ./recursive-master.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_JG7KD.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_2JYLY.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_QRVWD.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_K5DBS.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_G6ONU.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_D4W59.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_0RIRQ.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_K5DBS.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_0RIRQ.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_G6ONU.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_D4W59.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_QRVWD.zip
	* ./$RECYCLE.BIN/.prl_rec/$I_2JYLY.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_JG7KD.zip
	* ./fonts-master.zip
	* ./Space_Mono.zip
	* ./CritParty.glyphsPlugin-beta.zip
	* ./Eskorte_manuals.zip
	* ./TextPreview1.0-8.zip
	* ./Open_Sans_Condensed.zip
	* ./glyphs-export-master.zip
	* ./opensans-master.zip
	* ./literata-master.zip
	* ./$RECYCLE.BIN/.prl_rec/$R_HDUZ6.rar and ./$RECYCLE.BIN/.prl_rec/$I_HDUZ6.rar [code: zip-files]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there unwanted tables?</summary>

* [com.google.fonts/check/unwanted_tables](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unwanted_tables)
<pre>--- Rationale ---

Some font editors store source data in their own SFNT tables, and these can
sometimes sneak into final release files, which should only have OpenType spec
tables.


</pre>

* 🔥 **FAIL** The following unwanted font tables were found:
Table: FFTM
Reason: Table contains redundant FontForge timestamp info

They can be removed with the gftools fix-unwanted-tables script.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/dsig](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/dsig.html#com.google.fonts/check/dsig)
<pre>--- Rationale ---

Microsoft Office 2013 and below products expect fonts to have a digital
signature declared in a DSIG table in order to implement OpenType features. The
EOL date for Microsoft Office 2013 products is 4/11/2023. This issue does not
impact Microsoft Office 2016 and above products. 

This checks verifies that this signature is available in the font.

A fake signature is enough to address this issue. If needed, a dummy table can
be added to the font with the `gftools fix-dsig` script available at
https://github.com/googlefonts/gftools

Reference: https://github.com/googlefonts/fontbakery/issues/1845


</pre>

* 🔥 **FAIL** This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly. You can add a DSIG table by running the `gftools fix-dsig` script. [code: lacks-signature]

</details>
<details>
<summary>⚠ <b>WARN:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
<pre>--- Rationale ---

A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry
of the name table.

The source of truth for this check is the licensing text found on the NameID 13
entry (LICENSE DESCRIPTION).

The string snippets used for detecting licensing terms are:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;


Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.

When in doubt, please choose OFL for new font projects.


</pre>

* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=1, enc=0, name=14] [code: http-in-license-info]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=14] [code: http-in-license-info]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font contains .notdef as first glyph?</summary>

* [com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs)
<pre>--- Rationale ---

The OpenType specification v1.8.2 recommends that the first glyph is the
.notdef glyph without a codepoint assigned and with a drawing.

https://docs.microsoft.com/en-us/typography/opentype/spec
/recom#glyph-0-the-notdef-glyph

Pre-v1.8, it was recommended that a font should also contain a .null, CR and
space glyph. This might have been relevant for applications on MacOS 9.


</pre>

* ⚠ **WARN** Font should contain the .notdef glyph as the first glyph, it should not have a Unicode value assigned and should contain a drawing.

</details>
<details>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)

* ⚠ **WARN** GPOS table lacks kerning information. [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 7 | 3 | 83 | 10 | 72 | 0 |
| 0% | 4% | 2% | 47% | 6% | 41% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**
[abel-report.zip](https://github.com/google/fonts/files/4788266/abel-report.zip)

**Comment by m4rc1e** [comment]
@RosaWagner The FB report isn't too useful for this fix. Showing the results of diffenator would be better.

kerns_modified


Can confirm the fix has been implemented and no regressions have been introduced.

Thanks for checking.

**Comment by RosaWagner** [comment]
Noted thks

**Pull request merged**
