### PR TITLE
viaodalibre: v1.000 added

### PR DESCRIPTION
**Pull request by bettergui**
Taken from the upstream repo https://github.com/bettergui/ViaodaLibre at commit https://github.com/bettergui/ViaodaLibre/commit/b01d5587f0be6bfce907b4fc02710c5ddd5a471b

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.14

<details>
<summary><b>[6] ViaodaLibre-Regular.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: quotedblbase	Contours detected: 1	Expected: 2
Glyph name: ellipsis	Contours detected: 1	Expected: 3
Glyph name: D	Contours detected: 3	Expected: 2
Glyph name: H	Contours detected: 2	Expected: 1
Glyph name: O	Contours detected: 3	Expected: 2
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: b	Contours detected: 3	Expected: 2
Glyph name: d	Contours detected: 3	Expected: 2
Glyph name: p	Contours detected: 3	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: Ograve	Contours detected: 4	Expected: 3
Glyph name: Oacute	Contours detected: 4	Expected: 3
Glyph name: Ocircumflex	Contours detected: 4	Expected: 3
Glyph name: Otilde	Contours detected: 4	Expected: 3
Glyph name: Odieresis	Contours detected: 5	Expected: 4
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: Dcaron	Contours detected: 4	Expected: 3
Glyph name: dcaron	Contours detected: 4	Expected: 3
Glyph name: dcroat	Contours detected: 3	Expected: 2
Glyph name: Omacron	Contours detected: 4	Expected: 3
Glyph name: Ohungarumlaut	Contours detected: 5	Expected: 4
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: uni0156	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: Wcircumflex	Contours detected: 3	Expected: 2
Glyph name: uni01D1	Contours detected: 4	Expected: 3
Glyph name: uni0243	Contours detected: 2	Expected: 3
Glyph name: Etatonos	Contours detected: 3	Expected: 2
Glyph name: Omicrontonos	Contours detected: 4	Expected: 3
Glyph name: Beta	Contours detected: 2	Expected: 3
Glyph name: Eta	Contours detected: 2	Expected: 1
Glyph name: Omicron	Contours detected: 3	Expected: 2
Glyph name: beta	Contours detected: 1	Expected: 2
Glyph name: uni0409	Contours detected: 1	Expected: 2
Glyph name: uni0412	Contours detected: 2	Expected: 3
Glyph name: uni041D	Contours detected: 2	Expected: 1
Glyph name: uni041E	Contours detected: 3	Expected: 2
Glyph name: uni042A	Contours detected: 1	Expected: 2
Glyph name: uni042B	Contours detected: 2	Expected: 3
Glyph name: uni042C	Contours detected: 1	Expected: 2
Glyph name: uni042E	Contours detected: 3	Expected: 2
Glyph name: uni042F	Contours detected: 1	Expected: 2
Glyph name: uni0440	Contours detected: 3	Expected: 2
Glyph name: uni0462	Contours detected: 1	Expected: 2
Glyph name: uni04E6	Contours detected: 5	Expected: 4
Glyph name: uni04F8	Contours detected: 4	Expected: 5
Glyph name: uni1E0C	Contours detected: 4	Expected: 3
Glyph name: uni1E0D	Contours detected: 4	Expected: 3
Glyph name: uni1E24	Contours detected: 3	Expected: 2
Glyph name: Wgrave	Contours detected: 3	Expected: 2
Glyph name: Wacute	Contours detected: 3	Expected: 2
Glyph name: Wdieresis	Contours detected: 4	Expected: 3
Glyph name: uni1ECC	Contours detected: 4	Expected: 3
Glyph name: uni1ECE	Contours detected: 4	Expected: 3
Glyph name: uni1ED0	Contours detected: 5	Expected: 4
Glyph name: uni1ED2	Contours detected: 5	Expected: 4
Glyph name: uni1ED4	Contours detected: 5	Expected: 4
Glyph name: uni1ED6	Contours detected: 5	Expected: 4
Glyph name: uni1ED8	Contours detected: 5	Expected: 4
Glyph name: uni042E	Contours detected: 3	Expected: 2
Glyph name: Eta	Contours detected: 2	Expected: 1
Glyph name: Wacute	Contours detected: 3	Expected: 2
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: Etatonos	Contours detected: 3	Expected: 2
Glyph name: uni1ED6	Contours detected: 5	Expected: 4
Glyph name: dcroat	Contours detected: 3	Expected: 2
Glyph name: uni04F8	Contours detected: 4	Expected: 5
Glyph name: uni041E	Contours detected: 3	Expected: 2
Glyph name: uni1E24	Contours detected: 3	Expected: 2
Glyph name: p	Contours detected: 3	Expected: 2
Glyph name: H	Contours detected: 2	Expected: 1
Glyph name: ellipsis	Contours detected: 1	Expected: 3
Glyph name: uni042A	Contours detected: 1	Expected: 2
Glyph name: uni0409	Contours detected: 1	Expected: 2
Glyph name: uni042F	Contours detected: 1	Expected: 2
Glyph name: uni1ED0	Contours detected: 5	Expected: 4
Glyph name: Ohungarumlaut	Contours detected: 5	Expected: 4
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: O	Contours detected: 3	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: uni0412	Contours detected: 2	Expected: 3
Glyph name: uni0156	Contours detected: 2	Expected: 3
Glyph name: Odieresis	Contours detected: 5	Expected: 4
Glyph name: Oacute	Contours detected: 4	Expected: 3
Glyph name: uni1ED8	Contours detected: 5	Expected: 4
Glyph name: Beta	Contours detected: 2	Expected: 3
Glyph name: uni042C	Contours detected: 1	Expected: 2
Glyph name: Omicron	Contours detected: 3	Expected: 2
Glyph name: Dcaron	Contours detected: 4	Expected: 3
Glyph name: uni042B	Contours detected: 2	Expected: 3
Glyph name: dcaron	Contours detected: 4	Expected: 3
Glyph name: beta	Contours detected: 1	Expected: 2
Glyph name: Omicrontonos	Contours detected: 4	Expected: 3
Glyph name: uni0440	Contours detected: 3	Expected: 2
Glyph name: uni0243	Contours detected: 2	Expected: 3
Glyph name: Otilde	Contours detected: 4	Expected: 3
Glyph name: D	Contours detected: 3	Expected: 2
Glyph name: d	Contours detected: 3	Expected: 2
Glyph name: uni1ECE	Contours detected: 4	Expected: 3
Glyph name: uni1ED2	Contours detected: 5	Expected: 4
Glyph name: Wdieresis	Contours detected: 4	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: uni1ED4	Contours detected: 5	Expected: 4
Glyph name: Wgrave	Contours detected: 3	Expected: 2
Glyph name: b	Contours detected: 3	Expected: 2
Glyph name: Omacron	Contours detected: 4	Expected: 3
Glyph name: uni01D1	Contours detected: 4	Expected: 3
Glyph name: quotedblbase	Contours detected: 1	Expected: 2
Glyph name: Ocircumflex	Contours detected: 4	Expected: 3
Glyph name: uni041D	Contours detected: 2	Expected: 1
Glyph name: Ograve	Contours detected: 4	Expected: 3
Glyph name: uni0462	Contours detected: 1	Expected: 2
Glyph name: uni1ECC	Contours detected: 4	Expected: 3
Glyph name: uni1E0C	Contours detected: 4	Expected: 3
Glyph name: Wcircumflex	Contours detected: 3	Expected: 2
Glyph name: uni04E6	Contours detected: 5	Expected: 4
Glyph name: uni1E0D	Contours detected: 4	Expected: 3 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- T + h
	- c + t
	- f + f
	- f + b
	- b + f
	- f + h
	- h + f
	- f + i
	- i + f
	- f + j
	- j + f
	- f + k
	- k + f
	- f + l
	- l + b
	- b + h
	- h + i
	- i + j
	- j + k
	- k + l
	- l + t
	- s + t
	- t + t

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 6 | 26 | 8 | 121 | 0 |
| 0% | 0% | 4% | 16% | 5% | 75% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [viaodalibre.zip](http://35.188.158.120/media/45587ed7-0c82-42ea-adb0-ab2003e857d8/viaodalibre.zip)

**Comment by m4rc1e** [comment]
Thanks for your submission. Technically, it's super clean so thank you!

ViaodaLibre-Regular

Desktop_OS_X_High_Sierra_safari_11 1_

Personally, I'm questioning some of the design choices. I don't really like the elements within the counters and some of the details feel bolted on, such as the ornament on the unjoined "P". It appears like a serif typeface was designed first and then elements have been added to give it flair.

I apologise if this sounds harsh. I understand a great deal of work has gone into this and I really respect that. I just feel it could do with another round of revision and possibly a decent critique from another designer. 

It's not just up to me. @davelab6 your thoughts?

**Comment by bettergui** [comment]
Dear Marc,
I can see your point about how it appeared like we added the ornaments to the serif typeface. The type does look busy in small font size:
Screen Shot 2019-11-20 at 9 34 58 PM

Thank you for giving us a chance to explain. There is a system behind all the details, would you mind watching our concept video?
https://www.facebook.com/Gydient/videos/210938389822502/?v=210938389822502

Screen Shot 2019-11-20 at 9 33 38 PM
_An example of how the crossbars were formed using local culture._


We have actually gone through multiple iterations with Giang’s type professor and other designers. They did give us feedback about how this type should mostly be used for display size, particularly scale at least from 36pt and wide tracking from 25-50pt. We understand the risk of a junior designer misusing this. Nevertheless, we still want to take the risk for the following reason:

Vietnamese design landscape has long been dominated by safe but uninspiring OS types from Microsoft such as Arial and Times New Roman. We want to challenge Vietnamese designers to use a unique type like this with the goal to change the country's attention to type design.

Your thoughts? Should we revise our description?

**Comment by bettergui** [comment]
Hi Marc, have you had a chance to take another look?

**Comment by bettergui** [comment]
Is there any update on this?

**Comment by m4rc1e** [comment]
I've just raised it again with the team. I'll try and get you an answer soon.

**Comment by davelab6** [comment]
I don't have any strong concerns about the design. Let's push it and see how it evolves :)

**Comment by m4rc1e** [comment]
Great. I'm happy we well.

**Comment by bettergui** [comment]
Thank you all for your time and support. After this is launched, I will work closely with users to get feedback and evolve it.

**Pull request merged**
