### PR TITLE
Update METADATA.pb

### PR DESCRIPTION
**Pull request by marekjez86**
Adding all of the languages that notosanshk can handle

### CODE REVIEW

**Comment by simoncozens** [comment]
I think the reason these languages aren't in the METADATA.pb (and weren't generated by add-font) is because we don't have textproto records for them in our languages database.

I'm not familiar enough with the textproto files to know what this means and how these language records are used; things may be different between Noto and GF, for example. I don't know. But it feels to me that there probably isn't any point adding `cjy_Hant` to the languages when we don't have a `cjy_Hant.textproto`.

**Comment by marekjez86** [comment]
I didn't realize it was generated
where is cjy_Hant.textprot kept?

**Comment by simoncozens** [comment]
> where is cjy_Hant.textprot kept?

We don't have one; that's why I don't understand if there is a need to  add this language. If it did exist it would be [here](https://github.com/google/fonts/tree/main/lang/Lib/gflanguages/data/languages).

**Comment by marekjez86** [comment]
Created https://github.com/google/fonts/pull/4627 to cover the missing languages for Traditional. Note that we have yue_Hans.textproto and yue_Hant.textproto .... I would expect these to be part of the Noto * HK metadata, but it weren't ? @simoncozens : why would it be missing from notosanshk  METADATA.pb ?

**Comment by RosaWagner** [comment]
Closing this PR since Simon is working on the same thing in a separate one

**Comment by simoncozens** [comment]
-> #4650.

**Pull request closed without merging**
