### PR TITLE
Update tiny5/METADATA.pb

### PR DESCRIPTION
**Pull request by davelab6**
Per auto closed PR #7816 this should match upstream

### CODE REVIEW

**Review by emmamarichal — APPROVED** [review]

**Comment by emmamarichal** [comment]
@m4rc1e I see "manifest" in these errors:
💥 ERROR Check if the vertical metrics of a CJK family are similar to the same family hosted on Google Fonts.
💥 ERROR Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts.

I saw the manifest error last week with the traffic jam tool, but I'll not merge that PR without confirmation. What would be the best move here?

**Comment by vv-monsalve** [comment]
> I saw the manifest error last week with the traffic jam tool

What do you mean by "manifest" error?

**Comment by emmamarichal** [comment]
@vv-monsalve Inside the check: 

```
💥 ERROR
'manifest'


[code: error]
```


I don't know what "manifest" means, but I had it also with the traffic jam tool

**Comment by m4rc1e** [comment]
Just fixed fontbakery https://github.com/fonttools/fontbakery/pull/4810. "manifest" appears when we're not able to download the family from a server. This should only happen if the family hasn't been pushed to the server yet, once the fb pr has been merged. I'll make a fix in manage traffic jam as well.

**Comment by vv-monsalve** [comment]
This pull request was included in the 'to_sandbox' list and technically incorporated into the latest push. However, at present, it is not feasible to track this change through the servers, not even manually. Therefore, I am adding it to the "Blocked" list to prevent it from being added to the lists until we find a way to track these changes.

**Comment by m4rc1e** [comment]
The download zip's OFL file has been changed so we can track it. 

Screenshot 2024-11-28 at 21 08 59

**Pull request merged**
