### PR TITLE
Afacad Flux: Version 1.100 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/Dicotype/Afacad at commit https://github.com/Dicotype/Afacad/commit/a3d77cea32b6f29801c5c1771fbad276d817c97a.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [x] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [x] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [x] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
Updated

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@emmamarichal the `wght` interpolation is running odly in de-server. Looks like something related to the spacing


https://github.com/google/fonts/assets/48698976/cf289bf3-c4cd-43fb-8c07-f89289d08430

**Comment by emmamarichal** [comment]
@vv-monsalve Yes definitely the spacing. Let me check with the designer! :)

**Comment by vv-monsalve** [comment]
@emmamarichal Friendly ping about this project. It's still blocked in the dev server due to the spacing issue :)

**Comment by emmamarichal** [comment]
@ktkm I'm still on holidays, I quickly copy/answer your email here:

> I hope you’re well! I missed your message earlier, sorry! 
> If you mean that the spacing becomes tighter in the heavier weights, then yes, it is intentional. The idea for Afacad is to match the spacing with counter-letter shapes. I hope it helps.
> 
> What is the next step?

@vv-monsalve: it's intentional, if you're ok with that, we can unblock it!

**Comment by ktkm** [comment]
@emmamarichal Thank you, Emma, for taking the time and reminding me about this thread.
@vv-monsalve The same non-linear spacing rule applies to the initial version of Afacad and Afacad Flux.

**Comment by vv-monsalve** [comment]
> @vv-monsalve The same non-linear spacing rule applies to the initial version of Afacad and Afacad Flux.

I can confirm now this is also present in the original font. 
@m4rc1e LGTM

**Pull request merged**
