### PR TITLE
Noto Sans Imperial Aramaic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/imperial-aramaic at commit https://github.com/notofonts/imperial-aramaic/commit/f32017cb2dba233b0a09565037af84f12016b0c8.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
This very minor update adds a default languagesystem.

**Comment by vv-monsalve** [comment]
@simoncozens there is a tofu in Latin
noto-imperialaramaic-ba

**Comment by simoncozens** [comment]
The Latin tofu is fine; LATIN SMALL LETTER ENG is no longer part of the GF Latin Core. (Maybe our test text should be updated.)

**Comment by vv-monsalve** [comment]
> (Maybe our test text should be updated.)

This sample text is created dynamically based on the languages supported by the font to deliver multiple strings that could reflect them.

@m4rc1e what could be done here?

**Review by vv-monsalve — APPROVED** [review]

**Pull request merged**
