### PR TITLE
Removed from this repo deprecated fonts which are not in sandbox

### LINKED ISSUE #2187: unpublished fonts
These fonts: 
Seoul Hangang, Seoul Hangang Condensed, Merge One, Amatica SC, Yinmar, Gemunu Libre, Nikukyu, Mplus1p, Myanmar Sans, Adobe Blank. Carrios Gothic, Carrios Gothic SC, Karla Tamil Incline, Karla Tamil Upright, Lao Muangdon & Lao Muangkhongnot are not available on fonts.google.com (although available in github.com/google/fonts) and should be pushed.

### PR DESCRIPTION
**Pull request by RosaWagner**
This PR intend to fix #2187: inconsistencies between fonts between this repo, in dev-sandbox, in sandbox and in production. 

- amaticasc
- andada
- andadasc
- archivovfbeta
- butchermancaps
- cabinvfbeta
- cherrybomb
- eatercaps
- faustinavfbeta
- josefinsansstdlight
- stalinone

### CODE REVIEW

**Comment by davelab6** [comment]
This LGTM! 

We need the GF eng team to confirm when merged this won't cause any issues with their ingestion process.

**Comment by rsheeter** [comment]
Can you explain how you got the binaries for this? - we'd want them to match the ones in the internal repo, which isn't necessarily true if you downloaded them from the site.

**Comment by RosaWagner** [comment]
@rsheeter thanks for your attention on this, I send you an email with more details.

**Comment by rsheeter** [comment]
Oh I'm sorry; I skimmed in a meeting and didn't notice it was only *removal*. LGTM, if it somehow crashes something for us we have a bug and will fix it.

**Comment by davelab6** [comment]
@garretrieger also LGTM'd, please merge @RosaWagner :)

**Comment by RosaWagner** [comment]
Ok great, more to come in next batch.

**Pull request merged**
