### PR TITLE
Petrona 2.001

### PR DESCRIPTION
**Pull request by yanone**
New fonts with STAT table, bumped minor version and date
https://github.com/RingoSeeber/Petrona

### CODE REVIEW

**Comment by thlinard** [comment]
An AxisValue for italic is missing (otherwise the Roman version and the Italic version will have duplicated weight names).

**Comment by m4rc1e** [comment]
Please include the upstream repo url in the body of your pr.

**Comment by yanone** [comment]
Added correct STAT table for Italics, and PRd to upstream: https://github.com/RingoSeeber/Petrona/pull/11
The PR on the upstream repo hasn't been merged yet, but last time he merged it quickly.

**Comment by thlinard** [comment]
Seems good. 😀

**Pull request merged**
