### PR TITLE
Noto Rashi Hebrew is a serif

### PR DESCRIPTION
**Pull request by simoncozens**
This:

* Changes the METADATA.pb category of Rashi Hebrew to be SERIF.
* Pairs the Hebrew with Noto Serif instead of Noto Sans.

### CODE REVIEW

**Comment by RosaWagner** [comment]
Is the number version higher ?

**Comment by simoncozens** [comment]
I didn't increase the version number on the Noto side because it's the same base font, just a new subset. I didn't think GF was too fussy about version numbers.

**Comment by RosaWagner** [comment]
It happened two or three times in the past that a font didn't get updated because the version number was the same as the previous version: I don't exactly know the push system from the eng team but I suspect same version number disturbs the tooling. Would be good to know better about that.

In any case, we are monitoring about 80 projects at the same time, the version number is the only info we have to make sure the font was actually updated in sandbox.

**Comment by simoncozens** [comment]
OK, let's close this and I'll do a new release

**Pull request closed without merging**
