### PR TITLE
Cherry Bomb One: Version 4.000; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by aaronbell**
3ebfaf0: [gftools-packager] Cherry Bomb One: Version 4.000; ttfautohint (v1.8.3) added

* Cherry Bomb One Version 4.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/satsuyako/CherryBomb.git at commit https://github.com/satsuyako/CherryBomb/commit/9f7cce81aa78b3b13eceb86ec6282f23651350a2.

 ef3abc7: [gftools-packager] ofl/cherrybombone remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by m4rc1e** [comment]
Fine to merge but we can't push this to production yet.

**Comment by thlinard** [comment]
> Fine to merge but we can't push this to production yet.

Indeed! Look at the "d", the "q"…

**Comment by RosaWagner** [comment]
We need to remove the chinese subsets in METADATA.pb

**Comment by aaronbell** [comment]
It appears that the export filter applied to the font caused an issue. I have an updated version of the font that resolves this problem. As this branch has been closed, what is the best way for me to upload the updated version?

**Comment by m4rc1e** [comment]
Make a new PR but make sure you've also bumped the font's version number.

**Comment by aaronbell** [comment]
New PR here: https://github.com/google/fonts/pull/2983

**Pull request merged**
