### PR TITLE
Cairo: Version 3.120 added

### PR DESCRIPTION
**Pull request by yanone**
c62cf64: [gftools-packager] Cairo: Version 3.120 added

* Cairo Version 3.120 taken from the upstream repo https://github.com/Gue3bara/Cairo at commit https://github.com/Gue3bara/Cairo/commit/76d942d5bcc0ea491b6ff7d9d199bd0bb817f127.

### CODE REVIEW

**Comment by RosaWagner** [comment]
same problem as Cairo Play with the font origin and regression of name ID 6

**Comment by yanone** [comment]
I'll check this out tomorrow

**Comment by yanone** [comment]
Updated

## Cairo: Version 3.120 added

---
 127d9a6: [gftools-packager] Cairo: Version 3.120 added

* Cairo Version 3.120 taken from the upstream repo https://github.com/Gue3bara/Cairo at commit https://github.com/Gue3bara/Cairo/commit/f596f41991bc01d5865cdfb9fd751b8de04b6753.

**Comment by yanone** [comment]
As far as I'm concerned: Name table entries that exist but aren't accessed aren't a problem other than a few bytes of file size.

**Pull request merged**
