### PR TITLE
Sofia Sans: Version 4.100 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
3fdbce5: [gftools-packager] Sofia Sans: Version 4.100 added

* Sofia Sans Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/b574c9c2919561f26e86816f58e6209c9292689b.

 c086b3b: [gftools-packager] ofl/sofiasans remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Notes on the PR:

- Backwards compatibility has been a priority in this project as Sofia Sans static CFF instances are used practically everywhere in Bulgaria.
- Taking Hepta Slab as a reference, and having in mind the allowed axis particles in the spec, the Hairline instance was mapped to the min value: 1 of the Weight Axis, and ExtraBlack to the max value: 1000 of the Axis Registry. This was discussed [here](https://github.com/lettersoup/Sofia-Sans/issues/19#issuecomment-722698388).
- About the Latin Encore [coverage](https://github.com/lettersoup/Sofia-Sans/issues/20#issuecomment-589700685).

**Comment by vv-monsalve** [comment]
Updated

## Sofia Sans: Version 4.100 added

---
 af9f88c: [gftools-packager] Sofia Sans: Version 4.100 added

* Sofia Sans Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/135d7197ebb2fe931460bca5d7e3296fad061aae.

 ddde97f: [gftools-packager] ofl/sofiasans remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
status update: @vv-monsalve is going to make a small fix to the fvar table before we can merge this PR. 
Otherwise I run a diff and all, and it looked good.

**Comment by vv-monsalve** [comment]
Updated

## Sofia Sans: Version 4.100 added

---
 1247475: [gftools-packager] Sofia Sans: Version 4.100 added

* Sofia Sans Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/cba178c3fe78ed2d43b73717cd2d5b72ae456503.

 fe06fe4: [gftools-packager] ofl/sofiasans remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> status update: @vv-monsalve is going to make a small fix to the fvar table before we can merge this PR.
> Otherwise I run a diff and all, and it looked good.

Thanks, Rosa. Solved in the latest update.

**Comment by vv-monsalve** [comment]
Updated

## Sofia Sans: Version 4.100 added

---
 b8ff8bb: [gftools-packager] Sofia Sans: Version 4.100 added

* Sofia Sans Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/cba178c3fe78ed2d43b73717cd2d5b72ae456503.

 e5d6399: [gftools-packager] ofl/sofiasans remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> Notes on the PR:
> 
> * Backwards compatibility has been a priority in this project as Sofia Sans static CFF instances are used practically everywhere in Bulgaria.
> * Taking [Hepta Slab](https://fonts.google.com/specimen/Hepta+Slab?query=Hep) as a reference, and having in mind the allowed axis particles in the spec, the Hairline instance was mapped to the min value: 1 of the Weight Axis, and ExtraBlack to the max value: 1000 of the Axis Registry. This was discussed [here](https://github.com/lettersoup/Sofia-Sans/issues/19#issuecomment-722698388).
> * About the GF Latin Core encoding [coverage](https://github.com/lettersoup/Sofia-Sans/issues/20#issuecomment-589700685).
> * Static folder was not included considering [this](https://github.com/googlefonts/fontbakery/issues/3099)

* fvar table includes Thin to Black instances
* STAT table includes Hairline and Extrablack as reviewed [here](https://github.com/lettersoup/Sofia-Sans/issues/19#issuecomment-723198812)

LGTM

**Comment by RosaWagner** [comment]
Interpolation issues in sandbox in the "condensed" part of the design space

**Pull request merged**
