### PR TITLE
Update to LXGW WenKai TC

### LINKED ISSUE #8695: Issue with `vert` feature not working in macOS/iOS
The font in use is [LXGW WenKai TC](https://fonts.google.com/specimen/LXGW+WenKai+TC?lang=zh_Hant)。

**Describe the bug**

When displaying LXGW WenKai TC on Apple devices (eg Safari and Google Chrome on iPad), the OpenType `vert` feature is not triggered. This caused vertical punctuations to fail to rotate. This issue does not appear on Windows/Linux devices.

iPad Safari:
Image

**To Reproduce**

Open the HTML file in Apple devices and compare to Windows/Linux devices.
<details>
  <summary> Replication HTML </summary>

```html
<html>
    <head>
        <meta charset="utf8" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=LXGW+WenKai+TC:wght@300;400;700&display=swap"
            rel="stylesheet"
        />
        <meta viewport="width=device-width, initial-scale=1, minimum-scale=1" />
        <style>
            html,
            body {
                height: 100%;
            }
            body {
                font-family: "LXGW WenKai TC", sans-serif;
                writing-mode: vertical-rl;
                height: 100%;
                font-feature-settings: "kern" 1, "liga" 1, "calt" 1, "vert" 1;
            }
        </style>
    </head>
    <body lang="zh">
        <h1>测试</h1>
        <p>
            ABCD這～是！鍵·盤＃上￥的％全……形—標＊點（符）號——橫＋排｀豎－排＝的「顯」示【情】況：一；點“明”體‘與’其『他』字，體「對」比？自、動｜橫／變豎。
        </p>
    </body>
</html>
```
</details>

**Expected behavior**

Punctuations in OpenType `vert` feature are triggered. 

Google Chrome on Windows:
Image

### PR DESCRIPTION
**Pull request by aaronbell**
The previous implementation of the `vert` feature did not include all languagesystems, so when rendering vertical text, Safari would not realize that it needed to apply the `vert` feature. This minor change enables Safari to correctly rotate punctuation for vertical typesetting Traditional Chinese. 

The fix was to remove all language-specific code and leave `DFLT` / `dflt` for the lookups. 

Fixes #8695

### CODE REVIEW

**Comment by lxgw** [comment]
Are the language-specific codes of all features removed, or only `vert` feature?

**Comment by NightFurySL2001** [comment]
@aaronbell I think you can submit a pull request to the upstream for the FEA code changes. It might also be helpful if you can merge some commits from upstream to bump the version with #8216.

**Comment by emmamarichal** [comment]
@aaronbell I let you take a look to this: https://github.com/google/fonts/pull/8714#issuecomment-2538455839 before I start the review, in case you have some changes to make :)
Ping me once it's ready to review! thanks!

**Comment by aaronbell** [comment]
Closing as there are additional changes coming.

**Pull request closed without merging**
