### PR TITLE
Montserrat Underline: Version 9.000 added



### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/JulietaUla/Montserrat at commit https://github.com/JulietaUla/Montserrat/commit/679ead9bcd0d6cef6d3712369dc49fe72e8bd8d7.
## PR Checklist:

- [ ] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [ ] `tags` are added for NEW FONTS
- [ ] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by m4rc1e** [comment]
The rename from Subrayada to Underline is intentional so I'm reopening, https://github.com/JulietaUla/Montserrat/issues/154.

**Comment by m4rc1e** [comment]
@davelab6 I'm guessing we will delist the Subrayada family?

**Comment by vv-monsalve** [comment]
HI @m4rc1e these are the findings for Montserrat Underline. After seeing similar SmallCaps issues as reported in Monserrat, I wanted to confirm if it was also happening in Word, so you'll find some reports for that.

### Windows 10

- Installation ok
- MS Word
    - SemiBold instance is not listed in the menu
    - ss01 working ok even for `Ⱦ`
    - SmallCaps works overly ok, however `ⱥ`  looking lighter in weight above 700
- ExtraLight instance test with Cyrillic looked fine (the name length issue has been confirmed to be critical with complex scripts or layouts -eg. handwriting fonts)

### macOS

- installation ok
- **MS Word**
  - ss01 works in lighter weights but not working for glyphs like `Ⱥ` or `Ⱦ` above 700
  - SmallCaps not working for `ⱥ`  `ɇ` `ⱦ`
  Screenshot 2024-11-08 at 11 31 26
- **Indesign 2025**
    - Sliders working ok
    - ss01 `Ⱦ` not working. Its also visible in FontGaulet, FontGoogles
      Screenshot 2024-11-08 at 11 54 03
      
    - SmallCaps not working from ExtraBold for `ⱥ`  `ɇ` `ⱦ` 
      Screenshot 2024-11-08 at 11 46 49

**Comment by juandelperal** [comment]
Hi Vivi and Marc

Thanks for the review.
According your screenshots, It seems that in MS word we are not getting real small caps (but scaled-down uppercases), are we?

And regarding the alternate layers replacements, we had the same issue with Montserrat, and it was related to gf-tools builder, we couldn't do anything, and added a known issue notice to the readme

https://github.com/google/fonts/pull/8281#issuecomment-2419002841

Thanks

**Comment by vv-monsalve** [comment]
Hi Juan

> According your screenshots, It seems that in MS word we are not getting real small caps (but scaled-down uppercases), are we?

I've double-checked now, and yes, that's the case, actually.

**Comment by kenmcd** [comment]
> Hi Juan
> 
> > According your screenshots, It seems that in MS word we are not getting real small caps (but scaled-down uppercases), are we?
> 
> I've double-checked now, and yes, that's the case, indeed.

Word has never supported OpenType small caps.
Same with OpenType superscript and subscript.
They are always faked.

**Comment by m4rc1e** [comment]
> If Montserrat was accepted that way, I don't think it should be a blocker. @m4rc1e, what do you think?

No blocker from me.

**Comment by vv-monsalve** [comment]
@nathan-williams 

This new font will replace the previous [Montserrat Subrayada](https://fonts.google.com/specimen/Montserrat+Subrayada). The name has been changed to English.

- Former font name: `Montserrat Subrayada` (this font will be delisted and will only be accessible to current users)
- New font name: `Montserrat Underline` (this will be the only font available to users in production at the end of this process)

I will add the former font to the [delist.txt](https://github.com/google/fonts/blob/main/to_delist.txt) file. However, please let us know if there is anything else we need to consider when replacing this font.

**Comment by vv-monsalve** [comment]
Bringing @nathan-williams chat answer here:

> We can hide Subrayada on our side once Underline is onboarded. I imagine we should wait until Underline reaches production to delist Subrayada.

**Pull request merged**
