### PR TITLE
Add human-readable names to the table

### PR DESCRIPTION
**Pull request by CatharsisFonts**
Using "nice names" as per Glyphs App convention.

### CODE REVIEW

**Comment by davelab6** [comment]
@nyshadhr9 is tabs okay, or must it be space separated?

**Comment by rsheeter** [comment]
line[2:6] needs to be the hex code for the character. If it's all comment it should start with a #. Other than that you can pretty much put whatever you like. To date we have typically put some stuff from python unicodedata in (0x0625 # ARABIC LETTER ALEF WITH HAMZA BELOW).

**Comment by davelab6** [comment]
@schriftgestalt is there a definitive source of this Glyphs App convention published online?

**Comment by schriftgestalt** [comment]
You mean a list of all nice names or a spec on how to build them? I was thinking about publishing a streamlined version of my GlyphData file ...

**Comment by davelab6** [comment]
Both :)

**Comment by davelab6** [comment]
Wasn't such a spec presented at Granshan?

**Comment by rsheeter** [comment]
Whatever we end up choosing we should update all the nam files to be consistent; in glancing at a few they are excitingly random in what comment (if any) they provide.

If we want to adopt the Glyphs nice names we probably want a python function to give the name for an arbitrary codepoint.

I'm curious, is there an advantage to Glyphs nice names vs using unicodedata to describe the character (e.g. 0x0622 # ARABIC LETTER ALEF WITH MADDA ABOVE)?

**Comment by davelab6** [comment]
@schriftgestalt any non-streamlined GlyphData files we could take a look at today? :)

**Comment by schriftgestalt** [comment]
There are some fields in the file I like to keep for myself. But those are not important in this case. I see what I can do.

**Comment by davelab6** [comment]
@schriftgestalt I'm curious if you have made any progress on this? :)

**Comment by davelab6** [comment]
@schriftgestalt is there a canonical version for this now?

**Comment by schriftgestalt** [comment]
Yes. It is in https://github.com/schriftgestalt/GlyphsInfo

**Comment by RosaWagner** [comment]
@davelab6 seeing the date of this PR, we maybe can close it ? Or is it still relevant ?

**Comment by davelab6** [comment]
Yeah this was all redone by @graphicore on our side in the https://github.com/googlefonts/gftools repo.

**Pull request closed without merging**
