### PR TITLE
Kufam font designer's info added

### PR DESCRIPTION
**Pull request by vv-monsalve**
This PR includes the catalog designer's information for Artur Schmal and Wael Morcos, authors of Kufam Family.

### CODE REVIEW

**Comment by RosaWagner** [comment]
catalog/designers/arturschmal
catalog/designers/waelmorcos

LGTM

**Comment by RosaWagner** [comment]
Artur Schmal got to sandbox, but not Wael Morcos. I checked info.pb and it misses the dieresis in the designer's name.

**Comment by vv-monsalve** [comment]
> Artur Schmal got to sandbox, but not Wael Morcos. I checked info.pb and it misses the dieresis in the designer's name.

Inspecting this in detail, which dieresis do you mean? The designer sent the information as it is and he doesn't use a dieresis in his name, nor here neither in his [webpage](http://morcoskey.com/about)

**Comment by RosaWagner** [comment]
In the metadata.pb of the font: the designer name has to match the one in the catalog, otherwise they are not linked. 

If if the designer doesn’t want to use the dieresis, then we have to remove the dieresis from kufam’s metadata.

**Comment by vv-monsalve** [comment]
> In the metadata.pb of the font: the designer name has to match the one in the catalog, otherwise they are not linked. If if the designer doesn’t want to use the dieresis, then we have to remove the dieresis from kufam’s metadata.

So the error is in the metadata of the original PR, no info.pb of this one. I'll change the metadata in another PR.

**Pull request merged**
