### PR TITLE
Zain: Version 1.20; ttfautohint (v1.8.4) added

### LINKED ISSUE #7626: Add Zain
**Font Project Git Repo URL:**

https://github.com/JuergenWillrodt/Zain (now); will be https://github.com/googlefonts/zain shortly

**Super short description of the Font Family:**

Related to https://github.com/google/fonts/issues/7625 this is a new arabic-latin family from Boutros.

**Requirements:**

Maintaining this is being delegated to Google Fonts by Boutros.

### PR DESCRIPTION
**Pull request by yanone**
Taken from the upstream repo https://github.com/googlefonts/zain at commit https://github.com/googlefonts/zain/commit/38d5fc32498b9671ea3d4df29c8ad1ca0d4a6b73.

Resolves #7626
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [x] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by yanone** [comment]
Updated

**Comment by emmamarichal** [comment]
@yanone Should I block the 1.1 version in the Sandbox then? because it looked quite urgent. At least this update corrects a big bug or mistake?

**Comment by yanone** [comment]
Yes, it corrects a mistake. 
I don't know anymore how and when to release it.
The contractor Jürgen Willrodt just told me that now they want the font publication to be delayed, which is of course the opposite of what they said earlier. I will write an email now to him and Chris and CC you. Maybe it's best to hold the release for now until this is resolved.

**Comment by emmamarichal** [comment]
@yanone Ok thanks, I'll block the first PR!

**Comment by emmamarichal** [comment]
Context: here is the update:
(glyphs added)

Screenshot 2024-06-27 at 14 23 35

**Review by emmamarichal — APPROVED** [review]

**Comment by vv-monsalve** [comment]
Dave reported that Boutros has confirmed that this is okay to go now.

**Pull request merged**
