### PR TITLE
Lexend Exa: Version 1.100 added; Lexend: Version 1.100 added; Lexend Giga: Version 1.100 added; Lexend Peta: Version 1.100 added; Lexend Mega: Version 1.100 added; Lexend Deca: Version 1.100 added; Lexend Zetta: Version 1.100 added; Lexend Tera: Version 1.100 added

### PR DESCRIPTION
**Pull request by RosaWagner**
8ecd332: [gftools-packager] Lexend: Version 1.100 added

* Lexend Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 20b9f81: [gftools-packager] ofl/lexend remove METADATA "source".  google/fonts#2587

 8465871: [gftools-packager] Lexend Deca: Version 1.100 added

* Lexend Deca Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 caec337: [gftools-packager] ofl/lexenddeca remove METADATA "source".  google/fonts#2587

 9ab01b4: [gftools-packager] Lexend Exa: Version 1.100 added

* Lexend Exa Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 49041c9: [gftools-packager] ofl/lexendexa remove METADATA "source".  google/fonts#2587

 24197ac: [gftools-packager] Lexend Giga: Version 1.100 added

* Lexend Giga Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 49177b4: [gftools-packager] ofl/lexendgiga remove METADATA "source".  google/fonts#2587

 7630e27: [gftools-packager] Lexend Mega: Version 1.100 added

* Lexend Mega Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 f0d186b: [gftools-packager] ofl/lexendmega remove METADATA "source".  google/fonts#2587

 866d31b: [gftools-packager] Lexend Peta: Version 1.100 added

* Lexend Peta Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 899b126: [gftools-packager] ofl/lexendpeta remove METADATA "source".  google/fonts#2587

 9d77c61: [gftools-packager] Lexend Tera: Version 1.100 added

* Lexend Tera Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 7233779: [gftools-packager] ofl/lexendtera remove METADATA "source".  google/fonts#2587

 dec6ab1: [gftools-packager] Lexend Zetta: Version 1.100 added

* Lexend Zetta Version 1.100 taken from the upstream repo https://github.com/RosaWagner/lexend at commit https://github.com/RosaWagner/lexend/commit/cb5b0005b7e01903191b3b5aff68bb0430d8f960.

 2215fda: [gftools-packager] ofl/lexendzetta remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
I made the PR from my own branch since I am still waiting for upstream to merge the PR and I go on holidays tomorrow.
All descriptions need to be updated, especially the one for Lexend (new) to reflect that the default weight has shifted again.

**Comment by m4rc1e** [comment]
This is fab.

The weights have changed a bit. Is this intentional?


Desktop_Windows_10_chrome_71 0_


We can see the Regular is clearly heavier.

**Comment by m4rc1e** [comment]
If this is intentional, feel free to merge.

**Comment by RosaWagner** [comment]
Intentional, but @davelab6 should maybe add explanation in the description? This is relsted to the issue linked in this PR

**Pull request merged**
