### PR TITLE
Jacquarda Bastarda 9 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
9b2bf63: [gftools-packager] Jacquarda Bastarda 9 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Jacquarda Bastarda 9 Charted Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-jacquarda-bastarda at commit https://github.com/scfried/soft-type-jacquarda-bastarda/commit/0d686fc6716df540065e5dc2b83001945eca178f.

 7119758: Description and metadatas

### CODE REVIEW

**Comment by emmamarichal** [comment]
Updated

## Jacquarda Bastarda 9 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

---
 fd72fe7: [gftools-packager] Jacquarda Bastarda 9 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Jacquarda Bastarda 9 Charted Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-jacquarda-bastarda at commit https://github.com/scfried/soft-type-jacquarda-bastarda/commit/cfc133ee284c74b8f76980a1267f4a3d45671377.

 e32fd3e: description and metadatas updated

**Comment by emmamarichal** [comment]
@vv-monsalve description updated, the non-charted version looks good in the sandbox, I think we can merge this PR :)

**Comment by vv-monsalve** [comment]
We need to solve the tagging to unblock the merge

**Comment by emmamarichal** [comment]
@chrissimpkins are the menus ok?

**Comment by chrissimpkins** [comment]
> @chrissimpkins are the menus ok?

Ready!

**Pull request merged**
