### PR TITLE
Noto Serif Ethiopic: Version 2.102 added

### PR DESCRIPTION
**Pull request by simoncozens**
e413ce4: [gftools-packager] Noto Serif Ethiopic: Version 2.102 added

* Noto Serif Ethiopic Version 2.102 taken from the upstream repo https://github.com/notofonts/ethiopic.git at commit https://github.com/notofonts/ethiopic/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
Updated

## Noto Serif Ethiopic: Version 2.102 added

---
 b17d6bf: [gftools-packager] Noto Serif Ethiopic: Version 2.102 added

* Noto Serif Ethiopic Version 2.102 taken from the upstream repo https://github.com/notofonts/ethiopic.git at commit https://github.com/notofonts/ethiopic/commit/.

**Comment by RosaWagner** [comment]
@simoncozens is this part of Q4 review, or next year review?

**Comment by simoncozens** [comment]
Ethiopic is living, so needs to be in this year if possible.

**Comment by m4rc1e** [comment]
I now have a world list for Amharic so I'll run this through diffenator2

**Review by m4rc1e — COMMENTED** [review]
Summary:

Latin is missing (probably intentional)

ETHIOPIC SYLLABLE GWA design has changed.

before:
Screenshot 2022-11-09 at 12 20 57

after:
Screenshot 2022-11-09 at 12 21 13

This change is causing a few words to change. 

STAT AxisValues has been removed
gasp has been removed
fvar instances include Condensed styles.

[noto_sans_ethiopic.zip](https://github.com/google/fonts/files/9970945/noto_sans_ethiopic.zip)

I get the feeling the family hasn't been run through gftools fix-family and the last release was.

**Comment by RosaWagner** [comment]
@m4rc1e I am looking at Noto Sans Ethiopic from #5509 and they look good, also for the serif ones in this PR. I see in your package "new" is `2.000` and "old" is `2.101`, maybe it is reversed?

**Pull request merged**
