### PR TITLE
ofl/molengo: v0.11 added. Fixed OS X validation error.

### LINKED ISSUE #1305: Font Validation report
I tested all the fonts (minus the duplicate, i.e. Alef, EkMukta, JosefinSansStd, MrBedfort, MrsSaintDelafield, Siemreap, and TerminalDosis) from the GF repo in the Font Book application (macOS 10.12.6). Here the Font Validation report:

**Errors** (“14 serious errors were found. Do not use these fonts”)
Artifika-Regular.ttf

- [x] 	‘post’ table usability

Aubrey-Regular.ttf

- [x] 	‘post’ table usability

Brawler-Regular.ttf

- [x] 	‘post’ table usability

Molengo-Regular.ttf

- [x] 	System Validation

Sarabun-Bold.ttf

- [x] 	‘post’ table usability

Sarabun-BoldItalic.ttf

- [x] 	‘post’ table usability

Sarabun-Italic.ttf

- [x] 	‘post’ table usability

Simonetta-Black.ttf

- [x] 	‘post’ table usability

Simonetta-BlackItalic.ttf

- [x] 	‘post’ table usability

Simonetta-Italic.ttf

- [x] 	‘post’ table usability

Simonetta-Regular.ttf

- [x] 	‘post’ table usability

WireOne.ttf

- [x] 	‘post’ table usability

**Warnings** (“32 minor problems were found. Proceed with caution”)
Astloch-Bold.ttf

- [x] 	‘name’ table structure

BM-HANNA.ttf

- [x] 	‘name’ table structure

CaesarDressing-Regular.ttf

- [x] 	‘name’ table structure

Flavors-Regular.ttf

- [x] 	‘name’ table structure

FrederickatheGreat-Regular.ttf

- [x] 	‘name’ table structure

Kantumruy-Bold.ttf

- [x] 	‘name’ table structure

Kantumruy-Light.ttf

- [x] 	‘name’ table structure

Kantumruy-Regular.ttf

- [x] 	‘name’ table structure

LeagueScript.ttf

- [x] 	‘name’ table structure

Padauk-Bold.ttf

- [x] 	‘name’ table structure

Padauk-Regular.ttf

- [x] 	‘name’ table structure

SeoulHangang-Light.ttf

- [x] 	‘sfnt’ required tables
- [x] 	‘vmtx’ table usability

SeoulHangang-Medium.ttf

- [x] 	‘sfnt’ required tables
- [x] 	‘vmtx’ table usability

SeoulHangangCondensed-Bold.ttf

- [x] 	‘kern’ table structure and contents

SeoulHangangCondensed-BoldL.ttf

- [x] 	‘kern’ table structure and contents

SeoulHangangCondensed-ExtraBold.ttf

- [x] 	‘kern’ table structure and contents

SeoulHangangCondensed-Light.ttf

- [x] 	‘kern’ table structure and contents

SeoulHangangCondensed-Medium.ttf

- [x] 	‘kern’ table structure and contents

SeoulNamsan-Bold.ttf

- [x] 	‘sfnt’ required tables
- [x] 	‘vmtx’ table usability

SeoulNamsan-Light.ttf

- [x] 	‘sfnt’ required tables
- [x] 	‘vmtx’ table usability

SeoulNamsan-Medium.ttf

- [x] 	‘sfnt’ required tables
- [x] 	‘vmtx’ table usability

SeoulNamsanCondensed-Black.ttf

- [x] 	‘kern’ table structure and contents

SeoulNamsanCondensed-Bold.ttf

- [x] 	‘kern’ table structure and contents

SeoulNamsanCondensed-ExtraBold.ttf

- [x] 	‘kern’ table structure and contents

SeoulNamsanCondensed-Light.ttf

- [x] 	‘kern’ table structure and contents

SeoulNamsanCondensed-Medium.ttf

- [x] 	‘kern’ table structure and contents

StardosStencil-Regular.ttf

- [x] 	‘fpgm’ table instructions

I didn't checked the mentioned issues further.

### PR DESCRIPTION
**Pull request by laerm0**
Unspecified validation error on OS X ("System Validation"), but a roundtrip through FontForge fixed it. v0.11 added. Fixes #1305.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Just ran this pr through diffbrowsers:

```
Regression Report:

Fonts: ["Molengo-Regular.ttf"]

View: glyphs-all_14pt
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 13482 pixels
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 12391 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 13447 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 8228 pixels
```

desktop_windows_10_edge_15 0_
*Edge*

```
Regression Report:

Fonts: ["Molengo-Regular.ttf"]

View: waterfall
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 41419 pixels
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 38578 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 41419 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 26829 pixels
```

desktop_windows_7_ie_9 0_

size 8, 16-19 are jumping. Which fonts did you round trip? is round tripping through FontForge changing tables related to the hints?

**Comment by laerm0** [comment]
Yeah, I see that. Hm. The hint tables are identical, but it looks like the per-glyph hints are changed. This file was hinted using [xgridfit](http://xgridfit.sourceforge.net/), which I don't know, you probably don't either, and I bet FontForge didn't parse those hints adequately when it imported the file.

Thoughts? This has FF source, so it's kinda easy to go back to the drawing board on it.

**Comment by m4rc1e** [comment]
Try running the fonts through FontVal and see if anything suspicious is flagged.

I don't like round tripping since it can destroy other data. I think its best to really work out what is causing this. It also means we can write an FB test so the issue is documented and we have tests to catch this in the future.

**Comment by laerm0** [comment]
It crashes FontVal, so whatever it is, it's really in there. OS X font validation only says "System Validation," so that's no help. It passes OTS. [check-googlefonts](https://pastebin.com/CjDZvicg) didn't throw up any real errors. A roundtrip through ttx still failed. So I was pretty stumped.

**Comment by m4rc1e** [comment]
It worked for me:
https://jsbin.com/yajilepeka/edit?output

**Comment by laerm0** [comment]
Ah, cool, thanks.

Looks like it's only the OS/2 table that has any real issues, and those are trivial. I don't think either of those would crash validation, but I'll go back to the previous version and fix that and see if it installs in OS X.

**Comment by laerm0** [comment]
Taking this font through ttx fails OS X font validation ("serious errors were found with this font"). I think OS X font validation has issues with ttx in general, actually.

Any other ways to edit the OS/2 that don't involve a font editor that you'd recommend?

**Comment by m4rc1e** [comment]
Version on Google Fonts works just fine in OS X 10.14.3. No issues with Fontbook or ttx.

**Pull request closed without merging**
