### PR TITLE
Noto Sans Limbu: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
b08c9f4: [gftools-packager] Noto Sans Limbu: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Limbu Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/limbu.git at commit https://github.com/notofonts/limbu/commit/.

This PR fixes sample text issue pointed in #4930

### CODE REVIEW

**Comment by chrissimpkins** [comment]
In sandbox.  I still see tofu:

6c5zyLytqiutC9k

Is the glyph addition noted in https://github.com/google/fonts/pull/4930#issuecomment-1261050740 subset out?

**Comment by simoncozens** [comment]
Yes, probably that. We need to also alter the nam files. I've had to do this a few times now and doing it a script at a time feels like a very scattershot approach.

If sample text is in the protobufs for a language, the associated nam file for that language needs to have support for the codepoints in that sample text. This is something we should be able to have both automated tests for, and automated fixes for.

**Comment by simoncozens** [comment]
This is now https://github.com/googlefonts/glyphsets/pull/77.

**Comment by RosaWagner** [comment]
@simoncozens dotted circle appears in sample text + one mark overlap
Capture d’écran 2022-10-14 à 15 39 34
Capture d’écran 2022-10-14 à 15 39 25

**Comment by chrissimpkins** [comment]
@twardoch Any thoughts about a new sample text source for this family?

**Comment by chrissimpkins** [comment]
OK to move to production to fix the tofu bug.  We'll continue to work on the text specimen after the production push.  @twardoch please let us know if you have ideas about how to improve the text specimens that are shown for Limbu.  Thanks all.

**Pull request merged**
