### PR TITLE
Zen Loop: Version 1.000; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
3f52add: [gftools-packager] Zen Loop: Version 1.000; ttfautohint (v1.8.3) added

* Zen Loop Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/zen-loop at commit https://github.com/googlefonts/zen-loop/commit/ed607f9dcdbfd1b721fb5ad6071f8dfad8ab8117.

 e4e41f2: [gftools-packager] ofl/zenloop remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
The reported Fails about broken links are due to it's still a private repo. I can't change that, but @davelab6 could do it ;-)

**Comment by RosaWagner** [comment]
All look good. Since I don't know the project, @vv-monsalve can you confirm that is it expected that this font doesn't contain any Japanese glyphset ?

**Comment by vv-monsalve** [comment]
> All look good. Since I don't know the project, @vv-monsalve can you confirm that is it expected that this font doesn't contain any Japanese glyphset ?

Yes, this is one of three Latin only typefaces from Yoshimichi Ohira.

**Comment by m4rc1e** [comment]
I'll leave this family open so we can review it on Thursday's push meeting.

Desktop_Windows_10_chrome_71 0_

**Comment by davelab6** [comment]
@m4rc1e lgtm, lets discus tomorrow

**Pull request merged**
