### PR TITLE
Knowledge: xopq_axis/content.md

### PR DESCRIPTION
**Pull request by davelab6**
Updated based on discussions in https://twitter.com/TiroTypeworks/status/1525134013530185728

This is currently a draft PR as similar edits are needed to YOPQ if this is accepted; possibly it should go into the Introduction article.

It might be good to add a GFKized version of the illustration @dberlow provided in the thread to the Introduction article.

### CODE REVIEW

**Comment by davelab6** [comment]
I also want to update the intro article to include a paragraph or two explaining the axis scales, which might also add a sentence into each glossary definition; https://github.com/googlefonts/roboto-flex/issues/328 might be the best source for that atm

**Comment by RosaWagner** [comment]
@davelab6 @elliotjaystocks This PR is open since May 2022, let's merge or close :)

**Comment by RosaWagner** [comment]
@davelab6 please resume this PR or close

**Comment by RosaWagner** [comment]
This PR has been open for a very long time with no intent to resume it, therefore it doesn't seem necessary. Closing.

**Pull request closed without merging**
