### PR TITLE
Update Work Sans to v1.51

### PR DESCRIPTION
**Pull request by weiweihuanghuang**
- Fixed /m stem in Black Master
- Fixed some bugs (iacute_j, localCAT, among others)
- Created Combining diacritics from diacritics already in fonts
- Added anchors, will now support some African orthographies (thanks to Denis Moyogo Jacquerye for the last two)

### CODE REVIEW

**Comment by weiweihuanghuang** [comment]
signed

**Comment by m4rc1e** [comment]
@davelab6 We should merge this as well. 

Thanks @weiweihuanghuang

**Comment by weiweihuanghuang** [comment]
Hi I would holdn't use this pull anymore to be honest, since Glyphs app updated the way it generates TTFs since when my ttfa delta files were written they're not going to be correct anymore...

**Comment by m4rc1e** [comment]
Ok thanks @weiweihuanghuang, I hope all is well.

Feel free to pr it again sometime. 

I'll close this for now.

**Comment by davelab6** [comment]
Should we push your latest release?

**Comment by weiweihuanghuang** [comment]
No

**Comment by davelab6** [comment]
Ok 😂 Do you plan to work on Work Sans much further?

**Comment by weiweihuanghuang** [comment]
Yes, cant give definite timelines though!

**Comment by davelab6** [comment]
I'm wondering if it would be better to get it hand hinted with vtt at some
point...

Or, Werner needs to figure out a way to help make your ttfa manual file
continue to work 😂

**Comment by lemzwerg** [comment]
Usually, you can execute ttfautohint again, *after* glyphs.  I thus guess that you only have to adapt to changed point indices.

**Comment by weiweihuanghuang** [comment]
I'd be open to getting it VTT hinted sure that would be great.
Right, so I need going through every glyph that has deltas and find the new point indices, which will take me some time.

**Pull request closed without merging**
