### PR TITLE
Noto Sans Buginese: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
e305bdf: [gftools-packager] Noto Sans Buginese: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Buginese Version 2.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/buginese.git at commit https://github.com/notofonts/buginese/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens marks are shifting, is it ok?
Desktop_Windows_10_chrome_71 0_

**Comment by vv-monsalve** [comment]
@simoncozens I've reviewed them in the local Browserstack server, and it's also not working under Catalina's Safari or the latest Edge and Chrome versions.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Buginese: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

---
 c21d606: [gftools-packager] Noto Sans Buginese: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Buginese Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/buginese.git at commit https://github.com/notofonts/buginese/commit/.

**Comment by simoncozens** [comment]
Try again with this version.

**Comment by vv-monsalve** [comment]
LGTM
Desktop_Windows_10_edge_18 0_

**Pull request merged**
