### PR TITLE
Beta variable fonts added to Early Access R02

### PR DESCRIPTION
**Pull request by m4rc1e**
Another 8 fonts.

I've included a few serifs as well :-)

Tested using [Axis Praxis](http://www.axis-praxis.org)

### CODE REVIEW

**Comment by davelab6** [comment]
Asap should have 2 axes for width and weight, i guess

**Comment by m4rc1e** [comment]
@davelab6 Asap has been drawn as two separate families, Asap, https://github.com/Omnibus-Type/Asap and Asap Condensed, https://github.com/Omnibus-Type/AsapCondensed.

There are a few families which have this problem. Also, Oblique fonts could be included with Romans.

I can remove Asap for the time being, if you wish?

**Comment by davelab6** [comment]
I'll merge and remove it

**Comment by m4rc1e** [comment]
Thanks!

**Pull request merged**
