### PR TITLE
NaN designer profile

### PR DESCRIPTION
**Pull request by yanone**
Designer of Rubikk filtered fonts + Unbounded

### CODE REVIEW

**Comment by RosaWagner** [comment]
@yanone The green square as image may be a bit disappointing once online with grayscale transfer. Do you want to ask Luke for a logo that works in black and wight?

**Comment by yanone** [comment]
What do you mean by grayscale transfer? Where is this applied? They don't really have a logo, but I could ask

**Comment by RosaWagner** [comment]
All profil pictures on GF appear gray, even if they are coloured in the repo

**Comment by yanone** [comment]
I'll ask

**Comment by yanone** [comment]
Updated the image

**Pull request merged**
