### PR TITLE
JetBrains Mono: Version 2.211 added

### PR DESCRIPTION
**Pull request by RosaWagner**
846794f: [gftools-packager] JetBrains Mono: Version 2.211 added

* JetBrains Mono Version 2.211 taken from the upstream repo https://github.com/JetBrains/JetBrainsMono at commit https://github.com/JetBrains/JetBrainsMono/commit/bb91b14fbbf0c5295165d993983571b9e70eaca8.

 8e7c101: [gftools-packager] ofl/jetbrainsmono remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
LGTM. The name is an expected fail.

**Comment by m4rc1e** [comment]
Just took a quick look. STAT doesn't have any Axis Values.

**Comment by RosaWagner** [comment]
Mh… Somehow fix-vf-meta disappeared from the build script… There should be a Fontbakery check for this.

**Comment by RosaWagner** [comment]
Updated

## JetBrains Mono: Version 2.211 added

---
 6d23b58: [gftools-packager] JetBrains Mono: Version 2.211 added

* JetBrains Mono Version 2.211 taken from the upstream repo https://github.com/JetBrains/JetBrainsMono at commit https://github.com/JetBrains/JetBrainsMono/commit/6a005ca77d9202aa12fc277aefa8f5bb4eb7f0cd.

 c514973: [gftools-packager] ofl/jetbrainsmono remove METADATA "source".  google/fonts#2587

**Pull request merged**
