### PR TITLE
Noto Sans Cham: Version 2.005 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/cham at commit https://github.com/notofonts/cham/commit/1688bf8b8c53fbc07d363c5ab31610a1a65f16f9.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
This release removes a semibold master.

**Comment by vv-monsalve** [comment]
> 🔥 FAIL Ensure dotted circle glyph is present and can attach marks.

Please review this fail.

Tofu (same Eng and eng case as int the other fonts)

Screen Shot 2024-05-23 at 15 55 04

**Comment by vv-monsalve** [comment]
@simoncozens, I think you've solved the dotted circle failure for other Noto fonts that have been reviewed before. Let me know if you would like to do it here.

Other than that, LGTM.

**Comment by simoncozens** [comment]
Same deal as Balinese. We'll get it working automatically eventually, but the important marks are anchored correctly.

**Comment by vv-monsalve** [comment]
Okay. Merging this here now in that case.

**Pull request merged**
