### PR TITLE
Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
3989f48: [gftools-packager] Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Brahmi Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/brahmi.git at commit https://github.com/notofonts/brahmi/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
Noto Sans Brahmi v2.004

This release:

* Covers new codepoints in Unicode 14.0 (U+11071, U+11072), thanks to Ek Type.
* Adds space before vocalic R (#6)
* Improves the anchoring of AI vowel, BHATTIPROLU AA, and digits (#2, #4, #5)
```

**Comment by vv-monsalve** [comment]
> * Adds space before vocalic R 

@simoncozens Thanks for the context notes. I've inspected the # 6 issue on the Noto Issue tracker, however confirming here if the new space is the intended. It looks a bit wide (close to the space).
NotoSansBrahmi-ba

**Comment by simoncozens** [comment]
Good catch, I've fixed it another way and done a new release.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

---
 5ee2a85: [gftools-packager] Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Brahmi Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/brahmi.git at commit https://github.com/notofonts/brahmi/commit/.

**Comment by vv-monsalve** [comment]
Hi, @simoncozens; I'm spotting more changes (from the previous version). A new glyph that looks with wider space, some changes on other glyphs, and a dot that looks clashing with a base letter. 

There are also two glyphs reported as modified. Please check the images and confirm everything.

Noto-Brahmi-New-findings

Noto-Brahmi-Modified-glyphs

**Comment by simoncozens** [comment]
The kerning is a bit wrong, but everything else is fine. I'll try again with new kerning rules.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

---
 3353f45: [gftools-packager] Noto Sans Brahmi: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Brahmi Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/brahmi.git at commit https://github.com/notofonts/brahmi/commit/.

**Comment by emmamarichal** [comment]
Thanks @simoncozens!
I just need a last confirmation about `𑀤𑀾`, that changed compared to the previous version:

https://github.com/google/fonts/assets/64773544/3aa5573d-acac-42e2-95aa-d6c8c4cd10fb

If it's intentional, then I'll merge the PR :)

**Comment by simoncozens** [comment]
Yes, this is OK. The glyph was changed by Unicode a long time ago (https://github.com/notofonts/brahmi/issues/8) and this is the first release since then.

**Pull request merged**
