### PR TITLE
Mplus 1p: hotfix font name

### LINKED ISSUE #4731: M Plus 1P static fonts Bold has broken name table
A user wrote in,

> with the M Plus 1P font.
> When downloading the font from Google Fonts and install it locally, we noticed that the MPlus 1P - Bold weight is mapped incorrectly as a separate font. (Please refer to the attached image)
> This issue happens also when we try to deploy the font inside our developed application.
> Due to this incorrect mapping, the Bold weight is not being read correctly and significantly affect our development as a result.
> Our team suspect that this issue is caused by the incorrect Meta information, which removed the Bold weight from the family.
> 
> Screenshot 2022-06-02 at 12 30 26

Should be a quick hot fix, or a complete upgrade to the latest family version

### PR DESCRIPTION
**Pull request by RosaWagner**
Fixes #4731 

Apparently there was no metadata.pb before
also bumped up version number

### CODE REVIEW

**Comment by RosaWagner** [comment]
The name used to find this font in GF is ["M PLUS 1p"](https://fonts.google.com/specimen/M+PLUS+1p), and not the actual name of the font ("Mplus 1p"), so I added a display_name field like in Noto fonts, but no idea if it is how we should proceed here.

**Comment by RosaWagner** [comment]
Dave says: 

"The display name was special for Noto, in this case we should fix the name table I think. 

This was onboarded to Early Access, which didn't use METADATA, and when migrated to the API, we forgot to publish the internal METADATA file. 

So someone should back-convert the internal one to the external format and diff with what Rosalie has, and merge so the new one will be in sync and the best version for the latest file."

**Comment by davelab6** [comment]
https://fonts.google.com/specimen/M+PLUS+1p uses `M PLUS 1p` (with that capitalization) as the family name in the API, and that should be used in the name/etc tables.

Screen Shot 2022-07-02 at 12 07 53 PM

Here's the METADATA file we have internally, back converted:

```
name: "M PLUS 1p"
designer: "Coji Morishita, M+ Fonts Project"
license: "OFL"
category: "SANS_SERIF"
date_added: 2017-06-12
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 100
  filename: "MPLUS1p-Thin.ttf"
  post_script_name: "MPLUS1p-Thin"
  full_name: "M PLUS 1p Thin"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 300
  filename: "MPLUS1p-Light.ttf"
  post_script_name: "MPLUS1p-Light"
  full_name: "M PLUS 1p Light"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 400
  filename: "MPLUS1p-Regular.ttf"
  post_script_name: "MPLUS1p-Regular"
  full_name: "M PLUS 1p"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 500
  filename: "MPLUS1p-Medium.ttf"
  post_script_name: "MPLUS1p-Medium"
  full_name: "M PLUS 1p Medium"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 700
  filename: "MPLUS1p-Bold.ttf"
  post_script_name: "MPLUS1p-Bold"
  full_name: "M PLUS 1p Bold"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 800
  filename: "MPLUS1p-ExtraBold.ttf"
  post_script_name: "MPLUS1p-ExtraBold"
  full_name: "M PLUS 1p ExtraBold"
  copyright: "Copyright 2016 The M+ Project Authors."
}
fonts {
  name: "M PLUS 1p"
  style: "normal"
  weight: 900
  filename: "MPLUS1p-Black.ttf"
  post_script_name: "MPLUS1p-Black"
  full_name: "M PLUS 1p Black"
  copyright: "Copyright 2016 The M+ Project Authors."
}
subsets: "cyrillic"
subsets: "cyrillic-ext"
subsets: "greek"
subsets: "greek-ext"
subsets: "hebrew"
subsets: "japanese"
subsets: "latin"
subsets: "latin-ext"
subsets: "menu"
subsets: "vietnamese"
```

The `name` on the first line defines the API name, and matches the `name` keys in the `fonts` items.

The actual name of the font in each file's metadata must be updated (from `Mplus 1p` to `M PLUS 1p`

**Comment by vv-monsalve** [comment]
Followed in #4935

**Pull request closed without merging**
