### PR TITLE
dosis v2.007 added 

### PR DESCRIPTION
**Pull request by m4rc1e**
No bugs apart from #279 which is asking for a Romanian char set expansion

### CODE REVIEW

**Comment by impallari** [comment]
I wont recommend publishing this, there a a lot of diacritic related issues in v2.007

**Comment by davelab6** [comment]
@impallari thanks for catching this :) I'll assign to Marc to resolve

**Comment by m4rc1e** [comment]
pr kept open. We'll be resolving this next year.

**Comment by davelab6** [comment]
@impallari any news on this? :)

**Comment by m4rc1e** [comment]
Dosis is now at V2.031.

I can't pr the latest version yet since there are a lot of glyphs missing.


screen shot 2017-07-10 at 14 12 00


@impallari shall I fix the ibreve and we pr this at v2.007? I understand you may be currently working on an update

**Comment by m4rc1e** [comment]
closing.

We will have a newer version pr'd soon.

**Comment by m4rc1e** [comment]
ping @impallari

**Pull request closed without merging**
