### PR TITLE
fraunces: v1.000 added.

### PR DESCRIPTION
**Pull request by arrowtype**
_Taking over for https://github.com/google/fonts/pull/2755, using a shell script to update rather than the gftools packager, which I was having trouble with._

This is Fraunces after [some mastering work](https://github.com/arrowtype/Fraunces/issues/1).

It includes two variable fonts:
- Fraunces (the variable font, axes [SOFT,WONK,opsz,wght])
- Fraunces Italic (variable font, axes [SOFT,WONK,opsz,wght])

...and 108 static fonts, 6 weights w/ Roman & Italics in the following families:
- Fraunces 9pt [Sharp]
- Fraunces 9pt Soft
- Fraunces 9pt SuperSoft
- Fraunces 72pt [Sharp]
- Fraunces 72pt Soft
- Fraunces 72pt SuperSoft
- Fraunces 144pt [Sharp]
- Fraunces 144pt Soft
- Fraunces 144pt SuperSoft

It is possible that the `STAT` table may still need a small adjustment, pending resolution of https://github.com/google/fonts/issues/2741.

### CODE REVIEW

**Comment by arrowtype** [comment]
The latest here: @sponcey has agreed with the Wonky/NonWonky STAT naming:

https://github.com/google/fonts/pull/2765#issuecomment-728304730

Once that is merged, this should be merged, as the VF in this PR also uses Wonky/NonWonky STAT naming.

**Comment by davelab6** [comment]
@arrowtype now that #2765 is merged, do you need to do a final rebuild?

**Comment by davelab6** [comment]
The next week is the final week to get new families info sandbox and then production on Monday 14th so would be great if this can be merged this week 👎

**Comment by arrowtype** [comment]
@davelab6 Because the fallback is now officially `Wonky` and `Non Wonky`, I believe the font is actually ready to merge!

The font includes `NonWonky` (with no space) in the STAT table, which follows the formatting convention of all other style names, e.g. `ExtraBold`, `SemiBold`, etc etc.

**Comment by m4rc1e** [comment]
Alright, let's merge this.

**Pull request merged**
