### PR TITLE
arefruqaa: v1.003

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by khaledhosny** [comment]
FWIW, the previous version was completely broken in Adobe design apps as they apparently choke on fonts with cvXX feature params.

**Comment by m4rc1e** [comment]
Thanks @khaledhosny.

**Comment by m4rc1e** [comment]
All looks good apart from the space width has changed significantly which is causing overflow.

Desktop_Windows_10_chrome_71 0_

**Comment by khaledhosny** [comment]
That Chrome bug again, I guess. Not sure what to do this time, I’m building the Arabic and Latin fonts separately because there is no way to reliably merge to UFO/Glyphs/SFD fonts together, and then merge the binary fonts with `fontTools.merge` and since the Arabic is the first font (otherwise font metadata will be inherited from the Latin font) it makes the Arabic space the default and adds Latin space to `locl` feature.

**Comment by khaledhosny** [comment]
Hmm, I tested on Chrome and the spacing looks fine actually, how are you testing this?

**Comment by m4rc1e** [comment]
> how are you testing this?

The screenshots were taken using the BrowserStack Screenshots api. They haven't updated their browsers in a long time so the version I'm testing is Chrome 71.

I've found that the fonts are working correctly in newer versions of Chrome so I'm tempted to just merge this.

I've attached the test files which were generated using `gftools gen-html`

[arefrruqaa-diffs.zip](https://github.com/google/fonts/files/6197624/arefrruqaa-diffs.zip)

**Comment by khaledhosny** [comment]
Apparently Chrome fixed the bug that was blocking #2893, and this was another manifestation of it.

**Pull request merged**
