### PR TITLE
Redacted: Version 1.001; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by emmamarichal**
1bee8b7: [gftools-packager] Redacted: Version 1.001; ttfautohint (v1.8.3) added

* Redacted Version 1.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/christiannaths/redacted-font at commit https://github.com/christiannaths/redacted-font/commit/dae1afaa7d96c89825c5e0193f07b4b16ccef4d7.

 65044f2: [gftools-packager] ofl/redacted remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
I think I gave wrong vertical-metrics directions to Emma. We gonna roll back a fix.

**Comment by emmamarichal** [comment]
Updated

## Redacted: Version 1.002; ttfautohint (v1.8.3) added

---
 eae877b: [gftools-packager] Redacted: Version 1.002; ttfautohint (v1.8.3) added

* Redacted Version 1.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/christiannaths/redacted-font at commit https://github.com/christiannaths/redacted-font/commit/c86d607ca8531631aeff4d3aacb44de05a2ed523.

 3ed74ad: [gftools-packager] ofl/redacted remove METADATA "source".  google/fonts#2587

**Comment by m4rc1e** [comment]
Just a thought but couldn't we use a format 13 cmap table? https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-13-many-to-one-range-mappings

Since every glyph has a width of 375, it may be easier to map all code points to a single glyph.

**Comment by RosaWagner** [comment]
How do we achieve that?

**Comment by m4rc1e** [comment]
.glyphs and .ufo allow glyphs to have multiple unicodes. I don't think ufo2ft supports this yet so I've just opened an issue.

**Pull request merged**
