### PR TITLE
merriweathersans: v2.000 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/TypeNetwork/Merriweather-Sans at commit https://github.com/TypeNetwork/Merriweather-Sans/commit/b37362977e331ffce377ba94b96fd866b76d59e4

### CODE REVIEW

**Comment by anushbhatia** [comment]
sir reply to my pr #2557

**Comment by thlinard** [comment]
Hi @m4rc1e 

Could gftools-fix-vf-meta.py be applied to these two VF? Their STAT table is almost empty.

**Comment by m4rc1e** [comment]
@thlinard we're going to talk to Adobe soonish regarding this matter. Even if you get the STAT tables "correct", the sliders may not work in Indesign etc. We can easily push an update once the apps have sorted out their support. Anyways, pdfs and postscript don't support VFs yet so I recommend not using them for DTP apps.

**Comment by m4rc1e** [comment]
@thlinard that's not to say we won't fix this. It's just we're not sure what's the right approach, given the current state of vf support in these apps.

**Comment by thlinard** [comment]
@m4rc1e well, at least with gftools-fix-vf-meta.py the fonts work in Photoshop (named instances and sliders), and the named instances work in InDesign.

There, only the named instances work.

Adobe is certainly at fault, but on the other hand I understand them: they need properly made fonts first to test their own bugs.

**Pull request merged**
