### PR TITLE
Moderustic: Version 2.120 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/Tural/Moderustic at commit https://github.com/Tural/Moderustic/commit/bb3aa38f789ead5002524d44f97045fb531811cf.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [x] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
I sent an email to the designer to get some images and the PR for the designer profile is ready! 🎉

**Comment by vv-monsalve** [comment]
@emmamarichal These are the main checks that would need attention

- 🔥 FAIL METADATA.pb: Check URL on copyright string is the same as in repository_url field.
   It's a capitalization issue
- 🔥 FAIL Shapes languages in all GF glyphsets.
    This would be solved by the soft dotted glyphs. Related to:
    ⚠️ WARN Ensure soft_dotted characters lose their dot when combined with marks that replace the dot.
- ⚠️ WARN Ensure fonts have ScriptLangTags declared on the 'meta' table.

On the glyphs, please review the following

- Bars, strokes and macron look bit too light for the system
    Screen Shot 2024-07-10 at 18 29 52

- `multiply` has a hole in the intersection and Catalán punt volat spacing

Screen Shot 2024-07-10 at 18 33 03

- `Y` is looking heavy. Also check kerning consistency, e.g `LY`, `AVA`
Screen Shot 2024-07-10 at 18 33 40

**Comment by emmamarichal** [comment]
Updated

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
LGTM

**Pull request merged**
