### PR TITLE
Radio Canada Display: Version 1.001 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/googlefonts/radiocanadadisplay at commit https://github.com/googlefonts/radiocanadadisplay/commit/6bea54bb10a8c296a42a50a76d506637fcc262be.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [x] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not) https://github.com/google/fonts/issues/7515
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
@m4rc1e @felipesanches I think we have a fontbakery issue here! 🤪

**Comment by felipesanches** [comment]
@emmamarichal, sorry for not having replied earlier. I only saw your message now.

I noticed 2 problems at once:
* An ERROR on an experimental check (which is fine)
* The inclusion of a longer quoted message detailing the ERROR, though, resulted in broken github markdown syntax.

I have now manually fixed the report, so that you can read the results. And I am now trying to fix fontbakery to avoid the same problems from happening again on future PRs.

**Comment by emmamarichal** [comment]
Great, thank you! @felipesanches

**Comment by emmamarichal** [comment]
@vv-monsalve 
🔥 **FAIL** Combined length of family and style must not exceed 32 characters.
-> Don't really know how to solve it

⚠️ **WARN** Each font in set of sibling families must have the same set of vertical metrics values.
-> The check compared this family with the Radio Canada one, already on GF. This check makes sense, but I don't feel confortable to change the v-metrics chosen by the designer. What do you think?

**Comment by vv-monsalve** [comment]
> -> Don't really know how to solve it

- We have discussed with Emma the option of using `Head` or `H` instead of `Display`. Let's see what @davelab6 says.

- The VMs are really tight now. The font could benefit from a bit looser leading (even to leave room for further updates) and centering the caps in the line
Screen Shot 2024-04-12 at 9 43 42

**Comment by davelab6** [comment]
I propose `Radio Canada Big` as a family name

**Comment by emmamarichal** [comment]
@vv-monsalve I close that PR since the name changed! Will open a new one

**Pull request closed without merging**
