### PR TITLE
vollkorn: v4.015 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Thanks @FAlthausen

### CODE REVIEW

**Comment by FAlthausen** [comment]
When will this go life? People want to use Vollkorn 4.0 instead of three years old Vollkorn 2.1!

**Comment by thlinard** [comment]
The [previous version](https://github.com/google/fonts/tree/be482e97a2064503e851c911abc0f2b058716e88/ofl/vollkorn) was already v4.015 (even if the commit's title says v4.014). What's the difference between the two v4.015?

**Comment by m4rc1e** [comment]
@thlinard upstream repo was one commit ahead of my last pr. This has changed https://github.com/FAlthausen/Vollkorn-Typeface/commit/3c1909a419a13eaf222cf9324b2c6d5be080c47e

**Comment by davelab6** [comment]
I can't give an exact date but soon :)

**Comment by FAlthausen** [comment]
When will this go life? People want to use Vollkorn 4.0 instead of three and a half years old Vollkorn 2.1!

**Comment by davelab6** [comment]
Soon :)

**Comment by FAlthausen** [comment]
Wow! After three and a half year Vollkorn got its first update on GoogleFonts! I was about to start celebrating when I found out that the small caps fonts are lost somewhere! 
Please publish the “Vollkorn SC” family, too!

**Comment by davelab6** [comment]
> Please publish the “Vollkorn SC” family, too!

This was done :)

https://fonts.google.com/specimen/Vollkorn+SC

**Pull request merged**
