### PR TITLE
Gungsuhche: Version 2.21 added



### PR DESCRIPTION
**Pull request by aaronbell**
Taken from the upstream repo https://github.com/googlefonts/batang at commit https://github.com/googlefonts/batang/commit/6c1e09f93204c963881afbb4e25699095565f2e5.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Review by m4rc1e — DISMISSED** [review]
@aaronbell We should probably fix the following:

- The METADATA.pb file has no `SLAB_SERIF` category. Should be changed it to `SERIF`.
- The filename should be `GungsuhChe-Regular.ttf`
- The vertical metrics should probably follow our CJK recommendations, which were set by Ken Lunde. Is there a reason for your particular values?

**Comment by aaronbell** [comment]
The vertical metrics follow what the Windows version has set for compatibility reasons. We certainly can change them but that could result in unexpected reflow. (@davelab6 )

**Comment by aaronbell** [comment]
@m4rc1e Updated the vertical metrics and some other metadata items.

**Comment by emmamarichal** [comment]
Are we ok with that very large spacing for cyrillic?

Screenshot 2024-06-25 at 16 14 56

**Comment by aaronbell** [comment]
@emmamarichal Many CJK fonts, when monospaced, are designed with full-width Cyrillic and Greek. I've always found it odd in comparison that the Latins are set to half-width (since there's unicode slots for full width Latins), but that's how things are.

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
