### PR TITLE
Honk: Version 1.000 added

### PR DESCRIPTION
**Pull request by yanone**
8b744f9: [gftools-packager] Honk: Version 1.000 added

* Honk Version 1.000 taken from the upstream repo https://github.com/EkType/Honk at commit https://github.com/EkType/Honk/commit/2e591a75cce4068dabee6552d6423c15e4a33301.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@yanone if the default value of the family is different from the one declared in the axis registry, we need to add the registry_default_override key to METADATA.pb https://googlefonts.github.io/gf-guide/metadata.html#registry_default_overrides

**Comment by RosaWagner** [comment]
@yanone for variable families with a single-weight style we allow several instances in the FVAR table as we did for Kablammo. Is it something the authors would be interested in?

Screenshot 2023-11-15 at 14 22 19

**Comment by yanone** [comment]
> Is it something the authors would be interested in?

Yes, absolutely. The source has such oddly-named instances. I will add them back and amend the PR. Thank you.

**Comment by yanone** [comment]
Updated

## Honk: Version 1.000 added

---
 b95114c: [gftools-packager] Honk: Version 1.000 added

* Honk Version 1.000 taken from the upstream repo https://github.com/EkType/Honk at commit https://github.com/EkType/Honk/commit/964739fca4b7f5485b21525df1e803fffbe6da99.

**Review by RosaWagner — APPROVED** [review]

**Comment by emmamarichal** [comment]
Solved thanks new axis
https://github.com/google/fonts/assets/64773544/77278143-118b-4c38-9b3c-5e70712a75d9

**Pull request merged**
