### PR TITLE
Pixelify Sans: Version 1.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
2101f61: [gftools-packager] Pixelify Sans: Version 1.000 added

* Pixelify Sans Version 1.000 taken from the upstream repo https://github.com/eifetx/Pixelify-Sans at commit https://github.com/eifetx/Pixelify-Sans/commit/ac61403c4763697ea2832542a4e586d4e062847f.

 c35c851: description and metadata

### CODE REVIEW

**Comment by RosaWagner** [comment]
@emmamarichal there is not so much difference between the different weights, the range should probably be brought back to Regular-Bold, no ?

Screenshot 2023-09-13 at 12 03 57
Screenshot 2023-09-13 at 12 04 08

**Comment by emmamarichal** [comment]
@RosaWagner Ah yes, it would be better, I will see with the designer if it's ok, but it shouldn't be a problem for him!

**Comment by emmamarichal** [comment]
Updated

## Pixelify Sans: Version 1.000 added

---
 9ce5017: [gftools-packager] Pixelify Sans: Version 1.000 added

* Pixelify Sans Version 1.000 taken from the upstream repo https://github.com/eifetx/Pixelify-Sans at commit https://github.com/eifetx/Pixelify-Sans/commit/b862e0925f58e77583ddb2e056a2d667f2f3544a.

 efd3f87: description and metadata

**Comment by emmamarichal** [comment]
@RosaWagner updated!

**Comment by RosaWagner** [comment]
@emmamarichal did you check the vertical metrics to see if they were dramatically not-centered or just a little bit?

⚠ WARN: Check if uppercase glyphs are vertically centered. ([com.google.fonts/check/caps_vertically_centered](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/caps_vertically_centered))
⚠ WARN Uppercase glyphs are not vertically centered in the em box. [code: vertical-metrics-not-centered]

**Comment by emmamarichal** [comment]
@RosaWagner So weird I missed this check 🤔
I just had a look:
typoascenders=920
typodescenders= -280
caps height= 700

To have centered caps, we would need 950 and -250, so I think we can keep this version?

**Comment by RosaWagner** [comment]
Yes all good, the threshold of that check should probably be a bit higher

**Review by RosaWagner — APPROVED** [review]

**Pull request merged**
