### PR TITLE
sync ./axisreg dir with googlefonts/axisregistry repo

### PR DESCRIPTION
**Pull request by m4rc1e**
@chrissimpkins  Is there any reason why we cannot do this?

If we merge this, both googlefonts/axisregistry and the axisregistry dir in this repo will be in sync. However, I've squashed the axisregistry commits.

I used the following command:

`git subtree add --prefix axisregistry/ https://github.com/googlefonts/axisregistry main --squash`

### CODE REVIEW

**Comment by m4rc1e** [comment]
I think I finally get it.

If we simply try to pull in the existing subtree (in this pr, I deleted the subtree then readded) with the command `git subtree pull --prefix axisregistry/ https://github.com/googlefonts/axisregistry main`, we get a merge conflict.

```
CONFLICT (content): Merge conflict in axisregistry/tox.ini
Auto-merging axisregistry/Lib/axisregistry/__init__.py
CONFLICT (content): Merge conflict in axisregistry/Lib/axisregistry/__init__.py
Automatic merge failed; fix conflicts and then commit the result.
```

Lemme see if I can simply fix this conflict.

**Comment by chrissimpkins** [comment]
> Lemme see if I can simply fix this conflict.

Yep! That is what we need.  Ty!

**Comment by chrissimpkins** [comment]
Should be done in googlefonts/axisregistry and git subtree pulled here though.  I suggest that we stop directly touching the files in google/fonts axisregistry or we just need to pull changes back into googlefonts/axisregistry

**Comment by m4rc1e** [comment]
I feel the cleanest is what I've just done and force pushed:

- rm the badly synced axisregistry subtree (imo this is broken, not googlefonts/axisregistry)
- readd the axisregistry subtree

This took 3 commits and it also means I don't have to mess around with the googlefonts/axisregistry when there's absolutely nothing wrong with it. 

In the future, folks can simply update the axisregistry subtree in this repo by doing:

`git subtree pull --prefix axisregistry/ https://github.com/googlefonts/axisregistry main --squash`


I agree with never making tweaks to this one so we avoid getting out of sync going forward. In fact I want this to be a complete non-issue. I want a gh action to check if googlefonts/axisregistry has been updated and just do a subtree pull for us.

**Comment by chrissimpkins** [comment]
> git subtree pull --prefix axisregistry/ https://github.com/googlefonts/axisregistry main --squash

We added the documentation in https://googlefonts.github.io/gf-guide/googlefonts.html#axis-registry

Rod asked that we not squash on the git subtree pull.  This supports review of the commits on this side then they are squashed at main branch merge time.

> @chrissimpkins if you disagree with the above. I don't have a problem with you merging your pr in googlefonts/axisregistry and then undoing it and repulling it here.

No, no.  I'm fine with any approach that makes the two in sync so that we can use git subtree pulls to pull changes from googlefonts/axisregistry and googlefonts/lang into this repo.

**Comment by vv-monsalve** [comment]
Rod has recently merged a new [PR](https://github.com/google/fonts/pull/5108) for the `axisregistry` directly here on `google/fonts`. Would this PR (approach) leave the `googlefonts/axisregistry` out of sync if merged?

**Comment by rsheeter** [comment]
Those changes are present upstream as well. I updated directly on
google/fonts because subtree pulls are currently blocked. As soon as that
gets unblocked unblock we can move to that exclusively.

**Pull request closed without merging**
