### PR TITLE
ofl/robotoflex/article updated with youtube embed

### PR DESCRIPTION
**Pull request by davelab6**
Per internal discussion, perhaps we can embed youtube videos on specimen pages properly rather than the current workaround :)

### CODE REVIEW

**Comment by tomasdev** [comment]
This won't have the desired effect until b/332954475 is solved. Added a comment on that ticket.

**Comment by vv-monsalve** [comment]
Isn't this somehow repeated on #7518? (Could this change be handled there?)
The `hero.jpg` is reported as missing there.

**Comment by tomasdev** [comment]
> Isn't this somehow repeated on #7518? (Could this change be handled there?) The `hero.jpg` is reported as missing there.

Not really. This one is about an upcoming feature where we allow YouTube embeds directly on the about page. The jpg optimization from #7518 will probably land before this feature, so still good to have both.

**Comment by vv-monsalve** [comment]
Thanks, Tomas, for the clarification. We'll wait for your signal then for when b/332954475 is solved to merge this PR.

**Comment by tomasdev** [comment]
b/332954475 has been fixed, feel free to squash and merge this one whenever!

**Pull request merged**
