### PR TITLE
Correct order of subsets in METADATA.pb

### PR DESCRIPTION
**Pull request by sapics**
I guess that subsets are sorted in alphabetical order except 'menu'.
This pr correct order of subsets.

### CODE REVIEW

**Comment by davelab6** [comment]
@rsheeter what is the canonical order?

**Comment by rsheeter** [comment]
I don't recall offhand that there is one; we typically view them as a set.
Having the order be consistent in textproto form sounds reasonable.

**Comment by davelab6** [comment]
Alphabetical order sounds good.

**Comment by sapics** [comment]
Thank you for your approval!

**Pull request merged**
