### PR TITLE
Teachers: Version 1.001 added

### PR DESCRIPTION
**Pull request by emmamarichal**
844e425: [gftools-packager] Teachers: Version 1.001 added

* Teachers Version 1.001 taken from the upstream repo https://github.com/chankfonts/Teachers-fonts at commit https://github.com/chankfonts/Teachers-fonts/commit/f903bca18f4ecb61ee43f6a33e30a91e21449836.

 05a39dd: description

Email sent to the author for:
- [x] tags
- [x] designer profile
- [x] images

### CODE REVIEW

**Comment by emmamarichal** [comment]
@m4rc1e I have a subset `greek-ext`, it still a mistake, since we have no greek here. I let it in the metadata.pb if you want to take a look. You can remove it during the review

**Comment by m4rc1e** [comment]
Family needs tags.

**Comment by m4rc1e** [comment]
Apart from tags, this family look amazing! Like a friendlier Futura. Will merge once we get tags.

**Comment by emmamarichal** [comment]
I sent a email to the designer this morning, I'll let you know! :)

**Comment by emmamarichal** [comment]
@m4rc1e tags have been added! I'll add the designer profile today. I think you can merge :)

**Pull request merged**
