### PR TITLE
Readex Pro: Version 1.204 added

### LINKED ISSUE #3734: Upgrade Readex Pro with hyper expansion axis
upstream: https://github.com/ThomasJockin/readexpro

### PR DESCRIPTION
**Pull request by RosaWagner**
5028986: [gftools-packager] Readex Pro: Version 1.204 added

* Readex Pro Version 1.204 taken from the upstream repo https://github.com/ThomasJockin/readexpro at commit https://github.com/ThomasJockin/readexpro/commit/6a4f24e40e424ec77badb04c101af81da96ed157.

Closes #3734

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Relies on HEXP (hyper expansion) axis merged in https://github.com/googlefonts/axisregistry/pull/79

**Comment by vv-monsalve** [comment]
> Relies on HEXP (hyper expansion) axis registration merged in [googlefonts/axisregistry#79](https://github.com/googlefonts/axisregistry/pull/79)

From the guideline _the axis must reach sandbox one week before the font does_, should this PR still wait to be merged?

**Comment by chrissimpkins** [comment]
Yes please.  Thanks!

**Comment by chrissimpkins** [comment]
Pushed to sandbox and removed from the to_sandbox list today d0253df25eac810af5a0a11975d2224fcd5944b4

**Comment by chrissimpkins** [comment]
Added to the to_production list in https://github.com/google/fonts/pull/5678

**Pull request merged**
