### PR TITLE
Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
1052af0: [gftools-packager] Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

* Castoro Version 1.19 Build 011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/TiroTypeworks/Castoro.git at commit https://github.com/TiroTypeworks/Castoro/commit/2357a7ddd73a225e095b8a7279017fe4b7ca4312.

 6c921c0: [gftools-packager] ofl/castoro remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Updated

## Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

---
 f5a2f5f: [gftools-packager] Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

* Castoro Version 1.19 Build 011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/TiroTypeworks/Castoro.git at commit https://github.com/TiroTypeworks/Castoro/commit/2c0ec31eb4906494828688c9053fa6667230b81a.

 9521b00: [gftools-packager] ofl/castoro remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
Updated

## Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

---
 3b1791f: [gftools-packager] Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

* Castoro Version 1.19 Build 011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/TiroTypeworks/Castoro.git at commit https://github.com/TiroTypeworks/Castoro/commit/56da70fd9f66423bfa212118289a440f3bc1756f.

 7996425: [gftools-packager] ofl/castoro remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
Updated

## Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

---
 3ec0a9f: [gftools-packager] Castoro: Version 1.19 Build 011; ttfautohint (v1.8.3) added

* Castoro Version 1.19 Build 011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/TiroTypeworks/Castoro.git at commit https://github.com/TiroTypeworks/Castoro/commit/56da70fd9f66423bfa212118289a440f3bc1756f.

 4771a71: [gftools-packager] ofl/castoro remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
@vv-monsalve, what do you think about the v-metric warn? I don't know if we should ignore it, it would be difficult to fix after publishing the font.

**Comment by vv-monsalve** [comment]
> @vv-monsalve, what do you think about the v-metric warn? I don't know if we should ignore it, it would be difficult to fix after publishing the font.

@RosaWagner Thanks, it was discussed and agreed here https://github.com/TiroTypeworks/Castoro/issues/7#issuecomment-678170815

**Pull request merged**
