### PR TITLE
Update khmer_unique-glyphs.nam

### PR DESCRIPTION
**Pull request by davelab6**
* Adding 0x17DD for Bunong language (CMO, Cambodia, Khmer script) requested by Diethelm Kanjahn at SIL

### CODE REVIEW

**Comment by rsheeter** [comment]
Expected to just see addition of one codepoint but files changed is also showing me removal of a bunch (basically latin; 1 addition and 99 deletions.). I don't think we want to merge as-is.

**Comment by davelab6** [comment]
The other name files don't have latin glyphs; eg https://github.com/google/fonts/blob/master/tools/encodings/greek_unique-glyphs.nam

**Comment by rsheeter** [comment]
That is currently intentional (and odd). We could explore changing it but
doing it separate of adding the new codepoint would be best.

**Comment by davelab6** [comment]
Okay I rebased so that 2nd commit is gone :)

**Comment by rsheeter** [comment]
LGTM.

**Pull request merged**
