### PR TITLE
Fix broken merge of ebgaramond METADATA

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Comment by m4rc1e** [comment]
I'm going to rebreak this to see if FATALs make it all the way through,

**Comment by vv-monsalve** [comment]
I've re-run the jobs now to see it

**Comment by simoncozens** [comment]
Sadly fontbakery isn't running in this PR for some reason...

**Comment by m4rc1e** [comment]
> Sadly fontbakery isn't running in this PR for some reason...

I reckon this happened because I basically did a revert so the ci didn't run because it didn't find any changed files. Anyways, I've just done a new modification that I can see is broken locally. Let's see what happens.

**Comment by m4rc1e** [comment]
Sweet! The FATALs have now been picked up so the PR fails.

**Pull request merged**
