### PR TITLE
Add repository_url where implied by archive

### PR DESCRIPTION
**Pull request by rsheeter**
Add repo_url where missing and implied by archive as suggested in https://github.com/google/fonts/issues/4773#issuecomment-1328101047.

Changes generated by https://github.com/rsheeter/google_fonts_sources/blob/main/add_missing_repo_urls.py.

### CODE REVIEW

**Review by m4rc1e — COMMENTED** [review]
I think the majority of these urls already exist in the METADATA.pb files e.g

https://github.com/google/fonts/blob/main/ofl/abyssinicasil/METADATA.pb#L20
https://github.com/google/fonts/blob/main/ofl/alkalami/METADATA.pb#L20
https://github.com/google/fonts/blob/main/ofl/andika/METADATA.pb#L49
...

**Comment by rsheeter** [comment]
> I think the majority of these urls already exist in the METADATA.pb files e.g

They _should_ be in upstream though? - I was told that's how you are supposed to find sources. Or is upstream.yaml deprecated?

**Comment by m4rc1e** [comment]
The upstream.yaml file isn't deprecated, it just holds metadata which isn't in the METADATA.pb file. The gftools packager will use both the METADATA.pb file and the upstream.yaml file. Personally, it would be nice if the fields in the upstream.yaml were added to the METADATA.pb file. It feels a bit strange having both files.

Do we have a one pages floating around for including sources instead of binaries in google/fonts? I'm curious.

**Comment by rsheeter** [comment]
> The upstream.yaml file isn't deprecated, it just holds metadata which isn't in the METADATA.pb file

That's a bit of a nuisance to work with. Why do we need two files? Why don't we delete upstream.yaml and put *everything* into metadata?

**Comment by rsheeter** [comment]
> it would be nice if the fields in the upstream.yaml were added to the METADATA.pb file

+1, lets make it happen. What is the authoritative list of fields an upstream.yaml can contain?

**Comment by m4rc1e** [comment]
Here's the packager's yaml template: https://github.com/googlefonts/gftools/blob/main/Lib/gftools/template.upstream.yaml

Since the METADATA proto already includes repo urls and archive urls, I think we only need to include the files field.

**Comment by rsheeter** [comment]
Closing PR since deleting upstream.yaml appears to be the preferred outcome.

**Comment by rsheeter** [comment]
I believe I have added the fields in https://github.com/googlefonts/gftools/pull/639. Will anything break if I migrate the yaml content over?

**Comment by m4rc1e** [comment]
> Will anything break if I migrate the yaml content over?

I'll take a look. We may need to update the packager which I'll do for you.

**Pull request closed without merging**
