### PR TITLE
Noto Naskh Arabic UI: v2.015 added

### PR DESCRIPTION
**Pull request by chrissimpkins**
Supersedes #5019 

Includes a production v2.001 VF binary edit to fix the Persian/Urdu figures U+06F4, U+06F6, U+06F7 localization substitutions across Farsi and Urdu locales.  Addresses the issue described in https://github.com/notofonts/arabic/issues/27

The full ttx diff between the edited file added here and the current production v2.001 file is:

```diff
--- NotoNaskhArabicUI[wght]-production.ttf      2022-08-03T19:19:51.783671-04:00
+++ NotoNaskhArabicUI[wght].ttf 2022-08-04T08:18:31.198928-04:00
@@ -1600,23 +1600,23 @@
     <GlyphID id="1594" name="_1033"/>
     <GlyphID id="1595" name="_1040"/>
     <GlyphID id="1596" name="_1023"/>
   </GlyphOrder>

   <head>
     <!-- Most of this table will be recalculated by the compiler -->
     <tableVersion value="1.0"/>
-    <fontRevision value="2.001"/>
-    <checkSumAdjustment value="0xf399853e"/>
+    <fontRevision value="2.015"/>
+    <checkSumAdjustment value="0xcb285334"/>
     <magicNumber value="0x5f0f3cf5"/>
     <flags value="00000000 00000011"/>
     <unitsPerEm value="1000"/>
     <created value="Tue Nov  3 01:40:58 2020"/>
-    <modified value="Tue Nov 10 04:07:34 2020"/>
+    <modified value="Thu Aug  4 12:17:43 2022"/>
     <xMin value="-249"/>
     <yMin value="-419"/>
     <xMax value="2148"/>
     <yMax value="1191"/>
     <macStyle value="00000000 00000000"/>
     <lowestRecPPEM value="6"/>
     <fontDirectionHint value="2"/>
     <indexToLocFormat value="0"/>
@@ -1654,17 +1654,17 @@
     <maxZones value="1"/>
     <maxTwilightPoints value="0"/>
     <maxStorage value="0"/>
     <maxFunctionDefs value="0"/>
     <maxInstructionDefs value="0"/>
     <maxStackElements value="0"/>
     <maxSizeOfInstructions value="0"/>
     <maxComponentElements value="8"/>
-    <maxComponentDepth value="7"/>
+    <maxComponentDepth value="3"/>
   </maxp>

   <OS_2>
     <!-- The fields 'usFirstCharIndex' and 'usLastCharIndex'
          will be recalculated by the compiler -->
     <version value="4"/>
     <xAvgCharWidth value="736"/>
     <usWeightClass value="400"/>
@@ -30551,23 +30551,23 @@
     </namerecord>
     <namerecord nameID="1" platformID="3" platEncID="1" langID="0x409">
       Noto Naskh Arabic UI
     </namerecord>
     <namerecord nameID="2" platformID="3" platEncID="1" langID="0x409">
       Regular
     </namerecord>
     <namerecord nameID="3" platformID="3" platEncID="1" langID="0x409">
-      2.001;GOOG;NotoNaskhArabicUI-Regular
+      2.015;GOOG;NotoNaskhArabicUI-Regular
     </namerecord>
     <namerecord nameID="4" platformID="3" platEncID="1" langID="0x409">
       Noto Naskh Arabic UI Regular
     </namerecord>
     <namerecord nameID="5" platformID="3" platEncID="1" langID="0x409">
-      2.001
+      2.015
     </namerecord>
     <namerecord nameID="6" platformID="3" platEncID="1" langID="0x409">
       NotoNaskhArabicUI-Regular
     </namerecord>
     <namerecord nameID="7" platformID="3" platEncID="1" langID="0x409">
       Noto is a trademark of Google LLC.
     </namerecord>
     <namerecord nameID="8" platformID="3" platEncID="1" langID="0x409">
@@ -79372,18 +79372,21 @@
       </Lookup>
       <Lookup index="21">
         <LookupType value="1"/>
         <LookupFlag value="0"/>
         <!-- SubTableCount=1 -->
         <SingleSubst index="0">
           <Substitution in="uni00AB" out="uni00AB.locl"/>
           <Substitution in="uni00BB" out="uni00BB.locl"/>
+          <Substitution in="uni0666" out="uni06F6"/>
           <Substitution in="uni066B" out="uni066B.locl"/>
           <Substitution in="uni066C" out="uni066B.1"/>
+          <Substitution in="uni06F4.locl" out="uni06F4"/>
+          <Substitution in="uni06F7.locl" out="uni06F7"/>
         </SingleSubst>
       </Lookup>
       <Lookup index="22">
         <LookupType value="1"/>
         <LookupFlag value="0"/>
         <!-- SubTableCount=1 -->
         <SingleSubst index="0">
           <Substitution in="uni0660" out="uni0660.4"/>
```

I can confirm the fix in Font Goggles:

persianurdu-nnaui

A zip archive with the full set of ttx and ttf binaries for this fix are attached below:

[NNA_UI.zip](https://github.com/google/fonts/files/9259633/NNA_UI.zip)

### CODE REVIEW

**Comment by m4rc1e** [comment]
@chrissimpkins I think Simon fixed this issue a few days ago, https://github.com/notofonts/arabic/commit/454d5adb842d60562543ddae8fefbc230a44f0e3. Wouldn't it be better to just use this source file instead of hot fixing the binary? 

I've been looking at this PR with Viv and we've encountered some inconsistencies. We'll chat about them in the meeting coming up since we're not 100% sure of the changes.

**Comment by chrissimpkins** [comment]
> @chrissimpkins I think Simon fixed this issue a few days ago, [notofonts/arabic@454d5ad](https://github.com/notofonts/arabic/commit/454d5adb842d60562543ddae8fefbc230a44f0e3). Wouldn't it be better to just use this source file instead of hot fixing the binary?

We're looking for a min diff against the prod v2.001 binary that only includes the fix requested by this team.  Simon's builds add the full Latin script and Viv identified a large number of Arabic mark shaping regressions.  This is blocking a product launch and I am trying to land this fix soon (ideally today).  If someone is able to locate v2.001 source state, fix `locl` for Urdu/Persian on the figures addressed here, review, and merge today that sounds very good to me.  We won't have time to work through Arabic shaping regression work in advance of this push.

> I've been looking at this PR with Viv and we've encountered some inconsistencies. We'll chat about them in the meeting coming up since we're not 100% sure of the changes.

Sure, sg

**Comment by chrissimpkins** [comment]
cc @simoncozens let’s chat about how we approached this and how it impacts you when you are available

**Comment by vv-monsalve** [comment]
Not meant to reach prod.

**Pull request merged**
