### PR TITLE
El-Messiri: v2.009 added.

### PR DESCRIPTION
**Pull request by eliheuer**
Taken from the upstream repo https://github.com/eliheuer/El-Messiri/tree/eli-gf-mastering
at commit https://github.com/eliheuer/El-Messiri/commit/594bf64681e900985e93ee2300bcadc1ac84508d

### CODE REVIEW

**Comment by m4rc1e** [comment]
ping @eliheuer

**Comment by m4rc1e** [comment]
@eliheuer let us leave Lemonada for the time being and focus on this.

**Comment by m4rc1e** [comment]
LGTM

**Comment by m4rc1e** [comment]
Can you send a pr to Gaber's upstream please? once that's done we'll merge this.

**Comment by eliheuer** [comment]
Sure, I already made a upstream PR that was merged: https://github.com/Gue3bara/El-Messiri/pull/18

**Comment by thlinard** [comment]
Why was it never in production? This VF certainly has issues, but...

**Comment by eliheuer** [comment]
I can still look into this and try to move it forward, It needs a gftools builder build script update anyway...

**Comment by thlinard** [comment]
@eliheuer For the issues (STAT table, mostly), `gftools gen-stat` could help.

**Pull request merged**
