### PR TITLE
montserrat: v4.000 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Been testing this over the weekend. Can confirm @JulietaUla @kalapi @graphicore have done a sterling job. Source [repo](https://github.com/JulietaUla/Montserrat) is solid as well, all forks have been merged back.

Mac OS X Safari:
screen shot 2016-11-14 at 09 41 48

Win7 Chrome:
screen shot 2016-11-14 at 10 01 49

I'll pr the Alternates now as well.

Can we get a +1 from the +1 crew as well please?

Cheers,
Marc

### CODE REVIEW

**Comment by m4rc1e** [comment]
@davelab6 hold off PRing this till we have an answer for [this](https://github.com/JulietaUla/Montserrat/issues/22)

**Comment by m4rc1e** [comment]
Montserrat is being updated. Keep this open.

**Comment by m4rc1e** [comment]
This issue needs resolving https://github.com/JulietaUla/Montserrat/issues/25 before we can merge this.

**Comment by davelab6** [comment]
Okay sure

**Pull request closed without merging**
