### PR TITLE
Noto Sans Adlam Unjoined: Version 3.002 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/adlam at commit https://github.com/notofonts/adlam/commit/430ceaeb57254439626f14319cd228e0bc0945aa.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
Updated

**Comment by simoncozens** [comment]
There's a sample text issue here; the missing glyph is ARABIC COMMA, but this is no longer the correct glyph for Adlam.

> the comma and semicolon are ⹁U+2E41 REVERSED COMMA and ⁏U+204F REVERSED SEMICOLON, respectively, rather than the Arabic comma and semicolon. (The Arabic comma/semicolon are only used as carryovers from the older Adlam fonts.)[8](https://r12a.github.io/scripts/adlm/fuf.html#refs)

(https://r12a.github.io/scripts/adlm/fuf.html)

**Comment by vv-monsalve** [comment]
> There's a sample text issue here; the missing glyph is ARABIC COMMA, but this is no longer the correct glyph for Adlam.

Should the language textproto be updated?

> Font can't render "fuf_Adlm" sample text:
"𞤋𞤲𞥆𞤢𞤥𞤢 𞤢𞥄𞤣𞤫𞥅𞤶𞤭 𞤬𞤮𞤬 𞤨𞤮𞤼𞤭، 𞤲'𞤣𞤭𞤥𞤯𞤭𞤣𞤭 𞤫 𞤶𞤭𞤦𞤭𞤲𞤢𞤲𞥆𞤣𞤫 𞤼𞤮 𞤦𞤢𞤲𞥆𞤺𞤫 𞤸𞤢𞤳𞥆𞤫𞥅𞤶𞤭. 𞤉𞤩𞤫" >

Please review this Fail. I've used that string in the diffenator text html proof and it seems it works on rendering it, but the font is showing a couple of tofu. 

Also, please also confirm on the changes for Adlam.

noto-sans-adlam-ba

<br>

> 🔥 FAIL Shapes languages in all GF glyphsets.
> nl_Latn (Dutch) | Shaper didn't attach acutecomb to J

Please review this.

<br>

> 🔥 FAIL Combined length of family and style must not exceed 32 characters.

I'll go back about the name length Fail

**Comment by vv-monsalve** [comment]
> Please review this Fail. I've used that string in the diffenator text html proof and it seems it works on rendering it, but the font is showing a couple of tofu.

Per your comment on Imperial Aramaic, we'll ignore the `Eng` and `eng` tofu. Only the one shown on Adlam needs attention.

**Comment by simoncozens** [comment]
Something very bad has happened with mark positioning here.

**Comment by simoncozens** [comment]
Updated

**Comment by simoncozens** [comment]
The sample text check FAIL is also to do with the bad sample text (Arabic comma). The nl_Latn fail is to fine, we do not expect full Latin shaping in Noto fonts. Latin Core is just in there to avoid tofu.

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
LGTM. However, the description file was deleted after the last update :,)
Please reinstate it.

**Review by vv-monsalve — APPROVED** [review]

**Pull request merged**
