### PR TITLE
Average: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
e2ba9fb: [gftools-packager] Average: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

* Average Version 1.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/etunni/average at commit https://github.com/etunni/average/commit/6388db3a611d1d489a19a5511a90bb426bd2bae4.

 edf6537: Description updated according the update

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal some ligatures are reported as missing

glyphs_missing

**Comment by vv-monsalve** [comment]
Other than that LGTM.

**Comment by emmamarichal** [comment]
@vv-monsalve I think it's because I renamed them correctly (example: fh -> f_h), and in the features, they are now classified in liga and dlig (whereas before, they were only in liga). 
Did I do it right or should I have left it as before?

**Comment by RosaWagner** [comment]
@emmamarichal if they were only in liga before, they need to stay in liga with the update

**Comment by emmamarichal** [comment]
Updated

## Average: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

---
 941754f: [gftools-packager] Average: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

* Average Version 1.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/etunni/average at commit https://github.com/etunni/average/commit/6583341221fb0625ba1b9c3ee2a7490d57df951f.

 3c89805: Description updated

**Pull request merged**
