### PR TITLE
Climate Crisis: Version 1.003 added

### PR DESCRIPTION
**Pull request by RosaWagner**
c16048e: [gftools-packager] Climate Crisis: Version 1.003 added

* Climate Crisis Version 1.003 taken from the upstream repo https://github.com/dancoull/ClimateCrisis at commit https://github.com/dancoull/ClimateCrisis/commit/e0398e2d7e84a9f08cf7ec67bb463e4e2bb35431.

 f1c4b53: Climate Crisis: added description

 ea955ec: Climate Crisis: added registry default override

### CODE REVIEW

**Comment by RosaWagner** [comment]
Waiting for #5333 to hit prod before merging this.

**Comment by chrissimpkins** [comment]
Ready to move to sandbox

**Comment by chrissimpkins** [comment]
Added to the to_sandbox list in https://github.com/google/fonts/pull/5658

**Comment by chrissimpkins** [comment]
The download zip archive issue is fixed.  I removed the blocked label.

**Pull request merged**
