### PR TITLE
oswald: v4.101 vf added

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/googlefonts/OswaldFont at commit https://github.com/googlefonts/OswaldFont/pull/12/commits/6c80ad8d6fcc42141d00e3b97d0175e54e9ee5a8

@davelab6 lets not merge this until the diffs are genned

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.6.4

<details>
<summary><b>[8] Oswald-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/001](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :fire: **FAIL** Style name used in "/Users/marcfoley/Type/fonts/ofl/oswald/Oswald-Regular.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

</details>
<details>
<summary>:fire: <b>FAIL:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/056](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :fire: **FAIL** Failed to parse ttfautohint version values: installed = '1.8.2'; used_in_font = '1.8.1.43-b0c9' [code: parse-error]

</details>
<details>
<summary>:warning: <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/018](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** OS/2 VendorID value 'newt' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>:warning: <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/116](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will liely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>:warning: <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/118](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** Following glyphs differ greatly from Google Fonts version: [uni20BC, lira, emptyset, uni0463, brevecombcy, uni0402, gcircumflex, uni045B, uni20B9, Tbar, uni0492, g, uni20A6, uni01E5, uni04A2, uni2113, Oslash, gbreve, U1C87, uni20AD, Oslashacute, oslashacute, uni049A, uni01F5, uni04E8, uni20B1, uni046A, uni20BA, oslash, uni20A9, gcaron, colonmonetary, gdotaccent, franc, uni2116, uni0496, uni0452, uni04E9]

</details>
<details>
<summary>:warning: <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/153](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: g	Contours detected: 4	Expected: 2 or 3
Glyph name: lira	Contours detected: 3	Expected: 1
Glyph name: uni20AD	Contours detected: 3	Expected: 1
Glyph name: uni20AE	Contours detected: 3	Expected: 1
Glyph name: uni20B5	Contours detected: 3	Expected: 1 or 2
Glyph name: uni20B4	Contours detected: 3	Expected: 1 or 2
Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: eogonek	Contours detected: 3	Expected: 2
Glyph name: gcircumflex	Contours detected: 5	Expected: 3 or 4
Glyph name: gbreve	Contours detected: 5	Expected: 3 or 4
Glyph name: gdotaccent	Contours detected: 5	Expected: 3 or 4
Glyph name: uni0123	Contours detected: 5	Expected: 3 or 4
Glyph name: Tbar	Contours detected: 2	Expected: 1
Glyph name: tbar	Contours detected: 2	Expected: 1
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: ohorn	Contours detected: 3	Expected: 2
Glyph name: Uhorn	Contours detected: 2	Expected: 1
Glyph name: uhorn	Contours detected: 2	Expected: 1
Glyph name: uni01E4	Contours detected: 2	Expected: 1
Glyph name: uni01E5	Contours detected: 4	Expected: 2
Glyph name: gcaron	Contours detected: 5	Expected: 3 or 4
Glyph name: uni01EA	Contours detected: 3	Expected: 2
Glyph name: uni01EB	Contours detected: 3	Expected: 2
Glyph name: uni01F5	Contours detected: 5	Expected: 3
Glyph name: uni0452	Contours detected: 2	Expected: 1
Glyph name: uni045B	Contours detected: 2	Expected: 1
Glyph name: uni0462	Contours detected: 3	Expected: 2
Glyph name: uni0463	Contours detected: 3	Expected: 2
Glyph name: uni046A	Contours detected: 3	Expected: 2
Glyph name: uni046B	Contours detected: 3	Expected: 2
Glyph name: uni048C	Contours detected: 3	Expected: 2
Glyph name: uni048D	Contours detected: 3	Expected: 2
Glyph name: uni048E	Contours detected: 3	Expected: 1 or 2
Glyph name: uni048F	Contours detected: 3	Expected: 2
Glyph name: uni0492	Contours detected: 2	Expected: 1
Glyph name: uni0493	Contours detected: 2	Expected: 1
Glyph name: uni0496	Contours detected: 3	Expected: 1 or 2
Glyph name: uni049A	Contours detected: 3	Expected: 1 or 2
Glyph name: uni049C	Contours detected: 2	Expected: 1
Glyph name: uni049D	Contours detected: 2	Expected: 1
Glyph name: uni049E	Contours detected: 2	Expected: 1
Glyph name: uni04A0	Contours detected: 2	Expected: 1
Glyph name: uni04A1	Contours detected: 2	Expected: 1
Glyph name: uni04A2	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04A4	Contours detected: 2	Expected: 1
Glyph name: uni04A8	Contours detected: 1	Expected: 2
Glyph name: uni04A9	Contours detected: 1	Expected: 2
Glyph name: uni04AC	Contours detected: 3	Expected: 1 or 2
Glyph name: Ustraitstrokecy	Contours detected: 2	Expected: 1
Glyph name: ustraitstrokecy	Contours detected: 2	Expected: 1
Glyph name: uni04B2	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04B6	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04B8	Contours detected: 2	Expected: 1
Glyph name: uni04B9	Contours detected: 2	Expected: 1
Glyph name: uni04BC	Contours detected: 3	Expected: 2
Glyph name: uni04BD	Contours detected: 3	Expected: 2
Glyph name: uni04BE	Contours detected: 6	Expected: 2 or 3
Glyph name: uni04BF	Contours detected: 6	Expected: 2 or 3
Glyph name: uni04CB	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04F6	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04FE	Contours detected: 2	Expected: 1
Glyph name: uni04FF	Contours detected: 2	Expected: 1
Glyph name: uni0524	Contours detected: 3	Expected: 1
Glyph name: uni0525	Contours detected: 2	Expected: 1
Glyph name: uni0526	Contours detected: 3	Expected: 1
Glyph name: uni0527	Contours detected: 2	Expected: 1
Glyph name: uni052E	Contours detected: 3	Expected: 1
Glyph name: uni052F	Contours detected: 2	Expected: 1
Glyph name: uni2113	Contours detected: 1	Expected: 2
Glyph name: uni1EDB	Contours detected: 4	Expected: 3
Glyph name: uni1EDD	Contours detected: 4	Expected: 3
Glyph name: uni1EDF	Contours detected: 4	Expected: 3
Glyph name: uni1EE1	Contours detected: 4	Expected: 3
Glyph name: uni1EE3	Contours detected: 4	Expected: 3
Glyph name: uni1EE8	Contours detected: 3	Expected: 2
Glyph name: uni1EE9	Contours detected: 3	Expected: 2
Glyph name: uni1EEA	Contours detected: 3	Expected: 2
Glyph name: uni1EEB	Contours detected: 3	Expected: 2
Glyph name: uni1EEC	Contours detected: 3	Expected: 2
Glyph name: uni1EED	Contours detected: 3	Expected: 2
Glyph name: uni1EEE	Contours detected: 3	Expected: 2
Glyph name: uni1EEF	Contours detected: 3	Expected: 2
Glyph name: uni1EF0	Contours detected: 3	Expected: 2
Glyph name: uni1EF1	Contours detected: 3	Expected: 2
Glyph name: uni20B9	Contours detected: 2	Expected: 1
Glyph name: uni20BA	Contours detected: 3	Expected: 1
Glyph name: uni20BC	Contours detected: 2	Expected: 1
Glyph name: uni20BD	Contours detected: 3	Expected: 2

</details>
<details>
<summary>:warning: <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/065](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<details>
<summary>:warning: <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/064](https://github.com/googlefonts/fontbakery/search?q={checkid})
* :warning: **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 6 | 11 | 7 | 112 |
| 0% | 1% | 4% | 8% | 5% | 81% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Comment by m4rc1e** [comment]
desktop_windows_10_chrome_69 0_
*Win 10 Chrome 69*

@davelab6 there are no major x-height or cap height jumps. Rendering overall is better than Comfortaa.

glyphs_modified
Only major change is to Numero

**Comment by thlinard** [comment]
Is it finally the new policy to give the same name to static and variable versions? This is very annoying when someone can't adopt the same practice of subfolders as you do.

**Comment by m4rc1e** [comment]
@thlinard Nope, this is just temporary. Apologies for the annoyance but naming them is harder than it seems.

**Comment by davelab6** [comment]
> Apologies for the annoyance but naming them is harder than it seems.

I filed #1817 to discuss this; merging as-is for now

**Comment by davelab6** [comment]
> `+121 KB (230%) ofl/oswald/Oswald-Regular.ttf`

Not too shabby :)

**Pull request merged**
