### PR TITLE
Noto Sans Symbols 2: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
3898ef3: [gftools-packager] Noto Sans Symbols 2: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Symbols 2 Version 2.006; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/symbols.git at commit https://github.com/notofonts/symbols/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
Expected changes:

* Adds support for Kaktovik Numerals (thanks to Kevin King)
* Improves the spacing of tau-rho 
* Raises the baseline of some transport glyphs 
* Uses components and rotation to make fleurons consistent 
* Fixes the heraldic hatching of orange circle/square 
* Adjusts the anchor on the Coptic epact thousands mark 
* Improves the design of the Mahjongg circles suit 
* Fixes an issue where the rotated pawn was not rotated

**Review by m4rc1e — COMMENTED** [review]
Thanks for pointing out what has changed.

Btw, the LGC weight was Thin, it's now Regular. Is this ok?

**Comment by simoncozens** [comment]
Yep, all expected. (See release notes above.)

**Comment by simoncozens** [comment]
(see https://github.com/notofonts/symbols/issues/65)

**Review by m4rc1e — APPROVED** [review]

**Comment by RosaWagner** [comment]
@simoncozens the sample text here was removed.

**Pull request merged**
