### PR TITLE
Noto Serif Tamil: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
8d42bad: [gftools-packager] Noto Serif Tamil: Version 2.003 added

* Noto Serif Tamil Version 2.003 taken from the upstream repo https://github.com/notofonts/tamil.git at commit https://github.com/notofonts/tamil/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
> 🔥 FAIL: The variable font 'wght' (Weight) axis coordinate must be 400 on the 'Regular' instance. ([com.google.fonts/check/varfont/regular_wght_coord](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/regular_wght_coord))
> 🔥 FAIL: The variable font 'wdth' (Width) axis coordinate must be 100 on the 'Regular' instance. ([com.google.fonts/check/varfont/regular_wdth_coord](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/regular_wdth_coord))
> 🔥 FAIL: The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance. ([com.google.fonts/check/varfont/bold_wght_coord](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/bold_wght_coord))

I don't understand these fails. I think the instances are correct:

```
    <!-- Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="348">
      <coord axis="wght" value="400.0"/>
      <coord axis="wdth" value="100.0"/>
    </NamedInstance>

    <!-- Bold Italic -->
    <NamedInstance flags="0x0" subfamilyNameID="351">
      <coord axis="wght" value="700.0"/>
      <coord axis="wdth" value="100.0"/>
    </NamedInstance>
```

STAT table:

```
      <AxisValue index="7" Format="3">
        <AxisIndex value="1"/>
        <Flags value="2"/>  <!-- ElidableAxisValueName -->
        <ValueNameID value="338"/>  <!-- Regular -->
        <Value value="400.0"/>
        <LinkedValue value="700.0"/>
      </AxisValue>
      <AxisValue index="10" Format="1">
        <AxisIndex value="1"/>
        <Flags value="0"/>
        <ValueNameID value="341"/>  <!-- Bold -->
        <Value value="700.0"/>
      </AxisValue>
```

**Comment by vv-monsalve** [comment]
I'll need to inspect this in detail later. This is one of the diff images
Desktop_Windows_10_chrome_71 0_

**Comment by vv-monsalve** [comment]
@RosaWagner, from what has been reported in [fontbakery#3818](https://github.com/googlefonts/fontbakery/issues/3818) I think this one could be merged. Could you confirm?

**Comment by simoncozens** [comment]
Needs article.

**Comment by vv-monsalve** [comment]
> Looks like the diffenator is picking up the wrong before font. (I hope that's what it is, anyway.) Manually choosing the fonts seems to work OK.

I've run some local test and I can confirm that running local test this doesn't happen, but it's still happening from the GHA-CI package. What could be the situation here @m4rc1e?

So, below is the image of kerns missing reported on `qa` package, while the local test reported none

kerns_missing

**Comment by vv-monsalve** [comment]
> DiffBrowsers images from local test. Reflow spotted in Safari is for `Light` weight is not happening in recent versions, it looks more as a browserstack issue. Don't know if we should confirm.

After accessing to Live preview in BrowserStack I can confirm it is working well in Safari (11 and recent versions).

**Pull request merged**
