### PR TITLE
Noto Sans Yi: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
74ce6f3: [gftools-packager] Noto Sans Yi: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Yi Version 2.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/yi.git at commit https://github.com/notofonts/yi/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))

This warn could be easily avoided.

---

🔥 FAIL: Check samples can be rendered.
🔥 FAIL Font can't render "ii_Yiii" sample text:

This is the current status of the font in the type tester:

Capture d’écran 2022-09-15 à 13 36 32

Looks like `comma.full` is missing, or the sample text should be updated to not display that character.

**Comment by simoncozens** [comment]
Seems like Yi uses both kinds of comma. So we need to fix the font and the nam files, to support U+FF0C, but the sample text is ok.

**Comment by simoncozens** [comment]
New version of the font with those glyphs incoming, subset fix PR at https://github.com/googlefonts/glyphsets/pull/73.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Yi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

---
 4084ccd: [gftools-packager] Noto Sans Yi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Yi Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/yi.git at commit https://github.com/notofonts/yi/commit/.

**Pull request merged**
