### PR TITLE
ofl/lora: ttfautohinted. v2.102 added.

### PR DESCRIPTION
**Pull request by laerm0**
A quick ttfautohint updated the hints on these for modern renderers. v2.102 added. Fixes https://github.com/cyrealtype/Lora-Cyrillic/issues/11

(I didn't want to put these into Lora's repo because I didn't know if @alexeiva wanted this as a fix for him or if it was just for Google Fonts.)

### CODE REVIEW

**Comment by alexeiva** [comment]
Thank you @laerm0, I am merging this. If you used custom ttfautohinting parameters here, can you post them so that I can include them in the source .glyphs files.

**Comment by alexeiva** [comment]
@laerm0 please make a new PR for this, as I messed this up.

**Comment by laerm0** [comment]
The parameters were `-w GD`.

I don't know how to PR again as it says my fork matches... What should I do?

**Comment by alexeiva** [comment]
> I don't know how to PR again as it says my fork matches... What should I do?

I've reopened your PR here: https://github.com/google/fonts/pull/1403

These options aren't default in Glyphs App. I inherited them in the sources:
screen shot 2017-12-22 at 10 58 32 am

In Glyphs by default GDI is half-checked, and no DW:

screen shot 2017-12-22 at 10 57 28 am

**Pull request merged**
