### PR TITLE
Noto Sans Elymaic: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
9045def: [gftools-packager] Noto Sans Elymaic: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Elymaic Version 1.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/elymaic.git at commit https://github.com/notofonts/elymaic/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
> 🔥 FAIL: Check hhea.caretSlopeRise and hhea.caretSlopeRun ([com.google.fonts/check/caret_slope](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/hhea.html#com.google.fonts/check/caret_slope))
🔥 FAIL hhea.caretSlopeRise and hhea.caretSlopeRun do not match with post.italicAngle.
Got: caretSlopeRise 1000 and caretSlopeRun 87
Expected: caretSlopeRise 1 and caretSlopeRun 0 [code: caretslope-mismatch]

@simoncozens current caret slope is indeed strange for italicAngle=0

**Comment by simoncozens** [comment]
Something is weird about this, this should be an italic font; export style name is "Italic", but instance name is Regular in the designspace (that's one problem). The other problem is that the italicAngle is set to -5 in the UFO, but it got lost in the TTF. I think we need a new release.

**Comment by RosaWagner** [comment]
Okay, since it's one style, better for it to be Regular with italic angle=0

**Comment by simoncozens** [comment]
Updated

## Noto Sans Elymaic: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added

---
 56d94ef: [gftools-packager] Noto Sans Elymaic: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Elymaic Version 1.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/elymaic.git at commit https://github.com/notofonts/elymaic/commit/.

**Comment by simoncozens** [comment]
```
This releases:

* Adds a new stylistic set for an allograph found at Tang-i Butan (#3)
* Removes the erroneous yodh/zayin ligature (#1)
* Clarifies the name of stylistic sets (#3)
```

I'm not worried about the dotted circle for this font.

**Pull request merged**
