### PR TITLE
rebuild all metadata with gftools add-font to add `ext` subsets where needed

### PR DESCRIPTION
**Pull request by thundernixon**
Work-in-progress PR to resolve https://github.com/google/fonts/issues/187

This uses a slightly-modified version of `gftools-add-font.py` to apply `ext` subset labels where even a single glyph from an `ext` glyph set is present.

Simplified logs of git diffs (removing some of the noise) are available at https://github.com/thundernixon/fix-gf-metadata/tree/master/docs. However, these aren't necessarily a huge improvement on what GitHub shows below, in part because they lack color.

I've written about changes [in these notes](https://github.com/thundernixon/fix-gf-metadata/blob/master/docs/2019-02-22-metadata-diffs.md), but I'll summarize this more concisely here.

### Known issues with the first version of this PR:

- `korean` subsets are dropped due to lack of cp/`.nam` file ([comment in issue gftools issue 92](https://github.com/googlefonts/gftools/issues/92#issuecomment-467132144))
- CamelCased font names are given unwanted spaces (https://github.com/googlefonts/gftools/issues/122)
  - (probably related: "PT Serif" and "PT Serif Caption" become simply "Web")

### Possible/probable issues:

- Other subsets (besides `korean`) are dropped – notably:
  - `chinese-simplified` removed from 3 fonts
  - `devanagari` removed from 7 fonts
  - `greek` removed from 5 fonts
  - `arabic` removed from 3 fonts
- Copyright strings get more escaping than might be necessary
  - I'm not sure whether all of these changes are desired, and simply from the updated Protobuf, or if some/many are incorrect. I need to find a way to see how these would render in practice.
- Adobe Blank gets subset labels, where it excluded these before – I'm not sure whether these will help or hurt its intended purpose
- Language coverage is different between styles, but metadata gets the labels for the more-extensive style (e.g. News Cycle Regular has wider coverage than Bold)

## Primary Current Question

There are a lot of changes introduced by running add-font across the collection. This gives two main paths forward in this PR:
1. Fixing add-font so that it runs as desired on every font in the collection. I'll probably have to loop in Marc and Felipe to assist in these updates. It will take longer and be slightly higher-risk, but will likely have greater overall benefits.
2. Simply adding `ext` labels to applicable fonts, using the existing diffs to guide a script in this, but leaving other possible fixes for later. This will be faster and lower-risk, but may be leaving other existing issues intact, both in metadata and add-font.

@davelab6 / @m4rc1e, which approach do you recommend taking?

---

To-Do items

- [ ] check for `UKNOWN` values, as are currently in the metadata for Open Sans Hebrew + Condensed

### CODE REVIEW

**Comment by thundernixon** [comment]
I've updated add-font to make font names in a more intelligent way and have remade metadata files again. Overall, this improves many of the names that were previously getting messed up by being derived from the filenames. Still, there are some aspects that don't seem perfect yet.

Some possible issues:
-  `Cantora One` becomes `CantoraOne`
- `Fjord One` becomes `Fjord`
- `Gemunu Libre` becomes `Gemunu Libre ExtraLight`
- `Hammersmith One` becomes `HammersmithOne`
- `Headland One` becomes `HeadlandOne`
- 3 `Nanum` families lose spaces (e.g. `Nanum Gothic Coding` becomes `NanumGothicCoding`)
- `Nanum Pen Script` becomes `Nanum Pen`
- `Pompiere` becomes `Pompiere ` (it gets a trailing space)
- `Post No Bills Colombo` becomes `Post No Bills Colombo Light`
- `Post No Bills Jaffna` becomes `Post No Bills Jaffna Light`
- `Raleway Dots` becomes `Raleway Dots ` (gets a trailing space)
- `Sansation` becomes `Sansation Light`
- 4 `Seoul` families lose spaces. E.g. `Seoul Hangang` becomes `SeoulHangang` (not sure if this change is incorrect, but it seems off)
- `Sirin Stencil` becomes `SirinStencil`
- `Supermercado One` becomes `Supermercado`
- `Yaldevi Colombo` becomes `Yaldevi Colombo ExtraLight`


I don't know for sure, but I suspect that these issues (at least most of them) are because of odd naming in nameID 16 or 1. As one example, SirinStencil has this for nameID 1, even though it has a space in the GF website:

```
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      SirinStencil
</namerecord>
```
Likewise, it's "Hammersmith One" on the directory, but:
```
<namerecord nameID="1" platformID="1" platEncID="0" langID="0x0" unicode="True">
      HammersmithOne
</namerecord>
```

**Comment by thlinard** [comment]
So, you get the font nameID 16, else nameID 1, and you obtain:
    * Gemunu Libre ExtraLight
    * Post No Bills Colombo Light
    * Post No Bills Jaffna Light
    * Sansation Light
    * Yaldevi Colombo ExtraLight

This is a kind of bug check for these fonts, isn't it? The fonts should receive a nameID 16, which is obviously lacking.

The other cases are a matter of consistency.

**Comment by thundernixon** [comment]
> This is a kind of bug check for these fonts

That's an interesting way to look at it! NameID 16 is optional, and software just falls back to nameID 1 if it's lacking. But yes, it wouldn't hurt to add 16 to correct the root issue.

**Comment by m4rc1e** [comment]
> That's an interesting way to look at it! NameID 16 is optional, and software just falls back to nameID 1 if it's lacking. But yes, it wouldn't hurt to add 16 to correct the root issue.

NameID 16 and 17 should be used if a font style is non RIBBI. The fonts @thlinard pointed out are all non RIBBI.

Ms spec has more info: https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids

You'll find that all of these fonts will also fail Fontbakery on the name checks.

**Comment by m4rc1e** [comment]
This pr enables latin-ext for 668 families. How many families will enable latin-ext if we use the default 10% theshold?

**Comment by m4rc1e** [comment]
@davelab6 If we stick to the original 10% threshold, we'll get an additional 86 families added to latin-ext. This sounds more sensible than adding 233 families which may only contain 1 latin-ext glyph. Shall we proceed with the 86 approach? it also doesn't modify the copyright strings or remove any existing codepages. It will only add the latin-ext codepage of there's more than 80 glyphs.

**Comment by thundernixon** [comment]
*source of "213" added latin-ext families:

Search for the string `+subsets: "latin-ext"` in: 
- https://github.com/thundernixon/fix-gf-metadata/blob/master/docs/git-diffs-ofl.txt
- https://github.com/thundernixon/fix-gf-metadata/blob/master/docs/git-diffs-apache.txt

**Pull request closed without merging**
