### PR TITLE
arefruqaa: v1.002 (#1132)

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.25

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds
/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** Could not find ftxvalidator.

</details>
<br>
</details>
<details>
<summary><b>[8] ArefRuqaa-Bold.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check license file has good copyright string.</summary>

* [com.google.fonts/check/license/OFL_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright)
<pre>--- Rationale ---

An OFL.txt file&#x27;s first line should be the font copyright e.g:
&quot;Copyright 2019 The Montserrat Project Authors
(https://github.com/julietaula/montserrat)&quot;


</pre>

* 🔥 **FAIL** First line in license file does not match expected format: "copyright 2015-2020 the aref ruqaa project authors (https://github.com/alif-type/aref-ruqaa), with reserved font name eurm10."

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)
<pre>--- Rationale ---

The expected pattern for the copyright string adheres to the following rules:
* It must say &quot;Copyright&quot; followed by a 4 digit year
* Then it must say &quot;The &lt;familyname&gt; Project Authors&quot;
* And within parentheses, a URL for a git repository must be provided
* The check is case insensitive and does not validate whether the familyname is
correct, even though we&#x27;d expect it is (and we may soon update the check to
validate that aspect as well!)

Here is an example of a valid copyright string:
&quot;Copyright 2017 The Archivo Black Project Authors
(https://github.com/Omnibus-Type/ArchivoBlack)&quot;


</pre>

* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2020 The Familyname Project Authors (git url)"
But instead we have got:
"copyright 2015-2020 the aref ruqaa project authors (https://github.com/alif-type/aref-ruqaa), with reserved font name eurm10." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)

* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Name table strings must not contain the string 'Reserved Font Name'.</summary>

* [com.google.fonts/check/name/rfn](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn)
<pre>--- Rationale ---

Some designers adopt the &quot;Reserved Font Name&quot; clause of the OFL license. This
means that the original author reserves the rights to the family name and other
people can only distribute modified versions using a different family name.

Google Fonts published updates to the fonts in the collection in order to fix
issues and/or implement further improvements to the fonts. It is important to
keep the family name so that users of the webfonts can benefit from the
updates. Since it would forbid such usage scenario, all families in the GFonts
collection are required to not adopt the RFN clause.

This check ensures &quot;Reserved Font Name&quot; is not mentioned in the name table.


</pre>

* 🔥 **FAIL** Name table entry ("Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering?</summary>

* [com.google.fonts/check/gasp](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp)
<pre>--- Rationale ---

Traditionally version 0 &#x27;gasp&#x27; tables were set so that font sizes below 8 ppem
had no grid fitting but did have antialiasing. From 9-16 ppem, just grid
fitting. And fonts above 17ppem had both antialiasing and grid fitting toggled
on. The use of accelerated graphics cards and higher resolution screens make
this approach obsolete. Microsoft&#x27;s DirectWrite pushed this even further with
much improved rendering built into the OS and apps.

In this scenario it makes sense to simply toggle all 4 flags ON for all font
sizes.


</pre>

* ⚠ **WARN** The gasp range 0xFFFF value 0x02 should be set to 0x0F. [code: unset-flags]

</details>
<details>
<summary>⚠ <b>WARN:</b> Copyright notice on METADATA.pb should not contain 'Reserved Font Name'.</summary>

* [com.google.fonts/check/metadata/reserved_font_name](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/reserved_font_name)

* ⚠ **WARN** METADATA.pb: copyright field ("Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [arKaf.init, .notdef]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** hhea lineGap is not equal to 0. [code: hhea]

</details>
<br>
</details>
<details>
<summary><b>[8] ArefRuqaa-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check license file has good copyright string.</summary>

* [com.google.fonts/check/license/OFL_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_copyright)
<pre>--- Rationale ---

An OFL.txt file&#x27;s first line should be the font copyright e.g:
&quot;Copyright 2019 The Montserrat Project Authors
(https://github.com/julietaula/montserrat)&quot;


</pre>

* 🔥 **FAIL** First line in license file does not match expected format: "copyright 2015-2020 the aref ruqaa project authors (https://github.com/alif-type/aref-ruqaa), with reserved font name eurm10."

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)
<pre>--- Rationale ---

The expected pattern for the copyright string adheres to the following rules:
* It must say &quot;Copyright&quot; followed by a 4 digit year
* Then it must say &quot;The &lt;familyname&gt; Project Authors&quot;
* And within parentheses, a URL for a git repository must be provided
* The check is case insensitive and does not validate whether the familyname is
correct, even though we&#x27;d expect it is (and we may soon update the check to
validate that aspect as well!)

Here is an example of a valid copyright string:
&quot;Copyright 2017 The Archivo Black Project Authors
(https://github.com/Omnibus-Type/ArchivoBlack)&quot;


</pre>

* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2020 The Familyname Project Authors (git url)"
But instead we have got:
"copyright 2015-2020 the aref ruqaa project authors (https://github.com/alif-type/aref-ruqaa), with reserved font name eurm10." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)

* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10." [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Name table strings must not contain the string 'Reserved Font Name'.</summary>

* [com.google.fonts/check/name/rfn](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/rfn)
<pre>--- Rationale ---

Some designers adopt the &quot;Reserved Font Name&quot; clause of the OFL license. This
means that the original author reserves the rights to the family name and other
people can only distribute modified versions using a different family name.

Google Fonts published updates to the fonts in the collection in order to fix
issues and/or implement further improvements to the fonts. It is important to
keep the family name so that users of the webfonts can benefit from the
updates. Since it would forbid such usage scenario, all families in the GFonts
collection are required to not adopt the RFN clause.

This check ensures &quot;Reserved Font Name&quot; is not mentioned in the name table.


</pre>

* 🔥 **FAIL** Name table entry ("Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is the Grid-fitting and Scan-conversion Procedure ('gasp') table set to optimize rendering?</summary>

* [com.google.fonts/check/gasp](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gasp)
<pre>--- Rationale ---

Traditionally version 0 &#x27;gasp&#x27; tables were set so that font sizes below 8 ppem
had no grid fitting but did have antialiasing. From 9-16 ppem, just grid
fitting. And fonts above 17ppem had both antialiasing and grid fitting toggled
on. The use of accelerated graphics cards and higher resolution screens make
this approach obsolete. Microsoft&#x27;s DirectWrite pushed this even further with
much improved rendering built into the OS and apps.

In this scenario it makes sense to simply toggle all 4 flags ON for all font
sizes.


</pre>

* ⚠ **WARN** The gasp range 0xFFFF value 0x02 should be set to 0x0F. [code: unset-flags]

</details>
<details>
<summary>⚠ <b>WARN:</b> Copyright notice on METADATA.pb should not contain 'Reserved Font Name'.</summary>

* [com.google.fonts/check/metadata/reserved_font_name](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/reserved_font_name)

* ⚠ **WARN** METADATA.pb: copyright field ("Copyright 2015-2020 The Aref Ruqaa Project Authors (https://github.com/alif-type/aref-ruqaa), with Reserved Font Name EURM10.") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>⚠ <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/production_glyphs_similarity](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/production_glyphs_similarity)

* ⚠ **WARN** Following glyphs differ greatly from Google Fonts version: [arKaf.init, .notdef]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** hhea lineGap is not equal to 0. [code: hhea]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 8 | 9 | 61 | 15 | 233 | 0 |
| 0% | 2% | 3% | 19% | 5% | 71% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [arefruqaa_qa.zip](http://35.238.63.0/media/2d445f5f-9931-461a-8293-66a40bd6c1dc/arefruqaa_qa.zip)

**Comment by m4rc1e** [comment]
Thanks!

The spacing for the Latin has changed a lot but it looks way better.

Desktop_OS_X_High_Sierra_safari_11 1_


Seems these glyphs are missing

glyphs_missing

uni06F0, uni06F1, uni06F3, uni06F8, uni06F9 

@khaledhosny is this intentional?

**Comment by khaledhosny** [comment]
> 🔥 FAIL: Check license file has good copyright string.
> 🔥 FAIL: Copyright notices match canonical pattern in METADATA.pb
> 🔥 FAIL: Copyright notices match canonical pattern in fonts

These are fixed in Fontbakery, you might need to update your installation.
 
> 🔥 FAIL: Name table strings must not contain the string 'Reserved Font Name'.

This is unfortunate but harmless, it involves the name of the original Latin fonts (EURM10, EURB10) which we don’t use here.

**Comment by khaledhosny** [comment]
> Thanks!
> 
> The spacing for the Latin has changed a lot but it looks way better.

Yes, that is one of the major changes. It was re-spaced by @kalapi for GF years ago.

> Seems these glyphs are missing
> 
> glyphs_missing
> 
> uni06F0, uni06F1, uni06F3, uni06F8, uni06F9
> 
> @khaledhosny is this intentional?

Yes, the glyphs are identical to other glyphs so they were de-duplicated and the characters were mapped to the other glyphs:

```
$ hb-shape ArefRuqaa-Regular.ttf -u '06F0,06F1,06F3,06F8,06F9' --direction=l
[uni0660=0+475|uni0661=1+387|uni0663=2+848|uni0668=3+771|uni0669=4+651]

$ hb-view ArefRuqaa-Regular.ttf -u '06F0,06F1,06F3,06F8,06F9' --direction=l
```
hb-view output

**Comment by m4rc1e** [comment]
SGTM. I'll recheck it once its been pushed to sandbox.

**Comment by khaledhosny** [comment]
Thanks!

**Comment by m4rc1e** [comment]
Will be around 2 weeks before it hits prod. Thank you for the clean pr!

**Comment by khaledhosny** [comment]
> Will be around 2 weeks before it hits prod.

 Have there been any progress in this? I still see the old fonts in https://fonts.google.com/specimen/Aref+Ruqaa

**Comment by khaledhosny** [comment]
Any news? it is been almost two months. Is it stuck somewhere, Amiri is already updated and it was merged later.

**Comment by m4rc1e** [comment]
@khaledhosny I'll see what's holding it up. If it's good, I'll get it pushed this week.

**Comment by khaledhosny** [comment]
Friendly reminder.

**Comment by m4rc1e** [comment]
Sorry for the delay. I'll see what's holding it up.

**Comment by khaledhosny** [comment]
It is been over three months since this PR was merged and the font is still not updated on the server. cc @davelab6

**Comment by RosaWagner** [comment]
Metadata.pb misses arabic in the subset menu, we should add it before sending it to production

**Comment by khaledhosny** [comment]
> Metadata.pb misses arabic in the subset menu, we should add it before sending it to production

It is been like that since it was first added in #1001, but I can send a PR if you want me to.

**Comment by RosaWagner** [comment]
it's okay, it's a pretty quick fix, I do it now ;)

**Comment by RosaWagner** [comment]
Fixed in : https://github.com/google/fonts/pull/2769

**Comment by khaledhosny** [comment]
Thanks!

**Pull request merged**
