### PR TITLE
Rubik Doodle Shadow: Version 2.201 added

### LINKED ISSUE #3710: Add Rubik Doodle Shadow
upstream: https://github.com/NaN-xyz/Rubik-Filtered

Capture d’écran 2022-05-19 à 17 58 15

- [ ] Build
- [ ] QA
- [ ] PR Upstream
- [ ] Package

### PR DESCRIPTION
**Pull request by RosaWagner**
981d8c3: [gftools-packager] Rubik Doodle Shadow: Version 2.201 added

* Rubik Doodle Shadow Version 2.201 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/409369746e32796524d9b0b6c9c5aa6445c83bcd.

Closes #3710 

For fails to ignore see #6998

### CODE REVIEW

**Comment by emmamarichal** [comment]
Maybe to confirm with the designer if these kind of things ok
->  avoid the overlapping(1) with a small dot? (2)

(1)
Capture d’écran 2023-11-22 à 17 55 46

(2)
Capture d’écran 2023-11-22 à 17 56 44

**Comment by RosaWagner** [comment]
Yes ideally it would better to avoid that.

**Comment by RosaWagner** [comment]
Updated

## Rubik Doodle Shadow: Version 2.201 added

---
 0a22934: [gftools-packager] Rubik Doodle Shadow: Version 2.201 added

* Rubik Doodle Shadow Version 2.201 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/c70421b2f209e0aa88a84210d94da557602a5e56.

**Comment by RosaWagner** [comment]
@emmamarichal just fixed it

**Pull request merged**
