### PR TITLE
Noto Sans Oriya: Version 2.005 added

### PR DESCRIPTION
**Pull request by simoncozens**
4d7d100: [gftools-packager] Noto Sans Oriya: Version 2.005 added

* Noto Sans Oriya Version 2.005 taken from the upstream repo https://github.com/notofonts/oriya.git at commit https://github.com/notofonts/oriya/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens can you check the diff? there are big changes

**Comment by simoncozens** [comment]
Sorry, I should have left a note. Yes, I expect big changes. We fixed a lot of anchor attachment issues. I looked through the diffenator output and I am very happy with it - big improvement!

**Comment by simoncozens** [comment]
Argh. We don't have the right masters for this to work with our toolchain. (No regular condensed master.) I'll see if Glyphs can synthesise one.

**Comment by RosaWagner** [comment]
Ah one should always refresh the page.

**Pull request merged**
