### PR TITLE
Reem Kufi Ink: Version 1.7 added (#5592)

### PR DESCRIPTION
**Pull request by RosaWagner**
* Reem Kufi Ink Version 1.7 taken from the upstream repo https://github.com/aliftype/reem-kufi.git at commit https://github.com/aliftype/reem-kufi/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@khaledhosny to add the SVG table we run the maximum_color script, can it be somehow integrated to your build script?

**Comment by khaledhosny** [comment]
> @khaledhosny to add the SVG table we run the maximum_color script, can it be somehow be integrated into your build script?

Sure, I’ll try to do that.

**Comment by khaledhosny** [comment]
> > @khaledhosny to add the SVG table we run the maximum_color script, can it be somehow be integrated into your build script?
> 
> Sure, I’ll try to do that.

What options do you pass to `maximum_color`?

**Comment by RosaWagner** [comment]
I didn’t put the bitmap thing, just the default settings. But I think @rsheeter would have a better answer than me., cause I may have done it wrong.

**Comment by rsheeter** [comment]
It should be sufficient to run `maximum_color my_font_binary.ttf` (https://github.com/googlefonts/nanoemoji#adding-color-tables-to-existing-fonts) and then copy the generated file to wherever you want it.

**Pull request merged**
