### PR TITLE
Bakbak One: Version 1.002; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by aaronbell**
8ff6e8e: [gftools-packager] BakBak: Version 1.002; ttfautohint (v1.8.3) added

* BakBak Version 1.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/bakbak.git at commit https://github.com/googlefonts/bakbak/commit/eee2dc2a6da7fe3d5e636180be4f30a814866ac2.

 a7faf30: [gftools-packager] ofl/bakbak remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by m4rc1e** [comment]
Family looks very heavy for a Regular weight. @davelab6 shall we append "One" to the family name?

Desktop_Windows_10_chrome_71 0_

**Comment by davelab6** [comment]
@m4rc1e good catch, yes, sorry @aaronbell I forgot about this

**Comment by aaronbell** [comment]
Updated

## BakBak One: Version 1.002; ttfautohint (v1.8.3) added

---
 c620756: [gftools-packager] BakBak One: Version 1.002; ttfautohint (v1.8.3) added

* BakBak One Version 1.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/bakbak.git at commit https://github.com/googlefonts/bakbak/commit/e5d017474731395ca729bae4f43ff9cb61ff2df1.

 5394647: [gftools-packager] ofl/bakbakone remove METADATA "source".  google/fonts#2587

**Comment by aaronbell** [comment]
Font name updated :)

**Comment by RosaWagner** [comment]
Camel case name has been validated ?

-> Description typo: "Bakbak" / "BakBak"

**Comment by aaronbell** [comment]
Thanks Rosalie I double checked with the original specimen website and it appears that it is written "Bakbak". I'll change it

**Comment by aaronbell** [comment]
Updated

## Bakbak One: Version 1.002; ttfautohint (v1.8.3) added

---
 f76f089: [gftools-packager] Bakbak One: Version 1.002; ttfautohint (v1.8.3) added

* Bakbak One Version 1.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/bakbak.git at commit https://github.com/googlefonts/bakbak/commit/8308b62b527659d7be4a2890c5f07e2d1db1496b.

 2aa9a14: [gftools-packager] ofl/bakbakone remove METADATA "source".  google/fonts#2587

**Comment by m4rc1e** [comment]
Please add a description.

**Comment by aaronbell** [comment]
Weird. I thought I had. One has been added now.

**Comment by RosaWagner** [comment]
The font has only latin subset

**Pull request merged**
