### PR TITLE
nunitosans: v2.500 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/Fonthausen/NunitoSans

This pr adds the following glyphs

uni01D4, uni01E5, uni01E9, uni2052, uni01EF, uni021F, uni0292, uni0400, uni0401, uni0402, uni0403, uni0404, uni0405, uni0406, uni0407, uni0408, uni0409, uni040A, uni040B, uni040C, uni040D, uni040E, uni040F, uni0410, uni0411, uni0412, uni0413, uni0414, uni0415, uni0416, uni0417, uni0418, uni0419, uni041A, uni041B, uni041C, uni041D, uni041E, uni041F, uni0420, uni0421, uni0422, uni0423, uni0424, uni0425, uni0426, uni0427, uni0428, uni0429, uni042A, uni042B, uni042C, uni042D, uni042E, uni042F, uni0430, uni0431, uni0432, uni0433, uni0434, uni0435, uni0436, uni0437, uni0438, uni0439, uni043A, uni043B, uni043C, uni043D, uni043E, uni043F, uni0440, uni0441, uni0442, uni0443, uni0444, uni0445, uni0446, uni0447, uni0448, uni0449, uni044A, uni044B, uni044C, uni044D, uni044E, uni044F, uni0450, uni0451, uni0452, uni0453, uni0454, uni0455, uni0456, uni0457, uni0458, uni0459, uni045A, uni045B, uni045C, uni045D, uni045E, uni045F, uni0462, uni0463, uni046A, uni046B, uni0472, uni0473, uni0474, uni0475, uni048A, uni048B, uni048C, uni048D, uni048E, uni048F, uni0490, uni0491, uni0492, uni0493, uni0494, uni0495, uni0496, uni0497, uni0498, uni0499, uni049A, uni049B, uni049C, uni049D, uni049E, uni049F, uni04A0, uni04A1, uni04A2, uni04A3, uni04A4, uni04A5, uni04A8, uni04A9, uni04AA, uni04AB, uni04AC, uni04AD, uni04AE, uni04AF, uni04B0, uni04B1, uni04B2, uni04B3, uni04B4, uni04B5, uni04B6, uni04B7, uni04B8, uni04B9, uni04BA, uni04BB, uni04BC, uni04BD, uni04BE, uni04BF, uni04C0, uni04C1, uni04C2, uni04C3, uni04C4, uni04C5, uni04C6, uni04C7, uni04C8, uni04C9, uni04CA, uni04CB, uni04CC, uni04CD, uni04CE, uni04CF, uni04D0, uni04D1, uni04D2, uni04D3, uni04D4, uni04D5, uni04D6, uni04D7, uni04D8, uni04D9, uni04DA, uni04DB, uni04DC, uni04DD, uni04DE, uni04DF, uni04E0, uni04E1, uni04E2, uni04E3, uni04E4, uni04E5, uni04E6, uni04E7, uni04E8, uni04E9, uni04EA, uni04EB, uni04EC, uni04ED, uni04EE, uni04EF, uni04F0, uni04F1, uni04F2, uni04F3, uni04F4, uni04F5, uni04F6, uni04F7, uni04F8, uni04F9, uni04FA, uni04FB, uni04FC, uni04FD, uni04FE, uni04FF, uni0510, uni0511, uni0512, uni0513, uni051A, uni051B, uni051C, uni051D, uni0524, uni0525, uni0526, uni0527, uni0528, uni0529, uni052E, uni052F, uni20AE, uni20B4, uni20B8, uni27E8, uni27E9

desktop_windows_7_ie_9 0_

**FB Report**
```
There is a total of 127 checks on <Section: Default>.
Start ... running 1440 individual check executions.
>> com.google.fonts/check/011
   Fonts have equal numbers of glyphs?
 * FAIL: Fonts have different numbers of glyphs:

| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraLight.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Regular.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraBoldItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraBold.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Italic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-LightItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Black.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Bold.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-BlackItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-BoldItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Light.ttf | 1041 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-SemiBoldItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraLightItalic.ttf | 1043 |
| /Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-SemiBold.ttf | 1041 |


   Result: FAIL

>> com.google.fonts/check/012
   Fonts have equal glyph names?
 * FAIL: Fonts have different glyph names.

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Black.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-BlackItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[2]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Bold.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[3]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-BoldItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraBold.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraBoldItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[6]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraLight.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-ExtraLightItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[8]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Italic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[9]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Light.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[10]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-LightItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[11]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-Regular.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[12]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-SemiBold.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

>> com.google.fonts/check/018 with ((u'font[13]', '/Users/marc/Documents/googlefonts/fonts/ofl/nunitosans/NunitoSans-SemiBoldItalic.ttf'),)
   Checking OS/2 achVendID
 * FAIL: OS/2 VendorID is 'UKWN', a font editor default. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: bad]

   Result: FAIL

======== <Section: Default> ========
1440 checks in section


Section results:

    ERROR: 0
    FAIL: 16
    WARN: 81
    SKIP: 57
    INFO: 72
    PASS: 1172

======== END <Section: Default> ========

Total:

    ERROR: 0
    FAIL: 16
    WARN: 81
    SKIP: 57
    INFO: 72
    PASS: 1214


DONE!


```
Summary:
Vendor Id: Same as before, skipping

**Rendering**
```
Regression Report:

Fonts: ["NunitoSans-Black.ttf", "NunitoSans-Light.ttf", "NunitoSans-Regular.ttf"]

View: glyphs-modified
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same

View: waterfall
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 11384 pixels
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 688 pixels
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 10875 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 688 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 50393 pixels
```

Worst Performing, Win 7 Firefox

desktop_windows_7_firefox_45 0_

desktop_windows_7_firefox_45 0_

@alexeiva did you jig the kerning?

@davelab6 apart from the kerning changes, I'm happy with this.

[NunitoSans_img.zip](https://github.com/google/fonts/files/1542489/NunitoSans_img.zip)

### CODE REVIEW

**Comment by m4rc1e** [comment]
GFR link, http://45.55.138.144/compare/10238653-6fce-4c97-8a55-d158a1c284e7 (Expires Sunday)

**Comment by alexeiva** [comment]
May be related to ttfautohint options parameter. Is it the same? We have seen similar behavior after my hintingfix1.

Or another less likely option, Latin kerning jigged after changes in Cyrillic, since classes are shared.  I will inspect this.

**Comment by m4rc1e** [comment]
We have differences reported in OS X which doesn't use ttfautohint

**Comment by alexeiva** [comment]
You are right, there are 12 diffs in the cluster-foxtroted Latin kerning (In Light master):

```
$> colordiff /Users/alexeiva/Desktop/Light-LAT.txt /Users/alexeiva/Desktop/Light-MY.txt 
177a178
> @MMK_L_O,@MMK_R_hyphen,-20.0
496a498
> @MMK_L_e,@MMK_R_T,-100.0
628a631
> @MMK_L_n,@MMK_R_T,-50.0
636a640
> @MMK_L_o,@MMK_R_T,-80.0
770a775
> @MMK_L_s,@MMK_R_T,-80.0
833a839
> @MMK_L_u,@MMK_R_T,-80.0
844a851,853
> @MMK_L_v,@MMK_R_O,-10.0
> @MMK_L_v,@MMK_R_T,-60.0
> @MMK_L_v,@MMK_R_X,-10.0
850a860
> @MMK_L_v,@MMK_R_h,10.0
860a871
> @MMK_L_x,@MMK_R_T,-60.0
903c914
< racute,@MMK_R_braceright,60.0
```
I will reset the Latin kerning.

**Comment by alexeiva** [comment]
Here are the kerning changes visualized. It doesn't look like they affected pairs `i+n`,`i+c`,`t+i` as seen in your gifs. These pairs have no kerning in both versions.

_Left: v2.500 with 12 new Latin pairs | Right: v2.002_

screen shot 2017-12-11 at 6 18 41 pm

_Top: v2.500 | Bottom: v2.002 => Identical metrics and kerning_

screen shot 2017-12-11 at 6 23 29 pm

Can these changes be related to v.2000 vs v.2002 update, or a new Glyphs version?

**Comment by alexeiva** [comment]
I downloaded and checked the TTFs, GF serves v2.001, but not v2.002 yet.

In 2.002 you added a ttfautohint --detailed-info custom parameter https://github.com/m4rc1e/NunitoSans/commit/1f035bd0ec3cf0314875d0ccdc327a066647277b#diff-50136c7b8cc5a82ebf1629afd55739e2R31

I think this parameter caused the kern jitter or I would say a different grid-fitting ttfautohint behavior.

**Comment by alexeiva** [comment]
2.501 in https://github.com/m4rc1e/NunitoSans/pull/2 restores original kerning in Latin. 12 pairs in Light, and 44 pairs in Bold were removed.

**Comment by m4rc1e** [comment]
kerns_modified

Only modifications are happening to T: combos. This looks fine to me so I'm merging

**Pull request merged**
