### PR TITLE
Voltaire: Version 1.009; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/SorkinType/Voltaire at commit https://github.com/SorkinType/Voltaire/commit/552e0def6d66582c2132271b11243054e770d09a.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [x] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [x] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL The following glyphs lack their case-swapping counterparts:

Some capital counterparts are missing.

**Comment by vv-monsalve** [comment]
@EbenSorkin, could you please confirm about the missing counterpart characters reported above?

**Comment by emmamarichal** [comment]
@vv-monsalve the work is done, he just have to merge my last PR, and then I'll update this one :) 

@EbenSorkin it also concerns Calistoga and maybe Alata and Pinyon Script

**Comment by EbenSorkin** [comment]
I added them yesterday for Emma

**Comment by emmamarichal** [comment]
Updated

**Review by m4rc1e — APPROVED** [review]

**Pull request merged**
