### PR TITLE
Public Sans Roman: v1.006 added

### PR DESCRIPTION
**Pull request by eliheuer**
From the upstream repo: https://github.com/uswds/public-sans
At commit: 4c9f0fab4659bcab309fe3ab03abe45be704b108

### CODE REVIEW

**Comment by wouterds** [comment]
Any progress being made?

**Comment by eliheuer** [comment]
@wouterds Yes, I'm working on this all week.

**Comment by m4rc1e** [comment]
- weightClass: vals are different for vfs. Since we want multiples of 100, the Thin should be 100 and the ExtraLight 200.

- Copyright: Is the copyright holder really Impallari or is this a derivative of one of his families?

**Comment by eliheuer** [comment]
Thanks marc, I'm addressing both these points in upstream issues. Both italic and roman are building with fontmake, so this should be ready for a serious merge review soon.

**Comment by eliheuer** [comment]
@m4rc1e The odd copyright is due to Matthew Butterick's activity in the repo's issues:
https://github.com/uswds/public-sans/issues/30
https://github.com/uswds/public-sans/issues/31

Leaving Pablo Impallari as the copyright holder was a compromise since Matthew claims any work of a US government employee is not subject to copyright: [17 USC § 105](https://www.law.cornell.edu/uscode/text/17/105)

This seems wrong to me beacuse the copyright was transfered to Dan when he forked the project, he didn't start Public Sans from scratch as a US government employee. Anyway, I need to reread that long issue to make sure I understand what happened.

**Comment by davelab6** [comment]
I accept this

**Comment by m4rc1e** [comment]
@eliheuer Can I ignore the Italic pr, #2010? Each family should not be spread over multiple prs.

**Comment by m4rc1e** [comment]
@eliheuer Just ran a QA on both the Roman and Italic and it looks good. Mind if I close #2010 and move the Italic ttf into this pr?

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.14

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb: According Google Fonts standards, families should have a Regular style.</summary>

* [com.google.fonts/check/metadata/has_regular](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/has_regular)
* 🔥 **FAIL** This family lacks a Regular (style: normal and weight: 400) as required by Google Fonts standards. [code: lacks-regular]

</details>
<br>
</details>
<details>
<summary><b>[10] PublicSans-Italic[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please mention in the DESCRIPTION.en-us.html that the family is a variable font. This check expects the words 'variable font' to be present in the text e.g 'This font is now available as a variable font.' [code: should-mention-varfonts]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)
* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2015, Pablo Impallari, Rodrigo Fuenzalida (Modified by Dan O. Williams and USWDS) (https://github.com/uswds/public-sans)" [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2015, Impallari Type (www.impallari.com)" [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWeightClass matches weight specified at METADATA.pb.</summary>

* [com.google.fonts/check/metadata/os2_weightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/os2_weightclass)
* 🔥 **FAIL** OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (100:"Thin"). [code: mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright field for this font on METADATA.pb matches all copyright notice entries on the name table ?</summary>

* [com.google.fonts/check/metadata/nameid/copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/copyright)
* 🔥 **FAIL** Copyright field for this font on METADATA.pb ("Copyright (c) 2015, Pablo Impallari, Rodrigo Fuenzalida (Modified by Dan O. Williams and USWDS) (https://github.com/uswds/public-sans)") differs from a copyright notice entry on the name table: "Copyright (c) 2015, Impallari Type (www.impallari.com)" [code: mismatch]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID value 'NONE' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 usWeightClass.</summary>

* [com.google.fonts/check/usweightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/usweightclass)
* ⚠ **WARN** Thin Italic:100 is OK on TTFs, but OTF files with those values will cause bluring on Windows. GlyphsApp users must set an Instance Custom Parameter for the Thin and ExtraLight styles to 250 and 275, so that if OTFs are exported then it will not blur on Windows. [code: blur-on-windows]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l
	- colon + f
	- f + l
	- l + a
	- a + g
	- g + two
	- two + colon
	- g + colon
	- colon + one
	- one + eight
	- eight + F
	- F + colon

   [code: lacks-kern-info]

</details>
<br>
</details>
<details>
<summary><b>[11] PublicSans[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Does DESCRIPTION file mention when a family is available as variable font?</summary>

* [com.google.fonts/check/description/variable_font](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/variable_font)
* 🔥 **FAIL** Please mention in the DESCRIPTION.en-us.html that the family is a variable font. This check expects the words 'variable font' to be present in the text e.g 'This font is now available as a variable font.' [code: should-mention-varfonts]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)
* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2015, Pablo Impallari, Rodrigo Fuenzalida (Modified by Dan O. Williams and USWDS) (https://github.com/uswds/public-sans)" [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in fonts</summary>

* [com.google.fonts/check/font_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/font_copyright)
* 🔥 **FAIL** Name Table entry: Copyright notices should match a pattern similar to: "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2015, Impallari Type (www.impallari.com)" [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWeightClass matches weight specified at METADATA.pb.</summary>

* [com.google.fonts/check/metadata/os2_weightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/os2_weightclass)
* 🔥 **FAIL** OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (100:"Thin"). [code: mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright field for this font on METADATA.pb matches all copyright notice entries on the name table ?</summary>

* [com.google.fonts/check/metadata/nameid/copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/copyright)
* 🔥 **FAIL** Copyright field for this font on METADATA.pb ("Copyright (c) 2015, Pablo Impallari, Rodrigo Fuenzalida (Modified by Dan O. Williams and USWDS) (https://github.com/uswds/public-sans)") differs from a copyright notice entry on the name table: "Copyright (c) 2015, Impallari Type (www.impallari.com)" [code: mismatch]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
* ⚠ **WARN** OS/2 VendorID value 'NONE' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 usWeightClass.</summary>

* [com.google.fonts/check/usweightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/usweightclass)
* ⚠ **WARN** Thin:100 is OK on TTFs, but OTF files with those values will cause bluring on Windows. GlyphsApp users must set an Instance Custom Parameter for the Thin and ExtraLight styles to 250 and 275, so that if OTFs are exported then it will not blur on Windows. [code: blur-on-windows]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l
	- colon + f
	- f + l
	- l + a
	- a + g
	- g + two
	- two + colon
	- g + colon
	- colon + one
	- one + eight
	- eight + F
	- F + colon

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/glyf.html#com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
	* ('uni2120', 74.5, 221.25)

This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message. [code: points-out-of-bounds]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 11 | 11 | 67 | 15 | 189 | 0 |
| 0% | 4% | 4% | 23% | 5% | 65% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [public_sans_qa.zip](http://35.188.158.120/media/eb464c23-3948-4874-8526-015ad0b9e24c/public_sans_qa.zip)

**Comment by thisisdano** [comment]
Hi — I see I’m coming to this late but we plan to release v1.007 next week with fixes to the light and extralight weightClasses among other metrics and spacing changes. I see this PR is now merged but might it make sense to start with v1.007?

Draft PR here: https://github.com/uswds/public-sans/pull/123

Thanks for all your work on this. Let me know how I can be helpful.

**Comment by davelab6** [comment]
Thanks Dan! While this is merged, Marc can hold off from pushing it through
the pipeline until the next PR is merged.

**Comment by thisisdano** [comment]
I see that it is live now. (https://github.com/google/fonts/issues/1923) 🎉 
I will be pushing a new release out today — what's the process for submitting and processing updates?

**Comment by davelab6** [comment]
> I will be pushing a new release out today — what's the process for submitting and processing updates?

File an issue on this repo asking for an update, and you can try to ping me on twitter/email/etc if there is some urgency.

**Pull request merged**
