### PR TITLE
Jacquard 12 Charted: Version 1.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
f4bb5af: [gftools-packager] Jacquard 12 Charted: Version 1.000 added

* Jacquard 12 Charted Version 1.000 taken from the upstream repo https://github.com/scfried/soft-type-jacquard at commit https://github.com/scfried/soft-type-jacquard/commit/9c5c14889fd148d385536658cc2d320be294f32d.

 4da0a25: Description and metadatas updated

### CODE REVIEW

**Comment by emmamarichal** [comment]
@m4rc1e 

Some fails explanation:

🔥 FAIL: Whitespace glyphs have ink? 
-> This is the charted version with a grid, so it's normal.

🔥 FAIL: Does DESCRIPTION file contain broken links? 
-> Normal, the links are those of the other fonts in the family, which are not yet live

🔥 FAIL: Check font follows the Google Fonts vertical metric schema 
-> The grid makes the v-metrics special, we can ignore

**Review by m4rc1e — APPROVED** [review]

**Comment by emmamarichal** [comment]
blocked because of the menu rendering

**Comment by emmamarichal** [comment]
@chrissimpkins are the menus ok? can I unblock it?

**Comment by chrissimpkins** [comment]
> @chrissimpkins are the menus ok? can I unblock it?

Ready to go

**Pull request merged**
