### PR TITLE
Chivo Mono: Version 1.008 added

### PR DESCRIPTION
**Pull request by emmamarichal**
41c6ec1: [gftools-packager] Chivo Mono: Version 1.008 added

* Chivo Mono Version 1.008 taken from the upstream repo https://github.com/Omnibus-Type/Chivo at commit https://github.com/Omnibus-Type/Chivo/commit/b651a548bc8432485aaf0513da0f00a9ad774868.

 dc32907: Description added (to complete)

### CODE REVIEW

**Comment by emmamarichal** [comment]
In the fontbakery, there is a fail on the v-metrics, which do not follow the Google specs. Knowing that there is only 10 units difference, I kept the same values as in the normal Chivo and be consistent.

**Comment by RosaWagner** [comment]
@emmamarichal is this still in progress ?

**Comment by emmamarichal** [comment]
They merged my last PR https://github.com/Omnibus-Type/Chivo/pull/4
I'll do that next week :)

**Comment by RosaWagner** [comment]
@emmamarichal can you check the font for these signs which appear a bit bolder in sandbox?
Capture d’écran 2022-11-09 à 13 31 31 


Capture d’écran 2022-11-09 à 13 30 54

**Pull request merged**
