### PR TITLE
Jaro: Version 1.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
2a07a56: [gftools-packager] Jaro: Version 1.000 added

* Jaro Version 1.000 taken from the upstream repo https://github.com/agyeiarcher/Jaro at commit https://github.com/agyeiarcher/Jaro/commit/51096c4f8e9e0076709d509b905741470beb972d.

 6aa5422: description

- [x] tags - form sent
- [ ] images - images asked
- [ ] designer profiles
Céline Hurka: https://github.com/google/fonts/pull/7477
Agyei Archer
- [ ] Improve the description @bghryct 
- [ ] review

### CODE REVIEW

**Comment by m4rc1e** [comment]
LGTM

**Comment by vv-monsalve** [comment]
@emmamarichal Agyei Archer and Celine Hurka are missing the designer's bio info. Is it ok?
Screen Shot 2024-04-17 at 19 46 20

**Comment by vv-monsalve** [comment]
I've now seen the PR for Celine, but not for Agyei.

**Comment by emmamarichal** [comment]
Celine has been added: https://github.com/google/fonts/pull/7477
I'll ask Mirko for Agyei!

**Pull request merged**
