### PR TITLE
muktamalar: v2.203 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Thanks @girish-dalvi

This is currently unreleased on http://fonts.google.com

I did a quick test on https://theekkathir.in/2017/01/24/தோழர்-என்றால்-அவர்களின்/ with font dragr. Its shaping correctly.

**Mac Os X Safari**
screen shot 2017-01-26 at 15 26 19

**Win 7 Chrome**
screen shot 2017-01-26 at 15 33 50

Cheers,
Marc

### CODE REVIEW

**Comment by m4rc1e** [comment]
@girish-dalvi Just to point out, the [sources](https://github.com/EkType/Mukta) contain no autohinting.

cc @davelab6

**Comment by davelab6** [comment]
I suggest leaving this PR open until ttfautohint is applied

**Comment by m4rc1e** [comment]
I was curious and put the font through ttfautohint v1.6 with default settings.

**Win7 Chrome**
screen shot 2017-01-26 at 15 58 29

The rendering is far better and @girish-dalvi agrees. I'll add autohinting.

keep this open.

**Comment by m4rc1e** [comment]
Last push involved using ttfautohint to hint the fonts. Settings are recorded in the [hotfix source build script](https://github.com/googlefonts/MuktaGFVersion/blob/master/build/build.sh#L55)

screen shot 2017-01-26 at 16 30 11

I've disabled x-height scaling for this font. My previous comment has it applied. Personally, I prefer it without. However, this is always debatable.

**Comment by m4rc1e** [comment]
@davelab6 My Mac and Win ttfautohints were out of sync. Let me pr these again using ttfautohint v1.6, currently they're v1.5.

**Comment by m4rc1e** [comment]
Ok, fonts have been run through ttfautohint v1.6.

Changes are minimal from previous
screen shot 2017-01-26 at 17 24 24


Note to brew users: brew ttfautohint needs upgrading, it still uses v1.5

**Pull request closed without merging**
