### PR TITLE
josefinsans: v2.000 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
I am pleased to finally have this out the bag. Thanks @ThomasJockin.

The missing glyphs issue in the upstream repo, has been solved,
https://github.com/ThomasJockin/JosefinSansFont-master/issues/4

This update is a big one. I looked at the fonts in GFR, it looks pretty sweet.

josefin

### CODE REVIEW

**Comment by m4rc1e** [comment]
People may complain because the update is so drastic... however, it looks way better.

**Comment by indolering** [comment]
This also contains a bugfix (#28) that has been floating around for 2 years!

**Comment by m4rc1e** [comment]
@indolering A test or evidence would be nice to see?

**Comment by davelab6** [comment]
@m4rc1e yeah I think @indolering is right on this. Josefin has needed the last mile for ages

**Comment by indolering** [comment]
Nope, @m4rc1e is correct, his pull doesn't have that fix.  @m4rc1e could you cherry pick?

**Comment by davelab6** [comment]
@indolering which commit do you want to cherry pick?

**Comment by indolering** [comment]
@davelab6 IDK :man_shrugging:.

**Comment by thezelja** [comment]
@m4rc1e is there any option to revert to v1.0 
or use Josefine Sans v1.0 from fonts.google.com?

**Comment by davelab6** [comment]
You could apply negative letter-spacing to reduce the shift in spacing;
however the new spacing is considered better for readability.

**Comment by thezelja** [comment]
@davelab6 thanx

**Comment by redranger** [comment]
My feedback is that v.1 looked much better. I will need to remove this font as an option on my websites as it is not nearly as nice. Sorry! Any chance we can get v.1 back, or at least have it as an option?

**Comment by indolering** [comment]
@redranger You could host the font yourself and lock it to a specific version.

**Comment by redranger** [comment]
Where would I get the original? Also, what was wrong with the original? I'd like to see the original to compare them again, as I need to decide for definite whether to remove this font, keep the new version, or host version 1 as you suggest. Thanks.

**Comment by inspire22** [comment]
Yeah this broke a bunch of pages on my website.  The new one is MUCH bolder.  How to download the old one for older pages?  Is it even possible since it has been updated at the source?

**Comment by redranger** [comment]
I think there is a bug with the updated font. The tops of some letters go above the top line of their container.

**Comment by m4rc1e** [comment]
@redranger screenshot or jsbin please.

Also, which OS and browser?

**Comment by redranger** [comment]
I'm using Firefox v.55.0.3 on Windows 10. I also tested it in the latest version of Chrome (v.61). See the attached screenshot that highlights the problem. I had a website where the tops of the letters was being cropped off because of this problem.
firefoxwindows10

**Comment by benjaminparis** [comment]
Hi, on Mac OSX 10.11.6, no matter what the browser is (Chrome, Safari, Firefox) the regular font (400) font is bolder and bigger than the bold one (700) as you can see. 
capture d ecran 2017-09-14 a 15 48 18

Here is the file loaded by Google Fonts API : 
```
@font-face {
  font-family: 'Josefin Sans';
  font-style: normal;
  font-weight: 400;
  src: local('Josefin Sans Regular'), local('JosefinSans-Regular'), url(https://fonts.gstatic.com/s/josefinsans/v11/xgzbb53t8j-Mo-vYa23n5hampu5_7CjHW5spxoeN3Vs.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
}
```
which isn't the regular one. Any idea ? 
Thanks

**Comment by m4rc1e** [comment]
@redranger do you have the family installed locally?

On Win 10, FF v55, I couldn't replicate this.

screen shot 2017-09-14 at 15 05 27

@benjaminparis duplicate of #1193

**Comment by redranger** [comment]
I don't have it installed locally. Go to that page in Chrome, then right click on the word Bold (don't select it, just right click on it), then select Inspect. You should see the tops of the letters 'l' and 'd' sticking out.

**Comment by m4rc1e** [comment]
> I'm using Firefox v.55.0.3 on Windows 10

> Go to that page in Chrome, then right click on the word Bold

Using Browser stack so can't right click. Highlighting LGTM on Win 10 Chrome 61

screen shot 2017-09-14 at 15 35 52

**Comment by redranger** [comment]
I mentioned both Firefox and Chrome if you look back. I'm guessing it will probably be an issue with most modern browsers. I'll leave the issue with you. I've removed the font as an option for users on my websites.

**Comment by thlinard** [comment]
Hi @m4rc1e 

I'm unable to reproduce the bug on Chrome 61 for Mac or Safari 10.1 (macOS 10.12.6), but it's visible on Firefox 55.0.3 for Mac, specially for the Bold weight.

The hheaAscent and sTypoAscender value of 750 doesn't seem right for the Bold (something like 789 would probably be better, or 793 in a "Webfont Strategy").

**Comment by m4rc1e** [comment]
@thlinard I can't change this. Vertical metrics visually have to be the same as the previous edition. By changing these values, users will get reflow issues.

**Comment by davelab6** [comment]
If its actually broken we should fix it.

**Comment by thlinard** [comment]
Yes, I understand. But have you see the documents I put in [Google Fonts Discussions](https://groups.google.com/d/msg/googlefonts-discuss/v4RUY3u2HW4/UuvYpIpIBAAJ)? Users already get reflow issues anyway with the version 2.00.

**Comment by davelab6** [comment]
Not vertical reflow though, which is more disruptive

**Comment by m4rc1e** [comment]
Apologies @thlinard, I mean't vertical reflow. We care about this because some DTP apps/text editors make it difficult/impossible to change the 'leading'.

**Comment by indolering** [comment]
@m4rc1e  Maybe it would be better to create a Josefin neue?  Google Fonts doesn't let one stick to a specific version, so these changes have lots of potentially breaking consequences.  That and my inability to get Mozilla to update the repos readme make me think it would be better to just fork 😦 .

**Comment by fastfasterfastest** [comment]
I see the same thing in Edge.
You see it when the text is selected AND the element does not have the focus.  E.g., double-click the word Regular to select it.  The selection has then a blue background and the text is white and the top of the letters are not "sticking out". Then click in the address bar to remove the focus and the selection changes to a gray background and the text is black and the top of the letters are "sticking out".  Another way do see it is to use F12 Developer tools and highlight the span element (with the text Regular) in the DOM Explorer - then you also see the top of the letters "sticking out".

> Go to that page in Chrome, then right click on the word Bold (don't select it, just right click on it), then select Inspect.

The key is NOT to select the word but to right-click on it and select Inspect.

**Comment by jkyeung** [comment]
Hi, I am having the exact same issue as #1193, namely that the current regular weight (400) is too bold for my use case and light (300) is too thin. To me, it's a big gap that would be nicely filled with 350. Would it be possible to include it as a static instance for download?

**Pull request merged**
