### PR TITLE
baloo: 1.443 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Thanks @girish-dalvi!

@davelab6 The ps name has changed in this version. This is also present in the other families. Shall we fix this before I pr the other families in this collection?

### CODE REVIEW

**Comment by davelab6** [comment]
@m4rc1e it should conform to our PS requirements.

**Comment by davelab6** [comment]
@girish-dalvi is the copyright string losing the URL intended?

**Comment by m4rc1e** [comment]
@davelab6 Ok, thank you.

@girish-dalvi could you do the following:
```
Full fontname:
Baloo --> Baloo Regular

Ps fontname:
Baloo -->Baloo-Regular
```
This problem exists on the other families as well.

**Comment by girish-dalvi** [comment]
@davelab6 No, I think this is a porting issue. We can add the URL and revert to the earlier OFL.

@m4rc1e Sure I can make the changes. Please confirm that the changes have to be in name id 4 & 6. Correct ?

**Comment by m4rc1e** [comment]
@girish-dalvi yes, in both 4,6. Make sure you do both the Mac and Win names.

I see the problem exists in the win names only.

**Comment by girish-dalvi** [comment]
@m4rc1e How do you want the name id 4 for fonts with spaces.
`Baloo Bhai Regular`
or
`BalooBhai Regular`

**Comment by m4rc1e** [comment]
```
Fullname: Baloo Bhai Regular
psname: BalooBhai-Regular
```

**Comment by girish-dalvi** [comment]
@m4rc1e Files have been updated. Please pull the new files from the repository. 
@davelab6 I have rolled back to the earlier copyright string in the new version. 

Since this is a naming fix and there is no functional change, we've not incremented the version.

**Comment by davelab6** [comment]
Sounds good

**Comment by m4rc1e** [comment]
Thanks @girish-dalvi, I've just pr'd the new fonts. They look good.

**Comment by m4rc1e** [comment]
@girish-dalvi! I need a DESCRIPTION.en_us.html file for Baloo Bhaijaan.

**Comment by davelab6** [comment]
Please make the description file from the others in the series for now

**Pull request merged**
