### PR TITLE
ofl/coiny: v1.00102 added. Updated vert metrics.

### LINKED ISSUE #1629: Coiny font has a wrong ascendent/decendent
Compare the google font verison of coiny, with the same font 'coiny', seems the google API one has a wrong descendent, which is higher than the baseline.

I thought it's special for this font, but I just compare with others, and found that google api's one is special for this, probably i just its wrong with this version.

### PR DESCRIPTION
**Pull request by laerm0**
Vertical metrics have been fixed/properly calculated. Fixes #1629

### CODE REVIEW

**Comment by m4rc1e** [comment]
@laerm0 see https://github.com/google/fonts/issues/1629#issuecomment-460973591.

**Comment by m4rc1e** [comment]
Please diff the upstream fonts before commencing work in the future.

**Comment by laerm0** [comment]
Coiny isn't in the upstream repos list.

**Comment by m4rc1e** [comment]
Add it to the upstream doc then.

**Comment by laerm0** [comment]
Well, I will, I just didn't know it existed until your comment.

**Comment by laerm0** [comment]
Hey @m4rc1e, upstream is in the doc now, but I won't fix there: OT is old and a mess and doesn't compile. Save that for another time.

**Pull request closed without merging**
