### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Akshayak603**

### CODE REVIEW

**Comment by fitojb** [comment]
This PR seems pointless.

**Comment by eliheuer** [comment]
Agreed, copy editing PRs should at least have a short description justifying the changes.

**Comment by fanninpm** [comment]
Taking a look at the deltas, the edits actually changed the meaning of the sentences.

**Comment by davelab6** [comment]
@Akshayak603 thanks for contributing :) 

While my style of English language may be unfamiliar to some, being British, I think these 2 edits are not improvements.

**Pull request closed without merging**
