### PR TITLE
Saira: Version 1.010 added

### PR DESCRIPTION
**Pull request by graphicore**
* Saira Version 1.010 taken from the upstream repo https://github.com/Omnibus-Type/Saira.git at commit https://github.com/Omnibus-Type/Saira/commit/be8dca06d2e106d3ee14e37b4de2e37d1a7feecb.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Love the fact we can now fetch upstream fonts and end up with a PR and qa results with a single cli command!

**Comment by graphicore** [comment]
Yes it's great. Though Saira needs some work :-D

BTW @m4rc1e is there a reason that there's no QA rendering for the italic? I'd expect a rendering but no diff, because italic is new,

**Comment by m4rc1e** [comment]
Diffbrowsers needs both styles to exist in the fonts_before and fonts_after sets. Perhaps we should generate browser previews if the updated family includes new styles?

**Comment by graphicore** [comment]
Yes, I think I'm doing that with the Dashboard. Though admittedly a fatal rendering flaw in new styles wouldn't cause that much harm.

https://github.com/googlefonts/fontbakery-dashboard/blob/5f389d4b2901ab00ad79d54447c873060a7063bc/containers/base/python/worker/diffbrowsers.py#L83-L109

**Comment by RosaWagner** [comment]
@graphicore I saw Omnibus pushed an new version in the upstream repo, maybe it is good to re-QA?

**Comment by graphicore** [comment]
@RosaWagner possible, but I'm on vacation right now. Thanks for the note.

**Comment by RosaWagner** [comment]
Enjoy the holidays ;)

**Comment by Omnibus-Type** [comment]
Hi @graphicore we hope that you are having a good vacation and a great rest! We are waiting for your return to continue on Saira's advance. In the meantime we leave the following queries as a note.
Currently have some questions about this project, along with the technical issues (corrected in the last version) we are interested in how the new Saira VF is going to be displayed. The current version (without Italics) was published in single-width: Normal, Semi Condensed, Condensed, Extra Condensed... How the new VF version (with Italics) will be published? Current single-width versions will be removed from the catalog? Will current widths be patched for ‘vintage’ users? This will be very helpful for our latest WIP project: Archivo VF. Many thanks for any clarification regarding our queries.

**Comment by RosaWagner** [comment]
Updated

## Saira: Version 1.100 added

---
 8cb4059: [gftools-packager] Saira: Version 1.100 added

* Saira Version 1.100 taken from the upstream repo https://github.com/Omnibus-Type/Saira at commit https://github.com/Omnibus-Type/Saira/commit/b0edbaa6955e047b134a85a667be194b45c6a6e8.

 63217f3: [gftools-packager] ofl/saira remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
@googlebot I consent.

**Comment by RosaWagner** [comment]
oslashactute is glitching because of some bracket tricks… So I have to fix that before pushing.

**Comment by Omnibus-Type** [comment]
We agree with fix these glitches, many thanks Rosa!

**Comment by RosaWagner** [comment]
Updated

## Saira: Version 1.100 added

---
 9210ecc: [gftools-packager] Saira: Version 1.100 added

* Saira Version 1.100 taken from the upstream repo https://github.com/Omnibus-Type/Saira at commit https://github.com/Omnibus-Type/Saira/commit/06e00b2f92f03a81cc234303af840eaf5eb47ed1.

 66fedd0: [gftools-packager] ofl/saira remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
On my local testing I have a beautiful cupcake, no regression and nice variation of the bracket glyphs.

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.7.33

<details>
<summary><b>[1] Saira-Italic[wdth,wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>
<details>
<summary><b>[1] Saira[wdth,wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 2 | 77 | 17 | 277 | 0 |
| 0% | 0% | 1% | 21% | 5% | 74% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Pull request merged**
