### PR TITLE
Anton: Version 2.116; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
f2d76ce: [gftools-packager] Anton: Version 2.116; ttfautohint (v1.8.3) added

* Anton Version 2.116; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/AntonFont at commit https://github.com/googlefonts/AntonFont/commit/80d0112310690cf8257d067aae7ccc9b6790a587.

 21ffe83: [gftools-packager] ofl/anton remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This Update to Version 2.116 made by Rodrigo Fuenzalida includes the extension of the character set to support African Latin alphabets. It also includes some fixes to character drawings, revised spacing and basic kerning.

There is a [regression on Vertical Metrics](https://github.com/rfuenzalida/AntonFont/issues/2#issuecomment-747808533), given the "Use of Typo Metrics" was not enabled in the previous version. So it was solved following the specification for those cases, as mentioned in the linked Issue where this was reviewed.

**Comment by m4rc1e** [comment]
Why was the unitsPerEm changed to 2048? We can see some vertical metrics values are off by 1 due to this.

**Comment by m4rc1e** [comment]
Apart from that, LGTM.

**Comment by vv-monsalve** [comment]
> Why has the upm changed to 2048? We can see some vertical metrics values are off by 1 due to this.

I don't know the reason for the change. @rfuenzalida could you confirm?

**Comment by rfuenzalida** [comment]
The source files had a UPM of 2048, I didn't want to change them to 1000 since I didn't know if they would cause conflicts.

**Comment by m4rc1e** [comment]
FE. Thanks!

**Pull request merged**
