### PR TITLE
Noto Naskh Arabic: Version 2.017 added

### PR DESCRIPTION
**Pull request by simoncozens**
7f84744: [gftools-packager] Noto Naskh Arabic: Version 2.017 added

* Noto Naskh Arabic Version 2.017 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
This release:

* Brings codepoint support up to Unicode 14
* Includes extensive re-engineering to fix bugs (particularly in minority languages), reduce glyphset size, and increase consistency with other Noto Arabic families

**Review by eliheuer — APPROVED** [review]
Looks good to me. The bismillah and medial heh are a big improvements!

@RosaWagner Do you think we can ignore the one vertical metrics fail? If so I think this is ready to merge.

**Comment by RosaWagner** [comment]
🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1405, but got 1069 instead [code: ascent]

@eliheuer @simoncozens 
I don't see what would be against updating the winAscent to match Ymax, 350units difference is quite important. Or maybe there is an outline issue? like a point super far out bounding the box.

**Comment by eliheuer** [comment]
Ok thanks, I think @khaledhosny updated the vertical metrics for Noto Sans Arabic recently. Maybe Khaled could update the vertical metrics for Noto Naskh Arabic and then Simon can push a new update to this PR and it should be good to go.

**Comment by khaledhosny** [comment]
> Ok thanks, I think @khaledhosny updated the vertical metrics for Noto Sans Arabic recently. Maybe Khaled could update the vertical metrics for Noto Naskh Arabic and then Simon can push a new update to this PR and it should be good to go.

I updated the win metrics for the three typefaces, Sans, Naskh, and Kufi.

**Comment by simoncozens** [comment]
Yeah, I just need to cut another release.

**Comment by simoncozens** [comment]
Updated

## Noto Naskh Arabic: Version 2.018 added

---
 e77f6e7: [gftools-packager] Noto Naskh Arabic: Version 2.018 added

* Noto Naskh Arabic Version 2.018 taken from the upstream repo https://github.com/notofonts/arabic.git at commit https://github.com/notofonts/arabic/commit/.

**Review by RosaWagner — APPROVED** [review]

**Comment by simoncozens** [comment]
This is *not* live. @emmamarichal Could notonaskharabic be added to push lists please? Thanks.

**Comment by vv-monsalve** [comment]
This is live now

**Pull request merged**
