### PR TITLE
Darumadrop Renaming

### PR DESCRIPTION
**Pull request by yanone**
unblocking #2864

### CODE REVIEW

**Comment by RosaWagner** [comment]
@yanone can you attach a QA in comment? The gh-action doesn't seem to work on this PR.

**Comment by yanone** [comment]
## Fontbakery report

Fontbakery version: 0.8.5.dev18+g3e56c493

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Check README.md has a sample image.</summary>

* [com.google.fonts/check/repo/sample_image](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/sample_image)
<pre>--- Rationale ---
In order to showcase what a font family looks like, the project&#x27;s README.md file
should ideally include a sample image and highlight it in the upper portion of
the document, no more than 10 lines away from the top of the file.</pre>

* 💔 **ERROR** Failed with AttributeError: 'NoneType' object has no attribute 'split'

</details>
<br>
</details>
<details>
<summary><b>[12] DarumadropOne-Regular.ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Check `Google Fonts Latin Core` glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
<pre>--- Rationale ---
Google Fonts expects that fonts in its collection support at least the minimal
set of characters defined in the `GF-latin-core` glyph-set.</pre>

* 💔 **ERROR** Failed with TypeError: name() argument 1 must be a unicode character, not int

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check OFL body text is correct.</summary>

* [com.google.fonts/check/license/OFL_body_text](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/license/OFL_body_text)
<pre>--- Rationale ---
Check OFL body text is correct. Often users will accidently delete parts of the
body text.</pre>

* 🔥 **FAIL** The OFL.txt body text is incorrect. Please use https://github.com/googlefonts/Unified-Font-Repository/blob/main/OFL.txt as a template. You should only modify the first line. [code: incorrect-ofl-body-text]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---
All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.
If using GlyphsApp or UFOs, ligature carets can be defined as anchors with names
starting with &#x27;caret_&#x27;. These can be compiled with fontmake as of version
v2.4.0.</pre>

* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---
Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> On a family update, the DESCRIPTION.en_us.html file should ideally also be updated.</summary>

* [com.google.fonts/check/description/family_update](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/family_update)
<pre>--- Rationale ---
We want to ensure that any significant changes to the font family are properly
mentioned in the DESCRIPTION file.
In general, it means that the contents of the DESCRIPTION.en_us.html file will
typically change if when font files are updated. Please treat this check as a
reminder to do so whenever appropriate!</pre>

* ⚠ **WARN** The DESCRIPTION.en_us.html file in this family has not changed in comparison to the latest font release on the google/fonts github repo.
Please consider mentioning note-worthy improvements made to the family recently. [code: description-not-updated]

</details>
<details>
<summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table.</summary>

* [com.google.fonts/check/meta/script_lang_tags](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags)
<pre>--- Rationale ---
The OpenType &#x27;meta&#x27; table originated at Apple. Microsoft added it to OT with
just two DataMap records:
- dlng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font is designed for
- slng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font supports
The slng structure is intended to describe which languages and scripts the font
overall supports. For example, a Traditional Chinese font that also contains
Latin characters, can indicate Hant,Latn, showing that it supports Hant, the
Traditional Chinese variant of the Hani script, and it also supports the Latn
script
The dlng structure is far more interesting. A font may contain various glyphs,
but only a particular subset of the glyphs may be truly &quot;leading&quot; in the design,
while other glyphs may have been included for technical reasons. Such a
Traditional Chinese font could only list Hant there, showing that it’s designed
for Traditional Chinese, but the font would omit Latn, because the developers
don’t think the font is really recommended for purely Latin-script use.
The tags used in the structures can comprise just script, or also language and
script. For example, if a font has Bulgarian Cyrillic alternates in the locl
feature for the cyrl BGR OT languagesystem, it could also indicate in dlng
explicitly that it supports bul-Cyrl. (Note that the scripts and languages in
meta use the ISO language and script codes, not the OpenType ones).
This check ensures that the font has the meta table containing the slng and dlng
structures.
All families in the Google Fonts collection should contain the &#x27;meta&#x27; table.
Windows 10 already uses it when deciding on which fonts to fall back to. The
Google Fonts API and also other environments could use the data for smarter
filtering. Most importantly, those entries should be added to the Noto fonts.
In the font making process, some environments store this data in external files
already. But the meta table provides a convenient way to store this inside the
font file, so some tools may add the data, and unrelated tools may read this
data. This makes the solution much more portable and universal.</pre>

* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---
Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will only
differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.
However, a quotedbl should have 2 contours, unless the font belongs to a display
family.
This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.</pre>

* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

 - Glyph name: R	Contours detected: 3	Expected: 1 or 2
 - Glyph name: V	Contours detected: 2	Expected: 1
 - Glyph name: a	Contours detected: 3	Expected: 2
 - Glyph name: multiply	Contours detected: 3	Expected: 1
 - Glyph name: ograve	Contours detected: 4	Expected: 3
 - Glyph name: uni030B	Contours detected: 1	Expected: 2
 - Glyph name: arrowdblboth	Contours detected: 1	Expected: 2
 - Glyph name: uni2225	Contours detected: 1	Expected: 2
 - Glyph name: equivalence	Contours detected: 2	Expected: 3
 - Glyph name: R	Contours detected: 3	Expected: 1 or 2 
 - And 10 more.

Use -F or --full-lists to disable shortening of long lists.
 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does the font contain chws and vchw features?</summary>

* [com.google.fonts/check/cjk_chws_feature](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/cjk_chws_feature)
<pre>--- Rationale ---
The W3C recommends the addition of chws and vchw features to CJK fonts to
enhance the spacing of glyphs in environments which do not fully support JLREQ
layout rules.
The chws_tool utility (https://github.com/googlefonts/chws_tool) can be used to
add these features automatically.</pre>

* ⚠ **WARN** chws feature not found in font. Use chws_tool (https://github.com/googlefonts/chws_tool) to add it. [code: missing-chws-feature]
* ⚠ **WARN** vchw feature not found in font. Use chws_tool (https://github.com/googlefonts/chws_tool) to add it. [code: missing-vchw-feature]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/dsig](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/dsig.html#com.google.fonts/check/dsig)
<pre>--- Rationale ---
Microsoft Office 2013 and below products expect fonts to have a digital
signature declared in a DSIG table in order to implement OpenType features. The
EOL date for Microsoft Office 2013 products is 4/11/2023. This issue does not
impact Microsoft Office 2016 and above products.
As we approach the EOL date, it is now considered better to completely remove
the table.
But if you still want your font to support OpenType features on Office 2013,
then you may find it handy to add a fake signature on a placeholder DSIG table
by running one of the helper scripts provided at
https://github.com/googlefonts/gftools
Reference: https://github.com/googlefonts/fontbakery/issues/1845</pre>

* ⚠ **WARN** This font has a digital signature (DSIG table) which is only required - even if only a placeholder - on old programs like MS Office 2013 in order to work properly.
The current recommendation is to completely remove the DSIG table. [code: found-DSIG]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class.</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---
Mark characters should be in the GDEF mark glyph class.</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 uni20DD (U+20DD) [code: mark-chars]

</details>
<details>
<summary>⚠ <b>WARN:</b> Do any segments have colinear vectors?</summary>

* [com.google.fonts/check/outline_colinear_vectors](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_colinear_vectors)
<pre>--- Rationale ---
This check looks for consecutive line segments which have the same angle. This
normally happens if an outline point has been added by accident.
This check is not run for variable fonts, as they may legitimately have colinear
vectors.</pre>

* ⚠ **WARN** The following glyphs have colinear vectors:
	* D (U+0044): L<<45.0,86.0>--<44.0,176.0>> -> L<<44.0,176.0>--<44.0,177.0>>
	* eight (U+0038): L<<325.0,178.0>--<319.0,192.0>> -> L<<319.0,192.0>--<312.0,206.0>>
	* ntilde (U+00F1): L<<458.0,296.0>--<463.0,277.0>> -> L<<463.0,277.0>--<465.0,268.0>>
	* uni307B (U+307B): L<<652.0,304.0>--<652.0,304.0>> -> L<<652.0,304.0>--<652.0,304.0>> and uni30EB (U+30EB): L<<595.0,396.0>--<598.0,365.0>> -> L<<598.0,365.0>--<598.0,337.0>> [code: found-colinear-vectors]

</details>
<details>
<summary>⚠ <b>WARN:</b> Do outlines contain any jaggy segments?</summary>

* [com.google.fonts/check/outline_jaggy_segments](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_jaggy_segments)
<pre>--- Rationale ---
This check heuristically detects outline segments which form a particularly
small angle, indicative of an outline error. This may cause false positives in
cases such as extreme ink traps, so should be regarded as advisory and backed up
by manual inspection.</pre>

* ⚠ **WARN** The following glyphs have jaggy segments:
	* g (U+0067): B<<473.5,92.0>-<472.0,87.0>-<470.0,79.0>>/B<<470.0,79.0>-<470.0,81.0>-<469.5,80.0>> = 14.036243467926484
	* uni301D (U+301D): L<<268.0,585.0>--<267.0,587.0>>/L<<267.0,587.0>--<274.0,569.0>> = 5.314545669944662
	* uni3056 (U+3056): L<<747.0,753.0>--<746.0,753.0>>/B<<746.0,753.0>-<750.0,752.0>-<751.0,749.0>> = 14.036243467926484
	* uni3069 (U+3069): L<<398.0,437.0>--<421.0,442.0>>/B<<421.0,442.0>-<417.0,442.0>-<423.5,443.0>> = 12.2647737278924
	* uni3080 (U+3080): B<<367.0,667.0>-<372.0,668.0>-<376.0,669.0>>/L<<376.0,669.0>--<375.0,669.0>> = 14.036243467926484
	* uni308F (U+308F): B<<498.5,31.0>-<499.0,31.0>-<499.0,32.0>>/B<<499.0,32.0>-<500.0,24.0>-<496.5,16.5>> = 7.125016348901757
	* uni30AF (U+30AF): L<<64.0,293.0>--<46.0,317.0>>/L<<46.0,317.0>--<47.0,316.0>> = 8.13010235415596
	* uni30F9 (U+30F9): L<<669.0,52.0>--<672.0,48.0>>/L<<672.0,48.0>--<669.0,51.0>> = 8.13010235415596 and w (U+0077): B<<317.0,45.5>-<317.0,33.0>-<306.0,20.0>>/B<<306.0,20.0>-<307.0,21.0>-<305.5,19.0>> = 4.763641690726144 [code: found-jaggy-segments]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 2 | 1 | 10 | 52 | 9 | 148 | 0 |
| 1% | 0% | 5% | 23% | 4% | 67% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by yanone** [comment]
I checked the FAIL about OFL.txt. but can't find any mistakes.

**Comment by yanone** [comment]
[qa_daruma.zip](https://github.com/google/fonts/files/7828099/qa_daruma.zip)

**Comment by yanone** [comment]
Why was this blocked? I can't find any mention of a reason

**Comment by RosaWagner** [comment]
This is part of the japanese fonts that show tofu because support only kana

**Pull request merged**
