### PR TITLE
Fix total download filesize estimate

### PR DESCRIPTION
**Pull request by graingert**
It was 8 times bigger than I expected!

### CODE REVIEW

**Comment by m4rc1e** [comment]
I think you've just made the best pr ever sir :-)

**Comment by graingert** [comment]
@m4rc1e I mean it's technically correct already, because 300MB >= 300Mb. But I'd rather a nearer estimate.

**Comment by graingert** [comment]
@m4rc1e nah, this is better: https://github.com/microscaling/imagelayers-graph/pull/89

**Comment by graingert** [comment]
@m4rc1e I mean it's technically correct already, because 300MB >= 300Mb. But I'd rather a nearer estimate.

**Comment by m4rc1e** [comment]
ahaha love it. Sadly, this has made my day.

It reminds me of [this](http://edition.cnn.com/TECH/space/9909/30/mars.metric.02/)

@davelab6 lets merge this.

**Comment by davelab6** [comment]
Thanks @graingert :)

**Pull request merged**
