### PR TITLE
roboto: v2.136 added

### PR DESCRIPTION
**Pull request by m4rc1e**
The version of Roboto currently hosted on fonts.google.com is v2.000. This pr is for the lastest release, v2.136, https://github.com/google/roboto/releases. The Roboto [repository](https://github.com/google/roboto) is currently 2 commits ahead of this release. The webfonts were generated from the same commit which created v2.136. I haven't done any hot fixes to the web fonts. I've simply followed the build instructions. The current v2.000 webfonts are released in the same manner.

### diff summary:
Roboto-Regular.ttf
    version: 2.001101 vs 2.136
    size: 162876 vs 171676 (8800 bytes bigger)
    tables: changed glyf(+5686), GPOS(+2984), GSUB(-600), name(+398), hmtx(+176)
    glyphs: 1250 vs 1294 (44 more glyphs)

## Size diff
|Font|v2.136 (kb)|v2.136 (with web subsetting)|% subset vs v2.136|v2.000 (web old)|% 2.000 webfonts vs 2.136 webfonts|
| ------ | ------ | ------ | ------ | ------ | ------ |
|Roboto-Black.ttf|522|167|32.08%|159|105.32%|
|Roboto-BlackItalic.ttf|538|173|32.23%|161|107.70%|
|Roboto-Bold.ttf|528|167|31.58%|158|105.54%|
|Roboto-BoldItalic.ttf|546|171|31.29%|159|107.45%|
|Roboto-Italic.ttf|544|170|31.22%|157|108.19%|
|Roboto-Light.ttf|530|166|31.40%|158|105.33%|
|Roboto-LightItalic.ttf|550|172|31.36%|162|106.47%|
|Roboto-Medium.ttf|525|168|32.01%|158|106.35%|
|Roboto-MediumItalic.ttf|547|173|31.58%|161|107.28%|
|Roboto-Regular.ttf|526|168|31.87%|159|105.44%|
|Roboto-Thin.ttf|533|168|31.50%|159|105.58%|
|Roboto-ThinItalic.ttf|548|172|31.42%|164|104.98%|

**Mac names have been added**

old v2.00

|Font|platformID|encodingID|languageID|nameID|nameString|
| ------ | ------ | ------ | ------ | ------ | ------ |
|Roboto-Regular.ttf|3|1|1033|0|Copyright 2011 Google Inc. All Rights Reserved.|
|Roboto-Regular.ttf|3|1|1033|1|Roboto|
|Roboto-Regular.ttf|3|1|1033|2|Regular|
|Roboto-Regular.ttf|3|1|1033|3|Roboto|
|Roboto-Regular.ttf|3|1|1033|4|Roboto|
|Roboto-Regular.ttf|3|1|1033|5|Version 2.001101; 2014|
|Roboto-Regular.ttf|3|1|1033|6|Roboto-Regular|
|Roboto-Regular.ttf|3|1|1033|7|Roboto is a trademark of Google.|
|Roboto-Regular.ttf|3|1|1033|9|Google|
|Roboto-Regular.ttf|3|1|1033|11|Google.com|
|Roboto-Regular.ttf|3|1|1033|12|Christian Robertson|
|Roboto-Regular.ttf|3|1|1033|13|Licensed under the Apache License, Version 2.0|
|Roboto-Regular.ttf|3|1|1033|14|http://www.apache.org/licenses/LICENSE-2.0|

new 2.136

|Font|platformID|encodingID|languageID|nameID|nameString|
| ------ | ------ | ------ | ------ | ------ | ------ |
|Roboto-Regular.ttf|1|0|0|0|Copyright 2011 Google Inc. All Rights Reserved.|
|Roboto-Regular.ttf|1|0|0|1|Roboto|
|Roboto-Regular.ttf|1|0|0|2|Regular|
|Roboto-Regular.ttf|1|0|0|3|Roboto|
|Roboto-Regular.ttf|1|0|0|4|Roboto|
|Roboto-Regular.ttf|1|0|0|5|Version 2.136; 2017|
|Roboto-Regular.ttf|1|0|0|6|Roboto-Regular|
|Roboto-Regular.ttf|1|0|0|7|Roboto is a trademark of Google.|
|Roboto-Regular.ttf|1|0|0|9|Google|
|Roboto-Regular.ttf|1|0|0|11|Google.com|
|Roboto-Regular.ttf|1|0|0|12|Christian Robertson|
|Roboto-Regular.ttf|1|0|0|13|Licensed under the Apache License, Version 2.0|
|Roboto-Regular.ttf|1|0|0|14|http://www.apache.org/licenses/LICENSE-2.0|
|Roboto-Regular.ttf|3|1|1033|0|Copyright 2011 Google Inc. All Rights Reserved.|
|Roboto-Regular.ttf|3|1|1033|1|Roboto|
|Roboto-Regular.ttf|3|1|1033|2|Regular|
|Roboto-Regular.ttf|3|1|1033|3|Roboto|
|Roboto-Regular.ttf|3|1|1033|4|Roboto|
|Roboto-Regular.ttf|3|1|1033|5|Version 2.136; 2017|
|Roboto-Regular.ttf|3|1|1033|6|Roboto-Regular|
|Roboto-Regular.ttf|3|1|1033|7|Roboto is a trademark of Google.|
|Roboto-Regular.ttf|3|1|1033|9|Google|
|Roboto-Regular.ttf|3|1|1033|11|Google.com|
|Roboto-Regular.ttf|3|1|1033|12|Christian Robertson|
|Roboto-Regular.ttf|3|1|1033|13|Licensed under the Apache License, Version 2.0|
|Roboto-Regular.ttf|3|1|1033|14|http://www.apache.org/licenses/LICENSE-2.0|

**Design modifications**
roboto-design-mods

**More c2sc glyphs**

## Resolved issues since v2.000:
*U+20A9 (Korean Won Sign) is too wide (also fixes yen):*
https://github.com/google/roboto/issues/45

*Greek: Lowercase chi should probably be differentiated from lowercase Latin x:*
https://github.com/google/roboto/issues/18

*Issue with ligatures*
https://github.com/google/roboto/issues/189

More here:
https://github.com/google/roboto/issues?q=is%3Aissue+is%3Aclosed

## Upstream Repo:
pr needs merging https://github.com/google/roboto/pull/238

This pr will subset the webfonts when running `make web`

## API:
Greek ext was included in the original METADATA.pb. Its been removed which should solve #411

## Win 7 hinting:
roboto-hint-regular-8
roboto-hint-regular11
roboto-hint-regular-16
roboto-hint-regular-18
roboto-hint-regular-21

Pixel jumps occur for the x-height and cap height. Each weight has the same jumps.

Jumps occurred up to 27ppem:
roboto-hint-regular-27

## Live previews (Win 7 Chrome 56):

Roboto is used in Android and Material Design. [Font dragr](http://fontdragr.com) has been used to swap the old Roboto with the new. 

http://developers.google.com
roboto-developers google com
Clear 1px x-height jump

http://wallet.google.com
roboto-google-wallet
Ok

http://analytics.google.com
roboto-analytics

https://material.angularjs.org/latest/CSS/typography
roboto-material-headings

### CODE REVIEW

**Comment by davelab6** [comment]
https://github.com/google/roboto/issues/236 also related to this

**Comment by davelab6** [comment]
@graphicore why is travis failing this? :)

**Comment by m4rc1e** [comment]
@davelab6 Travis cannot find a rake file (ruby equivalent of a Makefile)

https://travis-ci.org/google/fonts/builds/211781749

**Comment by graphicore** [comment]
Because, when I activated Travis for the repository there were no tests available, nor a travis.yaml file. Travis fails because it is not configured in this branch. Now a `git fetch master; git rebase master; git push -f`would solve this, but it is not a problem either. The tests are only concerned with the contents of `tools/encodings`.

From the build log, line 6:
> `Could not find .travis.yml, using standard configuration.`

**Comment by graphicore** [comment]
@m4rc1e you were faster :-)

**Comment by m4rc1e** [comment]
For better referencing, lets move this into its own issue.

**Comment by thlinard** [comment]
Hi @davelab6 

Where are you found extended Greek characters in Roboto (any version) for your commit:
" apache/roboto/METADATA.pb keep greek-ext
davelab6 committed on GitHub 12 hours ago
We must not remove subsets that exist!"
?

https://graphicore.github.io/mdlFontSpecimen/html/language-coverage-details.html
Roboto Regular
Charset Coverage Details
Greek Extended 0%

**Comment by m4rc1e** [comment]
@thlinard We had a complaint in #411, which led me to believe we should remove subsets which don't actually exist.

I will reinclude it.

**Comment by davelab6** [comment]
> Where are you found extended Greek characters in Roboto (any version) for your commit:

I don't find any, but since the subset was enabled, it must remain enabled.

**Comment by thlinard** [comment]
> since the subset was enabled, it must remain enabled.

Isn't that a bit too Kafkaesque?

**Comment by davelab6** [comment]
An internal lint says that Roboto-Black.ttf and Roboto-BlackItalic.ttf have `fsSelection` bold value of 1, but should be 0

**Comment by davelab6** [comment]
Hmm, this is checked for in https://github.com/googlefonts/fontbakery/blob/12257aa92a6dc927849309de048088dfbd66d5f3/checks.py#L742-L747

**Comment by m4rc1e** [comment]
@davelab6 We can't really make these fonts comply with our fb spec. They must comply with the previous fonts. The v2.000 Black weights had the fsSelection set to bold. We must keep this, the stakes are too high.

**Comment by davelab6** [comment]
(Offlinst Marc proposed to update the fsSelection for the Black files in the web fonts post-processing script, so only the web fonts are effected.)

**Pull request merged**
