### PR TITLE
Sofia Sans: Version 4.102 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
bea4999: [gftools-packager] Sofia Sans: Version 4.102 added

* Sofia Sans Version 4.102 taken from the upstream repo https://github.com/vv-monsalve/Sofia-Sans at commit https://github.com/vv-monsalve/Sofia-Sans/commit/0edd730d634463701f6d15ed4d4b018a7ecdc580.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Hi @RosaWagner 
This PR updates our previous test-PR #4333 to reduce the width ranges from `UltraCondensed - Normal` to `ExtraCondensed to Normal` so that the API doesn't produce undesired default  `ExtraCondensed`.

**Comment by vv-monsalve** [comment]
Updated

## Sofia Sans: Version 4.102 added

---
 af10a73: [gftools-packager] Sofia Sans: Version 4.102 added

* Sofia Sans Version 4.102 taken from the upstream repo https://github.com/vv-monsalve/Sofia-Sans at commit https://github.com/vv-monsalve/Sofia-Sans/commit/0edd730d634463701f6d15ed4d4b018a7ecdc580.

**Comment by RosaWagner** [comment]
@m4rc1e CI is curiously not triggered on Vivi's PR

**Comment by vv-monsalve** [comment]
> @m4rc1e CI is curiously not triggered on Vivi's PR

I've closed this PR to try another one from scratch #4409 bit it the QA action is still not triggered. 
When I updated another PR, My Soul one, it wasn't deployed at first either, but then it worked. 
So now is less clear what could be the cause of this.

@m4rc1e Am I missing something here?

**Pull request closed without merging**
