### PR TITLE
Edu AU VIC WA NT Hand: Version 1.001 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/SorkinType/VICWANTSchoolhandAustralia at commit https://github.com/SorkinType/VICWANTSchoolhandAustralia/commit/88099a2e2d47e222cb62441730a2bc1c082754e1.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [x] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
@m4rc1e I'm not sure why we're seeing the tags FATAL here. It's fine locally.

**Comment by emmamarichal** [comment]
Hey @simoncozens! cc @EbenSorkin 
I noticed some few things that could be improved:

**SPACING**

- The numbers spacing look a bit weird
Screenshot 2024-05-08 at 14 54 14

- the `space` looks very tight, is it intentional? (between 'mona' and 'graduate')
Screenshot 2024-05-08 at 15 07 04

- spacing issue between 't' and 'e' in both masters
Screenshot 2024-05-08 at 15 07 39
Screenshot 2024-05-08 at 15 07 44

**DESIGN**
- The caron isn't the good one for dcaron, tcaron, lcaron 
Screenshot 2024-05-08 at 15 14 45

- tcedilla placement could be improved
Screenshot 2024-05-08 at 15 15 36

- not a big issue, but if we want to be perfect, `f` and `t` bars could be aligned :)
Screenshot 2024-05-08 at 14 59 42


### Fontbakery checks:
I'm ok to onboard the font like this, but if we want to avoid some WARN, those ones could be solved quite easily:

**⚠️ WARN** Check math signs have the same width.
**⚠️ WARN** Font has **proper** whitespace glyph names?
**⚠️ WARN** Are there caret positions declared for every ligature?
**⚠️ WARN** Check font follows the Google Fonts vertical metric schema (except if the font has special v-metrics, according to the design)

**Comment by EbenSorkin** [comment]
This looks appalling. IDK why it is like that but I will look today.

-e.

**Comment by EbenSorkin** [comment]
It looks like your version isn't right because
[image: image.png]
This is version is
[image: image.png]

and is here

https://github.com/SorkinType/VICWANTSchoolhandAustralia

Where did the stuff you found come from?

-e.

**Comment by EbenSorkin** [comment]
making sure Simon and Emma see this

**Comment by emmamarichal** [comment]
@EbenSorkin @simoncozens 
Actually this is weird: when I open the font file in Glyphs for example, I see the good version.
But in the proofs generated by the CI, the bad version appears. So I don't know where it comes from.

**Comment by simoncozens** [comment]
Probably a build chain issue, I will investigate.

**Comment by EbenSorkin** [comment]
Ok I’ll have a look at those other issues then

**Comment by EbenSorkin** [comment]
I think I have fixed all of these. Please have a look at the artifact of
this:
https://github.com/SorkinType/VICWANTSchoolhandAustralia/actions/runs/9006727899

I think it will make sense to observe some text because I redid kerning in
Kern on ad there can sometimes be odd results here & there.

-e.

**Comment by emmamarichal** [comment]
@simoncozens That fail appeared with the new version: 🔥 FAIL Ensure dotted circle glyph is present and can attach marks.

**Comment by simoncozens** [comment]
It's a false positive in this case; caroncomb.alt is not encoded and can't be accessed without a base glyph, so it can never end up on a dotted circle.

**Comment by emmamarichal** [comment]
@EbenSorkin @simoncozens 
Sorry, I've just notified the following cases. I'd rather check with you, knowing that this is the first PR in a long series.

- the cedilla in the 's' looks a bit too much on the right?
Screenshot 2024-05-09 at 10 34 01

- cedilla placement
Screenshot 2024-05-09 at 10 33 56

- hbar and dcroat bars placement.
Screenshot 2024-05-09 at 10 33 40

- should be more like this:
Screenshot 2024-05-09 at 10 37 15

**Comment by simoncozens** [comment]
>  I'd rather check with you, knowing that this is the first PR in a long series.

Good, thank you! @EbenSorkin, these (particularly cedilla placement) seem to have changed since the last version!

**Comment by vv-monsalve** [comment]
Hi @simoncozens, @EbenSorkin 

The space still looks a bit tight. The separation between words is sometimes barely noticeable. e.g.: "Alle mennesker er født frie og likeverdige og verdige" or "die zware tas mee te slepen?"


Screen Shot 2024-05-23 at 14 09 07

Screen Shot 2024-05-23 at 13 55 29

<br>

- `t` looks a bit short. Inspecting the font it is indeed some units above the baseline.
Screen Shot 2024-05-23 at 13 58 35
Screen Shot 2024-05-23 at 13 58 21

<br>

- Please review the spacing or kerning here
Screen Shot 2024-05-23 at 13 55 44

<br>

On the FB report:

> 🔥 FAIL Checking with fontTools.ttx

Simon, please inspect the reported Fail.

**Comment by EbenSorkin** [comment]
So I should explain again that Dave said not to worry about performance outside of English for these because we didn't have budget to push them past that. However (maybe foolishly) I added some letters that go beyond English so that when/if we do come back to this it will be easier to keep going. But that did mean that there is for example an "n.cv02" but no "ntilde.cv02". 

Weirdly too the designer did want the letters to float above the baseline because that's what teachers expect in AU apparently. Not so great for rendering but she explained it makes the baseline something you can stroke more easily. The compromise I tried to work in was to have letters just touch but not to overshoot the baseline. We might decide that since we will be pulling in a stroke feature of our own that we can have conventional overshoots. I am not feeling doctrinaire about it. 

I have opened the wordspace wider, dcroat and hbar have the same height. I added a bit more kerning and and made a couple of joins smoother.

Please let me know if this is sufficient or if you want to discuss any of the the above.

**Comment by vv-monsalve** [comment]
> So I should explain again that Dave said not to worry about performance outside of English for these because we didn't have budget to push them past that. However (maybe foolishly) I added some letters that go beyond English so that when/if we do come back to this it will be easier to keep going. But that did mean that there is for example an "n.cv02" but no "ntilde.cv02".

The last feedback did not request adding accented letters. The English focus on these fonts is clear. That's why I didn't mention, e.g., the tofu on the `ele geminada`. However, everything included in the font should work, including the `lcaron` spacing.

> Weirdly too the designer did want the letters to float above the baseline because that's what teachers expect in AU apparently. Not so great for rendering but she explained it makes the baseline something you can stroke more easily. The compromise I tried to work in was to have letters just touch but not to overshoot the baseline.

The context of why the glyphs do not have an overshoot is appreciated. However, when reviewing the font before reporting the above, the `i` is touching the baseline, while the t does not. This difference seems to be enough to impact the rendering, where the `t` looks shorter than the `i`.

Screen Shot 2024-05-30 at 12 58 43

<br>
<br>

> We might decide that since we will be pulling in a stroke feature of our own that we can have conventional overshoots. I am not feeling doctrinaire about it.

The decision around this is up to you. Please let us know how you would like to proceed.

**Comment by simoncozens** [comment]
I've updated the PR with Eben's latest changes.

**Comment by emmamarichal** [comment]
@simoncozens 

The nbspace hasn't been updated at the same time (I guess it's an automatic spacing, but it has been forgotten here)

🔥 FAIL Space and non-breaking space have the same width?

**Comment by EbenSorkin** [comment]
I thought I fixed that. Now I'm concerned I'm pushing to the wrong branch.

**Comment by simoncozens** [comment]
@EbenSorkin Still an issue in the bold with the latest build. The caron problem is because we are decomposing it. I've added some contextual kern magic to fix, and also solved the gj clash.

@emmamarichal Latest build attached.

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
