### PR TITLE
Lateef: Version 4.200 added

### PR DESCRIPTION
**Pull request by eliheuer**
016aa52: [gftools-packager] Lateef: Version 4.100 added

* Lateef Version 4.100 taken from the upstream repo https://github.com/silnrsi/font-lateef at commit https://github.com/silnrsi/font-lateef/commit/.

### CODE REVIEW

**Comment by eliheuer** [comment]
Updating  to 4.100 from 4.000 as suggested in this issue: https://github.com/google/fonts/issues/6615
Not sure where all the fails came from in this update, looking into it now.

**Comment by RosaWagner** [comment]
@eliheuer we have a special agreement with SIL to ignore the FAILS. 

The only thing we need to check before merging is if the additional glyphs are already included in the subset defined here: https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/arabic_unique-glyphs.nam, and it the case, so good to merge.

**Review by RosaWagner — APPROVED** [review]

**Comment by RosaWagner** [comment]
Although when I linked the issue to the PR I saw the 4.2 was ready, so will wait for you to update the PR before merging.

**Comment by eliheuer** [comment]
I can confirm that all the new codepoints are Arabic ligatures that are in the [arabic_unique-glyphs.nam](https://github.com/googlefonts/glyphsets/blob/main/Lib/glyphsets/encodings/arabic_unique-glyphs.nam) file

**Comment by eliheuer** [comment]
Updated

## Lateef: Version 4.200 added

---
 1d555c6: [gftools-packager] Lateef: Version 4.200 added

* Lateef Version 4.200 taken from the upstream repo https://github.com/silnrsi/font-lateef at commit https://github.com/silnrsi/font-lateef/commit/.

**Pull request merged**
