### PR TITLE
Noto Sans Lydian: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
06337c1: [gftools-packager] Noto Sans Lydian: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Lydian Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/lydian.git at commit https://github.com/notofonts/lydian/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
This release adds a combining dot below glyph (#1).
```

**Comment by eliheuer** [comment]
@simoncozens This has one FontBakery fail: 
🔥 FAIL: Ensure dotted circle glyph is present and can attach marks. ([com.google.fonts/check/dotted_circle](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/%3CSection:%20Shaping%20Checks%3E.html#com.google.fonts/check/dotted_circle))
🔥 FAIL No dotted circle glyph present and font uses a complex shaper [code: missing-dotted-circle-complex]

Is there a good reason to ignore this, or should this be fixed?

**Review by eliheuer — CHANGES_REQUESTED** [review]
@simoncozens This looks ok to merge to me. We just need the one FontBakery fail fixed, or an explanation of why is should be ignored.

**Review by RosaWagner — APPROVED** [review]

**Review by eliheuer — APPROVED** [review]
Looks good to me. I will merge this soon.

**Pull request merged**
