### PR TITLE
Tac One Article: update <img> to <video> for mp4 formats

### PR DESCRIPTION
**Pull request by emmamarichal**
Fix that bug:

Screenshot 2024-04-17 at 12 10 57

@simoncozens 
not sure if I have to add all of this?

```
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
```

### CODE REVIEW

**Comment by simoncozens** [comment]
I think technically you probably want

```
<video autoplay muted>
  <source src="movie.mp4" type="video/mp4">
</video>
```

to work on most browsers.

**Comment by emmamarichal** [comment]
@simoncozens I corrected, but not sure about the syntax. Feel free to correct it!

**Comment by emmamarichal** [comment]
Maybe I didn't need to repeat it for each, but I let it like this to choose the right order

**Comment by emmamarichal** [comment]
It works, I merge this PR then

**Comment by emmamarichal** [comment]
@vv-monsalve fyi, I've updated the Tac One article with the correct html syntax so that it displays correctly on every browser.

**Comment by vv-monsalve** [comment]
Superseded by #7576. Changes will be followed by that PR.

**Pull request merged**
