### PR TITLE
Alumni Sans Inline: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
dee3616: [gftools-packager] Alumni Sans Inline: Version 1.010; ttfautohint (v1.8.3) added

* Alumni Sans Inline Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/alumni-sans-inline at commit https://github.com/googlefonts/alumni-sans-inline/commit/bc0b167659b8e9e2a1e204c75edf0c849371c808.

 32eea47: [gftools-packager] ofl/alumnisansinline remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@davelab6 could you please turn `Alumni-Sans-Inline` the repository public?

**Comment by vv-monsalve** [comment]
Updated

## Alumni Sans Inline: Version 1.010; ttfautohint (v1.8.3) added

---
 3ca6274: [gftools-packager] Alumni Sans Inline: Version 1.010; ttfautohint (v1.8.3) added

* Alumni Sans Inline Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/alumni-sans-inline at commit https://github.com/googlefonts/alumni-sans-inline/commit/43bd00d1daa048b82c2db34d3ad79a9f22acd5e1.

 30509cf: [gftools-packager] ofl/alumnisansinline remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
The weight is super heavy, do we have confirmation somewhere that there won't be any addition of weight to this family (and therefore justify the absence of "One" in the family name) ?

**Comment by vv-monsalve** [comment]
> The weight is super heavy, do we have confirmation somewhere that there won't be any addition of weight to this family (and therefore justify the absence of "One" in the family name)?

There is not a written confirmation if that is the question. From the current TypeSetIt scope of work, there are no plans for more Inline weights to come. 

Now, under the Open Source logic, theoretically, anyone in the future could contribute by adding more weights, so perhaps it could be a case on adding the "one" particle if that is the practice for these cases.

Perhaps @davelab6 could confirm.

**Comment by RosaWagner** [comment]
Posting an image to facilitate decision about appending "one" or not:

Capture d’écran 2022-01-19 à 11 16 37

I thing we should do, cc @davelab6 or @m4rc1e for confirmation.

**Comment by vv-monsalve** [comment]
Following this in #4331. Closing this here.

**Pull request closed without merging**
