### PR TITLE
encodesans: v3.0 added.

### PR DESCRIPTION
**Pull request by thundernixon**
This PR replaces the current `encodesans` directory with a wght+wdth variable font, and includes a `static` folder with autohinted static instances.

This PR relates to and supercedes a previous PR: https://github.com/google/fonts/pull/1768. For a record of what has changed in the upstream from that PR, see [my notes on finishing this upgrade](https://github.com/thundernixon/Encode-Sans/tree/master/docs/17-finishing).

Upstream: https://github.com/thundernixon/Encode-Sans

## To do:
- [x] add `variable font` to description
- [x] Fix copyright string. `copyright 2020 the Encode Sans project authors (stephen@thundernixon.com), with reserved font name "encode sans”.`
- [x] update instance style names to include width descriptors
- [x] check that the 'Regular' instance has a 'wdth' (Width) axis coordinate must of 100, fix if needed
- [x] Update license URL with `https` URL in OFL & in font info
- [x] Check copyright namerecords match license file.
- [x] **semi-blocked:** I can't simply follow FontBakery's suggestion of adding `Axis Location` custom parameters to each master in the Glyphs source, as this causes glyphsLib to fail to generate the correct axis map, resulting in bad middle-instance wght values on the fvar table. See https://github.com/googlefonts/fontmake/issues/543. I'll probably have to either edit the designspace in the build, or edit the final OS/2 table with TTFont. I'll probably do the latter. [Solution found](https://github.com/googlefonts/fontmake/issues/543#issuecomment-621951478)
- [x] `🔥 FAIL TYPOGRAPHIC_SUBFAMILY_NAME for Win "Thin Condensed" is incorrect. It must be "Thin". [code: bad-typo-win]` Solution: this name was incorrect in the masters and had to be corrected.
- [x]  FAIL: Checking OS/2 usWeightClass matches weight specified at METADATA.pb.
- [x] check & fix alignment of vietnamese accents. These are off in certain masters.
- [x] correct flipped numerators & denominators.

## Questions
- [x] Is a "reserved font name" okay? We never heard back from Impallari on whether we had his blessing to change that. UPDATE: in https://github.com/google/fonts/pull/1768, Dave said that we could keep the RFN for this.

## Incorrect FontBakery checks

> 🔥 FAIL: A static fonts directory with at least two fonts must accompany variable fonts

There are static fonts in the `static` folder.

> ⚠ WARN: Combined length of family and style must not exceed 27 characters. com.google.fonts/check/name/family_and_style_max_length

This exceeds 27 characters only if names 1 & 2 are added up – but I haven't seen any documentation, anywhere, that this is the restriction. It should be (maybe) checking name 4 & 6, only. See first and last comments at https://github.com/googlefonts/fontbakery/issues/2179

> 🔥 FAIL OS/2 usWeightClass expected value for 'Condensed Thin' is 250 but this font has 100.
GlyphsApp users should set a Custom Parameter for 'Axis Location' in each master to ensure that the information is accurately built into variable fonts. [code: bad-value]

100 is correct. See https://github.com/googlefonts/fontbakery/issues/2644

> 🔥 FAIL: METADATA.pb: According Google Fonts standards, families should have a Regular style.

Incorrect for variable font. More at: https://github.com/googlefonts/fontbakery/issues/2378#issuecomment-622410346

### CODE REVIEW

**Comment by thundernixon** [comment]
The latest force push solves a previous issue of misaligned Vietnamese accents. It corrects all the fontbakery checks that I believe are accurate. 

A few others that are now coming up, but which I think are invalid:

> 🔥 FAIL This family lacks a Regular (style: normal and weight: 400) as required by Google Fonts standards. [code: lacks-regular]

This seems wrong... this is a variable font, and the weight in metadata should match the default instance, correct? Previously, it was reported as a fail for not matching the `usWeightClass`. One of these tests must be wrong, right?

> FAIL: Checking OS/2 usWeightClass matches weight specified at METADATA.pb.
> com.google.fonts/check/metadata/os2_weightclass
> 🔥 FAIL OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (100:"Thin"). [code: mismatch]

These weights do match. 

>  FAIL: METADATA.pb weight matches postScriptName.

Probably due to the name parser not currently working with width names.

## Combining marks

I'm finding in the diffs that combining accents are way off of where they previously were. I think this is due to [the way Glyphs encourages these to be spaced in the middle of a wide glyph box](https://glyphsapp.com/tutorials/diacritics), whereas [the traditional / UFO approach is to draw them as zero-width glyphs](https://robofont.com/documentation/how-tos/introduction-to-accented-glyphs/) (except for non-`comb` accents, which should have some default margin. In either approach letters are constructed correctly, so long as anchors are correctly place.

I'm going to look at some other recent PRs to see how others are handling this. I assume that FontMake would probably correct these to be zero-width glyphs if this were critical, but I'll check on that assumption.

**Comment by thundernixon** [comment]
Haha, somehow the numerators and denominators are flipped in this family, currently. Fixing that now.

image

**Comment by thundernixon** [comment]
Okay, that was just a simple issue of mismatched-components. This latest push has corrected it.

image

**Comment by thundernixon** [comment]
Repushed to get update an qa.zip (Git deletes attached files at the end of the month).

**Comment by thundernixon** [comment]
Diffenator is reporting changes to the sups/infs glyphs, but these are now working well in Font Goggles:

image

**Comment by thundernixon** [comment]
I realized that the ordering passed to statmake effects the ordering or composed names from the STAT table (at least in Samsa), so I’ve moved Width ahead of Weight and pushed again. Now it is looking as expected:

image

**Comment by m4rc1e** [comment]
Your gftools is out of date. 

`gftools add-font` should return  a `400` for the weightClass value of a VF, if the VF's weight range includes 400, else it should be the closest value to 400

https://github.com/googlefonts/gftools/blob/master/Lib/gftools/util/google_fonts.py#L450-L452

**Comment by m4rc1e** [comment]
I've updated and force pushed. I'll review it now.

**Comment by m4rc1e** [comment]
- lcommaaccent: The mark looks mispositioned in the Regular

encode_1

**Comment by thundernixon** [comment]
@m4rc1e I've fixed the comma accent issue, rebuilt, and repushed. Please check this again when you have the chance to. Thanks!

**Comment by m4rc1e** [comment]
Thanks @thundernixon

**Comment by thundernixon** [comment]
Thanks for the guidance & review, @m4rc1e!

**Pull request merged**
