### PR TITLE
hotfix-opensans: v1.101 added

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by davelab6** [comment]
Somehow the case wasn't changed; I think you may need to run your git of this repo in a disk image to get full case sensitivity... 

screen shot 2017-05-15 at 20 10 11

**Comment by bardware** [comment]
Is there a description available how this font was changed by this update?

**Comment by m4rc1e** [comment]
@bardware We've had issues with the fonts in Google Docs and Android. The hotfix prs will update the font's name table, fsSelection and macStyle bits.

**Comment by m4rc1e** [comment]
This hotfix does not address the kern sub table issue, 
```
marc$ ./ots-sanitize /Users/marc/Documents/googlefonts/hotfix/out/repo_cp/apache/opensans/OpenSans-Regular.ttf
ERROR: kern: Too large subtable
ERROR: Table discarded
```

Otherwise the bits are good.

cc @davelab6

**Comment by m4rc1e** [comment]
## Regular
**fsType**
screen shot 2017-06-08 at 11 28 07

**Nametable**
screen shot 2017-06-08 at 11 27 40


## SemiBold
**fsType & fsSelection**
screen shot 2017-06-08 at 11 34 44
SemiBold fsSelection changed from Bold to Regular

**Nametable**
screen shot 2017-06-08 at 11 38 10


Everything else has remained the same.
screen shot 2017-06-08 at 11 38 55


The bits and nametables have changed for all the fonts. I only chose to show the Reg and SemiBold due to their different treatments. The nametable now complies with the following [repo](https://github.com/davelab6/glyphs-export)

**Comment by m4rc1e** [comment]
Outstanding issue for Open Sans are:
#272 #721 #399 #134 #410 #78 #230 #411 #88 #213 #51 #22 #152 #154 

I'll go through these and see which are still applicable once this pr has gone live.

**Comment by m4rc1e** [comment]
#272: Result of Adobe TypeKit, skipping
#721: Could not replicate issue with these fonts and latest Chrome, skipping
#399: Todo look at this in Browser Stack
#134: [OpenSans Condensed](https://fonts.google.com/specimen/Open+Sans+Condensed) only has three weights, skipping
#410: User has fonts loaded locally, known problem, skipping
#78: Works just fine for me, added comment, skipping
#230: Design choice, skipping
...
I need to go vote now. I'll add to this once I'm back

**Comment by m4rc1e** [comment]
Looks like the Sandboxed Open Sans works as expected
http://jsbin.com/tebewupoye/edit?html,output

screen shot 2017-06-08 at 21 49 29

I made a [script](https://gist.github.com/m4rc1e/dc044c465d507fb9fc2b6473852f8005) which can generate jsbin snippets for fonts hosted on fonts.google.com and fonts which are sandboxed. I often need to make these, we may as well have an automated way to do it.

cc @davelab6 

@felipesanches @graphicore I'd love to include this script in FontBakery. Unfortuantely I lack the time to polish and pepify, it is 85% of the way there.

**Comment by davelab6** [comment]
> It would be nice if we could fix this all at source

No source are available; please just fix the TTF.

**Comment by thlinard** [comment]
> #411: Greek-ext included in METADATA.pb files, dont think we can remove or fix this... too risky

Because otherwise <link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=greek-ext" rel="stylesheet"> will fail? Could a mechanism be set up for a graceful degradation, so that at least users don't see Open Open in the list of fonts supporting extended Greek?

**Comment by davelab6** [comment]
Yes. The solution is to add the glyphs :)

**Comment by davelab6** [comment]
Yes. The solution is to add the glyphs :)

**Comment by thlinard** [comment]
Well, I was thinking about a more realistic solution. Because the problem is not a future problem, it is a present problem. A site writes ΑαᾆᾼΗηᾖῌΩωᾦῼ with `<link href="https://fonts.googleapis.com/css?family=Open+Sans&amp;subset=greek-ext" rel="stylesheet">`, and an user sees what? A mix between Open Sans and Arial or Helvetica if the browser is not very bright in its substitution, or Arial or Helvetica all along if the browser is smarter.

What is really the problem to delete Greek-ext in METADATA.pb? The browser crash, a kitten dies?

Or simply Arial or Helvetica, or whatever sans-serif default configured in the browser, are substitued to Open Sans? But it'll happens anyway: it's already the case.

**Comment by davelab6** [comment]
The scale of the Google Fonts API (https://fonts.google.com/analytics) brings constraints that aren't present in more simple font hosting solutions. Subsets, once added, will not be removed.

**Comment by thlinard** [comment]
Well, "too big to be fixed" sounds like a design flaw, but what do I know!
Could there be at least a warning somewhere, a "KNOWNBUGS.md", like:
"Open Sans (and some others, like Roboto) are advertised as they supporting Extended Greek, but choosing the greek-ext subset will not display Open Sans (or the required font) for this range: they don't have the required characters.
You're welcome to commission these characters, though."

**Comment by davelab6** [comment]
I made a note about this in https://github.com/google/fonts/blob/master/TRIVIA.md#incomplete-greek-ext-subsets

**Comment by thlinard** [comment]
Thanks, Dave!

**Pull request merged**
