### PR TITLE
Saman Dere: Version 1.001 added

### LINKED ISSUE #3340: Saman Dere: Version 1.001 added
Hello,
I would like to add my font to google font. 
My repo is here: https://github.com/tcgumus/saman and I created a pull request https://github.com/google/fonts/pull/3339.
Thank you,
Best regards,
Tuna

### PR DESCRIPTION
**Pull request by tcgumus**
Saman Dere Version 1.001 taken from the upstream repo https://github.com/tcgumus/saman at commit tcgumus/saman@45aca05
Fixes #3340

### CODE REVIEW

**Comment by tcgumus** [comment]
@googlebot I signed it!

**Comment by tcgumus** [comment]
@RosaWagner Hey Rosa, could you run the QA to see if there's any FAIL left? Thank you. :)

**Comment by tcgumus** [comment]
Please let me know if I can be of any help.

**Comment by m4rc1e** [comment]
Desktop_Windows_10_chrome_71 0_


Desktop_Windows_10_chrome_71 0_

**Comment by davelab6** [comment]
@tcgumus I'm sorry to say that at this time, I can't accept this PR. I think this is promising work, and I encourage you to keep improving your skills and craft, but there are some inconsistencies in the design that will need to be resolved. I'm sad to say that currently I can't offer any direct help or more detailed feedback with these issues. I encourage you to seek feedback on typedrawers forum, font design workshops and conferences.

**Comment by tcgumus** [comment]
Hello @davelab6 @RosaWagner @m4rc1e,
Thanks for all the time you spare for this pr. I should have been more prepared. I'm not sure I understand the inconsistencies in the design but I will try my best to find the problems and fix them. 
Best regards,
Tuna

**Comment by m4rc1e** [comment]
On the plus side, your PR was very clean. You generated the metadata and provided a description.

> I'm not sure I understand the inconsistencies in the design but I will try my best to find the problems and fix them.

A very good book that would help this project immensely is Designing Type by Karen Cheng, https://yalebooks.yale.edu/book/9780300249927/designing-type. It covers the construction of individual letterforms and how to make them appear balanced.

Hope it helps.

**Comment by RosaWagner** [comment]
Ok so I am closing this for now. @tcgumus don't hesitate to reopen the issue when you have an updated design to propose :)

**Pull request closed without merging**
