### PR TITLE
Noto Sans Sinhala: Version 2.006 added

### PR DESCRIPTION
**Pull request by simoncozens**
7b91be8: [gftools-packager] Noto Sans Sinhala: Version 2.004 added

* Noto Sans Sinhala Version 2.004 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

### CODE REVIEW

**Review by m4rc1e — CHANGES_REQUESTED** [review]
Following strings didn't work too well:

෫හෑ්6*ඥ්

ඡ/𑇬ලැිඃ

ාේ𑇨෯ැ÷[

—ඞ𑇴ශෟීඟඎ෴

හැේැඃ}{

ොඁපෞ්𑇩ජව

ූ෧ජොූඟ9

ං𑇩ඖජෞූඪ

.ඊ𑇢ඟොු*෫ග

**Comment by simoncozens** [comment]
OK, I've been through all these strings. Most of them don't make sense and the problem is due to having two vowel marks on the same base. But I prefer the newer rendering; it forms ligatures for the above vowels, which at least positions one of them correctly.

**Comment by simoncozens** [comment]
There is the same dlig problem here is #4880. I'll need to fix it.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Sinhala: Version 2.005 added

---
 5588810: [gftools-packager] Noto Sans Sinhala: Version 2.005 added

* Noto Sans Sinhala Version 2.005 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

**Comment by vv-monsalve** [comment]
@simoncozens the only `text` image produced by browserstack as part of the `qa` package is:

**Windows 10 Chrome_71**
Desktop_Windows_10_chrome_71 0_

But when running local text with a Sinhala sample, this is produced.

**OS X High Sierra Safari_11**
Desktop_OS_X_High_Sierra_safari_11 1_
**Windows 10 Edge_18**
Desktop_Windows_10_edge_18 0_

**Comment by vv-monsalve** [comment]
You would like to inspect the [serif variant results](https://github.com/google/fonts/pull/4880#issuecomment-1191072865)

**Comment by simoncozens** [comment]
That doesn't look right. I'll take a look.

**Comment by vv-monsalve** [comment]
> That doesn't look right. I'll take a look.

Ok, please let me know if we should block the serif PR

**Comment by simoncozens** [comment]
This is https://github.com/harfbuzz/harfbuzz/issues/3725

**Comment by simoncozens** [comment]
Updated

## Noto Sans Sinhala: Version 2.005 added

---
 1ad8614: [gftools-packager] Noto Sans Sinhala: Version 2.005 added

* Noto Sans Sinhala Version 2.005 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

**Comment by RosaWagner** [comment]
Article is not reinstated in this PR

**Comment by RosaWagner** [comment]
And same issue as Serif Sinhala

🔥 FAIL: Font has **proper** whitespace glyph names? ([com.google.fonts/check/whitespace_glyphnames](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphnames))
🔥 FAIL Glyph 0x00A0 is called "uni00A0.sinh": Change to "uni00A0" [code: non-compliant-00a0]

**Comment by simoncozens** [comment]
Updated

## Noto Sans Sinhala: Version 2.006 added

---
 2bb0968: [gftools-packager] Noto Sans Sinhala: Version 2.006 added

* Noto Sans Sinhala Version 2.006 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

**Comment by vv-monsalve** [comment]
Now the width values differ and it would make it not eligible to be added to Workspace.

> 🔥 FAIL: Space and non-breaking space have the same width? ([com.google.fonts/check/whitespace_widths](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/hmtx.html#com.google.fonts/check/whitespace_widths))
> 🔥 FAIL Space and non-breaking space have differing width: The space glyph named space is 500 font units wide, non-breaking space named (uni00A0) is 260 font units wide, and both should be positive and the same. GlyphsApp has "Sidebearing arithmetic" (https://glyphsapp.com/tutorials/spacing) which allows you to set the non-breaking space width to always equal the space width. [code: different-widths]

**Comment by vv-monsalve** [comment]
Other tha the above, `qa` images are looking good.

**Comment by simoncozens** [comment]
Grr. I'm sorry; I thought I had checked that... In fact:

Screenshot 2022-07-29 at 08 33 09

*sigh* I'll see what's going on.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Sinhala: Version 2.006 added

---
 236fc38: [gftools-packager] Noto Sans Sinhala: Version 2.006 added

* Noto Sans Sinhala Version 2.006 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

**Comment by vv-monsalve** [comment]
Fb report + `qa` images look good now

**Comment by chrissimpkins** [comment]
Still requires prod push

**Pull request merged**
