### PR TITLE
Noto Sans Chorasmian: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
0ecedac: [gftools-packager] Noto Sans Chorasmian: Version 1.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Chorasmian Version 1.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/chorasmian.git at commit https://github.com/notofonts/chorasmian/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
This release:

* Improves cursive joining (#2)
* Improves the character variation of isolated glyphs (#1)
```

**Comment by emmamarichal** [comment]
- I don't know if this fail should be fixed or not:

`🔥 FAIL: Ensure dotted circle glyph is present and can attach marks. ([com.google.fonts/check/dotted_circle](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/%3CSection:%20Shaping%20Checks%3E.html#com.google.fonts/check/dotted_circle))`

- Maybe this WARN could be avoid? I don't have access to the description since it has not been modified.

`⚠ WARN: DESCRIPTION.en_us.html should end in a linebreak. ([com.google.fonts/check/description/eof_linebreak](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/eof_linebreak))`

- Concerning the design, I only see this big change, but I guess this is what you updated.

https://github.com/google/fonts/assets/64773544/ef507692-d8c9-427b-b2fb-2cf806ad99f2

**Comment by simoncozens** [comment]
Joining changes are OK but (as with other Noto fonts recently) mark attachment on Latin is broken.

**Comment by RosaWagner** [comment]
@simoncozens on the video and the diff we see that the mark attachment actually got better :)

diffbrowsers_text-macOS-12 6 9-x86_64-i386-64bit_firefox_117 0 1

**Review by RosaWagner — APPROVED** [review]

**Review by emmamarichal — APPROVED** [review]

**Comment by emmamarichal** [comment]
@simoncozens 
Checking in sandbox: [_Joining changes are OK_](https://github.com/google/fonts/pull/6760#issuecomment-1782528352) but I wanted to be sure that kind of behavior is ok:

Capture d’écran 2023-11-15 à 13 40 27

**Comment by eliheuer** [comment]
Bump, any thoughts @simoncozens? I'm trying to get some blocked issues moving through the pipeline. 

Can we unblock this?

**Comment by simoncozens** [comment]
Looks like a kerning problem. I'll take a further look.

**Comment by simoncozens** [comment]
No, it's even worse than a kerning problem; wrong shaping. I'll do another release.

**Pull request merged**
