### PR TITLE
Noto Sans Sundanese: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
7bd9413: [gftools-packager] Noto Sans Sundanese: Version 2.002 added

* Noto Sans Sundanese Version 2.002 taken from the upstream repo https://github.com/notofonts/sundanese.git at commit https://github.com/notofonts/sundanese/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
About the dotted circle fail: we are attaching marks to Sundanese glyphs but not Latin glyphs. I'm not sure why.

**Comment by RosaWagner** [comment]
@simoncozens is the issue with the dotted circle a blocker for merging this PR?

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by simoncozens** [comment]
I'm more interested in the way that all the marks have changed positions. Will check.

**Comment by simoncozens** [comment]
I can't reproduce the mark changes locally. It looks fine here.

**Comment by simoncozens** [comment]
Wait, no, I see it. Something odd is happening.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Sundanese: Version 2.003 added

---
 d6ca738: [gftools-packager] Noto Sans Sundanese: Version 2.003 added

* Noto Sans Sundanese Version 2.003 taken from the upstream repo https://github.com/notofonts/sundanese.git at commit https://github.com/notofonts/sundanese/commit/.

**Pull request merged**
