### PR TITLE
Noto Serif Khojki: Version 2.005 added

### PR DESCRIPTION
**Pull request by simoncozens**
96deac9: [gftools-packager] Noto Serif Khojki: Version 2.005 added

* Noto Serif Khojki Version 2.005 taken from the upstream repo https://github.com/notofonts/khojki.git at commit https://github.com/notofonts/khojki/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
Noto Serif Khojki v2.005

This release:

* Improves the display of nukta combinations (#14, #22)
* Correct reorders the nukta + sukun combination (#15)
* Allow conjuncts to form in the presence of a nukta (#16)
* Uses the steeper alternative E vowel to avoid clashes (#17)
* Fixes the kerning and display of AI vowel (#18)
* Removes some unnecessary glyphs (#19)
* Adds the newly encoded characters QA (U+1123F) and SHORT I (U+11240)
```

**Review by m4rc1e — APPROVED** [review]

**Comment by eliheuer** [comment]
@simoncozens Noto Serif Khojki still has tofu in sandbox despite https://github.com/google/fonts/pull/6970 also being in sandbox.

Screenshot 2023-12-05 at 11 11 23 AM

**Comment by simoncozens** [comment]
My fault, I missed a character when fixing up the sample texts.

**Comment by simoncozens** [comment]
Filed https://github.com/googlefonts/lang/pull/135 to fix.

**Comment by simoncozens** [comment]
This should be good now.

**Pull request merged**
