### PR TITLE
comfortaa: v3.103 Upgraded to VF

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/googlefonts/comfortaa at commit https://github.com/googlefonts/comfortaa/commit/a308e42532deabdbf0e289541f3eb336da69c4cc

## Fontbakery report

Fontbakery version: 0.5.1.dev28+g39c4540c

<details>
<summary><b>[9] Comfortaa-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/001](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/001)
* :fire: **FAIL** Style name used in "/Users/marc/Documents/googlefonts/fonts/ofl/comfortaa/Comfortaa-Regular.ttf" is not canonical. You should rebuild the font using any of the following style names: "Thin", "ExtraLight", "Light", "Regular", "Medium", "SemiBold", "Bold", "ExtraBold", "Black", "Thin Italic", "ExtraLight Italic", "Light Italic", "Italic", "Medium Italic", "SemiBold Italic", "Bold Italic", "ExtraBold Italic", "Black Italic".

</details>
<details>
<summary>:fire: <b>FAIL:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/056](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/056)
* :fire: **FAIL** Failed to parse ttfautohint version values: installed = '1.8.2'; used_in_font = '1.8.1.43-b0c9' [code: parse-error]

</details>
<details>
<summary>:warning: <b>WARN:</b> Copyright notice on METADATA.pb should not contain 'Reserved Font Name'.</summary>

* [com.google.fonts/check/103](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/103)
* :warning: **WARN** METADATA.pb: copyright field ("Copyright 2011 The Comfortaa Project Authors (https://github.com/alexeiva/comfortaa), with Reserved Font Name "Comfortaa".") contains "Reserved Font Name". This is an error except in a few specific rare cases.

</details>
<details>
<summary>:warning: <b>WARN:</b> Glyphs are similiar to Google Fonts version?</summary>

* [com.google.fonts/check/118](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/118)
* :warning: **WARN** Following glyphs differ greatly from Google Fonts version: [b, uni20BD, quotedblright, uni049C, Phi, quotereversed, uni0416, colonmonetary, uni0442, Oslash, uni2113, peseta, m, infinity, uni04DC, cent, uni0432, uni04CB, lira, h, dollar, f_f_i, ae, OE, aeacute, uni040B, fl, Euro, uni049D, alpha, uni20AE, uni04BB, f_f_l, uni042D, eight, ampersand, uni04D5, hcircumflex, hbar, alphatonos, sigma, oslashacute, uni045B, uni04C1, uni0424, uni00B5, bracketright, uni20B4.bold, uni044D, uni20A9, parenright, uni20B9, uni20B2, Oslashacute, yen, braceright, oe, tbar, oslash, f_f, uni20BA, uni20B1, lambda]

</details>
<details>
<summary>:warning: <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/153](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/153)
* :warning: **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: numbersign	Contours detected: 8	Expected: 2
Glyph name: dollar	Contours detected: 2	Expected: 1 or 3
Glyph name: six	Contours detected: 3	Expected: 1 or 2
Glyph name: eight	Contours detected: 4	Expected: 3
Glyph name: nine	Contours detected: 3	Expected: 1 or 2
Glyph name: G	Contours detected: 2	Expected: 1
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: R	Contours detected: 3	Expected: 1 or 2
Glyph name: T	Contours detected: 2	Expected: 1
Glyph name: X	Contours detected: 2	Expected: 1
Glyph name: a	Contours detected: 3	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: f	Contours detected: 2	Expected: 1
Glyph name: h	Contours detected: 3	Expected: 1
Glyph name: k	Contours detected: 3	Expected: 1 or 2
Glyph name: m	Contours detected: 3	Expected: 1
Glyph name: n	Contours detected: 2	Expected: 1
Glyph name: r	Contours detected: 2	Expected: 1
Glyph name: t	Contours detected: 2	Expected: 1
Glyph name: u	Contours detected: 2	Expected: 1
Glyph name: x	Contours detected: 3	Expected: 1
Glyph name: y	Contours detected: 2	Expected: 1
Glyph name: z	Contours detected: 3	Expected: 1
Glyph name: colonmonetary	Contours detected: 2	Expected: 1 or 3
Glyph name: lira	Contours detected: 3	Expected: 1
Glyph name: uni20A6	Contours detected: 2	Expected: 1, 3 or 5
Glyph name: Euro	Contours detected: 3	Expected: 1 or 2
Glyph name: uni20AD	Contours detected: 3	Expected: 1
Glyph name: uni20AE	Contours detected: 4	Expected: 1
Glyph name: uni20B2	Contours detected: 4	Expected: 1, 2 or 3
Glyph name: uni20B5	Contours detected: 3	Expected: 1 or 2
Glyph name: uni20B4	Contours detected: 4	Expected: 1 or 2
Glyph name: uni20B8	Contours detected: 3	Expected: 2
Glyph name: Eth	Contours detected: 3	Expected: 2
Glyph name: agrave	Contours detected: 4	Expected: 3
Glyph name: aacute	Contours detected: 4	Expected: 3
Glyph name: acircumflex	Contours detected: 4	Expected: 3
Glyph name: atilde	Contours detected: 4	Expected: 3
Glyph name: adieresis	Contours detected: 5	Expected: 4
Glyph name: aring	Contours detected: 5	Expected: 4
Glyph name: ae	Contours detected: 4	Expected: 3
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: eth	Contours detected: 4	Expected: 2
Glyph name: ntilde	Contours detected: 3	Expected: 2
Glyph name: ugrave	Contours detected: 3	Expected: 2
Glyph name: uacute	Contours detected: 3	Expected: 2
Glyph name: ucircumflex	Contours detected: 3	Expected: 2
Glyph name: udieresis	Contours detected: 4	Expected: 3
Glyph name: yacute	Contours detected: 3	Expected: 2
Glyph name: ydieresis	Contours detected: 4	Expected: 3
Glyph name: amacron	Contours detected: 4	Expected: 3
Glyph name: abreve	Contours detected: 4	Expected: 3
Glyph name: aogonek	Contours detected: 4	Expected: 2
Glyph name: Dcroat	Contours detected: 3	Expected: 2
Glyph name: dcroat	Contours detected: 3	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: Gcircumflex	Contours detected: 3	Expected: 2
Glyph name: Gbreve	Contours detected: 3	Expected: 2
Glyph name: Gdotaccent	Contours detected: 3	Expected: 2
Glyph name: uni0122	Contours detected: 3	Expected: 2
Glyph name: hcircumflex	Contours detected: 4	Expected: 2
Glyph name: hbar	Contours detected: 4	Expected: 1
Glyph name: uni0137	Contours detected: 4	Expected: 2 or 3
Glyph name: kgreenlandic	Contours detected: 3	Expected: 1 or 2
Glyph name: nacute	Contours detected: 3	Expected: 2
Glyph name: uni0146	Contours detected: 3	Expected: 2
Glyph name: ncaron	Contours detected: 3	Expected: 2
Glyph name: Eng	Contours detected: 2	Expected: 1
Glyph name: Racute	Contours detected: 4	Expected: 3
Glyph name: racute	Contours detected: 3	Expected: 2
Glyph name: uni0156	Contours detected: 4	Expected: 3
Glyph name: uni0157	Contours detected: 3	Expected: 2
Glyph name: Rcaron	Contours detected: 4	Expected: 3
Glyph name: rcaron	Contours detected: 3	Expected: 2
Glyph name: uni0162	Contours detected: 3	Expected: 1 or 2
Glyph name: uni0163	Contours detected: 3	Expected: 1 or 2
Glyph name: Tcaron	Contours detected: 3	Expected: 2
Glyph name: tcaron	Contours detected: 3	Expected: 2
Glyph name: Tbar	Contours detected: 3	Expected: 1
Glyph name: tbar	Contours detected: 3	Expected: 1
Glyph name: utilde	Contours detected: 3	Expected: 2
Glyph name: umacron	Contours detected: 3	Expected: 2
Glyph name: ubreve	Contours detected: 3	Expected: 2
Glyph name: uring	Contours detected: 4	Expected: 3
Glyph name: uhungarumlaut	Contours detected: 4	Expected: 3
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: uogonek	Contours detected: 3	Expected: 1
Glyph name: ycircumflex	Contours detected: 3	Expected: 2
Glyph name: zacute	Contours detected: 4	Expected: 2
Glyph name: zdotaccent	Contours detected: 4	Expected: 2
Glyph name: zcaron	Contours detected: 4	Expected: 2
Glyph name: uni018F	Contours detected: 1	Expected: 2
Glyph name: ohorn	Contours detected: 3	Expected: 2
Glyph name: Uhorn	Contours detected: 2	Expected: 1
Glyph name: uhorn	Contours detected: 3	Expected: 1
Glyph name: uni01CE	Contours detected: 4	Expected: 3
Glyph name: uni01D4	Contours detected: 3	Expected: 2
Glyph name: Gcaron	Contours detected: 3	Expected: 2
Glyph name: uni01EA	Contours detected: 3	Expected: 2
Glyph name: uni01EB	Contours detected: 3	Expected: 2
Glyph name: aringacute	Contours detected: 6	Expected: 4 or 5
Glyph name: aeacute	Contours detected: 5	Expected: 4
Glyph name: uni0201	Contours detected: 5	Expected: 4
Glyph name: uni0203	Contours detected: 4	Expected: 3
Glyph name: uni0205	Contours detected: 3	Expected: 4
Glyph name: uni0207	Contours detected: 2	Expected: 3
Glyph name: uni0210	Contours detected: 5	Expected: 4
Glyph name: uni0211	Contours detected: 4	Expected: 3
Glyph name: uni0212	Contours detected: 4	Expected: 3
Glyph name: uni0213	Contours detected: 3	Expected: 2
Glyph name: uni0215	Contours detected: 4	Expected: 3
Glyph name: uni0217	Contours detected: 3	Expected: 2
Glyph name: uni021A	Contours detected: 3	Expected: 2
Glyph name: uni021B	Contours detected: 3	Expected: 2
Glyph name: infinity	Contours detected: 4	Expected: 3
Glyph name: uni0233	Contours detected: 3	Expected: 2
Glyph name: uni0259	Contours detected: 1	Expected: 2
Glyph name: fl	Contours detected: 3	Expected: 1 or 2
Glyph name: yen	Contours detected: 3	Expected: 1 or 2
Glyph name: registered	Contours detected: 5	Expected: 3 or 4
Glyph name: uni00B5	Contours detected: 3	Expected: 1
Glyph name: Tau	Contours detected: 2	Expected: 1
Glyph name: Chi	Contours detected: 2	Expected: 1
Glyph name: Psi	Contours detected: 3	Expected: 1
Glyph name: alphatonos	Contours detected: 4	Expected: 3
Glyph name: etatonos	Contours detected: 3	Expected: 2
Glyph name: alpha	Contours detected: 3	Expected: 2
Glyph name: eta	Contours detected: 2	Expected: 1
Glyph name: kappa	Contours detected: 3	Expected: 1
Glyph name: lambda	Contours detected: 2	Expected: 1
Glyph name: sigma	Contours detected: 3	Expected: 2
Glyph name: psi	Contours detected: 3	Expected: 1
Glyph name: uni0402	Contours detected: 3	Expected: 1
Glyph name: uni0404	Contours detected: 2	Expected: 1
Glyph name: uni040B	Contours detected: 3	Expected: 1
Glyph name: uni040C	Contours detected: 3	Expected: 2
Glyph name: uni040E	Contours detected: 3	Expected: 2
Glyph name: uni0416	Contours detected: 3	Expected: 1
Glyph name: uni041A	Contours detected: 2	Expected: 1
Glyph name: uni0422	Contours detected: 2	Expected: 1
Glyph name: uni0423	Contours detected: 2	Expected: 1
Glyph name: uni0425	Contours detected: 2	Expected: 1
Glyph name: uni0427	Contours detected: 2	Expected: 1
Glyph name: uni0429	Contours detected: 2	Expected: 1
Glyph name: uni042D	Contours detected: 2	Expected: 1
Glyph name: uni042E	Contours detected: 3	Expected: 2
Glyph name: uni042F	Contours detected: 3	Expected: 2
Glyph name: uni0430	Contours detected: 3	Expected: 2
Glyph name: uni0431	Contours detected: 3	Expected: 2
Glyph name: uni0434	Contours detected: 3	Expected: 2
Glyph name: uni0435	Contours detected: 1	Expected: 2
Glyph name: uni0438	Contours detected: 2	Expected: 1
Glyph name: uni0439	Contours detected: 3	Expected: 2
Glyph name: uni043A	Contours detected: 2	Expected: 1
Glyph name: uni043D	Contours detected: 3	Expected: 1
Glyph name: uni043F	Contours detected: 2	Expected: 1
Glyph name: uni0442	Contours detected: 3	Expected: 1
Glyph name: uni0443	Contours detected: 2	Expected: 1
Glyph name: uni0445	Contours detected: 3	Expected: 1
Glyph name: uni0446	Contours detected: 2	Expected: 1
Glyph name: uni0447	Contours detected: 2	Expected: 1
Glyph name: uni0448	Contours detected: 3	Expected: 1
Glyph name: uni0449	Contours detected: 3	Expected: 1
Glyph name: uni044A	Contours detected: 3	Expected: 2
Glyph name: uni044D	Contours detected: 2	Expected: 1
Glyph name: uni044E	Contours detected: 4	Expected: 2
Glyph name: uni044F	Contours detected: 3	Expected: 2
Glyph name: uni0450	Contours detected: 2	Expected: 3
Glyph name: uni0451	Contours detected: 3	Expected: 4
Glyph name: uni0454	Contours detected: 2	Expected: 1
Glyph name: uni045B	Contours detected: 3	Expected: 1
Glyph name: uni045C	Contours detected: 3	Expected: 2
Glyph name: uni045D	Contours detected: 3	Expected: 2
Glyph name: uni045E	Contours detected: 3	Expected: 2
Glyph name: uni0462	Contours detected: 3	Expected: 2
Glyph name: uni0463	Contours detected: 3	Expected: 2
Glyph name: uni0492	Contours detected: 2	Expected: 1
Glyph name: uni0493	Contours detected: 2	Expected: 1
Glyph name: uni0494	Contours detected: 2	Expected: 1
Glyph name: uni0495	Contours detected: 2	Expected: 1
Glyph name: uni049C	Contours detected: 3	Expected: 1
Glyph name: uni049D	Contours detected: 3	Expected: 1
Glyph name: uni04A0	Contours detected: 3	Expected: 1
Glyph name: uni04A1	Contours detected: 3	Expected: 1
Glyph name: uni04A3	Contours detected: 4	Expected: 1 or 2
Glyph name: uni20B9	Contours detected: 4	Expected: 1
Glyph name: uni20BA	Contours detected: 3	Expected: 1
Glyph name: uni04AF	Contours detected: 2	Expected: 1
Glyph name: uni04B0	Contours detected: 2	Expected: 1
Glyph name: uni20BC	Contours detected: 2	Expected: 1
Glyph name: uni04B6	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04B7	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04B8	Contours detected: 3	Expected: 1
Glyph name: uni04B9	Contours detected: 3	Expected: 1
Glyph name: uni04BA	Contours detected: 2	Expected: 1
Glyph name: uni04BB	Contours detected: 3	Expected: 1
Glyph name: uni20BD	Contours detected: 4	Expected: 2
Glyph name: uni04C1	Contours detected: 4	Expected: 2
Glyph name: uni04CB	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04CC	Contours detected: 3	Expected: 1 or 2
Glyph name: uni04D1	Contours detected: 4	Expected: 3
Glyph name: uni04D3	Contours detected: 5	Expected: 4
Glyph name: uni04D5	Contours detected: 4	Expected: 3
Glyph name: uni04D7	Contours detected: 2	Expected: 3
Glyph name: uni04D8	Contours detected: 1	Expected: 2
Glyph name: uni04D9	Contours detected: 1	Expected: 2
Glyph name: uni04DC	Contours detected: 5	Expected: 3
Glyph name: uni04E3	Contours detected: 3	Expected: 2
Glyph name: uni04E5	Contours detected: 4	Expected: 3
Glyph name: uni04EE	Contours detected: 3	Expected: 2
Glyph name: uni04EF	Contours detected: 3	Expected: 2
Glyph name: uni04F0	Contours detected: 4	Expected: 3
Glyph name: uni04F1	Contours detected: 4	Expected: 3
Glyph name: uni04F2	Contours detected: 4	Expected: 3
Glyph name: uni04F3	Contours detected: 4	Expected: 3
Glyph name: uni04F4	Contours detected: 4	Expected: 3
Glyph name: uni04F5	Contours detected: 4	Expected: 3
Glyph name: uni051A	Contours detected: 3	Expected: 2
Glyph name: uni20A9	Contours detected: 2	Expected: 1, 3, 4 or 7
Glyph name: uni2113	Contours detected: 1	Expected: 2
Glyph name: uni1E9E	Contours detected: 2	Expected: 1
Glyph name: uni1EA1	Contours detected: 4	Expected: 3
Glyph name: uni1EA3	Contours detected: 4	Expected: 3
Glyph name: uni1EA5	Contours detected: 5	Expected: 4
Glyph name: uni1EA7	Contours detected: 5	Expected: 4
Glyph name: uni1EA9	Contours detected: 5	Expected: 4
Glyph name: uni1EAB	Contours detected: 5	Expected: 4
Glyph name: uni1EAD	Contours detected: 5	Expected: 4
Glyph name: uni1EAF	Contours detected: 5	Expected: 4
Glyph name: uni1EB1	Contours detected: 5	Expected: 4
Glyph name: uni1EB3	Contours detected: 5	Expected: 4
Glyph name: trademark	Contours detected: 3	Expected: 2
Glyph name: uni1EB5	Contours detected: 5	Expected: 4
Glyph name: uni1EB7	Contours detected: 5	Expected: 4
Glyph name: uni1EB9	Contours detected: 2	Expected: 3
Glyph name: uni1EBB	Contours detected: 2	Expected: 3
Glyph name: uni1EBD	Contours detected: 2	Expected: 3
Glyph name: uni1EBF	Contours detected: 3	Expected: 4
Glyph name: uni1EC1	Contours detected: 3	Expected: 4
Glyph name: uni1EC3	Contours detected: 3	Expected: 4
Glyph name: uni1EC5	Contours detected: 3	Expected: 4
Glyph name: uni1EC7	Contours detected: 3	Expected: 4
Glyph name: uni1EDB	Contours detected: 4	Expected: 3
Glyph name: uni1EDD	Contours detected: 4	Expected: 3
Glyph name: uni1EDF	Contours detected: 4	Expected: 3
Glyph name: uni1EE1	Contours detected: 4	Expected: 3
Glyph name: uni1EE3	Contours detected: 4	Expected: 3
Glyph name: uni1EE5	Contours detected: 3	Expected: 2
Glyph name: uni1EE7	Contours detected: 3	Expected: 2
Glyph name: uni1EE8	Contours detected: 3	Expected: 2
Glyph name: uni1EE9	Contours detected: 4	Expected: 2
Glyph name: uni1EEA	Contours detected: 3	Expected: 2
Glyph name: uni1EEB	Contours detected: 4	Expected: 2
Glyph name: uni1EEC	Contours detected: 3	Expected: 2
Glyph name: uni1EED	Contours detected: 4	Expected: 2
Glyph name: uni1EEE	Contours detected: 3	Expected: 2
Glyph name: uni1EEF	Contours detected: 4	Expected: 2
Glyph name: uni1EF0	Contours detected: 3	Expected: 2
Glyph name: uni1EF1	Contours detected: 4	Expected: 2
Glyph name: ygrave	Contours detected: 3	Expected: 2
Glyph name: uni1EF5	Contours detected: 3	Expected: 2
Glyph name: uni1EF7	Contours detected: 3	Expected: 2
Glyph name: uni1EF9	Contours detected: 3	Expected: 2

</details>
<details>
<summary>:warning: <b>WARN:</b> Name table strings must not contain the string 'Reserved Font Name'.</summary>

* [com.google.fonts/check/152](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/152)
* :warning: **WARN** Name table entry ("Copyright 2011 The Comfortaa Project Authors (https://github.com/alexeiva/comfortaa), with Reserved Font Name "Comfortaa".") contains "Reserved Font Name". This is an error except in a few specific rare cases.

</details>
<details>
<summary>:warning: <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/065](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/065)
* :warning: **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<details>
<summary>:warning: <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/064](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/064)
* :warning: **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>:warning: <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/075](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/075)
* :warning: **WARN** The following glyphs have coordinates which are out of bounds:
[('icircumflex', 285.1, 690.0), ('icircumflex', 285.1, 669.0), ('icircumflex', 285.1, 654.0), ('jcircumflex', 280.1, 690.0), ('jcircumflex', 280.1, 669.0), ('jcircumflex', 280.1, 654.0)]
This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 7 | 9 | 7 | 111 |
| 0% | 1% | 5% | 7% | 5% | 82% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Summary**
old ttfautohint: This font is using Ewald's custom ttfautohint.
Canonical name: This seems like an issue with Fb to me. Can't see anything wrong with the filename

Both of these seem like false positives. I'll make a separate FB issue for each.

<details>
<summary>
<b>Diff Images</b>
</summary>

desktop_windows_10_chrome_69 0_
_Win 10 Chrome 69_

A single cap height jump at 8pt in the Regular only.

desktop_windows_10_chrome_69 0_
_Win 10 Chrome 69_

</details>

@davelab6 @nyshadhr9: Should we get @nyshadhr9 to sandbox the family before we merge? I'd like to test the mutated instances

### CODE REVIEW

**Comment by davelab6** [comment]
Marc wrote on an email thread regarding this: 

> For the past few weeks, we attempted to match the hinting using VTT (we spent around ~13 hours on it). Just before pushing, I noticed that if a glyph contained an accent, they may collide with the base glyph at certain sizes.
>
> accent_collide
> 
> Running out of ideas and in possession of a free Sunday, I revisited Ewald's ttfautohint and rebuilt it using the latest Freetype. The results were pretty good. A further thought occurred "What if we include the Regular as a master and make it the origin?"
> 
> Boom, it looks great. There's only 1 pixel jump at 8pt in Reg. The rest is spot on
> 
> The downside with this approach is an increase in file size. By having 3 masters, the family is now 220kb, the vtt compiled version was 180kb. However, it's still lighter than the 3 static fonts served on GF which total 390kb.
> 
> This version of ttfautohint will add a 'cvar' table. I understand varLib mutator may not support this yet. Tomorrow, I want to see if stripping this table out won't impact the hinting significantly. If it doesn't, I'll do some final checks and make sure it's PR'd this week

<blockquote>
<details>
<summary>
Here are two gifs, one using the approach above, the other our previous vtt effort.
</summary>
win_10_chrome_69 0_3_vf_masters_vs_gf:


win_10_chrome_69 0_vtt_vs_gf:
)
</details>
</blockquote>

**Comment by davelab6** [comment]
> The downside with this approach is an increase in file size. By having 3 masters, the family is now 220kb, the vtt compiled version was 180kb. However, it's still lighter than the 3 static fonts served on GF which total 390kb.

So, how can we have a ttfa hinted file with only 2 masters?

**Comment by nyshadhr9** [comment]
Can we merge this PR, but continue to investigate above issue in parallel?

**Comment by davelab6** [comment]
Done!

**Pull request merged**
