### PR TITLE
Yanone Kaffeesatz: Version 2.003 added

### PR DESCRIPTION
**Pull request by yanone**
a630335: [gftools-packager] Yanone Kaffeesatz: Version 2.003 added

* Yanone Kaffeesatz Version 2.003 taken from the upstream repo https://github.com/yanone/kaffeesatz at commit https://github.com/yanone/kaffeesatz/commit/104c0ced99e8390bf5b138c5ca6065c0f5fcc333.

### CODE REVIEW

**Comment by yanone** [comment]
Not sure what to make of the MATADATA FAIL. If I change the font name in METADATA as suggested, this FAIL turns into 4 others.

Please ignore the FAIL about the glyph coverage. I just finished a [PR](https://github.com/fonttools/fontbakery/pull/4380) to Fontbakery that uses the new glyphset definitions and the font covers those.

**Comment by emmamarichal** [comment]
@yanone Ah, we already had this issue, see: https://github.com/google/fonts/pull/7040#issuecomment-1840859815

**Comment by m4rc1e** [comment]
I've fixed the metadata name issue in FB, https://github.com/fonttools/fontbakery/pull/4407 so I'm going to merge this. Thanks @yanone and @emmamarichal

**Comment by vv-monsalve** [comment]
This PR needed the "I Font Upgrade" label. We use the labels to feed the push lists and also to track the projects by case.

**Pull request merged**
