### PR TITLE
Asap: Version 3.000 added

### PR DESCRIPTION
**Pull request by m4rc1e**
f4ddcb6: [gftools-packager] Asap: Version 3.000 added

* Asap Version 3.000 taken from the upstream repo https://github.com/Omnibus-Type/Asap at commit https://github.com/Omnibus-Type/Asap/commit/83b5b2566789401e3d3112f1a6a61264256d95af.

 1def850: [gftools-packager] ofl/asap remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by m4rc1e** [comment]
Upstream needs fixing, https://github.com/TypeNetwork/Asap/issues/6

**Comment by m4rc1e** [comment]
Updated

## Asap: Version 3.000 added

---
 b36a67a: [gftools-packager] Asap: Version 3.000 added

* Asap Version 3.000 taken from the upstream repo https://github.com/Omnibus-Type/Asap at commit https://github.com/Omnibus-Type/Asap/commit/83b5b2566789401e3d3112f1a6a61264256d95af.

 a0a726e: [gftools-packager] ofl/asap remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
Is it ready for review?

**Comment by RosaWagner** [comment]
Updated

## Asap: Version 3.000 added

---
 4185f40: [gftools-packager] Asap: Version 3.000 added

* Asap Version 3.000 taken from the upstream repo https://github.com/Omnibus-Type/Asap at commit https://github.com/Omnibus-Type/Asap/commit/b8c81d51d918c6e5213e73b01b6833a055efd0f2.

 5f22c19: [gftools-packager] ofl/asap remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
@googlebot I consent.

**Comment by RosaWagner** [comment]
Ah I see the OFL is 2021 and the fonts are 2019. I hotfix that and send the same to upstream to avoid future conflict…

**Comment by RosaWagner** [comment]
Updated

## Asap: Version 3.001 added

---
 8b20609: [gftools-packager] Asap: Version 3.001 added

* Asap Version 3.001 taken from the upstream repo https://github.com/Omnibus-Type/Asap at commit https://github.com/Omnibus-Type/Asap/commit/18c81047238c630e396728d24e6d3e62ea12d145.

 0014654: [gftools-packager] ofl/asap remove METADATA "source".  google/fonts#2587

**Pull request merged**
