### PR TITLE
Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
d347402: [gftools-packager] Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b) added

* Unica One Version 2.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/etunni/unica at commit https://github.com/etunni/unica/commit/9ce262ea51620674236322bab321615615228913.

 ccb3345: Unica One: description updated according the upgrade

### CODE REVIEW

**Comment by m4rc1e** [comment]
Looks good. Only concern is the dots for the "i" since this is a unicase font. Will get confirmation on Thursday.

Old
Screenshot 2023-01-20 at 17 31 54


New
Screenshot 2023-01-20 at 17 31 29

**Comment by emmamarichal** [comment]
@m4rc1e Have you discussed this at the meeting?

**Comment by m4rc1e** [comment]
Yep. We're concerned about the dots on the "I" and the "J". We feel these need to be removed because they may cause conflicts with the Turkish dotted I etc.

**Comment by emmamarichal** [comment]
Ok I will suggest to Eduardo to modify this!

**Comment by emmamarichal** [comment]
Updated

## Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

---
 4c8a6c8: [gftools-packager] Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

* Unica One Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] taken from the upstream repo https://github.com/etunni/unica at commit https://github.com/etunni/unica/commit/4a55b40cb9dbc2d6cf5b7f0d8546499793d1e92d.

 cef211f: Description updated

**Comment by emmamarichal** [comment]
@m4rc1e updated!

**Review by m4rc1e — CHANGES_REQUESTED** [review]
Almost, the "į" still needs its dot removed. I'd also triple check any glyph which uses the dotlessi and dotlessj as a component as well.

**Comment by emmamarichal** [comment]
Updated

## Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

---
 332996b: [gftools-packager] Unica One: Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

* Unica One Version 2.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] taken from the upstream repo https://github.com/etunni/unica at commit https://github.com/etunni/unica/commit/e92da87539ff465aab50b7767512080bf71e39f1.

 8621876: Description udpated

**Comment by emmamarichal** [comment]
@m4rc1e Done! The iogonek was the only one forgotten, the rest are accents

**Review by m4rc1e — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
