### PR TITLE
Sync axisregistry subtree and resolve conflicts

### PR DESCRIPTION
**Pull request by chrissimpkins**
The axisregistry subtree directory has been edited in this repository and in the googlefonts/axisregistry repository.  This PR attempts to resolve the subtree pull differences between the two repositories so that we can decide what changes need to be pushed back into googlefonts/axisregistry.

In the future, all edits targeting the axisregistry sub-directory git subtree should take place in the googlefonts/axisregistry repository.  The changes are then pulled into this repository with the following command executed from the root of the google/fonts repository:

```
git subtree pull --prefix=axisregistry https://github.com/googlefonts/axisregistry.git main
```

### CODE REVIEW

**Review by nathan-williams — APPROVED** [review]

**Review by m4rc1e — APPROVED** [review]
LGTM.

I also diffed all the textprotos against the other repo and they're all in sync!

```BASH
cd axisregistry/Lib/axisregistry/data
protos=$(ls *.textproto)
for p in $protos; do diff $p ~/path/to/axisregistry/data/$p; done
```

Thanks Chris.

**Comment by chrissimpkins** [comment]
> I also diffed all the textprotos against the other repo and they're all in sync!

Good news!

**Comment by chrissimpkins** [comment]
@felipesanches @simoncozens Any concerns about the changes here?  We're prepared to onboard new axes and I'd like to land these changes + update googlefonts/axisregistry with the merge conflict resolution decided here before we begin.  Ty!

**Comment by chrissimpkins** [comment]
Will merge.  @vv-monsalve Your EGRD axis registration will land in google/fonts with the merge of this PR

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/axisregistry/pull/65 copies the merge conflict resolution changes that we agreed upon here back to googlefonts/axisregistry.  After we merge that PR, we will no longer edit the google/fonts axisregistry directory directly.  Changes will occur in the googlefonts/axisregistry repository and will be git subtree pulled into this repository.

**Pull request merged**
