### PR TITLE
poppins: v3.100 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo, https://github.com/itfoundry/Poppins

**FB Report**
```
There is a total of 120 tests on <Section: Default>.
Start ... running 1718 individual test executions.
>> com.google.fonts/test/006
   DESCRIPTION.en_us.html must have less than 1000 bytes.
 * FAIL: DESCRIPTION.en_us.html must have size smaller than 1000 bytes.

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Black.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Black.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Black" while METADATA.pb has "Poppins"

   Result: FAIL
```
I will raise an issue for this in FB. The fonts are ok. This font only has win nametable records and it includes the preferred family name as "Poppins". 

```
>> com.google.fonts/test/102 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Black.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Black.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Black" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BlackItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BlackItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Black" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BlackItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BlackItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Black" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[2]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Bold.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[2]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Bold.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[3]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BoldItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[3]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-BoldItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBold.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBold.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins ExtraBold" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBold.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBold.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins ExtraBold" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBoldItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBoldItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins ExtraBold" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBoldItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraBoldItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins ExtraBold" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[6]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLight.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[6]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLight.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins ExtraLight" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[6]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLight.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[6]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLight.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins ExtraLight" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLightItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLightItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins ExtraLight" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLightItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ExtraLightItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins ExtraLight" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[8]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Italic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[8]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Italic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[9]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Light.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[9]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Light.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Light" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[9]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Light.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[9]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Light.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Light" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[10]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-LightItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[10]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-LightItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Light" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[10]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-LightItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[10]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-LightItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Light" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[11]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Medium.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[11]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Medium.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Medium" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[11]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Medium.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[11]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Medium.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Medium" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[12]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-MediumItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[12]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-MediumItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Medium" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[12]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-MediumItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[12]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-MediumItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Medium" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[13]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Regular.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[13]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Regular.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[14]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBold.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[14]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBold.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins SemiBold" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[14]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBold.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[14]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBold.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins SemiBold" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[15]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBoldItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[15]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBoldItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins SemiBold" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[15]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBoldItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[15]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-SemiBoldItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins SemiBold" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[16]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Thin.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[16]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Thin.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Thin" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[16]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Thin.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[16]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-Thin.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Thin" ! [code: familyname-mismatch]

   Result: FAIL

>> com.google.fonts/test/049 with ((u'font[17]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ThinItalic.ttf'),)
   Whitespace glyphs have ink?
 * FAIL: Glyph "zerowidthnonjoiner" has ink. It needs to be replaced by an empty glyph.
 * FAIL: Glyph "zerowidthjoiner" has ink. It needs to be replaced by an empty glyph.

   Result: FAIL

>> com.google.fonts/test/092 with ((u'font[17]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ThinItalic.ttf'),)
   Checks METADATA.pb font.name field matches family name declared on the name table.
 * FAIL: Unmatched family name in font: TTF has "Poppins Thin" while METADATA.pb has "Poppins"

   Result: FAIL

>> com.google.fonts/test/102 with ((u'font[17]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ThinItalic.ttf'),)
   Copyright notice on METADATA.pb matches canonical pattern ?
 * FAIL: METADATA.pb: Copyright notices should match a pattern similar to: 'Copyright 2017 The Familyname Project Authors (git url)'
But instead we have got: 'Copyright 2014-2017 Indian Type Foundry (info@indiantypefoundry.com)'

   Result: FAIL

>> com.google.fonts/test/108 with ((u'font[17]', '/Users/marc/Documents/googlefonts/fonts/ofl/poppins/Poppins-ThinItalic.ttf'),)
   METADATA.pb font.name and font.full_name fields match the values declared on the name table?
 * FAIL: METADATA.pb Family name "Poppins") does not match name table entry "Poppins Thin" ! [code: familyname-mismatch]

   Result: FAIL

======== <Section: Default> ========
1718 tests in section


Section results:

    ERROR: 0
    FAIL: 65
    WARN: 120
    SKIP: 54
    INFO: 74
    PASS: 1405

======== END <Section: Default> ========

Total:

    ERROR: 0
    FAIL: 65
    WARN: 120
    SKIP: 54
    INFO: 74
    PASS: 1405


DONE!


```
Summary:
-Copyright string: fonts have old copyright string format, should we file an issue upstream and get this updated?
-ZWJ, ZWNJ: why do all our Indic fonts include outlines for these glyphs? I've noticed this pattern from other foundries as well. By the looks of things, they should be empty.
screen shot 2017-11-27 at 13 59 50
*zwnj*
-meta vs name: mentioned above

**Rendering Report**
```

Fonts: ["Poppins-Black.ttf", "Poppins-BlackItalic.ttf", "Poppins-Italic.ttf", "Poppins-Regular.ttf", "Poppins-Thin.ttf", "Poppins-ThinItalic.ttf"]

View: glyphs-modified
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 40044 pixels

View: waterfall
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 331741 pixels
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 409171 pixels
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 318698 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 311365 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 320516 pixels
```

**win 7 IE 9 render**
*See attached zip (Github compressed them too much to show in this message)*

**Modified Glyphs**
desktop_os_x_el_capitan_safari_9 1_

[poppins_img.zip](https://github.com/google/fonts/files/1506079/poppins_img.zip)

### CODE REVIEW

**Comment by m4rc1e** [comment]
@davelab6 don't merge this, we have a problem with quotedbl base.

**Comment by m4rc1e** [comment]
Also have https://github.com/itfoundry/Poppins/issues/18

**Comment by roozbehp** [comment]
> -ZWJ, ZWNJ: why do all our Indic fonts include outlines for these glyphs? I've noticed this pattern from other foundries as well. By the looks of things, they should be empty.

Microsoft specs strongly recommend putting visible glyphs there. See https://www.microsoft.com/typography/otfntdev/glyphs.htm

**Comment by thlinard** [comment]
And http://www.typophile.com/node/16461

**Comment by m4rc1e** [comment]
@roozbehp thanks! I've updated our linter to take this into consideration.

**Pull request merged**
