### PR TITLE
Beta variable fonts R04: added

### PR DESCRIPTION
**Pull request by m4rc1e**
This pr includes beta variable fonts which can be built from M Foley's system using [Fontmake 1.3.0.](https://github.com/googlei18n/fontmake/releases/tag/v1.3.0) It is by no means a complete list of all the families in Google Fonts which can be turned into variable fonts.

Previous beta variable font families which can't be built with the current Fontmake have been removed.

The toolchain used to produce the families can be found here, https://github.com/m4rc1e/gfvf Happy variable fonts!

### CODE REVIEW

**Comment by thlinard** [comment]
Hi Marc,

Which version of Raleway did you use?

**Comment by thlinard** [comment]
OK, thanks. I tagged the current pull request, it's been so long that we're waiting for its merging.

**Comment by m4rc1e** [comment]
No worries. These are just quick betas so we have something to play with.

**Comment by davelab6** [comment]
@m4rc1e these are beta... what is needed to make these final? :)

**Comment by m4rc1e** [comment]
Better tooling to test them.

I'm also apprehensive to call them final. I would rather sync with the others to ensure we're making these in a future proof manner.

**Comment by davelab6** [comment]
Okay cool, are you still going to file more fontmake issues?

**Comment by davelab6** [comment]
> Okay cool, are you still going to file more fontmake issues?

Offline Marc said he would, but likely end of next week. 

However, sadly these all fail OTS so I think they can't be launched. 

```sh
$ echo "ArchivoVFBeta-Italic.ttf "; ots-sanitize ofl/archivovfbeta/ArchivoVFBeta-Italic.ttf;
echo "ArchivoVFBeta.tttf";  ots-sanitize ofl/archivovfbeta/ArchivoVFBeta.ttf ;
echo "AsapVFBeta-Condensed.ttf "; ots-sanitize ofl/asapvfbeta/AsapVFBeta-Condensed.ttf;
echo "AsapVFBeta-Italic.ttf "; ots-sanitize ofl/asapvfbeta/AsapVFBeta-Italic.ttf;
echo "AsapVFBeta.tttf";  ots-sanitize ofl/asapvfbeta/AsapVFBeta.ttf ;
echo "CabinVFBeta-Italic.ttf "; ots-sanitize ofl/cabinvfbeta/CabinVFBeta-Italic.ttf;
echo "CabinVFBeta.tttf";  ots-sanitize ofl/cabinvfbeta/CabinVFBeta.ttf ;
echo "FaustinaVFBeta-Italic.ttf "; ots-sanitize ofl/faustinavfbeta/FaustinaVFBeta-Italic.ttf;
echo "FaustinaVFBeta.tttf";  ots-sanitize ofl/faustinavfbeta/FaustinaVFBeta.ttf ;
echo "MavenProVFBeta.tttf";  ots-sanitize ofl/mavenprovfbeta/MavenProVFBeta.ttf ;
echo "PodkovaVFBeta.tttf";  ots-sanitize ofl/podkovavfbeta/PodkovaVFBeta.ttf ;

ArchivoVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
ArchivoVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta-Condensed.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 2
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in anchor table
ERROR: GPOS: Faled to parse anchor table for mark table 0
ERROR: GPOS: Failed to parse mark array
ERROR: Layout: Failed to parse lookup subtable 3
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in anchor table
ERROR: GPOS: Faled to parse anchor table for mark table 0
ERROR: GPOS: Failed to parse mark array
ERROR: Layout: Failed to parse lookup subtable 3
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
CabinVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
CabinVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse lookup from extension lookup
ERROR: Layout: Failed to parse lookup subtable 8
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
FaustinaVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
FaustinaVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
MavenProVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
PodkovaVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
$
```

**Comment by laerm0** [comment]
These all failed ots because of an error in the GPOS and it looks like it's the same error. I wonder if there's a glitch in the process of building variable fonts that breaks the GPOS somehow? I'll compare the errors to see if it's truly the same later.

**Comment by davelab6** [comment]
@m4rc1e please post any other FB check fails :)

**Comment by m4rc1e** [comment]
@laerm0 it may be related to this https://github.com/khaledhosny/ots/issues/113. I don't think ots has support for variable fonts yet, hence why I ignored it and wanted to do further tests.

**Pull request merged**
