### PR TITLE
Noto Sans Thaana: Version 3.000 added

### PR DESCRIPTION
**Pull request by simoncozens**
7a1ca27: [gftools-packager] Noto Sans Thaana: Version 3.000 added

* Noto Sans Thaana Version 3.000 taken from the upstream repo https://github.com/notofonts/thaana.git at commit https://github.com/notofonts/thaana/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
This is a completely redrawn font based on community input, so it should look very different to version 2!

**Comment by RosaWagner** [comment]
It is indeed another font. 

I read the issue https://github.com/notofonts/thaana/issues/1 and the article https://medium.com/kodefly/is-noto-sans-thaana-relevant-29a8307fb6cb. I also see that the new design was implemented in the last 2 month. Is there a link to a review of the new design by the community that we can add here? To make sure that the new design doesn't come with regression.

Latin semicolon appears reversed (it looks the same as the Thaana semicolon which was not the case in the previous version)

**Comment by RosaWagner** [comment]
oops didn't click the right button sorry

**Comment by simoncozens** [comment]
The new version was actually provided to us [last September](https://github.com/notofonts/thaana/pull/2). I *believe* this was reviewed internally by the team at Google who requested the update - but all I have to go on is a buganizer reference, which of course I can't see.

**Comment by RosaWagner** [comment]
Ok ok. Maybe @chrissimpkins can access the buganizer ref ?

I don't want to block a major update but the article goes through all the feedback and saying that except for the handwriting style, they are very happy with the evolution of the current version. And in the diff, the angle and the size of the glyphs have changed:

diffbrowsers_glyphs-Windows-10-10 0 20348-SP0_firefox_117 0 1

**Comment by simoncozens** [comment]
Allah glyph got de-encoded, I'll fix that. I'll also de-encode Latin comma and semicolon; comma-ar and semicolon-ar should be used in RTL text.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Thaana: Version 3.001 added

---
 a12275b: [gftools-packager] Noto Sans Thaana: Version 3.001 added

* Noto Sans Thaana Version 3.001 taken from the upstream repo https://github.com/notofonts/thaana.git at commit https://github.com/notofonts/thaana/commit/.

**Comment by simoncozens** [comment]
```
This release:

* Fixes an interpolation issue in the javiyani glyph
* Re-encodes the ALLAH glyphs
* Uses Latin comma and semicolon in full builds
```

**Comment by simoncozens** [comment]
This *has* now been approved and reviewers are very happy with it.

**Comment by RosaWagner** [comment]
Zuper!

**Pull request merged**
