### PR TITLE
Shantell Sans: Version 1.010;[586c7102b] added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/arrowtype/shantell-sans at commit https://github.com/arrowtype/shantell-sans/commit/da45107f66d2faed3b695a976b20d957855f0925.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [x] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [x] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
@vv-monsalve 
I added some images to the article, that have to be checked :)

**Comment by emmamarichal** [comment]
@vv-monsalve Images look too large, let me update that!

**Comment by vv-monsalve** [comment]
> 🔥 FAIL Ensure 'ital' STAT axis is last.

@emmamarichal, please check this one. This is a strong requirement from our side.

**Comment by emmamarichal** [comment]
@vv-monsalve Right! 

@arrowtype, could you update the STAT table to avoid that fail?
```
🔥 FAIL Ensure 'ital' STAT axis is last.
STAT table 'ital' axis is not the last in the axis order.
Overridden: This check was originally a WARN but was overridden by the ufo profile: For Google Fonts, the 'ital' axis must be last in the axes order.
[code: ital-axis-not-last]
```
I'll then update that PR!

**Comment by arrowtype** [comment]
Okay, I will be trying to improve NameID 1 of the static fonts, possibly this weekend, so I’ll work on this in the same go.

I’ve also filed an issue requesting more rationale in that check, as it is a little brief, at the moment. https://github.com/fonttools/fontbakery/issues/4754

**Comment by arrowtype** [comment]
Okay, the STAT table was actually super quick to reorder. I’ve checked with fdiff that the only changes between the earlier v1.010 VFs and the latest are in the STAT table, related name table entries, and the git commit version in the name table.

Here’s my set of changes:
https://github.com/arrowtype/shantell-sans/pull/139

Here are the latest fonts:
https://github.com/arrowtype/shantell-sans/releases/tag/1.010

As I mentioned in my previous comment, I do intend to make some adjustments to the static fonts soon, but since they aren’t used in this PR, those changes should have no impact here.

Hope this helps!

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
@vv-monsalve updated! :)

**Comment by m4rc1e** [comment]
@vv-monsalve do we have a policy for STAT AxisValue names for axes that only have a single "Default" entry? In this family, the BNCE, SPAC and INFM axes have additional names declared by the user.

**Comment by vv-monsalve** [comment]
Yes, named instances in the stat table are allowed for these cases. This is what we have now in the Guide:

> very instance that is allowed to be a part of the `fvar` table should also be listed in the STAT table with equivalent values and names. However, the STAT table can also include axis values with string labels which can add extra style variants.

Shantell Sans was one of the first fonts onboarded with custom axes using this approach.

**Pull request merged**
