### PR TITLE
Big Shoulders Text: Version 2.000 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
236ef44: [gftools-packager] Big Shoulders Text: Version 2.000 added

* Big Shoulders Text Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/b465ae3b3cc320591f44462dd3e3e7306bc96d00.

 59f64ca: [gftools-packager] ofl/bigshoulderstext remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Text: Version 2.000 added

---
 979bd77: [gftools-packager] Big Shoulders Text: Version 2.000 added

* Big Shoulders Text Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 d92eafe: [gftools-packager] ofl/bigshoulderstext remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
This PR upgrades [Big Shoulders](https://fonts.google.com/specimen/Big+Shoulders+Text?query=Big) into a Variable Font.

**Comment by m4rc1e** [comment]
Thanks!

The horn has moved for all glyphs.

horn

Is this intentional?

**Comment by vv-monsalve** [comment]
> Is this intentional?

Yes, is part of the Vietnamese improvements done by the designer

**Comment by m4rc1e** [comment]
@vv-monsalve Are these prs still draft?

**Comment by vv-monsalve** [comment]
> @vv-monsalve Are these prs still draft?

Yes, the designer is checking the ExtraLight weight

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Text: Version 2.002 added

---
 2eef182: [gftools-packager] Big Shoulders Text: Version 2.002 added

* Big Shoulders Text Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/c32776c15acba7f76797d45cfeb27d1c2a1738a0.

 4ba6cba: [gftools-packager] ofl/bigshoulderstext remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The font includes now the `ExtraLight` Instance.

**Comment by RosaWagner** [comment]
As it be confirmed somewhere that it was okay to have "Text" in the STAT table (instead of 10pt)? 
I actually think the opsz axis shouldn't appear in the STAT at all since Text is already in the family name and the font only display a weight axis.

## Fontbakery report

Fontbakery version: 0.7.37

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Do we have the latest version of FontBakery installed?</summary>

* [com.google.fonts/check/fontbakery_version](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/fontbakery_version)

* 🔥 **FAIL** Current Font Bakery version is 0.7.37, while a newer 0.7.38 is already available. Please upgrade it with 'pip install -U fontbakery'

</details>
<br>
</details>
<details>
<summary><b>[7] BigShouldersText[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Validate STAT particle names and values match the fallback names in GFAxisRegistry. </summary>

* [com.google.fonts/check/STAT/gf-axisregistry](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT/gf-axisregistry)
<pre>--- Rationale ---
Check that particle names and values on STAT table match the fallback names in
each axis entry at the Google Fonts Axis Registry, available at
https://github.com/google/fonts/tree/main/axisregistry</pre>

* 🔥 **FAIL** On the font variation axis 'opsz', the name 'Text' is not among the expected ones (6pt, 7pt, 8pt, 9pt, 10pt, 11pt, 12pt, 14pt, 16pt, 17pt, 18pt, 20pt, 24pt, 28pt, 36pt, 48pt, 60pt, 72pt, 96pt, 120pt, 144pt) according to the Google Fonts Axis Registry. [code: invalid-name]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---
Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Combined length of family and style must not exceed 27 characters.</summary>

* [com.google.fonts/check/name/family_and_style_max_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/family_and_style_max_length)
<pre>--- Rationale ---
According to a GlyphsApp tutorial [1], in order to make sure all versions of
Windows recognize it as a valid font file, we must make sure that the
concatenated length of the familyname (NameID.FONT_FAMILY_NAME) and style
(NameID.FONT_SUBFAMILY_NAME) strings in the name table do not exceed 20
characters.
After discussing the problem in more detail at `FontBakery issue #2179 [2] we
decided that allowing up to 27 chars would still be on the safe side, though.
[1] https://glyphsapp.com/tutorials/multiple-masters-part-3-setting-up-instances
[2] https://github.com/googlefonts/fontbakery/issues/2179</pre>

* ⚠ **WARN** The combined length of family and style exceeds 27 chars in the following 'WINDOWS' entries:
 FONT_FAMILY_NAME = 'Big Shoulders Text Thin' / SUBFAMILY_NAME = 'Regular'

Please take a look at the conversation at https://github.com/googlefonts/fontbakery/issues/2179 in order to understand the reasoning behind these name table records max-length criteria. [code: too-long]

</details>
<details>
<summary>⚠ <b>WARN:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---
Variable font family directories kept in the google/fonts git repo may include a
static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.</pre>

* ⚠ **WARN** Please consider adding a subdirectory called "static/" and including in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Ensure Stylistic Sets have description.</summary>

* [com.google.fonts/check/stylisticset_description](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description)
<pre>--- Rationale ---
Stylistic sets should provide description text. Programs such as InDesign,
TextEdit and Inkscape use that info to display to the users so that they know
what a given stylistic set offers.</pre>

* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if OS/2 xAvgCharWidth is correct.</summary>

* [com.google.fonts/check/xavgcharwidth](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/os2.html#com.google.fonts/check/xavgcharwidth)

* ⚠ **WARN** OS/2 xAvgCharWidth is 549 but it should be 664 which corresponds to the average of the widths of all glyphs in the font. [code: xAvgCharWidth-wrong]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there any misaligned on-curve points?</summary>

* [com.google.fonts/check/outline_alignment_miss](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/<Section: Outline Correctness Checks>.html#com.google.fonts/check/outline_alignment_miss)
<pre>--- Rationale ---
This check heuristically looks for on-curve points which are close to, but do
not sit on, significant boundary coordinates. For example, a point which has a
Y-coordinate of 1 or -1 might be a misplaced baseline point. As well as the
baseline, here we also check for points near the x-height (but only for lower
case Latin letters), cap-height, ascender and descender Y coordinates.
Not all such misaligned curve points are a mistake, and sometimes the design may
call for points in locations near the boundaries. As this check is liable to
generate significant numbers of false positives, it will pass if there are more
than 100 reported misalignments.</pre>

* ⚠ **WARN** The following glyphs have on-curve points which have potentially incorrect y coordinates:
	* uni1E9E: X=296.0,Y=1602.0 (should be at cap-height 1600?)
	* uni1E9E: X=538.0,Y=1602.0 (should be at cap-height 1600?)
	* uni1E64: X=294.0,Y=1970.0 (should be at ascender 1968?)
	* uni1E64: X=392.0,Y=1970.0 (should be at ascender 1968?)
	* uni1E66: X=294.0,Y=1970.0 (should be at ascender 1968?)
	* uni1E66: X=392.0,Y=1970.0 (should be at ascender 1968?)
	* uni1EAB: X=219.0,Y=1598.0 (should be at cap-height 1600?)
	* uni1EAB.ss01: X=207.0,Y=1598.0 (should be at cap-height 1600?)
	* ampersand: X=704.0,Y=2.0 (should be at baseline 0?)
	* ampersand.sc: X=700.0,Y=2.0 (should be at baseline 0?) and 53 more. [code: found-misalignments]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 6 | 45 | 9 | 142 | 0 |
| 0% | 1% | 3% | 22% | 4% | 70% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## [BigShoulderText_QA.zip](https://github.com/google/fonts/files/6822319/BigShoulderText_QA.zip)

**Comment by RosaWagner** [comment]
So indeed, the opsz axis shouldn't appear in the STAT, but this is a problem with the builder, so we gonna try to implement a variable slicer in there that does it correctly.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Text: Version 2.002 added

---
 04323d4: [gftools-packager] Big Shoulders Text: Version 2.002 added

* Big Shoulders Text Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/465a9c592f06d493841b35dca5d248c8142b75f8.

 d31dd2c: [gftools-packager] ofl/bigshoulderstext remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> So indeed, the opsz axis shouldn't appear in the STAT, but this is a problem with the builder, so we gonna try to implement a variable slicer in there that does it correctly.

The PR has been updated to solve this.

**Pull request merged**
