### PR TITLE
Added link (to view all fonts in a 3D projection) to README.

### PR DESCRIPTION
**Pull request by py-ranoid**
I had extracted low dimensional representations of all Google Fonts with a variational auto-encoder. font2vec.vishalgupta.me has a 3D projection of vectors of all fonts.

### CODE REVIEW

**Comment by py-ranoid** [comment]
I signed it!

**Comment by m4rc1e** [comment]
Thanks for the Pr.

Just curious but what's the purpose of this? choosing similar fonts?

**Comment by eliheuer** [comment]
Interesting. Is there a git repo for this project?
 
screen shot 2018-10-26 at 1 41 48 pm

**Comment by eliheuer** [comment]
This is a nice tech demo, but I don't think it's usable or helpful enough to include in the readme. For something like this to be useful, lots of work would need to go into designing a user interface.

**Comment by davelab6** [comment]
Moving to the TRIVIA file :)

**Pull request closed without merging**
