### PR TITLE
Big Shoulders Display: Version 2.000 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
07cb680: [gftools-packager] Big Shoulders Display: Version 2.000 added

* Big Shoulders Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 f6ed97e: [gftools-packager] ofl/bigshouldersdisplay remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This PR upgrades [Big Shoulders Display](https://fonts.google.com/specimen/Big+Shoulders+Display?query=Big) into a Variable Font.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Display: Version 2.000 added

---
 85b6476: [gftools-packager] Big Shoulders Display: Version 2.000 added

* Big Shoulders Display Version 2.000 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/41153e6fe01d218e933919a1d08c8e45065bc8fe.

 551b9b4: [gftools-packager] ofl/bigshouldersdisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Display: Version 2.002 added

---
 c594250: [gftools-packager] Big Shoulders Display: Version 2.002 added

* Big Shoulders Display Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/c32776c15acba7f76797d45cfeb27d1c2a1738a0.

 cb4f841: [gftools-packager] ofl/bigshouldersdisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
The font includes now the `ExtraLight` Instance.

**Comment by RosaWagner** [comment]
All looks good, but same comment as in #3432, not sure if the opsz axis should appear in the STAT table.

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Display: Version 2.002 added

---
 287290f: [gftools-packager] Big Shoulders Display: Version 2.002 added

* Big Shoulders Display Version 2.002 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/465a9c592f06d493841b35dca5d248c8142b75f8.

 57ec853: [gftools-packager] ofl/bigshouldersdisplay remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> All looks good, but same comment as in #3432, not sure if the opsz axis should appear in the STAT table.

The PR has been updated to solve this.

**Comment by RosaWagner** [comment]
We can also update all Big Shoulders' descriptions with links

**Pull request merged**
