### PR TITLE
Edu AU VIC WA NT Cursive: Version 1.000 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/SorkinType/VICWANTSchoolHandAustralia at commit https://github.com/SorkinType/VICWANTSchoolHandAustralia/commit/abab94d19985f24132e45db4c4822b042eb63302.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Review by vv-monsalve — APPROVED** [review]

**Comment by simoncozens** [comment]
I want to fix the connections of glyphs with accents before we merge this. @EbenSorkin is testing.

**Comment by vv-monsalve** [comment]
@simoncozens, @EbenSorkin 

- Please review the quotes spacing or kerning. Next to `s` the quotes look like diacritic marks
    Screenshot 2024-08-15 at 22 04 43

**Comment by EbenSorkin** [comment]
That does look like excessive kerning tp me.

I can do a pass on it on Friday.

**Comment by simoncozens** [comment]
Closing in favour of #8320, which fixes the spacing issue.

**Pull request closed without merging**
