### PR TITLE
Comforter: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
503f8fe: [gftools-packager] Comforter: Version 1.010; ttfautohint (v1.8.3) added

* Comforter Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/comforter at commit https://github.com/googlefonts/comforter/commit/9d9f0db4b5c5bcce6840ae6dea893ec0c4f75e50.

 e6af33b: [gftools-packager] ofl/comforter remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Comforter is part of TypeSetIt Batch 2 projects

**Comment by RosaWagner** [comment]
g.fina and x.fina have a tight spacing compare to the other ones, was that kind of issue you were talking about during our last call?
Capture d’écran 2021-09-16 à 14 13 53

**Comment by vv-monsalve** [comment]
> g.fina and x.fina have a tight spacing compare to the other ones, was that kind of issue you were talking about during our last call?

Among others

**Comment by vv-monsalve** [comment]
Updated

## Comforter: Version 1.010; ttfautohint (v1.8.3) added

---
 f2261dc: [gftools-packager] Comforter: Version 1.010; ttfautohint (v1.8.3) added

* Comforter Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/comforter at commit https://github.com/googlefonts/comforter/commit/9d9f0db4b5c5bcce6840ae6dea893ec0c4f75e50.

 b973800: [gftools-packager] ofl/comforter remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> g.fina and x.fina have a tight spacing compare to the other ones, was that kind of issue you were talking about during our last call?

Updated, both this and Comforter Brush

**Comment by vv-monsalve** [comment]
Hi @RosaWagner, I've changed the `fina` fea as we talked last time and it's working. So I'll take your report on fina spacing as an opportunity to update the PRs again (both for this and the Brush version) using it instead in the `calt` which is automatically activated.

**Comment by vv-monsalve** [comment]
Updated

## Comforter: Version 1.013; ttfautohint (v1.8.3) added

---
 87d8d0c: [gftools-packager] Comforter: Version 1.013; ttfautohint (v1.8.3) added

* Comforter Version 1.013; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/comforter at commit https://github.com/googlefonts/comforter/commit/3112f6b6990f10c7a101e5577b8267988989cff7.

 a9a8596: [gftools-packager] ofl/comforter remove METADATA "source".  google/fonts#2587

**Pull request merged**
