### PR TITLE
Babylonica: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
32cccf0: [gftools-packager] Babylonica: Version 1.010; ttfautohint (v1.8.3) added

* Babylonica Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/babylonica at commit https://github.com/googlefonts/babylonica/commit/39b985f83f2186579d4f78e21205b1b379015b80.

 9583bc7: [gftools-packager] ofl/babylonica remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Babylonica is part of Batch 5 of TypeSetIT fonts.

**Comment by RosaWagner** [comment]
This one still have the apple logo, I know you guys usually replace it by a head. @vv-monsalve shall I merge anyway?

**Comment by vv-monsalve** [comment]
Updated

## Babylonica: Version 1.010; ttfautohint (v1.8.3) added

---
 9ff4202: [gftools-packager] Babylonica: Version 1.010; ttfautohint (v1.8.3) added

* Babylonica Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/babylonica at commit https://github.com/googlefonts/babylonica/commit/7b1c733f74a11604a711e87f840010e0746cfcd1.

**Comment by vv-monsalve** [comment]
> This one still have the apple logo, I know you guys usually replace it by a head. @vv-monsalve shall I merge anyway?

We haven't been checking this on the fonts as part of the long list of confirmations for TSI projects tbh. But out of consistency, I've updated the PR. 

Also, I wanted to test again the PR with packager without using the `--no-source` flag, and when doing so indeed the repo URL doesn't get included in the [upstream.yml](ofl/babylonica/upstream.yaml) file as reported by FB.

Haven't adjusted it manually yet so that we could inspect this.

**Comment by RosaWagner** [comment]
> Also, I wanted to test again the PR with packager without using the --no-source flag, and when doing so indeed the repo URL doesn't get included in the [upstream.yml](https://github.com/google/fonts/pull/ofl/babylonica/upstream.yaml) file as reported by FB.

I think it's correct since the source field is in metadata.pb

**Pull request merged**
