### PR TITLE
Noto Serif Gujarati: Version 2.105 added

### PR DESCRIPTION
**Pull request by simoncozens**
7180e58: [gftools-packager] Noto Serif Gujarati: Version 2.105 added

* Noto Serif Gujarati Version 2.105 taken from the upstream repo https://github.com/notofonts/gujarati.git at commit https://github.com/notofonts/gujarati/commit/.

### CODE REVIEW

**Comment by emmamarichal** [comment]
I found this interpolation issue, but otherwise all looks good!

https://github.com/google/fonts/assets/64773544/2d2b5dcd-6755-47a8-81fe-d89875f29732

**Comment by RosaWagner** [comment]
@simoncozens can you also confirm this is okay

old
Screenshot 2023-10-26 at 11 25 32

new
Screenshot 2023-10-26 at 11 25 25

**Comment by simoncozens** [comment]
Doing another release to fix.

**Comment by simoncozens** [comment]
No, that RU is definitely not OK.

**Comment by simoncozens** [comment]
Updated

## Noto Serif Gujarati: Version 2.106 added

---
 f4b148a: [gftools-packager] Noto Serif Gujarati: Version 2.106 added

* Noto Serif Gujarati Version 2.106 taken from the upstream repo https://github.com/notofonts/gujarati.git at commit https://github.com/notofonts/gujarati/commit/.

**Review by emmamarichal — APPROVED** [review]

**Review by RosaWagner — APPROVED** [review]

**Pull request merged**
