### PR TITLE
ScrambleFont

### PR DESCRIPTION
**Pull request by NgineerBabu**
https://github.com/NgineerBabu/ScrambleFont

### CODE REVIEW

**Comment by NgineerBabu** [comment]
I signed it!

**Comment by NgineerBabu** [comment]
I signed it!

**Comment by m4rc1e** [comment]
Your PR doesn't contain the font mentioned in your upstream. You've just resubmitted previous commits. Am I missing something?

**Comment by NgineerBabu** [comment]
I have signed the CLA agreement 
And the fonts files are accesible in below github link

https://github.com/NgineerBabu/ScrambleFont

**Pull request closed without merging**
