### PR TITLE
Oooh Baby: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
0691688: [gftools-packager] Oooh Baby: Version 1.010; ttfautohint (v1.8.3) added

* Oooh Baby Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/oooh-baby at commit https://github.com/googlefonts/oooh-baby/commit/e2057b877276becfcbda165dbadcfeaac38f0574.

 d5bbaf3: [gftools-packager] ofl/ooohbaby remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Part of Batch 4 of TypeSetIT fonts.

**Comment by RosaWagner** [comment]
Noted 2 stuff about diacritics, I don't know if it's wanted: 
- dots position on /i and /j has quite of a gap. 
- /circumflex on /e is higher than the other.

Capture d’écran 2021-11-25 à 11 25 24
Capture d’écran 2021-11-25 à 11 24 49

**Comment by vv-monsalve** [comment]
> Noted 2 stuff about diacritics, I don't know if it's wanted:

They are not wanted indeed. Thanks for the report.

**Comment by vv-monsalve** [comment]
Updated

## Oooh Baby: Version 1.011; ttfautohint (v1.8.3) added

---
 ddd571a: [gftools-packager] Oooh Baby: Version 1.011; ttfautohint (v1.8.3) added

* Oooh Baby Version 1.011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/oooh-baby at commit https://github.com/googlefonts/oooh-baby/commit/f36e2452e1c1a793fcf49524ab392eb6a2cd1dce.

 94d4906: [gftools-packager] ofl/ooohbaby remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
> Noted 2 stuff about diacritics, I don't know if it's wanted:

PR updated now

**Pull request merged**
