### PR TITLE
normalized all chinese METADATA.pb

### PR DESCRIPTION
**Pull request by marekjez86**
normalized all chinese METADATA.pb

### CODE REVIEW

**Comment by marekjez86** [comment]
ALL chinese scripts support the following
languages: "cjy_Han{s,t}"  # Chinese, Jinyu
languages: "gan_Han{s,t}"  # Gan Chinese
languages: "hak_Han{s,t}"  # Hakka Chinese
languages: "hsn_Han{s,t}"  # Xiang Chinese
languages: "lzh_Han{s,t}"  # Literary Chinese
languages: "nan_Han{s,t}"  # Min Nan Chinese
languages: "wuu_Han{s,t}"  # Wu Chinese
languages: "yue_Han{s,t}"  # Cantonese
languages: "za_Han{s,t}"   # Zhuang, Han
languages: "zh_Han{s,t}"   # Chinese

where Hant is used for HK and TC and Hans is used for SC

**Review by nathan-williams — APPROVED** [review]

**Comment by RosaWagner** [comment]
@andyjgf do you approve this pull request?

**Comment by RosaWagner** [comment]
@andyjgf do you approve this pull request?

**Comment by marekjez86** [comment]
@RosaWagner : Nathan's approval is enough

**Comment by RosaWagner** [comment]
@marekjez86 @chrissimpkins @nathan-williams 

It looks like the content of this PR went to sandbox, but the font do miss languages compared to their METADATA.pb.

For example, this is the language menu for Noto Serif and Sans HK:

Capture d’écran 2022-07-22 à 16 15 55

And this is their METADATA.pb:

- [x] languages: "cjy_Hant"  # Chinese, Jinyu
- [x] languages: "gan_Hant"  # Gan Chinese
- [ ] languages: "hak_Hant"  # Hakka Chinese, Traditional
- [x] languages: "hsn_Hant"  # Xiang Chinese
- [ ] languages: "lzh_Hant"  # Literary Chinese, Traditional
- [x] languages: "nan_Hant"  # Min Nan Chinese, Traditional
- [x] languages: "wuu_Hant"  # Wu Chinese
- [ ] languages: "yue_Hant"  # Cantonese
- [ ] languages: "za_Hant"   # Zhuang, Traditional Han
- [x] languages: "zh_Hant"   # Chinese (Traditional)

Is there a problem with the lang text protos ?

**Comment by nathan-williams** [comment]
WAI as currently structured. To have those other languages appear in Catalog, please add regions to the text protos. For example, the other languages list at least: `region: "CN"`.

**Comment by vv-monsalve** [comment]
> WAI as currently structured.

So the PR could be moved as it is now to production?

> To have those other languages appear in Catalog, please add regions to the text protos.

If it is working as intended, then I'm not sure if this is what @marekjez86 was addressing by this PR.

@chrissimpkins

**Comment by nathan-williams** [comment]
```
So the PR could be moved as it is now to production?
```

Yes, no risk with moving this PR forward. If the desired result is to have those other languages be named in the UI, we can add `region: "CN"` to their textprotos in a separate PR.

**Comment by chrissimpkins** [comment]
> ```
> So the PR could be moved as it is now to production?
> ```
> 
> Yes, no risk with moving this PR forward. If the desired result is to have those other languages be named in the UI, we can add `region: "CN"` to their textprotos in a separate PR.

Thanks Nate.

@vv-monsalve we're sure that the missing UI languages are supported?  If so, I suggest that we open a new issue to add `region: "CN"` on each of the projects that Marek updated here.

**Comment by chrissimpkins** [comment]
> on May 26

Marek indicates that this is the case in https://github.com/google/fonts/pull/4722#issuecomment-1139127250

**Comment by chrissimpkins** [comment]
> > ```
> > So the PR could be moved as it is now to production?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Yes, no risk with moving this PR forward. If the desired result is to have those other languages be named in the UI, we can add `region: "CN"` to their textprotos in a separate PR.
> 
> Thanks Nate.
> 
> @vv-monsalve we're sure that the missing UI languages are supported? If so, I suggest that we open a new issue to add `region: "CN"` on each of the projects that Marek updated here.

Marek indicates that this is the case in https://github.com/google/fonts/pull/4722#issuecomment-1139127250

**Comment by vv-monsalve** [comment]
> I suggest that we open a new issue to add `region: "CN"` on each of the projects that Marek updated here.

In that case, it should be done to their textprotos. 

However, inspecting the current `.textproto` files of the languages not listed yet, some of them are also missing a sample text needed to reflect the differences in the language when it's picked from the list.

- "hak_Hant"  # Hakka Chinese, Traditional
- "lzh_Hant"  # Literary Chinese, Traditional - Missing
- "za_Hant"   # Zhuang, Traditional Han

E.g current `hak_Hant` file only has:

```
id: "hak_Hant"
language: "hak"
script: "Hant"
name: "Hakka Chinese, Traditional"
```

**Comment by vv-monsalve** [comment]
@nathan-williams said:

> When a language that doesn't have sample text is selected, we show a blended/hybrid sample text that combined the sample text of other languages of the same script.

**Comment by vv-monsalve** [comment]
> we're sure that the missing UI languages are supported?

From Marek's [above comment](https://github.com/google/fonts/pull/4722#issuecomment-1139127250) it seems so.

**Comment by vv-monsalve** [comment]
This PR seems to have hit production, but would not be possible to verify it until #5088 hits it as well.

**Pull request merged**
