### PR TITLE
Noto Sans Syloti Nagri: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
f83507e: [gftools-packager] Noto Sans Syloti Nagri: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Syloti Nagri Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/syloti-nagri.git at commit https://github.com/notofonts/syloti-nagri/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens 

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by simoncozens** [comment]
This is a bug (https://github.com/notofonts/syloti-nagri/issues/6). Re-releasing.

**Comment by RosaWagner** [comment]
@simoncozens tofu in sample text

Capture d’écran 2022-10-26 à 13 48 35

**Comment by simoncozens** [comment]
Glyphset issue was fixed in https://github.com/googlefonts/glyphsets/pull/79. Maybe eng team need to pull the new glyphsets?

**Pull request merged**
