### PR TITLE
cormorant: v3.301 added

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by CatharsisFonts** [comment]
Did you use v3.301? Why not v3.500?

https://github.com/CatharsisFonts/Cormorant/releases

**Comment by m4rc1e** [comment]
Because this pr was made in January.

**Comment by CatharsisFonts** [comment]
> Because this pr was made in January.
I know. 🙄 

In any case, the current live version on GF definitely still features the bug:
screen shot 2017-06-19 at 10 30 17

I do hope it's not going to take another half year for the fix to be implemented... 😬

**Comment by m4rc1e** [comment]
It was uploaded within the same week if I remember correctly. I'm just closing issues at the moment.

**Comment by CatharsisFonts** [comment]
Ah, OK, that would explain it. 😉 Any chance we might get that bug-fixing update uploaded soon?

**Pull request merged**
