### PR TITLE
Features GIF For Readme

### PR DESCRIPTION
**Pull request by mohitjaisal**
# Features Gif Preview: 

</img>

- [x]  Highly Compressed Gif
- [x]  Seo Friendly Name for Gif [ **GoogleFontsFeatures** ]
- [x]  Gif link in the readme file is **./GoogleFontsFeatures.gif** (Root directory so that it remains there in future)
- [x]  This branch has no conflicts with the base branch

### CODE REVIEW

**Comment by mohitjaisal** [comment]
@davelab6 Please Review this PR✔️

**Comment by mohitjaisal** [comment]
@davelab6 & @m4rc1e Please Review this PR✔️

**Comment by davelab6** [comment]
@mohitjaisal thanks for your efforts on this. Sadly, since the catalog is regularly updated, and we have no way to keep this gif updated as the site changes, I am rejecting this. Also, since its 32Mb, I think its a bit excessive. A static image might be OK, but the updates issue remains.

**Comment by mohitjaisal** [comment]
> @mohitjaisal thanks for your efforts on this. Sadly, since the catalog is regularly updated, and we have no way to keep this gif updated as the site changes, I am rejecting this. Also, since its 32Mb, I think its a bit excessive. A static image might be OK, but the updates issue remains.

Thanks for your kind review 👍

**Pull request closed without merging**
