### PR TITLE
Funnel Display: Version 1.000 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/Dicotype/Funnel at commit https://github.com/Dicotype/Funnel/commit/57136df97ea2e966aab4fe45f540afb5ad74dfc4.
## PR Checklist:

- [x] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [x] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [x] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not) https://github.com/google/fonts/issues/8203
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [x] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal From the red label I'm taking, this is not ready to review yet. Ping me when you consider it ready for review.

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
@vv-monsalve Done!
For the designer Warn, the NORD ID one is normal, I opened an issue about it.
But for: 

```
⚠️ WARN
It seems that Kristian Möller is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry.
```

It's weird because Kristian is already in the catalog and it works well: https://fonts.google.com/specimen/Afacad/about?query=Kristian+M%C3%B6ller

see also: https://github.com/google/fonts/blob/main/catalog/designers/kristianmoller/info.pb

**Comment by vv-monsalve** [comment]
> It's weird because Kristian is already in the catalog and it works well

Weird indeed. I've just checked the info.pb and confirmed it's the exact spelling. @felipesanches this could probably be another regression from the latest version (mentioned in the meeitng).

**Comment by vv-monsalve** [comment]
> ⚠️ WARN
In order to optimize performance on some legacy renderers, the value of unitsPerEm at the head table should ideally be a power of 2 between 16 to 16384. And values of 1000 and 2000 are also common and may be just fine as well. But we got 1200 instead.

The vertical metrics look a bit tight to leave room for added languages in the future. Let me know if you would prefer to continue with them as they are. Currently, they sum up 1500 units, but given the font's UPM is 1200. This implies they are at 125%. You could make them 130% if you want to leave a bit more loose.

Screenshot 2024-09-27 at 13 25 41

**Comment by emmamarichal** [comment]
@vv-monsalve Ah yes, I remember now: 
I would let it like this, because the designer added two values, a default one and a localised one:
Screenshot 2024-10-02 at 11 30 40

For v-metrics, I'm ok to let them like this since it's a Display, but I'll ask confirmations for the text version. I'll ping you once it's ready! :)

**Comment by vv-monsalve** [comment]
> I would let it like this, because the designer added two values, a default one and a localised one:

But remember that this kind of mismatch prevents the designer from being listed in the About section for this font. We had a similar case recently.



> For v-metrics, I'm ok to let them like this since it's a Display, but I'll ask confirmations for the text version. I'll ping you once it's ready! :)

In this case, it's not about leaving more room for updates but the other requirement about the Caps being centered in the line to benefit UI usage.

**Comment by emmamarichal** [comment]
@vv-monsalve 

> But remember that this kind of mismatch prevents the designer from being listed in the About section for this font. We had a similar case recently.

Afacad Flux (that has been merged recently) has the same configuration (with the localised writting), and it works here: https://fonts.google.com/specimen/Afacad+Flux/about?query=afacad+flux

I would make an exception here, to let the possibility to have several way of writing it. Do you remember the case? I would be curious to see what wasn't working!

> In this case, it's not about leaving more room for updates but the other requirement about the Caps being centered in the line to benefit UI usage.

Ah right, I'll modify them then!

**Comment by vv-monsalve** [comment]
> Afacad Flux (that has been merged recently) has the same configuration (with the localised writting), and it works here: https://fonts.google.com/specimen/Afacad+Flux/about?query=afacad+flux

Okay. Let's merge and see how it goes.

After rechecking the above image, the VMs are centered (they were briefly confused with another project).
If you are okay with them as they are now, I can merge it here.

**Comment by ktkm** [comment]
> The vertical metrics look a bit tight to leave room for added languages in the future. Let me know if you would prefer to continue with them as they are. Currently, they sum up 1500 units, but given the font's UPM is 1200. This implies they are at 125%. You could make them 130% if you want to leave a bit more loose.

If I understand correctly -- this was never an issue, right?

**Comment by emmamarichal** [comment]
@ktkm Exactly! sorry for the confusion

**Pull request merged**
