### PR TITLE
Adds fixes to typographic tag issues identified by Evan

### PR DESCRIPTION
**Pull request by kalapi**
@evanwadams Fixed the typographic tag issues you pointed out in the following link:

https://docs.google.com/spreadsheets/d/1cNUL2i6C5heKMD6v0W1jdUBluO37L9PshzrI7fXzPOc/edit?gid=1033747182#gid=1033747182

### CODE REVIEW

**Comment by evanwadams** [comment]
Kalapi, I'm seeing that your branch has conflicts that need to be resolved. 

Can you take care of that?

Thanks, Evan

**Comment by kalapi** [comment]
> Kalapi, I'm seeing that your branch has conflicts that need to be resolved.
> 
> Can you take care of that?
> 
> Thanks, Evan

Hi Evan, didn't see this. I'll look into it tomorrow.

**Comment by kalapi** [comment]
@evanwadams Can you run the workflow and check if this fixes it?

**Comment by evanadams-zz** [comment]
Things look good.  Kalapi's typographic changes have been merged and the
file is now sorted.

    Evan

**Pull request closed without merging**
