### PR TITLE
Manjari: Version 1.810 added

### PR DESCRIPTION
**Pull request by graphicore**
* Manjari Version 1.810 taken from the upstream repo https://github.com/smc/manjari.git at commit https://github.com/smc/manjari/commit/7cdabff487afbeb7471f4554f79e006046421850.

### CODE REVIEW

**Comment by graphicore** [comment]
**CAUTION** I have experimented with a version of `gftools packager` here that enables building binaries. The upstream does not contain font binaries, but clear build instructions. We'll have to discuss how to handle this case, but to move forward the updating process, I decided this version is a good start.

**Comment by vv-monsalve** [comment]
Updated

## Manjari: Version 1.920 added

---
 9660329: [gftools-packager] Manjari: Version 1.920 added

* Manjari Version 1.920 taken from the upstream repo https://gitlab.com/smc/fonts/manjari.git at commit 83656f3a02205b60ce826410385c1387009ec770.

 c4ab3cc: [gftools-packager] ofl/manjari remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
@googlebot I consent

**Comment by vv-monsalve** [comment]
### Diffenator Results on Regular
(as a sample)

**gdef base new**
gdef_base_new
**glyphs modified**
glyphs_modified
**glyphs new**
glyphs_new

**Comment by vv-monsalve** [comment]
### Diff Browsers

**OS X High Sierra Safari11**
Desktop_OS_X_High_Sierra_safari_11 1_
**Windows 10 Chrome 69**
Desktop_Windows_10_chrome_69 0_
**Windows 10 Firefox 62**
Desktop_Windows_10_firefox_62 0_

**Comment by vv-monsalve** [comment]
### Cyreal comparisons 

After seeing the Diffbrowsers results where there it seems like if it would be a change in vertical metrics, new comparisons were done in Cyreal webpage, but no regressions on Vertical Metrics were seen.
 
**Paragraphs**

Manjari-Text

**Glyphs**

Manjari-Lettering

**Layout**

Manjari-Layout

**Comment by RosaWagner** [comment]
- Is there a particular reason for the change of vertical metrics ?
- Is it somehow possible to keep the previous ones ?

**Comment by vv-monsalve** [comment]
> * Is there a particular reason for the change of vertical metrics ?
> * Is it somehow possible to keep the previous ones ?

It's being reviewed in the [Vertical Metrics issue](https://github.com/smc/manjari/issues/4)

**Comment by vv-monsalve** [comment]
Updated

## Manjari: Version 2.000 added

---
 f396e63: [gftools-packager] Manjari: Version 2.000 added

* Manjari Version 2.000 taken from the upstream repo https://gitlab.com/smc/fonts/manjari.git at commit daba7c592ea3d51358c2c1368bb9d09c8a6e2c37.

 b0acec7: [gftools-packager] ofl/manjari remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
Comments on PR:

- The reported Fails on Vertical Metrics were reviewed in [this Issue](https://github.com/smc/manjari/issues/4#issuecomment-731165635)
- There could be small spacing regressions but they were reviewed [here](https://github.com/smc/manjari/issues/14#issuecomment-776917468)

**Pull request closed without merging**
