### PR TITLE
Noto Sans Saurashtra: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
413165e: [gftools-packager] Noto Sans Saurashtra: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Saurashtra Version 2.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/saurashtra.git at commit https://github.com/notofonts/saurashtra/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens 
Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
Updated

## Noto Sans Saurashtra: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

---
 ade29ce: [gftools-packager] Noto Sans Saurashtra: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Saurashtra Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/saurashtra.git at commit https://github.com/notofonts/saurashtra/commit/.

**Comment by chrissimpkins** [comment]
This build shows up as v2.002 in dev

**Comment by simoncozens** [comment]
That's fine; PR was updated with a new version but I didn't update the title.

**Pull request merged**
