### PR TITLE
[gftools-packager] Kode Mono: Version 1.000;gftools[0.9.28] added

### LINKED ISSUE #6191: Add Kode Mono VF
[**https://github.com/isaozler/kode-mono**](https://github.com/isaozler/kode-mono)

A custom-designed typeface explicitly created for the developer community.

**Requirements:**

I understand that Google Fonts will publish only fonts that matches its requirements, and I can confirm the project meets them (by ticking the cases, or putting x between the square brackets in text mode):

- [x] The entire font project is licensed under the [OFL](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
- [x] There is no "Reserved Font Name" mention in the OFL license
- [x] Family name is unique according to namecheck.fontdata.com
- [x] The font supports at least [GF Latin Core glyphset](https://github.com/googlefonts/glyphsets/tree/main/GF_glyphsets/Latin/)
- [x] The repository respect the [upstream repo structure](https://googlefonts.github.io/gf-guide/upstream.html)
- [x] The source files are available in the repository
- [x] I read, agree and comply with the full [contributing requirements](https://googlefonts.github.io/gf-guide/onboarding.html)
- [x] I am the author of the font or the author agreed to this submission
- [x] I will maintain the repository

Kode Mono cover

### PR DESCRIPTION
**Pull request by isaozler**
* Kode Mono Version 1.000;gftools[0.9.28] taken from the upstream repo https://github.com/isaozler/kode-mono at commit https://github.com/isaozler/kode-mono/commit/15b36a40179d3678e0fe8bff19903af09c0fc0f7.

fixes #6191

### CODE REVIEW

**Comment by isaozler** [comment]
Hi Rosa @RosaWagner Marc @m4rc1e, if there is anything I can do to assist or expedite the process, please let me know. I am more than willing to offer additional information or address any concerns arising during the review.

Thank you for your hard work and continued commitment to maintaining this exceptional collection of fonts. I understand the challenges you face, and I genuinely appreciate the opportunity to contribute to it.

**Comment by RosaWagner** [comment]
@isaozler we are very grateful you made a PR and all but it bypasses our submission process ;) We first have to discuss if the font gets accepted during a quarterly intake meeting. We'll let you know.

**Comment by isaozler** [comment]
Thanks, Rosa. Looking forward to hearing from you.

**Comment by RosaWagner** [comment]
@isaozler this PR has been open for a while. So I'm closing it. Please feel free to re-do it when the font is ready for onboarding.

**Comment by isaozler** [comment]
In the first week of December, I planned to update the font with all the fixes, and it is ready for onboarding. 🙏 Thanks for the support @RosaWagner

**Comment by isaozler** [comment]
@RosaWagner So I refactored it into Glyphs.app instead of FontLab. All issues are fixed (fontbakery-report: https://isaozler.github.io/kode-mono/fontbakery/fontbakery-report.html) except for an experimental check.

image

what should I do with this?

**Comment by isaozler** [comment]
@RosaWagner Created a new PR 
https://github.com/google/fonts/pull/7136

**Comment by RosaWagner** [comment]
Hi @isaozler, I am in a sabbatical and not contracted by Google anymore. Therefore it will be picked up by someone else after the holidays and no need to tag me in issues or PRs. Cheers!

**Comment by isaozler** [comment]
Have a fantastic sabbatical! Wishing you all the best during your time off. Take care!

**Pull request closed without merging**
