### PR TITLE
Improve and extend Namelist file format documentation.

### PR DESCRIPTION
**Pull request by graphicore**
This is a living PR for discussion. **Don't merge it** until we agree that it is good.

### CODE REVIEW

**Comment by davelab6** [comment]
Great work! Please assign to me when ready to merge

**Comment by davelab6** [comment]
@graphicore is this ready to merge?

**Comment by graphicore** [comment]
> Great work! Please assign to me when ready to merge

Uh, I missed this. Thanks.

I'm rather happy with this. The biggest three issues for me right now are:

1. The  `tools/encodings/README.md` has a passage at the top "**TODO: clarify:** Typically all the Unicodes in each file are in each font." That sentence is hard for me to understand, it seems that it's just not true. Do I miss something?
2. Since you seem to agree with what I did to the Namelist format, especially the `#$ include` headers. I should remove all parts in `tools/encodings/README.md` that say it's a "proposal". Also, I'd clean it up once more in general, in case I see something more
3. Wrong includes could also be fixed later, but in general, are the dependencies via the  `#$ include` headers declared correctly? At the moment, the newly added Greek encodings don't have these headers, so that should be fixed. And the "optional" encodings don't have these headers. The latter usually don't have unicode codepoints, so it's not important for the CLDR/language detection related stuff. 

Other things can be done in a subsequent PR, like tasks derrived from  #660 and #624

**Comment by graphicore** [comment]
I'll tackle the remarks above later today, as far as I can.

**Comment by graphicore** [comment]
What I did:

1. just removed the "**TODO: clarify:**". This must have made sense before, so maybe I'm reading it wrong. Feel free to comment/ask for a change on this one before you merge.
2. I had another go on that README.md file, I think it's OK now.
3. I added include rules to Greek core, plus and expert. The rest can be dealt with later, I'll have some questions anyways.

**Comment by graphicore** [comment]
I just removed  including `GF-latin-plus_unique-glyphs.nam` into `GF-greek-core.nam` because of: https://github.com/graphicore/specimenTools/issues/19

Note that we should probably create `GF-latin-core.nam` because that should be included by `GF-greek-core.nam`.

I'd rather do this and other changes on the encodings in a separate PR which would however depend on this PR. Or I can just add to this PR. What should I do?

**Comment by graphicore** [comment]
closed by merging #685

**Comment by davelab6** [comment]
Thanks!

> "TODO: clarify: Typically all the Unicodes in each file are in each font." That sentence is hard for me to understand, it seems that it's just not true. Do I miss something?

I guess that there are a couple of things to take from that. 

1. all the unicode characters specified in a glyph set definition should be available as drawn glyphs in each font that meets that definition, and

2. all the fonts in a family should have the same unicode encoded glyphs. There is a FB issue to track that.

**Comment by graphicore** [comment]
> 1. all the unicode characters specified in a glyph set definition should be available as drawn glyphs in each font that meets that definition, and

I think the key here is saying **should**, we'll have to update fonts from time to time to keep the glyph set definitions and the fonts in sync.

@davelab6, somehow related, could you have look at this please? https://github.com/graphicore/specimenTools/issues/20

**Pull request closed without merging**
