### PR TITLE
Tilt Neon: Version 1.000 added

### PR DESCRIPTION
**Pull request by yanone**
1ff103a: [gftools-packager] Tilt Neon: Version 1.000 added

* Tilt Neon Version 1.000 taken from the upstream repo https://github.com/googlefonts/Tilt-Fonts at commit https://github.com/googlefonts/Tilt-Fonts/commit/a6ebddfad88d0f6d91865eaa31aeb05fe685fe62.

### CODE REVIEW

**Comment by yanone** [comment]
Hi. Please don't make me add the missing glyphs here. I don't think that's possible for me to pull off given the complicated pseudo 3-dimensional design of the shapes.

Otherwise, these fonts are missing a `wght` axis, hence the STAT table FAIL. 

The above applies to all three Tilt fonts identically.

**Comment by chrissimpkins** [comment]
The axes were registered as [XROT](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/x_rotation.textproto) and [YROT](https://github.com/googlefonts/axisregistry/blob/main/Lib/axisregistry/data/y_rotation.textproto).  

The axis registrations are ready and this family can be pushed to sandbox as soon as the axes are correct, QA passes, and this PR is merged.

**Comment by yanone** [comment]
Updated

## Tilt Neon: Version 1.000 added

---
 68f60c2: [gftools-packager] Tilt Neon: Version 1.000 added

* Tilt Neon Version 1.000 taken from the upstream repo https://github.com/googlefonts/Tilt-Fonts at commit https://github.com/googlefonts/Tilt-Fonts/commit/c67203809831ead39ecf05da5997688316cd6fb8.

**Comment by RosaWagner** [comment]
@yanone Default on XROT doesn't seem to be elided

**Comment by yanone** [comment]
Updated

## Tilt Neon: Version 1.000 added

---
 f815ec3: [gftools-packager] Tilt Neon: Version 1.000 added

* Tilt Neon Version 1.000 taken from the upstream repo https://github.com/googlefonts/Tilt-Fonts at commit https://github.com/googlefonts/Tilt-Fonts/commit/0773dc9f490aabba0c19c15d290b575b62245970.

**Pull request merged**
