### PR TITLE
catalog/designers/robleuschke

### PR DESCRIPTION
**Pull request by vv-monsalve**
Rob Leuschke bio info added

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Empty link in info.pb added

**Comment by m4rc1e** [comment]
@RosaWagner Do we have confirmation that empty links are ok?

**Comment by RosaWagner** [comment]
No… I would prefer to send the test-PR (natanael gama) to sandbox before merging more profiles with empty links

**Comment by vv-monsalve** [comment]
Should a link be included in the meanwhile (to be able to merge the PR)? Or should we rather wait for confirmation?

**Comment by RosaWagner** [comment]
If you are in a hurry for this one, yes you can add the link. Otherwise we will ask again this week and probably have confirmation soon.

**Comment by vv-monsalve** [comment]
No, no hurry on my side. Just confirming if any action was required.

**Comment by RosaWagner** [comment]
All fonts onboarded are under the name of "Robert Leuschke" (here it is "Rob Leuschke")

**Comment by vv-monsalve** [comment]
> All fonts onboarded are under the name of "Robert Leuschke" (here it is "Rob Leuschke")

Updated.

**Pull request merged**
