### PR TITLE
Playwrite GB S: Version 1.002 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the upstream repo https://github.com/TypeTogether/Playwrite/ at commit https://github.com/TypeTogether/Playwrite//commit/99cb288e23e1066551824e66f759f9cbb460014c.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [x] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
Hi @vv-monsalve! cc @josescaglione
I'm starting with this one. I'll wait for your answer before to start the other ones, because the errors I found are maybe in all families.
Otherwise, I tested the fonts in different software, no problems, it works well :) 


### Fontbakery

Maybe some WARN can be avoid, but I'm ok to onboard the font like this. I guess you already reviewed the report and chose to let it like this :)

### Outlines / Spacing / Kerning

- The spacing between `g` and `u` seems very large. I prefer to check if it's intentional or not.
Screenshot 2024-05-10 at 10 08 10

- Check ogoneks
Screenshot 2024-05-10 at 10 17 51
Screenshot 2024-05-10 at 10 18 02
Screenshot 2024-05-10 at 10 18 15
Screenshot 2024-05-10 at 10 18 27
Screenshot 2024-05-10 at 10 18 32
Screenshot 2024-05-10 at 10 18 39
Screenshot 2024-05-10 at 10 10 59
Screenshot 2024-05-10 at 10 11 03
Screenshot 2024-05-10 at 10 17 46


- Cedilla placement
Screenshot 2024-05-10 at 10 12 25

- Just want to check the `lbar` placement (not too high?)
Screenshot 2024-05-10 at 10 11 33

- Is it normal?
Screenshot 2024-05-10 at 10 21 38

- TJ kerning
Screenshot 2024-05-10 at 10 24 30

**Comment by josescaglione** [comment]
There is obviously something wrong with the anchors. I will check against old versions and fix. Passed on the kerning notes to Vik.

I am missing the text string Panruji string towards the end of the report

**Comment by emmamarichal** [comment]
Screenshot 2024-05-10 at 15 06 38

____________


għall-maskil, tal-paċi ż-żebliħ ġabu tal-Ġnus Ħadd bụ pụghị Ọgbakọ Ụmụ enupa,…) pruckamakir+t ZWAŻYWSZY, **Panru̸ji** ŨũMm KkÕõ Śś pơmĭn ayŏng ĘęGg TtÔô Việc thừa nhận phẩm vốn quyền Sự phạm thường đến những động Cần phải Tất nước Hợp bức đẳng bằng để hoặc hưởng đủ. diễn | ,ÁL,ÁLŦ. murutǘkpí

**Comment by josescaglione** [comment]
> Panru̸ji

@emmamarichal , we do not support that character in Playwrite

**Comment by emmamarichal** [comment]
alright, no problem! forget my remark :)

**Comment by josescaglione** [comment]
@emmamarichal Just fixed in commit `168b643`

See [here](https://github.com/TypeTogether/Playwrite/commit/168b643a6b69a6452a73642616d33ad3e43f4eba)

**Comment by vv-monsalve** [comment]
> See [here](https://github.com/TypeTogether/Playwrite/commit/168b643a6b69a6452a73642616d33ad3e43f4eba)

@emmamarichal I'll take the new fonts run a new QA round and update the PRs ASAP

**Comment by vv-monsalve** [comment]
@josescaglione after pulling the latest fonts at commit `5735d7c`, the reported kerning pair is still present.

Screen Shot 2024-05-14 at 11 25 37

**Comment by vv-monsalve** [comment]
Version `1.002` has the kerning fix
GB-S-kerning-change

**Comment by vv-monsalve** [comment]
Updated

**Comment by vv-monsalve** [comment]
@emmamarichal this PR has been updated and it's ready to revive now :)

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
