### PR TITLE
Noto Sans Old Turkic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
06411f8: [gftools-packager] Noto Sans Old Turkic: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Old Turkic Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/old-turkic.git at commit https://github.com/notofonts/old-turkic/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens 
🔥 FAIL: Check samples can be rendered. ([com.google.fonts/check/metadata/can_render_samples](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/can_render_samples))
🔥 FAIL Font can't render "otk_Orkh" sample text:
"𐱅𐰇𐰼𐰜⁚𐰆𐰍𐰔⁚𐰋𐰏𐰠𐰼𐰃⁚𐰉𐰆𐰑𐰣⁚𐱁𐰃𐰓𐰤⁚𐰇𐰔𐰀⁚𐱅𐰭𐰼𐰃⁚𐰉𐰽𐰢𐰽𐰺⁚𐰽𐰺𐰀⁚𐰘𐰃𐰼⁚𐱅𐰠𐰃𐰤𐰢𐰾𐰼⁚𐱅𐰇𐰼𐰜⁚𐰉𐰆𐰑𐰣⁚𐰃𐰠𐰤𐰭⁚𐱅𐰇𐰼𐰇𐰭𐰇𐰤"
[code: sample-text]


Capture d’écran 2023-06-15 à 11 47 19

**Comment by simoncozens** [comment]
This font is missing the TWO DOT PUNCTUATION glyph which is used as a punctuation mark in Old Turkic test. I'll add it to the subset and re-release.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Old Turkic: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

---
 48f0e71: [gftools-packager] Noto Sans Old Turkic: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Old Turkic Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/old-turkic.git at commit https://github.com/notofonts/old-turkic/commit/.

**Comment by RosaWagner** [comment]
@simoncozens I think the codepoint missing from the nam file cause the font is still showing tofu
Screenshot 2023-06-29 at 11 28 05

**Comment by RosaWagner** [comment]
@simoncozens if you are fixing nam files at the moment, this one can be part of the batch

**Pull request merged**
