### PR TITLE
Wavefont: Version 3.005;gftools[0.9.33] added

### PR DESCRIPTION
**Pull request by RosaWagner**
b83de91: [gftools-packager] Wavefont: Version 3.005;gftools[0.9.33] added

* Wavefont Version 3.005;gftools[0.9.33] taken from the upstream repo https://github.com/dy/wavefont at commit https://github.com/dy/wavefont/commit/1f7ae553ddafa999986990ac7775da0ebbd44135.

**IMPORTANT:**

**This upgrade introduce a regression in the horizontal metrics. This is to improve the display of the font on the website, and we do it now since the font got releases only few weeks ago and use is still low.**

### CODE REVIEW

**Comment by RosaWagner** [comment]
🔥 FAIL: METADATA.pb font.name field contains font name in right format? ([com.google.fonts/check/metadata/valid_name_values](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_name_values))
🔥 FAIL METADATA.pb font.name field ("Wavefont") does not match correct font name format ("Wavefont Thin"). [code: mismatch]

**Bug from fontbakery**

🔥 FAIL: Check a font's STAT table contains compulsory Axis Values. ([com.google.fonts/check/STAT](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/STAT))

We accept ExtraBlack 1000 in the STAT table

🔥 FAIL: Validate defaults on fvar table match registered fallback names in GFAxisRegistry. ([com.google.fonts/check/gf_axisregistry/fvar_axis_defaults](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/gf_axisregistry/fvar_axis_defaults))
🔥 FAIL The defaul value ROND:100.0 is not registered as an axis fallback name on the Google Axis Registry.
You should consider suggesting the addition of this value to the registry or adopted one of the existing fallback names for this axis:
[name: "Default"
value: 0.0
] [code: not-registered]

**The default is override in METADATA.pb so it's all good.**
🔥 FAIL The defaul value YELA:-100.0 is not registered as an axis fallback name on the Google Axis Registry.
You should consider suggesting the addition of this value to the registry or adopted one of the existing fallback names for this axis:
[name: "Default"
value: 0.0
] [code: not-registered]

🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1270, but got 1200 instead [code: ascent]
🔥 FAIL OS/2.usWinDescent value 200 is too large. It should be less than double the yMin. Current absolute yMin value is 15 [code: descent]

**This is a symbol font that need to have rationalised vertical metrics, nothing "readable" is clipped.**

🔥 FAIL: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))
🔥 FAIL The '.notdef' glyph should contain a drawing, but it is blank. [code: notdef-is-blank]

**For that font, exceptionally, we accept, cause all missing glyphs need to fallback on a blank glyphs**

**Comment by RosaWagner** [comment]
@vv-monsalve cf discussion here: https://github.com/dy/wavefont/pull/61, the author decided to not include Hairline to not break the linearity of the weight axis. So this is should be good to go again.

**Comment by RosaWagner** [comment]
Updated

## Wavefont: Version 3.005;gftools[0.9.33] added

---
 f97be59: [gftools-packager] Wavefont: Version 3.005;gftools[0.9.33] added

* Wavefont Version 3.005;gftools[0.9.33] taken from the upstream repo https://github.com/dy/wavefont at commit https://github.com/dy/wavefont/commit/91649d7bede2a302b8b820dbccc2401672400cdd.

**Comment by vv-monsalve** [comment]
After running into the full maths for this project with @RosaWagner it makes sense for this font intended for precision graphics to have a mapping to a min of 4 (instead of 1 as used for previous cases).

**Review by vv-monsalve — APPROVED** [review]

**Pull request merged**
