### PR TITLE
Ysabeau: Version 2.002 added

### PR DESCRIPTION
**Pull request by yanone**
a9bf8df: [gftools-packager] Ysabeau: Version 2.002 added

* Ysabeau Version 2.002 taken from the upstream repo https://github.com/CatharsisFonts/Ysabeau at commit https://github.com/CatharsisFonts/Ysabeau/commit/130cdf5a22fd2cf8632c6ba96a831b67be01f5c7.

### CODE REVIEW

**Comment by yanone** [comment]
@RosaWagner These are all the results of the interpolation bugs that Behdad reported, so there should be no major other changes

**Comment by yanone** [comment]
Updated

## Ysabeau: Version 2.002 added

---
 8948186: [gftools-packager] Ysabeau: Version 2.002 added

* Ysabeau Version 2.002 taken from the upstream repo https://github.com/CatharsisFonts/Ysabeau at commit https://github.com/CatharsisFonts/Ysabeau/commit/2267184e6cfe7c49c910dd7b5ee5c9fec3b5dce4.

**Comment by yanone** [comment]
One second, this was a much longer description file. Will be back...

**Comment by yanone** [comment]
Updated

## Ysabeau: Version 2.002 added

---
 371a9e2: [gftools-packager] Ysabeau: Version 2.002 added

* Ysabeau Version 2.002 taken from the upstream repo https://github.com/CatharsisFonts/Ysabeau at commit https://github.com/CatharsisFonts/Ysabeau/commit/8e2ca3573545176256d370f891604bc453029568.

**Review by eliheuer — APPROVED** [review]
Looks good to me. I reviewed all the QA files and it looks like all the FontBakery fails can be ignored.

@RosaWagner You can merge this unless I missed something.

**Review by RosaWagner — APPROVED** [review]

**Comment by RosaWagner** [comment]
Thanks @eliheuer, if the 3 other Ysabeau family PRs are like this one, you can go ahead and merge them (I am not here this afternoon)

**Pull request merged**
