### PR TITLE
amiri: v0.112 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream release https://github.com/alif-type/amiri/releases

### CODE REVIEW

**Comment by khaledhosny** [comment]
Thank you!

**Comment by khaledhosny** [comment]
Any idea why we are not getting a FontBakery report here?

**Comment by khaledhosny** [comment]
Anything I can help with to get this moving forward?

**Comment by m4rc1e** [comment]
Family seems to choke our ci. This isn't the your fault, it's our regression tooling. GFRegression uses nototools.hb_input to allow us to access every glyph. Unfortunately it can get stuck in an infinite loop or require too much memory for GFR's server on some largish families.

I've been working on fontTools.otlLib.unbuild which will have a more efficient version of hb_input.

I'm currently working on Roboto and a few other project so it has taken a back seat.

In the meantime, I can see if genning the diffs locally will expedite this family. I'll attempt it this week.

**Comment by khaledhosny** [comment]
I fixed a few issues in the master branch, so you might want to pick the files from there (I can open a new PR if you like).

**Comment by khaledhosny** [comment]
I think this should be closed now.

**Pull request closed without merging**
