### PR TITLE
varta: v1.004 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
Varta is a Sans Serif family created by Sorkin Type. Although it was initially intended for Devanagari, this release would only include the Latin, while the designer solves some Issues with Devanagari's Matras.

A variable font was developed for the project, and many fixes were performed to meet GF specs to contribute.

This Pull Request is almost ready to be merged, font files don't report Fails on local FB checks. Nevertheless, there is one thing that is not working correctly and would need a detailed revision:
Despite the MinValue and DefaultValue are 300, and the usWeightClass on the OS/2 table is also 300 when the Metadata.pb is created (using the gftools add-font command) the "weight" value of the font is 400.

This would be related to [#2873](https://github.com/googlefonts/fontbakery/issues/2873) and [#2874](https://github.com/googlefonts/fontbakery/issues/2874).

----
Taken from the upstream repo https://github.com/SorkinType/Varta at commit https://github.com/SorkinType/Varta/commit/38d842bff4d906c7f8859d898b1ac946a549c092

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Link to ['fvar' table](https://github.com/vv-monsalve/Varta/blob/master/fonts/variable/Varta%5Bwght%5D%2312.ttx)

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.27

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds
/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** Could not find ftxvalidator.

</details>
<br>
</details>
<details>
<summary><b>[3] Varta[wght].ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---

Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is
stored in the achVendID field of the OS/2 table.

Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:

https://docs.microsoft.com/en-us/typography/vendors/

This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.

Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.


</pre>

* ⚠ **WARN** OS/2 VendorID value 'STC' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 4 | 35 | 9 | 127 | 0 |
| 0% | 0% | 2% | 20% | 5% | 73% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [varta.zip](http://35.238.63.0/media/5ad6f57b-b241-46ef-bee8-ea29941b6818/varta.zip)

**Comment by m4rc1e** [comment]
Thanks. LGTM

**Comment by m4rc1e** [comment]
> Nevertheless, there is one thing that is not working correctly and would need a detailed revision:
Despite the MinValue and DefaultValue are 300, and the usWeightClass on the OS/2 table is also 300 when the Metadata.pb is created (using the gftools add-font command) the "weight" value of the font is 400.

This was fixed in https://github.com/googlefonts/fontbakery/pull/2902

**Pull request merged**
