### PR TITLE
Noto Rashi Hebrew: Version 1.005 added

### PR DESCRIPTION
**Pull request by simoncozens**
8d68ca0: [gftools-packager] Noto Rashi Hebrew: Version 1.005 added

* Noto Rashi Hebrew Version 1.005 taken from the upstream repo https://github.com/notofonts/hebrew.git at commit https://github.com/notofonts/hebrew/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Hi @simoncozens,

Making my firsts apprentice's review for PR now :)

- There is one small missing Kerning case reported
kerns_missing

- And some marks modified + missing. Please ensure they are as expected in the current version
marks_modified
marks_modified

**Comment by simoncozens** [comment]
Thank you - yes, looks like we have some wrong anchors.

**Comment by simoncozens** [comment]
Actually these also look better. Hebrew has lots of dot above marks; I saw the SHIN DOT positioning אׁ and thought it was a HOLAM ֹא...

**Comment by vv-monsalve** [comment]
> Actually these also look better. Hebrew has lots of dot above marks; I saw the SHIN DOT positioning אׁ and thought it was a HOLAM ֹא... (This is why diffenator really needs to give us the text as well; ah well, it will be better in the next version.)

Ok, so merging this one here.

**Comment by RosaWagner** [comment]
Main description says: "Noto Rashi Hebrew is modulated (“serif”) design for the Middle Eastern Hebrew script with a semi-cursive skeleton based on 15th-century Sephardic writing. It can be used for emphasis, complementing Noto Serif Hebrew." but fonts contains Noto Sans. It that okay?

**Comment by simoncozens** [comment]
Good point. No, we should pair it with Noto Serif.

**Pull request merged**
