### PR TITLE
[Noto Znamenny] Add znamenny subset to METADATA

### PR DESCRIPTION
**Pull request by simoncozens**
Will magically start not showing tofu once https://github.com/googlefonts/nam-files/pull/4 is merged.

### CODE REVIEW

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
> googlefonts/nam-files#4

The PR for the nam file has been merged. So merging this here now.

**Comment by vv-monsalve** [comment]
The change introduced by this PR will be followed on the pipeline through #7087

**Comment by vv-monsalve** [comment]
We are still seeing tofu on dev. DO the [googlefonts/nam-files#4](https://github.com/googlefonts/nam-files/pull/4) need to have git subtree pull?

**Comment by vv-monsalve** [comment]
We are still seeing tofu on dev. Do the [googlefonts/nam-files#4](https://github.com/googlefonts/nam-files/pull/4) need to have git subtree pull?

**Comment by simoncozens** [comment]
No, the subset definitions don't get a subtree pull; they are synced manually by eng from that repository. Probably they need to repush the font?

**Comment by vv-monsalve** [comment]
@nyshadhr9 What could be the case here?

**Comment by nyshadhr9** [comment]
I don't see tofu, can you check again. 
You might have seen tofu when the changes were still propagating on our side.

**Comment by vv-monsalve** [comment]
Thanks. I updated it multiple times to see if it was a cache issue and it is better now. 
However, @simoncozens it still shows one tofu >.<

Screen Shot 2024-01-25 at 22 01 02

**Comment by simoncozens** [comment]
Oh, it's a bug in the sample text, I can fix that.

**Comment by simoncozens** [comment]
-> https://github.com/google/fonts/pull/7229

**Pull request merged**
