### PR TITLE
Updated Montserrat and MontserratAlternates

### PR DESCRIPTION
**Pull request by graphicore**

### CODE REVIEW

**Comment by sebastiaanluca** [comment]
What's the usual ETA on merging fonts? I see a lot of people are desperately waiting for this :)

**Comment by m4rc1e** [comment]
When we're happy nothing is going to explode ;-)

**Comment by m4rc1e** [comment]
Ok more specifically, we're coming across bugs/potential bugs which are collection wide or affect a certain group of fonts. We'd rather batch release them, instead of doing it on a per family basis.

**Comment by sebastiaanluca** [comment]
Haha, always a good thing to prevent such a scenario :p I'm sure you guys have a ton of work to do, so I'll try to store and serve the font from my own site for now in anticipation of an update. 

Thanks for the quick reply and good luck!

**Comment by graphicore** [comment]
@m4rc1e: Is this still the latest version or will you make a new PR?

**Comment by m4rc1e** [comment]
I'll make a new pr.

**Pull request closed without merging**
