### PR TITLE
cabin: v3.001 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the upstream repo https://github.com/impallari/Cabin/commit/70efa8c3179359cc50b01ca184fec8a694156140

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.29

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds
/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** Could not find ftxvalidator.

</details>
<br>
</details>
<details>
<summary><b>[2] Cabin-Italic[wdth,wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.


</pre>

* 🔥 **FAIL** Please create a subdirectory called "static/" and include in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---

Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is
stored in the achVendID field of the OS/2 table.

Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:

https://docs.microsoft.com/en-us/typography/vendors/

This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.

Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.


</pre>

* ⚠ **WARN** OS/2 VendorID value 'IMPA' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<br>
</details>
<details>
<summary><b>[2] Cabin[wdth,wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.


</pre>

* 🔥 **FAIL** Please create a subdirectory called "static/" and include in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---

Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is
stored in the achVendID field of the OS/2 table.

Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:

https://docs.microsoft.com/en-us/typography/vendors/

This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.

Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.


</pre>

* ⚠ **WARN** OS/2 VendorID value 'IMPA' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 3 | 73 | 19 | 243 | 0 |
| 0% | 1% | 1% | 21% | 6% | 71% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [cabin_qa.zip](http://35.238.63.0/media/4eab106b-e033-4a44-8b6f-f9c2fc0e92a4/cabin_qa.zip)

**Comment by m4rc1e** [comment]
You need to move the static ttfs into a new dir called /static e.g https://github.com/google/fonts/tree/master/ofl/oswald

**Comment by vv-monsalve** [comment]
The static ttfs are already included in a dir called static in the folder for GF https://github.com/vv-monsalve/fonts/tree/Cabin/ofl/cabin/static

**Comment by m4rc1e** [comment]
My bad. Thanks.

**Comment by m4rc1e** [comment]
Looks good! thanks you.

**Comment by thlinard** [comment]
Condensed Named Instances are missing in the fvar table.

And it doesn't just break Photoshop this time around: fvar is really, at the moment, the most important table when it comes to the implementation of VFs by applications.

**Comment by m4rc1e** [comment]
@thlinard re instance names, https://github.com/googlefonts/gf-docs/tree/master/Spec#fvar-instances

**Comment by thlinard** [comment]
@m4rc1e OK. But the reasons given are wrong.

"Backwards compatibility with static fonts. Documents won't break if users swap static fonts for variable fonts": wrong. When the user switches from "Condensed Bold" static to the VF version, their document will break.

"DTP applications do not properly support variable fonts yet": this is actually the Google Fonts API which doesn't support VFs beyond the wght axis. Support in DTP applications is better than this. Properly configured, named instances for the wght and wdth axis of a font like Cabin would work fine in Photoshop, InDesign, and Illustrator, for example.

There, we have a font whose Condensed instances are inaccessible in MS Office for Windows, various Windows applications, Apple applications, etc. Actually, its wdth axis can be accessed only in Illustrator—and maybe also CorelDraw but I haven't tested. Whereas there was a way to do it other than by creating deliberately flawed and crippled fonts.

**Comment by davelab6** [comment]
@thlinard I am very grateful 

> @m4rc1e OK. But the reasons given are wrong.
> 
> "Backwards compatibility with static fonts. Documents won't break if users swap static fonts for variable fonts": wrong. When the user switches from "Condensed Bold" static to the VF version, their document will break.

If the `fvar` table had named instances for "Condensed Bold", well, the family "Cabin Condensed" with style "Bold" won't immediately map to family "Cabin" with style "Condensed Bold." 

So, their documents will 'break' if they uninstall static font family and install only variable font family, in all cases. 

Most applications have some way to 'heal' such breakage with a regex on font family and style attributes, to map old ones to new ones.

If applications supposedly support variable fonts, but do not support the STAT table, then I hope the app's users will report that serious deficiency to the developers so it can be addressed.
 
> "DTP applications do not properly support variable fonts yet": this is actually the Google Fonts API which doesn't support VFs beyond the wght axis. 

The API supports the axes in the `/axisregistry` of this repo. The catalog only makes discovery of the Weight axis interactive, right now, but this will improve over time.

> Support in DTP applications is better than this. Properly configured, named instances for the wght and wdth axis of a font like Cabin would work fine in Photoshop, InDesign, and Illustrator, for example.

However, a single list of styles in a single dropdown menu becomes very long - too long - very quickly, as the number of axes increase. The UI made possible by the STAT table, a set of dropdown menus, mitigates this.

> There, we have a font whose Condensed instances are inaccessible in MS Office for Windows, various Windows applications, Apple applications, etc. Actually, its wdth axis can be accessed only in Illustrator—and maybe also CorelDraw but I haven't tested. Whereas there was a way to do it other than by creating deliberately flawed and crippled fonts.

We need to take future-facing and library-wide perspective when making this decision. 

Since we expect to onboard families like Roboto Flex, with a wdth range from 50 to 150, and a weight range from 1 to 1000, in roman and italic, for a range of optical sizes, then even limiting fvar named instances to "only OpenType registered axes" can produce a single style dropdown that is too long. 

Therefore the current approach, to only list the 1 to 18 styles, 9 weights roman and italic, which were available in the family name's legacy set of static fonts, seems to me like the best way to offer some backwards compatibility for non-STAT-aware legacy software, drive awareness of the need for STAT based named style selection, or better, a complete UI for selecting styles along axes.

**Comment by thlinard** [comment]
> @thlinard I am very grateful for your sustained engagement on this project! It is very helpful :)

Hi @davelab6 

Pleasure is mine. 😀 It's natural, we share the same interest in typography.

> When you say,
> 
> > fvar is really, at the moment, the most important table when it comes to the implementation of VFs by applications.
> 
> I hear you, but I kindly disagree. Since it is mainly me who decides this, rather than Marc or anyone else, I thought I'd directly address your concerns :)
> 
> > @m4rc1e OK. But the reasons given are wrong.
> > "Backwards compatibility with static fonts. Documents won't break if users swap static fonts for variable fonts": wrong. When the user switches from "Condensed Bold" static to the VF version, their document will break.
> 
> If the `fvar` table had named instances for "Condensed Bold", well, the family "Cabin Condensed" with style "Bold" won't immediately map to family "Cabin" with style "Condensed Bold."
> 
> So, their documents will 'break' if they uninstall static font family and install only variable font family, in all cases.
> 
> Most applications have some way to 'heal' such breakage with a regex on font family and style attributes, to map old ones to new ones.

Agreed. But at least the user will find the style "Condensed Bold" if the fvar table contains such an instance. If not (like in the present case with Cabin), the user will never find it.

> If applications supposedly support variable fonts, but do not support the STAT table, then I hope the app's users will report that serious deficiency to the developers so it can be addressed.

Well, everybody is currently not at its best with VF support. For example, Google has long provided VFs with very bad STAT tables. 😉 The situation is fixed for new simple axis fonts *when* they use the gftools-fix-vf-meta.py script (than I helped Marc to test).

You're right to point out than customers should complain about poor VF implementation. But I believe Google has a responsibility here: make good (from a technical point of view) VF fonts, to help developers test their apps.

And concerning VF support, two things must be distinguished:

1. Named instances support.
2. Arbitrary values support.

Concerning the former, macOS provides support for the fvar table in the Skia font for years, if not decades, so the fvar support in Apple applications and other macOS relying on macOS API offers named instances support. Fvar support in Windows 10, tested with the VF font included (Bahnschrift), offers named instances support also, available in MS Office (but I'm not a regular Windows user). Adobe apps have named instances support also.

Concerning the latter, I only know Adobe Illustrator to have a not-too-picky support (theoretically, Photoshop and InDesign 2020 too, but Photoshop support can go wrong if the typeface has a separate file for Italic and if the tables doesn't contain what it likes – which gftools-fix-vf-meta.py fixes –, and concerning InDesign, it needs in addition STAT.AxisValue in format 2 — but nobody outside Adobe seems to use format 2).

It's not bright, but it's today's reality: no application support the STAT table alone (Apple doesn't care at all, Microsoft doesn't seems to use it – but the simple presence of a STAT table breaks the font in MS Office for Mac –, and Adobe use the STAT table in InDesign, for arbitrary values support, if it contains STAT.AxisValue in format 2). Tests are simple: create VF fonts with bad STAT table, no application breaks (or not more than before). Create VF fonts with bad fvar table: all break. (And I'm not saying that to say that the STAT table is not important: the future is in the STAT table, and to prepare for the advent of this future, we must create good STAT tables. But that's just not the present reality.)

Thus, when you release a font such of Cabin without Condensed instances in fvar table (and Cabin Condensed statics existed), you're making a "Adobe Illustrator only" VF font (outside Google, of course), because the Condensed is only available as arbitrary value (which very few applications provide, and probably only Illustrator without too much expectations) and I think call such a font a flawed and crippled font (in regard to its previous static state) is not an overstatement.

In doing so, it doesn't help the VF ecosystem as a whole. Because it's not progressive enhancing, it's just breaking the current support, and that tells the potential frustrated users: "things will be fixed in the future, just wait for some years!". Their conclusion will be to reject VF fonts and stay with static fonts.

> > "DTP applications do not properly support variable fonts yet": this is actually the Google Fonts API which doesn't support VFs beyond the wght axis.
> 
> The API supports the axes in the `/axisregistry` of this repo. The catalog only makes discovery of the Weight axis interactive, right now, but this will improve over time.

Indeed! So it's not even a necessity.

> > Support in DTP applications is better than this. Properly configured, named instances for the wght and wdth axis of a font like Cabin would work fine in Photoshop, InDesign, and Illustrator, for example.
> 
> However, a single list of styles in a single dropdown menu becomes very long - too long - very quickly, as the number of axes increase. The UI made possible by the STAT table, a set of dropdown menus, mitigates this.

Well, a good incentive to make good STAT tables. 😄 But, in waiting for new STAT-aware UI (which doesn't exist – outside Samsa, of course), don't abandon the current state of VF support, i.e. fvar table. In the future VF paradise, things could be made otherwise, but in today's world, don't drop fvar table too quickly.

> > There, we have a font whose Condensed instances are inaccessible in MS Office for Windows, various Windows applications, Apple applications, etc. Actually, its wdth axis can be accessed only in Illustrator—and maybe also CorelDraw but I haven't tested. Whereas there was a way to do it other than by creating deliberately flawed and crippled fonts.
> 
> I want to take future-facing and library-wide perspective when making this decision.
> 
> Since we expect to onboard families like Roboto Flex, with a wdth range from 50 to 150, and a weight range from 1 to 1000, in roman and italic, for a range of optical sizes, then even limiting fvar named instances to "only OpenType registered axes" can produce a single style dropdown that is too long.
> 
> Therefore the current approach, to only list the 1 to 18 styles, 9 weights roman and italic, which were available in the family name's legacy set of static fonts, seems to me like the best way to offer some backwards compatibility for non-STAT-aware legacy software, drive awareness of the need for STAT based named style selection, or better, a complete UI for selecting styles along axes.

As Roboto Flex is intended (explicitly or implicitly?) to replace Roboto, Roboto Flex should provide the same named instances as Roboto (currently, with Normal and Condensed: 18 styles – but not uniformly distributed: if you want 9 weights, it could represent 36 named instances – not so big a number, as previous Adobe Multiple Master fonts, such as Minion or Myriad, have more). For new features, like the opiz axis which doesn't exist in Roboto, well, it's progressive enhancement if the users with only named instances support can't see them.

And I think that this would be a better rule than "nothing over 9 weight": it would rather be the minimum rule "at least all the styles of the old static version must be found in named instances in the VF version".

**Pull request merged**
