### PR TITLE
knowledge/glossary/terms/grade_axis Add example

### PR DESCRIPTION
**Pull request by davelab6**
Hilary suggested this based on a chat conversation about the axis definition

### CODE REVIEW

**Comment by davelab6** [comment]
This can be rewritten for clarity 

Also add a link to wcag and material design resources

Eg https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast

**Comment by RosaWagner** [comment]
@elliotjaystocks shall this PR be merged?

**Comment by elliotjaystocks** [comment]
> @elliotjaystocks shall this PR be merged?

@RosaWagner Looks like it’s failing one of the checks...? I looked at the error and don’t understand, I’m afraid.

**Comment by RosaWagner** [comment]
This check is failing for the previous sandbox list that had a wrong file path (not knowledge related) ;)

**Comment by elliotjaystocks** [comment]
@RosaWagner Ah, cool. Yes, this can be merged, then. :) Thanks!

**Pull request merged**
