### PR TITLE
Oswald: Version 4.103;gftools[0.9.32] added

### PR DESCRIPTION
**Pull request by emmamarichal**
b537dc7: [gftools-packager] Oswald: Version 4.103;gftools[0.9.32] added

* Oswald Version 4.103;gftools[0.9.32] taken from the upstream repo https://github.com/googlefonts/OswaldFont at commit https://github.com/googlefonts/OswaldFont/commit/f1a24296ba9366f2fabeb555364a6d7dfe84bad9.

 5a20001: description updated

### CODE REVIEW

**Comment by RosaWagner** [comment]
This pair has become too close imo. You can see it also with `l/e` and `l/a` so I would inspect the kerning value with everything pairing with the right side of `l`.

Screenshot 2023-07-19 at 11 58 44

**Comment by emmamarichal** [comment]
Updated

## Oswald: Version 4.103;gftools[0.9.33.dev8+g029e19f] added

---
 65a49ad: [gftools-packager] Oswald: Version 4.103;gftools[0.9.33.dev8+g029e19f] added

* Oswald Version 4.103;gftools[0.9.33.dev8+g029e19f] taken from the upstream repo https://github.com/googlefonts/OswaldFont at commit https://github.com/googlefonts/OswaldFont/commit/7e532e153ac9010b1c632894b611dc1020a30f90.

 b95436c: description

**Comment by emmamarichal** [comment]
@RosaWagner updated!

**Comment by RosaWagner** [comment]
@emmamarichal there is still a kerning pair between `l` and `a`

**Comment by emmamarichal** [comment]
Updated

## Oswald: Version 4.103;gftools[0.9.33.dev8+g029e19f] added

---
 b6f0fe1: [gftools-packager] Oswald: Version 4.103;gftools[0.9.33.dev8+g029e19f] added

* Oswald Version 4.103;gftools[0.9.33.dev8+g029e19f] taken from the upstream repo https://github.com/googlefonts/OswaldFont at commit https://github.com/googlefonts/OswaldFont/commit/6e65651c229e897dc55fb8d17097ee7f75b2769b.

 d9b9162: description

**Pull request merged**
