### PR TITLE
notoseriftodhri: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/notofonts/todhri at commit https://github.com/notofonts/todhri/commit/850ebfdfca2d445c3e53577ec0b4c7e5d80a7d0f.
## PR Checklist:

- [ ] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [x] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [x] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
todhri is the correct subset. It was added in https://github.com/googlefonts/nam-files/pull/21 but I haven't done a gfsubsets release yet. I'll do that now.

**Comment by vv-monsalve** [comment]
> The following links are broken in the article file:
https://scriptsource.org/scr/Todr (status code: 403)

The link is working ok

> but I haven't done a gfsubsets release yet. I'll do that now.

@simoncozens should we better wait for this?

**Review by vv-monsalve — APPROVED** [review]

**Comment by simoncozens** [comment]
The eng team have created the subset their end, and I've now done the release.

**Comment by vv-monsalve** [comment]
@nathan-williams 

This font is not shown consistently in the Sandbox server.

- It displays it ok in the font preview and `Specimen` tab.
Screenshot 2024-11-15 at 14 48 18

<br>

- But then, when entering the font's Type tester, nothing is displayed.
    Screenshot 2024-11-15 at 14 45 18

**Comment by m4rc1e** [comment]
Can confirm Viv's findings.

**Comment by emmamarichal** [comment]
Working now! (sandbox)
Screenshot 2025-01-16 at 15 08 10

**Pull request merged**
