### PR TITLE
Annapurna SIL: Version 2.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
f609169: [gftools-packager] Annapurna: Version 2.000 added

* Annapurna Version 2.000 taken from the upstream repo https://github.com/silnrsi/font-annapurna at commit https://github.com/silnrsi/font-annapurna/commit/.

 4c56fc8: Description added

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: METADATA.pb font.name value should be same as the family name declared on the name table. ([com.google.fonts/check/metadata/nameid/font_name](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/font_name))

Please confirm the name ID1, Non of the other SIL fonts includes 'SIL' on it.

**Comment by kenmcd** [comment]
> > 🔥 FAIL: METADATA.pb font.name value should be same as the family name declared on the name table. ([com.google.fonts/check/metadata/nameid/font_name](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/font_name))
> 
> Please confirm the name ID1, Non of the other SIL fonts includes 'SIL' on it.

Charis SIL
https://fonts.google.com/specimen/Charis+SIL

Abyssinica SIL
https://fonts.google.com/specimen/Abyssinica+SIL

Dai Banna SIL
https://fonts.google.com/specimen/Dai+Banna+SIL

**Comment by vv-monsalve** [comment]
@kenmcd Indeed some projects include "SIL" in the name ID1 (also Nuosu SIL) but they don't present the Fail reported for Annapurna:
> Unmatched family name in font: TTF has "Annapurna SIL" while METADATA.pb has "Annapurna" [code: mismatch]

**Comment by emmamarichal** [comment]
@vv-monsalve Yes sorry, my fault! I've updated it

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: Check OFL body text is correct. 

@emmamarichal have you checked this one? 

> 🔥 FAIL: Directory name in GFonts repo structure must match NameID 1 of the regular. ([com.google.fonts/check/repo/dirname_matches_nameid_1](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/dirname_matches_nameid_1))
> 🔥 FAIL: Check font family directory name. ([com.google.fonts/check/metadata/family_directory_name](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/family_directory_name))

Perhaps it is better to repeat the PR so the OFL dir gets updated?

**Comment by emmamarichal** [comment]
Ok, I close this one!

**Pull request closed without merging**
