### PR TITLE
Comic Neue credit Hrant

### PR DESCRIPTION
**Pull request by davelab6**

### CODE REVIEW

**Comment by m4rc1e** [comment]
Since you've only update the metadata.pb, let's ignore the fails.

Would be interesting one day to roll out some collection wide fixes.

**Comment by hpapazian** [comment]
Sorry, is
https://fonts.google.com/specimen/Comic+Neue#about
supposed to reflected the crediting now? I can't see it...

**Comment by RosaWagner** [comment]
Before being published the content of this PR has to travel to different servers for other validation. It will be up in few weeks.

**Comment by hpapazian** [comment]
Ah OK, thank you for explaining. (And sorry for being such a noob.)

**Pull request merged**
