### PR TITLE
Edu AU VIC WA NT Pre: Version 1.001 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/SorkinType/VICWANTSchoolHandAustralia at commit https://github.com/SorkinType/VICWANTSchoolHandAustralia/commit/abab94d19985f24132e45db4c4822b042eb63302.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
~- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects~
~- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target~
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Similar [comment](https://github.com/google/fonts/pull/7447#issuecomment-2294247158) about the name schema: the family name should include `AU` particle.

**Comment by simoncozens** [comment]
PR name is wrong, but font name is correct.

**Comment by emmamarichal** [comment]
@EbenSorkin, have you seen [this](https://github.com/google/fonts/pull/8022#issuecomment-2294410205)? :)

> same quotes situation as in the Cursive variant

**Comment by emmamarichal** [comment]
Is the CI still broken @simoncozens? The checks failed again 🤔

**Comment by simoncozens** [comment]
No, but rerunning the job runs it with the original Action, not the updated one. We need to add a new commit to start a new Action.

**Comment by emmamarichal** [comment]
@simoncozens @EbenSorkin 

### **Fontbakery**

This warns appeared in the last version:
```
⚠️ WARN Validate size, and resolution of article images, and ensure article page has minimum length and includes visual assets.
Family metadata at ofl/eduauvicwantpre does not have an article.
```

I just check if it's intentional? 


### **Outlines / Anchors**

**- Ogoneks to check**
Screenshot 2024-09-13 at 15 20 14
Screenshot 2024-09-13 at 15 20 41
Screenshot 2024-09-13 at 15 21 19
Screenshot 2024-09-13 at 15 23 15

**- Regarding quotes and https://github.com/google/fonts/pull/8022#issuecomment-2294410205, is this result ok?**

Screenshot 2024-09-13 at 15 19 02

**- caron.alt position looks wrong**

Screenshot 2024-09-13 at 15 23 35
Screenshot 2024-09-13 at 15 26 10

**- check this**
Screenshot 2024-09-13 at 15 20 28

**Comment by simoncozens** [comment]
I fixed the anchors on these glyphs.

**Pull request merged**
