### PR TITLE
asapcondensed: v1.006 added

### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by davelab6** [comment]
RFN?

**Comment by m4rc1e** [comment]
The Asap Condensed files include a Hindi font called Jaldi. I didn't include Jaldi in this release. This was also the default copyright string. I'm guessing they did this so it doesn't need editing for either subset.

@davelab6 I'm more than happy to remove Jaldi from the RFN if you wish?

**Comment by davelab6** [comment]
@m4rc1e thanks for clarifying, lets review this next year

**Comment by davelab6** [comment]
Superceded by https://github.com/google/fonts/pull/1033

**Pull request merged**
