### PR TITLE
Add sample text for Hentaigana

### PR DESCRIPTION
**Pull request by simoncozens**

### CODE REVIEW

**Comment by vv-monsalve** [comment]
The sample text included in the metadata looks unintelligible is not possible to review here. I'll merge this here and inspect it on dev server.

**Comment by m4rc1e** [comment]
I don't think this has made it to the dev server since the sample text is latin.

Screenshot 2024-10-18 at 15 50 17

@garretrieger @simoncozens

**Comment by emmamarichal** [comment]
Ah? I saw it working in sandbox: https://github.com/google/fonts/pull/7327#issuecomment-2346117143

**Comment by vv-monsalve** [comment]
This PR can be tracked by #7327. I'm removing this one from the Traffic jam board.

**Pull request merged**
