### PR TITLE
Noto Sans Modi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
a059250: [gftools-packager] Noto Sans Modi: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Modi Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/modi.git at commit https://github.com/notofonts/modi/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens 1 and 2 is problematic, 3 is improvement ?

Desktop_OS_X_High_Sierra_safari_11 1_

kerns_new

marks_missing

**Comment by simoncozens** [comment]
The first one is a fix: https://github.com/notofonts/modi/issues/6
The last one is a fix: https://github.com/notofonts/modi/issues/1

I don't know what the second one is showing. I need a text sequence to test these...

**Comment by simoncozens** [comment]
The second one is not a real problem, just a fontdiffenator problem. The kern should not be there in the sources, but it is not actually activated by the shaper.

**Comment by RosaWagner** [comment]
@simoncozens sample text in sandbox:

Capture d’écran 2022-10-05 à 12 11 59

**Comment by simoncozens** [comment]
Partly a subset issue:

```
modi missing the following codepoints to render samples in sa_Modi:

0x093D  ऽ DEVANAGARI SIGN AVAGRAHA
```

We don't have that codepoint in the font, either; I'll add it.

**Pull request merged**
