### PR TITLE
Otomanopee One: Version 3.003; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by aaronbell**
8f3cc5d: [gftools-packager] Otomanopee One: Version 3.003; ttfautohint (v1.8.3) added

* Otomanopee One Version 3.003; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Gutenberg-Labo/Otomanopee.git at commit https://github.com/Gutenberg-Labo/Otomanopee/commit/bbda248048584055da6708b317a4d4f4b5d97a79.

 eb0da7c: [gftools-packager] ofl/otomanopeeone remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by m4rc1e** [comment]
Was this built with fontmake? if it was, we should try and get https://github.com/googlefonts/ufo2ft/pull/438 merged which will solve the nested component issue.

**Comment by aaronbell** [comment]
Yes, but I can work around not having that option right now (export to ufo first, apply filter, generate font). So no need to rush the commit.

**Comment by aaronbell** [comment]
Updated

## Otomanopee One: Version 3.003; ttfautohint (v1.8.3) added

---
 8129e3b: [gftools-packager] Otomanopee One: Version 3.003; ttfautohint (v1.8.3) added

* Otomanopee One Version 3.003; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Gutenberg-Labo/Otomanopee.git at commit https://github.com/Gutenberg-Labo/Otomanopee/commit/21c3571eebc24b2723f94ef25dbf478c3a996047.

 d42b2cf: [gftools-packager] ofl/otomanopeeone remove METADATA "source".  google/fonts#2587

**Comment by aaronbell** [comment]
This should be working now. I actually just needed to wait for the designer to merge my PR :D

**Comment by m4rc1e** [comment]
This family has fallen through the cracks and isn't served in prod

**Pull request merged**
