### PR TITLE
Truculenta: Version 1.002 added

### PR DESCRIPTION
**Pull request by RosaWagner**
0b4b81c: [gftools-packager] Truculenta: Version 1.002 added

* Truculenta Version 1.002 taken from the upstream repo https://github.com/Omnibus-Type/Truculenta at commit https://github.com/Omnibus-Type/Truculenta/commit/ac07749ba0cdf141b5e91f83e74e6b64908aea6d.

 93d1183: [gftools-packager] ofl/truculenta remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
## Fontbakery report

Fontbakery version: 0.7.33

<details>
<summary><b>[4] Truculenta[opsz,wdth,wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Is this a proper HTML snippet?</summary>

* [com.google.fonts/check/description/valid_html](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/valid_html)
<pre>--- Rationale ---

Sometimes people write malformed HTML markup. This check should ensure the file
is good.

Additionally, when packaging families for being pushed to the `google/fonts`
git repo, if there is no DESCRIPTION.en_us.html file, some older versions of
the `add_font.py` tool insert a dummy description file which contains invalid
html. This file needs to either be replaced with an existing description file
or edited by hand.


</pre>

* 🔥 **FAIL** /Users/rosalie/Development/GF_qa/Truculenta/fonts/ofl/truculenta/DESCRIPTION.en_us.html does not look like a propper HTML snippet. Please look for syntax errors. Maybe the following parser error message can help you find what's wrong:
----------------
xmlParseEntityRef: no name, line 6, column 51 (<string>, line 6)
----------------
 [code: malformed-snippet]

</details>
<details>
<summary>🔥 <b>FAIL:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.


</pre>

* 🔥 **FAIL** Please create a subdirectory called "static/" and include in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 2 | 41 | 8 | 141 | 0 |
| 0% | 1% | 1% | 21% | 4% | 73% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [Truculenta.zip](http://35.238.63.0/media/8e3f55d2-402f-4239-8ac8-77429628b2ba/Truculenta.zip)

**Comment by RosaWagner** [comment]
Boh I couldn't have a complete preview, but what went through looks okay.

[Truculenta_previews.zip](https://github.com/google/fonts/files/5704216/Truculenta_previews.zip)

**Comment by RosaWagner** [comment]
Thank you bot. This is strange news you bringing me here… I have an axis mapping parameter in the sources so why the avar was not generated?

I don't understand what is wrong with the snippet.

**Comment by m4rc1e** [comment]
Description needs double checking. It doesn't flow too well.

**Pull request merged**
