### PR TITLE
Noto Serif Sinhala: Version 2.004 added

### PR DESCRIPTION
**Pull request by simoncozens**
28d79c6: [gftools-packager] Noto Serif Sinhala: Version 2.004 added

* Noto Serif Sinhala Version 2.004 taken from the upstream repo https://github.com/notofonts/sinhala.git at commit https://github.com/notofonts/sinhala/commit/.

### CODE REVIEW

**Review by m4rc1e — DISMISSED** [review]
Following string looks suspect:

"ත𑇤◌කෳ්ඁ

Screenshot 2022-07-06 at 15 08 24

Oh my my have tofus in the string here ;-)

**Comment by vv-monsalve** [comment]
You may want to review the kerning also
kerns_new-cut

**Comment by vv-monsalve** [comment]
@simoncozens could you confirm the reported cases above?

**Comment by simoncozens** [comment]
Ohh. Turns out it's turning on the dlig feature and not telling me. Thanks, fontdiffenator!

**Comment by simoncozens** [comment]
Right, I see the change and it's potentially a bug in the font. I'll work on it.

**Comment by simoncozens** [comment]
New version incoming.

**Comment by simoncozens** [comment]
Actually it'll probably just put the new version onto the same PR

**Comment by vv-monsalve** [comment]
> Marc's cases are fine - it's the same issue as #4879; when there are two vowels on a base, we form a ligature glyph with the above vowel. I'm happy with that.

Ok. Thanks for the clarification.

New diff images look LGTM

**Comment by vv-monsalve** [comment]
After some finding when running local test for the Sans version, I've run the same local tests for the Serif version.
@simoncozens despite not having a reflow in paragraphs for the serif variant, are the new glyphs ok?

**OS X High Sierra Safari_11**
Desktop_OS_X_High_Sierra_safari_11 1_

**Windows 10 E
Desktop_Windows_10_edge_18 0_
dge_18**

**Comment by simoncozens** [comment]
OK, there are a couple of glyph category issues here.

**Comment by simoncozens** [comment]
Oh joy, I'm getting different results on different Harfbuzz versions.

**Comment by RosaWagner** [comment]
@simoncozens if you think a font shouldn't go to sandbox yet, feel free to add the label "Blocked" so it doesn't end up in the sandbox list. In the PR fixing it, you can add in comment "unblocking #..." so I know which one should be tracked ;)

**Pull request merged**
