### PR TITLE
Cairo Play: Version 3.130;gftools[0.9.24.dev9+gaf4c611] added

### PR DESCRIPTION
**Pull request by RosaWagner**
ad4f001: [gftools-packager] Cairo Play: Version 3.130;gftools[0.9.24.dev9+gaf4c611] added

* Cairo Play Version 3.130;gftools[0.9.24.dev9+gaf4c611] taken from the upstream repo https://github.com/Gue3bara/Cairo at commit https://github.com/Gue3bara/Cairo/commit/617ed31e442f2be1ae31bdd7f3a88693fc41ae8b.

### CODE REVIEW

**Review by m4rc1e — APPROVED** [review]
Before:

Screenshot 2023-03-02 at 09 56 21

After:

Screenshot 2023-03-02 at 09 56 40


Only issue is what appears to be missing kerns on the Reh:

Screenshot 2023-03-02 at 09 57 36


Since this fixes a major issue, we should merge it.

**Comment by yanone** [comment]
Holding this back because Khaled may have fixed the glyphsLib issue that led to the duplicate red layer. Will check today and report back

**Comment by yanone** [comment]
I'm closing this because I manually added CairoPlay to the other PR #5924 and now I don't know how to undo it, so committing new versions over there.

**Comment by RosaWagner** [comment]
@yanone Please let's try to avoid manual addition, and let's keep PRs separated. We need the commit numbers to be in sync, and to track fonts individually once merged. Close the other one and re-do it if there is something wrong.

**Pull request closed without merging**
