### PR TITLE
Solitreo: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by eliheuer**
ff1a2f7: [gftools-packager] Solitreo: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

* Solitreo Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/ladinoprojects/solitreo at commit https://github.com/ladinoprojects/solitreo/commit/fd2871e6298fec55c9bb6e257adf4c8bc688785d.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@eliheuer can you confirm the 2 scripts are scaled correctly to match with each other?  

Desktop_Windows_10_chrome_71 0_

**Comment by eliheuer** [comment]
@RosaWagner Yes, I did the best I could trying to match the two scripts, but I'm sure I could have done a better job somehow, and If there is something specific I could have done better I'm open to suggestions and could update the source. 

It's a very strange style of Hebrew, mostly small characters, but with a few large loopy ones, so it was hard to match with the Latin. There were some Latin glyphs included by the original designer, so I mostly tried to match the Latin with those.

This is what it should look like in use: 

solitro

**Comment by eliheuer** [comment]
@davelab6 I have a lot of free time this week, if there is anything that you would have done differently with this project please let me know and I will do it.

I'm also open to the idea that this font just won't work on Google Fonts and the PR should be closed, the [upstream project](https://documentingjudeospanish.com/) can still use the font even if it is not on Google Fonts.

**Comment by eliheuer** [comment]
I'm working on a new version of this font with improved proportions between the Hebrew and Latin, will update this PR with that hopefully next week.

**Comment by vv-monsalve** [comment]
Hi @eliheuer 

> I'm working on a new version of this font with improved proportions between the Hebrew and Latin, will update this PR with that hopefully next week.

Do you have an estimated date for updating the PR? Content editors are asking about this project since I understand they are preparing an article for the font.

**Comment by eliheuer** [comment]
@vv-monsalve @RosaWagner The only thing holding this up is that RTL kerning will not build with the Google Fonts Project Template GitHub Actions, see the issues here:

1) https://github.com/googlefonts/glyphsLib/pull/778
2) https://github.com/googlefonts/glyphsLib/pull/818

I'm going to try to make a new release without RTL kerning today and update this PR, so this should be ready to review tomorrow, just keep in mind that the Hebrew will have many issues due to the RTL kerning being broken. Thanks!

**Comment by eliheuer** [comment]
Updated

## Solitreo: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added

---
 a3d4088: [gftools-packager] Solitreo: Version 1.100; ttfautohint (v1.8.4.7-5d5b) added

* Solitreo Version 1.100; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/ladinoprojects/solitreo.git at commit https://github.com/ladinoprojects/solitreo/commit/9b03239708d7d37e86cb2594cf9360121be0740e.

**Comment by eliheuer** [comment]
@RosaWagner @vv-monsalve I made a v1.100 release in the [upstream repo](https://github.com/ladinoprojects/solitreo) and this is now ready for review again.

In order to get the RTL kerning to work, I had to build the font locally using GlyphsLib a branch called [support_glyphs3_rtl_kerning-3](https://github.com/googlefonts/glyphsLib/tree/support_glyphs3_rtl_kerning-3), but the font should build fine with GitHub Actions once RTL kerning is supported in the main branch of GlyphsLib.

Besides RTL kerning the v1.100 release also fixes the scaling issues between the Hebrew and Latin, plus various other bug fixes and some additional Latin kerning as well. 

Thanks! Let me know if any more updates are needed. I'm looking into why the GF-QA check is failing now, but it doesn't seem like a big issue.

**Comment by RosaWagner** [comment]
LGTM

## Fontbakery report

Fontbakery version: 0.8.11a8

</div></details><details><summary>⚠ <b>WARN:</b> URLs on DESCRIPTION file must not display http(s) prefix. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/urls">com.google.fonts/check/description/urls</a>)</summary><div>


* ⚠ **WARN** Please remove the "http(s)://" prefix from the link text "https://github.com/ladinoprojects/solitreo" [code: prefix-found]
</div></details><details><summary>⚠ <b>WARN:</b> Checking OS/2 achVendID. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id">com.google.fonts/check/vendor_id</a>)</summary><div>


* ⚠ **WARN** OS/2 VendorID value 'NONE' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]
</div></details><details><summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts">com.google.fonts/check/metadata/listed_on_gfonts</a>)</summary><div>


* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]
</div></details><details><summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets">com.google.fonts/check/ligature_carets</a>)</summary><div>


* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]
</div></details><details><summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences">com.google.fonts/check/kerning_for_non_ligated_sequences</a>)</summary><div>


* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:

	- uni05D1 + uni05F3

	- uni05F3 + quoteright

	- quoteright + quotesingle

	- uni05D2 + uni05F3

	- uni05F3 + uni05D5

	- uni05D5 + uni05F3

	- uni05F3 + uni05D9

	- uni05D9 + quoteright

	- quoteright + uni05D5

	- uni05D5 + quoteright 

	- And 34 more.

Use -F or --full-lists to disable shortening of long lists. [code: lacks-kern-info]
</div></details><details><summary>⚠ <b>WARN:</b> METADATA.pb: Designers are listed correctly on the Google Fonts catalog? (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/designer_profiles">com.google.fonts/check/metadata/designer_profiles</a>)</summary><div>


* ⚠ **WARN** It seems that Nathan Gross is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]
* ⚠ **WARN** It seems that Bryan Kirschen is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags">com.google.fonts/check/meta/script_lang_tags</a>)</summary><div>


* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]
</div></details><details><summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs">com.google.fonts/check/unreachable_glyphs</a>)</summary><div>


* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:

	- eight.dnom

	- eight.numr

	- five.dnom

	- five.numr

	- four.dnom

	- four.numr

	- nine.dnom

	- nine.numr

	- one.dnom

	- one.numr 

	- And 13 more.

Use -F or --full-lists to disable shortening of long lists.
 [code: unreachable-glyphs]
</div></details><details><summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/contour_count">com.google.fonts/check/contour_count</a>)</summary><div>


* ⚠ **WARN** This font has a 'Soft Hyphen' character (codepoint 0x00AD) which is supposed to be zero-width and invisible, and is used to mark a hyphenation possibility within a word in the absence of or overriding dictionary hyphenation. It is mostly an obsolete mechanism now, and the character is only included in fonts for legacy codepage coverage. [code: softhyphen]
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

	- Glyph name: percent	Contours detected: 4	Expected: 5

	- Glyph name: Q	Contours detected: 3	Expected: 2

	- Glyph name: q	Contours detected: 1	Expected: 2

	- Glyph name: uni2076	Contours detected: 1	Expected: 2

	- Glyph name: uni2086	Contours detected: 1	Expected: 2

	- Glyph name: Q	Contours detected: 3	Expected: 2

	- Glyph name: percent	Contours detected: 4	Expected: 5 

	- And Glyph name: q	Contours detected: 1	Expected: 2
 [code: contour-count]
</div></details><details><summary>⚠ <b>WARN:</b> Ensure dotted circle glyph is present and can attach marks. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/dotted_circle">com.google.fonts/check/dotted_circle</a>)</summary><div>


* ⚠ **WARN** No dotted circle glyph present [code: missing-dotted-circle]
</div></details><br></div></details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 10 | 62 | 8 | 152 | 0 |
| 0% | 0% | 4% | 27% | 3% | 65% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

# [Proof.zip](https://github.com/google/fonts/files/10236453/Proof.zip)

**Pull request merged**
