### PR TITLE
girassol: v1.004 added

### PR DESCRIPTION
**Pull request by liamspradlin**
Adding Girassol - FYI Still need to generate metadata file.

### CODE REVIEW

**Comment by liamspradlin** [comment]
@googlebot I fixed it.

**Comment by liamspradlin** [comment]
Added metadata but needs a double check that the subsets are correct. Also, I do have a CLA for this account but Googlebot is ignoring me. :)

**Comment by arrowtype** [comment]
@m4rc1e did Travis fail to QA this PR due to the CLA issue, or was it something else?

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.15

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** ftxvalidator is not available.

</details>
<br>
</details>
<details>
<summary><b>[8] Girassol-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Copyright notices match canonical pattern in METADATA.pb</summary>

* [com.google.fonts/check/metadata/valid_copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/valid_copyright)

* 🔥 **FAIL** METADATA.pb: Copyright notices should match a pattern similar to:
 "Copyright 2019 The Familyname Project Authors (git url)"
But instead we have got:
"Copyright (c) 2019 by Liam Spradlin" [code: bad-notice-format]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Copyright field for this font on METADATA.pb matches all copyright notice entries on the name table ?</summary>

* [com.google.fonts/check/metadata/nameid/copyright](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/nameid/copyright)

* 🔥 **FAIL** Copyright field for this font on METADATA.pb ("Copyright (c) 2019 by Liam Spradlin") differs from a copyright notice entry on the name table: "Copyright 2019 The Girassol Project Authors (https://github.com/liamspradlin/Girassol-Display)" [code: mismatch]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)

* ⚠ **WARN** OS/2 VendorID value 'LIAM' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---

Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.

But value of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.

Another acceptable value is 2000. Since TT outlines are all integers (no
floats), then instances in a VF suffer rounding compromises, and therefore a
1000 UPM is to small because it forces too many such compromises.

Therefore 2000 is a good &#x27;new VF standard&#x27;, because 2000 is a simple 2x
conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what
10 units can do for 1000 UPM will know what 20 units does too.

Additionally, values above 2048 would result in filesize increases with not
much added benefit.


</pre>

* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.


</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: rupee	Contours detected: 1	Expected: 3
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: etilde	Contours detected: 2	Expected: 3
Glyph name: e	Contours detected: 1	Expected: 2
Glyph name: g	Contours detected: 1	Expected: 2 or 3
Glyph name: gdotaccent	Contours detected: 2	Expected: 3 or 4
Glyph name: thorn	Contours detected: 1	Expected: 2
Glyph name: i	Contours detected: 1	Expected: 2
Glyph name: emacron	Contours detected: 2	Expected: 3
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: ecaron	Contours detected: 2	Expected: 3
Glyph name: ebreve	Contours detected: 2	Expected: 3
Glyph name: uogonek	Contours detected: 2	Expected: 1
Glyph name: egrave	Contours detected: 2	Expected: 3
Glyph name: edotaccent	Contours detected: 2	Expected: 3
Glyph name: gbreve	Contours detected: 2	Expected: 3 or 4
Glyph name: gcircumflex	Contours detected: 2	Expected: 3 or 4
Glyph name: hbar	Contours detected: 2	Expected: 1
Glyph name: Uogonek	Contours detected: 2	Expected: 1
Glyph name: edieresis	Contours detected: 3	Expected: 4
Glyph name: ecircumflex	Contours detected: 2	Expected: 3
Glyph name: Racute	Contours detected: 2	Expected: 3
Glyph name: aogonek	Contours detected: 3	Expected: 2
Glyph name: aeacute	Contours detected: 3	Expected: 4
Glyph name: j	Contours detected: 1	Expected: 2
Glyph name: eacute	Contours detected: 2	Expected: 3
Glyph name: p	Contours detected: 1	Expected: 2
Glyph name: ae	Contours detected: 2	Expected: 3
Glyph name: Q	Contours detected: 3	Expected: 2
Glyph name: oe	Contours detected: 2	Expected: 3
Glyph name: Rcaron	Contours detected: 2	Expected: 3
Glyph name: rupee	Contours detected: 1	Expected: 3 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.


</pre>

* ⚠ **WARN** GDEF table is missing, but it is mandatory to declare it on fonts that provide ligature glyphs because the caret (text cursor) positioning for each ligature must be provided in this table. [code: GDEF-missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- R + R
	- T + T
	- r + r
	- t + t

   [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 7 | 32 | 6 | 114 | 0 |
| 0% | 1% | 4% | 20% | 4% | 71% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [girassol_qa.zip](http://35.238.63.0/media/cacff286-242b-43df-8d0e-3ee0f73169b8/girassol_qa.zip)

**Comment by m4rc1e** [comment]
I dislike the rendering. Characters are jumping at certain sizes. 

Screenshot 2019-11-28 at 12 29 39

I suggest we release it unhinted.

**Comment by liamspradlin** [comment]
Thanks Marc! Since Girassol is really only intended for large sizes, I'm fine with it being unhinted.

**Comment by davelab6** [comment]
Agree about nonhinting

**Comment by liamspradlin** [comment]
Wondering if there's anything I need to do on my end to clear up the Travis checks.

**Comment by m4rc1e** [comment]
@liamspradlin please do the following and I'll rerun the checks

- Remove autohinting. If you're using glyphs to gen the fonts just untick "autohint" in the export menu, otherwise use the following ttfautohint command `ttfautohint -d path/to/font_in.ttf path/to/font_out.ttf`
- Run `gftools fix-nonhinting path/to/font_in.ttf path/to/font_out.ttf`
- Rerun `gftools add-font ./path/to/this/repo/ofl/girassol`

@yanone Please assist if he needs help.

---

Travis is aborting because you're sending a PR from a forked repo and we have private environment variables. 

> Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, it will not have access to the encrypted variables.

https://docs.travis-ci.com/user/environment-variables/

Please ignore this for the time being. I plan to solve this by dropping travis next year. We'll probably use a small dedicated server and Github webhooks instead.

**Comment by yanone** [comment]
I could do it first thing on Thursday, unless @liamspradlin wants to give it a go.
A question: How do you assess whether a font needs hinting or not?

**Comment by m4rc1e** [comment]
> A question: How do you assess whether a font needs hinting or not?

If ttfa doesn't produce a good result (see my image above). I find ttfa does well for text faces only.

**Comment by yanone** [comment]
But how do you produce these images? There's a step in the production process that I'm not aware of yet.

**Comment by m4rc1e** [comment]
Use [gfregression](http://35.238.63.0/) and look at the results on a Windows machine. If you have a browserstack account `gftools qa -f font_in.ttf -gfb -a -out ./out` will use gfregression and browserstack to make diff images.

**Comment by liamspradlin** [comment]
Yanone, if you don't mind making the changes Thursday that would be a huge help to me!

**Comment by m4rc1e** [comment]
Closing. https://github.com/google/fonts/pull/2271 is newer

**Pull request closed without merging**
