### PR TITLE
Noto Sans Newa: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
724ff74: [gftools-packager] Noto Sans Newa: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Newa Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/newa.git at commit https://github.com/notofonts/newa/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens could you confirm this is ok?

Windows 10 Chrome

Desktop_Windows_10_chrome_71 0_

And, something really odd is showed on Safari Sierra 11. BrowserStack? In Safari BigSur 15.4 is only happening the same reported for Windows and Edge (above)

Desktop_OS_X_High_Sierra_safari_11 1_

**Comment by simoncozens** [comment]
The second is clearly a Safari bug! The first looks bad though.

**Comment by simoncozens** [comment]
Yep , confirmed, Repha not attaching to Wa.nohd; looks like a source problem:

shape

**Comment by simoncozens** [comment]
Pre-USE font no longer working in USE...

**Comment by simoncozens** [comment]
Updated

## Noto Sans Newa: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

---
 7c18f76: [gftools-packager] Noto Sans Newa: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Newa Version 2.006; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/newa.git at commit https://github.com/notofonts/newa/commit/.

**Comment by RosaWagner** [comment]
@simoncozens some mark shifts

marks_missing

https://user-images.githubusercontent.com/12222436/196959842-4da22046-7789-4b90-a5fa-556de50f2c56.mov

**Comment by simoncozens** [comment]
Updated

## Noto Sans Newa: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added

---
 7b3020c: [gftools-packager] Noto Sans Newa: Version 2.007; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Newa Version 2.007; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/newa.git at commit https://github.com/notofonts/newa/commit/.

**Comment by simoncozens** [comment]
There are some mark changes, but I'm happy with the ones above apart from 𑐉𑑂, which I have now fixed in 2.007.

**Pull request merged**
