### PR TITLE
Roboto: Version 3.008; 2023 added

### PR DESCRIPTION
**Pull request by m4rc1e**
4dd6e2b: [gftools-packager] Roboto: Version 3.008; 2023 added

* Roboto Version 3.008; 2023 taken from the upstream repo https://github.com/googlefonts/roboto-classic at commit https://github.com/googlefonts/roboto-classic/commit/.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
This is the variable font format upgrade, Marc?

**Comment by m4rc1e** [comment]
Let's get this through to SB

**Comment by vv-monsalve** [comment]
Does this PR supersede #5020?

**Comment by m4rc1e** [comment]
Correct

**Pull request merged**
