### PR TITLE
Noto Nastaliq Urdu: Version 3.004 added

### PR DESCRIPTION
**Pull request by simoncozens**
719fd3a: [gftools-packager] Noto Nastaliq Urdu: Version 3.004 added

* Noto Nastaliq Urdu Version 3.004 taken from the upstream repo https://github.com/notofonts/nastaliq.git at commit https://github.com/notofonts/nastaliq/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
Mark positions look better. Change of the number sign is a bit concerning, I can't remember why that changed. U+077A and U+077B being empty is actually bad, needs fixing.

**Comment by simoncozens** [comment]
Updated

## Noto Nastaliq Urdu: Version 3.005 added

---
 6f0d8ba: [gftools-packager] Noto Nastaliq Urdu: Version 3.005 added

* Noto Nastaliq Urdu Version 3.005 taken from the upstream repo https://github.com/notofonts/nastaliq.git at commit https://github.com/notofonts/nastaliq/commit/.

**Comment by simoncozens** [comment]
Oh, I didn't know it would do that. That works!

**Comment by vv-monsalve** [comment]
@simoncozens Something is happening quite different for the Bold font in Safari.

**OS X High Sierra Safari_11**
Desktop_OS_X_High_Sierra_safari_11 1_
**Windows 10 Chrome_71**
Desktop_Windows_10_chrome_71 0_
**Windows 10 Edge_18**
Desktop_Windows_10_edge_18 0_

**Comment by simoncozens** [comment]
That's *very* weird.

**Comment by khaledhosny** [comment]
> Mark positions look better. Change of the number sign is a bit concerning, I can't remember why that changed. U+077A and U+077B being empty is actually bad, needs fixing.

The change no number sign is good, but the position of the small numbers in ݳݴ is wrong.

**Comment by simoncozens** [comment]
Updated

## Noto Nastaliq Urdu: Version 3.006 added

---
 bfdf91a: [gftools-packager] Noto Nastaliq Urdu: Version 3.006 added

* Noto Nastaliq Urdu Version 3.006 taken from the upstream repo https://github.com/notofonts/nastaliq.git at commit https://github.com/notofonts/nastaliq/commit/.

**Comment by vv-monsalve** [comment]
> @simoncozens Something is happening quite different for the Bold font in Safari.

This is still happening for Safari Sierra 11 and Mojave 12.1. After Catalina 13.1 it's only the spacing/kerning differences.

According wiki Safari 12.x "Bundled with macOS 10.14 Mojave.[[75]](https://en.wikipedia.org/wiki/Safari_version_history#cite_note-75) Ends support for OS X 10.11 El Capitan." 12.1.2 Release date: July 22, 2019

cc @m4rc1e 

**Sierra Safari 11.1**
Nastaliq-Urdu-Safari-Sierra-11

**Sierra Mojave 12.1**
Nastaliq-Urdu-Mojave-12-1

**Sierra Catalina 13.1**
Nastaliq-Urdu-Catalina-13-1

**Comment by simoncozens** [comment]
I'm trying to get a OS X High Sierra VM installed to have a look at this and other Safari 11 issues.

**Comment by simoncozens** [comment]
I'm an idiot. I'm a complete idiot.

This is *fine*.

There is reflow in the bold, and it's been made looser, but that was part of variabalizing it. But the rendering is absolutely fine. The reflow is throwing us off because we are reading it left to right. But it's Arabic. Read it right-to-left and ignore the script-neutral numbers at the beginning of the paragraph and it's just standard reflow.

Screenshot 2022-07-29 at 22 08 23

BiDi is hard.

**Comment by vv-monsalve** [comment]
> But it's Arabic. Read it right-to-left and ignore the script-neutral numbers at the beginning of the paragraph and it's just standard reflow.

We all somehow overlooked this!

**Comment by vv-monsalve** [comment]
Last question, before going to Sandbox. Description in the [current specimen](https://fonts.google.com/noto/specimen/Noto+Nastaliq+Urdu) says 

> Noto Nastaliq Urdu is a cursive, modulated (“serif”) 

However, the new Latin companion is a Sans Serif font.

Screen Shot 2022-07-29 at 18 04 05

**Comment by twardoch** [comment]
Is there a real companion or is this just CSS fallback in the test that happens to be sans?

**Comment by vv-monsalve** [comment]
> Is there a real companion or is this just CSS fallback in the test that happens to be sans?

It's the real companion on the font

**Comment by simoncozens** [comment]
This is a good point. I'll replace it with a serif. (The algorithm adds Noto Serif Latin core to all fonts called "Noto Serif..." and Noto Sans Latin core to everything else. I didn't think about "Noto Naskh", "Noto Nastaliq", "Noto Looped", "Noto Traditional", and they will all get sans. Turns out this is almost always wrong. But we can fix it in the config file.)

**Comment by simoncozens** [comment]
Updated

## Noto Nastaliq Urdu: Version 3.007 added

---
 f912c35: [gftools-packager] Noto Nastaliq Urdu: Version 3.007 added

* Noto Nastaliq Urdu Version 3.007 taken from the upstream repo https://github.com/notofonts/nastaliq.git at commit https://github.com/notofonts/nastaliq/commit/.

**Comment by vv-monsalve** [comment]
LGTM

**Comment by chrissimpkins** [comment]
Still requires a prod push

**Pull request merged**
