### PR TITLE
Literata: Version 3.021 added

### PR DESCRIPTION
**Pull request by aaronbell**
69d495d: [gftools-packager] Literata: Version 3.021 added

* Literata Version 3.021 taken from the upstream repo https://github.com/googlefonts/literata at commit https://github.com/googlefonts/literata/commit/e2319ff4e68662e3b2f85fe70a148d12bc6e37b0.

 1f68cd0: [gftools-packager] ofl/literata remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by thlinard** [comment]
ExtraLight instance in `STAT` but not in `fvar` (much less of an issue than the other way around, but there is an ExtraLight instance in the API: https://fonts.google.com/specimen/Literata).

**Comment by aaronbell** [comment]
It isn't clear to me why the ExtraLight instance is not showing up in fvar. The source masters are there and in the designspace doc. It may be that the source / build process needs to be overhauled. In the meantime, this PR fixes up the `stat` table :).

**Comment by thlinard** [comment]
Oh, I hadn't seen: there is also a Black (900) instance missing in `fvar`. But in fact both `<instance>` are missing from vf-*.designspace in the source.

But indeed, the issue is less serious this way. 😄

**Comment by thlinard** [comment]
What holds back this PR?

**Comment by RosaWagner** [comment]
Updated

## Literata: Version 3.102;gftools[0.9.29] added

---
 1508d77: [gftools-packager] Literata: Version 3.102;gftools[0.9.29] added

* Literata Version 3.102;gftools[0.9.29] taken from the upstream repo https://github.com/googlefonts/literata at commit https://github.com/googlefonts/literata/commit/5996ce787044ff9b1e993d8d104a1d58010bf161.

**Comment by RosaWagner** [comment]
closing this old PR and opening a new one

**Pull request closed without merging**
