### PR TITLE
Revert "Rokkitt v3.103 (stat fix)"

### PR DESCRIPTION
**Pull request by m4rc1e**
Reverts google/fonts#3663

### CODE REVIEW

**Comment by m4rc1e** [comment]
@aaronbell apologies, I merged this without inspecting the diffs thoroughly. It appears that #3663 is missing the fl ligature.

glyphs_missing

Can you add this and make another pr?

**Comment by aaronbell** [comment]
Will do. I have to say, I have been really frustrated in how, in many cases, the sources don't seem to line up with the current ship font. I guess that's what happens when PRs happen from various different locations?

**Comment by m4rc1e** [comment]
Can also happen due to changes in the build system and original designers updating the sources.

Tip. Search for the previous PR in this repo to discover the correct source.

**Comment by aaronbell** [comment]
Thanks Marc. Yeah, that was the approach I'd used. Clearly wasn't sufficient!

**Pull request merged**
