### PR TITLE
IBM Plex Sans Condensed: Version 1.3 added

### PR DESCRIPTION
**Pull request by yanone**
76e09d5: [gftools-packager] IBM Plex Sans Condensed: Version 1.3 added

* IBM Plex Sans Condensed Version 1.3 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/308cac76d04da9df05dd518ff513607e9d0fcb00.

 53890d3: [gftools-packager] ofl/ibmplexsanscondensed remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by yanone** [comment]
All visible FAILs are intentionally left in place:
* Vertical metrics (checked for regression)
* Copyright strings left untouched
* Hinting-related: `fix-nonhinting` (as suggested in the FAIL) messed up the manual hinting.

Basically, I just went over the name table.

**Comment by yanone** [comment]
@m4rc1e When you review this one, pay special attention to the names. I just noticed that in my work I had expanded shortened names into full names, such as the Condensed’s postScript names.(IBMPlexSansCond-Medium)
If those need to stay the same, then we may consider to not change anything at all in the fonts actually.
I noticed that I implemented the specs/fontbakery checks regarding names, rather than looking at the already published fonts, which may have been a mistake.

**Comment by yanone** [comment]
@m4rc1e Basically I think I need to ask you to look at a fontbakery check (or the name table directly) of one of the original unchanged non-RBBI fonts which you find right here in this repo (or the ones live right now) to see whether their name tables are legit. I thought I should follow the fontbakery checks here, but the old fonts don't follow them either, so I'm really unsure here.

**Comment by yanone** [comment]
Regarding font names: I prepared [this overview](https://github.com/googlefonts/plex/blob/master/Google-Fonts-Fixes/IBM%20Sans%20Names.ods) (.ods file) that compares the name tables of the 1) currently live fonts, 2) the incoming updates by IBM, and 3) my hotfixed versions in this PR (separate tab for Sans & Sand Condensed in the same file)

Red marks my changes against the LIVE fonts.
Blue marks diffs of the incoming updates against the LIVE fonts

What it shows:

* The incoming updates (middle columns) are named differently than the LIVE fonts with abbreviated names for the Condensed for family and style values, and some name ID 16 diffs
* My hotfixes differ from the LIVE fonts only in the postScript name

I propose: I stick to the naming pattern of the LIVE fonts:

* Ignore all names of the incoming updates
* Drop Mac names altogether
* Keep all other names identical to LIVE fonts (with abbreviated postScript family name)

**Comment by RosaWagner** [comment]
I would also go for keeping the naming of the already live fonts (and drop all mac names), so the RIBBI scheme of nameID 2 is maintained. If @m4rc1e agrees, we should also change the spec in that regard.

**Comment by davelab6** [comment]
FWIW I agree with Jan's proposal too

**Comment by yanone** [comment]
Updated

## IBM Plex Sans Condensed: Version 1.3 added

---
 4184337: [gftools-packager] IBM Plex Sans Condensed: Version 1.3 added

* IBM Plex Sans Condensed Version 1.3 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/5489e99859e9b4a88faf3013324d89a34a294c53.

 6b87b21: [gftools-packager] ofl/ibmplexsanscondensed remove METADATA "source".  google/fonts#2587

**Comment by yanone** [comment]
I updated the name tables. This is ready for review now.

**Comment by yanone** [comment]
Updated

## IBM Plex Sans Condensed: Version 1.3 added

---
 a5cfc3d: [gftools-packager] IBM Plex Sans Condensed: Version 1.3 added

* IBM Plex Sans Condensed Version 1.3 taken from the upstream repo https://github.com/googlefonts/plex at commit https://github.com/googlefonts/plex/commit/71d012bccb31a2e282cc46de63b387ff7f676287.

 2736018: [gftools-packager] ofl/ibmplexsanscondensed remove METADATA "source".  google/fonts#2587

**Pull request merged**
