### PR TITLE
Update Fira Code to v6

### PR DESCRIPTION
**Pull request by tonsky**
Compare: https://github.com/tonsky/FiraCode/compare/5.2...6

Release notes: https://github.com/tonsky/FiraCode/releases/tag/6

Issue: https://github.com/tonsky/FiraCode/issues/1141

### CODE REVIEW

**Comment by RosaWagner** [comment]
Please tell us if this upgrade is fixing any of these issues: https://github.com/google/fonts/issues?q=is%3Aissue+is%3Aopen+fira

**Comment by RosaWagner** [comment]
Great thank you for linking into it :)
## Fontbakery report

Fontbakery version: 0.8.4

<details>
<summary><b>[19] FiraCode[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---
Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.
The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.
But values of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.
Additionally, values above 2048 would likely result in unreasonable filesize
increases.</pre>

* 🔥 **FAIL** Font em size (unitsPerEm) is 1950. If possible, please consider using 1000. Good values for unitsPerEm, though, are typically these: [16, 32, 64, 128, 256, 500, 512, 1000, 1024, 2000, 2048]. [code: bad-value]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Ensure component transforms do not perform scaling or rotation.</summary>

* [com.google.fonts/check/transformed_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/transformed_components)
<pre>--- Rationale ---
Some families have glyphs which have been constructed by using transformed
components e.g the &#x27;u&#x27; being constructed from a flipped &#x27;n&#x27;.
From a designers point of view, this sounds like a win (less work). However,
such approaches can lead to rasterization issues, such as having the &#x27;u&#x27; not
sitting on the baseline at certain sizes after running the font through
ttfautohint.
As of July 2019, Marc Foley observed that ttfautohint assigns cvt values to
transformed glyphs as if they are not transformed and the result is they render
very badly, and that vttLib does not support flipped components.
When building the font with fontmake, this problem can be fixed by using the
&quot;Decompose Transformed Components&quot; filter.</pre>

* 🔥 **FAIL** The following glyphs had components with scaling or rotation:

* uni0123 (component uni0326)
* uni0123.cv02 (component uni0326)
* uni04FE (component hyphen)
* uni03FE (component uni0307)
* uni03FF (component uni0307)
* dottedlunatesigmasymbol (component uni0307)
* reverseddottedlunatesigmasymbol (component uni0307)
* canadiansyllabicsa (component canadiansyllabicso)
* zero.cv12 (component zero)
* zero.tosf.cv12 (component zero.tosf)
* uni27E9 (component uni27E8)
* backslash_slash.liga (component slash_backslash.liga)
* hyphen_end.seq (component hyphen_start.seq)
* uni2770 (component uni2771)
* braceright.cv29 (component braceleft.cv29)
* parenright.cv31 (component parenleft.cv31)
* uni0375 (component uni02B9)
* acknowledgecontrol (component A)
* acknowledgecontrol (component C)
* acknowledgecontrol (component K)
* uni2387 (component uni2325)
* backspacecontrol (component B)
* backspacecontrol (component S)
* bar_braceright.liga (component braceleft_bar.liga)
* bar_bracketright.liga (component bracketleft_bar.liga)
* bellcontrol (component B)
* bellcontrol (component E)
* bellcontrol (component L)
* cancelcontrol (component C)
* cancelcontrol (component A)
* cancelcontrol (component N)
* carriageReturncontrol (component C)
* carriageReturncontrol (component R)
* dataLinkEscapecontrol (component D)
* dataLinkEscapecontrol (component L)
* dataLinkEscapecontrol (component E)
* deletecontrol (component D)
* deletecontrol (component L)
* deletecontrol (component E)
* deviceControlFourcontrol (component D)
* deviceControlFourcontrol (component C)
* deviceControlFourcontrol (component four)
* deviceControlOnecontrol (component D)
* deviceControlOnecontrol (component C)
* deviceControlOnecontrol (component one)
* deviceControlThreecontrol (component D)
* deviceControlThreecontrol (component C)
* deviceControlThreecontrol (component three)
* deviceControlTwocontrol (component D)
* deviceControlTwocontrol (component C)
* deviceControlTwocontrol (component two)
* endOfMediumcontrol (component E)
* endOfMediumcontrol (component M)
* endOfTextcontrol (component E)
* endOfTextcontrol (component T)
* endOfTextcontrol (component X)
* endOfTransmissioncontrol (component E)
* endOfTransmissioncontrol (component O)
* endOfTransmissioncontrol (component T)
* endOfTransmissionBlockcontrol (component E)
* endOfTransmissionBlockcontrol (component T)
* endOfTransmissionBlockcontrol (component B)
* enquirycontrol (component E)
* enquirycontrol (component N)
* enquirycontrol (component Q)
* escapecontrol (component E)
* escapecontrol (component S)
* escapecontrol (component C)
* fileSeparatorcontrol (component F)
* fileSeparatorcontrol (component S)
* formFeedcontrol (component F)
* formFeedcontrol (component F)
* groupSeparatorcontrol (component G)
* groupSeparatorcontrol (component S)
* horizontalTabulationcontrol (component H)
* horizontalTabulationcontrol (component T)
* uni21DF (component uni21DE)
* lineFeedcontrol (component L)
* lineFeedcontrol (component F)
* negativeAcknowledgecontrol (component N)
* negativeAcknowledgecontrol (component A)
* negativeAcknowledgecontrol (component K)
* newlinecontrol (component N)
* newlinecontrol (component L)
* nullcontrol (component N)
* nullcontrol (component U)
* nullcontrol (component L)
* less_bar.liga (component bar_greater.liga)
* less_bar_bar.liga (component bar_bar_greater.liga)
* less_bar_bar_bar.liga (component bar_bar_bar_greater.liga)
* less_equal.liga (component greater_equal.liga)
* less_less.liga (component greater_greater.liga)
* less_less_less.liga (component greater_greater_greater.liga)
* less_asciitilde.liga (component asciitilde_greater.liga)
* less_asciitilde_asciitilde.liga (component asciitilde_asciitilde_greater.liga)
* asciitilde_hyphen.liga (component hyphen_asciitilde.liga)
* recordSeparatorcontrol (component R)
* recordSeparatorcontrol (component S)
* shiftIncontrol (component S)
* shiftIncontrol (component I)
* shiftOutcontrol (component S)
* shiftOutcontrol (component O)
* spacecontrol (component S)
* spacecontrol (component P)
* startOfHeadingcontrol (component S)
* startOfHeadingcontrol (component O)
* startOfHeadingcontrol (component H)
* startOfTextcontrol (component S)
* startOfTextcontrol (component T)
* startOfTextcontrol (component X)
* substitutecontrol (component S)
* substitutecontrol (component U)
* substitutecontrol (component B)
* substituteFormTwocontrol (component question)
* synchronousIdlecontrol (component S)
* synchronousIdlecontrol (component Y)
* synchronousIdlecontrol (component N)
* uni218B (component three)
* uni218A (component two)
* unitSeparatorcontrol (component U)
* unitSeparatorcontrol (component S)
* verticalTabulationcontrol (component V)
* verticalTabulationcontrol (component T)
* bar_hyphen_end.seq (component bar_hyphen_start.seq)
* bar_bar_hyphen_end.seq (component bar_bar_hyphen_start.seq)
* bar_bar_equal_end.seq (component bar_bar_equal_start.seq)
* bar_equal_end.seq (component bar_equal_start.seq)
* less_hyphen_end.seq (component greater_hyphen_start.seq)
* less_hyphen_middle.seq (component greater_hyphen_middle.seq)
* less_hyphen_start.seq (component greater_hyphen_end.seq)
* less_equal_end.seq (component greater_equal_start.seq)
* less_equal_middle.seq (component greater_equal_middle.seq)
* less_equal_start.seq (component greater_equal_end.seq)
* less_less_hyphen_end.seq (component greater_greater_hyphen_start.seq)
* less_less_hyphen_middle.seq (component greater_greater_hyphen_middle.seq)
* less_less_hyphen_start.seq (component greater_greater_hyphen_end.seq)
* less_less_equal_end.seq (component greater_greater_equal_start.seq)
* less_less_equal_middle.seq (component greater_greater_equal_middle.seq)
* less_less_equal_start.seq (component greater_greater_equal_end.seq)
* less_equal.ss02 (component greater_equal.ss02)
* uni2235 (component therefore)
* uni220D (component uni220A)
* existential (component E)
* gradient (component uni2206)
* logicalor (component logicaland)
* union (component intersection)
* uni239F (component uni239C)
* uni23A0 (component uni239D)
* uni239E (component uni239B)
* reflexsuperset (component reflexsubset)
* uni23AD (component uni23A9)
* uni23AC (component uni23A8)
* uni23AB (component uni23A7)
* uni23A5 (component uni23A2)
* uni23A6 (component uni23A3)
* uni23A4 (component uni23A1)
* suchthat (component element)
* propersuperset (component propersubset)
* uni22A3 (component uni22A2)
* universal (component A)
* uni22A5 (component uni22A4)
* less.center (component greater.center)
* uni21E4 (component uni21E5)
* uni21AA (component uni21A9)
* uni21B0 (component uni21B2)
* uni21B1 (component uni21B2)
* uni21B3 (component uni21B2)
* uni27F2 (component uni27F3)
* uni27F1 (component uni27F0)
* uni27F5 (component uni27F6)
* uni27F8 (component uni27F9)
* uni27FB (component uni27FC)
* uni27FD (component uni27FE)
* uni2572 (component uni2571)
* uni030F (component hungarumlaut)
* uni0314 (component uni0326)
* uniE0B2 (component uniE0B0)
* uniE0B3 (component uniE0B1)
* uniEE02 (component uniEE00)
* uniEE05 (component uniEE03)
* uniEE0A (component uniEE08)
* uniEE0B (component uniEE07)
 [code: transformed-components]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check glyphs do not have components which are themselves components.</summary>

* [com.google.fonts/check/glyf_nested_components](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyf_nested_components)
<pre>--- Rationale ---
There have been bugs rendering variable fonts with nested components.
Additionally, some static fonts with nested components have been reported to
have rendering and printing issues.
For more info, see:
* https://github.com/googlefonts/fontbakery/issues/2961
* https://github.com/arrowtype/recursive/issues/412</pre>

* 🔥 **FAIL** The following glyphs have components which themselves are component glyphs:
	* Adieresis
	* Amacron
	* Aring
	* Atilde
	* Ccedilla
	* Cdotaccent
	* Edieresis
	* Edotaccent
	* Emacron
	* Gdotaccent and 196 more. [code: found-nested-components]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check if the vertical metrics of a family are similar to the same family hosted on Google Fonts.</summary>

* [com.google.fonts/check/vertical_metrics_regressions](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics_regressions)
<pre>--- Rationale ---
If the family already exists on Google Fonts, we need to ensure that the checked
family&#x27;s vertical metrics are similar. This check will test the following schema
which was outlined in Fontbakery issue #1162 [1]:
- The family should visually have the same vertical metrics as the Regular style
hosted on Google Fonts.
- If the family on Google Fonts has differing hhea and typo metrics, the family
being checked should use the typo metrics for both the hhea and typo entries.
- If the family on Google Fonts has use typo metrics not enabled and the family
being checked has it enabled, the hhea and typo metrics should use the family on
Google Fonts winAscent and winDescent values.
- If the upms differ, the values must be scaled so the visual appearance is the
same.
[1] https://github.com/googlefonts/fontbakery/issues/1162</pre>

* 🔥 **FAIL** Fira Code Light: OS/2 sTypoAscender is 1800 when it should be 1931 [code: bad-typo-ascender]
* 🔥 **FAIL** Fira Code Light: OS/2 sTypoDescender is -600 when it should be -627 [code: bad-typo-descender]
* 🔥 **FAIL** Fira Code Light: hhea Ascender is 1800 when it should be 1931 [code: bad-hhea-ascender]
* 🔥 **FAIL** Fira Code Light: hhea Descender is -600 when it should be -627 [code: bad-hhea-descender]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent)
<pre>--- Rationale ---
A font&#x27;s winAscent and winDescent values should be greater than the head table&#x27;s
yMax, abs(yMin) values. If they are less than these values, clipping can occur
on Windows platforms (https://github.com/RedHatBrand/Overpass/issues/33).
If the font includes tall/deep writing systems such as Arabic or Devanagari, the
winAscent and winDescent can be greater than the yMax and abs(yMin) to
accommodate vowel marks.
When the win Metrics are significantly greater than the upm, the linespacing can
appear too loose. To counteract this, enabling the OS/2 fsSelection bit 7
(Use_Typo_Metrics), will force Windows to use the OS/2 typo values instead. This
means the font developer can control the linespacing with the typo values,
whilst avoiding clipping by setting the win values to values greater than the
yMax and abs(yMin).</pre>

* 🔥 **FAIL** OS/2.usWinAscent value should be equal or greater than 2400, but got 1800 instead [code: ascent]
* 🔥 **FAIL** OS/2.usWinDescent value should be equal or greater than 1000, but got 600 instead. [code: descent]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Does the font have any invalid script tags?</summary>

* [com.google.fonts/check/layout_valid_script_tags](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/layout.html#com.google.fonts/check/layout_valid_script_tags)
<pre>--- Rationale ---
Incorrect script tags can be indications of typos, leftover debugging code or
questionable approaches, or user error in the font editor. Such typos can cause
features and language support to fail to work as intended.</pre>

* 🔥 **FAIL** The following invalid script tags were found in the font: zinh, zyyy [code: bad-script-tags]

</details>
<details>
<summary>⚠ <b>WARN:</b> URLs on DESCRIPTION file must not display http(s) prefix.</summary>

* [com.google.fonts/check/description/urls](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/urls)
<pre>--- Rationale ---
The snippet of HTML in the DESCRIPTION.en_us.html file is added to the font
family webpage on the Google Fonts website.
Google Fonts has a content formatting policy for that snippet that expects the
text content of links not to include the http:// or https:// prefixes.</pre>

* ⚠ **WARN** Please remove the "http(s)://" prefix from the link text "https://github.com/tonsky/FiraCode" [code: prefix-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)
<pre>--- Rationale ---
Microsoft keeps a list of font vendors and their respective contact info. This
list is updated regularly and is indexed by a 4-char &quot;Vendor ID&quot; which is stored
in the achVendID field of the OS/2 table.
Registering your ID is not mandatory, but it is a good practice since some
applications may display the type designer / type foundry contact info on some
dialog and also because that info will be visible on Microsoft&#x27;s website:
https://docs.microsoft.com/en-us/typography/vendors/
This check verifies whether or not a given font&#x27;s vendor ID is registered in
that list or if it has some of the default values used by the most common font
editors.
Each new FontBakery release includes a cached copy of that list of vendor IDs.
If you registered recently, you&#x27;re safe to ignore warnings emitted by this
check, since your ID will soon be included in one of our upcoming releases.</pre>

* ⚠ **WARN** OS/2 VendorID value 'CTDB' is not yet recognized. If you registered it recently, then it's safe to ignore this warning message. Otherwise, you should set it to your own unique 4 character code, and register it with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx
 [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check copyright namerecords match license file.</summary>

* [com.google.fonts/check/name/license](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license)
<pre>--- Rationale ---
A known licensing description must be provided in the NameID 14 (LICENSE
DESCRIPTION) entries of the name table.
The source of truth for this check (to determine which license is in use) is a
file placed side-by-side to your font project including the licensing terms.
Depending on the chosen license, one of the following string snippets is
expected to be found on the NameID 13 (LICENSE DESCRIPTION) entries of the name
table:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;
Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.
When in doubt, please choose OFL for new font projects.</pre>

* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]

</details>
<details>
<summary>⚠ <b>WARN:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)
<pre>--- Rationale ---
A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry
of the name table.
The source of truth for this check is the licensing text found on the NameID 13
entry (LICENSE DESCRIPTION).
The string snippets used for detecting licensing terms are:
- &quot;This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is available with a FAQ at: https://scripts.sil.org/OFL&quot;
- &quot;Licensed under the Apache License, Version 2.0&quot;
- &quot;Licensed under the Ubuntu Font Licence 1.0.&quot;
Currently accepted licenses are Apache or Open Font License.
For a small set of legacy families the Ubuntu Font License may be acceptable as
well.
When in doubt, please choose OFL for new font projects.</pre>

* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=13] [code: http-in-description]
* ⚠ **WARN** Please consider using HTTPS URLs at name table entry [plat=3, enc=1, name=14] [code: http-in-license-info]
* ⚠ **WARN** For now we're still accepting http URLs, but you should consider using https instead.
 [code: http]

</details>
<details>
<summary>⚠ <b>WARN:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---
Variable font family directories kept in the google/fonts git repo may include a
static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.</pre>

* ⚠ **WARN** Please consider adding a subdirectory called "static/" and including in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Designers are listed correctly on the Google Fonts catalog?</summary>

* [com.google.fonts/check/metadata/designer_profiles](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/designer_profiles)
<pre>--- Rationale ---
Google Fonts has a catalog of designers.
This check ensures that the online entries of the catalog can be found based on
the designer names listed on the METADATA.pb file.
It also validates the URLs and file formats are all correctly set.</pre>

* ⚠ **WARN** It seems that The Mozilla Foundation is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]
* ⚠ **WARN** It seems that Telefonica S.A. is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]
* ⚠ **WARN** It seems that Nikita Prokopov is still not listed on the designers catalog. Please submit a photo and a link to a webpage where people can learn more about the work of this designer/typefoundry. [code: profile-not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Ensure Stylistic Sets have description.</summary>

* [com.google.fonts/check/stylisticset_description](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description)
<pre>--- Rationale ---
Stylistic sets should provide description text. Programs such as InDesign,
TextEdit and Inkscape use that info to display to the users so that they know
what a given stylistic set offers.</pre>

* ⚠ **WARN** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss02 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss03 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss04 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss05 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss06 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss07 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss08 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss09 lacks a description string on the 'name' table. [code: missing-description]
* ⚠ **WARN** The stylistic set ss10 lacks a description string on the 'name' table. [code: missing-description]

</details>
<details>
<summary>⚠ <b>WARN:</b> Ensure fonts have ScriptLangTags declared on the 'meta' table.</summary>

* [com.google.fonts/check/meta/script_lang_tags](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/meta/script_lang_tags)
<pre>--- Rationale ---
The OpenType &#x27;meta&#x27; table originated at Apple. Microsoft added it to OT with
just two DataMap records:
- dlng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font is designed for
- slng: comma-separated ScriptLangTags that indicate which scripts, or languages
and scripts, with possible variants, the font supports
The slng structure is intended to describe which languages and scripts the font
overall supports. For example, a Traditional Chinese font that also contains
Latin characters, can indicate Hant,Latn, showing that it supports Hant, the
Traditional Chinese variant of the Hani script, and it also supports the Latn
script
The dlng structure is far more interesting. A font may contain various glyphs,
but only a particular subset of the glyphs may be truly &quot;leading&quot; in the design,
while other glyphs may have been included for technical reasons. Such a
Traditional Chinese font could only list Hant there, showing that it’s designed
for Traditional Chinese, but the font would omit Latn, because the developers
don’t think the font is really recommended for purely Latin-script use.
The tags used in the structures can comprise just script, or also language and
script. For example, if a font has Bulgarian Cyrillic alternates in the locl
feature for the cyrl BGR OT languagesystem, it could also indicate in dlng
explicitly that it supports bul-Cyrl. (Note that the scripts and languages in
meta use the ISO language and script codes, not the OpenType ones).
This check ensures that the font has the meta table containing the slng and dlng
structures.
All families in the Google Fonts collection should contain the &#x27;meta&#x27; table.
Windows 10 already uses it when deciding on which fonts to fall back to. The
Google Fonts API and also other environments could use the data for smarter
filtering. Most importantly, those entries should be added to the Noto fonts.
In the font making process, some environments store this data in external files
already. But the meta table provides a convenient way to store this inside the
font file, so some tools may add the data, and unrelated tools may read this
data. This makes the solution much more portable and universal.</pre>

* ⚠ **WARN** This font file does not have a 'meta' table. [code: lacks-meta-table]

</details>
<details>
<summary>⚠ <b>WARN:</b> Glyph names are all valid?</summary>

* [com.google.fonts/check/valid_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/valid_glyphnames)
<pre>--- Rationale ---
Microsoft&#x27;s recommendations for OpenType Fonts states the following:
&#x27;NOTE: The PostScript glyph name must be no longer than 31 characters, include
only uppercase or lowercase English letters, European digits, the period or the
underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter,
except the special glyph name &quot;.notdef&quot; which starts with a period.&#x27;
https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table
In practice, though, particularly in modern environments, glyph names can be as
long as 63 characters.
According to the &quot;Adobe Glyph List Specification&quot; available at:
https://github.com/adobe-type-tools/agl-specification</pre>

* ⚠ **WARN** The following glyph names may be too long for some legacy systems which may expect a maximum 31-char length limit:
numbersign_underscore_parenleft.liga, asterisk_asterisk_asterisk.liga.cv16, asciitilde_asciitilde_greater.liga, greater_greater_hyphen_middle.seq, greater_greater_hyphen_start.seq, greater_greater_equal_middle.seq, quadrantUpperLeftAndLowerLeftAndLowerRight, quadrantUpperLeftAndUpperRightAndLowerLeft, quadrantUpperLeftAndUpperRightAndLowerRight, quadrantUpperRightAndLowerLeftAndLowerRight and 4 more. [code: legacy-long-names]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check font contains no unreachable glyphs</summary>

* [com.google.fonts/check/unreachable_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unreachable_glyphs)
<pre>--- Rationale ---
Glyphs are either accessible directly through Unicode codepoints or through
substitution rules. Any glyphs not accessible by either of these means are
redundant and serve only to increase the font&#x27;s file size.</pre>

* ⚠ **WARN** The following glyphs could not be reached by codepoint or substitution rules:
 - numbersign_colon.liga_rem
 - at.spacer
 - acute.case.loclPLK
 - LIG
 - brevecy
 - space.frac
 - parenleft.spacer
 - null
 - braceright.spacer
 - caron.alt 
 - l.spacer
 [code: unreachable-glyphs]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking unitsPerEm value is reasonable.</summary>

* [com.google.fonts/check/unitsperem](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/head.html#com.google.fonts/check/unitsperem)
<pre>--- Rationale ---
According to the OpenType spec:
The value of unitsPerEm at the head table must be a value between 16 and 16384.
Any value in this range is valid.
In fonts that have TrueType outlines, a power of 2 is recommended as this allows
performance optimizations in some rasterizers.
But 1000 is a commonly used value. And 2000 may become increasingly more common
on Variable Fonts.</pre>

* ⚠ **WARN** In order to optimize performance on some legacy renderers, the value of unitsPerEm at the head table should idealy be a power of between 16 to 16384. And values of 1000 and 2000 are also common and may be just fine as well. But we got 1950 instead. [code: suboptimal]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/dsig](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/dsig.html#com.google.fonts/check/dsig)
<pre>--- Rationale ---
Microsoft Office 2013 and below products expect fonts to have a digital
signature declared in a DSIG table in order to implement OpenType features. The
EOL date for Microsoft Office 2013 products is 4/11/2023. This issue does not
impact Microsoft Office 2016 and above products.
As we approach the EOL date, it is now considered better to completely remove
the table.
But if you still want your font to support OpenType features on Office 2013,
then you may find it handy to add a fake signature on a dummy DSIG table by
running one of the helper scripts provided at
https://github.com/googlefonts/gftools
Reference: https://github.com/googlefonts/fontbakery/issues/1845</pre>

* ⚠ **WARN** This font has a digital signature (DSIG table) which is only required - even if only a dummy placeholder - on old programs like MS Office 2013 in order to work properly.
The current recommendation is to completely remove the DSIG table. [code: found-DSIG]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check mark characters are in GDEF mark glyph class.</summary>

* [com.google.fonts/check/gdef_mark_chars](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gdef.html#com.google.fonts/check/gdef_mark_chars)
<pre>--- Rationale ---
Mark characters should be in the GDEF mark glyph class.</pre>

* ⚠ **WARN** The following mark characters could be in the GDEF mark glyph class:
	 strokelongoverlay (U+0336) and strokeshortoverlay (U+0335) [code: mark-chars]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 6 | 13 | 52 | 9 | 140 | 0 |
| 0% | 3% | 6% | 24% | 4% | 64% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

## [QA.zip](https://github.com/google/fonts/files/7650636/QA.zip)

**Comment by RosaWagner** [comment]
@tonsky do you need more info or help to resolve the fontbakery fails ?

**Comment by tonsky** [comment]
There are a lot of issues, I think I’ll address them all in the next version https://github.com/tonsky/FiraCode/issues/1141

Feel free to close it for now, I can open new PR after fixing the issues

**Comment by RosaWagner** [comment]
Ok thanks!

**Pull request closed without merging**
