### PR TITLE
Geist Mono: Version 1.400 added



### LINKED ISSUE #6922: Add Geist & Geist Mono
https://github.com/vercel/geist-font

- [x] Geist #8246 
- [x] Geist Mono #8264

### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the upstream repo https://github.com/vercel/geist-font at commit https://github.com/vercel/geist-font/commit/1bd07b141c309bae59a982e2a43eea96ae4cbdde.
## PR Checklist:

- [x] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [x] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [x] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

Fixes #6922

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal This is the mono counterpart of Geist #8246

**Comment by emmamarichal** [comment]
Hi @vv-monsalve:

**Cyrillic**
I think cyrillic need some corrections for some glyphs:
- The descender is not well attached for these glyphs:
Screenshot 2024-10-04 at 15 38 13
- The bar could be better centered:
Screenshot 2024-10-04 at 15 41 15
- Alignement issue:
Screenshot 2024-10-04 at 15 34 17
Screenshot 2024-10-04 at 15 37 54

**Monospace issues**
Since it's a monospace, it creates weird results for some glyphs. I want to confirm if it's ok.
Screenshot 2024-10-04 at 15 47 24
Screenshot 2024-10-04 at 15 46 59

**Licence url**
We need to add back the check about the new URL. Here the licence field isn't in the source info, and the url is wrong. 
Screenshot 2024-10-04 at 15 48 13

**Small adjustments**
- Alignements could be improved a bit (but I'm ok to merge it like this)
Screenshot 2024-10-04 at 15 30 33

The comma could be centered with the T stem:
Screenshot 2024-10-04 at 15 32 34
Screenshot 2024-10-04 at 15 33 03

**Comment by vv-monsalve** [comment]
> **Monospace issues**
> Since it's a monospace, it creates weird results for some glyphs. I want to confirm if it's ok.

Could you please provide the string to replicate this?

**Comment by vv-monsalve** [comment]
I've created a PR to fix the essential ones (License, `Tcommaaccent`, `uhungarumlaut` and some outlines). Ive asked them to check on the Cyrillic ones. However, as said above, being a submitted font I'm ok with proceeding with them as they are now.

I'll update the PR when they have incorporated the changes and ping here when this one is updated.

**Comment by vv-monsalve** [comment]
Updated

**Comment by vv-monsalve** [comment]
@emmamarichal 

- Cyrillic issues
  I've reported this as a suggestion. However, this is a submitted font for which Latin Core is the base support requirement. This should not be considered a blocker.

- Ligatures issue
   The design team solved the ones that could be solved and marked as non-export the ones that were not working.
   They would look bad at the source level, indeed, given it's a monospaced font.

- > 🔥 FAIL Check there are no overlapping path segments
   
   The design team worked on the previously reported cases, but some new ones emerged. I tested the concerned glyphs on Chrome and Indesign, and there were no rendering issues. Also, Marc said about this check, "I think this check may already be redundant since Chrome 130 has fixed it." So I would not consider this a blocker.
   
- >   🔥 FAIL METADATA.pb: Designers are listed correctly on the Google Fonts catalog?

    The designer didn't want to include an image. I would not consider this as a blocker.

**Comment by emmamarichal** [comment]
Hi @vv-monsalve 

> Cyrillic issues
> I've reported this as a suggestion. However, this is a submitted font for which Latin Core is the base support requirement. This should not be considered a blocker.

Ah sorry, I'm just reading this. I made a comment on the other PR about some cyrillic issues. I'll merge it then!

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
