### PR TITLE
Josefin Slab: Version 2.100 added



### PR DESCRIPTION
**Pull request by emmamarichal**

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal note for this PR: Many fails remain because the idea was to quickly fix the kerning issues. Since there are UFOs, updating them would require a lot of work, so this PR only updates the kerning Dave marked as a priority for now.

**Comment by vv-monsalve** [comment]
@emmamarichal some kerning pairs still need to be improved, e.g. some combinations with lower case letters
Screenshot 2024-09-26 at 11 58 07

**Comment by emmamarichal** [comment]
Updated

**Comment by kenmcd** [comment]
These v2.100 variable fonts do not work in LibreOffice (or Word).
The 2.000 variable fonts from GF work fine.
 
These v2.100 variable fonts only appear as one font - and only at the Thin weight.
First time I tried I only got the Italic Thin.
So I re-installed v2.000 from GF and it works as expected.
Re-installed v2.100 VF fonts and this time only see the Roman Thin.
No other instances are available.
And Bold and Italic buttons yield fakes.

Windows Font Viewer clicks thru the five styles but only displays the Thin.
With the v2.000 VF fonts all the instances display properly.

The MainType font manager only displays the Thin instance for both the Roman and Italic v2.100 VF fonts.
With v2.000 VF fonts all five instances are listed for both the Roman and Italics fonts.

So my guess is something changed in the STAT table.

**Comment by vv-monsalve** [comment]
@emmamarichal the previos version indeed had a STAT table, and the new one lacks it. It would be a regression.

#### old

Screenshot 2024-09-27 at 18 26 34

#### new

Screenshot 2024-09-27 at 18 26 38

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
sorry @vv-monsalve, forgot to tag you on the update! it's ready to review!

**Comment by m4rc1e** [comment]
Previous font didn't kerning or the kerns have drastically changed

jose_kern


If we're happy with the new kerning then its LGTM. STAT is now back.

**Comment by emmamarichal** [comment]
@m4rc1e Yeah the kerning was the issue I was solving at the beggining! It's not perfect, but "less worst" let say hehe :)

**Comment by vv-monsalve** [comment]
@emmamarichal, as we discussed, I'm reporting the spotted pairs.

Screenshot 2024-11-01 at 10 41 11

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
@vv-monsalve Wait, the stat table seems to be gone again 😫 I'll let you know once it's fixed

**Comment by emmamarichal** [comment]
Updated

**Comment by emmamarichal** [comment]
@vv-monsalve ready! 👍

**Review by vv-monsalve — APPROVED** [review]

**Pull request merged**
