### PR TITLE
Noto Serif Khojki: Version 2.002 added

### PR DESCRIPTION
**Pull request by simoncozens**
01bac5c: [gftools-packager] Noto Serif Khojki: Version 2.002 added

* Noto Serif Khojki Version 2.002 taken from the upstream repo https://github.com/notofonts/khojki.git at commit https://github.com/notofonts/khojki/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens I merged this one but languages are also missing

**Comment by simoncozens** [comment]
I'll do a new PR.

**Comment by RosaWagner** [comment]
@simoncozens I think a subset definition may be missing

Capture d’écran 2022-10-26 à 12 03 14
Capture d’écran 2022-10-26 à 12 02 59
Capture d’écran 2022-10-26 à 12 02 40

**Comment by RosaWagner** [comment]
@simoncozens Subset is now in Sandbox, unfortunately there is an interpolation issue

https://user-images.githubusercontent.com/12222436/199469166-0fb4ae68-ef28-4266-8d45-30f8fec09c0a.mov

**Comment by simoncozens** [comment]
Good catch. I'll do a new release. (Fontbakery will catch these once we get the check merged.)

**Pull request merged**
