### PR TITLE
Hotfix: update roboto mono isFixedPitch flag to true

### PR DESCRIPTION
**Pull request by thundernixon**
Fixes Issue #225 by setting `isFixedPitch` from `0` to `1`.

Uses [this shell script](https://gist.github.com/thundernixon/583dbfaf018bde2c118352e162103375) to TTX files, update the value, and TTX them back.

### CODE REVIEW

**Comment by thundernixon** [comment]
We should probably also update the sources, but I am having trouble finding them on GitHub. @davelab6, do you know where I could find them?

**Comment by m4rc1e** [comment]
You haven't bumped the version number.

**Comment by m4rc1e** [comment]
I suspect the previous version number was meant to be v2.001. This looks like a rounding issue to me. I'd Just bump your fonts to 2.002 for both the head fontRevision and nametable entry.

cc @anthrotype

**Comment by thundernixon** [comment]
Okay, thanks @m4rc1e! I've bumped the version to `2.002` in both spots, and set the `isFixedPitch` to `1`.

I upgraded the shell script in a few ways, such as automatically checking and reporting that the changes were made: https://gist.github.com/thundernixon/583dbfaf018bde2c118352e162103375

**Comment by thundernixon** [comment]
During today's meeting, the question was asked whether the `isFixedPitch` issue would be caught by FontBakery today. Yes, it's part of [Check 33](https://github.com/googlefonts/fontbakery/blob/007eaad107eb36f91ff52e1bad378691c0ffe647/Lib/fontbakery/specifications/name.py#L138).

However, checking into this led me to find several FontBakery `FAIL`s that seem problematic (including in another part of Check 33, covering Panose values).

# Roboto Mono Regular - Fontbakery fails

<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 2163, but got 1946 instead [code: ascent]
* :fire: **FAIL** OS/2.usWinDescent value should be equal or greater than 555, but got 512 instead [code: descent]
</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/042](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/042)
* :fire: **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking correctness of monospaced metadata.</summary>

* [com.google.fonts/check/033](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/033)
* :fire: **FAIL** On monospaced fonts, the value of OS/2.panose.bProportion must be set to 9 (proportion: monospaced), but got 0 instead. [code: mono-bad-panose-proportion]
* :warning: **WARN** Font is monospaced but 34 glyphs (3.266090297790586%) have a different width. You should check the widths of: ['hyphen', 'f', 'gravecomb', 'acutecomb', 'tildecomb', 'hook', 'uni030F', 'dotbelow', 'uni0483', 'uni0484', 'uni0485', 'uni0486', 'uni0488', 'uni0489', 'at.alt', 'uni00AD', 'Dcroat', 'Eth', 'hbar', 'dcaron', 'lcaron', 'ldot', 'tcaron', 'Epsilontonos', 'Etatonos', 'Iotatonos', 'Omicrontonos', 'Upsilontonos', 'Omegatonos', 'exclamdbl', 'dcroat', 'uni20AB', 'uni049E', 'uni049F'] [code: mono-outliers]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/045](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/045)
* :fire: **FAIL** This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly.

</details>
</br>

The most obvious problem for a monospace is that some glyphs are not the standard width – a few are around 8% wider than they should be:

image

image

# Roboto Mono Italic
<details>
<summary>:fire: <b>FAIL:</b> Checking post.italicAngle value.</summary>

* [com.google.fonts/check/130](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/130)
* :fire: **FAIL** Font is italic, so post.italicAngle should be non-zero. [code: zero-italic]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 usWinAscent & usWinDescent.</summary>

* [com.google.fonts/check/040](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/040)
* :fire: **FAIL** OS/2.usWinAscent value should be equal or greater than 2163, but got 1946 instead [code: ascent]
* :fire: **FAIL** OS/2.usWinDescent value should be equal or greater than 555, but got 512 instead [code: descent]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking OS/2 Metrics match hhea Metrics.</summary>

* [com.google.fonts/check/042](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/042)
* :fire: **FAIL** OS/2 sTypoAscender and hhea ascent must be equal. [code: ascender]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Checking correctness of monospaced metadata.</summary>

* [com.google.fonts/check/033](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/033)
* :fire: **FAIL** On monospaced fonts, the value of OS/2.panose.bProportion must be set to 9 (proportion: monospaced), but got 0 instead. [code: mono-bad-panose-proportion]
* :warning: **WARN** Font is monospaced but 35 glyphs (3.3621517771373677%) have a different width. You should check the widths of: ['hyphen', 'f', 'gravecomb', 'acutecomb', 'tildecomb', 'hook', 'uni030F', 'dotbelow', 'uni0483', 'uni0484', 'uni0485', 'uni0486', 'uni0488', 'uni0489', 'uniFFFD', 'at.alt', 'uni00AD', 'Dcroat', 'Eth', 'hbar', 'dcaron', 'lcaron', 'ldot', 'tcaron', 'Epsilontonos', 'Etatonos', 'Iotatonos', 'Omicrontonos', 'Upsilontonos', 'Omegatonos', 'exclamdbl', 'dcroat', 'uni20AB', 'uni049E', 'uni049F'] [code: mono-outliers]

</details>
<details>
<summary>:fire: <b>FAIL:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/045](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/045)
* :fire: **FAIL** This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly.

</details>
</br>

In the Italic, quite a few of the glyphs mentioned (e.g. `/hyphen` are off by just 1 unit (1203 vs the standard 1202). However, quite a few are off by significantly more, which probably isn't killing anyone, but isn't ideal:

image

image

Of course, the _most significant_ problem here is that the standard width in the regular is 1229, but the standard width in the italic is 1202. This is about 2.25% different. Here's [a codepen test](https://codepen.io/thundernixon/pen/gqPoKE) showing the effect this has over a line of text:

image
image

There are also issues around vertical metrics which probably make display inconsistent between platforms.

@davelab6  Should I file each of these as separate issues, all of them as one big issue, or work on fixing them in this PR? If it's a priority to fix them ASAP, is there an available upstream repo? So far, I haven't been able to find the source repo.

image

**Comment by davelab6** [comment]
I suggest to focus on quickly resolving issues users care about. If the
fixed pitch flag and panose flag actually fixes a user issue, it's a half
day job to do all the extra stuff around fontbakery meta checking too.

Recreation of sources, respacing and even redrawing a bunch of off-mono
glyphs, respacing the entire italic.... These are not a half day job. And
they will introduce visible changes to all web users. If we are going to do
that, we should allocate a month to comfortably fix everything that is
wrong.

Instead: What can do you do with each half day that has the highest impact?
If you fix 2 families a day, it will still take months to get through the
known issues...

So... It's good to file an issue noting stuff that's smelling bad, that you
are putting out of scope for fixing, during that half day.

**Comment by thundernixon** [comment]
I've created issue #1832 to encapsulate remaining metric issues in Roboto Mono which would make sense to fix at the same time. In that issue, one person has noted that even with the `isFixedPitch` flag set to true, Roboto Mono still isn't available for use in the Windows console.

**Comment by thundernixon** [comment]
@davelab6 this hotfix is complete. Should I merge it, or should I let you or Marc?

**Comment by davelab6** [comment]
I'll merge it when it's closer to being shipped in the API

**Comment by thundernixon** [comment]
Okay, thanks for clarifying! Just wanted to be sure I wasn't leaving any open loops.

**Comment by musm** [comment]
@davelab6  is it appropriate to merge now?

**Comment by shana** [comment]
Any ETA on when this PR will be merged?

**Comment by chiniara** [comment]
Would love to use roboto mono on my windows terminals. Any updates?

**Comment by SidShetye** [comment]
Where can the font (with this fix) be downloaded from?

**Comment by arrowtype** [comment]
In response to @SidShetye, the files are at https://github.com/thundernixon/fonts/tree/5338537ef835a3d9ccf8faf386399f13a30605e2/apache/robotomono

**Pull request merged**
