### PR TITLE
Inclusive Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.30] added

### PR DESCRIPTION
**Pull request by emmamarichal**
2f2040f: [gftools-packager] Inclusive Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.30] added

* Inclusive Sans Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.30] taken from the upstream repo https://github.com/LivKing/Inclusive-Sans at commit https://github.com/LivKing/Inclusive-Sans/commit/77fbedf8918eacb3faf7e69097c194419c4688b6.

 c13f643: Description added

To do:
- add designer profile
- tweet

### CODE REVIEW

**Comment by RosaWagner** [comment]
I saw several issues so I decided to take a deeper look:

- The `IJ` `ij` glyphs have accents, they should not have accents.
- Capital `Eszett` has a weird design (they could follow this article: https://www.lucasfonts.com/learn/1E9E)
- `loclMAH` is there to give the option to have a proper cedilla instead of a commabelow (otherwise they could just use the non localised L and N with comma below), cf https://forum.glyphsapp.com/t/best-way-to-handle-marshallese-locl-glyphs/10863
- They may want to look at this article about `ogonek`: http://www.twardoch.com/download/polishhowto/ogonek.html
- `AE` `ae` `OE` `oe` digraphs -> each letter should have balanced/equal proportion
- `periodcentered.loclCAT.case` should be centered between the 2 L (as if there were no space), and is a bit low. Better to handle it with negative spacing than with kerning (cause some app don't display kerning by default)
- Stylistic sets only have the base glyphs and not the accented ones
- Bar of `dcroat` and `hbar` should be a bit longer (almost to the middle of the letter), but only a small part outside the stem. Currently the bar of `hbar` is in the middle of the stem.
- Bar of `eth` should be longer and less vertical
- `commaaccent` should have a similar shape to the actual `comma` and not a reversed acute (they should not be confused)
- `Quotedbl` and `Quotesingle` are supposed to be straight
- `Quoteleft` and `Quotedblleft` are in the wrong direction
- `registered` is often designed as a superscript
- `macron` looks a tiny tiny bit too large (compared to the width of dieresis and tilda), especially on lowercases.
- `tilda` could be confused with macron at small sizes, maybe it could be more curvy to avoid that
- there is no `bottom` anchors in lowercases which leads to weird composites positioning such as in `scommaaccent`
- positioning and size of accents could be more consistent in a general way

Capture d’écran 2023-06-13 à 11 43 13

Capture d’écran 2023-06-13 à 11 42 15

Capture d’écran 2023-06-13 à 11 46 54

Capture d’écran 2023-06-13 à 11 52 42

Capture d’écran 2023-06-13 à 12 34 21

**Comment by emmamarichal** [comment]
@RosaWagner ok thanks, I'll write to the designer

**Comment by emmamarichal** [comment]
Updated

## Inclusive Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.32] added

---
 2c9ec4b: [gftools-packager] Inclusive Sans: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.32] added

* Inclusive Sans Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.32] taken from the upstream repo https://github.com/LivKing/Inclusive-Sans at commit https://github.com/LivKing/Inclusive-Sans/commit/9372a181bb299bf48b251bfeb821015b0572e0dc.

 d5ee0ef: Description

**Comment by emmamarichal** [comment]
@RosaWagner updated!

**Comment by RosaWagner** [comment]
Sorry I didn't report kerning issues before

Screenshot 2023-06-30 at 13 07 11

**Pull request merged**
