### PR TITLE
Englebert: hotfixed v-metrics

### PR DESCRIPTION
**Pull request by emmamarichal**
### v1.000 ➡️ v1.010

Updated:
- name table
- hhea table
- OS/2 table
- head table

See: https://github.com/google/fonts/issues/8679

@davelab6 

Screenshot 2024-12-04 at 10 38 44
Screenshot 2024-12-04 at 10 38 52

[complete-qa.zip](https://github.com/user-attachments/files/18005773/complete-qa.zip)

### CODE REVIEW

**Review by davelab6 — APPROVED** [review]
Image shows what I expect :) I didn't review closer.

**Comment by emmamarichal** [comment]
thanks @davelab6! :)
@vv-monsalve do you have the time today to take a look?

**Comment by vv-monsalve** [comment]
HI @emmamarichal, I just had the opportunity to check this today.

The new vertical metrics values LGTM.

> "copyright (c) 2012, brian j. bonislawsky dba astigmatic (aoeti) ([astigma@astigmatic.com](mailto:astigma@astigmatic.com)), with reserved font name 'englebert'"

Other than that I wonder if now it could be a good time to update the copyright and delete the RFN.

**Comment by emmamarichal** [comment]
@vv-monsalve updated! :)

**Comment by vv-monsalve** [comment]
I would need to be updated also in the font. I think fix_nameids would do it.

**Comment by emmamarichal** [comment]
thank you @vv-monsalve, I'll do this asap! :)

**Comment by emmamarichal** [comment]
@vv-monsalve fixed!

**Pull request merged**
