### PR TITLE
Add `primary_language` field to Chinese fonts; Add languages to new Chinese fonts;

### PR DESCRIPTION
**Pull request by laubonghaudoi**
Current Traditional Chinese fonts don't have a primary language setting in their meta data, resulting in the default sample text to be in `wuu_Hant` which has the highest population. This PR specifies the `primary_language` fields of them. 

The PR also adds the Chinese languages to the metadata of new Chinese fonts.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
@simoncozens Mind reviewing this PR when you have an opportunity?

**Comment by chrissimpkins** [comment]
cc @nathan-williams re: incoming changes to front end specimens

**Review by davelab6 — APPROVED** [review]

**Comment by simoncozens** [comment]
The problem here is that fontbakery's version of the protobuf headers doesn't have a `primary_language` field, so it's not being parsed correctly there. I'll fix in fontbakery and try again.

**Review by nathan-williams — COMMENTED** [review]
We should not specify languages explicitly in the METADATA.pb files. We currently do so, but only for Noto families. Please remove any specification of `languages` in the textprotos for non-Noto families.

Otherwise, PR looks good. Thanks again for the contribution!

**Review by nathan-williams — CHANGES_REQUESTED** [review]
See [earlier comment](https://github.com/google/fonts/pull/7792#pullrequestreview-2094248810).

**Comment by laubonghaudoi** [comment]
I see. But if I remove all `languages` in the non-Noto families, how to specify the default displayed sample text for them? Currently they are all showing Shanghainese texts by default which is what this PR is trying to fix.

**Comment by laubonghaudoi** [comment]
I just updated the PR and removed the `languages` and `primary_language` for all non-Noto fonts. I see that https://github.com/fonttools/fontbakery/pull/4756 is working in progress, IIUC I should make another PR to add the languages back once that PR is merged and rolled out, so that the default display language issue can be fixed. Is this correct?

**Review by nathan-williams — APPROVED** [review]
The current set of changes looks good!

You can actually restore some of the reverted changes, though. Specifying `primary_language` for non-Noto families is fine – just not `languages`.

**Comment by laubonghaudoi** [comment]
Okay done, thanks for letting me know!

**Pull request merged**
