### PR TITLE
Gayathri: Version 1.000 added

### PR DESCRIPTION
**Pull request by graphicore**
* Gayathri Version 1.000 taken from the upstream repo https://github.com/smc/Gayathri.git at commit https://github.com/smc/Gayathri/commit/ae7a4ea30ca950798c06bdd6f488fd2c4faf1f4d.

### CODE REVIEW

**Comment by graphicore** [comment]
**CAUTION** same disclaimer as in [Manjari PR#2572](https://github.com/google/fonts/pull/2572#issuecomment-663273018) I used a `gftools packager` that builds from source, needs resolution.

**Comment by vv-monsalve** [comment]
This project is already included in [GF](https://fonts.google.com/specimen/Gayathri?query=Gayathri#standard-styles) with the same version that the current source file has: 1.000

**Comment by vv-monsalve** [comment]
Updated

## Gayathri: Version 1.110 added

---
 d7f0441: [gftools-packager] Gayathri: Version 1.110 added

* Gayathri Version 1.110 taken from the upstream repo https://gitlab.com/smc/fonts/gayathri.git at commit 74544b1d2e6619a872710be05fde7bc309e3e162.

 e059325: [gftools-packager] ofl/gayathri remove METADATA "source".  google/fonts#2587

**Comment by vv-monsalve** [comment]
@googlebot I consent

**Pull request closed without merging**
