### PR TITLE
Rubik Scribble: Version 2.103 added

### LINKED ISSUE #3725: Add Rubik Scribble
upstream: https://github.com/NaN-xyz/Rubik-Filtered

- [ ] Build
- [ ] QA
- [ ] PR Upstream
- [ ] Package

### PR DESCRIPTION
**Pull request by RosaWagner**
baa3737: [gftools-packager] Rubik Scribble: Version 2.103 added

* Rubik Scribble Version 2.103 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/c70421b2f209e0aa88a84210d94da557602a5e56.

Closes #3725

### CODE REVIEW

**Comment by RosaWagner** [comment]
Updated

## Rubik Scribble: Version 2.201 added

---
 91209d6: [gftools-packager] Rubik Scribble: Version 2.201 added

* Rubik Scribble Version 2.201 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/6555502a8b48b1aa3b8c773d34a871a9fb84a2b8.

**Comment by emmamarichal** [comment]
@RosaWagner There are overlaps that I'm not sure can be left as they are. There's also a counter-shape in the ringcomb that shouldn't be black, I think:

Capture d’écran 2023-11-23 à 14 44 56
Capture d’écran 2023-11-23 à 14 46 12
Capture d’écran 2023-11-23 à 14 46 18
Capture d’écran 2023-11-23 à 14 49 55
Capture d’écran 2023-11-23 à 14 55 01

**Comment by RosaWagner** [comment]
Updated

## Rubik Scribble: Version 2.201 added

---
 7a6fbec: [gftools-packager] Rubik Scribble: Version 2.201 added

* Rubik Scribble Version 2.201 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/bad54a1074926c9b2b0111db2bed0b65393f4426.

**Comment by RosaWagner** [comment]
@emmamarichal thanks, I fixed the `u ring`, the rest you can ignore

**Comment by eliheuer** [comment]
I changed the title of this PR to reflect the version number in sandbox (2.201 )

**Pull request merged**
