### PR TITLE
alegreyasc: v2.001 added

### PR DESCRIPTION
**Pull request by m4rc1e**
This SC family is related to the previous Alegreya pr, #1207

Both families are generated from the same upstream repo, https://github.com/huertatipografica/Alegreya

### CODE REVIEW

**Comment by m4rc1e** [comment]
Keep this open. The fi ligature is still for the lowercase

screen shot 2017-09-18 at 16 02 12

@juandelperal guessing the latest ttfs may not be in sync with the sources.

**Comment by juandelperal** [comment]
Thanks Marc! 
I added a v2.002 removing that and others unneeded glyphs from the sc family.
I hope now we can go live.
Thanks

**Comment by juandelperal** [comment]
now will check similar issues in Alegreya Sans

**Comment by m4rc1e** [comment]
@juandelperal thanks, I'll throw this on the todo for next week.

**Comment by m4rc1e** [comment]
@juandelperal Please regen the fonts in the repo. Issue still persists.

screen shot 2017-09-25 at 14 51 05

**Comment by juandelperal** [comment]
Thanks Marc, could yo please share the link of gf regression?
That's strange: the new fonts doesn't have fi, fl.


2017-09-25 10:52 GMT-03:00 Marc Foley <notifications@github.com>:

**Comment by m4rc1e** [comment]
> That's strange: the new fonts doesn't have fi, fl.

That's the problem. We must have these glyphs. They should have capitalised forms in them 'FL' and 'FI' what you're seeing is a fallback font.

I'll email you the gf regression link.

**Comment by juandelperal** [comment]
Ah! sorry, I misunderstood the issue.
Will fix and get back to you.


2017-09-25 11:11 GMT-03:00 Marc Foley <notifications@github.com>:

**Comment by davelab6** [comment]
I believe this needs to be fixed in an upcoming 2.003 (which isn't on https://github.com/huertatipografica/Alegreya/releases yet) 

@juandelperal please confirm :)

**Comment by m4rc1e** [comment]
Closing this since 2.003 now exists

**Pull request closed without merging**
