### PR TITLE
fix metadata.json for stalinone font

### PR DESCRIPTION
**Pull request by sapics**
this is just a correction.

### CODE REVIEW

**Comment by davelab6** [comment]
Brilliant, thanks! Have you agreed to the Google CLA? https://cla.developers.google.com/about/google-individual

**Comment by sapics** [comment]
Thank you so much for posting this to Github!
This project helps me a lot!

I am sorry, i did not know about the Google CLA.
Now, i make a submit for agreement.

**Comment by davelab6** [comment]
You might find https://github.com/googlefonts/fontbakery helpful :)

**Comment by sapics** [comment]
Thank you for letting me know! :)

**Pull request merged**
