### PR TITLE
ofl/exo2: v1.002 added. Updated from source.

### PR DESCRIPTION
**Pull request by laerm0**
Files are updated from source, which had issues #1151 and #1153 already fixed.

### CODE REVIEW

**Comment by laerm0** [comment]
I signed it!

**Comment by davelab6** [comment]
Keeping this open until we have before/after screenshots :)

**Comment by m4rc1e** [comment]
## Bug fix
desktop_os_x_el_capitan_safari_9 1_


#1151 and #1153 are solved. However, there's a new problem. [Uni0419](http://www.fileformat.info/info/unicode/char/0419/index.htm) is missing its breve accent.

We need to fix this.

screen shot 2017-11-17 at 11 05 53

---

## Rendering

In the smaller sizes, the hinting has improved

Win 7 Chrome 50
**before**
screen shot 2017-11-17 at 10 53 01

**after**
screen shot 2017-11-17 at 10 54 00
Since there are so many weights, here's just the masters in a waterfall.

**Win 7 Chrome 50**
desktop_windows_7_chrome_50 0_

We are getting some x-height jumps in sizes 11pt and 14pt.

We need to fix the x-height jumps and the uni0419 before we can merge this.

@davelab6, For each new pr, I'll be attaching a zip of all the renders.

[1259_exo2_img_core.zip](https://github.com/google/fonts/files/1482056/1259_exo2_img_core.zip)

**Comment by m4rc1e** [comment]
Closing. https://github.com/google/fonts/pull/2126 is newer.

**Pull request closed without merging**
