### PR TITLE
josefinsans: v2.000 added.

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from the upstream repo https://github.com/googlefonts/josefinsans at commit https://github.com/googlefonts/josefinsans/commit/132fdfd997a62411375d15e20ef81285923750c6

### CODE REVIEW

**Comment by thlinard** [comment]
@m4rc1e : JosefinSans-Italic.ttf and JosefinSans-SemiBoldItalic.ttf are missing in the static files.

**Comment by m4rc1e** [comment]
Thanks, I'll push an update once I've seen why all the statics are not generating.

**Comment by m4rc1e** [comment]
Issue posted upstream, I'll see what they say,

**Comment by davelab6** [comment]
Thanks @m4rc1e - took a quick look at the qa.zip images, and

`qa/Diffbrowsers/LightItalic_Regular_SemiBold_SemiBoldItalic/waterfall/before/Desktop_Windows_10_firefox_62.0_.jpg`
`qa/Diffbrowsers/LightItalic_Regular_SemiBold_SemiBoldItalic/waterfall/after/Desktop_Windows_10_firefox_62.0_.jpg`

look like there are changes to v metrics apparent on Windows due what I guess is a switch from ttfautohinit to non-hinting - but the changes make the resulting pixel rendering truer to the design, and more even both in x height across glyphs, and stem thicknesses, so I approve this PR as a "C" grade change, "Shapes & metrics change but not in a way anticipated to cause major issues (e.g. not significantly wider)" :)

Screen Shot 2019-12-02 at 11 06 41 PM
Screen Shot 2019-12-02 at 11 07 11 PM
Screen Shot 2019-12-02 at 11 07 50 PM

**Pull request merged**
