### PR TITLE
Update ruslandisplay/METADATA & DESC for proper attribution

### LINKED ISSUE #6740: Plagiarism allegations for Ruslan Display
Twitter user [Tanita26086361](https://twitter.com/Tanita26086361) has flagged Google Fonts in a [retweet](https://twitter.com/Tanita26086361/status/1704399732943048911) of user [viterzbayraku](https://twitter.com/viterzbayraku), saying that Google Fonts’ [Ruslan Display](https://fonts.google.com/specimen/Ruslan+Display?query=ruslan) typeface originates from Ukrainian designer Oleg Snarskii and has been plagiarized by Russian designer Denis Masharov.

Masharov’s claim in the font’s description that Ruslan is derived from a _poluustav_ lettering style can only be remotely supported by a quick [image search](https://www.google.com/search?sca_esv=566929587&sxsrf=AM9HkKmgO-1WbfpGlTcNiu9-f1B3kMdCeA:1695216429777&q=poluustav&tbm=isch&source=lnms&sa=X&ved=2ahUKEwiTxvSopbmBAxUQ_rsIHWlJAaQQ0pQJegQICxAB&biw=2236&bih=1418&dpr=2). 

Instead, the typeface’s origin in Ukraine is apparent from photos of the [Teremky metro station](https://www.google.com/search?sca_esv=566929587&sxsrf=AM9HkKnZJ0iE_bsOyxjXtKhTMO8guMDglA:1695216601406&q=Teremky+metro+station&tbm=isch&source=lnms&sa=X&ved=2ahUKEwjc9N_6pbmBAxWi1QIHHXJRCdwQ0pQJegQICBAB&biw=2236&bih=1418&dpr=2#imgrc=Khveqv0oYMFoWM).

Can we find any printed evidence that confirms Snarskii as the design’s author? If so, I propose to re-release Ruslan under a different name and correct crediting of the authors (which probably must still include Masharov as a secondary author as having drawn the outlines).

### PR DESCRIPTION
**Pull request by davelab6**
Fixes #6740

### CODE REVIEW

**Comment by RosaWagner** [comment]
These 2 fails must be resolved to be able to be pushed to sandbox:

🔥 FAIL: Checking file is named canonically. ([com.google.fonts/check/canonical_filename](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/canonical_filename))
🔥 FAIL Expected "RuslanDisplay-Regular.ttf. Got RuslanDisplay.ttf. [code: bad-filename]

🔥 FAIL: METADATA.pb subsets should be alphabetically ordered. ([com.google.fonts/check/metadata/subsets_order](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/subsets_order))
🔥 FAIL METADATA.pb subsets are not sorted in alphabetical order: Got ['menu', 'cyrillic', 'latin', 'latin-ext'] and expected ['cyrillic', 'latin', 'latin-ext', 'menu'] [code: not-sorted]

**Comment by RosaWagner** [comment]
These 2 fails can easily be hotfixed:

🔥 FAIL: Description strings in the name table must not contain copyright info. ([com.google.fonts/check/name/no_copyright_on_description](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/name.html#com.google.fonts/check/name/no_copyright_on_description))

🔥 FAIL: Are there unwanted tables? ([com.google.fonts/check/unwanted_tables](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/unwanted_tables))
🔥 FAIL The following unwanted font tables were found:

FFTM - Table contains redundant FontForge timestamp info

They can be removed with the 'fix-unwanted-tables' script provided by gftools. [code: unwanted-tables]
🔥 FAIL Some namerecords with ID=10 (NameID.DESCRIPTION) containing copyright info should be removed (perhaps these were added by a longstanding FontLab Studio 5.x bug that copied copyright notices to them.) [code: copyright-on-description]

**Comment by davelab6** [comment]
> These 2 fails must be resolved to be able to be pushed to sandbox:

Since the file isn't changing, and it is important to correct the attribution, I am kindly declining to change the font files.

**Comment by thlinard** [comment]
> > These 2 fails must be resolved to be able to be pushed to sandbox:
> 
> Since the file isn't changing, and it is important to correct the attribution, I am kindly declining to change the font files as a blocker on pushing these changes; its good for @yanone to fix the font, but it must not block these changes.

Maybe then it would be desirable to hotfix the font so that the metadata of the font file matches what will be said in METADATA & DESC?

**Comment by davelab6** [comment]
I don't want to wait.

**Comment by RosaWagner** [comment]
The eng team won’t be able to push if we don’t fix these 2 metadata issue, it literally will block the push. It takes 2 minutes to add « Regular » to the file name, and 2 more to put the subsets in the alphabetical order. The font would be on the list already if you had asked for a review before merging.

**Comment by davelab6** [comment]
I'm confused; the changes are already on sandbox, and look good, so I've added to `to_production` :)

**Comment by RosaWagner** [comment]
Then I am confused because these kind of issues already blocked a push in the past, requiring the eng team to fix it to be able to continue.

**Pull request merged**
