### PR TITLE
Yuji hentaigana fonts

### PR DESCRIPTION
**Pull request by aaronbell**
Includes the two Yuji Hentaigana fonts (split from https://github.com/google/fonts/pull/3521 PR).

### CODE REVIEW

**Comment by m4rc1e** [comment]
We will need to look into why the OFL check is failing. It looks fine to me.

**Comment by aaronbell** [comment]
Rosalie mentioned yesterday on another thread that the OFL formatting has changed with UFR, so that might be why these files (which had been set up some months ago) appear to be failing the check.

**Comment by RosaWagner** [comment]
@aaronbell  So we need to add the japanese subset in metadata, and you you suggested we will follow the same process as kana-only families

**Comment by davelab6** [comment]
Kana only fonts still get the japanese subset flag in METADATA, but are held in sandbox.

(The gftools METADATA generator will only add subset flags to METADATA when the fonts have a high % coverage of the full subset char set; kana is a tiny fraction of the kana+kanji total so typically won't be added)

**Comment by aaronbell** [comment]
Thanks! I've submitted a PR to update the METADATA for these two fonts:
https://github.com/google/fonts/pull/3822

**Pull request merged**
