### PR TITLE
Handjet: Version 2.003 added

### PR DESCRIPTION
**Pull request by RosaWagner**
2bc5a95: [gftools-packager] Handjet: Version 2.003 added

* Handjet Version 2.003 taken from the upstream repo https://github.com/rosettatype/handjet at commit https://github.com/rosettatype/handjet/commit/3918b7798e06c81da6bc558e88dfddd5a6b49807.

### CODE REVIEW

**Comment by RosaWagner** [comment]
Preview on Mac (whatever the browser) is still a bit disastrous compared to Windows.

Chrome Mac
Capture d’écran 2022-10-07 à 11 52 07


Edge Windows
Capture d’écran 2022-10-07 à 11 51 58

I would push it to sandbox to test the axes though.

**Comment by kontur** [comment]
🥳

**Comment by RosaWagner** [comment]
It not live yet, but we can see it in dev-sandbox with the custom axes ;)

**Comment by chrissimpkins** [comment]
This is no longer blocked.  Ready for sandbox.

**Comment by chrissimpkins** [comment]
Added to to_sandbox list in https://github.com/google/fonts/pull/5658

**Pull request merged**
