### PR TITLE
ofl/tuffy: v 1.272 added. Fixes ots failure.

### PR DESCRIPTION
**Pull request by laerm0**
ttx round trip and ttfautohinted, version number increased.

### CODE REVIEW

**Comment by laerm0** [comment]
I SIGNED IT

**Comment by davelab6** [comment]
Thanks @laerm0 :)

**Comment by davelab6** [comment]
@m4rc1e Sadly these all fail OTS so I think they can't be launched. 

```sh
$ echo "ArchivoVFBeta-Italic.ttf "; ots-sanitize ofl/archivovfbeta/ArchivoVFBeta-Italic.ttf;
echo "ArchivoVFBeta.tttf";  ots-sanitize ofl/archivovfbeta/ArchivoVFBeta.ttf ;
echo "AsapVFBeta-Condensed.ttf "; ots-sanitize ofl/asapvfbeta/AsapVFBeta-Condensed.ttf;
echo "AsapVFBeta-Italic.ttf "; ots-sanitize ofl/asapvfbeta/AsapVFBeta-Italic.ttf;
echo "AsapVFBeta.tttf";  ots-sanitize ofl/asapvfbeta/AsapVFBeta.ttf ;
echo "CabinVFBeta-Italic.ttf "; ots-sanitize ofl/cabinvfbeta/CabinVFBeta-Italic.ttf;
echo "CabinVFBeta.tttf";  ots-sanitize ofl/cabinvfbeta/CabinVFBeta.ttf ;
echo "FaustinaVFBeta-Italic.ttf "; ots-sanitize ofl/faustinavfbeta/FaustinaVFBeta-Italic.ttf;
echo "FaustinaVFBeta.tttf";  ots-sanitize ofl/faustinavfbeta/FaustinaVFBeta.ttf ;
echo "MavenProVFBeta.tttf";  ots-sanitize ofl/mavenprovfbeta/MavenProVFBeta.ttf ;
echo "PodkovaVFBeta.tttf";  ots-sanitize ofl/podkovavfbeta/PodkovaVFBeta.ttf ;

ArchivoVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
ArchivoVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta-Condensed.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 2
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in anchor table
ERROR: GPOS: Faled to parse anchor table for mark table 0
ERROR: GPOS: Failed to parse mark array
ERROR: Layout: Failed to parse lookup subtable 3
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
AsapVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in anchor table
ERROR: GPOS: Faled to parse anchor table for mark table 0
ERROR: GPOS: Failed to parse mark array
ERROR: Layout: Failed to parse lookup subtable 3
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 1
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
CabinVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
CabinVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse lookup from extension lookup
ERROR: Layout: Failed to parse lookup subtable 8
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
FaustinaVFBeta-Italic.ttf 
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
FaustinaVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
MavenProVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
Failed to sanitize file!
PodkovaVFBeta.tttf
ERROR: Layout: bad delta format: 32768
ERROR: GPOS: Failed to parse device table in value record
ERROR: GPOS: Failed to parse value record in format 1 pair set table
ERROR: GPOS: Failed to parse pair set table 0
ERROR: GPOS: Failed to parse pair pos format 1
ERROR: Layout: Failed to parse lookup subtable 1
ERROR: Layout: Failed to parse subtable 0
ERROR: Layout: Failed to parse lookup 0
ERROR: GPOS: Failed to parse lookup list table
ERROR: GPOS: Failed to parse table
$
```

**Comment by davelab6** [comment]
oops wrong page

**Pull request merged**
