### PR TITLE
Aboreto: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by emmamarichal**
781101f: [gftools-packager] Aboreto: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

* Aboreto Version 1.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/domija/Aboreto at commit https://github.com/domija/Aboreto/commit/1423a732a34d080e360e8771ae9aca3de47ced31.

### CODE REVIEW

**Comment by RosaWagner** [comment]
I am so happy we have now this vertical metric check because indeed, they are problematic.

🔥 FAIL: Check font follows the Google Fonts vertical metric schema ([com.google.fonts/check/vertical_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics))

The caps should be at least centred. The font doesn't have MUCH descenders, so if the designer wants to keep the same line spacing, then some space of the typoAscender height should be given to the typoAscender value. 

Capture d’écran 2022-06-24 à 12 15 49

But I would largely recommend to cover at least an accent, and increase the linespacing to avoid this kind of clash:

Capture d’écran 2022-06-24 à 12 20 44

**Comment by emmamarichal** [comment]
@RosaWagner Ah yes I saw the fail, I was hesitating to correct that because it was a full caps typeface precisely. 
I can correct that and make a proposal to the designer!

**Comment by emmamarichal** [comment]
Updated

## Aboreto: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

---
 9c17659: [gftools-packager] Aboreto: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

* Aboreto Version 1.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/domija/Aboreto at commit https://github.com/domija/Aboreto/commit/07795db7fb5cf9029f1bac1ae0b130bbae6c5feb.

**Comment by vv-monsalve** [comment]
Hi @RosaWagner and @emmamarichal 

It seems that I never hit the "comment" button yesterday. I was commenting this:

> 🔥 FAIL: Check font follows the Google Fonts vertical metric schema ([com.google.fonts/check/vertical_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vertical_metrics))
🔥 FAIL The sum of hhea.ascender+abs(hhea.descender)+hhea.lineGap is 1160 when it should be at least 1200 [code: bad-hhea-range]


Both the Fail and the line height issue remain in the font. Even though it's an all-caps font, the idea would be to not have visual clutter or near-colliding shapes (letters, accents) when composing with the default line spacing.

Screen Shot 2022-06-30 at 13 38 40

**Comment by RosaWagner** [comment]
A compromise has been made here with the designer in that particular case, in the sense that it is easier to add line height than to remove some when it comes to layout on web pages. Since it is the intention of the designer to allow very tight linespacing, we proposed a compromise that avoid super big clashes.

**Pull request merged**
