### PR TITLE
Noto Sans: Version 2.013 added

### PR DESCRIPTION
**Pull request by simoncozens**
62c17bc: [gftools-packager] Noto Sans: Version 2.013 added

* Noto Sans Version 2.013 taken from the upstream repo https://github.com/notofonts/latin-greek-cyrillic.git at commit https://github.com/notofonts/latin-greek-cyrillic/commit/.

### CODE REVIEW

**Comment by bsoap-cat** [comment]
yippee

**Comment by simoncozens** [comment]
```
This release:

* Corrects the shape of U+A7AB LATIN CAPITAL LETTER REVERSED OPEN E and
U+026F TURNED M in italic (#48, #148)
* Improves the hook shape on V WITH HOOK (#178)
* Makes U+A7AE CAPITAL LETTER SMALL CAPITAL I a capital (#154)
* Improves the design and anchor positions of Latin upsilons (#179, #121)
* Corrects the placement of U+031A COMBINING LEFT ANGLE ABOVE (#183)
* Improves the design of U+1DF15 and U+1DF16 (#432)
* Corrects anchor positions on U+1D16 TOP HALF O and U+1D17 BOTTOM HALF O (#67)
* Allows the onum feature to apply to the figurespace (#39)
* Corrects the shape of U+2E49 DOUBLE STACKED COMMA (#59)
* Uses a Cyrillic breve when U+0306 COMBINING BREVE is used with Cyrillic (#38)
* Fixes the right side bearing of U+2057 QUADRUPLE PRIME (#415)
* Allows more African Latin combinations to be have the small caps feature
* Updates the shape of U+AB5A SMALL LETTER Y WITH SHORT RIGHT LEG to match Unicode 15.1
* Allows the pokrytie to be placed over superscript letters (#138)
* Support the sequence U+2E2B, U+032E for typicon notation (#63)
* Improves the anchoring of U+A69E COMBINING CYRILLIC LETTER EF (#220)
* Improves U+019E SMALL LETTER N WITH LONG RIGHT LEG and U+A798 CAPITAL LETTER F WITH STROKE
* Fixes the anchors on U+03D4, U+047E, and U+047F (#68)
* Adds IPA localizations to Greek script (#110)
```

**Comment by simoncozens** [comment]
ots fail is the same as before, dotted circle fail happens because of the shonky Deva subset. (It only affects Devanagari marks and as this is not *really* meant to be a Deva font, I don't particularly care.)

**Review by RosaWagner — APPROVED** [review]

**Comment by simoncozens** [comment]
> not something that will prevent to merge this PR, but you may want to look into it

It's the usual problem with the glyphsets. Eng don't want them to be too big. I think the reality is you just can't get all the glyphs available through the web API using the current subsetting strategy.

**Pull request merged**
