### PR TITLE
Noto Sans Batak: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
78987ec: [gftools-packager] Noto Sans Batak: Version 2.003; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Batak Version 2.003; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/batak.git at commit https://github.com/notofonts/batak/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
This release:

* Adds a default languagesystem tag (#11)
* Swaps postvowel and ng (#8)
```

**Comment by RosaWagner** [comment]
@simoncozens there is a shift with a diacritic. Is it okay?

https://github.com/google/fonts/assets/12222436/330fc583-f64d-46d4-864f-6e5d6d22a44e

**Comment by emmamarichal** [comment]
@simoncozens, could you take a look so we can merge or not the PR?

**Comment by simoncozens** [comment]
Sorry about the delay, yes, this is a fix, part of https://github.com/notofonts/batak/issues/8 - the NG sign should be above the consonant, not the vowel. So all good here.

**Comment by vituspolikarpussm** [comment]
I like the noto sans batak font because it has implemented a reordering command for diacritics. However, there are some ligatures that need to be fixed; namely the combination of the u diacritic which I circled in red in the following image
Glyph Noto sans Batak

the u diacritic symbol should be added intact. And it should be placed on the right or on the bottom right of the letter.
So the ligature in the image above should be made as I circled in red in the following image.

glyph noto sans batak modifikasi

If the glyph for the ligature can be fixed and updated, then the noto sans batak font is worthy of being the standard font for writing Batak script in supporting the digitalization process of the Batak script that we are currently doing. We greatly hope that the ligature can be fixed and updated. Thank you for making the noto sans batak font for us Batak people. Greetings Horas

**Comment by vituspolikarpussm** [comment]
As a consideration for improving the u diacritical ligature, here are some screenshots of the facts about writing the u diacritic in several Batak manuscripts, as I have framed in red in the following images:
pulung pulungan pangulu balang poda ajimamis alaman 2
andalu AA00001323
amang guru pustaha rambu siporhas halaman 4
pangulubalang the great pustaha

**Pull request merged**
