### PR TITLE
Chilanka: Version 1.510 added

### PR DESCRIPTION
**Pull request by graphicore**
* Chilanka Version 1.510 taken from the upstream repo https://github.com/smc/Chilanka.git at commit https://github.com/smc/Chilanka/commit/806d65fd8ec723e316063fb55dca83daf498f217.

### CODE REVIEW

**Comment by graphicore** [comment]
**CAUTION** same disclaimer as in [Manjari PR#2572](https://github.com/google/fonts/pull/2572#issuecomment-663273018) I used a `gftools packager` that builds from source, needs resolution.

**Comment by graphicore** [comment]
Updated

## Chilanka: Version 1.510 added

---
* Chilanka Version 1.510 taken from the upstream repo https://github.com/smc/Chilanka.git at commit https://github.com/smc/Chilanka/commit/76462b137b0b8a8b4734a62ad76d994e01101458.

**Comment by graphicore** [comment]
last update: changed the `upstream.yaml` branch to use the release tag instead.

**Comment by m4rc1e** [comment]
LGTM.

This review took me less than 5 minutes. I hope in the future the packager and our automated tests means we can push smaller updates much faster.

cc @davelab6.

**Comment by davelab6** [comment]
Great stuff!

**Pull request merged**
