### PR TITLE
Noto Sans Hanifi Rohingya: Version 2.101 added

### PR DESCRIPTION
**Pull request by simoncozens**
2e0a94f: [gftools-packager] Noto Sans Hanifi Rohingya: Version 2.101 added

* Noto Sans Hanifi Rohingya Version 2.101 taken from the upstream repo https://github.com/notofonts/hanifi-rohingya.git at commit https://github.com/notofonts/hanifi-rohingya/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens please confirm the marks shift is intended.

Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
This is wrong! Mark positioning isn't happening properly in the full builds. (This often happens in UFO-based projects where I haven't explicitly set the glyph categories; when merging the Latin core in, everything that isn't given an explicit category is considered to be a base.)

**Comment by simoncozens** [comment]
Hm, I can't reproduce this. Things look fine to me using the font in the repo:

shape

Must be browser weirdness? I'll take a look at the browserstack images.

**Comment by simoncozens** [comment]
I'm sorry - I don't know what's going on. The marks are attaching correctly in the font, and in the diffbrowser tests when I look at them in Safari and Chrome locally, but obviously they are not attaching for *any* of the diffbrowser VMs. I don't understand it. @m4rc1e, any ideas?

**Comment by vv-monsalve** [comment]
Yeah, I've performed local tests with a new template and reviewed them in the local Browserstack server, and it's working ok on Catalina's Safari, and the latest Edge and Chrome. So yes, it's not good that the marks are always shifting in the QA images :(

In the meanwhile, I think I'll merge the PR with this situation and check them on the dev sandbox server then. Wdyt @m4rc1e ?

cc @RosaWagner

**Comment by vv-monsalve** [comment]
Merging this here

**Pull request merged**
