### PR TITLE
Bruno Ace: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

### PR DESCRIPTION
**Pull request by yanone**
49fc1f9: [gftools-packager] Bruno Ace: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

* Bruno Ace Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] taken from the upstream repo https://github.com/googlefonts/Bruno-ace at commit https://github.com/googlefonts/Bruno-ace/commit/58dc219db32ffd9eaf573f2dc3be2e342410e15a.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@yanone I looked in the sources and there is all the elements to build combining marks etc

**Comment by yanone** [comment]
Updated

## Bruno Ace: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

---
 7ef6473: [gftools-packager] Bruno Ace: Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

* Bruno Ace Version 1.100; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] taken from the upstream repo https://github.com/googlefonts/Bruno-ace at commit https://github.com/googlefonts/Bruno-ace/commit/4dced3c1f1babfa7c2eac8ab0efa372c7bc5000f.

**Comment by RosaWagner** [comment]
These WARNs can easily be fixed:

⚠ WARN: Check math signs have the same width. ([com.google.fonts/check/math_signs_width](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/math_signs_width))

⚠ WARN: Does the font contain a soft hyphen? ([com.google.fonts/check/soft_hyphen](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/soft_hyphen)) 
**(to remove)**

⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))
**tip: if you remove it form source files, ufo2ft should build it with outline during export**

⚠ WARN: DESCRIPTION.en_us.html should end in a linebreak. ([com.google.fonts/check/description/eof_linebreak](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/eof_linebreak))

⚠ WARN: Are there caret positions declared for every ligature? ([com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets))

**Comment by RosaWagner** [comment]
Then please propose check deprecation in fontbakery so these WARNs stop warning https://github.com/googlefonts/fontbakery/issues/4102

**Comment by yanone** [comment]
Okay

**Comment by thlinard** [comment]
> > These WARNs can easily be fixed:
> > ⚠ WARN: Check math signs have the same width. ([com.google.fonts/check/math_signs_width](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/math_signs_width))
> 
> This makes no sense given that the font has only proportional figures.

Nope, the test doesn't refer to the figures: https://github.com/googlefonts/fontbakery/blob/main/Lib/fontbakery/profiles/universal.py 

```

> # Ironically, the block of text below may not have
>     # uniform widths for these glyphs depending on
>     # which font your text editor is using while you
>     # read the source code of this check:
>     COMMON_WIDTH_MATH_GLYPHS = (
>         "+ < = > ¬ ± × ÷ ∈ ∉ ∋ ∌ − ∓ ∔ ∝ ∟ ∠ ∡ ∢ ∷ ∸ ∹ ∺ ∻ "
>         "∼ ∽ ∾ ∿ ≁ ≂ ≃ ≄ ≅ ≆ ≇ ≈ ≉ ≊ ≋ ≌ ≍ ≎ ≏ ≐ ≑ ≒ ≓ ≖ ≗ "
>         "≘ ≙ ≚ ≛ ≜ ≝ ≞ ≟ ≠ ≡ ≢ ≣ ≤ ≥ ≦ ≧ ≨ ≩ ≭ ≮ ≯ ≰ ≱ ≲ ≳ "
>         "≴ ≵ ≶ ≷ ≸ ≹ ≺ ≻ ≼ ≽ ≾ ≿ ⊀ ⊁ ⊂ ⊃ ⊄ ⊅ ⊆ ⊇ ⊈ ⊉ ⊊ ⊋ ⊏ "
>         "⊐ ⊑ ⊒ ⊢ ⊣ ⊤ ⊥ ⊨ ⊰ ⊱ ⊲ ⊳ ⊴ ⊵ ⊹ ⊾ ⋇ ⋍ ⋐ ⋑ ⋕ ⋖ ⋗ ⋚ ⋛ "
>         "⋜ ⋝ ⋞ ⋟ ⋠ ⋡ ⋢ ⋣ ⋤ ⋥ ⋦ ⋧ ⋨ ⋩ ⋳ ⋵ ⋶ ⋸ ⋹ ⋻ ⋽ ⟀ ⟃ ⟄ ⟓ "
>         "⟔ ⥶ ⥸ ⥹ ⥻ ⥾ ⥿ ⦓ ⦔ ⦕ ⦖ ⦛ ⦜ ⦝ ⦞ ⦟ ⦠ ⦡ ⦢ ⦣ ⦤ ⦥ ⦨ ⦩ ⦪ "
>         "⦫ ⧣ ⧤ ⧥ ⧺ ⧻ ⨢ ⨣ ⨤ ⨥ ⨦ ⨧ ⨨ ⨩ ⨪ ⨫ ⨬ ⨳ ⩦ ⩧ ⩨ ⩩ ⩪ ⩫ ⩬ "
>         "⩭ ⩮ ⩯ ⩰ ⩱ ⩲ ⩳ ⩷ ⩸ ⩹ ⩺ ⩻ ⩼ ⩽ ⩾ ⩿ ⪀ ⪁ ⪂ ⪃ ⪄ ⪅ ⪆ ⪇ ⪈ "
>         "⪉ ⪊ ⪋ ⪌ ⪍ ⪎ ⪏ ⪐ ⪑ ⪒ ⪓ ⪔ ⪕ ⪖ ⪗ ⪘ ⪙ ⪚ ⪛ ⪜ ⪝ ⪞ ⪟ ⪠ ⪡ "
>         "⪢ ⪦ ⪧ ⪨ ⪩ ⪪ ⪫ ⪬ ⪭ ⪮ ⪯ ⪰ ⪱ ⪲ ⪳ ⪴ ⪵ ⪶ ⪷ ⪸ ⪹ ⪺ ⪽ ⪾ ⪿ "
>         "⫀ ⫁ ⫂ ⫃ ⫄ ⫅ ⫆ ⫇ ⫈ ⫉ ⫊ ⫋ ⫌ ⫏ ⫐ ⫑ ⫒ ⫓ ⫔ ⫕ ⫖ ⫟ ⫠ ⫡ ⫢ "
>         "⫤ ⫦ ⫧ ⫨ ⫩ ⫪ ⫫ ⫳ ⫴ ⫵ ⫶ ⫹ ⫺ 〒"
>     )

```

Cf. "Metrics" in https://www.tug.org/twg/mfg/papers/jkuester/20041002-atypi.pdf

**Comment by thlinard** [comment]
> Yes, the check doesn't refer to figures. But you never type-set math symbols in isolation. They are only ever used in conjunction with figures, and only ever need to be of equal width when set in a table with table figures. So as long as the figures are of proportional width, equal-width math figures are useless.
> 
> And if you ever do type-set math symbols in isolation, they still don't need to be of equal width.

Well, what we see most often are minuses which have the width of a dash and not a + without a vertical bar, × which don't have the shape of a + inclined at 45°, ='s which are not the same width as two minus in parallel... In this case, a warning for such basic things is useful.

But indeed, https://www.tug.org/twg/mfg/papers/jkuester/20041002-atypi.pdf says the expected norm in mathematics: "Glyphs of the same kind should have the same width", and not all the signs.

**Pull request merged**
