### PR TITLE
Noto Sans Canadian Aboriginal: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
2fa3be4: [gftools-packager] Noto Sans Canadian Aboriginal: Version 2.003 added

* Noto Sans Canadian Aboriginal Version 2.003 taken from the upstream repo https://github.com/notofonts/canadian-aboriginal.git at commit https://github.com/notofonts/canadian-aboriginal/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
This release:

* Adds stylistic set support for mid/low finals used in Athabaskan languages (#2)
* Fixes inconsistent dot spacing (#5)
```

**Comment by simoncozens** [comment]
Something very obviously weird about the STAT table with this font.

**Comment by RosaWagner** [comment]
@simoncozens The error must be due to the "indefined" position in the STAT table
Screenshot 2023-09-07 at 12 00 49

**Comment by RosaWagner** [comment]
@simoncozens the weight slightly changed but it's not chocking. Do I merge?

**Comment by simoncozens** [comment]
Let me check. I had a slight worry about the way this was built, I think there may be an issue with avar mapping.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Canadian Aboriginal: Version 2.004 added

---
 a83cd50: [gftools-packager] Noto Sans Canadian Aboriginal: Version 2.004 added

* Noto Sans Canadian Aboriginal Version 2.004 taken from the upstream repo https://github.com/notofonts/canadian-aboriginal.git at commit https://github.com/notofonts/canadian-aboriginal/commit/.

**Comment by simoncozens** [comment]
```
This release:

* adds the narrow no-break space character (U+202F) used in Cree.
* removes the semibold master, regularizing some spacing and dot positioning.
```

There *will* be weight and spacing changes in this release, and that's OK.

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
