### PR TITLE
Kalnia Glaze: Version 1.106 added



### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the upstream repo https://github.com/fridamedrano/Kalnia-Glaze at commit https://github.com/fridamedrano/Kalnia-Glaze/commit/3a17843c85b66d8acf51d0dd389da95131c1e66e.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
~- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target~
- [x] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> * I have still some interpolations issues reported in the pdf, but it's not visible. So I don't know how it's important. I guess it's some gradient issues.

Yes, we inspected the reported issues and confirmed that they were not crucial. Some of the reported cases cannot be handled differently due to how the shapes are colored.

> I would like to check with you if these kind of glyphs (hbar, lslash, etc) are ok. We can see the overlap, but it's maybe intentional.

These cases need to be confirmed by @fridamedrano

**Comment by fridamedrano** [comment]
Hi @vv-monsalve  and @emmamarichal !
Yes, those glyphs are ok (hbar, lslash, etc), I did an update for the cedilla one.
I'm glad you like the icons! I love how they are layed out for review, maybe I can do something similar for the minisite.

Thanks!

**Comment by vv-monsalve** [comment]
Updated

**Comment by vv-monsalve** [comment]
Something went wrong after running packager to update this PR. I'll close these here.

**Pull request closed without merging**
