### PR TITLE
to_production list July 4th fix

### PR DESCRIPTION
**Pull request by vv-monsalve**
@chrissimpkins This PR removes `Edu AU VIC WA NT Hand` from the prod list.

@garretrieger, please confirm if Kalnia Glaze should also be deleted from the list? See this [comment](https://github.com/google/fonts/pull/7917#issuecomment-2209087737) on the previous PR.

### CODE REVIEW

**Comment by garretrieger** [comment]
> @garretrieger, please confirm if Kalnia Glaze should also be deleted from the list? See this [comment](https://github.com/google/fonts/pull/7917#issuecomment-2209087737) on the previous PR.

Started an internal discussion on how we want to handle this one.

**Comment by vv-monsalve** [comment]
Okay, so I'll delist it not to block the PW push.

**Comment by garretrieger** [comment]
> Okay, so I'll delist it so as not to block the PW push.

Sounds good.

**Comment by vv-monsalve** [comment]
Done!

**Review by chrissimpkins — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@garretrieger, @chrissimpkins, I'll start preparing the new full lists for the week, so I'll close this first to avoid overlaps.

**Comment by vv-monsalve** [comment]
Oh! I see now you approved this one while I was writing my last comment.
So please let me know how you would like to proceed. Should we merge this one now and follow up with a new PR, including this week's new projects?

**Comment by vv-monsalve** [comment]
Since it was approved, I'll merge it now. Then, I will open a new one with the full official weekly lists.

**Pull request merged**
