### PR TITLE
Fix STAT table in Spartan variable

### PR DESCRIPTION
**Pull request by aaronbell**
This is a straight replacement of the existing Spartan font in the GF repository to resolve STAT-table related issues. 

The font in the upstream repro appears to be under development still, so it makes sense to wait for it to be completed. In the meantime, this will resolve the existing issue. Version bumped to 1.004.

### CODE REVIEW

**Comment by aaronbell** [comment]
## Fontbakery report

Fontbakery version: 0.7.16

<details>
<summary><b>[2] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Do we have the latest version of FontBakery installed?</summary>

* [com.google.fonts/check/fontbakery_version](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/fontbakery_version)

* 🔥 **FAIL** Unable to detect what's the latest version of FontBakery available. Maybe we're offline? Please check Internet access and try again.

</details>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** ftxvalidator is not available.

</details>
<br>
</details>
<details>
<summary><b>[9] Spartan[wght].ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking OS/2 usWeightClass matches weight specified at METADATA.pb.</summary>

* [com.google.fonts/check/metadata/os2_weightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/os2_weightclass)

* 🔥 **FAIL** OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (400:"Regular"). [code: mismatch]

</details>
<details>
<summary>🔥 <b>FAIL:</b> METADATA.pb weight matches postScriptName.</summary>

* [com.google.fonts/check/metadata/match_weight_postscript](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/match_weight_postscript)

* 🔥 **FAIL** METADATA.pb: Mismatch between postScriptName ("Spartan-Thin") and weight value (400). The name must be ended with "Regular" or "Italic".

</details>
<details>
<summary>🔥 <b>FAIL:</b> A static fonts directory with at least two fonts must accompany variable fonts</summary>

* [com.google.fonts/check/repo/vf_has_static_fonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/repo/vf_has_static_fonts)
<pre>--- Rationale ---

Variable font family directories kept in the google/fonts git repo must include
a static/ subdir containing static fonts.
These files are meant to be served for users that still lack support for
variable fonts in their web browsers.


</pre>

* 🔥 **FAIL** Please create a subdirectory called "static/" and include in it static font files. [code: missing]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)

* ⚠ **WARN** OS/2 VendorID value 'NONE' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 usWeightClass.</summary>

* [com.google.fonts/check/usweightclass](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/usweightclass)

* ⚠ **WARN** Thin:100 is OK on TTFs, but OTF files with those values will cause bluring on Windows. GlyphsApp users must set an Instance Custom Parameter for the Thin and ExtraLight styles to 250 and 275, so that if OTFs are exported then it will not blur on Windows. [code: blur-on-windows]

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is there kerning info for non-ligated sequences?</summary>

* [com.google.fonts/check/kerning_for_non_ligated_sequences](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/kerning_for_non_ligated_sequences)
<pre>--- Rationale ---

Fonts with ligatures should have kerning on the corresponding non-ligated
sequences for text where ligatures aren&#x27;t used (eg
https://github.com/impallari/Raleway/issues/14).


</pre>

* ⚠ **WARN** GPOS table lacks kerning info for the following non-ligated sequences:
	- f + f
	- f + i
	- i + f
	- f + l
	- l + f
	- i + l

   [code: lacks-kern-info]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font contains .notdef as first glyph?</summary>

* [com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs)
<pre>--- Rationale ---

The OpenType specification v1.8.2 recommends that the first glyph is the
.notdef glyph without a codepoint assigned and with a drawing.

https://docs.microsoft.com/en-us/typography/opentype/spec/recom#glyph-0-the-notdef-glyph

Pre-v1.8, it was recommended that a font should also contain a .null, CR and
space glyph. This might have been relevant for applications on MacOS 9.


</pre>

* ⚠ **WARN** Font should contain the .notdef glyph as the first glyph, it should not have a Unicode value assigned and should contain a drawing.

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking Vertical Metric Linegaps.</summary>

* [com.google.fonts/check/linegaps](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/hhea.html#com.google.fonts/check/linegaps)

* ⚠ **WARN** OS/2 sTypoLineGap is not equal to 0. [code: OS/2]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 4 | 7 | 35 | 7 | 110 | 0 |
| 0% | 2% | 4% | 21% | 4% | 67% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**

**Comment by aaronbell** [comment]
The fails here are pre-existing from the earlier version of the font. And the repro already contains the static versions, so not necessary to re-add them here :)

**Comment by davelab6** [comment]
> Fontbakery version: 0.7.16

Possibly the fails are false negatives that will auto resolve with latest fb release :)

**Comment by davelab6** [comment]
> the upstream repro appears to be under development still, so it makes sense to wait for it to be completed

Since https://fonts.google.com/specimen/Spartan is live, let's merge this ASAP. 

However, it would be good to update the family to the latest version, although indeed I'm not sure what that is.... I've enquired in https://github.com/theleagueof/league-spartan/issues/33 :)

There is some urgency in this due to https://github.com/google/fonts/issues/2505

**Comment by thlinard** [comment]
Issue #2505 not fixed.

**Comment by aaronbell** [comment]
@davelab6 How do you want to proceed on this font? It seems that there is some confusion / disagreement regarding the upstream source (per theleagueof/league-spartan#33 ) which may need some time to get sorted out. In the meantime, should we merge this in so that the STAT rendering issue is sorted?

**Comment by davelab6** [comment]
>> Since fonts.google.com/specimen/Spartan is live, let's merge this ASAP.
>
> How do you want to proceed on this font?

I'm not sure what changed since I said, "Since fonts.google.com/specimen/Spartan is live, let's merge this ASAP :) " - that remains my position :)

**Comment by thlinard** [comment]
Hi @davelab6 

> I'm not sure what changed since I said, "Since fonts.google.com/specimen/Spartan is live, let's merge this ASAP :) " - that remains my position :)

You said earlier "Since https://fonts.google.com/specimen/Spartan is live, let's merge this ASAP. […] There is some urgency in this due to #2505"

However, #2505 is still not fixed with this PR.

**Comment by RosaWagner** [comment]
@thlinard yes, we decided that this will be fixed later since we have to debunk the source repo issue which gonna need multiple emails and video calls. Until then we already have the STAT fix :)

**Comment by thlinard** [comment]
@RosaWagner OK I understand. At least one issue solved!

**Pull request merged**
