### PR TITLE
Titillium Web: v3.000 variable fonts added

### PR DESCRIPTION
**Pull request by eliheuer**
From the upstream repo: https://github.com/eliheuer/titillium-web-vf

### CODE REVIEW

**Comment by m4rc1e** [comment]
QA report in upstream https://github.com/eliheuer/titillium-web-vf

**Comment by eliheuer** [comment]
@m4rc1e I added a new regular variable font file conforming to the new name spec discussed here: https://github.com/google/fonts/issues/1817#issuecomment-466556000

Built from the upstream repo: https://github.com/eliheuer/titillium-web-vf/commit/c718586ffc06866e0a483952ebce51627a7a2eca

## Fontbakery report

Fontbakery version: 0.7.0

<details>
<summary><b>[4] TitilliumWeb.wght..ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/canonical_filename)
* 🔥 **FAIL** Please change the font filename to use one of the following valid suffixes for variable fonts: VF, Italic-VF, Roman-VF

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking with ots-sanitize.</summary>

* [com.google.fonts/check/ots](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/ots)
* 🔥 **FAIL** ots-sanitize returned an error code (1). Output follows:

ERROR: GDEF: bad caret value format: 3
ERROR: GDEF: Invalid ligature caret list
ERROR: GDEF: Failed to parse table
Failed to sanitize file!


</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
[('uni066C', 44.0572, -122.4099), ('uni066C', 75.6118, 35.3631), ('uni066C', 105.6638, 35.3631), ('uni066C', 67.3475, -122.4099), ('quotesinglbase', 121.2, 114.85), ('quotedblbase', 247.2, 108.85), ('quotedblleft', 273.14588, 727.1452), ('quotedblleft', 243.65775, 727.1452), ('quotedblleft', 140.14588, 727.1452), ('quotedblleft', 110.65775, 727.1452), ('quotedblright', 62.85412, 526.8548), ('quotedblright', 92.34225, 526.8548), ('quotedblright', 206.85412, 526.8548), ('quotedblright', 236.34225, 526.8548), ('quoteleft', 140.2, 726.85), ('quoteright', 62.8, 527.15), ('approxequal', 492.465, 329.0), ('approxequal', 492.465, 167.0)]
This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 2 | 53 | 6 | 87 |
| 0% | 1% | 1% | 35% | 4% | 58% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Comment by eliheuer** [comment]
I also added a new italic variable font file conforming to the new name spec. Built from the upstream repo: https://github.com/eliheuer/titillium-web-vf/commit/79ca7466dc7e611184905b6a6f6617d3d67f6e69

## Fontbakery report

Fontbakery version: 0.7.0

<details>
<summary><b>[4] TitilliumWeb-Italic.wght..ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Checking file is named canonically.</summary>

* [com.google.fonts/check/canonical_filename](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/canonical_filename)
* 🔥 **FAIL** Please change the font filename to use one of the following valid suffixes for variable fonts: VF, Italic-VF, Roman-VF

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking with ots-sanitize.</summary>

* [com.google.fonts/check/ots](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/ots)
* 🔥 **FAIL** ots-sanitize returned an error code (1). Output follows:

ERROR: GDEF: bad caret value format: 3
ERROR: GDEF: Invalid ligature caret list
ERROR: GDEF: Failed to parse table
Failed to sanitize file!


</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/unitsperem_strict)
* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check for points out of bounds.</summary>

* [com.google.fonts/check/points_out_of_bounds](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/points_out_of_bounds)
* ⚠ **WARN** The following glyphs have coordinates which are out of bounds:
[('uni066B', 98.5142, 83.0), ('uni066B', 187.34539999999998, -129.0), ('uni066C', 113.68809999999999, 32.3579), ('uni066C', 143.74009999999998, 32.3579), ('uni066C', 180.4375, -126.9177), ('uni060C', 173.48579999999998, 0.0), ('uni060C', 84.65460000000002, 212.0), ('approxequal', 124.65499999999997, 327.0), ('approxequal', 124.65499999999997, 165.0)]
This happens a lot when points are not extremes, which is usually bad. However, fixing this alert by adding points on extremes may do more harm than good, especially with italics, calligraphic-script, handwriting, rounded and other fonts. So it is common to ignore this message

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 2 | 2 | 53 | 6 | 87 |
| 0% | 1% | 1% | 35% | 4% | 58% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

**Comment by m4rc1e** [comment]
You can find the results of this pr [here](https://github.com/m4rc1e/fonts/pull/162#issuecomment-482145368). 



@eliheuer 
 can you rename the fonts in the following [manner]( https://github.com/m4rc1e/fonts/pull/162/commits/39f2004fb0cc1d67dc48f75b915ac1dc80cda3a1)

You'll then need to set the fsSelection to 200

**Comment by eliheuer** [comment]
I split this PR into two (roman, italic) new style PRs (for using GF bot). I'm closing work here and moving to the new PRs:

Roman:  https://github.com/google/fonts/pull/1987
Italic: https://github.com/google/fonts/pull/1988

**Pull request closed without merging**
