### PR TITLE
Noto Serif Hentaigana: Version 1.000 added

### PR DESCRIPTION
**Pull request by simoncozens**
ae3761d: [gftools-packager] Noto Serif Hentaigana: Version 1.000 added

* Noto Serif Hentaigana Version 1.000 taken from the upstream repo https://github.com/notofonts/hentaigana.git at commit https://github.com/notofonts/hentaigana/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
This is a new font family to cover the Kana Extended unicode block.

I'm fairly sure the name length failure is not a problem because this VF has its default position at extra light. ExtraLight should not be added to the instance name, so all is good.

**Comment by simoncozens** [comment]
This will probably need subset work.

**Comment by emmamarichal** [comment]
Ah, indeed!

Screenshot 2024-03-06 at 12 06 29

**Comment by emmamarichal** [comment]
@simoncozens I see that the subset issue is solved! 
So now, I just need to update the metadata.pb with 
`subsets: "kana-extended"` right?

**Comment by simoncozens** [comment]
Yes please!

**Comment by emmamarichal** [comment]
### Status:

When I added the subset 'kana-extended', it broke the dev-server. Garret fixed that, and re-pushed the subset update.
Currently, the metadata.pb shows well `subsets: "kana-extended"` and the subset is in the CSS:

```
/* kana-extended */
@font-face {
  font-family: 'Noto Serif Hentaigana';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts-dev.sandbox.google.com/l/font?kit=uk-OEHi3o6EruUbj3pGaDj3siVARn-kqgu1eOHk7wYK23O0hzowGm6QyfE06aDix6dU&skey=a3caba7afda0bcbb&v=dev) format('woff2');
  unicode-range: U+3099-309C, U+1B100-1B122;
}
```

**However**, I still see that in the dev-server:

Screenshot 2024-08-07 at 15 28 52

@simoncozens Do you know if we need language option like `languages: "ain_Kana"  # Ainu`, to make it works?

cc @garretrieger @nathan-williams

**Comment by simoncozens** [comment]
We probably need a language option, but more to the point we also need some Hentaigana sample text. I'll work on some.

However, I am not seeing the subset correctly in dev; if I enter Hentaigana in the type tester, I get tofu: (This is with U+1B01B)

Screenshot 2024-08-08 at 09 25 44

**Comment by simoncozens** [comment]
Sample text PR: #8013.

The kana extended subset definition looks correct. Eng may need to repush. @garretrieger @nathan-williams

**Comment by chrissimpkins** [comment]
We included this in the to_sandbox list and will check subsetting again following the sandbox push.

**Comment by emmamarichal** [comment]
Works in Sandbox! I add it to the to_production list.
Screenshot 2024-09-12 at 14 10 48

**Comment by simoncozens** [comment]
No longer working in sandbox?!

Screenshot 2024-10-18 at 16 06 19

**Comment by vv-monsalve** [comment]
Hi @garretrieger, @nathan-williams 

The target script is not shown consistently in the Sandbox server. 

- It displays it ok in the font preview. 

Screenshot 2024-11-08 at 15 13 28

- But then when entering to the font's specimen page, it only shows Latin.

Screenshot 2024-11-08 at 15 14 12

<br>

We consider all the necessary pieces to have been fulfilled. Could you please assist us in understanding the situation with it? Is there anything else needed from our side for the font to show up correctly in the UI? 

- Subset: `subsets: "kana-extended"`
- Script `primary_script: "Hira"`
- And the sample for the language was included in [#8013](https://github.com/google/fonts/pull/8013)

**Comment by emmamarichal** [comment]
@nyshadhr9, if you have time to take a look at this :) 
This font is blocked for a moment, and we don't know what is the blocker

**Comment by chrissimpkins** [comment]
What is the status here?

**Comment by emmamarichal** [comment]
Status:

We now have tofu everywhere (dev-sandbox + sandbox) cc @rsheeter 

Screenshot 2025-01-14 at 15 52 29
Screenshot 2025-01-14 at 15 52 41

**Comment by simoncozens** [comment]
@rsheeter This does point to some weirdness in the API, where if a font has both `primary_language` and `sample_text`, the primary language field is winning. I would have expected the `sample_text` field, which is specific to the font, to be displayed.

**Comment by simoncozens** [comment]
This is now behaving nicely in dev, can go to sandbox please!

**Pull request merged**
