### PR TITLE
Update Source Code Pro, version 2038 (roman), version 1.058 (italic),…

### PR DESCRIPTION
**Pull request by burnsra**
… version 1,018 (variable)

### CODE REVIEW

**Comment by burnsra** [comment]
@googlebot I signed it!

**Comment by davelab6** [comment]
@burnsra thanks for this. @RosaWagner please check these files match the Adobe originals, rename them back to what we had before, and haven't been modified, and lint them with fontbakery etc like normal :)

**Comment by brunoarueira** [comment]
@davelab6 @burnsra Since the font needs to be updated, I'd like to propose to fix the permissions over the files, because it has an executable permission which should not be necessary!

I've already filled an issue #3342 and a pull request on #3343 to fix the wrong permission on Source Code Pro and other resources as well which I've found through the project.

**Comment by burnsra** [comment]
@davelab6 / @m4rc1e  Thanks for getting things moving!  I had renamed the italic versions to match the names as they are in the Adobe repo currently, hoping to make any future changes from Adobe easier.

**Comment by RosaWagner** [comment]
We just merged another version of Source Code Pro in #4010 so I close this PR. Won't be live on the API before few weeks though. Thanks for the work in any case.

**Pull request closed without merging**
