### PR TITLE
Noto Sans: 2.007 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo [googlefonts/noto-fonts](https://github.com/googlefonts/noto-fonts/) at commit [a8800e6](https://github.com/googlefonts/noto-fonts/commit/a8800e6798c6837b981158d5a1f944ad480e06d5).

See notes from #4274.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens I don't remember, is this PR ready for review or still wanted to correct the fonts after generating the fontbakery report? If second option, you can use the label "in progress" to notify us so we don't merge.

**Comment by simoncozens** [comment]
I think I'm waiting for you!

**Comment by RosaWagner** [comment]
I only see this that is concerning since the font has devanagari:
🔥 FAIL: Ensure dotted circle glyph is present and can attach marks.

**Comment by simoncozens** [comment]
Argh. This is a new check, and I’m working on binaries for this font merge.

**Comment by RosaWagner** [comment]
> Argh. This is a new check,

Yes, then I think we can ignore if it can make the process faster and if it will be in the next update.

Since it's a very important font, I'd like someone to confirm these diff are okay (there can be bugs in the diff though, but better be sure):

[diffbrowsers.zip](https://github.com/google/fonts/files/8123448/diffbrowsers.zip)

**Comment by simoncozens** [comment]
Looks OK to me but the ring of Å is detached in the Italic. (But that's what's in Noto Sans, so...)

Anyway, I will leave Marek to look over the diffs and give the executive opinion.

**Comment by marekjez86** [comment]
looking at it

**Comment by marekjez86** [comment]
Looks great. Thank you Simon!

**Pull request merged**
