### PR TITLE
Noto Sans Tangsa: Version 1.504 added

### PR DESCRIPTION
**Pull request by simoncozens**
c04e041: [gftools-packager] Noto Sans Tangsa: Version 1.504 added

* Noto Sans Tangsa Version 1.504 taken from the upstream repo https://github.com/notofonts/tangsa.git at commit https://github.com/notofonts/tangsa/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
@simoncozens also missing languages in metadata.pb

**Comment by simoncozens** [comment]
We don't actually have any Tangsa text or even a script definition in the langs repo. I'll try and find something.

**Comment by RosaWagner** [comment]
Note to self.
Waiting for resolution on:
- [ ] https://github.com/googlefonts/glyphsets/pull/83
- [x] #5489

**Comment by simoncozens** [comment]
I merged the glyphset change but it needs eng to sync.

**Comment by simoncozens** [comment]
Probably opentypespec.tags

**Comment by simoncozens** [comment]
(Done)

**Pull request merged**
