### PR TITLE
oswald/DESC updated to correct Cyrillic info

### PR DESCRIPTION
**Pull request by davelab6**
Resolves https://github.com/googlefonts/OswaldFont/issues/25

### CODE REVIEW

**Comment by RosaWagner** [comment]
Does it mean that we can also merge https://github.com/google/fonts/pull/3893 ?

**Comment by alexeiva** [comment]
@davelab6 does this also remove the designer icon?
Screenshot 2021-12-04 at 09 31 37

**Comment by davelab6** [comment]
@RosaWagner Description updates run along a different path to TTF updates, so we can merge and push this separately to that PR which updates the VF. 

@alexeiva no, good point. I'll fix that now

**Comment by davelab6** [comment]
OK since that is controlled in the METADATA file, I've updated it in the other PR. I'll check with the eng team if that's the correct way to go.

**Comment by RosaWagner** [comment]
I would rather wait for confirmation from the eng team so we can merge all the Oswald pending PRs. Indeed there is a version of the font blocked in sandbox and putting this font directory on the prod list I'm afraid would also give instruction to push the blocked font.

**Comment by davelab6** [comment]
I'll ask @rsheeter about this too

**Pull request merged**
