### PR TITLE
Tac One article

### PR DESCRIPTION
**Pull request by emmamarichal**
I received nice images and gif. Let's add them in an article.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Will fix the CI before I merge this. Otherwise LGTM

**Comment by m4rc1e** [comment]
Blocking due to the .gif being too large.

**Comment by emmamarichal** [comment]
@m4rc1e images format changed, you can review it and merge it! Thanks :)

**Comment by emmamarichal** [comment]
The bigger mp4 is now 7,2mb instead of 14. Hope it will be enough!

**Review by m4rc1e — APPROVED** [review]

**Review by m4rc1e — DISMISSED** [review]
A 7mb mp4 still feels heavy. If @nathan-williams is happy then I'll merge.

**Comment by emmamarichal** [comment]
I can just remove it if it's too much! let me know @nathan-williams

**Comment by vv-monsalve** [comment]
This was @nathan-williams answer on the chat
> MP4 files would follow the same processing pathway as vector images, whereas GIFs would flow along with rasterized images like PNG and JPG

That is, mp4 could go up to 1.75MB while animated gifs should be 800Kb max.

@emmamarichal  please replace the huge `.mp4` file with a compliant image.

**Comment by emmamarichal** [comment]
Done!

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@emmamarichal, Tac One's article is showing broken links on dev server

Screen Shot 2024-04-16 at 10 02 28

**Comment by vv-monsalve** [comment]
Superseded bu #7576.

**Pull request merged**
