### PR TITLE
Update OFL/alike*/METADATA.pb

### PR DESCRIPTION
**Pull request by davelab6**
Per designer request

I'll add the other family and review the description html files shortly

### CODE REVIEW

**Comment by davelab6** [comment]
> I'll add the other family and review the description html files shortly

Done, ready to review

**Comment by alexeiva** [comment]
@davelab6 
Could you also update the ttfs in this or another PR, they have updated copyright info:

https://github.com/cyrealtype/Alike/blob/main/fonts/ttf/Alike-Regular.ttf

https://github.com/cyrealtype/Alike-Angular/blob/main/fonts/ttf/AlikeAngular-Regular.ttf

**Comment by RosaWagner** [comment]
@davelab6 @alexeiva there are too much fails to ignore here. Especially this one:
🔥 FAIL: OS/2.fsSelection bit 7 (USE_TYPO_METRICS) is set in all fonts. ([com.google.fonts/check/os2/use_typo_metrics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/os2/use_typo_metrics))
🔥 FAIL OS/2.fsSelection bit 7 (USE_TYPO_METRICS) wasNOT set in the following fonts: ['ofl/alikeangular/AlikeAngular-Regular.ttf']. [code: missing-os2-fsselection-bit7]

@alexeiva Since you want the font file to also be updated, do you mind if we re-QA and re-build the font upstream before merging these changes?

**Comment by alexeiva** [comment]
@RosaWagner yes, please do the re-QA

**Comment by emmamarichal** [comment]
I sent a PR for each family:
https://github.com/cyrealtype/Alike/pull/4
https://github.com/cyrealtype/Alike-Angular/pull/1

It needs some design work (mainly accents)

**Comment by davelab6** [comment]
@emmamarichal please could you set up a meeting with @alexeiva next week to review the design work?

@alexeiva comment vont vos compétences en français ces jours-ci ? :)

**Comment by alexeiva** [comment]
> @emmamarichal please could you set up a meeting with @alexeiva next week to review the design work?> 

@emmamarichal I'm available for a call 8-14h Paris time weekly

> @alexeiva comment vont vos compétences en français ces jours-ci ? :)
Oui. Croissant!

I've added some missing GF Core glyphs for [Alike](https://github.com/cyrealtype/Alike). 
Will do the same for Alike Angular as well.

**Comment by alexeiva** [comment]
> Let's say tomorrow 14h? @alexeiva @davelab6 can you make it?

Yes, works for me

**Comment by RosaWagner** [comment]
closing in favour of #6930 and #6929

**Pull request closed without merging**
