### PR TITLE
Noto Sans Lepcha: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
c739d0b: [gftools-packager] Noto Sans Lepcha: Version 2.004; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Lepcha Version 2.004; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/lepcha.git at commit https://github.com/notofonts/lepcha/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens are these marks shift ok? Particularly ᰎᰥᰦᰱᰊᰚᰬ
Desktop_Windows_10_chrome_71 0_

**Comment by simoncozens** [comment]
No, this is very bad. Thanks for catching.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Lepcha: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

---
 40d21dc: [gftools-packager] Noto Sans Lepcha: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Lepcha Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/lepcha.git at commit https://github.com/notofonts/lepcha/commit/.

**Comment by RosaWagner** [comment]
Seems that only Chrome is behaving correctly.

safari:
Desktop_OS_X_High_Sierra_safari_11 1_


Edge:
Desktop_Windows_10_edge_18 0_

**Comment by simoncozens** [comment]
OK, there are a number of issues here:

* Safari on Browserstack is zeroing out the width of post-base marks.
* On Edge, post-base marks are interfering with mark attachment.

These two problems are connected; the fix is to swap post-base marks to be after above/below marks and also to make them base glyphs. I'll work on this.

**Comment by simoncozens** [comment]
Updated

## Noto Sans Lepcha: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

---
 d3314a1: [gftools-packager] Noto Sans Lepcha: Version 2.006; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Lepcha Version 2.006; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/lepcha.git at commit https://github.com/notofonts/lepcha/commit/.

**Comment by RosaWagner** [comment]
@simoncozens 

Edge:
Desktop_Windows_10_edge_18 0_

But checking the html on Edge Windows 11 (below), it looks just fine, so tempted to ignore the above.

Capture d’écran 2022-10-27 à 10 47 54

**Comment by simoncozens** [comment]
I agree; old version on Browserstack, maybe?

**Pull request merged**
