### PR TITLE
Update Cairo Authors

### PR DESCRIPTION
**Pull request by Gue3bara**

### CODE REVIEW

**Comment by Gue3bara** [comment]
I signed the CLA

**Comment by Gue3bara** [comment]
I also wanted to update the authors on two more fonts "Lemonada" and "El Messiri" but i couldn't find them in the directory though they are on the platform any idea why?

**Comment by eliheuer** [comment]
@Gue3bara I'm looking at the latest commit to master on `google/fonts` and it looks like El Messiri is here [fonts/blob/master/ofl/elmessiri](https://github.com/google/fonts/blob/master/ofl/elmessiri/METADATA.pb), and Lemonada is here [fonts/tree/master/ofl/lemonada](https://github.com/google/fonts/tree/master/ofl/lemonada). Those Metadata files have the same problem and I believe it was my fault in those cases.

Sorry your name was left out of the metadata. Maybe the QA tool [FontBakery](https://github.com/googlefonts/fontbakery) could have a warning about metadata files that just lists "Multiple Designers" for `designer`. Or [gftools-add-font.py](https://github.com/googlefonts/gftools/blob/master/bin/gftools-add-font.py) could do a better job with this. Any thoughts @felipesanches ?

**Comment by Gue3bara** [comment]
Thank you @eliheuer I updated the other two families as well

**Comment by eliheuer** [comment]
Thanks, @m4rc1e could you review and merge this and the other two PRs (https://github.com/google/fonts/pull/2349, https://github.com/google/fonts/pull/2349) from @Gue3bara ? Or is there a reason for using `Multiple Designers`? To me it seam like @Gue3bara is clearly the primary designer for all three of these typefaces and leaving his name out of the metadata wouldn't be giving him proper credit.

**Comment by eliheuer** [comment]
@Gue3bara I talked to Marc about this today, and he was wondering if it would be better to list each designer or institution involved instead of including multiple designers. 

So, for Cairo would it make more sense to have this in the METADATA?
```
designer: "Mohamed Gaber, Accademia di Belle Arti di Urbino"
```
Thanks! Marc wasn't against the way it is now in this pull request, there just aren't any other METADATA files in this repo that list a designer and then `multiple designers`, so he didn't want to set a precedent without a good reason.

The two other PRs seem fine, Thanks again!

**Comment by Gue3bara** [comment]
Thank you @eliheuer and @m4rc1e 
I dont mind the proposed crediting 
I reported this and was just hoping for it to be fixed for couple of years already

**Comment by eliheuer** [comment]
@m4rc1e Cairo is still only shows "Designed by Multiple Designers" on https://fonts.google.com/specimen/Cairo. What needs to happen to fix this? If I make a PR changing the second line of Cairo's METADATA.pb file to `designer: "Mohamed Gaber, Accademia di Belle Arti di Urbino"`, would that work?

**Comment by m4rc1e** [comment]
Yes that will work.

**Comment by eliheuer** [comment]
Thanks, I made a PR here: https://github.com/google/fonts/pull/2450

**Comment by Gue3bara** [comment]
@m4rc1e any update on this matter?
The credit still says “Multiple Designers” 
Any idea when will this be fixed on the platform?

**Comment by eliheuer** [comment]
@Gue3bara I have a new pull request open that would solve this, it can be merged before the other pull request for Cairo: https://github.com/google/fonts/pull/2450

Sorry I stopped working on this, I moved across the county recently, but I'm back at a desk now and will try to get this merged ASAP.

**Pull request merged**
