### PR TITLE
Canonical names

### PR DESCRIPTION
**Pull request by thlinard**

### CODE REVIEW

**Comment by thlinard** [comment]
Hi @m4rc1e @davelab6 

If you don't see any problems with this PR, can you merge it? It'll make my life a little bit easier. 😀

**Comment by m4rc1e** [comment]
@thlinard Thanks! It looks good. I'll ask if we can get this merged.

**Comment by thlinard** [comment]
Hi @m4rc1e 

Any news?

**Comment by m4rc1e** [comment]
Discussing it tomorrow.

**Comment by m4rc1e** [comment]
Apologies, it didn't get merged this week. I'll try again tomorrow.

**Comment by thlinard** [comment]
Hi @m4rc1e 
If Friday is Update Day, don't forget this one!

**Comment by m4rc1e** [comment]
We'd be living life very dangerously if we pushed on Friday :-).

Pushes usually happen Mon-Thurs. This gives us time to rollback if we push something bad.

**Comment by thlinard** [comment]
Well, I don't want to ruin your weekend, but please push this correction in not too long! 😃

**Comment by davelab6** [comment]
I don't see any issues with this :) Thank you @thlinard!!! :)

**Comment by davelab6** [comment]
@thlinard small thing, if you prepend a `#` to issue/pr numbers, Github will auto-link them (eg see commit message text in https://github.com/google/fonts/commit/9253a5145f754df1d2eb110c3cf17d3161093e1d); I noticed your commit message text had issue/pr numbers but were not autolinked.

**Comment by thlinard** [comment]
Thank you Dave! And thanks for the tip!

**Pull request merged**
