### PR TITLE
Noto Sans Gujarati: Version 2.103 added

### PR DESCRIPTION
**Pull request by simoncozens**
f06afde: [gftools-packager] Noto Sans Gujarati: Version 2.103 added

* Noto Sans Gujarati Version 2.103 taken from the upstream repo https://github.com/notofonts/gujarati.git at commit https://github.com/notofonts/gujarati/commit/.

### CODE REVIEW

**Review by m4rc1e — COMMENTED** [review]
I see Latin kerning has been included. 

In the Gujarati, it seems that a dot above has been replaced by a candrabindu in some diffenator reports. @simoncozens if this is intentional then LGTM, feel free to merge.

**Comment by simoncozens** [comment]
Sorry, forgot the release notes:

This release:
* Decomposes vertical matras when forming ligatures
* **Fixes an issue where candrabindus would turn into anusvaras**
* Adds an anchor on the AI vowel

**Comment by m4rc1e** [comment]
Sweet. Thank you!

**Comment by RosaWagner** [comment]
@simoncozens @m4rc1e was that PR supposed to be merged? There is no label and it is not in traffic jam.

**Comment by m4rc1e** [comment]
Yep, apologies for missing the other stuff.

**Comment by simoncozens** [comment]
It was supposed to be merged, my fault for not labelling it up.

**Pull request merged**
