### PR TITLE
Oi: Version 3.000 added

### PR DESCRIPTION
**Pull request by emmamarichal**
c3358a4: [gftools-packager] Oi: Version 3.000 added

* Oi Version 3.000 taken from the upstream repo https://github.com/kosbarts/Oi at commit https://github.com/kosbarts/Oi/commit/c415b9872bf1313a294bbf26fc261b85c2b6c729.

 4e21443: [gftools-packager] ofl/oi remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
@kosbarts can you take a look at the 2 fails about components? Did you use `gftools builder` to replicate locally the gh-action build, or Fontmake directly?

You can ignore the fail about the broken link, I just tested and your website works fine :)

**Comment by kosbarts** [comment]
@RosaWagner I used fontmake directly. I can decompose the components and reproduce. However these components where there in the previous version and since it is a display font I am not sure if we should be worrying too much about any hinting issues. Let me know what you think. 
I can also fix the issue with  components who are themselves components and reproduce.

**Comment by RosaWagner** [comment]
No I would prefer gftools builder since it wraps a lot of little fixes needed for GF and you wouldn't need to decompose anything. It can be used on Big Sur, but if you don't want to struggle with that @emmamarichal can make you a PR today.

**Comment by kosbarts** [comment]
@RosaWagner how do I use GFtools builder locally?

**Comment by RosaWagner** [comment]
once you have gftools in a venv, you can run `gftools builder config.yaml` from the `sources` dir
if you want support for Glyphs3, you will also need to `pip install git+https://github.com/googlefonts/fontmake`, and then `pip install git+https://github.com/googlefonts/GlyphsLib`

**Comment by kosbarts** [comment]
OK. I reproduced the font files using builder and just pushed to the repo.

**Comment by emmamarichal** [comment]
Updated

## Oi: Version 3.000 added

---
 b072ccd: [gftools-packager] Oi: Version 3.000 added

* Oi Version 3.000 taken from the upstream repo https://github.com/kosbarts/Oi at commit https://github.com/kosbarts/Oi/commit/cf9af4eb9f50e30ca9cf08287a8193180a4526ed.

 87fa3de: [gftools-packager] ofl/oi remove METADATA "source".  google/fonts#2587

**Pull request merged**
