### PR TITLE
remove Mike LaGattuta from METADATA.pb

### PR DESCRIPTION
**Pull request by felipesanches**
followup to PR #2261

### CODE REVIEW

**Comment by felipesanches** [comment]
@googlebot I consent

**Comment by laerm0** [comment]
Thanks Felipe. Someday I will figure out git. 😞

**Comment by felipesanches** [comment]
@laerm0 Whenever we meet in person, I will be glad to show you in detail what happened here. It is not that much complicated. I will be glad to help you learn these "tricks". :-)

**Comment by felipesanches** [comment]
@laerm0 I think you have to tell the bot you're OK with this PR by posting here `@googlebot I consent`

**Comment by m4rc1e** [comment]
Thanks @laerm0 @felipesanches .

**Comment by laerm0** [comment]
@googlebot I consent

**Pull request merged**
