### PR TITLE
Noto Sans Cypriot: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
ce95cd3: [gftools-packager] Noto Sans Cypriot: Version 2.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Cypriot Version 2.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/cypriot.git at commit https://github.com/notofonts/cypriot/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
Updated

## Noto Sans Cypriot: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

---
 bae98ed: [gftools-packager] Noto Sans Cypriot: Version 2.002; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Cypriot Version 2.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/cypriot.git at commit https://github.com/notofonts/cypriot/commit/.

**Comment by RosaWagner** [comment]
@simoncozens 

🔥 FAIL: Checking STAT table entries in static fonts. ([com.google.fonts/check/STAT_in_statics](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/STAT_in_statics))
🔥 FAIL The STAT table has more than a single entry for the 'wght' axis (9) on this static font which will causes problems on Windows. [code: multiple-STAT-entries]
🔥 FAIL The STAT table has more than a single entry for the 'wdth' axis (4) on this static font which will causes problems on Windows. [code: multiple-STAT-entries]
🔥 FAIL The STAT table has more than a single entry for the 'CTGR' axis (2) on this static font which will causes problems on Windows. [code: multiple-STAT-entries]

**Comment by simoncozens** [comment]
Weird. I'll take a look.

**Comment by simoncozens** [comment]
Oh wait, I know what this is. A re-build should fix it.

**Comment by simoncozens** [comment]
No dotted circle needed.

**Review by RosaWagner — APPROVED** [review]

**Comment by RosaWagner** [comment]
@simoncozens Tofu in sandbox

Screenshot 2023-09-21 at 13 48 21

**Comment by simoncozens** [comment]
U+10100-10102 missing from Cypriot glyphset. I'll fix it.

**Comment by simoncozens** [comment]
https://github.com/googlefonts/glyphsets/pull/128

**Comment by simoncozens** [comment]
It's working now.

**Comment by RosaWagner** [comment]
Ah so we need to re-push to sandbox, thanks

**Comment by simoncozens** [comment]
It's working in sandbox.

**Pull request merged**
