### PR TITLE
Add Picon Font 1.0

### PR DESCRIPTION
**Pull request by yne**
- The typeface design is original :heavy_check_mark: 
- SIL OFL v1.1 Licenced :heavy_check_mark:
- No Reserved Font Names :heavy_check_mark:
- Google CLA :heavy_check_mark:
- Registraton namecheck.fontdata.com : :heavy_check_mark:  
- font automatically generated via GitHub Action :heavy_check_mark: 
- Font files are available in ttfautohinted-TTF + OTF + WOFF2 [using fontmake](https://github.com/yne/picon/blob/master/.github/workflows/page.yml#L34) :heavy_check_mark: 
- listed 215 glyphs :heavy_check_mark: 
- Font Bakery google-fonts profile checks: [ERROR:0 FAIL:3 WARN:5 SKIP:70 INFO:1 PASS:53](https://fontbakery.graphicore.de/report/79ef2f23-3f9c-4147-a863-ec8e3ce79618)
- [README.md](https://github.com/yne/picon/blob/master/README.md) in the root of the source repository
- DESCRIPTION.en_us.html, a profile.txt and a your-name.jpg

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.15

<details>
<summary><b>[2] Family checks</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> Check METADATA.pb parse correctly.</summary>

* [com.google.fonts/check/metadata/parses](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/parses)
<pre>--- Rationale ---

The purpose of this check is to ensure that the METADATA.pb file is not
malformed.


</pre>

* 🔥 **FAIL** Family metadata at /var/folders/y0/gs7dshh54gng8n1zgzr53nbw0000gn/T/tmpi2ci2eqa/ofl/picon failed to parse.
TRACEBACK:
3:1 : Message type "google.fonts.FamilyProto" has no field named "designer_url". [code: parsing-error]

</details>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** ftxvalidator is not available.

</details>
<br>
</details>
<details>
<summary><b>[17] Picon-Regular.ttf</b></summary>
<details>
<summary>🔥 <b>FAIL:</b> DESCRIPTION.en_us.html must have more than 200 bytes.</summary>

* [com.google.fonts/check/description/min_length](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/description/min_length)

* 🔥 **FAIL** DESCRIPTION.en_us.html must have size larger than 200 bytes. [code: too-short]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check copyright namerecords match license file.</summary>

* [com.google.fonts/check/name/license](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license)

* 🔥 **FAIL** License file OFL.txt exists but NameID 13 (LICENSE DESCRIPTION) value on platform 1 (MACINTOSH) is not specified for that. Value was: "OFL" Must be changed to "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL" [code: wrong]
* 🔥 **FAIL** License file OFL.txt exists but NameID 13 (LICENSE DESCRIPTION) value on platform 3 (WINDOWS) is not specified for that. Value was: "OFL" Must be changed to "This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL" [code: wrong]

</details>
<details>
<summary>🔥 <b>FAIL:</b> License URL matches License text on name table?</summary>

* [com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url)

* 🔥 **FAIL** A known license URL must be provided in the NameID 14 (LICENSE INFO URL) entry. Currently accepted licenses are Apache: 'http://www.apache.org/licenses/LICENSE-2.0' or Open Font License: 'http://scripts.sil.org/OFL'
For a small set of legacy families the Ubuntu Font License 'https://www.ubuntu.com/legal/terms-and-policies/font-licence' may be acceptable as well.
When in doubt, please choose OFL for new font projects. [code: no-license-found]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check name table: TYPOGRAPHIC_FAMILY_NAME entries.</summary>

* [com.google.fonts/check/name/typographicfamilyname](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/typographicfamilyname)

* 🔥 **FAIL** Font style is "Regular" and, for that reason, it is not expected to have a [TYPOGRAPHIC_FAMILY_NAME(16):MACINTOSH(1)] entry! [code: ribbi]
* 🔥 **FAIL** Font style is "Regular" and, for that reason, it is not expected to have a [TYPOGRAPHIC_FAMILY_NAME(16):WINDOWS(3)] entry! [code: ribbi]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Name table records must not have trailing spaces.</summary>

* [com.google.fonts/check/name/trailing_spaces](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/name/trailing_spaces)

* 🔥 **FAIL** Name table record with key = (1, 0, 0, 12) has trailing spaces that must be removed: ' '
* 🔥 **FAIL** Name table record with key = (3, 1, 1033, 12) has trailing spaces that must be removed: ' '

</details>
<details>
<summary>🔥 <b>FAIL:</b> Font has **proper** whitespace glyph names?</summary>

* [com.google.fonts/check/whitespace_glyphnames](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/whitespace_glyphnames)

* 🔥 **FAIL** Glyph 0x00A0 is called "uni00a0": Change to "nbsp" or "uni00A0" [code: badA0]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Are there unwanted tables?</summary>

* [com.google.fonts/check/unwanted_tables](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/unwanted_tables)
<pre>--- Rationale ---

Some font editors store source data in their own SFNT tables, and these can
sometimes sneak into final release files, which should only have OpenType spec
tables.


</pre>

* 🔥 **FAIL** The following unwanted font tables were found:
Table: FFTM
Reason: Table contains redundant FontForge timestamp info

They can be removed by using fonttools/ttx.

</details>
<details>
<summary>🔥 <b>FAIL:</b> Check name table for empty records.</summary>

* [com.adobe.fonts/check/name/empty_records](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/name.html#com.adobe.fonts/check/name/empty_records)
<pre>--- Rationale ---

Check the name table for empty records, as this can cause problems in Adobe
apps.


</pre>

* 🔥 **FAIL** "name" table record with key=(1, 0, 0, 12) is empty and should be removed. [code: empty-record]
* 🔥 **FAIL** "name" table record with key=(3, 1, 1033, 12) is empty and should be removed. [code: empty-record]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Checking correctness of monospaced metadata.</summary>

* [com.google.fonts/check/monospace](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/name.html#com.google.fonts/check/monospace)
<pre>--- Rationale ---

There are various metadata in the OpenType spec to specify if a font is
monospaced or not. If the font is not trully monospaced, then no monospaced
metadata should be set (as sometimes they mistakenly are...)

Monospace fonts must:

* post.isFixedWidth &quot;Set to 0 if the font is proportionally spaced, non-zero if
the font is not proportionally spaced (monospaced)&quot;
  www.microsoft.com/typography/otspec/post.htm

* hhea.advanceWidthMax must be correct, meaning no glyph&#x27;s width value is
greater.
  www.microsoft.com/typography/otspec/hhea.htm

* OS/2.panose.bProportion must be set to 9 (monospace). Spec says: &quot;The PANOSE
definition contains ten digits each of which currently describes up to sixteen
variations. Windows uses bFamilyType, bSerifStyle and bProportion in the font
mapper to determine family type. It also uses bProportion to determine if the
font is monospaced.&quot;
  www.microsoft.com/typography/otspec/os2.htm#pan
  monotypecom-test.monotype.de/services/pan2

* OS/2.xAverageWidth must be set accurately.
  &quot;OS/2.xAverageWidth IS used when rendering monospaced fonts, at least by
Windows GDI&quot;
  http://typedrawers.com/discussion/comment/15397/#Comment_15397

Also we should report an error for glyphs not of average width


</pre>

* 🔥 **FAIL** On monospaced fonts, the value of OS/2.panose.bProportion must be set to 9 (proportion: monospaced), but got 0 instead. [code: mono-bad-panose-proportion]

</details>
<details>
<summary>🔥 <b>FAIL:</b> Does the font have a DSIG table?</summary>

* [com.google.fonts/check/dsig](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/dsig.html#com.google.fonts/check/dsig)
<pre>--- Rationale ---

Some programs expect fonts to have a digital signature declared in their DSIG
table in order to work properly.

This checks verifies that such signature is available in the font.

Typically, even a fake signature would be enough to make the fonts work. If
needed, such dummy-placeholder can be added to the font by using the `gftools
fix-dsig` script available at https://github.com/googlefonts/gftools


</pre>

* 🔥 **FAIL** This font lacks a digital signature (DSIG table). Some applications may require one (even if only a dummy placeholder) in order to work properly. You can add a DSIG table by running the `gftools fix-dsig` script. [code: lacks-signature]

</details>
<details>
<summary>⚠ <b>WARN:</b> Checking OS/2 achVendID.</summary>

* [com.google.fonts/check/vendor_id](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/vendor_id)

* ⚠ **WARN** OS/2 VendorID value 'XXXX' is not a known registered id. You should set it to your own 4 character code, and register that code with Microsoft at https://www.microsoft.com/typography/links/vendorlist.aspx [code: unknown]

</details>
<details>
<summary>⚠ <b>WARN:</b> Font has old ttfautohint applied?</summary>

* [com.google.fonts/check/old_ttfautohint](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/old_ttfautohint)
<pre>--- Rationale ---

This check finds which version of ttfautohint was used, by inspecting name
table entries and then finds which version of ttfautohint is currently
installed in the system.


</pre>

* ⚠ **WARN** ttfautohint used in font = 1.8.1; installed = 1.8.3; Need to re-run with the newer version! [code: old-ttfa]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---

Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.

But value of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.

Another acceptable value is 2000. Since TT outlines are all integers (no
floats), then instances in a VF suffer rounding compromises, and therefore a
1000 UPM is to small because it forces too many such compromises.

Therefore 2000 is a good &#x27;new VF standard&#x27;, because 2000 is a simple 2x
conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what
10 units can do for 1000 UPM will know what 20 units does too.

Additionally, values above 2048 would result in filesize increases with not
much added benefit.


</pre>

* ⚠ **WARN** Even though unitsPerEm (16) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
<pre>--- Rationale ---

Visually QAing thousands of glyphs by hand is tiring. Most glyphs can only be
constructured in a handful of ways. This means a glyph&#x27;s contour count will
only differ slightly amongst different fonts, e.g a &#x27;g&#x27; could either be 2 or 3
contours, depending on whether its double story or single story.

However, a quotedbl should have 2 contours, unless the font belongs to a
display family.

This check currently does not cover variable fonts because there&#x27;s plenty of
alternative ways of constructing glyphs with multiple outlines for each feature
in a VarFont. The expected contour count data for this check is currently
optimized for the typical construction of glyphs in static fonts.


</pre>

* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: uni2013	Contours detected: 0	Expected: 1
Glyph name: uni2014	Contours detected: 0	Expected: 1
Glyph name: uni0023	Contours detected: 4	Expected: 2
Glyph name: uni002b	Contours detected: 2	Expected: 1
Glyph name: uni0040	Contours detected: 3	Expected: 2
Glyph name: uni0045	Contours detected: 3	Expected: 1
Glyph name: uni004b	Contours detected: 3	Expected: 1 or 2
Glyph name: uni0051	Contours detected: 3	Expected: 2
Glyph name: uni0059	Contours detected: 2	Expected: 1
Glyph name: uni0061	Contours detected: 3	Expected: 2
Glyph name: uni0065	Contours detected: 3	Expected: 2
Glyph name: uni0066	Contours detected: 2	Expected: 1
Glyph name: uni0071	Contours detected: 3	Expected: 2
Glyph name: uni0074	Contours detected: 2	Expected: 1
Glyph name: uni0078	Contours detected: 2	Expected: 1
Glyph name: uni007e	Contours detected: 2	Expected: 1
Glyph name: uni00a5	Contours detected: 3	Expected: 1 or 2
Glyph name: uni00a7	Contours detected: 1	Expected: 2
Glyph name: uni00a9	Contours detected: 2	Expected: 3
Glyph name: uni00ad	Contours detected: 0	Expected: 1
Glyph name: uni00b1	Contours detected: 3	Expected: 1 or 2
Glyph name: uni00c0	Contours detected: 2	Expected: 3
Glyph name: uni00c1	Contours detected: 2	Expected: 3
Glyph name: uni00c2	Contours detected: 2	Expected: 3
Glyph name: uni00c3	Contours detected: 2	Expected: 3
Glyph name: uni00c4	Contours detected: 2	Expected: 4
Glyph name: uni00c5	Contours detected: 2	Expected: 3 or 4
Glyph name: uni00c8	Contours detected: 3	Expected: 2
Glyph name: uni00c9	Contours detected: 3	Expected: 2
Glyph name: uni00ca	Contours detected: 3	Expected: 2
Glyph name: uni00cc	Contours detected: 1	Expected: 2
Glyph name: uni00cd	Contours detected: 1	Expected: 2
Glyph name: uni00ce	Contours detected: 1	Expected: 2
Glyph name: uni00cf	Contours detected: 1	Expected: 3
Glyph name: uni00d1	Contours detected: 1	Expected: 2
Glyph name: uni00d2	Contours detected: 2	Expected: 3
Glyph name: uni00d3	Contours detected: 2	Expected: 3
Glyph name: uni00d4	Contours detected: 2	Expected: 3
Glyph name: uni00d5	Contours detected: 2	Expected: 3
Glyph name: uni00d6	Contours detected: 2	Expected: 4
Glyph name: uni00d7	Contours detected: 2	Expected: 1
Glyph name: uni00d9	Contours detected: 1	Expected: 2
Glyph name: uni00da	Contours detected: 1	Expected: 2
Glyph name: uni00db	Contours detected: 1	Expected: 2
Glyph name: uni00dc	Contours detected: 1	Expected: 3
Glyph name: uni00df	Contours detected: 3	Expected: 1
Glyph name: uni00e4	Contours detected: 3	Expected: 4
Glyph name: uni00e5	Contours detected: 3	Expected: 4
Glyph name: uni00e6	Contours detected: 2	Expected: 3
Glyph name: uni00eb	Contours detected: 3	Expected: 4
Glyph name: uni00ef	Contours detected: 2	Expected: 3
Glyph name: uni00f2	Contours detected: 2	Expected: 3
Glyph name: uni00f3	Contours detected: 2	Expected: 3
Glyph name: uni00f4	Contours detected: 2	Expected: 3
Glyph name: uni00f5	Contours detected: 2	Expected: 3
Glyph name: uni00f6	Contours detected: 2	Expected: 4
Glyph name: uni00f8	Contours detected: 2	Expected: 3
Glyph name: uni00f9	Contours detected: 1	Expected: 2
Glyph name: uni00fa	Contours detected: 1	Expected: 2
Glyph name: uni00fb	Contours detected: 1	Expected: 2
Glyph name: uni00fc	Contours detected: 1	Expected: 3
Glyph name: uni00fd	Contours detected: 1	Expected: 2
Glyph name: uni00ff	Contours detected: 1	Expected: 3
Glyph name: uni0131	Contours detected: 2	Expected: 1
Glyph name: uni0153	Contours detected: 2	Expected: 3
Glyph name: uni02dc	Contours detected: 2	Expected: 1
Glyph name: uni20ac	Contours detected: 3	Expected: 1 or 2 [code: contour-count]

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
<pre>--- Rationale ---

All ligatures in a font must have corresponding caret (text cursor) positions
defined in the GDEF table, otherwhise, users may experience issues with caret
rendering.


</pre>

* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Name table strings must not contain the string 'Reserved Font Name'.</summary>

* [com.google.fonts/check/name/rfn](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/name.html#com.google.fonts/check/name/rfn)

* ⚠ **WARN** Name table entry ("Copyright 2020 The Picon Project Authors (https://github.com/yne/picon/graphs/contributors with Reserved Font Name "Picon")") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]
* ⚠ **WARN** Name table entry ("Copyright 2020 The Picon Project Authors (https://github.com/yne/picon/graphs/contributors with Reserved Font Name "Picon")") contains "Reserved Font Name". This is an error except in a few specific rare cases. [code: rfn]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)

* ⚠ **WARN** GPOS table lacks kerning information. [code: lacks-kern-info]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 11 | 8 | 64 | 6 | 72 | 0 |
| 0% | 7% | 5% | 40% | 4% | 45% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [picon_qa.zip](http://35.238.63.0/media/fd93fc0b-0aa6-4d3b-b79a-50fd6c6f5984/picon_qa.zip)

**Comment by m4rc1e** [comment]
Thank you for the PR. I'll show the family to the team and see if we'll include it.

**Comment by yne** [comment]
> Thank you for the PR. I'll show the family to the team and see if we'll include it.

@m4rc1e : any update or suggestions ?

**Comment by yne** [comment]
Hi, I'm just passing by to say that I've updated the PR with the new version, and I'm still available if you need anything :)

**Comment by davelab6** [comment]
@yne thanks for your amazing work on this - we are not quite ready to accept icon fonts, so I'll keep this open for now, and follow up soon

**Comment by yne** [comment]
@davelab6 thanks for your feedback.

I totally understand your position, so no problem for me, take your time.

I know that the question of what makes a font an "icon font" (especially in the unicode era) surely won't be easy to define.

**Comment by RosaWagner** [comment]
Since we won't be merging this before a while, I would rather close this PR and track the font through an issue.
@yne can you open an issue "add font" in the issue tracker to submit the font there ?

**Pull request closed without merging**
