### PR TITLE
Alumni Sans Collegiate One: Version 1.010 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
f4d0c8f: [gftools-packager] Alumni Sans Collegiate One: Version 1.010 added

* Alumni Sans Collegiate One Version 1.010 taken from the upstream repo https://github.com/googlefonts/alumni-sans-collegiate at commit https://github.com/googlefonts/alumni-sans-collegiate/commit/59d6f0cbe50850d784688415f64d771d2227ef18.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Updated

## Alumni Sans Collegiate One: Version 1.010 added

---
 ac67072: [gftools-packager] Alumni Sans Collegiate One: Version 1.010 added

* Alumni Sans Collegiate One Version 1.010 taken from the upstream repo https://github.com/googlefonts/alumni-sans-collegiate at commit https://github.com/googlefonts/alumni-sans-collegiate/commit/b46653d1fe947d6ec06438b1606ae3bb1928b69a.

**Comment by vv-monsalve** [comment]
- Alumni Sans Collegiate is part of Batch 4 of TypeSetIT fonts
- Is based on the ExtraBold weight of the Alumni Sans vf
- Particle 'One' was added in case other weight could be added in the future

**Comment by m4rc1e** [comment]
Thanks!

**Comment by RosaWagner** [comment]
saw that in sandbox:
Capture d’écran 2022-04-15 à 11 47 18

**Comment by vv-monsalve** [comment]
Solved in #4855

**Pull request merged**
