### PR TITLE
Alkatra: Version 1.100 added

### PR DESCRIPTION
**Pull request by yanone**
2d573ec: [gftools-packager] Alkatra: Version 1.100 added

* Alkatra Version 1.100 taken from the upstream repo https://github.com/suman51284/Alkatra at commit https://github.com/suman51284/Alkatra/commit/1998f70c8ab415d5e024e297f05704bab2a47241.

### CODE REVIEW

**Comment by RosaWagner** [comment]
Yes, otherwise it will get subsetted

**Comment by RosaWagner** [comment]
Just checked 2 glyphs reported with interpolation issues, it is true at least for Degree and Equal. So it would be good to check the other ones too.

Since you got to re-open the sources, those warns are quick to fix:
⚠ WARN: Check copyright namerecords match license file. ([com.google.fonts/check/name/license](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license))
⚠ WARN: License URL matches License text on name table? ([com.google.fonts/check/name/license_url](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/googlefonts.html#com.google.fonts/check/name/license_url))
⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))

**Comment by yanone** [comment]
I'll check. And anyway, the designer URL actually has a bunch of porn links on it. I'll ask for another one.

**Comment by yanone** [comment]
Updated

## Alkatra: Version 1.100 added

---
 ef03faa: [gftools-packager] Alkatra: Version 1.100 added

* Alkatra Version 1.100 taken from the upstream repo https://github.com/suman51284/Alkatra at commit https://github.com/suman51284/Alkatra/commit/650ed854f901403a4516cdfb8bd13f8c554dea33.

**Comment by yanone** [comment]
Okay, done

**Comment by yanone** [comment]
Holding this back as a rendering issue has appeared...

**Comment by yanone** [comment]
Updated

## Alkatra: Version 1.100;gftools[0.9.22] added

---
 d19507a: [gftools-packager] Alkatra: Version 1.100;gftools[0.9.22] added

* Alkatra Version 1.100;gftools[0.9.22] taken from the upstream repo https://github.com/suman51284/Alkatra at commit https://github.com/suman51284/Alkatra/commit/0192cbf706f1dc560534c73153fd0e566323b31e.

**Pull request merged**
