### PR TITLE
Birthstone: Version 1.010; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
833766e: [gftools-packager] Birthstone: Version 1.010; ttfautohint (v1.8.3) added

* Birthstone Version 1.010; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/birthstone at commit https://github.com/googlefonts/birthstone/commit/718357cb4fb59c0142ad4d51aa6f609b3587113e.

 6131584: [gftools-packager] ofl/birthstone remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by vv-monsalve** [comment]
This is part of the Batch2 TypeSetIt projects.

> 🔥 FAIL Designer Robert Leuschke still does not have a webpage link on the catalog. Please provide one. [code: missing-link]

It was already done in #3463

**Comment by vv-monsalve** [comment]
Updated

## Birthstone: Version 1.011; ttfautohint (v1.8.3) added

---
 23059e0: [gftools-packager] Birthstone: Version 1.011; ttfautohint (v1.8.3) added

* Birthstone Version 1.011; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/googlefonts/birthstone at commit https://github.com/googlefonts/birthstone/commit/ee85ee98a3678333faaed450ed7533e707876691.

 db63438: [gftools-packager] ofl/birthstone remove METADATA "source".  google/fonts#2587

**Comment by m4rc1e** [comment]
Thanks Viv! LGTM

**Comment by vv-monsalve** [comment]
Hi @RosaWagner, as we talked I just marked this as "blocked" for now.
It is going to have a sibling family and I want to be sure the VM are consistent between both of them.

**Comment by vv-monsalve** [comment]
> Hi @RosaWagner, as we talked I just marked this as "blocked" for now.
> It is going to have a sibling family and I want to be sure the VM are consistent between both of them.

This has been followed in #3792

**Pull request merged**
