### PR TITLE
bethellen: v2.000 added

### PR DESCRIPTION
**Pull request by felipesanches**
(https://github.com/googlefonts/BethEllen/commit/d6c8d9b3871c432c6abfd71660885f16ddbce3e2)

screenshot at 2019-03-07 18 48 56
screenshot at 2019-03-07 18 50 01
screenshot at 2019-03-07 18 50 18
screenshot at 2019-03-07 18 50 45
screenshot at 2019-03-07 18 51 01

## Fontbakery report

Fontbakery version: 0.7.4

<details>
<summary><b>[5] BethEllen-Regular.ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Checking with ftxvalidator.</summary>

* [com.google.fonts/check/ftxvalidator](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator)
* 💔 **ERROR** ftxvalidator returned an error code. Output follows:

ssh: connect to host 192.168.0.11 port 22: No route to host
lost connection
ssh: connect to host 192.168.0.11 port 22: No route to host
ssh: connect to host 192.168.0.11 port 22: No route to host

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: r.alt1	Contours detected: 1	Expected: 3
Glyph name: four	Contours detected: 3	Expected: 1 or 2
Glyph name: eight	Contours detected: 2	Expected: 3
Glyph name: C	Contours detected: 2	Expected: 1
Glyph name: D	Contours detected: 3	Expected: 2
Glyph name: F	Contours detected: 3	Expected: 1
Glyph name: G	Contours detected: 4	Expected: 1
Glyph name: H	Contours detected: 3	Expected: 1
Glyph name: I	Contours detected: 3	Expected: 1
Glyph name: J	Contours detected: 3	Expected: 1
Glyph name: K	Contours detected: 3	Expected: 1 or 2
Glyph name: L	Contours detected: 3	Expected: 1
Glyph name: O	Contours detected: 3	Expected: 2
Glyph name: R	Contours detected: 3	Expected: 1 or 2
Glyph name: S	Contours detected: 3	Expected: 1
Glyph name: T	Contours detected: 2	Expected: 1
Glyph name: U	Contours detected: 3	Expected: 1
Glyph name: Y	Contours detected: 2	Expected: 1
Glyph name: f	Contours detected: 2	Expected: 1
Glyph name: h	Contours detected: 3	Expected: 1
Glyph name: j	Contours detected: 3	Expected: 2
Glyph name: l	Contours detected: 2	Expected: 1
Glyph name: o	Contours detected: 3	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: s	Contours detected: 2	Expected: 1
Glyph name: currency	Contours detected: 3	Expected: 2
Glyph name: onequarter	Contours detected: 6	Expected: 3 or 4
Glyph name: onehalf	Contours detected: 4	Expected: 3
Glyph name: threequarters	Contours detected: 6	Expected: 3 or 4
Glyph name: Agrave	Contours detected: 4	Expected: 3
Glyph name: Aacute	Contours detected: 4	Expected: 3
Glyph name: Egrave	Contours detected: 3	Expected: 2
Glyph name: Eacute	Contours detected: 3	Expected: 2
Glyph name: Igrave	Contours detected: 5	Expected: 2
Glyph name: Iacute	Contours detected: 5	Expected: 2
Glyph name: Icircumflex	Contours detected: 4	Expected: 2
Glyph name: Idieresis	Contours detected: 5	Expected: 3
Glyph name: Eth	Contours detected: 3	Expected: 2
Glyph name: Ograve	Contours detected: 5	Expected: 3
Glyph name: Oacute	Contours detected: 5	Expected: 3
Glyph name: Ocircumflex	Contours detected: 4	Expected: 3
Glyph name: Otilde	Contours detected: 4	Expected: 3
Glyph name: Odieresis	Contours detected: 5	Expected: 4
Glyph name: Ugrave	Contours detected: 5	Expected: 2
Glyph name: Uacute	Contours detected: 5	Expected: 2
Glyph name: Ucircumflex	Contours detected: 4	Expected: 2
Glyph name: Udieresis	Contours detected: 5	Expected: 3
Glyph name: Yacute	Contours detected: 4	Expected: 2
Glyph name: Thorn	Contours detected: 3	Expected: 1 or 2
Glyph name: agrave	Contours detected: 4	Expected: 3
Glyph name: aacute	Contours detected: 4	Expected: 3
Glyph name: egrave	Contours detected: 4	Expected: 3
Glyph name: eacute	Contours detected: 4	Expected: 3
Glyph name: igrave	Contours detected: 3	Expected: 2
Glyph name: iacute	Contours detected: 3	Expected: 2
Glyph name: ograve	Contours detected: 5	Expected: 3
Glyph name: oacute	Contours detected: 5	Expected: 3
Glyph name: ocircumflex	Contours detected: 4	Expected: 3
Glyph name: otilde	Contours detected: 4	Expected: 3
Glyph name: odieresis	Contours detected: 5	Expected: 4
Glyph name: ugrave	Contours detected: 3	Expected: 2
Glyph name: uacute	Contours detected: 3	Expected: 2
Glyph name: yacute	Contours detected: 3	Expected: 2
Glyph name: trademark	Contours detected: 1	Expected: 2
Glyph name: uni2074	Contours detected: 3	Expected: 1 or 2
Glyph name: fraction	Contours detected: 2	Expected: 1

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)
* ⚠ **WARN** GPOS table lacks kerning information.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 1 | 0 | 4 | 28 | 7 | 116 |
| 1% | 0% | 3% | 18% | 4% | 74% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.8

<details>
<summary><b>[4] BethEllen-Regular.ttf</b></summary>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)
* ⚠ **WARN** Family not found via Google Fonts API.

</details>
<details>
<summary>⚠ <b>WARN:</b> Check if each glyph has the recommended amount of contours.</summary>

* [com.google.fonts/check/contour_count](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/contour_count)
* ⚠ **WARN** This check inspects the glyph outlines and detects the total number of contours in each of them. The expected values are infered from the typical ammounts of contours observed in a large collection of reference font families. The divergences listed below may simply indicate a significantly different design on some of your glyphs. On the other hand, some of these may flag actual bugs in the font such as glyphs mapped to an incorrect codepoint. Please consider reviewing the design and codepoint assignment of these to make sure they are correct.

The following glyphs do not have the recommended number of contours:

Glyph name: r.alt1	Contours detected: 1	Expected: 3
Glyph name: four	Contours detected: 3	Expected: 1 or 2
Glyph name: eight	Contours detected: 2	Expected: 3
Glyph name: C	Contours detected: 2	Expected: 1
Glyph name: D	Contours detected: 3	Expected: 2
Glyph name: F	Contours detected: 3	Expected: 1
Glyph name: G	Contours detected: 4	Expected: 1
Glyph name: H	Contours detected: 3	Expected: 1
Glyph name: I	Contours detected: 3	Expected: 1
Glyph name: J	Contours detected: 3	Expected: 1
Glyph name: K	Contours detected: 3	Expected: 1 or 2
Glyph name: L	Contours detected: 3	Expected: 1
Glyph name: O	Contours detected: 3	Expected: 2
Glyph name: R	Contours detected: 3	Expected: 1 or 2
Glyph name: S	Contours detected: 3	Expected: 1
Glyph name: T	Contours detected: 2	Expected: 1
Glyph name: U	Contours detected: 3	Expected: 1
Glyph name: Y	Contours detected: 2	Expected: 1
Glyph name: f	Contours detected: 2	Expected: 1
Glyph name: h	Contours detected: 3	Expected: 1
Glyph name: j	Contours detected: 3	Expected: 2
Glyph name: l	Contours detected: 2	Expected: 1
Glyph name: o	Contours detected: 3	Expected: 2
Glyph name: q	Contours detected: 3	Expected: 2
Glyph name: s	Contours detected: 2	Expected: 1
Glyph name: currency	Contours detected: 3	Expected: 2
Glyph name: onequarter	Contours detected: 6	Expected: 3 or 4
Glyph name: onehalf	Contours detected: 4	Expected: 3
Glyph name: threequarters	Contours detected: 6	Expected: 3 or 4
Glyph name: Agrave	Contours detected: 4	Expected: 3
Glyph name: Aacute	Contours detected: 4	Expected: 3
Glyph name: Egrave	Contours detected: 3	Expected: 2
Glyph name: Eacute	Contours detected: 3	Expected: 2
Glyph name: Igrave	Contours detected: 5	Expected: 2
Glyph name: Iacute	Contours detected: 5	Expected: 2
Glyph name: Icircumflex	Contours detected: 4	Expected: 2
Glyph name: Idieresis	Contours detected: 5	Expected: 3
Glyph name: Eth	Contours detected: 3	Expected: 2
Glyph name: Ograve	Contours detected: 5	Expected: 3
Glyph name: Oacute	Contours detected: 5	Expected: 3
Glyph name: Ocircumflex	Contours detected: 4	Expected: 3
Glyph name: Otilde	Contours detected: 4	Expected: 3
Glyph name: Odieresis	Contours detected: 5	Expected: 4
Glyph name: Ugrave	Contours detected: 5	Expected: 2
Glyph name: Uacute	Contours detected: 5	Expected: 2
Glyph name: Ucircumflex	Contours detected: 4	Expected: 2
Glyph name: Udieresis	Contours detected: 5	Expected: 3
Glyph name: Yacute	Contours detected: 4	Expected: 2
Glyph name: Thorn	Contours detected: 3	Expected: 1 or 2
Glyph name: agrave	Contours detected: 4	Expected: 3
Glyph name: aacute	Contours detected: 4	Expected: 3
Glyph name: egrave	Contours detected: 4	Expected: 3
Glyph name: eacute	Contours detected: 4	Expected: 3
Glyph name: igrave	Contours detected: 3	Expected: 2
Glyph name: iacute	Contours detected: 3	Expected: 2
Glyph name: ograve	Contours detected: 5	Expected: 3
Glyph name: oacute	Contours detected: 5	Expected: 3
Glyph name: ocircumflex	Contours detected: 4	Expected: 3
Glyph name: otilde	Contours detected: 4	Expected: 3
Glyph name: odieresis	Contours detected: 5	Expected: 4
Glyph name: ugrave	Contours detected: 3	Expected: 2
Glyph name: uacute	Contours detected: 3	Expected: 2
Glyph name: yacute	Contours detected: 3	Expected: 2
Glyph name: trademark	Contours detected: 1	Expected: 2
Glyph name: uni2074	Contours detected: 3	Expected: 1 or 2
Glyph name: fraction	Contours detected: 2	Expected: 1

</details>
<details>
<summary>⚠ <b>WARN:</b> Are there caret positions declared for every ligature?</summary>

* [com.google.fonts/check/ligature_carets](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/ligature_carets)
* ⚠ **WARN** This font lacks caret position values for ligature glyphs on its GDEF table. [code: lacks-caret-pos]

</details>
<details>
<summary>⚠ <b>WARN:</b> Does GPOS table have kerning information?</summary>

* [com.google.fonts/check/gpos_kerning_info](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/gpos.html#com.google.fonts/check/gpos_kerning_info)
* ⚠ **WARN** GPOS table lacks kerning information.

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 0 | 4 | 28 | 8 | 121 |
| 0% | 0% | 2% | 17% | 5% | 75% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**


## Diff images: [qa.zip](http://35.188.158.120/media/48c2e259-a54e-47f0-8d4f-9e54f67f8c64/qa.zip)

**Comment by m4rc1e** [comment]
LGTM. Quite possible the most illegible font I've ever seen :-)

Desktop_Windows_10_chrome_69 0_


@felipesanches If you make a pr in the future, make the pr directly to google/fonts, not from your fork. Travis doesn't work from forked repos which contain private environment variables

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

https://docs.travis-ci.com/user/environment-variables/

**Comment by m4rc1e** [comment]
@felipesanches Is this mergeable?

**Comment by felipesanches** [comment]
Yes, I think it is. But it could also still be much improved, such as by reducing quantity of points per glyph.

Maybe that could be done afterwards when/if the font gets more popular on gfonts?

**Comment by m4rc1e** [comment]
@felipesanches agreed. We can lower the node count later on. Most display/handwritten fonts do not have optimised nodes.

**Comment by laerm0** [comment]
We at Ascender/Monotype had a tool for this: paging @josh-hadley and Jeff Finger... 😜

**Pull request merged**
