### PR TITLE
Roboto: Version 3.005; 2022 added

### PR DESCRIPTION
**Pull request by m4rc1e**
85cafe3: [gftools-packager] Roboto: Version 3.005; 2022 added

* Roboto Version 3.005; 2022 taken from the upstream repo https://github.com/googlefonts/roboto-classic at commit https://github.com/googlefonts/roboto-classic/commit/.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Please note that we don't want to push this to fonts.google.com so it shouldn't be added to the push lists.

**Comment by chrissimpkins** [comment]
Noted.  Thanks Marc.  

We are ok with all of the fontbakery tests results?  These are not regressions vs. the last version?

**Comment by m4rc1e** [comment]
> We are ok with all of the fontbakery test results? These are not regressions vs. the last version or issues that must be addressed now?

Roboto Classic has its own FB profiles which have all passed, https://github.com/googlefonts/roboto-classic/runs/7537842826?check_suite_focus=true

I checked for regressions against v3.004 and the fonts are clean.

**Comment by chrissimpkins** [comment]
Thank you very much for the rapid turnaround on this Marc.  I really appreciate it!

**Comment by thlinard** [comment]
The fix #92 https://github.com/googlefonts/roboto-classic/pull/92 was apparently never merged.

**Comment by m4rc1e** [comment]
https://github.com/googlefonts/roboto-classic/pull/92 was made so two internal teams could get their fixes out asap. I'll review the stat stuff and cut a new release for it later on.

**Comment by kpozin** [comment]
Did you mean to delete all the static versions in this commit?

**Comment by m4rc1e** [comment]
@kpozin we've stopped including static fonts for releases. However, I spoke to @chrissimpkins and we've made an exception for this family. I've just made #5058 which includes the statics.

**Comment by vv-monsalve** [comment]
Superseded by #6943

**Pull request merged**
