### PR TITLE
Baloo Da 2: Version 1.700 added

### PR DESCRIPTION
**Pull request by yanone**
2c95a84: [gftools-packager] Baloo Da 2: Version 1.700 added

* Baloo Da 2 Version 1.700 taken from the upstream repo https://github.com/yanone/Baloo2-Variable at commit https://github.com/yanone/Baloo2-Variable/commit/da523dfa21aa0e376253d61c21e39146dc55702a.

 f97327b: [gftools-packager] ofl/balooda2 remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by yanone** [comment]
Updated

## Baloo Da 2: Version 1.700 added

---
 d0729a3: [gftools-packager] Baloo Da 2: Version 1.700 added

* Baloo Da 2 Version 1.700 taken from the upstream repo https://github.com/yanone/Baloo2-Variable at commit https://github.com/yanone/Baloo2-Variable/commit/ffd6308743a5829fe6980ce86f5629ba0250df98.

 a6bccd2: [gftools-packager] ofl/balooda2 remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
Curious that the font is having transformed components now, did the build changed?

**Comment by yanone** [comment]
`fontbakery` changed since I started Baloo. And now it doesn't build with `fontmake` anymore because it also changed regarding transformed components. Since half of the Baloo family has already been accepted beforehand, I decided to ignore the transformed components for now as they are only 6 affected Latin glyphs with double accents, and push the family as is (regarding the transformed components). I would like to ask to accept them. I can make an update once the tooling is good enough to accept transformed components in only one master (which is the case here)

**Comment by RosaWagner** [comment]
I see, the famous https://github.com/googlefonts/ufo2ft/issues/507 
yep okay, fine by me 👍

**Pull request merged**
