### PR TITLE
Vazirmatn: Version 32.0.0 added

### PR DESCRIPTION
**Pull request by yanone**
09dad74: [gftools-packager] Vazirmatn: Version 32.0.0 added

* Vazirmatn Version 32.0.0 taken from the upstream repo https://github.com/rastikerdar/vazirmatn at commit https://github.com/rastikerdar/vazirmatn/commit/ee3cdd5345612b07d7c0d5fde377d35f45209e9c.

### CODE REVIEW

**Comment by yanone** [comment]
Updated

## Vazirmatn: Version 32.0.0 added

---
 1d756d2: [gftools-packager] Vazirmatn: Version 32.0.0 added

* Vazirmatn Version 32.0.0 taken from the upstream repo https://github.com/rastikerdar/vazirmatn at commit https://github.com/rastikerdar/vazirmatn/commit/e56a45e09d5d83a254e50e1b11e92ba84f7a3b8f.

**Comment by thlinard** [comment]
> I told the author to put in a good work about the dotted circle check. He did his work ahead of the new requirement, and to my knowledge, it's never used for Arabic

Not quite. See "For the fallback mechanism to work properly, an Arabic OTL font should contain a glyph for the dotted circle (U+25CC)" https://docs.microsoft.com/en-us/typography/script-development/arabic. Also https://github.com/googlefonts/noto-fonts/issues/2248.

**Comment by rastikerdar** [comment]
Sorry, there is a serious problem in v32.0.0 about kerning in numbers. Any chance to replace the current file 32.0 with new 32.1 before merging?
https://github.com/rastikerdar/vazirmatn/blob/master/fonts/variable/Vazirmatn%5Bwght%5D.ttf
I apologize for the inconvenience. That issue occurred due to different displaying in windows 7, 10, Gnu/Linux and Android. So I removed the kerning tables for numbers. This is the only change.
https://github.com/rastikerdar/vazirmatn/issues/244
@yanone

**Comment by yanone** [comment]
Sure, I'll PR the new files. Thank you.

**Comment by yanone** [comment]
Updated

## Vazirmatn: Version 32.1 added

---
 caa7b00: [gftools-packager] Vazirmatn: Version 32.1 added

* Vazirmatn Version 32.1 taken from the upstream repo https://github.com/rastikerdar/vazirmatn at commit https://github.com/rastikerdar/vazirmatn/commit/70f08bf38a50498bfb96f349f15f8b8ff74e6699.

**Comment by rastikerdar** [comment]
Thanks for publishing Vazirmatn but there are two problems: Kerning and hinting.
I don't see any issue in the file uploaded by @yanone but as you can see in the picture all the kerning values has been set to zero during the font generation by fonts.google.com (why?!). I have used the fontmake tool from Google for generating all weights with no problem In the main repository of Vazirmatn. The very odd point is that when you check the preview in fonts.google.com with Google Chrome browser, kerning values are correct because it seems that the files are different when you see them in Firefox or when you download the family separately. Looks like that the fonts.google.com serves different files for each browser. Anyway kernings are lost by fonts.google.com!

googlefonts-vazirmatn-kerning-issue

googlefonts-vazirmatn-kerning-issue2

The second problem is about hinting. I used ttfautohint for hinting and everything looked fine in the main repository but as you can see in the picture hinting has been destroyed by fonts.google.com!

googlefonts-vazirmatn-hinting-issue

You can compare files by adding them on this page:
https://rastikerdar.github.io/vazirmatn/en/lab

Pictures are in Windows 10

**Comment by yanone** [comment]
Yes, it's possible that Google Fonts API serves different fonts for different browsers. The engineers responsible for this are a different team.

@davelab6 Please advise on how to proceed. It appears this needs to be raised to the API engineers.

**Comment by RosaWagner** [comment]
I opened a new issue, better to discuss the matter there #4463

**Comment by rastikerdar** [comment]
Hello
Sorry, can i request an update for Vazirmatn? Since the latest version on GF (32.102) several bug fixes and design improvements have been made:
- Added Jawi letters
- Added U+06C8 (ۈ) of Uyghur language
- Fixed wrong interpolation of endofproof
- Improved typeface design
- Fixed bugs in some glyphs
- Added missing alternatives for some glyphs
- Improved kerning

Details of changes:
https://github.com/rastikerdar/vazirmatn/releases

The white area is the old version of Vazirmatn:
vazirmatn33

https://github.com/rastikerdar/vazirmatn/tree/master/fonts/variable
Thanks in advance

**Comment by RosaWagner** [comment]
Can you open an issue in the issue tracker ("update" template)? https://github.com/google/fonts/issues

**Pull request merged**
