### PR TITLE
Reem Kufi Ink: Version 1.004 added

### PR DESCRIPTION
**Pull request by m4rc1e**
510ccf7: [gftools-packager] Reem Kufi Ink: Version 1.004 added

* Reem Kufi Ink Version 1.004 taken from the upstream repo https://github.com/aliftype/reem-kufi at commit https://github.com/aliftype/reem-kufi/commit/.

### CODE REVIEW

**Comment by m4rc1e** [comment]
@anthrotype noticed my use of maximum_color was incorrect in the previous pr.

**Review by anthrotype — APPROVED** [review]

**Comment by vv-monsalve** [comment]
> @anthrotype noticed my use of maximum_color was incorrect in the previous pr.

Should this go to Sandbox after #5167 does it?

**Comment by rsheeter** [comment]
> Should this go to Sandbox after https://github.com/google/fonts/pull/5167 does it?

Yes please

**Comment by RosaWagner** [comment]
The version number is the same as previous the onboarded version so I actually don't know if this version went to prod for the colour font launch or not.

**Pull request merged**
