### PR TITLE
Jaini Purva: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by yanone**
47c04b0: [gftools-packager] Jaini Purva: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added

* Jaini Purva Version 1.002; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/EkType/Jaini at commit https://github.com/EkType/Jaini/commit/55c7a9fd70c38b331dc4cfbfab85a49059969e6f.

### CODE REVIEW

**Comment by yanone** [comment]
Missing Latin is sanctioned by Dave: https://github.com/google/fonts/issues/3830#issuecomment-1042421369

Please ignore the dotted circle check, as not even the marks have anchors. They attach by horizontal positioning only.

**Comment by RosaWagner** [comment]
> Missing Latin is sanctioned by Dave: https://github.com/google/fonts/issues/3830#issuecomment-1042421369

Okay. Since the comment is from last February and some requirements have updated for automatic integration to Workspace since, I would like to address it again to be sure. We were pretty strict with other projects.

**Comment by yanone** [comment]
Closing this PR as it was decided that a Latin is going to be commissioned.

**Comment by chrissimpkins** [comment]
Dave weighed in and is ok with publishing this family without Latin

**Comment by RosaWagner** [comment]
Re-closing this PR since in a meeting we agreed a matching latin should commissioned.

**Pull request closed without merging**
