### PR TITLE
amiri: 0.113 added

### PR DESCRIPTION
**Pull request by khaledhosny**
This supersedes https://github.com/google/fonts/pull/2437 and includes fixes for issues reported by Fontbakery.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Any chance for someone to look into this, or should I close this PR in favor of the other one (I opened this mostly to do the changes to the non-font files).

**Comment by khaledhosny** [comment]
Any updates?

**Comment by m4rc1e** [comment]
Since our CI chokes on Amiri's OT features (I reckon there's circular reference amongst lookups), I just found an older version of our diff tooling that will only checks [encoded glyphs](http://45.55.138.144/compare/4a129de1-8a25-41a2-bd4e-1b866d624dfc) everything appears fine so I'm going to merge.



Thanks and apologies for the delay. It will still be around two weeks before it hits the production server.

**Comment by khaledhosny** [comment]
Thanks for checking and merging, much appreciated.

> (I reckon there's circular reference amongst lookups)

Hmm that would be odd, can you give me more details (or where to find them)?

**Pull request merged**
