### PR TITLE
Montserrat: Version 9.000 added



### PR DESCRIPTION
**Pull request by m4rc1e**

### CODE REVIEW

**Comment by m4rc1e** [comment]
Updated

**Comment by emmamarichal** [comment]
Hey @m4rc1e, here you can find my review!

### **Fontbakery:** 
`⚠️ WARN On a family update, the DESCRIPTION.en_us.html file should ideally also be updated.`
- Maybe we should add a sentence about the update? (SSA related)

### **Software**
-> Menus, rendering, kerning, features.

- Word Windows: `ok`
Screenshot 2024-10-09 at 14 15 43

- TextEdit Mac: `ok`
- Word Mac: `ok`
- Indesign Mac: `not ok`
Slider and style don't show up well:
Screenshot 2024-10-09 at 14 03 02
Screenshot 2024-10-09 at 14 03 16

https://github.com/user-attachments/assets/0eb41e9b-1c73-4cb7-ab85-dd35e8303f4a


### **Hinting**
- Here you can find the difference on Windows:

https://github.com/user-attachments/assets/32d8f72e-4046-4ee8-8714-c4ab24fc8e9a

https://github.com/user-attachments/assets/73883034-7ff2-4a72-b9c8-70eb8538389b

### **Bracket layers**
- There are some interpolation issues in the bracket layers (see the generated pdf in the qa), but they don't seem to have any impact on the rendering, so I'll not consider it as a blocker.

https://github.com/user-attachments/assets/5abe9e2a-7952-4618-ba6b-0a80f424002a


- The `ⱦ` bracket layer doesn't work for the small cap version (in normal version and in the stylistic set):
Screenshot 2024-10-09 at 14 01 55


### **Anchors placement**
- The following issues are mostly present in italic too (please check)


Screenshot 2024-10-09 at 14 48 09
Screenshot 2024-10-09 at 14 50 05
Screenshot 2024-10-09 at 14 29 00
Screenshot 2024-10-09 at 14 33 37


- is this bar placement ok?

https://github.com/user-attachments/assets/67158ec7-8fd0-40f6-aa52-9aa02622ddb9



### **Other bugs**
- this switch doesn't look right to me:

https://github.com/user-attachments/assets/1d9c2f19-1393-45b4-939b-8886ea755187


https://github.com/user-attachments/assets/c1b59b9e-2b1a-445c-a37f-7ed2762ba2b9

**Comment by m4rc1e** [comment]
Brilliant review thank you very much! @juandelperal I'll take a look at what could be causing the Indesign issue. Mind looking at the rest?

**Comment by juandelperal** [comment]
Hi Emma, 
Thanks a lot for this super detailed review! Amazing work.
We fixed all the issues you mentioned, like anchor positioning, hcedilla.sc and change the breakpoint of tdiagonalstroke.sc. You can review them from our latest commits.

> is this bar placement ok?

Yes, we designed it to switch the position like that, otherwise the inner counter got covered.

**Other bugs** 
Still, we couldn't reproduce what you mentioned there
We attach some screen recordings from Samsa

https://github.com/user-attachments/assets/eefc50bf-1272-488e-bdf6-09b2f6c939d0


https://github.com/user-attachments/assets/49d8acb8-a4b5-4e02-9539-d439e0897355



**Indesign** 
Is this problem present in the previous version of the family?
We had so many issues with Indesign support for Variable Fonts. I think something worth trying is dropping the stat table to test if the problem persist. Let us know if we can help @m4rc1e

**Comment by emmamarichal** [comment]
Hi @juandelperal, thank you for the update! 

**Bug with** `ⱥ`  **and** `ɇ` **/ small caps activated:**

I saw the problem in Fontgauntlet, and I have it also in Font Goggles and Indesign:
(in bold versions, they should appear as small caps)

Screenshot 2024-10-16 at 11 45 09
Screenshot 2024-10-16 at 11 45 23


**Indesign:**

Good news! The issue seems to be gone with the Indesign upgrade (2025 version `v20.0`). cc @m4rc1e 

**LATIN CAPITAL LETTER T WITH DIAGONAL STROKE**

Some alternate have been drawn for the bolder versions, but they still don't work.

Screenshot 2024-10-16 at 11 51 41
Screenshot 2024-10-16 at 11 51 55

For the default version `Ⱦ`, the alternate works, but when we activate the SS01, with the other `T` shape, we loose the ss01 shape after 700 (bold).

https://github.com/user-attachments/assets/3fdd4903-05a0-4683-bc81-673297a2eb32

**Comment by juandelperal** [comment]
There is also a random bug with the statics, variable version looks fine
https://github.com/JulietaUla/Montserrat/pull/150#issuecomment-2418182355

**Comment by juandelperal** [comment]
Thanks Emma

It seems to be a problem with gftools builder. Here the comparison


https://github.com/user-attachments/assets/5342befe-07ec-411c-83c3-59734e791a6e


https://github.com/user-attachments/assets/21577a2e-ddb6-40af-b3d5-cf135bdaa2b5



We also attach the font generated from glyphs to check
[MontserratVF.ttf.zip](https://github.com/user-attachments/files/17409418/MontserratVF.ttf.zip)

**Comment by emmamarichal** [comment]
Ok I see! Well, I don't think it should be a blocker, @m4rc1e what do you thing?
GlyphsLib had a lot of issues with alternate layers in the past, I'll re-read the issues to see if a solution exists or if the problem have been raised already. 

https://github.com/googlefonts/glyphsLib/issues?q=is%3Aissue%20state%3Aopen%20layer

**Comment by juandelperal** [comment]
Hi Emma and Marc!
We made some fixes. Please update this PR to the last commit before merging.

**Comment by m4rc1e** [comment]
Updated

**Comment by m4rc1e** [comment]
@juandelperal Thank you very much. The pr here now reflects your latest changes.

@emmamarichal Feel free to do another review. I don't mind if skip the review and I'll take another look.

**Comment by emmamarichal** [comment]
New fontbakery check:
`🔥 FAIL Check there are no overlapping path segments`
I tested the concerned glyphs on Chrome, Indesign and PDF (adobe acrobat), and we have no rendering issues. 

`🔥 FAIL Ensure smart dropout control is enabled in "prep" table instructions.`
I more concerned by this one, that was not here before. @m4rc1e?

**Comment by m4rc1e** [comment]
> 🔥 FAIL Check there are no overlapping path segments

I think this check may already be redundant since Chrome 130 has fixed it.

> 🔥 FAIL Ensure smart dropout control is enabled in "prep" table instructions.

This shouldn't be enabled since the font is manually hinted.

**Review by emmamarichal — APPROVED** [review]

**Pull request merged**
