### PR TITLE
inter: v3.19 added

### LINKED ISSUE #2386: Inter fonts lacks italics

### PR DESCRIPTION
**Pull request by m4rc1e**
Taken from https://github.com/rsms/inter/releases/download/v3.19/Inter-3.19.zip

@valerie-makes thanks for submitting #4149. I've decided to make a new PR since I have the correct permissions to open up a pr directly from this repo. This allows our CI to run correctly.

Fixes #2386

### CODE REVIEW

**Comment by valerie-makes** [comment]
@m4rc1e it may be helpful adding "Fixes #2386" to the PR description :)

**Comment by RosaWagner** [comment]
It looks like nameID6 is taking name ID 25+2 instead of name ID 1+2. The latter would avoid post-script name regression.

**Comment by davelab6** [comment]
@RosaWagner Yes, Adobe Fonts has asked us to be VERY careful about changes to PS names. If we can avoid it, we should. 
 So, @felipesanches what is the status of the fontbakery check for this? That is urgent to be into everyone's process. 
 
 @m4rc1e Since the `slnt` axis for this family was already added (like for [Recursive](https://github.com/google/fonts/tree/main/ofl/recursive) then I think as an exception we do not want to add our own forked Italic file, as in this PR, because that will complicate untangling the slnt axis. We'll need to discuss the case of these 2 fonts with the GF Eng team, since making some "italic" styles available to Workspace users is important, but there are deeper problems with how slnt, font-style, etc work. 
 
@RosaWagner please could you explain your ideas about how to to proceed here?

**Comment by RosaWagner** [comment]
I tested it and it works fine in app that doesn't have a good support of the slant axis, but it bugs in apps that does have a "good" support slant axis. So this is a bad idea. I don't see much solution here to avoid regression on the user end, except for onbaording it under another name.

**Pull request merged**
