### PR TITLE
Hahmlet: Version 1.001; ttfautohint (v1.8.3) added

### PR DESCRIPTION
**Pull request by aaronbell**
c82e525: [gftools-packager] Hahmlet: Version 1.001; ttfautohint (v1.8.3) added

* Hahmlet Version 1.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/hyper-type/hahmlet at commit https://github.com/hyper-type/hahmlet/commit/a39720495ab527f03c2b893321263993bc3096e3.

### CODE REVIEW

**Comment by RosaWagner** [comment]
By the way, the font looks good to me. I am just curious about this fail which doesn't appear in other VF, and is not related to the name written in another script than latin:

```
🔥 FAIL: METADATA.pb font.full_name and font.post_script_name fields have equivalent values ?
🔥 FAIL METADATA.pb font full_name = "Hahmlet" does not match post_script_name = "Hahmlet-Roman" [code: mismatch]
```

**Comment by aaronbell** [comment]
@RosaWagner Ahh. I had copied some code from another script to adjust the font naming and overlooked that naming convention being added as well. I can easily change it back. That said, as an FYI, this sort of naming convention is actually pretty common when the variable font family also contains an Italic as a separate font file as it helps differentiate the two. 

@m4rc1e Do you have a preference about the use of Roman in the postscript name here? Might this run afoul of Google's "there must be a Regular for every font" rule?

**Comment by RosaWagner** [comment]
@aaronbell We put `Roman` in the nameID 25, and leave 1 to 22 as usual. `gftools builder` is setting up the names so we don't have to script it.

**Comment by aaronbell** [comment]
Thanks @RosaWagner, interesting. I followed the model that I saw in Source Code Mono, which included updates to `6` and `17` as well.

**Comment by RosaWagner** [comment]
Ah, Source Code Mono might a bit old, we are figuring stuff on the go. Also the way we do right now may change in the future ^^ but [Texturina](https://github.com/Omnibus-Type/Texturina) is the one we use as example now for building process.

**Comment by aaronbell** [comment]
Updated

## Hahmlet: Version 1.001; ttfautohint (v1.8.3) added

---
 4288769: [gftools-packager] Hahmlet: Version 1.001; ttfautohint (v1.8.3) added

* Hahmlet Version 1.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/hyper-type/hahmlet at commit https://github.com/hyper-type/hahmlet/commit/98a376949035fe079839c17ad95db7917ec35ef4.

**Comment by aaronbell** [comment]
Updated variable font with modified name.

**Comment by aaronbell** [comment]
@m4rc1e ready for review :)

**Comment by m4rc1e** [comment]
Desktop_Windows_10_chrome_71 0_

This looks great!

Is this a VF Hangul font? if so, I'm very impressed.

**Comment by m4rc1e** [comment]
LGTM as well so let's merge.

**Comment by aaronbell** [comment]
Yup. Static and variable, just for you! :)

**Pull request merged**
