### PR TITLE
MuseoModerno: Version 1.003 added

### PR DESCRIPTION
**Pull request by emmamarichal**
772d883: [gftools-packager] MuseoModerno: Version 1.003 added

* MuseoModerno Version 1.003 taken from the upstream repo https://github.com/Omnibus-Type/MuseoModerno at commit https://github.com/Omnibus-Type/MuseoModerno/commit/ad2f135bea4525cf6d1f14d488593c0fc6ef82db.

 43d5cbe: Description updated according the update

### CODE REVIEW

**Comment by RosaWagner** [comment]
@m4rc1e we have this fail although the name table looks fine. Do you know if it's a problem from FB or from the font?

🔥 FAIL: Validates that when an instance record is included for the default instance, its subfamilyNameID value is set to either 2 or 17, and its postScriptNameID value is set to 6. ([com.adobe.fonts/check/varfont/valid_default_instance_nameids](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.adobe.fonts/check/varfont/valid_default_instance_nameids))
🔥 FAIL 'Thin' instance has the same coordinates as the default instance; its subfamilyNameID should be either 2 or 17, instead of 257. [code: invalid-default-instance-subfamily-nameid:257]
🔥 FAIL 'Thin' instance has the same coordinates as the default instance; its postScriptNameID should be 6, instead of 266. [code: invalid-default-instance-postscript-nameid:266]

**Comment by emmamarichal** [comment]
@RosaWagner @m4rc1e 
I'm working on another font that has the same kind of design space, and I also have these fails, but not on the roman, only on the italic (except for the last one)
I checked, and the instances and the stat table are configured exactly the same between roman and italic.
So maybe it's a fontbakery problem?


</div></details><details><summary>🔥 <b>FAIL:</b> The variable font 'wght' (Weight) axis coordinate must be 400 on the 'Regular' instance. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/regular_wght_coord">com.google.fonts/check/varfont/regular_wght_coord</a>)</summary><div>


* 🔥 **FAIL** The "wght" axis coordinate of the "Regular" instance must be 400. Got None instead. [code: wght-not-400]
</div></details><details><summary>🔥 <b>FAIL:</b> The variable font 'wdth' (Width) axis coordinate must be 100 on the 'Regular' instance. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/regular_wdth_coord">com.google.fonts/check/varfont/regular_wdth_coord</a>)</summary><div>


* 🔥 **FAIL** The "wdth" axis coordinate of the "Regular" instance must be 100. Got None as a default value instead. [code: wdth-not-100]
</div></details><details><summary>🔥 <b>FAIL:</b> The variable font 'wght' (Weight) axis coordinate must be 700 on the 'Bold' instance. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.google.fonts/check/varfont/bold_wght_coord">com.google.fonts/check/varfont/bold_wght_coord</a>)</summary><div>


* 🔥 **FAIL** The "wght" axis coordinate of the "Bold" instance must be 700. Got None instead. [code: wght-not-700]
</div></details><details><summary>🔥 <b>FAIL:</b> Validates that when an instance record is included for the default instance, its subfamilyNameID value is set to either 2 or 17, and its postScriptNameID value is set to 6. (<a href="https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/fvar.html#com.adobe.fonts/check/varfont/valid_default_instance_nameids">com.adobe.fonts/check/varfont/valid_default_instance_nameids</a>)</summary><div>


* 🔥 **FAIL** 'Italic' instance has the same coordinates as the default instance; its subfamilyNameID should be either 2 or 17, instead of 258. [code: invalid-default-instance-subfamily-nameid:258]
* 🔥 **FAIL** 'Italic' instance has the same coordinates as the default instance; its postScriptNameID should be 6, instead of 264. [code: invalid-default-instance-postscript-nameid:264]
</div></details>

**Comment by RosaWagner** [comment]
I checked the font and didn't find any problem with the italic, please open an issue in Fontbakery. Maybe someone can help us figuring this out there.

**Comment by emmamarichal** [comment]
https://github.com/googlefonts/fontbakery/issues/3818

**Pull request merged**
