### PR TITLE
Noto Sans Thai Looped: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
91b958d: [gftools-packager] Noto Sans Thai Looped: Version 1.001; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Thai Looped Version 1.001; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/thai.git at commit https://github.com/notofonts/thai/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
Need to re-add article.

**Review by m4rc1e — COMMENTED** [review]
Double stacking marks appear broken

Before:

Screenshot 2022-08-23 at 10 13 12


After:

Screenshot 2022-08-23 at 10 13 19

Latin has also been removed but I'm guessing this is intentional

**Comment by m4rc1e** [comment]
Here's the test doc which diffenator2 generated:

[thai_looped.zip](https://github.com/google/fonts/files/9401190/thai_looped.zip)

**Comment by simoncozens** [comment]
Latin should be added, not removed! I’ll check the stacking diacritics since that was the issue I was trying to fix…

**Comment by m4rc1e** [comment]
@simoncozens apologies. I had the fonts the wrong way round for making the diff. So in other words, you've fixed the double stacks and added the Latin.

**Review by m4rc1e — APPROVED** [review]
LGTM. Apologies for the confusion earlier. Latest diffs attached.

[thai_looped2.zip](https://github.com/google/fonts/files/9401567/thai_looped2.zip)

**Pull request merged**
