### PR TITLE
Edu VIC WA NT Pre Guide: Version 1.000 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/SorkinType/VICWANTSchoolHandAustralia at commit https://github.com/SorkinType/VICWANTSchoolHandAustralia/commit/abab94d19985f24132e45db4c4822b042eb63302.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
~- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects~
~- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target~
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 **FAIL** Whitespace glyphs have ink?

This Fail can be ignored since this is the guide variant, so the space is also expected to have outlines.

**Comment by vv-monsalve** [comment]
Same question about the top guide
Screen Shot 2024-04-04 at 20 03 52

**Comment by vv-monsalve** [comment]
The Top Guide position was confirmed to be ok [here](https://github.com/google/fonts/pull/7452#issuecomment-2038616232)

**Comment by simoncozens** [comment]
Do not push; in fact, we will revert. We went too fast here, and need to make the naming consistent ("Guides").

**Pull request merged**
