### PR TITLE
Added a otf format font

### PR DESCRIPTION
**Pull request by anubhav4sachan**
Added Open Source font under Apache license used regularly by @CCNITSilchar and related organizations in National Institute of Technology, Silchar to this great fonts repository

### CODE REVIEW

**Comment by anubhav4sachan** [comment]
I signed it!

**Comment by m4rc1e** [comment]
I can't figure out the license for this family. Where did you find the Apache license info?

**Comment by anubhav4sachan** [comment]
The explicit license isn't available. But the author has posted that this font-family is available for commercial use. https://befonts.com/playlist-script-font.html

**Comment by m4rc1e** [comment]
I don't think it's safe to assume a license type for a project we don't own. I'll send the author an email.

**Comment by anubhav4sachan** [comment]
Yes, I agree with you. Contacting him directly is the best option.

**Comment by davelab6** [comment]
@anubhav4sachan thanks for your enthusiasm, but only the copyright holder(s) can apply a new license. We'll need them to confirm, and we now only accept fonts under the SIL Open Font License, per https://github.com/google/fonts/blob/master/CONTRIBUTING.md

**Comment by davelab6** [comment]
@anubhav4sachan I'm going to close this, please follow the process described in https://github.com/google/fonts/blob/master/CONTRIBUTING.md - file an issue with a link to the projects github repo with the OFL license.

**Pull request closed without merging**
