### PR TITLE
Anek Bangla: Version 1.003 added

### PR DESCRIPTION
**Pull request by yanone**
39ddee6: [gftools-packager] Anek Bangla: Version 1.003 added

* Anek Bangla Version 1.003 taken from the upstream repo https://github.com/EkType/Anek at commit https://github.com/EkType/Anek/commit/34074c6b406f4112e20c7ad10254a6e954d0324b.

 39184a5: [gftools-packager] ofl/anekbangla remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by yanone** [comment]
Updated

## Anek Bangla: Version 1.003 added

---
 29d3467: [gftools-packager] Anek Bangla: Version 1.003 added

* Anek Bangla Version 1.003 taken from the upstream repo https://github.com/EkType/Anek at commit https://github.com/EkType/Anek/commit/34074c6b406f4112e20c7ad10254a6e954d0324b.

 dfc06e2: [gftools-packager] ofl/anekbangla remove METADATA "source".  google/fonts#2587

**Comment by m4rc1e** [comment]
What version of gftools are you running, do `gftools --version`?

Seems you're stripping out the language comments in the METADATA.pb files.

**Comment by yanone** [comment]
0.8.8

I tried both the pypi and the latest github code. Both produce the same result

**Comment by m4rc1e** [comment]
Strange. I've just run `gftools packager "Anek Bangla" path/to/my/google/fonts` and it didn't strip out the language comments.

**Comment by yanone** [comment]
Updated

## Anek Bangla: Version 1.003 added

---
 9bc3ec7: [gftools-packager] Anek Bangla: Version 1.003 added

* Anek Bangla Version 1.003 taken from the upstream repo https://github.com/EkType/Anek at commit https://github.com/EkType/Anek/commit/34074c6b406f4112e20c7ad10254a6e954d0324b.

 c6840a6: [gftools-packager] ofl/anekbangla remove METADATA "source".  google/fonts#2587

**Comment by yanone** [comment]
Updated

## Anek Bangla: Version 1.003 added

---
 5ab35e8: [gftools-packager] Anek Bangla: Version 1.003 added

* Anek Bangla Version 1.003 taken from the upstream repo https://github.com/EkType/Anek at commit https://github.com/EkType/Anek/commit/34074c6b406f4112e20c7ad10254a6e954d0324b.

**Pull request merged**
