### PR TITLE
Update ChocolateClassicalSans-Regular.ttf

### PR DESCRIPTION
**Pull request by aaronbell**
Updated font to include vmtx and vhea tables. 

(data was in the font, but due to the metadata missing in the fontinfo file, fontmake was not generating the tables. This has now been corrected). See #8694

### CODE REVIEW

**Comment by emmamarichal** [comment]
Hi @aaronbell,

I used the html sample to test it:

```
<html>
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Cactus+Classical+Serif&family=Chocolate+Classical+Sans&family=LXGW+WenKai+TC&display=swap" rel="stylesheet">
        <style>
            body {
                writing-mode: vertical-rl;
                font-family: "Chocolate Classical Sans";  //change the font-family here
                font-size: 20pt;
                padding: 1em;
            }
        </style>
    </head>
    <body>
        <h1>漢字</h1>
        <p>
            漢字，又稱漢文、華文、中文、華語字、唐話字、唐人字、中國字，是書寫漢語所使用的文字系統，也是現今世界上唯一仍廣泛使用的語素文字，主要流行於漢字文化圈（特別是大中華地區），也是聯合國四種官方文字之一（另外三種皆為拼音文字，分別是英語、法語與西班牙語使用的拉丁文字、俄語使用的西里爾文字和阿拉伯語使用的阿拉伯文字）。
        </p>
        <p>
            漢字是世界歷史上唯一被高度發展的語素文字，從基礎的象形字和指事字發展出了現今以形聲字和會意字為主流的六書系統，加上各類異體字和生僻字在所有字典中總共收錄超過十萬字。每個漢字在結構上由最基礎的筆畫進行二維排列組成，每個筆畫不包含任何語素，相當於表音文字的字母；由筆畫組成的偏旁部首是漢字內部結構上的最小語素單位，相當於一些表音文字的詞根。除形聲字外的漢字通常不具備音素，而形聲字的聲旁則帶有一定表音功能，但因為其大多基於上古漢語的發音所以與現代標準漢語有一些差異。現今漢字通常使用額外獨立的標音幫助閱讀，在中華民國時期主要使用注音符號，但在台灣以外的地區（特別是中國大陸）主要使用拉丁化的漢語拼音。雖然絕大多數漢字單字都擁有自身的獨立含義，在語法上相當於英文的單詞，但漢語詞彙通常都是由兩個以上單字組成的合成詞。
        </p>
    </body>
</html>
```

But I have the feeling that nothing changed, compared to the current live version:
Screenshot 2024-12-12 at 10 47 33

I maybe missed something in my test, CJK are still a bit complicated to review haha
Let me know!

**Comment by emmamarichal** [comment]
LGTM!

### **Before**
Screenshot 2024-12-12 at 10 58 58

### **After**
Screenshot 2024-12-12 at 10 58 53

**Comment by emmamarichal** [comment]
@aaronbell, I see some tofu in dev-sandbox. But nothing changed in sources regarding language support, can you confirm?
Otherwise, I guess there were a sample update somewhere

### **Dev-sandbox version:**
Screenshot 2024-12-12 at 15 00 03

### **API version**
Screenshot 2024-12-12 at 14 59 58

**Comment by aaronbell** [comment]
Nope, zero change to the language coverage. Actually, it looks like the same glyphs are missing as were missing in Iansui. So I’m guessing there’s a glyphset problem on dev?

**Comment by chrissimpkins** [comment]
I'm under the impression that this is in prod but it is labeled dev.  Possible to confirm @emmamarichal ?

**Comment by emmamarichal** [comment]
@chrissimpkins No, it's still on the dev-sandbox, and it shows tofu. I'll investigate with @garretrieger!


Screenshot 2025-03-06 at 13 47 28

**Pull request merged**
