### PR TITLE
barlow family to v1.408

### PR DESCRIPTION
**Pull request by jpt**
This is a few versions ahead now, fixes a number of issues, some small some big (see jpt/barlow/releases)

### CODE REVIEW

**Comment by m4rc1e** [comment]
Hey @jpt thank you for the pr!

We need the metadata.pb file regenerated with https://github.com/googlefonts/tools/blob/master/bin/gftools-add-font.py

and an FB report https://github.com/googlefonts/fontbakery for each family.

@davelab6 this is the perfect opportunity to get a 3rd party to try out our tools.

**Comment by jpt** [comment]
Cool!

Some notes and questions:

### gftools

The add-font script reports the following when run with the --update flag:

```
No change to ../fonts/ofl/barlow/METADATA.pb
No change to ../fonts/ofl/barlowcondensed/METADATA.pb
No change to ../fonts/ofl/barlowsemicondensed/METADATA.pb
```

If I delete and regenerate, it loses "Designer name" and updates the date created but otherwise doesn't change. I manually changed the designer name and will commit the files with the new dates, anything I can do to get "Designer name" working automatically?

A couple notes RE: 3rd parties testing the tool :)

- I think it's possible https://github.com/googlefonts/tools/blob/master/.gitmodules#L2 (`path = util/GlyphsInfo`) needs to change to `path = Lib/gftools/util/GlyphsInfo`

- It might make sense to explicitly state in the readme that gftools needs to be run from the repo's root path (otherwise the `encodings` directory isn't found)

### FontBakery

It's weird, sometimes it hangs, sometimes it doesn't. What verbosity flags should I be running it with and how should I actually deliver the report? The JSON export thing or just write STDOUT to a file?

**Comment by davelab6** [comment]
Don't change the date, it's for when the fonts were added. Marc, why did
you request this? Did a tool not pick it up?

**Comment by m4rc1e** [comment]
@davelab6 Helps us identify areas where our documentation is lacking.

**Comment by jpt** [comment]
@m4rc1e What command line args did you pass to generate the FB report in google/fonts/pull/1280?

**Comment by m4rc1e** [comment]
```
fontbakery-check-googlefonts.py [fonts.ttf]
```

**Comment by m4rc1e** [comment]
@jpt Version number has not advanced. Fonts still have v1.01 in them.

**Comment by m4rc1e** [comment]
@davelab6 Here's what we really want to see.

In this PR, Barlow renders exactly the same as the version on Google Fonts.

```
Regression Report:

Fonts: ["Barlow-Black.ttf", "Barlow-BlackItalic.ttf", "Barlow-Italic.ttf", "Barlow-Regular.ttf", "Barlow-Thin.ttf", "Barlow-ThinItalic.ttf"]

View: glyphs-modified
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same

View: waterfall
PASSED: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is the same
PASSED: Desktop_Windows_7_ie_9.0_.jpg is the same
PASSED: Desktop_Windows_7_chrome_50.0_.jpg is the same
PASSED: Desktop_Windows_10_edge_15.0_.jpg is the same
PASSED: Desktop_Windows_7_firefox_45.0_.jpg is the same
```

**Win 7 IE 9**
desktop_windows_7_ie_9 0_



[1330_barlow_img.zip](https://github.com/google/fonts/files/1482140/1330_barlow_img.zip)

**Comment by jpt** [comment]
@m4rc1e That's odd. If I download https://github.com/jpt/fonts/blob/313ba27f87d6d4b183a5c1313d034d1e12315218/ofl/barlow/Barlow-Black.ttf

I see v1.200:

screen shot 2017-11-17 at 4 03 50 am

Also, in the above images (which I think maybe are v1.101 -- I can't explain why you've got that version), even on 1.200, the only difference that should exist is on /p/d/q/b spacing at the Regular width Black weight and even then it's pretty small. Most of the other changes are to non-English characters. There's a full rundown at https://github.com/jpt/barlow/releases

**Comment by m4rc1e** [comment]
@jpt you're correct, git fetch was off here. Let me redo this.

**Comment by jpt** [comment]
Aha, thanks!

**Comment by m4rc1e** [comment]
## Glyph Changes since previous release

desktop_os_x_el_capitan_safari_9 1_

You've broken ij :-)

I see you've improved the obliques by offering changing the 'a' to single story? I don't know how I feel about this given the recent outcries.

## Rendering diffs
```
View: waterfall
WARNING: Desktop_OS_X_El_Capitan_safari_9.1_.jpg is different by 253359 pixels
WARNING: Desktop_Windows_7_ie_9.0_.jpg is different by 263878 pixels
WARNING: Desktop_Windows_7_chrome_50.0_.jpg is different by 243100 pixels
WARNING: Desktop_Windows_10_edge_15.0_.jpg is different by 217867 pixels
WARNING: Desktop_Windows_7_firefox_45.0_.jpg is different by 170262 pixels
```
**Win 7 ie 11**
desktop_windows_7_ie_9 0_

I see no x-height jumps, just horizontal spacing changes.

[1330_barlow_img.zip](https://github.com/google/fonts/files/1482277/1330_barlow_img.zip)

**Comment by m4rc1e** [comment]
You've also changed some of the metadata around. Here's an FB report of just the failing tests.

```
There is a total of 120 tests on <Section: Default>.
Start ... running 590 individual test executions.
>> com.google.fonts/test/040 with ((u'font[0]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Black.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/040 with ((u'font[1]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-BlackItalic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/040 with ((u'font[2]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Italic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/040 with ((u'font[3]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Regular.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/020 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Thin.ttf'),)
   Checking OS/2 usWeightClass
 * FAIL: OS/2 usWeightClass expected value for 'Thin' is 250 but this font has 100.

   Result: FAIL

>> com.google.fonts/test/040 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Thin.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/112 with ((u'font[4]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-Thin.ttf'),)
   Checking OS/2 usWeightClass matches weight specified at METADATA.pb
 * FAIL: OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (100:"Thin").

   Result: FAIL

>> com.google.fonts/test/020 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-ThinItalic.ttf'),)
   Checking OS/2 usWeightClass
 * FAIL: OS/2 usWeightClass expected value for 'Thin' is 250 but this font has 100.

   Result: FAIL

>> com.google.fonts/test/040 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-ThinItalic.ttf'),)
   Checking OS/2 usWinAscent & usWinDescent
 * FAIL: OS/2.usWinAscent value should be 983, but got 981 instead [code: ascent]
 * FAIL: OS/2.usWinDescent value should be 211, but got 271 instead [code: descent]

   Result: FAIL

>> com.google.fonts/test/112 with ((u'font[5]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlow/Barlow-ThinItalic.ttf'),)
   Checking OS/2 usWeightClass matches weight specified at METADATA.pb
 * FAIL: OS/2 usWeightClass (100:"bad Google Fonts API weight value") does not match weight specified at METADATA.pb (100:"Thin").

   Result: FAIL

======== <Section: Default> ========
590 tests in section


Section results:

    ERROR: 0
    FAIL: 10
    WARN: 49
    SKIP: 12
    INFO: 26
    PASS: 493

======== END <Section: Default> ========

Total:

    ERROR: 0
    FAIL: 10
    WARN: 49
    SKIP: 12
    INFO: 26
    PASS: 493


DONE!


```

**Comment by jpt** [comment]
@m4rc1e 

>You've broken ij :-)

Yikes, so I have. Looks like I screwed up /W or /A kerning too.

> I see you've improved the obliques by offering changing the 'a' to single story? I don't know how I feel about this given the recent outcries.

Huh, that was supposed to be in, previously, but I bet my previous Glyphs version had a broken TTF export. I didn't realize it was a contentious issue 😅 Outcries be damned -- Barlow started with the single story /a in Roman. I think that's ultimately why it ended up in the oblique -- "well, as long as I have it..."

Looks like a fix that was recently made in Glyphs recently broke something else with the components I use in /p/d/b/q, too, especially noticeable at Regular ExtraBold and Black:

screen shot 2017-11-17 at 4 30 43 am

I'll poke around at it.... I bet it's because I had created a bunch of brace layers specifically for GX export to compensate for a bug in a previous Glyphs version (/jpt/barlow/issues/8#issuecomment-315069663).

I'll tick the version up one and push another commit to this PR once I've got that sorted...

**Comment by jpt** [comment]
> I'll poke around at it.... I bet it's because I had created a bunch of brace layers specifically for GX export to compensate for a bug in a previous Glyphs version

Yep, this was the culprit for all sorts of breakage. I can't reproduce the WA kerning up there... v1.201 should fix all the above though. 

@m4rc1e The files to look at are now at 42358d9 :)

**Comment by m4rc1e** [comment]
Thanks, I'll probably check this out on Monday.

Did you get the chance to play with FontBakery?

**Comment by jpt** [comment]
@m4rc1e Yeah, have tested the fonts and got the same failures you mentioned above, I'll work on fixing the metadata stuff. 

I'm also seeing a few more failures, though -- xAvgCharWidth seems to be a problem, as well as style name length and some other things -- are your results different or are some of these failures more ignorable than others? 

Also -- is there a "GF official" way of generating TTFs from a Glyphs file? I seem to remember there was some sort of command line tool, could be useful for figuring out why things like the font weight metadata have changed btwn versions because I suspect some of these problems have been Glyphs export issues

**Comment by davelab6** [comment]
Fontmake is the compiler you are thinking of, although it doesn't support
100% of the Glyphsapp format.

**Comment by jpt** [comment]
@davelab6 Ah, thanks. Looks like it is not working at all with files saved by the latest Glyphs version (there's already an issue open - googlei18n/fontmake/issues/374)

Difficult time to be a Glyphs user... 2.4.2-stable required the brace layer hack for VF (jpt/barlow/issues/8); 2.4.4-stable (current) requires not having the VF hack and has a different problem with transformation filters running before decomposing glyphs; and 2.5b-edge seems to have some issues related to a change between camelcase and lowercase metadata...

**Comment by jpt** [comment]
Ok, bumped it up to v1.202 (https://github.com/jpt/barlow/releases/tag/v1.202)

As of c7d87ed metadata should be fixed. Seems like FB looks at weightClass but gftools creates the METADATA file with Axis Location? So still no change to METADATA.pb, even though the Thin weight is passing FB test now. 

Tests (note that I don't have all dependencies yet so I may have more errors or failures)

[barlow.fb.txt](https://github.com/google/fonts/files/1492806/barlow.fb.txt)
[barlowcondensed.fb.txt](https://github.com/google/fonts/files/1492807/barlowcondensed.fb.txt)
[barlowsemicondensed.fb.txt](https://github.com/google/fonts/files/1492808/barlowsemicondensed.fb.txt)

**Comment by Simek** [comment]
Refs #1414 - Update Barlow font family (1.101-Pre Release -> 1.208)

**Comment by jpt** [comment]
#1414 is a dupe of this PR -- just pushed up binaries for v1.300. I would run fontbakery myself but unfortunately I'm having trouble with some of the dependencies (it can't seem to recognize where ttfautohint or ots-sanitize are, for example)

**Comment by Simek** [comment]
Fontbakery log for 1.300 could be found here (script has been run for all TTF files in release):
https://gist.github.com/Simek/b8d0e74e95785f3563382b869b92b872

**Comment by jpt** [comment]
Thank you @Simek! 

> OS/2.usWinAscent value should be equal or greater than 1120, but got 1112 instead

Ok this means I need to either fix a glyph or fix some metadata and there will be a 1.301, this is occurring at regular width medium weight and heavier..

**Comment by Simek** [comment]
@jpt Sorry for deleting my comment, but I was working on some missing libraries. I've managed to resolve all dependency issues but `ot-sanitiser` which fails on make.

Here is updated log for 1.300:
https://gist.github.com/Simek/b8d0e74e95785f3563382b869b92b872

**Comment by jpt** [comment]
Yeah the culprit is Abrevehookabove, I have fixed it with an improved brevecomb. 
I will push up a new one shortly

**Comment by jpt** [comment]
OK @Simek I've got this to where the winAscent and winDescent are not creating errors in FontBakery. CC: @m4rc1e @davelab6 - this (1.301) PR closes jpt/barlow#14 jpt/barlow#15 and jpt/barlow#22

**Comment by Simek** [comment]
@jpt Good job with 1.4 changes! @davelab6 Any ETA on merge/feedback?

**Comment by m4rc1e** [comment]
I'll take a look at this soon.

**Comment by m4rc1e** [comment]
@jpt Thank you for the initiative and sending a pretty polished pr. I commend your efforts to make our lives easier and understand our tooling.

Design changes LGTM.

desktop_windows_7_ie_9 0_

desktop_windows_7_ie_9 0_


desktop_windows_7_ie_9 0_

Let me do one final pass on the modified glyphs

**Comment by m4rc1e** [comment]
We have an issue with uni021b.

desktop_windows_7_ie_9 0_

**GFR**
http://www.gf-regression.com/compare/c9c413ea-e564-4f09-9a77-e1aa2cdeb9de

**Comment by jpt** [comment]
@m4rc1e ah yes, I will do a 1.401 for uni021b. I think I also need to add a brace layer on the dot combine because I made it smaller at black but hadn't noticed how much it affected it at lighter weights. Also think I made approxequal worse for no good reason 😅

**Comment by m4rc1e** [comment]
@jpt could you also regen the METADATA.pb files for each dir?

I suspect we may have more codepages covered now.


To do this, install https://github.com/googlefonts/tools

Then run

```
python bin/gftools-add-font.py --update fonts/ofl/barlowdir
```

for each barlow family dir.

Cheers

**Comment by jpt** [comment]
Haven't had a chance to run the metadata stuff yet, but just bumped binaries to fix tcaron, uni021b, and tabular figures (which I had forgotten to compile OT features on)

**Comment by silvioboehme** [comment]
@jpt thank for your great work.
Is there any feedback regarding merge/release on google font?

Google Font is still version 1 from Okt. 2017

**Comment by jpt** [comment]
@silvioboehme Thanks for the reminder!

@m4rc1e / cc @davelab6: -- I ran the GF tools metadata update, all that has changed is the addition of `subsets: "vietnamese"` to each METADATA.pb file (https://github.com/google/fonts/pull/1330/commits/c4b2aeeda301b2194e32018d0cb74f161ec4e9ad)

Let me know if anything else is needed from me to move the PR along :)

**Comment by m4rc1e** [comment]
Update LGTM!

desktop_windows_7_ie_9 0_

@davelab6 I'll get you some FB reports and this can be merged

**Comment by jpt** [comment]
Thanks for your patience and for getting involved, @silvioboehme! I think we are very close. 

@m4rc1e & @davelab6 -- is there anything I can do to help move this along?

**Comment by Simek** [comment]
@m4rc1e & @davelab6 bump?

**Comment by m4rc1e** [comment]
Looking at this today.

**Comment by m4rc1e** [comment]
@jpt Only issue I could find metadata wise was for Barlow Semi Condensed ExtraLightItalic. Its win family name is _Barlow Semi Condensed ExLight_ we want _Barlow Semi Condensed ExtraLight_

```
>> com.google.fonts/check/157 with (('font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlowsemicondensed/BarlowSemiCondensed-ExtraLightItalic.ttf'),)
   Check name table: FONT_FAMILY_NAME entries.
 * FAIL: Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Barlow Semi Condensed ExtraLight' but got 'Barlow Semi Condensed ExLight'.

   Result: FAIL

```

I'll generate some diffs to see if anything as visually changed.

**Comment by m4rc1e** [comment]
@jpt Checkout the following:

**Black**
kerns_missing
I would expect kerns for AW, AV. Not for dcaron which this solves.

We also have some x-height cap height jumps at larger sizes in Direct Write Browsers such as Win10 Chrome 67

desktop_windows_10_chrome_69 0_
_Win 10 Chrome 67_

Jumps at 21pt.

This is happening because you're generating the fonts with a newer version of Glyphsapp which in turn  has a newer version of ttfautohint (1.8 I think). I reckon this family was originally autohinted with ttfautohint v1.6. @davelab6 this family is requested 40m times a week. I think the jumps are ok for this amount of users.

@jpt  I'll send you a mail with all the diff images now

cc @davelab6

**Comment by davelab6** [comment]
The After images look better to me so this is a go from me

**Comment by jpt** [comment]
@m4rc1e Correct, generated with a more recent Glyphsapp and therefore ttfautohint. I'll review the dcaron, AW/AV kerning as I'm less clear on what happened there.

**Comment by jpt** [comment]
@m4rc1e Ok, I've fixed the dcaron and AV kerning locally, but before I push another set of binaries I am still having an issue with the name table for Windows.

> com.google.fonts/check/157 with (('font[7]', '/Users/marc/Documents/googlefonts/fonts/ofl/barlowsemicondensed/BarlowSemiCondensed-ExtraLightItalic.ttf'),)
>    Check name table: FONT_FAMILY_NAME entries.
>  * FAIL: Entry [FONT_FAMILY_NAME(1):WINDOWS(3)] on the 'name' table: Expected 'Barlow Semi Condensed ExtraLight' but got 'Barlow Semi Condensed ExLight'.
> 
>    Result: FAIL
> 

I believe Glyphs shortens names for compatibility reasons. Is it possible fontbakery check 157 is looking at nameID 1 (the name that Glyphs shortens -- "Barlow Semi Condensed ExLight"), when its intention might be to look at nameID 4 instead (full font name, "Barlow Semi Condensed ExtraLight") which I presume is what's shown to the user)? Or does the GF API require that they are the same?

In any case I tried overriding it with custom name table parameters, with no luck. Bumped an old Glyphsapp thread about it -- https://forum.glyphsapp.com/t/font-name-limitations/2918/6

**Comment by davelab6** [comment]
This has been pending for over a year, so I'm going to merge this and get it pushed to production, and the next version that addresses that 1 remaining NAME table issue can be pushed in 2019 :)

**Pull request merged**
