### PR TITLE
Briem Hand: Version 1.004 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/SorkinType/Briem-Hand at commit https://github.com/SorkinType/Briem-Hand/commit/68fedd7eb5d65c2c1490300719ef8b1fa51fbcd5.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
`gunnlaugerbriem` is in the designers catalogue, but I think we want to change this to use the full name (Gunnlauger SE Briem).

**Review by m4rc1e — APPROVED** [review]
Thanks man!

Only suspicious looking glyph is 

Screenshot 2024-05-15 at 13 36 43

I get the impression this was removed from the font?

If the glyph was removed on purpose, feel free to merge.

**Comment by emmamarichal** [comment]
lgtm! except this one:

Screenshot 2024-05-15 at 17 15 55

**Comment by emmamarichal** [comment]
@simoncozens  I don't understand where the warn is coming from, because we use the right name in the catalogue: https://fonts.google.com/specimen/Briem+Hand/about?query=Gunnlaugur+SE+Briem

I remember I added the 'SE' in the PR: https://github.com/google/fonts/pull/7475

**Comment by simoncozens** [comment]
Fontbakery bug, we check for the designer being in the catalogue by normalizing the designer's name ("Gunnlaugur SE Briem" -> "gunnlaugursebriem") and then looking for that directory in the repository (`catalog/designers/gunnlaugursebriem`).

This normally works, but in this case we don't have that directory - it is called `gunnlaugurbriem` instead, so the designer is not found. We should check through the catalogue and see if the name is present or not.

**Comment by simoncozens** [comment]
This one's also pretty bad...
briem

Fix coming...

**Comment by emmamarichal** [comment]
Ah I saw that, but I think the update is the good design. to confirm!

**Comment by emmamarichal** [comment]
Status: We don't merge that PR, until we have the confirmation and the review of the designer.

**Comment by davelab6** [comment]
> We don't merge that PR, until we have the confirmation and the review of the designer.

This may be too conservative, we can merge the PR and get to sandbox, but we should wait for designer approval before going to prod :)

**Comment by davelab6** [comment]
Thanks @emmamarichal :) Good to get this refreshed on sandbox! But should be blocked from prod until Briem gives final approval

**Comment by simoncozens** [comment]
We have had some Glyphs file updates from Briem but I have not looked at them yet.

**Comment by emmamarichal** [comment]
I removed that PR from the traffic jam board, since I guess there will be a new PR with udpates!

**Comment by emmamarichal** [comment]
I created some subissues: https://github.com/google/fonts/issues/9037

**Pull request merged**
