### PR TITLE
reemkufi: v1.0

### PR DESCRIPTION
**Pull request by khaledhosny**
Reem Kufi is now a variable font with weight master. The previous version on GF does not install on Windows, FWIW.

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thanks for updating the metadata file as well.

**Comment by thlinard** [comment]
In MS Office for Mac (#3267 related):

ReemKufi

**Comment by khaledhosny** [comment]
I have no idea what to do with this. The font is designed with Glyphs and built with fontmake, what do I need to fix?

**Comment by thlinard** [comment]
> I have no idea what to do with this. The font is designed with Glyphs and built with fontmake, what do I need to fix?

Hi @khaledhosny
The `STAT` table is almost empty. `gftools fix-vf-meta` will correct it.

**Comment by khaledhosny** [comment]
Then fontmake should generate one in the first place, I don’t want to add more steps to the already complicated build.

**Comment by thlinard** [comment]
Oh yes, it should. In the meantime, here is the result after `gftools fix-vf-meta`:
Reem Kufi

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/issues/1507

**Comment by m4rc1e** [comment]
There's also `gftools gen-stat` which is the successor to `fix-vf-meta`. It will create STAT tables for a VF family based on our [Axis Registry](https://github.com/google/fonts/tree/main/axisregistry).

**Comment by thlinard** [comment]
Hi Marc,
Where can I find documentation for `gftools gen-stat`?

**Comment by m4rc1e** [comment]
gftools/stat.py: https://github.com/googlefonts/gftools/blob/main/Lib/gftools/stat.py#L1-L14

gftools/bin/gftools-gen-stat.py: https://github.com/googlefonts/gftools/blob/main/bin/gftools-gen-stat.py#L2-L41

**Comment by thlinard** [comment]
Perfect, thanks!

**Pull request merged**
