### PR TITLE
Big Shoulders Display SC: Version 2.002 added

### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shouldersi/commit/0b3d09a86862b19efae28eae0cd868f17c476b20.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@simoncozens, we need to confirm if we'll migrate to double axes VFs (`wght` + `opsz`) before merging all the Big Shoulders SC PRs.

**Comment by simoncozens** [comment]
Bah, after all the work I did to make these compatible with the existing builds. :-)

**Comment by davelab6** [comment]
> Bah, after all the work I did to make these compatible with the existing builds. :-)

This may not be wasted; I suspect we need both a "full vf" family and to retain the legacy families. For a start, Workspace Editors don't support variations ;)

**Comment by vv-monsalve** [comment]
In that case, @m4rc1e these fonts are ready to review

**Comment by emmamarichal** [comment]
@simoncozens 

Two small issues:
- anchor placement in 'J'
- anchor placement in 'ohorn'

Otherwise, lgtm!

Screenshot 2024-06-21 at 11 36 44
Screenshot 2024-06-21 at 11 39 28

**Comment by simoncozens** [comment]
These problems probably exist in the upstream Big Shoulders font. But we should check whether we still need these SC families.

**Comment by emmamarichal** [comment]
I think we were agree to onboard them yesterday!

But wait, I'm was doing last few tests and I meet these problems:
- the small caps don't appear in Word (Mac)
- I have weird results in Indesign. 

Screenshot 2024-06-21 at 11 49 38
Screenshot 2024-06-21 at 11 50 08

**Comment by simoncozens** [comment]
Looks like Word on the Mac does not apply ccmp. But my view is that the only target for these SC fonts is web browser, because the only reason they exist is that web API currently doesn't allow for the smcp feature. Word processors etc. do apply smcp, so people should use the main family in those environments.

**Review by emmamarichal — APPROVED** [review]

**Comment by vv-monsalve** [comment]
This is the project I asked about in last Friday's meeting to see if it's better to wait for the VF to happen.

**Comment by emmamarichal** [comment]
I really don't remember where and when, but I understood that we validated the fact we can onboard it as it is, and that we could still update it later with VF. If I find more infos, I'll let you know, but let's talk about this in our next meetings

**Pull request merged**
