### PR TITLE
Instrument Serif: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

### PR DESCRIPTION
**Pull request by emmamarichal**
1481ea5: [gftools-packager] Instrument Serif: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] added

* Instrument Serif Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.23] taken from the upstream repo https://github.com/Instrument/instrument-serif at commit https://github.com/Instrument/instrument-serif/commit/f6761d49c9e7687ea4d95bb2aa994f8673116c9b.

 7f2ad76: Instrument Serif: added a description - to complete

### CODE REVIEW

**Comment by emmamarichal** [comment]
I'm checking with the designer for a bigger description

**Comment by emmamarichal** [comment]
@RosaWagner the designer didn't mention anything concerning the description, so I guess it's okay, you can merge :)

**Comment by RosaWagner** [comment]
For new fonts, these 2 warns are good practice and easy to fix:

⚠ WARN: Font contains '.notdef' as its first glyph? ([com.google.fonts/check/mandatory_glyphs](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/mandatory_glyphs))
⚠ WARN: Check math signs have the same width. ([com.google.fonts/check/math_signs_width](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/math_signs_width))

**Comment by emmamarichal** [comment]
Updated

## Instrument Serif: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

---
 ded58fb: [gftools-packager] Instrument Serif: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] added

* Instrument Serif Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.27] taken from the upstream repo https://github.com/Instrument/instrument-serif at commit https://github.com/Instrument/instrument-serif/commit/9aefd76b9b96dffbdc7b65d38c0dc5bcae2717a9.

 69070ac: Instrument serif: Updated description

**Comment by emmamarichal** [comment]
@RosaWagnern updated!

**Pull request merged**
