### PR TITLE
Sixtyfour Convergence: Version 2.001 added



### PR DESCRIPTION
**Pull request by vv-monsalve**
Taken from the upstream repo https://github.com/jenskutilek/homecomputer-fonts at commit https://github.com/jenskutilek/homecomputer-fonts/commit/3e0b1194c1d2cc6bc66178908470a428f34349cd.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal this is a _special case_. Find here a disclosure of the acceptance of the reported Fails

- 🔥 FAIL Check Google Fonts glyph coverage.
- 🔥 FAIL Check variable font instances
- 🔥 FAIL Validate STAT particle names and values match the fallback names in GFAxisRegistry.
    These fails were already reviewed and accepted for the original [Sixtyfour font previously added](https://github.com/google/fonts/pull/7025#issuecomment-1830965038). The font only has custom Axes, we have allowed a set of `fvar` instances and named instances in the `STAT` to be included in [these cases](https://googlefonts.github.io/gf-guide/variable.html#stat-table). 

- 🔥 FAIL Validates that when an instance record is included for the default instance
    This was reviewed and [accepted here](https://github.com/google/fonts/pull/7025#issuecomment-1831770683).

- 🔥 FAIL Combined length of family and style must not exceed 32 characters.
    This was discussed and approved in the [Add Font Issue](https://github.com/google/fonts/issues/6980#issuecomment-2153307486)

- 🔥 FAIL Check font names are correct
    This doesn't make sense. FB is taking the unique `Default` instance registered for all the new custom axes and expecting it to be in the Name ID1. Otoh, we have recently ruled out the need to include the VF origin on it.

**Comment by vv-monsalve** [comment]
The XELA axis is included in the latest axis registry release v0.4.10

**Comment by emmamarichal** [comment]
@vv-monsalve Hey Viv!
And what about the ERROR? is it a fb bug? just to be sure!

**Review by emmamarichal — APPROVED** [review]

**Comment by vv-monsalve** [comment]
> And what about the ERROR? is it a fb bug?

Normally an ERROR is a tool level bug or issue. @felipesanches what could be the issue in this case?

**Comment by vv-monsalve** [comment]
Simon's comment on the error: That's a fontbakery bug, it should check whether the layerlist table has anything in it before attempting to read it.

So, I'm merging this here.

**Comment by vv-monsalve** [comment]
`XELA` default axis needed to be changed to `0` to unblock this one

**Comment by vv-monsalve** [comment]
Garret made a small change in the Metadata to re-push the family after the rendering issue was [fixed](https://github.com/harfbuzz/harfbuzz/pull/4831).

**Pull request merged**
