### PR TITLE
cairo: v3.116 added

### PR DESCRIPTION
**Pull request by eliheuer**
🚧 EDIT 🚧 latest force push is:

Taken from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/8cecfd4c79a6688c7233bca14af955bd3be0be67

### CODE REVIEW

**Comment by m4rc1e** [comment]
Metadata is good.

Here's some issues I just found

cairo_2

*Hinting still causing issues for fractions*

cairo_1

We should release the family unhinted and fix the brackets. Please inspect the diff images to if there's anything else wrong.

*Parenthesis also has same issue*

**Comment by eliheuer** [comment]
I talked with @Gue3bara about this yesterday and told him I would cc him on this pull request so we can work together in this thread to work out the best way forward for this typeface.

There have been lots of improvements to Cairo since it has last been updated. The most notable would be that the Black weight has more color. See the example screenshot from FontGoggles below:
cairo-color

I think this is an improvement, the Black weight looks much more like a Black in the latest upstream version. @Gue3bara agrees and has also suggested adding a new weight between the bold and the black. Maybe we should just update it to go from 100-900 hitting each weight?

What I did for now is to move the middle master to Regular, then try to keep all the weights as consistent as possible with the weights of the current static fonts. Then when I hit 700 the color ramps up shapely to the Black weight at 900, which wont match the current static font black well.

If Marc thinks the regressions are too much, I can easily update the PR with new weights that match across the whole range.

**Comment by Gue3bara** [comment]
Thank you @eliheuer for all the continuous help, 
originally the weight change was done to match "Titillium Web" on the platform in order to merge both families into one under the name "Titillium Web" with Arabic support, which i dont think will happen nor necessary as Cairo font grew its large Arabic audience. 

For now, I agree with Eli's proposal on the masters moving and i will be working on further testing and development to hopefully be able to publish this updated version very soon on the platform as it will have a lot of needed improvements.

**Comment by eliheuer** [comment]
The above Fontbakery report and QA images are:
Taken from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: Gue3bara/Cairo@2b99311

They are unhinted, and I attempted to fix the brace and bracket issues as Marc requested.

**Comment by m4rc1e** [comment]
Thanks. This is a big improvement. 

"quotesinglbase" is missing outlines. Please readd them. I think we're good after this.

Please also look into the diff images yourself, I may have missed some issues.

@Gue3bara could you also look at the latest gf-bot report?

**Comment by Gue3bara** [comment]
@m4rc1e I am checking the gf-bot report and running further tests and small modifications that will improve it, even further, I will be working in it today all day so by the end of the day I expect to report back to you

**Comment by davelab6** [comment]
If the new 900 is going to cause regressions and make user documents bolder, perhaps it should be setup as a 1000 weight?

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-597998749) force pushed update is from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/a5424a6754e3eb93e61fe337d4a047aea8b83940

@Gue3bara Worked on the Glyphs source some, and I wanted updated QA images to work from, so I force pushed this commit. No need for a review from Marc at this point, looking at the source file I still see some issues that need to be fixed.

**Comment by Gue3bara** [comment]
I solved the issues @eliheuer reported and ruan some further testing looking at the diff images -very handy- 
I still will run more tests and I need to change the weight on the tashkeel marks for the extra light master

**Comment by m4rc1e** [comment]
Thanks both of you for reviewing the diffs and making amendments. Ping me when you're done and I'll take a final look.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-598343909) force pushed update is from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/b9ce6f9df6454e167817e30695d32809181b7913

I'm reviewing the new QA images and with report any issues I find to the upstream issue tracker, and list them below.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-599484358) force pushed update is from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/b563b7324315b253210eec761bc4873f5d0b5131

**Comment by Gue3bara** [comment]
@eliheuer I will do one last check around and fix the outer overlap you mentioned on the eastern number 7 and 8 
following this I believe this will be good to go and will follow it with the final build for the slanted version as well

**Comment by eliheuer** [comment]
Thanks! We still need to figure out the shift in weight issues that @davelab6 brought up [here](https://github.com/google/fonts/pull/2380#issuecomment-597422919).

The problem is that when a font is updated and the weight/metrics change significantly, it can shift the layout and cause aesthetic changes on websites that are using the font served from Google Fonts. There have been issues like this in the past where people have been very upset. I believe there is one incident in particular that is known as "Montserrat-gate" where this caused lots of trouble, so Dave and Marc want to avoid changes in weight and metrics as much as possible.

It's a tricky situation because your upstream is clearly an improvement over what is currently available, and the black weight in the old version doesn't really match what I would consider a black, it's more of a Bold/ExtraBold. Also, there are people who I assume use this font already in it's current form(I think I remember @Gue3bara posted a screenshot of a TV news program using it!).

When I made the pull request to @Gue3bara's upstream repo with a new Glyphs file, I tried to do my best to make a compromise that would make everyone happy, but Marc or Dave need to give a firm yes or no if this amount of weight change is acceptable or not.

**Comment by Gue3bara** [comment]
Thank you @eliheuer for clarifying the point, which is very important to consider, Cairo is currently the most used Arabic font on the platform -149mil views a week- and used offline very widely -i never expected this insane spread- 

Screenshot-2020-03-16-19 40 59
The current differences between the weights are pretty close to the old version except for the new Black which went from 178 to 232 which is quite a difference I agree with @davelab6 

What i propose is to make the new black Heavy 1000 and interpolate a new black 900 that matches the old one in metrics 
the font will now be 7 weights instead of 6
if @davelab6 and @m4rc1e agree to this I can go ahead with it. as i dont find any other issues to fix after reviewing it thoroughly

**Comment by eliheuer** [comment]
That sounds good, thanks! Like I said above, ideally we can find a compromise that works for everyone and doesn't negatively effect the design of the upstream typeface.

**Comment by Gue3bara** [comment]
@eliheuer I guess i will try that in the new build and we can make a comparison

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-599874297) force pushed update is from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/3719d6f573c2e3c7fbdcf2ad155b4646c73a5ac7

This adds the new Heavy weight Dave suggested, but I didn't realize it introduces new Fontbakery Fails, addressing those issues now.

**Comment by eliheuer** [comment]
The CI build failed pushing new files from commit https://github.com/Gue3bara/Cairo/commit/e648690774a3ac0b471dfa4366a7f47f101bd0db, not sure why this happened @m4rc1e, looking into it. I might try to force push again with just the variable font if I can't think of anything else.

**Comment by eliheuer** [comment]
It looks like the QA tools aren't working for the 1000 Heavy weight yet, hence why the Travis CI build failed. I made an Issues in the [gfregression](https://github.com/googlefonts/gfregression) issue tracker that will hopefully address this here: https://github.com/googlefonts/gfregression/issues/61

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-601511100) force pushed update is from the upstream repo: https://github.com/Gue3bara/Cairo
At commit: https://github.com/Gue3bara/Cairo/commit/91290fd1fc935e4c83d7e6464b58eaf04f85cf88. I changed the weight value of Heavy back to 900, otherwise the Travis build would fail due to the [issue discussed](https://github.com/googlefonts/gfregression/issues/61) above.

**Comment by Gue3bara** [comment]
glyphs_missing

@eliheuer checking the comparison from the above report I still see a difference between the old and new heavy tho they are interpolated to be the same weight in the build

**Comment by eliheuer** [comment]
@Gue3bara I'll look at this now, I think maybe this has something to do with needing to change the Heavy back to 900 to get the QA tools to work, but it might also be a good idea to make more weight adjustments if things are still too different.

I talked with Dave and Marc today, and they both gave the OK for officially supporting the 1000 weight, and I think Marc will update the QA tools on Monday. So it could be merged Monday if there are no issues.

**Comment by Gue3bara** [comment]
> @Gue3bara I'll look at this now, I think maybe this has something to do with needing to change the Heavy back to 900 to get the QA tools to work, but it might also be a good idea to make more weight adjustments if things are still too different.

I made sure the weights are the exact same values from the old version there should be no weight differences, I wanna make sure the custom parameter worked 

now I am working on adding slant axis to slant right or left

**Comment by Gue3bara** [comment]
@m4rc1e @eliheuer 
I pushed a new build yesterday and I think its the one should go on the platform 
now added a new slant axis to interpolate between -11 and 11 degrees for slanting in both directions of reading 
I wanna make sure the new weight parameter we set is working correctly with fontmake and we are good to go

**Comment by eliheuer** [comment]
Fontmake dosen't like the new source file, but hopefully it is an easy fix, looking into it now and I made an upstream issue here: https://github.com/Gue3bara/Cairo/issues/54

**Comment by eliheuer** [comment]
⚠️ One important thing to note is that the latest commits from the upstream add a `Slant` axis. This seems like a great improvment for the upstream project, but might cause some issues here in this PR.

**Comment by Gue3bara** [comment]
@eliheuer I hope it works the new version with the slant will add a lot to the font

**Comment by eliheuer** [comment]
The new slant axis is introducing one new error that needs to be addressed to merge this PR. As far as I can tell there is only one other variable font in the GoogleFonts repository master branch at this time that has a slant axis, and that is [Inter](https://github.com/google/fonts/tree/master/ofl/inter), so this might still introduce some other issues, but ultimately that's a good thing since it tests the boundaries of what kind of variable fonts can be added. 

## Fontbakery report

Fontbakery version: 0.7.21

<summary><b>[1] Cairo[slnt,wght].ttf</b></summary>
<summary>🔥 <b>FAIL:</b> Check variable font instances have correct names</summary>

* [com.google.fonts/check/varfont_instance_names](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_names)

* 🔥 **FAIL** Instance "Heavy": is missing the following name tokens [wght]
* 🔥 **FAIL** Instance "Slant Right": is missing the following name tokens [wght]
* 🔥 **FAIL** Instance "Heavy Slant Right": is missing the following name tokens [wght]
* 🔥 **FAIL** Instance "Slant Left": is missing the following name tokens [wght]
* 🔥 **FAIL** Instance "Heavy Slant Left": is missing the following name tokens [wght]
* 🔥 **FAIL** Check has either failed or produced a warning. See our wip spec for further info https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb [code: bad-instance-names]

**Comment by m4rc1e** [comment]
We're not able to serve slnt axis fonts yet, due to lack of [browser](https://github.com/arrowtype/recursive/issues/56) support.

I suggest we just push the uprights and revisit the slanted version once browser support is better.

The instance names also seem a touch strange. We currently don't have a schema which supports fonts which have both a positive and negative slant I'm afraid.

**Comment by eliheuer** [comment]
Sure, thanks Marc.

@Gue3bara let's just try to get the uprights merged ASAP for now, and then we can start another PR for the slanted version later. I'll make a branch in my upstream fork that removes the slant axis I can build from.

**Comment by Gue3bara** [comment]
Thank you @m4rc1e and I agree to @eliheuer to go with the upright version for now and work later on a solution for the slanted version 

> The instance names also seem a touch strange. We currently don't have a schema which supports fonts which have both a positive and negative slant I'm afraid.
I thought it might be unusual but I want the font to support both slanting directions to be available as an option depending on the main language of the paragraph if it's Latin featuring Arabic words or Arabic featuring Latin words 
I think it is essential to support both directions for bi-script font families like Cairo

**Comment by eliheuer** [comment]
I made an issue for bidirectional slant axis support [here](https://github.com/google/fonts/issues/2400), and also a post about it on Google Fonts Discussions [here](https://groups.google.com/forum/#!topic/googlefonts-discuss/QEx_dtunAH8), so hopefully it will happen. It's clearly a very nice feature for the upstream typeface.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-603650514) gf-bot report is from my [upright only branch](https://github.com/eliheuer/Cairo/tree/upright-only) with the 1000 instance removed. 

GF-bot still breaks with the Heavy 1000 weight.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-603925479) gf-bot report is from my [upright only branch](https://github.com/eliheuer/Cairo/tree/upright-only), forked from the upstream commit `dbff50f`, with the `Heavy` weight renamed to `ExtraBlack`.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-604227593) gf-bot report is built from https://github.com/Gue3bara/Cairo/commit/f264108354ff1f86a660581fe8711cd1f7509575, with the slant axis removed.

This is close to ready for a merge review, I will review it now and list issues and thoughts below. After that I will request a final merge review from Marc.

**Comment by eliheuer** [comment]
I'm still going over the QA images looking for issues, but I think this is ready for a merge review from @m4rc1e.

**Comment by Gue3bara** [comment]
I also went through the QA images and so far I don't find issues to fix

**Comment by m4rc1e** [comment]
@Gue3bara is the Allah glyph correct? seems to be missing marks

glyphs_modified

**Comment by eliheuer** [comment]
I works when I test the variable font in FontGoggles, same with the Persian p ( پ ). 

test

**Comment by Gue3bara** [comment]
> @Gue3bara is the Allah glyph correct? seems to be missing marks
> 
> glyphs_modified

@m4rc1e  the difference you see here because I have two versions for Allah now to support further tashkeel marks positioning without issues
you can ignore this as it's working as expected 
Screenshot 2020-03-30 18 59 46

**Comment by m4rc1e** [comment]
Oslash bracket is working fine.

Screenshot 2020-03-31 at 10 41 42

It isn't working for accented Oslash glyphs.

Screenshot 2020-03-31 at 10 41 34

Should the Oslash even be bracketed? Will it lead to confusion?

**Comment by eliheuer** [comment]
Good catch Marc, sorry I missed this. Will do another full review today. It also does this between 900 and 1000 in the variable font.
oslash

**Comment by eliheuer** [comment]
@m4rc1e I'm not sure why Travis is failing with the following error:
`AttributeError: 'PngImageFile' object has no attribute '_PngImageFile__frame'`

But the Oslash and oslash issue is fixed in the latest force psuh.

**Comment by hugovk** [comment]
> @m4rc1e I'm not sure why Travis is failing with the following error:
> `AttributeError: 'PngImageFile' object has no attribute '_PngImageFile__frame'`
> 
> But the Oslash and oslash issue is fixed in the latest force psuh.

This is a bug in the new Pillow 7.1.0 release: https://github.com/python-pillow/Pillow/issues/4509.

In the meantime, you can pin `pillow!=7.1.0`

**Comment by m4rc1e** [comment]
@hugovk thank you for fixing the issue in Pillow and for replying to this pr.

It may be easier for us to just wait for a new pypi tagged release.

**Comment by Gue3bara** [comment]
> Oslash bracket is working fine.
> 
> Screenshot 2020-03-31 at 10 41 42
> 
> It isn't working for accented Oslash glyphs.
> 
> Screenshot 2020-03-31 at 10 41 34
> 
> Should the Oslash even be bracketed? Will it lead to confusion?

Kapture 2020-04-02 at 14 33 00
@m4rc1e  solved

**Comment by eliheuer** [comment]
The Pillow issue is still causing the Travis CI build to fail, but here is an update to keep this moving forward. I reviewed the QA images from https://github.com/Gue3bara/Cairo/commit/f264108354ff1f86a660581fe8711cd1f7509575 and didn't find any major issues, there are still small issues that might be renderings bugs or things I just don't understand. I will edit this post today to list those.

There is one remaining fail, I think I can fix that by rewriting the build script to build to UFOs, then fixing the issue in the UFOs, then building from the fixed UFOs. I wish there was a way to fix this in the Glyphs source, but I have tried multiple times and can't figure it out.

**Comment by hugovk** [comment]
Pillow 7.1.1 has just been released! Please can you retest?

**Comment by eliheuer** [comment]
Sure, I'll push a new update soon, thanks for all your help!

**Comment by eliheuer** [comment]
Just pushed again and now I'm getting a new error:
```
INFO:fontdiffenator:'diff_marks'  3.93 ms
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/gftools-qa.py", line 541, in <module>
    main()
  File "/home/travis/virtualenv/python3.7.1/bin/gftools-qa.py", line 518, in main
    qa.googlefonts_upgrade()
  File "/home/travis/virtualenv/python3.7.1/bin/gftools-qa.py", line 276, in googlefonts_upgrade
    self.diffenator()
  File "/home/travis/virtualenv/python3.7.1/bin/gftools-qa.py", line 165, in diffenator
    diff.to_gifs(dst=out)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/diffenator/diff.py", line 124, in to_gifs
    _table.to_gif(img_path, limit=limit)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/diffenator/__init__.py", line 312, in to_gif
    duration=1000
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/Image.py", line 2134, in save
    save_handler(self, fp, filename)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 499, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 510, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/GifImagePlugin.py", line 430, in _write_multiple_frames
    for im_frame in ImageSequence.Iterator(imSequence):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/ImageSequence.py", line 49, in __next__
    self.im.seek(self.position)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 748, in seek
    self._seek(f)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 791, in _seek
    cid, pos, length = self.png.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by pmrowla** [comment]
The new error is same as python-pillow/Pillow#4518

**Comment by Gue3bara** [comment]
I noticed an issue with the features of the ligatures somehow disappeared from the font features so I added them again to fix that 
but other than this I don't notice any other issues

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-610757771) QA report is force pushed update built from the upstream repo https://github.com/Gue3bara/Cairo At commit: https://github.com/Gue3bara/Cairo/commit/caeaa7026b0fee52cd339d65af161052d4ea366a. This includes the latest updates and fixes from @Gue3bara mentioned [here](https://github.com/google/fonts/pull/2380#issuecomment-610380318), thanks!

I will review the QA images again today, document any issues I find and report them in the upstream issue tracker. I'll also check everything against the [WIP spec](https://gist.github.com/m4rc1e/8f4c4498519e8a36cd54e16a004275cb). Hopefully @m4rc1e will have time to review this for merge tomorrow.

**Comment by Gue3bara** [comment]
Thank you @eliheuer 

> * If it isn't clear, the `ARABIC LETTER HEH MEDIAL FORM, U+FEEC` changes shape, but it still reads and looks like an improvement to me, although my Arabic skills aren't very advanced, so I could be missing something.
>   heh-fix

The new heh medial is just the more common way of illustrating heh medial, nothing was wrong with the older version but I find the new one more requested while the older version can still be used as an alternative especially for `hehDoachashmee-ar.medi U+FBAD`

> * I've tried to figure out what is happening here, can't figure it out `tcheh-ar.fina` `U+FB7B`. I think decomposing the `threedotsdowncenter-ar` might fix this, but I would like to figure this out without decomposing.
>   notsure
>   tcheh-ar fina
This is very odd but I will try to look into what's happening here and let you know if I figure it out

**Comment by eliheuer** [comment]
Thanks! I'm going to keep working on small details this weekend, and then bug @m4rc1e to review it Monday.

**Comment by eliheuer** [comment]
I made a FontBakery issues about the `com.google.fonts/check/valid_glyphnames` fail here: https://github.com/googlefonts/fontbakery/issues/2832

And Felipe [has merged an update](https://github.com/googlefonts/fontbakery/pull/2833) to the check that raises the character limit to 63 for a FAIL and produces a WARN for characters over 31. This is supported by the [Adobe Glyph List Specification](https://github.com/adobe-type-tools/agl-specification), which is where Microsoft gets the 31 character limit to begin with. Please see the [above mentioned](https://github.com/googlefonts/fontbakery/issues/2832) FontBakery issue for more detail.

The `com.google.fonts/check/repo/vf_has_static_fonts` fail is and issues with the CI process and passes when run locally. So there are no legitimate fails.

@m4rc1e Could you please let me know if there are any technical issues here besides the way outlines are rendered? If I'm missing anything I can propose a FontBakery check to catch the issue in the future.

**Comment by hugovk** [comment]
> The new error is same as [python-pillow/Pillow#4518](https://github.com/python-pillow/Pillow/issues/4518)


Pillow 7.1.2 was released yesterday to fix this.

https://pillow.readthedocs.io/en/stable/releasenotes/7.1.2.html

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-621618515) QA report is a force pushed update built from the upstream repo https://github.com/Gue3bara/Cairo At commit: https://github.com/Gue3bara/Cairo/commit/caeaa7026b0fee52cd339d65af161052d4ea366a.

The one remaining fail can be ignored because the CI/QA tools don't use the static directory. You can clone this branch (`cairo-vf`) and run `fontbakery` locally to see that this commit passes with no fails.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-626063631) QA report is a force pushed update built from the upstream repo https://github.com/Gue3bara/Cairo at commit: https://github.com/Gue3bara/Cairo/commit/15114e609854105e731e3722ef42d2402ba8de11.

The one remaining fail can be ignored because the CI/QA tools don't use the static directory. You can clone this branch (`cairo-vf`) and run `fontbakery` locally to see that this commit passes with no fails.

**Comment by m4rc1e** [comment]
Look good. @eliheuer this ready to merge?

**Comment by eliheuer** [comment]
Yes, as far as I can tell. 

There are still some [minor open issues](https://github.com/Gue3bara/Cairo/issues/68) that can be hotfixed soon.

The QA images still have some issues adapting to the new 1000 weights, but I looked at this regularly in FontGoggles and the weight changes all seem to be within an acceptable range there. 

I can make any needed hotfixes, and @Gue3bara has been very responsive to upstream issues recently.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-639533396) QA report is a force pushed update built from the upstream repo https://github.com/Gue3bara/Cairo at commit: https://github.com/Gue3bara/Cairo/commit/8cecfd4c79a6688c7233bca14af955bd3be0be67.

**Comment by eliheuer** [comment]
The [above](https://github.com/google/fonts/pull/2380#issuecomment-649159194) QA report is for a force-pushed update built from the upstream repo https://github.com/Gue3bara/Cairo at commit: https://github.com/Gue3bara/Cairo/commit/886eed813f071f8ad057a299d41e54b6edf0ed95.

https://github.com/Gue3bara/Cairo/commit/886eed813f071f8ad057a299d41e54b6edf0ed95 merged a [pull request](https://github.com/Gue3bara/Cairo/pull/69) from me that fixes the remaining upstream issues mentioned [here](https://github.com/google/fonts/pull/2380#issuecomment-639020185).

This pull request also adds [a new build script](https://github.com/Gue3bara/Cairo/blob/master/scripts/build.sh) that does a better job creating a reproducible font build. Just run the following from the Cairo root directory:
```
sh scripts/build.sh && scripts/google-fonts-pr.sh
```
@m4rc1e There are no fails and the upstream issues are fixed, so please consider merging at this point. Thanks.

**Comment by Gue3bara** [comment]
@m4rc1e any updates on this issue?
the new release of Cairo is still not on GF yet

**Comment by eliheuer** [comment]
I have time over the next few weeks to work on this, but I understand if anyone else wants to step in and assist or take over this PR completely.

I'll look at the current state of the Cario project and see what I can do to bring it into conformity with the current spec now.

**Comment by aaronbell** [comment]
Hi. It looks like the variable font version lacks a proper STAT table, which is causing issues in MS Word :(. I'll dive into the repro next week and get it sorted out.

**Comment by RosaWagner** [comment]
@aaronbell if you could fix the Multiple designers thing in the METADATA.pb at the same time it would be great (basically by removing the mention and replacing it by the actual names of the authors)

**Comment by aaronbell** [comment]
@googlebot I consent

**Comment by aaronbell** [comment]
@RosaWagner I've updated the metadata and corrected the STAT table, so this one should be good to go now. 

Meanwhile, I'm going to update the upstream repro for the `slnt` version so we can prepare another PR with that capability to put pressure on getting it registered :).

**Comment by RosaWagner** [comment]
The font looks really improve. 

Although, missing instances in FVAR table, + an ExtraBlack that is not supported by google. I suggest to move current Black to ExtraBold (800) and ExtraBlack to Black (1000). + adding a Medium at 500. --> I think regression of weight on extreme weight styles is okay since less used than intermediate ones, and even less in an entire paragraph (consequences are low).

Now @aaronbell is overly trained to handle these issues:

Capture d’écran 2021-09-08 à 15 08 21

Capture d’écran 2021-09-08 à 15 11 56

**Comment by aaronbell** [comment]
@RosaWagner According to https://github.com/googlefonts/gf-docs/tree/main/Spec#axis-particles, ExtraBlack is supported. Is this a mismatch? 

Not sure what happened with that undefined one. I've run gen-stat to fix it up.

**Comment by RosaWagner** [comment]
> @RosaWagner According to https://github.com/googlefonts/gf-docs/tree/main/Spec#axis-particles, ExtraBlack is supported. Is this a mismatch? 

I stand corrected ! So I don't remember where I read/heard that, I'll ask for confirmation to be sure, but I don't see the issue then.

**Comment by RosaWagner** [comment]
@aaronbell I looked at the building script which I didn't understand so well, but you could take care of the nested and transformed components issues in there by adding argument to the fontmake command:
`--flatten-components --filter DecomposeTransformedComponentsFilter`

**Comment by aaronbell** [comment]
@RosaWagner Yeah, fontbakery issues a FAIL if you have ExtraBlack at 1000, but according to gf-spec it is allowed. Kind of confusing :).

Anyway, I rebuilt the font using the UFR set up from the upstream repro (stripping out the slnt bits) and uploaded. Should be GTG now.

**Comment by RosaWagner** [comment]
LGTM. Since it's a pretty popular font and there is a slight horizontal regression, I wait for Marc's confirmation too.

**Comment by m4rc1e** [comment]
LGTM. Thanks for this and apologies for the delay.

**Pull request merged**
