### PR TITLE
Noto Serif Gurmukhi: Version 2.003 added

### PR DESCRIPTION
**Pull request by simoncozens**
3c63687: [gftools-packager] Noto Serif Gurmukhi: Version 2.003 added

* Noto Serif Gurmukhi Version 2.003 taken from the upstream repo https://github.com/notofonts/gurmukhi.git at commit https://github.com/notofonts/gurmukhi/commit/.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
> 🔥 FAIL: Checking OS/2 usWinAscent & usWinDescent. ([com.google.fonts/check/family/win_ascent_and_descent](https://font-bakery.readthedocs.io/en/stable/fontbakery/profiles/universal.html#com.google.fonts/check/family/win_ascent_and_descent))
> 🔥 FAIL OS/2.usWinDescent value should be equal or greater than 579, but got 428 instead. [code: descent]

Since you are enabling the Use of Type Metrics now, the Win value could be changed to avoid clippings.

**Comment by vv-monsalve** [comment]
I suppose the new mark positions are intended, but I rather confirm it with you.
Desktop_Windows_10_chrome_71 0_

**Comment by vv-monsalve** [comment]
> I suppose the new mark positions are intended, but I rather confirm it with you.

@simoncozens are the new mark positions ok?

**Comment by simoncozens** [comment]
Yes, these look nice.

**Comment by vv-monsalve** [comment]
> Yes, these look nice.

Ok, merging this one here then.

**Pull request merged**
