### PR TITLE
Alumni Sans SC: Version 1.016 added



### PR DESCRIPTION
**Pull request by simoncozens**
Taken from the upstream repo https://github.com/googlefonts/alumni at commit https://github.com/googlefonts/alumni/commit/44a7998fa2bfa1b3e119983cdc565dd7f0f03bda.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [ ] Minisite_url definition in the METADATA.pb file for commissioned projects
- [ ] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by simoncozens** [comment]
(This is a serious PR, but it is also a test of the small caps builder *and* the `gftools-packager --build-from-source` option.)

**Comment by vv-monsalve** [comment]
The SC fonts are automatically created from the non-SC fonts, so they do not cover update fixes. They should probably be done "upstream" later on.

**Comment by vv-monsalve** [comment]
@simoncozens I added the SC reference to the Description file. After that, LGTM. 
However, the CI run is not working now. I'll wait until we hear from Marc on that.

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
@simoncozens please rebase the PR so the CI can work with the latest changes to produce the complete qa files (including the diffenator proof)

**Comment by emmamarichal** [comment]
same question: https://github.com/google/fonts/pull/7769

**Pull request merged**
