### PR TITLE
artakana : bio added (desinger name fixed)

### PR DESCRIPTION
**Pull request by mintoming**
atalog/designers/artakana

### CODE REVIEW

**Comment by RosaWagner** [comment]
Means that designer field in Dela Gothic One (metadata + fonts) is wrong
cc @aaronbell

**Comment by mintoming** [comment]
@RosaWagner Yes, for metadata (not sure about the font). I'll PR the metadata too (that is if my SourceTree work fine😂).

**Comment by RosaWagner** [comment]
Ah better to have a separated PR for the font cause I checked the statics and it also have the wrong name, so it needs to be re-built

**Comment by mintoming** [comment]
Ah OK! 🙏

**Comment by aaronbell** [comment]
Huh. I'll correct it in the Dela Gothic source.

**Pull request merged**
