### PR TITLE
Splash: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by vv-monsalve**
05f8315: [gftools-packager] Splash: Version 1.010; ttfautohint (v1.8.4.7-5d5b) added

* Splash Version 1.010; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/googlefonts/splash at commit https://github.com/googlefonts/splash/commit/7653a0b5fcccd37a920ba9a4da8f1680c0203af2.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Splash is part of Batch 5 of TypeSetIT fonts.

**Comment by vv-monsalve** [comment]
```
ValueError: to_production.txt: Following paths are not valid:
lang/languages/ar_Arab.textproto
```
Are languages not supposed to be included anymore?

**Comment by m4rc1e** [comment]
> Are languages not supposed to be included anymore?

That CI error is for the push files. The path for these files is incorrect.

re METADATA.pb languages, judging by Andy's recent commits and Nathan's gftools work, we should remove them. I'll drop them from this pr for you.

AFAIK the latest version of gftools add-font shouldn't add the language stuff any more so it's worth upgrading.

**Review by m4rc1e — APPROVED** [review]

**Comment by vv-monsalve** [comment]
Thank you Marc

**Pull request merged**
