### PR TITLE
Roboto Slab: Version 2.002 added

### PR DESCRIPTION
**Pull request by emmamarichal**
2913ce9: [gftools-packager] Roboto Slab: Version 2.002 added

* Roboto Slab Version 2.002 taken from the upstream repo https://github.com/googlefonts/robotoslab at commit https://github.com/googlefonts/robotoslab/commit/3516216960b860546b4e0c213223ff556a7b8a3e.

### CODE REVIEW

**Comment by emmamarichal** [comment]
see: https://github.com/googlefonts/robotoslab/pull/32

**Comment by RosaWagner** [comment]
Prior to merging we may need to move APACHE to OFL license

**Comment by RosaWagner** [comment]
We are asked to move from APACHE to OFL in a separate PR

**Comment by RosaWagner** [comment]
kerning pairs `ηγ` and `ην` became quite tight it might means that the kerning of the Latin should be separated from the kerning of the Greek. Or that `η` is having a too tight right sidebearing. Maybe just an exception kerning pair would be enough, let's not necessarily disturb it all.

**Comment by emmamarichal** [comment]
Updated

## Roboto Slab: Version 2.002 added

---
 892dc85: [gftools-packager] Roboto Slab: Version 2.002 added

* Roboto Slab Version 2.002 taken from the upstream repo https://github.com/googlefonts/robotoslab at commit https://github.com/googlefonts/robotoslab/commit/67af3ce9c4ca574419e1295b6165a2eeee112e6e.

**Pull request merged**
