### PR TITLE
vollkorn: v4.014 added

### PR DESCRIPTION
**Pull request by m4rc1e**
New Vollkorn has more weights. This has affected the family weight distribution. New bold appears much lighter because it has become the Black in the latest release.

screen shot 2017-03-31 at 15 24 28
*Left: new Right: old*

People have complained about such issues in the past.

### CODE REVIEW

**Comment by davelab6** [comment]
Curious Medium and Extrabold are missing. Do you know why?

I'm ok to shift the weight to make it better

**Comment by m4rc1e** [comment]
@davelab6 Previous release only had:
- Regular
- Bold
- Italic
- Bold Italic
https://fonts.google.com/specimen/Vollkorn

New release has:
- Regular
- SemiBold
- Bold
- Black
- Italic
- SemiBold Italic
- Bold Italic
- Black Italic

I don't think there ever was a Medium.

The weight shift may be ok. The Regular is still the same weight as the old. The new Black weight is the same weight as the previous Bold. The new SemiBold and Bold are in between values.

Imo, the old Bold is more like an ExtraBold, so squeezing in two middle weights makes a better transition.

**Comment by davelab6** [comment]
I'm suggesting even more intermediate weights be generated

**Comment by davelab6** [comment]
Superceded by https://github.com/google/fonts/pull/1011

**Pull request merged**
