### PR TITLE
Harmattan: Version 4.300 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/silnrsi/font-harmattan at commit https://github.com/silnrsi/font-harmattan/commit/00b3f6eeb48170d46b0c56d386374dc79203bd2b.
## PR Checklist:

- [ ] `minisite_url` definition in the METADATA.pb file for commissioned projects
- [ ] `primary_script` definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] `subsets` definitions in the METADATA.pb reflect the actual subsets and languages present in the font files (in alphabetic order). For **CJK fonts**, only include one of the following subsets `chinese-hongkong`, `chinese-simplified`, `chinese-traditional`, `korean`, `japanese`.
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [ ] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not)
- [ ] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by vv-monsalve** [comment]
@emmamarichal The `name ID 3 Unique font identifier` is changing from `SIL International: Harmattan Regular 2023` to `SIL Global: Harmattan Regular 2024`. Is this OK? Have we seen this already in previous upgrades, and did this not bring any issue?.

Other than that LGTM.

**Comment by emmamarichal** [comment]
@vv-monsalve, I see Marc already merged Abyssinica that has the same change, and it appears well in the dev-server, so I guess we can merge this safely!

**Comment by vv-monsalve** [comment]
> @vv-monsalve, I see Marc already merged Abyssinica that has the same change, and it appears well in the dev-server, so I guess we can merge this safely!

Ok. Let's take this as a green light to go.

**Review by vv-monsalve — APPROVED** [review]

**Comment by vv-monsalve** [comment]
For the unsuccessful check, running diffenator locally, the changes seem to be the expected ones.

Harmattan-ba

**Comment by LornaSIL** [comment]
> The name ID 3 Unique font identifier is changing from SIL International: Harmattan Regular 2023 to SIL Global: Harmattan Regular 2024. Is this OK? Have we seen this already in previous upgrades, and did this not bring any issue?.

I didn't think about that change. This comes about from SIL's DBA name change which was announced here: https://www.sil.org/about/news/new-name-90-sil-international-becomes-sil-global We are still the same org, it hasn't changed except for the DBA name change. As we update our fonts we will be changing the copyright on them.

**Comment by vv-monsalve** [comment]
Thank you, @LornaSIL, for the expanded context on that change. I wanted to confirm if it would introduce any conflict regression in our servers, but the updated fonts seem to be working just fine.

**Pull request merged**
