### PR TITLE
Big Shoulders Text: Version 1.101 added

### PR DESCRIPTION
**Pull request by vv-monsalve**
d21a4c3: [gftools-packager] Big Shoulders Text: Version 1.101 added

* Big Shoulders Text Version 1.101 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/2ba5ffb0037850418d2084b2f1261e846eef3772.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Updated

## Big Shoulders Text: Version 1.101 added

---
 45901eb: [gftools-packager] Big Shoulders Text: Version 1.101 added

* Big Shoulders Text Version 1.101 taken from the upstream repo https://github.com/xotypeco/big_shoulders at commit https://github.com/xotypeco/big_shoulders/commit/2ba5ffb0037850418d2084b2f1261e846eef3772.

 87d5c56: [gftools-packager] ofl/bigshoulderstext remove METADATA "source".  google/fonts#2587

**Comment by RosaWagner** [comment]
- Patric King is not [in the catalog](https://github.com/google/fonts/tree/master/catalog/designers), could you PR a bio @vv-monsalve ?

**Comment by RosaWagner** [comment]
LGTM

**Comment by vv-monsalve** [comment]
Thanks, Rosalie. Although there is a last-minute update on the Description file that should be included, so it wouldn't be ready to push. I'll do a new PR with it.

**Comment by RosaWagner** [comment]
It's okay, we update the to_sandbox only tomorrow.

**Comment by vv-monsalve** [comment]
ok, it is solved here https://github.com/google/fonts/pull/2745

**Pull request merged**
