### PR TITLE
rubik: v2.000 added

### PR DESCRIPTION
**Pull request by m4rc1e**
Hey @davelab6,
Alexei's Cyrillic has been added.

Please check these fonts

FB reports diff glyph names. This is because the Cyrillic has an additional ss01 glyph ;)

There are many out of bound errors on the italics. The joy of tight rough corners on Italic fonts.

Have a nice weekend,
Marc

### CODE REVIEW

**Comment by m4rc1e** [comment]
@davelab6 

OFL and font copyright strings have been updated.

**Comment by davelab6** [comment]
Per https://github.com/google/fonts/issues/333#issuecomment-252087264 I'm going to hold this open for a while

**Comment by m4rc1e** [comment]
VTT hinting is being added. Only merge when the hinting is complete.

**Comment by davelab6** [comment]
@m4rc1e I'm going to merge this now as the errors are quite serious, so I think a hinting regression is worth the hit

**Pull request merged**
