### PR TITLE
Noto Sans Khojki: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

### PR DESCRIPTION
**Pull request by simoncozens**
78eb315: [gftools-packager] Noto Sans Khojki: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

* Noto Sans Khojki Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/khojki.git at commit https://github.com/notofonts/khojki/commit/.

### CODE REVIEW

**Comment by simoncozens** [comment]
```
This release:

* Fixes the anchoring of alternate anusvara (#23)
* Allows for kerning of sequences with marks (#13)
* Adds the newly encoded characters QA (U+1123F) and SHORT I (U+11240)
```

**Review by m4rc1e — APPROVED** [review]

**Comment by emmamarichal** [comment]
There are tofu in the current version on the API too, but I want to make sure it's okay!

Capture d’écran 2023-11-15 à 14 09 33

**Comment by simoncozens** [comment]
Tofu is never ok for the NoTo-fu project. :-) This is https://github.com/googlefonts/lang/issues/101 which still needs a fix to the Khojki sample text.

**Comment by emmamarichal** [comment]
Should I wait for it before unblock this PR?

**Comment by simoncozens** [comment]
Yeah, let me just do that now.

**Comment by simoncozens** [comment]
Done as https://github.com/googlefonts/lang/pull/122, will need review/merging and then a new lang module release (+ subtree pull) will fix the tofu.

**Comment by eliheuer** [comment]
@simoncozens Noto Sans Khojki still has tofu in sandbox despite https://github.com/google/fonts/pull/6970 also being in sandbox.

**Pull request merged**
