### PR TITLE
elmessiri: ElMessiri-VF.ttf added

### PR DESCRIPTION
**Pull request by m4rc1e**
Upstream pr also sent https://github.com/Gue3bara/El-Messiri/pull/16

### CODE REVIEW

**Comment by davelab6** [comment]
Shouldn't this be named `ElMessiriBetaVF.ttf` and be a new family?

**Comment by m4rc1e** [comment]
I added the VFBeta suffix to families which were destined for Early Access. This happened around a year ago.

These new VF families do not have this suffix. I was under the impression these families had to be production ready. I can happily append VFBeta and move them to new family dirs, if we're not confident enough yet. I've also just seen @nyshadhr9 is appending VFBeta to the filenames.

screen shot 2018-04-05 at 09 33 15


@nyshadhr9 Would you like me to add VFBeta to the filenames and adjust the font names? I will then also do as Dave suggested and move them to their own family.

**Comment by davelab6** [comment]
Since these are existing families, we need them to have the "VF Beta" appended to family name so they don't collide. So, if its an existing family being upgraded (which is the vast majority) then append "VF Beta". Then when the serving development is more progressed, we can discuss graduating them from beta status.

However, new families that aren't already in the API as static fonts could avoid this -- if we are sure that the quality of the VF is what it would be in a final release. If we have concerns about the VF output, they should also be a Beta.

**Comment by m4rc1e** [comment]
Ok. Here's a before and after on Rokkitt for the name table change

**Before**
```
Font                 platformID    encodingID    languageID    nameID  nameString
RokkittVFBeta.ttf             1             0             0         0  Copyright 2016 The Rokkit Project Authors (contact@sansoxygen.com)
RokkittVFBeta.ttf             1             0             0         1  Rokkitt
RokkittVFBeta.ttf             1             0             0         2  Regular
RokkittVFBeta.ttf             1             0             0         3  3.002;NEWT;Rokkitt-Regular
RokkittVFBeta.ttf             1             0             0         4  Rokkitt Regular
RokkittVFBeta.ttf             1             0             0         5  Version 3.002
RokkittVFBeta.ttf             1             0             0         6  Rokkitt-Regular
RokkittVFBeta.ttf             1             0             0         7  Rokkitt is a trademark of Vernon Adams and may be registered in certain jurisdictions.
RokkittVFBeta.ttf             1             0             0         8  Vernon Adams
RokkittVFBeta.ttf             1             0             0         9  Vernon Adams
RokkittVFBeta.ttf             1             0             0        11  http://www.sansoxygen.com
RokkittVFBeta.ttf             1             0             0        12  http://www.sansoxygen.com
RokkittVFBeta.ttf             1             0             0        13  This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
RokkittVFBeta.ttf             1             0             0        14  http://scripts.sil.org/OFL
RokkittVFBeta.ttf             3             1          1033         0  Copyright 2016 The Rokkit Project Authors (contact@sansoxygen.com)
RokkittVFBeta.ttf             3             1          1033         1  Rokkitt
RokkittVFBeta.ttf             3             1          1033         2  Regular
RokkittVFBeta.ttf             3             1          1033         3  3.002;NEWT;Rokkitt-Regular
RokkittVFBeta.ttf             3             1          1033         4  Rokkitt Regular
RokkittVFBeta.ttf             3             1          1033         5  Version 3.002
RokkittVFBeta.ttf             3             1          1033         6  Rokkitt-Regular
RokkittVFBeta.ttf             3             1          1033         7  Rokkitt is a trademark of Vernon Adams and may be registered in certain jurisdictions.
RokkittVFBeta.ttf             3             1          1033         8  Vernon Adams
RokkittVFBeta.ttf             3             1          1033         9  Vernon Adams
RokkittVFBeta.ttf             3             1          1033        11  http://www.sansoxygen.com
RokkittVFBeta.ttf             3             1          1033        12  http://www.sansoxygen.com
RokkittVFBeta.ttf             3             1          1033        13  This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
RokkittVFBeta.ttf             3             1          1033        14  http://scripts.sil.org/OFL
RokkittVFBeta.ttf             3             1          1033       256  Weight
RokkittVFBeta.ttf             3             1          1033       257  Thin
RokkittVFBeta.ttf             3             1          1033       258  ExtraLight
RokkittVFBeta.ttf             3             1          1033       259  Light
RokkittVFBeta.ttf             3             1          1033       260  Regular
RokkittVFBeta.ttf             3             1          1033       261  Medium
RokkittVFBeta.ttf             3             1          1033       262  SemiBold
RokkittVFBeta.ttf             3             1          1033       263  Bold
RokkittVFBeta.ttf             3             1          1033       264  ExtraBold
RokkittVFBeta.ttf             3             1          1033       265  Black
```

**After**
```
Font                     platformID    encodingID    languageID    nameID  nameString
RokkittVFBeta.ttf.fix             1             0             0         0  Copyright 2016 The Rokkit Project Authors (contact@sansoxygen.com)
RokkittVFBeta.ttf.fix             1             0             0         1  Rokkitt VF Beta
RokkittVFBeta.ttf.fix             1             0             0         2  Regular
RokkittVFBeta.ttf.fix             1             0             0         3  3.002;NEWT;RokkittVFBeta-Regular
RokkittVFBeta.ttf.fix             1             0             0         4  Rokkitt VF Beta Regular
RokkittVFBeta.ttf.fix             1             0             0         5  Version 3.002
RokkittVFBeta.ttf.fix             1             0             0         6  RokkittVFBeta-Regular
RokkittVFBeta.ttf.fix             1             0             0         7  Rokkitt is a trademark of Vernon Adams and may be registered in certain jurisdictions.
RokkittVFBeta.ttf.fix             1             0             0         8  Vernon Adams
RokkittVFBeta.ttf.fix             1             0             0         9  Vernon Adams
RokkittVFBeta.ttf.fix             1             0             0        11  http://www.sansoxygen.com
RokkittVFBeta.ttf.fix             1             0             0        12  http://www.sansoxygen.com
RokkittVFBeta.ttf.fix             1             0             0        13  This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
RokkittVFBeta.ttf.fix             1             0             0        14  http://scripts.sil.org/OFL
RokkittVFBeta.ttf.fix             3             1          1033         0  Copyright 2016 The Rokkit Project Authors (contact@sansoxygen.com)
RokkittVFBeta.ttf.fix             3             1          1033         1  Rokkitt VF Beta
RokkittVFBeta.ttf.fix             3             1          1033         2  Regular
RokkittVFBeta.ttf.fix             3             1          1033         3  3.002;NEWT;RokkittVFBeta-Regular
RokkittVFBeta.ttf.fix             3             1          1033         4  Rokkitt VF Beta Regular
RokkittVFBeta.ttf.fix             3             1          1033         5  Version 3.002
RokkittVFBeta.ttf.fix             3             1          1033         6  RokkittVFBeta-Regular
RokkittVFBeta.ttf.fix             3             1          1033         7  Rokkitt is a trademark of Vernon Adams and may be registered in certain jurisdictions.
RokkittVFBeta.ttf.fix             3             1          1033         8  Vernon Adams
RokkittVFBeta.ttf.fix             3             1          1033         9  Vernon Adams
RokkittVFBeta.ttf.fix             3             1          1033        11  http://www.sansoxygen.com
RokkittVFBeta.ttf.fix             3             1          1033        12  http://www.sansoxygen.com
RokkittVFBeta.ttf.fix             3             1          1033        13  This Font Software is licensed under the SIL Open Font License, Version 1.1. This license is available with a FAQ at: http://scripts.sil.org/OFL
RokkittVFBeta.ttf.fix             3             1          1033        14  http://scripts.sil.org/OFL
RokkittVFBeta.ttf.fix             3             1          1033       256  Weight
RokkittVFBeta.ttf.fix             3             1          1033       257  Thin
RokkittVFBeta.ttf.fix             3             1          1033       258  ExtraLight
RokkittVFBeta.ttf.fix             3             1          1033       259  Light
RokkittVFBeta.ttf.fix             3             1          1033       260  Regular
RokkittVFBeta.ttf.fix             3             1          1033       261  Medium
RokkittVFBeta.ttf.fix             3             1          1033       262  SemiBold
RokkittVFBeta.ttf.fix             3             1          1033       263  Bold
RokkittVFBeta.ttf.fix             3             1          1033       264  ExtraBold
RokkittVFBeta.ttf.fix             3             1          1033       265  Black
```

**Pull request merged**
