### PR TITLE
Noto Sans Oriya: Version 2.002 added

### PR DESCRIPTION
**Pull request by simoncozens**
43b140d: [gftools-packager] Noto Sans Oriya: Version 2.002 added

* Noto Sans Oriya Version 2.002 taken from the upstream repo https://github.com/notofonts/oriya.git at commit https://github.com/notofonts/oriya/commit/.

### CODE REVIEW

**Comment by RosaWagner** [comment]
LGTM

**Comment by vv-monsalve** [comment]
@simoncozens There seems to be a similar issue related either to Oriya subjoined letter THA or U+035A (can't tell the difference), but compared to the Serif Oriya in this case it also looks misplaced.
Screen Shot 2022-08-05 at 9 51 29

And some different subjoined letters issues


Screen Shot 2022-08-05 at 9 40 38
Screen Shot 2022-08-05 at 9 37 50

**Comment by vv-monsalve** [comment]
@simoncozens have you got the opportunity to inspect this?

**Comment by simoncozens** [comment]
-> https://github.com/google/fonts/pull/5100

**Pull request merged**
