### PR TITLE
added jost V3.500

### PR DESCRIPTION
**Pull request by bghryct**
upstream at https://github.com/indestructible-type/Jost/tree/google
    at commit 9270931

### CODE REVIEW

**Comment by m4rc1e** [comment]
## Fontbakery report

Fontbakery version: 0.7.15

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>⚠ <b>WARN:</b> Is the command `ftxvalidator` (Apple Font Tool Suite) available?</summary>

* [com.google.fonts/check/ftxvalidator_is_available](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/universal.html#com.google.fonts/check/ftxvalidator_is_available)
<pre>--- Rationale ---

There&#x27;s no reasonable (and legal) way to run the command `ftxvalidator` of the
Apple Font Tool Suite on a non-macOS machine. I.e. on GNU+Linux or Windows etc.

If Font Bakery is not running on an OSX machine, the machine running Font
Bakery could access `ftxvalidator` on OSX, e.g. via ssh or a remote procedure
call (rpc).

There&#x27;s an ssh example implementation at:
https://github.com/googlefonts/fontbakery/blob/master/prebuilt/workarounds/ftxvalidator/ssh-implementation/ftxvalidator


</pre>

* ⚠ **WARN** ftxvalidator is not available.

</details>
<br>
</details>
<details>
<summary><b>[3] Jost[ital,wght].ttf</b></summary>
<details>
<summary>💔 <b>ERROR:</b> Check variable font instances have correct coordinate values</summary>

* [com.google.fonts/check/varfont_instance_coordinates](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/varfont_instance_coordinates)

* 💔 **ERROR** Failed with KeyError: 'ital'

</details>
<details>
<summary>⚠ <b>WARN:</b> METADATA.pb: Fontfamily is listed on Google Fonts API?</summary>

* [com.google.fonts/check/metadata/listed_on_gfonts](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/metadata/listed_on_gfonts)

* ⚠ **WARN** Family not found via Google Fonts API. [code: not-found]

</details>
<details>
<summary>⚠ <b>WARN:</b> Stricter unitsPerEm criteria for Google Fonts. </summary>

* [com.google.fonts/check/unitsperem_strict](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/unitsperem_strict)
<pre>--- Rationale ---

Even though the OpenType spec allows unitsPerEm to be any value between 16 and
16384, the Google Fonts project aims at a narrower set of reasonable values.

The spec suggests usage of powers of two in order to get some performance
improvements on legacy renderers, so those values are acceptable.

But value of 500 or 1000 are also acceptable, with the added benefit that it
makes upm math easier for designers, while the performance hit of not using a
power of two is most likely negligible nowadays.

Another acceptable value is 2000. Since TT outlines are all integers (no
floats), then instances in a VF suffer rounding compromises, and therefore a
1000 UPM is to small because it forces too many such compromises.

Therefore 2000 is a good &#x27;new VF standard&#x27;, because 2000 is a simple 2x
conversion from existing fonts drawn on a 1000 UPM, and anyone who knows what
10 units can do for 1000 UPM will know what 20 units does too.

Additionally, values above 2048 would result in filesize increases with not
much added benefit.


</pre>

* ⚠ **WARN** Even though unitsPerEm (1000) in this font is reasonable. It is strongly advised to consider changing it to 2000, since it will likely improve the quality of Variable Fonts by avoiding excessive rounding of coordinates on interpolations. [code: legacy-value]

</details>
<br>
</details>

### Summary

| 💔 ERROR | 🔥 FAIL | ⚠ WARN | 💤 SKIP | ℹ INFO | 🍞 PASS | 🔎 DEBUG |
|:-----:|:----:|:----:|:----:|:----:|:----:|:----:|
| 1 | 0 | 3 | 37 | 8 | 112 | 0 |
| 1% | 0% | 2% | 23% | 5% | 70% | 0% |

**Note:** The following loglevels were omitted in this report:
* **SKIP**
* **INFO**
* **PASS**
* **DEBUG**


## Diff images: [jost_qa.zip](http://35.238.63.0/media/5dfbd181-5fda-4b0e-9810-e9633201fead/jost_qa.zip)

**Comment by m4rc1e** [comment]
How does the ital axis work in this font?

Looking at the [ms spec](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital#axis-definition), it should have a range of 0-1. This font has 0-2.

**Comment by m4rc1e** [comment]
ping @bghryct

**Comment by bghryct** [comment]
@m4rc1e speaking with Owen about it.

**Comment by bghryct** [comment]
I've updated the branch that this is pr'ing from with the correct ital axis files and it's not appearing here. perhaps I'm missing something fundamental about github, but shouldn't it be automatic?

**Comment by davelab6** [comment]
Odd that https://github.com/google/fonts/commit/5a74ca023e84e069669adf6f5aaa5e5634acfcfe isn't showing up, indeed

**Comment by bghryct** [comment]
hmm 5a74ca0 is present and accounted for.

**Comment by bghryct** [comment]
@m4rc1e  good question let me check.

**Comment by m4rc1e** [comment]
I don't think we should be using the ital axis in this family. It makes more sense to use a slnt axis since it's adjusting the letterform slant. According to the spec:

> The Italic axis is distinct from the Slant axis ('slnt'). Fonts may use one or the other, depending on the nature of the design, 

If we somehow managed to morph the double story "a" into a single story then perhaps ital would be more fitting.

https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital

Personally, I feel the ital axis is just there to support VF families which consist of two fonts, one for italic, the other for roman.

**Comment by m4rc1e** [comment]
@bghryct Please can you update the Ital range so it's 0-1, https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_ital. We currently have 0-2

**Comment by bghryct** [comment]
5a74ca0 should have taken care of that. Is that not the case?

**Comment by driehuis** [comment]
5a74ca0 does not seem to update METADATA.pb to limit the ital axis range to 0..1. Maybe that causes the confusion?

**Comment by davelab6** [comment]
@m4rc1e will this need to have the italic split out?

**Comment by m4rc1e** [comment]
I've done an inter and just released it as is. We can split later if we have time. There are more important projects to focus on.

**Comment by davelab6** [comment]
Since this is a 'New VF' class family, I think its fine; we needed to split Roboto because its a 'VF Upgrade'

**Pull request merged**
