### PR TITLE
Recursive: Version 1.078 added

### PR DESCRIPTION
**Pull request by RosaWagner**
3f8723d: [gftools-packager] Recursive: Version 1.078 added

* Recursive Version 1.078 taken from the upstream repo https://github.com/arrowtype/recursive at commit https://github.com/arrowtype/recursive/commit/6db52f2b78ed9404496a1de7a39e8b3b7dbfaf3f.

 2c11974: [gftools-packager] ofl/recursive remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
@arrowtype can you provide a line for the update's description? Mostly because of the change of v-metrics for desktop users.

I know we validated the fvar instances, but I would like to validate with @m4rc1e if it is also okay if the stat fallbacks doesn't match perfectly the axis registry.

**Comment by arrowtype** [comment]
Thanks, @RosaWagner!

I'm happy to provide an update description. Where is the description for, and what formatting does it need (e.g. is it a commit message, or does it have a character limit)?

**Comment by RosaWagner** [comment]
We just need a small paragraph in description_us.html to warn people about what the update is about (for eg. "The font was updated in April 2021 to address printing and Linespacing issues for Mac desktop users. The glyphset was extended etc"). In case users see a difference when using the font, they have something which explains it the specimen page. 100-250 characters.

**Comment by arrowtype** [comment]
Awesome, thanks! I'll write that this afternoon and reply here.

**Comment by arrowtype** [comment]
Here’s my proposal for the update description:

> Update, April 2021: the Google Fonts release of Recursive has been updated to incorporate various changes from its initial release. This includes fixes that correct printing issues, ensure consistent default line heights between styles on macOS, improve the handling of combining accents, add localization features for several languages, and resolve various other earlier issues.

I figure this would make sense at the end of the description, like this:

```html
<p>
Recursive is typographic palette for UI & code. It draws inspiration from single-stroke casual, a style of brush writing used in signpainting that is stylistically flexible and warmly energetic. Recursive adapts this aesthetic basis into an extensive variable font family, designed to excel in digital interactive environments, including data-rich user interfaces, technical documentation, and code editors.
</p>
<p>
Recursive offers a lot more styles than you see here! To download the full Recursive Sans &amp; Mono family, learn more about its 5 variable axes, and to configure advanced Google Fonts URL embed code for access to Recursive’s full stylistic range, check out its website at:
</p>
<p>
<a href="https://www.recursive.design/">→ recursive.design</a>
</p>

<p>
The Recursive project is led by Arrow Type, a type foundry based in Brooklyn, NY, USA. To contribute, see its <a href="https://github.com/arrowtype/recursive">GitHub repo</a>.
</p>

<p>
Update, April 2021: the Google Fonts release of Recursive has been updated to incorporate various changes from its initial release. This includes fixes that correct printing issues, ensure consistent default line heights between styles on macOS, improve the handling of combining accents, add localization features for several languages, and resolve various other earlier issues.
</p>
```

I’m open to suggestions if others feel like that can be improved further.

**Comment by m4rc1e** [comment]
@arrowtype LGTM. I'll update your description and merge.

**Pull request merged**
