### PR TITLE
Radio Canada Big: Version 1.001 added



### PR DESCRIPTION
**Pull request by emmamarichal**
Taken from the upstream repo https://github.com/googlefonts/radiocanadadisplay at commit https://github.com/googlefonts/radiocanadadisplay/commit/9ac9cf87d0fbd85bce912535994e02614b1b525f.
## PR Checklist:

- [x] Family categorization tags collected from the type design team with the Categories Form
- [x] Minisite_url definition in the METADATA.pb file for commissioned projects
- [x] Primary_script definition in the METADATA.pb file for all projects that have a primary non-Latin based language support target
- [ ] Fontbakery checks are reviewed and failing checks are resolved in collaboration with the upstream font development team
- [ ] Diffenator2 regression checks for revisions on all projects that are currently in production
- [x] Designers bio info have to be present in the designer catalog (at least an issue should be opened for tracking this, if they are not) https://github.com/google/fonts/issues/7515
- [x] Check designers order in metadata.pb, since the first one of the list appears as “principal designer”
- [ ] Social media formatted visual assets for all new commissioned projects in the Drive directory, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet
- [ ] Social media content draft for all new commissioned projects in the Drive directory and Social Media tracker spreadsheet, communicate with the repository Maintainer so that they can push this content to the Social Media tracker spreadsheet

### CODE REVIEW

**Comment by emmamarichal** [comment]
💥 ERROR Familyname must be unique according to namecheck.fontdata.com
I think it's a bug, there is no font already called like this

**Comment by vv-monsalve** [comment]
> 💥 ERROR Familyname must be unique according to namecheck.fontdata.com
> I think it's a bug, there is no font already called like this

The `ERROR` log level result in FB is something related to the tool (not the fonts). For a check like this one that requires an internet connection, it sometimes results in an error when it's broken. It's only a matter to re-run the tool ;)

**Comment by vv-monsalve** [comment]
I've edited the Description a bit updating Big instead of Display.

Confirming: Would they like to update the repo name before launching?. The copyright field uses `https://github.com/googlefonts/radiocanadadisplay`

**Comment by emmamarichal** [comment]
@vv-monsalve, Yes, the repo kept the "display" name. I think it's okay to keep it!

**Pull request merged**
