### PR TITLE
Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added

### PR DESCRIPTION
**Pull request by vv-monsalve**
c1b1a7e: [gftools-packager] Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added

* Freeman Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] taken from the upstream repo https://github.com/rfuenzalida/Freeman at commit https://github.com/rfuenzalida/Freeman/commit/a6e7fa3c4af62d44578a26ac2956b84f718882a2.

### CODE REVIEW

**Comment by vv-monsalve** [comment]
Updated

## Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added

---
 2ab8c0c: [gftools-packager] Freeman: Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] added

* Freeman Version 1.000; ttfautohint (v1.8.4.7-5d5b);gftools[0.9.28] taken from the upstream repo https://github.com/rfuenzalida/Freeman at commit https://github.com/rfuenzalida/Freeman/commit/4e9403375ef9745cbacab7259e9c1c8a91903493.

**Comment by vv-monsalve** [comment]
This is the font that derived from Francoise One. To bear in mind in case Francoise One gets finally actually updated.

**Comment by vv-monsalve** [comment]
@RosaWagner Why the Manager Opinion label?

**Comment by RosaWagner** [comment]
Cause I didn't remember what we do with François update, and Dave didn't confirm, and Chris didn't know, and you were off work. Do you have info?

**Comment by vv-monsalve** [comment]
@rfuenzalida Could you please add a mention in the repo Readme.md file of what differs from François One?

**Comment by vv-monsalve** [comment]
Updated

**Pull request closed without merging**
