### PR TITLE
Fraunces: Version 1.000 added

### PR DESCRIPTION
**Pull request by arrowtype**
[partially a manual push due to issue in packager]

This is Fraunces after [some mastering work](https://github.com/arrowtype/Fraunces/issues/1).

It includes two variable fonts:
- Fraunces (the variable font, axes [SOFT,WONK,opsz,wght])
- Fraunces Italic (variable font, axes [SOFT,WONK,opsz,wght])

...and 108 static fonts, 6 weights w/ Roman & Italics in the following families:
- Fraunces 9pt [Sharp]
- Fraunces 9pt Soft
- Fraunces 9pt SuperSoft
- Fraunces 72pt [Sharp]
- Fraunces 72pt Soft
- Fraunces 72pt SuperSoft
- Fraunces 144pt [Sharp]
- Fraunces 144pt Soft
- Fraunces 144pt SuperSoft

It is possible/likely that a couple of style names may still need to be adjusted, pending agreement from @davelab6 & @sponcey:
- `SOFT` (Softness) Axis might be better named with alphabetic styles: https://github.com/google/fonts/issues/2760
- `WONK` (Wonky) axis should have the name "Wonky," the default of "Wonky" (elided) at `0` and a style of "NonWonky" at `0`: https://github.com/google/fonts/issues/2741
- `opsz` defaults to `9` unless we want to get clever and add 72pt sources (this would perhaps better live up to the spirit of the family as a display face, but would add scope & complexity to build, plus some filesize to the VFs)

I anticipate that there are a couple of FontBakery issues, but I am partially checking what the automated PR tests are like these days. Thanks!

### CODE REVIEW

**Comment by arrowtype** [comment]
One small thing I will tweak: the name `Sharp` should be elided in the PostScript & Full Names.

Otherwise, I do think this is good to go, and should definitely be fine for the sandbox.

**Comment by RosaWagner** [comment]
Sorry, I got the wrong PR number for the update to sandbox. Do you have other correction to bring before we review it ?

**Comment by arrowtype** [comment]
> Do you have other correction to bring before we review it ?

Just fixed it, and I’m now re-running the packager. Should be up in 5–10 minutes, pending my internet speed!

**Comment by arrowtype** [comment]
Okay, clearly I am doing something wrong with the packager, or I’m just misunderstanding it.

Anyway, I updated the variable font files and `METADATA.pb` (the static `Sharp` fonts already had correct PS & Full names). I added that to the same squashed commit, and force pushed it.

One question: should the `METADATA.pb` point to my mastering repo & commit, or is it important to PR & merge this into https://github.com/undercasetype/Fraunces before we merge it? I assume it doesn’t matter, as the description has the upstream repo link hardcoded in. But, let me know if I am incorrect.

**Comment by m4rc1e** [comment]
Everything looks good, apart from the Axis Value Names do not match the fallback names (without spaces) in our axis registry e.g "SuperSoft" should be "ExtraSoft"

**Comment by m4rc1e** [comment]
I see you've already posted that our Axis Reg should be improved, https://github.com/google/fonts/issues/2741. I'll take a look.

**Comment by arrowtype** [comment]
Thanks, Marc! I have also added an issue with proposed naming for the `SOFT` axis: https://github.com/google/fonts/issues/2760

**Comment by arrowtype** [comment]
Update: made PRs at https://github.com/google/fonts/pull/2764 and https://github.com/google/fonts/pull/2765 for `SOFT` and `WONK` axis updates. I think Dave has separately emailed the team about it.

**Comment by m4rc1e** [comment]
I'm going to keep this open until the axis PRs have been sorted.

**Comment by arrowtype** [comment]
Updates:

- @sponcey ran the build scripts in the official repo to get the correct Git hash in the name ID 5 version string.
- I updated the `upstream.yaml` to point to `undercasetype/Fraunces` `master`, which now has these fonts
- I used the gf-packager to grab the fonts, but ran into some issues getting it to push (my local google/fonts repo was in another branch), so I ended up committing & pushing manually. However, I first checked to verify that the correct fonts (based on their version strings) were in that update.

But, now that I look at the files, I see that this is lacking the description HTML, metadata pb, and OFL. I will revert to using a shell script for these updates, as I am somehow mis-using the packager. Another update coming shortly...

**Comment by arrowtype** [comment]
Closing in favor of https://github.com/google/fonts/pull/2776, which uses a shell script I am more familiar with than the gftools packager, and which includes the files which are missing here.

**Pull request closed without merging**
