### PR TITLE
Outfit: Version 1.000 added

### PR DESCRIPTION
**Pull request by aaronbell**
9ce01eb: [gftools-packager] Outfit: Version 1.000 added

* Outfit Version 1.000 taken from the upstream repo https://github.com/Outfitio/Outfit-Fonts at commit https://github.com/Outfitio/Outfit-Fonts/commit/dcc810855e997afd5de73215566aebbe0f13506d.

 0689152: [gftools-packager] ofl/outfit remove METADATA "source".  google/fonts#2587

### CODE REVIEW

**Comment by RosaWagner** [comment]
I'll ask for confirmation, but I think we need to remove and branding ligatures
Capture d’écran 2021-09-29 à 12 17 48

**Comment by aaronbell** [comment]
@RosaWagner https://github.com/Outfitio/Outfit-Fonts/issues/2

Dave has already approved them.

**Comment by samueljim** [comment]
love this

**Comment by andyfitz** [comment]
Can't wait champions, thank you!

**Pull request merged**
